### ISSUE TITLE
Italian translation Bsod 

### ISSUE THREAD

**Issue by MicheleC11** [supermerill/SuperSlicer#1004]
### Version
2.3.55.5 Italian

### Operating system type + version
MacOS 10.15.7

### 3D printer brand + version
_Artillery genius_

### Behavior
* _SuperSlicer crashes when I access: filament settings -> cooling_
* _I expect you to fix the problem and let me access the settings_

**Comment by supermerill** [comment]
There's a problem in the italian translation.

**Comment by supermerill** [comment]
duplicate of #1003

**Comment by boromyr** [comment]
[Problem solved](https://github.com/supermerill/SuperSlicer/issues/1128)
