### ISSUE TITLE
Calibration -> Temp calibration generates wrong temps for first segment

### ISSUE THREAD

**Issue by azaz44** [supermerill/SuperSlicer#1007]
### Version
2.3.55.5

### Operating system type + version
Win10

### Steps to reproduce

1. Have filament with following temp settings: first layer: 240; other layers 230
2. Use Calibration -> Filament temp... to generate a tower, using 2 up and 2 dn, with 10 deg step
3. Expectation would be to have segments of 250, 240, 230, 220, 210
4. However results are 230, 240, 230, 220, 210
5. Which is because temp tower has g-code for first layer, but 2nd layer changes it to 230..

**Comment by foreachthing** [comment]
The fix solved the issue on my end. Thanks!
