### ISSUE TITLE
Variable Layer Height doesn't always work

### ISSUE THREAD

**Issue by mrkoz** [supermerill/SuperSlicer#1010]
### Behavior
* in some cases, it wont take into account the variable layer height until i resize the part.

### Steps:
1. Generate a 40mm voron test cube
2. set variable layer height on with defaults
3. click adaptive once
4. click slice preview
5.  -- layers not varied --
6. back out of preview and resize the voron cube to 99.9%
7. set varliable layer height on with defaults
8. click adaptive once
9. click slice 
10.  -- layers varied --

pre-slice at 100%
![image](https://user-images.githubusercontent.com/4994379/111061133-e3490700-84f5-11eb-8979-c349402de4f3.png)

sliced at 100% with dynamic layers
![image](https://user-images.githubusercontent.com/4994379/111061150-f9ef5e00-84f5-11eb-8ed5-87fd911a1b28.png)

resized cube to 99.9% then re-ran dynamic layers
![image](https://user-images.githubusercontent.com/4994379/111061169-18555980-84f6-11eb-8b17-793294d5f6d0.png)

Project file:
[voron_design_cube_v6.zip](https://github.com/supermerill/SuperSlicer/files/6136235/voron_design_cube_v6.zip)

**Comment by Pavulon87** [comment]
It's a bit weird, but I can confirm it.
However, this is not a problem for the 40mm cube(box shape).

**Comment by mrkoz** [comment]
> 
> 
> It's a bit weird, but I can confirm it.
> However, this is not a problem for the 40mm cube(box shape).

I have had this on a few other files, even a resize of 0.01% corrects it.

**Comment by TheAndr0id** [comment]
> > It's a bit weird, but I can confirm it.
> > However, this is not a problem for the 40mm cube(box shape).
> 
> I have had this on a few other files, even a resize of 0.01% corrects it.

I can confirm this as well.  I have something that needs to be printed at a specific height that is not a multiple of layer height.  I looked at variable layer height to use the top few layers to get closer to the height needed and it did nothing.  I scaled the item to 100.01 and now the variable layer height works.  This is a flat item (coin) with little to no surface detail.

I am using version 2.2.53.4 under Linux x64 (build from source).

**Comment by supermerill** [comment]
an dyou have the `printer->general -> enable variable layer height feature` enabled?

**Comment by supermerill** [comment]
Can't replicate (win10 also), with latest nightly

i opened your porject file
clic on varaible alyers,
clic on adaptative
clic on slice
=> i have some thin layers.

**Comment by TheAndr0id** [comment]
Thank you @supermerill for looking into this, I'm looking forward to the next release!

**Comment by mrkoz** [comment]
> 
> 
> and you have the settgin `printer->general -> enable variable layer height feature` enabled?

Yes, it works as expected 99% of the time, just for some files (potentially height based) it doesn't do the variable layer height part.

Ps @supermerill thank you for all your work, this is a brilliant fork!

**Comment by navr32** [comment]
Hello !
Excuse me I have update to 2.3.57.4 and the variable layer height is always Grey ??? i am unable to activate it again ?
I have try scale or others but nothing.
I am on linux manjaro so Arch distrib clone..
Someone have any idea or how troubleshoot ? many thanks.
Have a nice days.

**Comment by navr32** [comment]
Oh excuse me for this bad post... So i haven't see the option in "Printer settings"  "General" 
And the last line on bottom "Enable variable layer height feature" was disable..so just check it and it's ok..all works again.
Many thanks again to all enthusiastic dev and others.
