### ISSUE TITLE
Perimeter offset

### ISSUE THREAD

**Issue by Jack77777777** [supermerill/SuperSlicer#1012]
See attached pic of a simple box. I have a "perimeter offset" at height of top layer from the ground of model. Could this be caused by "only one perimeter on top layer", too much cooling, monotonic too infill or is it a bug. 

I am using SS 2.3.55.5 on Win10 64bit. 

![image](https://user-images.githubusercontent.com/64719909/111062574-03eb6f80-84aa-11eb-9e26-1698290668a7.jpeg)

**Comment by supermerill** [comment]
most probably, it's because you have a long printing time at this layer, so it has much more time to cool.

Can't say much more wthout the project file.

**Comment by Jack77777777** [comment]
I had auto cooling enabled and it could be that the fan speed up for the above layers due to fan_below_layer_time 60s. Testing with same speed for all layers now.

**Comment by Jack77777777** [comment]
Seems my isues are fixed. Thanks @supermerill
