### ISSUE TITLE
Bridge Infill - not getting the cooling it deserves?

### ISSUE THREAD

**Issue by thierryzoller** [supermerill/SuperSlicer#1014]
### Version
2.3.55

### Operating system type + version
Windows

In my object the majority of bridges get the right fanspeed, however there are at least two, that don't. Is this expected? It's a 90° hanging object so I'd kind of expect the increased fan speed.

![image](https://user-images.githubusercontent.com/958490/111185262-1355e000-85b2-11eb-8cef-25f948583724.png)

**Comment by thierryzoller** [comment]
[Form Giesen Lautsprecher.zip](https://github.com/supermerill/SuperSlicer/files/6142872/Form.Giesen.Lautsprecher.zip)

**Comment by The-EG** [comment]
I've been seeing this same issue. It appears that 'bridge infill' isn't getting the 'bridges fan speed' setting applied if they have perimeters on all sides or something.

Pretty easy to reproduce:
1. Add shape-> Cube (20x20x20)
2. Slice it with a fan settings of 50% default speed, 50% max fan speed, 100% bridges speed.
3. Observe the first top solid layer has 50% fan speed, not 100%:
![image](https://user-images.githubusercontent.com/7342077/111373627-8757bd00-8672-11eb-956c-485ddd4824f5.png)
![image](https://user-images.githubusercontent.com/7342077/111373674-963e6f80-8672-11eb-9e29-7bd2e5a75751.png)

Not the case in PrusaSlicer (2.3, eef800b5c4215abc9226cebae5733227190d9fd8):
![image](https://user-images.githubusercontent.com/7342077/111373956-eae1ea80-8672-11eb-950e-79c70cc7d8aa.png)

**Comment by supermerill** [comment]
I think it's a "fan speed-up" bug. It will be rewrote on the next makjor version.
Deactivate the option, in printer-general ( set it to 1)

**Comment by thierryzoller** [comment]
Setting it to 1 did not change the problem

**Comment by supermerill** [comment]
sorry, it's a typo, it's 0 to deactivate it.

**Comment by The-EG** [comment]
This appears to be working in master now.

**Comment by thierryzoller** [comment]
Still seem to have the same (similar issue) with the latest build 2.3.56.7. Bridge infill gets default 70% instead of 100%

![image](https://user-images.githubusercontent.com/958490/125193634-ba3f4580-e24d-11eb-8662-55eb4dc35265.png)

**Comment by thierryzoller** [comment]
Was Fan delay of 0.5s. My question then is : is why doesn't it start 0.5seconds **_earlier_** rather than later ? It seems to not speed up with 0.5s delay

![image](https://user-images.githubusercontent.com/958490/125193697-07bbb280-e24e-11eb-8554-3a87a7686271.png)

**Comment by supermerill** [comment]
It's buggy, i'm rewriting the gcode writer, and after that it will be easier to make something relibale.
