### ISSUE TITLE
Paint on seam not working as expected

### ISSUE THREAD

**Issue by ogland** [supermerill/SuperSlicer#1015]
### Version
Version 2.3.55

### Operating system type + version
Windows, version 10

### 3D printer brand / version + firmware version (if known)
Klipper

### Behavior
Seam not ending up where painted on seam
Paint seam in inner corners, slice
Expecting seam to end up where it's painted
![image](https://user-images.githubusercontent.com/37978198/111277959-5018ea00-8639-11eb-8810-47520033e063.png)

Not ending up where it's painted
![image](https://user-images.githubusercontent.com/37978198/111277985-57d88e80-8639-11eb-90e1-b8105cbe6917.png)

#### Project File (.3MF) where problem occurs
Can't share this model

**Comment by ogland** [comment]
Ok so on closer inspection, they are indeed where they are supposed to be, but not visible through.
![image](https://user-images.githubusercontent.com/37978198/111278403-c9184180-8639-11eb-8bd9-e17417b8deb1.png)

**Comment by thierryzoller** [comment]
Seems like it works?
