### ISSUE TITLE
Feature request: print restart at the point closest to where the previous layer ends

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#1017]
It would be interesting, as is present in the other slicers, to have the possibility to define the X and Y coordinates for the restart of the perimeters at layer change.
Unfortunately, the four options present now allow starting from angles but the STL does not necessarily have corners, so an X and Y coordinate would be useful.
It would also be interesting to have the restart at the point closest to where the previous layer ends.

**Comment by supermerill** [comment]
use the seam painter.

**Comment by robustini** [comment]
Great, it works very well.
I changed my feature request.

**Comment by supermerill** [comment]
print settign -> perimeter -> seam position.
Then choose aligned
