### ISSUE TITLE
[Feature request] Move slicer preview to tab bar for "old regular layout with tab bar"

### ISSUE THREAD

**Issue by JohanAR** [supermerill/SuperSlicer#1020]
I think the preview would be more accessible if it was a top level tab, rather than as a sub-view of the plater tab.

The bottom left 3d editor view / preview buttons make sense in the new layout without tabs, but for the regular layout it feels like a weird mixture of different ideas

**Comment by supermerill** [comment]
and also the return of the "sliced but not gcode" preview, which is currently only accessible if we sliced to gcode and then modify a gcode-only setting.

**Comment by supermerill** [comment]
I forgot to link it to the commit 80bee28b84781030e1547519d1bdbac9e368e842

you can test it on the lastest nightly build (action menu)
