### ISSUE TITLE
Polyholes converts hexagon hole into round hole

### ISSUE THREAD

**Issue by jesterhead82** [supermerill/SuperSlicer#1026]
### Version
Nightly as of 21.03.2021, happens also with 2.3.55

### Operating system type + version
Win10

### 3D printer brand / version + firmware version (if known)
CR10, Marlin 2.0xx

### Behavior
Enabling Polyholes converts hexagon hole into round hole
![image](https://user-images.githubusercontent.com/11690785/111906121-56e79880-8a4f-11eb-9eec-1a73656252b2.png)
![image](https://user-images.githubusercontent.com/11690785/111906128-61099700-8a4f-11eb-843a-adf876ebd0cb.png)

#### Project File (.3MF) where problem occurs

[bltouch_support_holder_34.59.3mf.zip](https://github.com/supermerill/SuperSlicer/files/6177477/bltouch_support_holder_34.59.3mf.zip)

**Comment by supermerill** [comment]
Lol, i heven't though of it.
IT detect your hole as a very coarse round hole, makes sense.
I have to add a threshold. maybe I can accept a hole as round only if it has at least 9 lines?
