### ISSUE TITLE
Notify of prusaslicer update

### ISSUE THREAD

**Issue by Liger0** [supermerill/SuperSlicer#1028]
### Version
2.2.53

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
_What 3D printer brand / version are you printing on, is it a stock model or did you modify the printer, what firmware is running on your printer, version of the firmware #s_

### Behavior
If a prusa slicer update happens and the current superslicer version isn't based on it, you get a prusa slicer download notify of prusa slicer download and changelog.

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_

**Comment by supermerill** [comment]
I though I had removed them. Maybe it's only removed since the 2.3 ... Have to double-check.
