### ISSUE TITLE
Preset bundle 'Creality' version not voind in index: 0.1.7

### ISSUE THREAD

**Issue by cbc02009** [supermerill/SuperSlicer#1030]
### Version
2.3.55.5

### Operating system type + version
Windows 10 Pro 20H2

### 3D printer brand / version + firmware version (if known)
Voron 2.4 and Creality Ender3 pro, both running latest version of Klipper

### Behavior
On program startup I always get the following error:
![image](https://user-images.githubusercontent.com/39525900/112143569-70ebbd00-8bae-11eb-8fc8-97d6d9e64973.png)

Everything works fine, but nothing I do stops the message from popping up again at startup.

This started after I added my ender 3 to super slicer.

Definitely not a high priority issue since everything works fine, but it would be nice if it would go away once and for all.

**Comment by supermerill** [comment]
I think it's quirk that comes from a change of version numbering.
You have to delete the creality.idx that is on your setting directory.
should be in C:\Users\myname\AppData\Roaming\SuperSlicer\cache

**Comment by cbc02009** [comment]
> 
> 
> I think it's a quirk that comes from a change of version numbering.
> You have to delete the creality.idx that is on your setting directory.
> should be in C:\Users\myname\AppData\Roaming\SuperSlicer\cache

That doesn't seem to have fixed it. The file was in SuperSlicer-alpha, if that makes any difference.

**Comment by supermerill** [comment]
mmm... maybe it contains also an old creality.ini in vendor. Can you replace it by the one that is in superslicer/resources/profiles?

**Comment by cbc02009** [comment]
That fixed it. Thanks!
