### ISSUE TITLE
One Perimiter on Top Surface adds extra lines...

### ISSUE THREAD

**Issue by LaserBee** [supermerill/SuperSlicer#1042]
### Version
2.3.55
### Operating system type + version
Win 10

Changing to "One perimiter on top surface" results in some extra lines. See the two attached photos, one with the feature enabled, one without... 
![with](https://user-images.githubusercontent.com/36974632/112758090-74cf7300-8fe4-11eb-8cb9-2f62597587e9.png)
![without](https://user-images.githubusercontent.com/36974632/112758097-7a2cbd80-8fe4-11eb-82c2-dc2b26a8d13f.png)

I can't attach the STL, or I would!

**Comment by neophyl** [comment]
Known problems with that function in the newer versions.  Just search.

FYI- to attach files they need to be zipped into archives (zip file).  The preferred upload is actually your saved project file (.3mf) as that also contains all your sliced settings and modifiers etc if any as well as the model.  The model on their own are of limited use in duplicating issues.

**Comment by supermerill** [comment]
Try with 0 in "One Perimeter on Top Surface" -> "minimum width"
