### ISSUE TITLE
The first tab of the new GUI should be named 3D view

### ISSUE THREAD

**Issue by liftbag** [supermerill/SuperSlicer#1046]
### Version
_SuperSlicer 2.3.55.5 Commit 80bee28

### Operating system type + version
_macOS Big Sur 11.2.2_

### Behavior
Shouldn't the first tab of the new GUI be named 3D editor?

<img width="1520" alt="Schermata 2021-03-29 alle 11 50 56" src="https://user-images.githubusercontent.com/14921654/112821437-ff68ae80-9086-11eb-9890-0e5f06a21ac9.png">

**Comment by JohanAR** [comment]
The first tab is supposed to be called "3D view" and the second "Sliced preview", which they do on Linux (and probably on Windows which I believe merill is using for development) so this could be a Mac specific bug. Though on Linux it's impossible to switch between the new tabs after slicing a model, does this happen on Mac too?

**Comment by qwewer0** [comment]
Looks good on my end. (Windows)
![Screenshot 2021-03-29 131523](https://user-images.githubusercontent.com/57561110/112829072-e1a04700-9090-11eb-8419-79be03fd1f33.png)

**Comment by liftbag** [comment]
> The first tab is supposed to be called "3D view" and the second "Sliced preview", which they do on Linux (and probably on Windows which I believe merill is using for development) so this could be a Mac specific bug. Though on Linux it's impossible to switch between the new tabs after slicing a model, does this happen on Mac too?

No, in the version related to this issue, switching between tabs is possible on the macOS version.
The only flaw, apart from the name of the tabs, is that after slicing the g-code view is displayed in the 3D view tab.
<img width="1303" alt="Schermata 2021-03-31 alle 12 03 54" src="https://user-images.githubusercontent.com/14921654/113127598-3b337d80-9219-11eb-9200-7b6a532f5f60.png">

**Comment by supermerill** [comment]
so
the old version
 - works on windows
 - can't switch tab on linux
 - can switch tab on macos but the name is the same on each tab and the gcode preview is on the first tab
the new version
 - works on windows
 - works on linux
 - can't switch tab on macos
that is right?

**Comment by liftbag** [comment]
> that is right?

Exactly

**Comment by JohanAR** [comment]
I might add that I compiled my own superslicer, in case there were any new commits that came in after nightly was built

**Comment by liftbag** [comment]
> can you repeat the process and paste the log here?
> thx.

How can I view that log?

**Comment by supermerill** [comment]
If you launch the software from a command line, you should see something in the terminal. At the startup, if should write 
```
create settings  print.ui
create settings  filament.ui
create settings  sla_print.ui
create settings  sla_material.ui
create settings  printer_fff.ui
create settings  extruder.ui
```

**Comment by liftbag** [comment]
> If you launch the software from a command line, you should see something in the terminal. At the startup, if should write
> 
> ```
> create settings  print.ui
> create settings  filament.ui
> create settings  sla_print.ui
> create settings  sla_material.ui
> create settings  printer_fff.ui
> create settings  extruder.ui
> ```

macOS terminal does not produce any log of the operations that take place in the slicer. Maybe it should be started with some additional parameters?

<img width="777" alt="Schermata 2021-04-01 alle 19 25 48" src="https://user-images.githubusercontent.com/14921654/113331515-5a690280-9320-11eb-803a-a9db1f9f673e.png">

**Comment by liftbag** [comment]
Ok, this is the log after launching the program with the parameter --loglevel 5.
It refers to Commit b446079 nightly.

[Saved terminal Output.zip](https://github.com/supermerill/SuperSlicer/files/6245388/Saved.terminal.Output.zip)

**Comment by supermerill** [comment]
Sorry, i wasn't clear enough (and the build failed anway).
Can you test the commit 85b75a, or the compiled version from https://github.com/supermerill/SuperSlicer/actions/runs/709474189
?

**Comment by liftbag** [comment]
> Sorry, i wasn't clear enough (and the build failed anway).
> Can you test the commit 85b75a (it's in the `CI` branch), or the compiled version from https://github.com/supermerill/SuperSlicer/actions/runs/709474189
> ?

The program exits on opening with the following error.

<img width="1255" alt="Schermata 2021-04-01 alle 22 27 15" src="https://user-images.githubusercontent.com/14921654/113350687-14209d00-933a-11eb-8fcc-937c2568df67.png">

**Comment by supermerill** [comment]
Damn! of course!
can you copy/paste /rename `superslicer/resources/cog.svg` to `superslicer/resources/printercog.svg` and `superslicer/resources/spool_cog.svg` (or pull 446fcc or wait the new build)
and retry?

**Comment by liftbag** [comment]
> Damn! of course!
> can you copy/paste /rename `superslicer/resources/cog.svg` to `superslicer/resources/printercog.svg` and `superslicer/resources/spool_cog.svg` (or pull 446fcc or wait the new build)
> and retry?

The new build seems to work fine.
Here is the output from the terminal.

[Saved Terminal Output.zip](https://github.com/supermerill/SuperSlicer/files/6250819/Saved.Terminal.Output.zip)

**Comment by supermerill** [comment]
mmm notyhing wrong in this log... i wonder where comes the problem.

Can you try the next build (43f60cc) ? Hoping it will select the right tab this time.

**Comment by liftbag** [comment]
> mmm notyhing wrong in this log... i wonder where comes the problem.
> 
> Can you try the next build ([43f60cc](https://github.com/supermerill/SuperSlicer/commit/43f60cc2800914251b17cc5e4ba8f9f0e59192f7)) ? Hoping it will select the right tab this time.
> 
> if i can have some screenshot to better understand what's going on, this would be nice.

Sorry, maybe my message wasn't very clear. The build 43f60cc works as intended, without the problems mentioned in the previous messages. The log comes from that version.
If you need it as a debug, I can re-download the problematic version and produce the log with the sequence of operations you asked for.

**Comment by liftbag** [comment]
Meanwhile I opened the latest build from the CI branch (93e5584). There is only the plater tab, like in release, but the icons for switching from 3D view to g-code view have disappeared.

<img width="1458" alt="Schermata 2021-04-05 alle 09 15 17" src="https://user-images.githubusercontent.com/14921654/113549002-e0bb6800-95f0-11eb-9494-c27446f564bf.png">

**Comment by supermerill** [comment]
right, bad copy-paste, fixed.
