### ISSUE TITLE
[FR] Option to have [filament_colour] parameter without trailing "#"

### ISSUE THREAD

**Issue by TheWarolf** [supermerill/SuperSlicer#1047]
### FR description

When calling the parameter [filament_colour] defined in filament tab, actual slicer behaviour is to output an hexa string like this: "#8080FF". 
If used as an argument for a klipper macro (Jinja2/python syntax), the trailing "#" is considered as a comment symbol, thus leading to the impossibility to actually use the parameter.

It would be great to add an option to to have the [filament_colour] parameter as a string without the trailing "#", or even better directly in rgb format.

**Comment by supermerill** [comment]
in next nightly, try with [filament_colour_int]
