### ISSUE TITLE
Weird gap infill behaviour

### ISSUE THREAD

**Issue by Phil1988** [supermerill/SuperSlicer#1049]
### Version
2.3.55.5

### Operating system type + version
Windows 10

### Behavior
I have a part where the infill is a bit weird.
When the part gets smaller, the latest SuperSlicer v2.3.55.5 does make these rectilinear infill patterns, while v2.2.53.3 made a gap infill.
I compared the settings and have no idea how to solve it.

Here is a screenshot:
v2.3.55.5
![00](https://user-images.githubusercontent.com/6054234/112946528-e79c3380-9135-11eb-832b-1189484ce1bc.PNG)

v2.2.53.3
![01](https://user-images.githubusercontent.com/6054234/112946534-eb2fba80-9135-11eb-81b0-e7a20045f88a.PNG)

Additionally on a smaller part, it even makes a layer, where no infill at all is placed (hard to see, but the purple recilinear infill is from the layer before):
v2.3.55.5
![02](https://user-images.githubusercontent.com/6054234/112946628-0dc1d380-9136-11eb-97be-17484589d6af.PNG)

on v2.2.53.3 it lookes like this:
![03](https://user-images.githubusercontent.com/6054234/112946675-1b775900-9136-11eb-81dc-6952034325be.PNG)

#### Project File (.3MF) where problem occurs for both slicers
[SuperSlicer_comparison.zip](https://github.com/supermerill/SuperSlicer/files/6227001/SuperSlicer_comparison.zip)

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/113036114-29f45d80-9194-11eb-9139-210ee6f618af.png)

maybe already fixed

**Comment by Phil1988** [comment]
Well this from you looks good...

Mine still looks like this:
![grafik](https://user-images.githubusercontent.com/6054234/113113807-f6a0e580-920a-11eb-9322-a1777bffad85.png)

Im using 2.3.55.5
Any ideas?

**Comment by supermerill** [comment]
You can try to download the latest nightly to be sure we have the same version and load the project file you sent me, to be sure we load the same thing.

**Comment by Phil1988** [comment]
I tried to start the nighly on 3 different Win 10 x64 PCs without success.

I downloaded the nightly_win64 from here:
https://github.com/supermerill/SuperSlicer/actions/runs/715598743

Anything I am doing wrong?

**Comment by neophyl** [comment]
I had the same problem with the latest nightly.  I found that running the "@SLIC3R_APP_CMD@.exe" started it though.  The other normal exe just result in nothing opening.

**Comment by Phil1988** [comment]
thanks @neophyl 
I was able to open it that way, but the opened 3mf project did not show anything in the 3D, Sliced or Gcode preview.
![grafik](https://user-images.githubusercontent.com/6054234/113848548-e489ee80-9798-11eb-8abd-687c6ae85324.png)

so if I am doing anything wrong or I should check, please let me know @supermerill 

Thanks :)

**Comment by supermerill** [comment]
oups. Naming bug.

**Comment by Phil1988** [comment]
Hi @supermerill 
Will there be a new release without this bug anytime soon?

I know I can use the nightly, but I would rather use a stable. 
Mainly because the nightly is still a bit buggy like switching automatically to the layer view and sometimes is slower on respond.

**Comment by supermerill** [comment]
I have to finish fixing the bugs.
