### ISSUE TITLE
Cannot switch to preview tabs

### ISSUE THREAD

**Issue by clinta** [supermerill/SuperSlicer#1051]
### Version
2.3.55.5

### Operating system type + version
Arch Linux

### Behavior
Preview tab buttons do not work. The only way to select the preview windows is through the window menu.

https://user-images.githubusercontent.com/3177437/113007073-e4a83f80-9143-11eb-9be1-f6dbf8ac5b70.mp4

**Comment by supermerill** [comment]
fixed in the latest master
