### ISSUE TITLE
Retraction when Tool is disabled -> extra length on restart -> setting is not working

### ISSUE THREAD

**Issue by ReneJurack** [supermerill/SuperSlicer#1052]
### Version
_2.3.55_

### Operating system type + version
_osX 11.2.3_

### 3D printer brand / version + firmware version (if known)
_E3D Toolchanger - RepRapFirmware for Duet 2 WiFi/Ethernet 2.05.1 (2020-02-09b1)_

### Behavior
* Retraction when Tool is disabled -> extra length on restart -> setting has no effect in generated gcode

No matter what values I put in there, I can't find them in the generated gcode

<img width="512" alt="Bildschirmfoto 2021-03-30 um 22 51 42" src="https://user-images.githubusercontent.com/24276215/113055131-85314a80-91aa-11eb-82ca-d38d9cdfa31b.png">

E.G. If I put a value like "123456" in the input-field for T0, I can find it 5 times in the generated gcode. But there are 141 pickups of this Tool (searching for T0 results in 141 hits)...

<img width="468" alt="Bildschirmfoto 2021-03-30 um 22 47 41" src="https://user-images.githubusercontent.com/24276215/113054656-fb817d00-91a9-11eb-9c71-d85e0245424d.png">

<img width="560" alt="Bildschirmfoto 2021-03-30 um 22 48 21" src="https://user-images.githubusercontent.com/24276215/113054701-09cf9900-91aa-11eb-9ed4-7739de4f6d0d.png">

#### Project File (.3MF) where problem occurs
[3mf and gcode.zip](https://github.com/supermerill/SuperSlicer/files/6232087/3mf.and.gcode.zip)

**Comment by laviRZ** [comment]
@supermerill This is still not working for me. I change the `retract_length_toolchange` setting and it doesn't affect the gcode. Attaching the project file and resulted gcode.
[pikachu_dual_details.zip](https://github.com/supermerill/SuperSlicer/files/9332014/pikachu_dual_details.zip)
.

**Comment by Ch4rlesB** [comment]
Still not working. Basically making superslicer UNUSABLE for IDEX as the toolheads just ooze on the side...
