### ISSUE TITLE
Improve the printing time when "with sheath around the support" is selected 

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#1053]
### Version
2.3.55.5

### Operating system type + version
Windows 10 Pro

### 3D printer brand / version + firmware version (if known)
Delta custom

### Behavior
When there are several supports, I mean separate on the bed, and the "with sheath around the support" option is selected, all the sheaths are printed first and then the supports, this involves countless movements of the nozzle around the print.
It would be more logical and faster if both were printed at the same time, not all sheaths first and then supports.

**Comment by supermerill** [comment]
Do you have a simple project that show the problem?

**Comment by robustini** [comment]
[FUSOLIERA_2.zip](https://github.com/supermerill/SuperSlicer/files/6254057/FUSOLIERA_2.zip)

**Comment by supermerill** [comment]
Can you try the nightly? I reworked that code, tell me if it's enough.

**Comment by robustini** [comment]
> Can you try the nightly? I reworked that code, tell me if it's enough.


https://github.com/supermerill/SuperSlicer/actions/runs/2025451330
