### ISSUE TITLE
G-code preview options not displaying correctly on Mac OS

### ISSUE THREAD

**Issue by timj79** [supermerill/SuperSlicer#1054]
On the latest nightly build for Mac OS, the view option aren't displaying correctly. Only the first letter is displayed instead of the description as shown in the screen shot.

![A29E0750-AFAE-4E5A-87FD-6884770F07A7](https://user-images.githubusercontent.com/45906353/113490623-3d206980-94c3-11eb-85a8-4454d7bf78c8.jpeg)

**Comment by supermerill** [comment]
It only does that if the window is too small or even if maximize on a 4k screen?

**Comment by timj79** [comment]
It does it both when minimised and maximised. This is on the retina display on a M1 MacBook Pro. 
Feature types is still displaying though

![Image 04-04-2021 at 09 55](https://user-images.githubusercontent.com/45906353/113503997-434b3000-952d-11eb-8f24-5ba2f10265db.jpg)

![Image 04-04-2021 at 10 04](https://user-images.githubusercontent.com/45906353/113504018-61b12b80-952d-11eb-8af7-dd6a1d722220.jpg)

I've also noticed the 30% bridge test is doing something strange on the latest version

![Image 04-04-2021 at 10 06](https://user-images.githubusercontent.com/45906353/113504096-bbb1f100-952d-11eb-9829-d637d91927d5.jpg)

**Comment by supermerill** [comment]
can't reproduce on latest beta version.
