### ISSUE TITLE
wrong slicing preset

### ISSUE THREAD

**Issue by DrDaveone** [supermerill/SuperSlicer#1060]
### Version
2.3.55

### Operating system type + version
Windows 10.0.19041.867 

### 3D printer brand / version + firmware version (if known)
Creality Ender 3 Pro - klipper

### Behavior
slicing preset "0.8mm HIGHDETAIL @CREALITY" has wrong name, because layer height = 0.08mm

#### Project File (.3MF) where problem occurs
[preset issue.zip](https://github.com/supermerill/SuperSlicer/files/6254927/preset.issue.zip)

**Comment by Pavulon87** [comment]
Fixed 3 days ago in 40c4b94da25516ed7afb414e0e59f6b491d5debc
