### ISSUE TITLE
[Feature] Improve "avoid crossing perimeters" option

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#1061]
### Version
2.3.55.5

### Operating system type + version
Windows 10 Pro

### 3D printer brand / version + firmware version (if known)
Delta custom

### Behavior
I notice that when this option is activated the nozzle moves correctly inside the print, but often passes too close to the external perimeters.
This certainly saves time on movement, but in my opinion it is incorrect because in the final result artifacts are noticed if there is a minimum of oozing.
It would be useful to have an option where you can declare how much must be inside the printed area, in mm or in%.
In the image you can see that it passes over that corner, but often in this print it also passes over the long flat front edge.
With this option enabled it should move inside the printed area at least a few mm, not on the outer edges.
The 3mf is the same posted in the issue #1053.

![immagine](https://user-images.githubusercontent.com/3864712/113548652-33485480-95f0-11eb-8e93-485726f59f98.png)

**Comment by robustini** [comment]
Here it is largely evident. 
The red line is how it should be about to do, I hope the concept is clear.

![Cattura](https://user-images.githubusercontent.com/3864712/113549654-13199500-95f2-11eb-8123-f1a322d42f42.JPG)

**Comment by Pavulon87** [comment]
Stay inside the infill could be good too.

**Comment by robustini** [comment]
Apparently Prusa Slicer has the same problem, so it came from there. 

https://github.com/prusa3d/PrusaSlicer/issues/5689
