### ISSUE TITLE
After any setting change view changes to 3d view - Mac OS, nightly build 

### ISSUE THREAD

**Issue by timj79** [supermerill/SuperSlicer#1062]
### Operating system type + version
SuperSlicer
Version:   2.3.55.5
Build:     SuperSlicer_2.3.55.5

Operating System:    Macintosh
System Architecture: 64 bit
System Version:      macOS Big Sur Version 11.2.3 (Build 20D91)
Total RAM size [MB]: 8,590MB
OpenGL installation
GL version:   2.1 Metal - 71.0.7
Vendor:       Apple
Renderer:     Apple M1
GLSL version: 1.20
Installed extensions:

### 3D printer brand / version + firmware version (if known)

Klipper

### Behavior

On the latest nightly build, any time any setting is changed in print settings, filament settings or printer settings as soon as soon as you click off of the input field you get returned back to the 3d view

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_
[spider.zip](https://github.com/supermerill/SuperSlicer/files/6258374/spider.zip)

**Comment by supermerill** [comment]
fixed
