### ISSUE TITLE
Issue with overlapping external perimeter

### ISSUE THREAD

**Issue by panosds** [supermerill/SuperSlicer#1065]
SuperSlicer
Version: 2.3.55.5
OS Windows 64
Brand Klipper

Activating the External perimeter first and better bonding to for example 50% the external perimeter and the one next to it come closer together as expected. If there is a third perimeter inside though, it is printed in the same place as it would be printed if the better bonding tab was left to zero.

The same happens with top infill. It is printed where the perimeter should have been but now the perimeter has been moved a bit towards the external perimeter. So now the top infill has no contact with the external perimeter.

If a flow ratio was given for each different line kind one would be able to adjust the line width and real flow for each line as wished and there would be no need for better bonding to even exist at all.
Another way would be to have a setting for overlapping each different line (bringing them closer to each other) that would have the same effect.
[Cube.zip](https://github.com/supermerill/SuperSlicer/files/6265918/Cube.zip)

**Comment by supermerill** [comment]
> Activating the External perimeter first and better bonding to for example 50% the external perimeter and the one next to it come closer together as expected. If there is a third perimeter inside though, it is printed in the same place as it would be printed if the better bonding tab was left to zero.

Can't replicate, I don't see that.

> The same happens with top infill. It is printed where the perimeter should have been but now the perimeter has been moved a bit towards the external perimeter. So now the top infill has no contact with the external perimeter.

yes, the infill isn't moved. You can increase the infill/perimeter overlap if it's too far away.

> If a flow ratio was given for each different line kind one would be able to adjust the line width and real flow for each line as wished and there would be no need for better bonding to even exist at all.

no because that would mean overextruding.
