### ISSUE TITLE
Avoid crossing perimeters doesn't works if extra wipe set

### ISSUE THREAD

**Issue by ZhenyaKa** [supermerill/SuperSlicer#1069]
### Version
Version 2.3.55

Compare with Cura slicing paths.
### Behavior
Head cross perimeters and option doesn't affect to that.
I tried different detour length - result the same

[Муфта тефаль-crossing.3mf.zip](https://github.com/supermerill/SuperSlicer/files/6276593/-crossing.3mf.zip)

![cura-ok](https://user-images.githubusercontent.com/28926895/113979794-6556f200-984e-11eb-8419-17c1dc52871e.png)
![ss-crossing](https://user-images.githubusercontent.com/28926895/113979824-6e47c380-984e-11eb-96a6-51cabd2a054e.png)

**Comment by ZhenyaKa** [comment]
I find when this issue appears: when option Extra wipe for external perimeter is not zero in Print setting-Extruder section.

**Comment by supermerill** [comment]
#1061

**Comment by supermerill** [comment]
on 2.3.55.5 nigtlhy:
![image](https://user-images.githubusercontent.com/6536403/114310901-c996e180-9aec-11eb-92b9-7c87c8c274a1.png)

**Comment by ZhenyaKa** [comment]
You didn't switch "Extra wipe for external perimeter" option ON!!!

**Comment by supermerill** [comment]
> You didn't switch "Extra wipe for external perimeter" option ON!!!

Hey, calm down! How can i have known that? It isn't in your project file and didn't talk about it... (and it's not a switch but a number).

> And your perimeters start points isn't RANDOM

not needed to replicate and your screenshot shows "cost-based" and not "random".

replicated:
![image](https://user-images.githubusercontent.com/6536403/114319842-7f752680-9b13-11eb-8ae9-4e419e1645b2.png)

**Comment by ZhenyaKa** [comment]
> > You didn't switch "Extra wipe for external perimeter" option ON!!!
> 
> Hey, calm down! How can i have known that? It isn't in your project file and didn't talk about it... (and it's not a switch but a number).
I wrote about that in my second message
![image](https://user-images.githubusercontent.com/28926895/114324727-603ac100-9b34-11eb-97bb-1e21275642c7.png)
