### ISSUE TITLE
Custom Printer Bugs

### ISSUE THREAD

**Issue by AgentMSG** [supermerill/SuperSlicer#1074]
### Version
Version: 2.3.55.5
Build: SuperSlicer_2.3.55.5

### Operating system type + version
Windows 10 Pro, Build 19042.867

### 3D printer brand / version + firmware version (if known)
Creality Ender 3, modified with SKR E3 Mini 1.2, running Marlin bugfix version 2.0.x (though the bug is happening before the printer gets involved)

### Behavior
*Problem Description: When a custom printer is configured with Marlin firmware, an erroneous M109 command is being put into the GCODE outside of starting GCODE options
* Steps: Define a customer printer profile (not using the predefined custom printers), Select Marlin firmware and define the other parameters (take note of the default bed temp used). Without using any of the custom GCODE options in the printer or filament settings, import a model, slice it, and export GCODE. You may have to go into the width and flow section to add %'s to all of the width options there, this profile specifically tries to set the width to 100+ mm. 
  * _If this is a command-line slicing issue, include the options used:_ Only the defaults
* _Expected Results:_ M140 commands to set bed temp, M109 commands that set the nozzle temp
* _Actual Results:_ After the "_; Filament gcode_" comment, an erroneous M109 command is issued on every GCODE file I've generated. It has the comment "_; Set bed temperature and wait for it to be reached_", but M109 is specifically "_wait for nozzle temp_". The temp that it sets is not the temperature specified in the filament settings, but always reflects the default bed temp specified when configuring the custom profile (for example, I have the settings for the bed temperature under filament settings set to 60c, nozzle temp set to 205c. The initial temp I defined when configuring the profile through the wizard was 55c. The code that appears in all of my GCODE files is "_M109 S55 ; set bed temperature and wait for it to be reached_"
  * _Screenshots from __*SuperSlicer*__ preview are preferred_
I've included an affected GCODE file, screenshots, and the project file here: [Custom Bug.zip](https://github.com/supermerill/SuperSlicer/files/6279379/Custom.Bug.zip)

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_

**Comment by supermerill** [comment]
> running Marlin bugfix 

you've set the firmware to Makerware.
Change it to marlin.
