### ISSUE TITLE
[Feature request] Disable or make deselectable the automatic switch from tabs during background processing

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#1083]
I compiled the version from the master (2.3.56.0) and I noticed that if the background processing is active there is an automatic switch between the tabs, this is very inconvenient, because if I am making changes it switches automatically every time.
It may happen that i make a repositioning or resizing of some support or other and every time the switch takes place, very boring.
This thing is being introduced recently, in the latest release fortunately it wasn't there.
It would be useful if there was not this automatic switching, or maybe it can be activated/deactivated with a flag in the configuration.
Thanks!

![immagine](https://user-images.githubusercontent.com/3864712/114515521-ba26ae00-9c3c-11eb-9791-fc971aff1d42.png)

**Comment by MLiv79** [comment]
Yes i've the same issue

**Comment by MLiv79** [comment]
In the latest Fix Build work as expected

**Comment by robustini** [comment]
> 
> 
> In the latest Fix Build work as expected

Which branch?
