### ISSUE TITLE
Ironing defects with 0.25mm nozzle after latest update

### ISSUE THREAD

**Issue by 3dprintrookie** [supermerill/SuperSlicer#109]
In the prior release, there were some gaps on the top infill especially when using 0.25mm nozzle, but now, it's over extruding like crazy!

I've been at it for more than 12 hours (still going) trying to play with the new ironing parameters to fix the issue, but I either fix the gaps and ruin the edges or vice versa. I can't get a clean print at all.

Check the images, it seems like the nozzle is extruding and pushing the plastic over the edges and smudging the whole thing.

This looks like the same feathering issue that is currently logged, but now the problem is greatly increased

Can you explain what is the difference between *above the bridges* and *top fill* ? I'm keeping *ironing tuning* at 50% as default and playing with the other two. But I just can't get it to work with 0.25mm nozzle. 

![IMG_6610 (1)](https://user-images.githubusercontent.com/55085445/67622050-39e17280-f827-11e9-970a-5ad0bc531649.jpg)
![IMG_6609](https://user-images.githubusercontent.com/55085445/67622051-39e17280-f827-11e9-9cfc-256c09f772f4.jpg)
![IMG_6608](https://user-images.githubusercontent.com/55085445/67622052-39e17280-f827-11e9-8350-77b5ede4cd99.jpg)

**Comment by 3dprintrookie** [comment]
This looks like the same feathering issue that is currently logged, but now the problem is greatly increased

**Comment by supermerill** [comment]
check if the new parameter "top layer flow" is at 100%

**Comment by supermerill** [comment]
With last version, do you still have the problem?
If yes you really need to send me your project file (zip it before dropping it here)

**Comment by 3dprintrookie** [comment]
Hey man sorry to keep you hanging, didn't notice your reply. 

I fixed it after more than a dozen tests with playing around the settings until I found out that the culprit was the **Above The Bridges** percentage. I put that to 30% to fix my issue. **Top Fill** remained at 100%.

I haven't tested your latest version. But what changed now? I am afraid that the new update will ruin my current settings that took so long to fix with tests.

**Comment by supermerill** [comment]
> I haven't tested your latest version. But what changed now?

I didn't touch the "Above The Bridges".

I think i will need to do some more test with an other nozzle than 0.4.

**Comment by 3dprintrookie** [comment]
Got more pictures of the surface, not really ideal even if I put the ATB to 35%

![fe2](https://user-images.githubusercontent.com/55085445/68565019-bd2bd680-046b-11ea-978c-a7bac124cff6.jpg)
![fe1](https://user-images.githubusercontent.com/55085445/68565020-bd2bd680-046b-11ea-9220-7b33db004fff.jpg)
![fe4](https://user-images.githubusercontent.com/55085445/68565021-bd2bd680-046b-11ea-9163-3b9e8408a02e.jpg)
![fe3](https://user-images.githubusercontent.com/55085445/68565022-bd2bd680-046b-11ea-860e-f74421cb3c51.jpg)

**Comment by supermerill** [comment]
can i have your .3mf (project file, sipped and dropped here) ?

**Comment by 3dprintrookie** [comment]
There you go

[raptorslicer.stl.zip](https://github.com/supermerill/Slic3r/files/3904749/raptorslicer.stl.zip)

**Comment by supermerill** [comment]
@3dprintrookie it's the stl, not the 3mf. Can you click on "save as" in slic3r++ just before/after slicing your object and sending the zip of this file instead?

Without that, i don't know what settings you used and so i can't replicate.

**Comment by Nyshan** [comment]
@3dprintrookie @supermerill Is this still a problem? This issue is now four years old and this question: https://github.com/supermerill/SuperSlicer/issues/109#issuecomment-550326357 was never properly answered.
