### ISSUE TITLE
When the specified number of perimeters will not fit in an area of a model, only a single perimeter is printed

### ISSUE THREAD

**Issue by NameOfTheDragon** [supermerill/SuperSlicer#1098]
### Version
2.3.55.5

### Operating system type + version
Windows 10

### Behavior
Consider the attached project
[Issue Repro.zip](https://github.com/supermerill/SuperSlicer/files/6338537/Issue.Repro.zip)

Examine the teeth in the small gear. When set to 4 perimeters, the teeth are solid (desired result):
![image](https://user-images.githubusercontent.com/1268490/115292411-d3a08c00-a14d-11eb-9e50-40d48acfecf7.png)

However, if the number of perimeter's is increased to 5, the teeth print with just a single perimeter and sparse infill:
![image](https://user-images.githubusercontent.com/1268490/115292532-034f9400-a14e-11eb-8759-1a802c84f657.png)

If the model feature is too small to accept the specified number of perimeters, I would expect it to print as solid (as many perimeters as will fit). Otherwise this can lead to unexpectedly weak small features.

**Comment by NameOfTheDragon** [comment]
May be related to #991

**Comment by supermerill** [comment]
remove the "only one perimeter on top" or the min eara for it
