### ISSUE TITLE
Wrong print settings profile name for 0.08mm HIGHDETAIL

### ISSUE THREAD

**Issue by fraaancooo** [supermerill/SuperSlicer#1104]
### Version
_Version 2.3.55_

### Operating system type + version
_Windows 10 Home, 21H1, OS Compilation 19043.962, Windows Feature Experience Pack 120.2212.3530.0_

### Behavior
* _Wrong print settings profile name. "**0.8mm** HIGHDETAIL" should be "**0.08mm** HIGHDETAIL". That's it!_

![image](https://user-images.githubusercontent.com/18744193/115940386-c3ebb500-a477-11eb-80c9-3589dfb45847.png)

**Comment by Pavulon87** [comment]
Duplicate of #1060

**Comment by supermerill** [comment]
When the configs has been moved into their own repo, the fix hasn't been used. Fixed since a week.
