### ISSUE TITLE
Fiilament extrusion override is casted to integer

### ISSUE THREAD

**Issue by sttts** [supermerill/SuperSlicer#1116]
**Describe the bug**

When adding an override for an object for the filament extrusion factor, every floating point value is casted to integer. When I enter 99.5, it becomes 99.

**To Reproduce**
1. add override: filament / extrusion
2. enter 99.5
3. change focus and come back
4. find 99

**Expected behavior**

99.5 to stay

**Screenshots**
![Bildschirmfoto 2021-04-28 um 08 50 49](https://user-images.githubusercontent.com/730123/116359213-d6ab1480-a7fe-11eb-9f31-2bcee5005859.png)

**Desktop (please complete the following information):**
 - MacOS 10.15
 - SuperSlicer from CI snapshot 2ish weeks ago

**Comment by Pavulon87** [comment]
I can confirm it in the last version(windows).

**Comment by Pavulon87** [comment]
This is the case for all settings of type coPercent.
For example fill_density or bridge_overlap.

**Comment by Pavulon87** [comment]
In src\slic3r\GUI\ **OptionsGroup.cpp** there is:
> 	case coPercent:{
		double val = config.option<ConfigOptionPercent>(opt_key)->value;
		text_value = wxString::Format(_T("%i"), int(val));
		ret = text_value;// += "%";
	}

@supermerill Maybe a good option would be to change the format to:
>text_value = wxString::Format(_T("%g"), val);

**Comment by supermerill** [comment]
@Pavulon87
got it
I prefer %f than %g for this case.
It also needs to not display 99.0000000005%
