### ISSUE TITLE
Small odd-shaped area does not get internal perimeters

### ISSUE THREAD

**Issue by JohanAR** [supermerill/SuperSlicer#1124]
**Describe the bug**
The end of the area with sawteeth only gets a single external perimeter and no internal perimeters, with 3 perimeters configured. It works as expected with 2 perimeters, and with 4 perimeters the area without internal perimeters grows even larger.

**To Reproduce**
1. Use Creality Ender 3 v2 printer configuration, Creality PLA @CREALITY filament configuration, 0.20mm NORMAL @CREALITY print configuration
1. Load my STL
2. Change perimeters to 3
3. Slice

**3D Model and Slic3r Configuration Export**

Rename to .3mf
[missing_perimeters.zip](https://github.com/supermerill/SuperSlicer/files/6398595/missing_perimeters.zip)

[t2_prong.stl.zip](https://github.com/supermerill/SuperSlicer/files/6398604/t2_prong.stl.zip)

**Expected behavior**
The whole area is filled with internal perimeters

**Screenshots**
![missing_perimeters](https://user-images.githubusercontent.com/4918549/116552510-6634ee00-a8f9-11eb-861b-f9f599084adb.png)

**Desktop (please complete the following information):**
 - OS: Xubuntu 20.04 LTS
 - Superslicer 2.3.55.5 (appimage)

**Additional context**
Not replicable in PrusaSlicer

**Comment by neophyl** [comment]
Turn off only one perimeter on top layers.  It is known to cause issues with most of the 2.3 based versions.  The reason it doesn't happen in PS is that PS doesn't have that option at all.

**Comment by supermerill** [comment]
can't reproduce on latest nightly.
99% neophyl is right.

**Comment by JohanAR** [comment]
Just verified that 2.3.56 that the bug is gone
