### ISSUE TITLE
AppImage not executable by default

### ISSUE THREAD

**Issue by nerdCopter** [supermerill/SuperSlicer#1125]
* the `./src/platform/unix/build_appimage.sh.in` does indeed mark it executable
* i've attempted solutions without success:
  - attempted remarking with another action, did not work
  - attempted using upload v2 (`upload-artifact@v2`), did not work.
* maybe a limitation of `.tar` format (or moreover, the parameters used in the action)

**Comment by supermerill** [comment]
https://github.com/actions/upload-artifact/issues/38#issuecomment-692890931
I'm going to put it in a tar
