### ISSUE TITLE
config of PrusaSlicer to SuperSlicer Error configbase

### ISSUE THREAD

**Issue by jensus11** [supermerill/SuperSlicer#1131]
Hello,

i use the Version 2.3.55.5 for MacOS Catalina.
I want to import the PrusaSlicer config and get the error message.
What can I do?
![Bildschirmfoto 2021-05-01 um 18 25 04](https://user-images.githubusercontent.com/17987533/116788651-1a29ab00-aaab-11eb-8d35-566a340389a7.png)

thanks

**Comment by jensus11** [comment]
on 2.3.55.3 comes this error.
![Bildschirmfoto 2021-05-02 um 17 10 27](https://user-images.githubusercontent.com/17987533/116818013-794df500-ab69-11eb-8735-f161ca2c2821.png)

**Comment by supermerill** [comment]
this second one is already fixed.
