### ISSUE TITLE
When is the next release expected and will it be a fully merged, stable release? 

### ISSUE THREAD

**Issue by JasonGuthrie** [supermerill/SuperSlicer#1132]
Sorry if it is bad manners to ask, but when can we expect the next release?

Superslicer is truly amazing and I can't wait for the fully merged version to come out!

Cheers SuperMerill, your work is fantastic. Keep up the great work!

**Comment by supermerill** [comment]
When there is no more bug poping up, or it can't be named "stable"

**Comment by JasonGuthrie** [comment]
> When there is no more bug poping up, or it can't be named "stable"

Fair point. Keep up the good work and I look forward to the next release.

**Comment by supermerill** [comment]
I wanted to release it last week-end...
