### ISSUE TITLE
Invalid notebook index and other startup errors

### ISSUE THREAD

**Issue by khumarahn** [supermerill/SuperSlicer#1134]
Hi. I run superslicer on arch linux, build it from aur. At the current git state I get errors at start
![screenshot-20210502@112042](https://user-images.githubusercontent.com/5206045/116808392-bd74d180-ab38-11eb-9658-dfd2941ba637.png)

Then the print settings and filament settings are unavailable.
![screenshot-20210502@112132](https://user-images.githubusercontent.com/5206045/116808400-d2516500-ab38-11eb-84c7-089733e69879.png)

Same with the recent appimages. Older appimages run fine.

**Comment by supermerill** [comment]
you can change the layout (preferecen -> gui) to old, for now.

**Comment by makhtev** [comment]
Same issue on arch
Changing layout to old solved warning messages on start but print settings and filament settings are still unavailable

**Comment by supermerill** [comment]
> Changing layout to old solved warning messages on start but print settings and filament settings are still unavailable

how is that possible? the third and fourth tab do nothing?

**Comment by khumarahn** [comment]
they are not there. resizing does not help

**Comment by tafli** [comment]
Same here on Manjaro. Building SuperSlicer from AUR. Changing layout doesn't fix the errors.

Additionally, the wizard does not run at all:
`~/.cache/yay/superslicer-git/src/SuperSlicer/src/slic3r/GUI/ConfigWizard.cpp(2595): assert ""prusa_it != p->bundles.cend()"" failed in ConfigWizard(): Vendor PrusaResearch not found`

![2021-05-03_17-47](https://user-images.githubusercontent.com/15720039/116899278-a79a0600-ac37-11eb-9ab3-5b32a0e9bb35.png)

I tried to delete the whole configuration folder but no success with that.

Additionally adding new printer is not possible. SuperSlicer crashes:
`usr/bin/superslicer: line 9: 31514 Segmentation fault      (core dumped) LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/wxgtk-dev/lib" /usr/share/SuperSlicer/superslicer "$@"`

The printer itself is beeing saved but when selecting SuperSlicer crashes again with above message written to the console.

**Comment by frap129** [comment]
+1 on this. Running on Arch, built from source. Switching to the old layout doesn't resolve the error or make the print/fillament settings tabs appear.

**Comment by supermerill** [comment]
@tafli
you have to update the profile git submodule now (see the updated how to build doc) to get the printer profiles.

I'll push a possible fix today

**Comment by frap129** [comment]
Reporting that the latest nightly fixed this issue for me. Thanks supermerill!

**Comment by khumarahn** [comment]
It will be fixed in arch linux AUR when nightly is merged to master?

**Comment by frap129** [comment]
> It will be fixed in arch linux AUR when nightly is merged to master?

@khumarahn The `superslicer` package will be fixed when the next version is released, `superslicer-git` will be fixed when this is merged into master. I reinstalled `superslicer-git` but added `git checkout Nigthly` after `cd "$srcdir/SuperSlicer` in the PKGBUILD to install the latest nightly.

**Comment by tafli** [comment]
Confirm to be working with AUR/superslicer-prerelease-bin:2.3.55.5-1 on Manjarko. Thanks for fixing!
