### ISSUE TITLE
Last nightly doesn't start on windows 10 (wxWidgets debug alert)

### ISSUE THREAD

**Issue by Liger0** [supermerill/SuperSlicer#1140]
### Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. [Development builds of Slic3r](https://dl.slic3r.org/dev). [Prusa3D Issue Tracker](https://github.com/Prusa3D/Slic3r/issues)

**Describe the bug**
The last nightlies (commit cf80732 and 23a708f) don't work.
Commit 580669e is the last working one.

**To Reproduce**
1. Try to open it

**3D Model and Slic3r Configuration Export**
Please upload a ZIP archive containing a copy of the 3D model you are seeing this bug with and a CTRL-E export of the configuration used.

**Expected behavior**
Start

**Screenshots**
![Start](https://user-images.githubusercontent.com/20385116/117462842-577cb580-af4f-11eb-8ad3-1d4b6ab2bdeb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version [e.g. 1.3.0]: Nightly cf80732 and newer

**Additional context**

**Comment by th33xitus** [comment]
Can't confirm.
Works for me.

**Comment by Sineos** [comment]
https://github.com/supermerill/SuperSlicer/runs/2444500043 works here as well (Win64)

**Comment by salocain** [comment]
he doesn't start on linux --> splash screen and.....nothing

**Comment by Liger0** [comment]
> 
> 
> https://github.com/supermerill/SuperSlicer/runs/2444500043 works here as well (Win64)

Well that's an old build, not the one I reported.

**Comment by supermerill** [comment]
It's weird as the only change on that is a deletion of a macos-only section.

**Comment by Liger0** [comment]
Not totally sure if it's of any meaning, but all the path is just reported as 'a'

**Comment by Liger0** [comment]
I confirm that the commit 23a708f is also broken.

**Comment by th33xitus** [comment]
> 
> 
> I confirm that the commit [23a708f](https://github.com/supermerill/SuperSlicer/commit/23a708f075c72f971761ee3786b5a5a7c17d5396) is also broken.

https://github.com/supermerill/SuperSlicer/suites/2791890190/artifacts/62002145

I can't confirm (again).
Works fine for me... Win10 Pro x64

**Comment by neophyl** [comment]
Works for me on Win 10 too.  Running in english though and not italian like the OP

**Comment by Liger0** [comment]
I'm running english.

**Comment by neophyl** [comment]
Sorry,I really shouldn't make assumptions but I saw Nascondi dettagli from your pic I thought it sounded/looked Italian.

**Comment by Liger0** [comment]
Well, the windows installation is italian, the slicer is english.

**Comment by Liger0** [comment]
> 
> 
> he doesn't start on linux --> splash screen and.....nothing

Indeed, the splash screen is displayed, the crash happens after it.

**Comment by Liger0** [comment]
The beta  2.3.56.0 is unfortunately also broken :(

**Comment by supermerill** [comment]
I just replicate this bug on one of my computer
