### ISSUE TITLE
 e637a9e Nigthly  in linux (not tested in windows) gui part lost ..

### ISSUE THREAD

**Issue by salocain** [supermerill/SuperSlicer#1143]
**Describe the bug**

**To Reproduce**
just load the nightly 

**Desktop (please complete the following information):**
 - OS:Linux

firtst capture --> the last working nightly (Merge branch 'merill-merge' C/C++ CI ubuntu #237)
the nightly after have this problems

![superslicer ](https://user-images.githubusercontent.com/72736639/117533899-674bd680-afef-11eb-866c-b6907f80ff7a.png)

the second --> the result --> some gui part lost

![superslice 2](https://user-images.githubusercontent.com/72736639/117533898-66b34000-afef-11eb-89a7-813a3296ce78.png)

**Comment by nerdCopter** [comment]
+1   ...i waited for settling of `master`, but no changes for sometime...
I can live with bed-graphic missing, but the Filament and Printer menus fail completely.

Ubuntu 20.04.2 LTS.   
[Separately, i can no longer even launch it in Debian -- segfault]

for completeness sake, when starting with no profile/config the following unusable dialog shows as well:
![2021-05-18_13-23](https://user-images.githubusercontent.com/56646290/118704040-544db900-b7dc-11eb-8885-cf0cca3c43b7.png)

**Comment by salocain** [comment]
The last release work well 😁😁

**Comment by nerdCopter** [comment]
Confirmed working Debian 10.
TYVM!
