### ISSUE TITLE
Can set speed travel slow on seem point ?

### ISSUE THREAD

**Issue by Witawat** [supermerill/SuperSlicer#1144]
Can set speed travel slow on seem point ?

this prusa slicer seem this slow move
![image](https://user-images.githubusercontent.com/4926369/117545736-3603f280-b051-11eb-8322-77d4c5dd5d2f.png)

but supper slicer now slow
![image](https://user-images.githubusercontent.com/4926369/117545760-5af86580-b051-11eb-8165-9f528982b553.png)

![image](https://user-images.githubusercontent.com/4926369/117545772-66e42780-b051-11eb-9944-2f233a5cb715.png)

**Comment by supermerill** [comment]
the prusa one print slower, because of something, not because of a seam.
If you want to print your perimeter slower, then put a lower number in external perimeter speed.
