### ISSUE TITLE
poor overhang performance, but only when the slicer labels it as an "Overhang perimeter"

### ISSUE THREAD

**Issue by actuallylemoncurd** [supermerill/SuperSlicer#1145]
### Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. [Development builds of Slic3r](https://dl.slic3r.org/dev). [Prusa3D Issue Tracker](https://github.com/Prusa3D/Slic3r/issues)

**Describe the bug**
When printing a 3D Benchy, it labels the bottom part of the overhang in the front of the ship as an "Overhang Perimeter"
You can see on the printed part exactly where it is labelled as such in the slicer, you can tell the slicer is doing something different there, appears to be extrusion width related but I am unsure at this time

https://discord.com/channels/771316156203270154/771319294113742858/840705638559776809

**To Reproduce**
Open 3dbenchy stl
slice and observe the overhang perimeter in the front
Print it, see error/artifact

**3D Model and Slic3r Configuration Export**
In the discord link above

**Expected behavior**
for this area to be printed like the rest of the perimeters

**Screenshots**
In the discord link above

**Desktop (please complete the following information):**
Windows 10, 20H2 build

**Additional context**

**Comment by actuallylemoncurd** [comment]
![image0](https://user-images.githubusercontent.com/25917842/117556425-e1ec1480-b036-11eb-8dfd-b71e7abb0cdf.jpg)
![unknown](https://user-images.githubusercontent.com/25917842/117556426-e284ab00-b036-11eb-9b61-61674cd74043.png)

**Comment by CCS86** [comment]
Check your setting for this:

![image](https://user-images.githubusercontent.com/12439543/118128255-4523d100-b3c0-11eb-813b-1c776e83e1b1.png)

If it is set below 100%, than an overhanging wall can get bridge flow applied, which is a huge increase in flow rate.

**Comment by actuallylemoncurd** [comment]
Ok interesting point

I was unable to find that exact settings panel you posted but I did find this
![image](https://user-images.githubusercontent.com/25917842/118143434-575e3900-b3d9-11eb-9ab3-27abe8717090.png)
the number circled used to be 50%. i bumped it up by 5% until i got this on the benchy
![image](https://user-images.githubusercontent.com/25917842/118143482-65ac5500-b3d9-11eb-837e-f4e6e1a61205.png)
no longer detected as a "bridge" so the flow rate is the same

thank you for pointing this out, i guess this was not a bug but incompetence as this slicer has WAY more variables than any other i've used

awesome work

**Comment by CCS86** [comment]
You might want to make that 100%, so only true bridges are detected as bridges. 

Any of those lines in blue, are treated as bridges, so the flow rate is calculated on making a 0.4mm diameter bead, instead of a 0.4 x [layer height] bead. It's a big increase.

**Comment by actuallylemoncurd** [comment]
ehh, i quite like how it slows the flow rate of the nozzle down when on the harse overhangs so ill just change that as needed per print

**Comment by CCS86** [comment]
It doesn't "slow the flow rate". If you are using a 0.4mm nozzle and 0.15mm layer height, using bridge flow (100%) doubles your flow rate.

**Comment by supermerill** [comment]
maybe a "min length" for overhang detection may be useful to avoid these "spikes" when it's just at the threshold limit.

**Comment by CCS86** [comment]
I think that's a good idea.
