### ISSUE TITLE
Not really an issue... Where's Supermerill?

### ISSUE THREAD

**Issue by LaserBee** [supermerill/SuperSlicer#1156]
Not an issue or a bug... 

The dev used to update quite regularly. There hasn't been an update since Feb. Does anyone have contact with Supermerill? Is he okay? Is he still working on this, or is he busy with other stuff? 

I'm not concerned in that my slicer works great, I just am curious if it's still being developed, and want to make sure the dev is doing well! :)

Thanks.

**Comment by ReubenBTalbott** [comment]
Someone on the SuperSlicer Discord said that Supermerill’s computer died and that he’ll be back soon.

**Comment by Liger0** [comment]
last nightly is from 10 days ago (altough it doesn't start so you have to use the one before it)

**Comment by LaserBee** [comment]
Ah okay, thanks guys. I didn't even realise nightlies were a thing!

**Comment by supermerill** [comment]
problem is there are too many bugs to output a proper release.

**Comment by LaserBee** [comment]
That's okay, there's no rush. I;m glad you're still around! :)
