### ISSUE TITLE
Loss of most recent presets

### ISSUE THREAD

**Issue by bakaufman** [supermerill/SuperSlicer#1160]
**Describe the bug**
My Printer Settings added since 2.3.55.3 are not available when I launch compile #260 for mac.

**To Reproduce**
1. Have had SS for a while, before and after the advent of Physical printer. Have used a version with physical printer
2. Install #260 separately.
3. open new file or previously saved .3mf files
4. Any Printer settings, Filament Settings, Printer Settings added in 2.3.55.3 are not available

**>> Project File <<**
Doesn't seem necessary

**Expected behavior**
I expected this update/upgrade to find and use prior presets

**Screenshots**
![2 3 55 3 print settings](https://user-images.githubusercontent.com/31897832/119169694-514b0680-ba30-11eb-95f4-16e0ad11b92a.png)
![2 3 56 print settings](https://user-images.githubusercontent.com/31897832/119169696-51e39d00-ba30-11eb-9aea-889c77324ab9.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version [e.g. 2.3.55.5], 2.3.56.0 #260

**Additional context**

**Comment by supermerill** [comment]
This version switches back from the `superslicer-alpha` to `superslicer` setting directory, maybe that's that?

**Comment by bakaufman** [comment]
that is what it looks like and what I speculated in the discord. Can we have options around this?

**Comment by bakaufman** [comment]
might convert this to a feature request, or at least find a way to synchronize these folders if we are going to flip back and forth.

**Comment by supermerill** [comment]
you can just rename it.
i'll stop changing it.

**Comment by bakaufman** [comment]
That worked and is nice. I'll close it.
