### ISSUE TITLE
[2.3.56.0] UI encoding issue like "lÃ¶st", at least with german language setting

### ISSUE THREAD

**Issue by dartrax** [supermerill/SuperSlicer#1161]
**Describe the bug**
Looks like an encoding issue in this version, in 2.3.55 everything was fine. Now characters like ä ö ü ß are shown as Ã¶ all over the interface. This also affects search function (not possible to search settings with special characters).

**Screenshots**
![image](https://user-images.githubusercontent.com/15105943/119225963-1c5db300-bb07-11eb-80ca-02e4c3bf7564.png)

**Desktop (please complete the following information):**
 - OS: Win 10 64bit
 - Version [2.3.56.0]

**Comment by supermerill** [comment]
can't replicate
![image](https://user-images.githubusercontent.com/6536403/119227550-c1c85500-bb0e-11eb-812e-8cf3f83c7b38.png)

maybe because i set my windows into beta-utf-8 mode.
I'll see if I can reproduce it on an other computyer

**Comment by dartrax** [comment]
It must have something to do with the files in \resources\localization\de\*.

When I replace the files with the ones of Version 2.2.55.5, everything is ok.

**Comment by supermerill** [comment]
I changed where they are done (not on my computer anymore).
Maybe it's the problem.
I wonder if the same problem will arise in other os...

**Comment by supermerill** [comment]
[SuperSlicer.zip](https://github.com/supermerill/SuperSlicer/files/6526455/SuperSlicer.zip)
 can you test with that one?

**Comment by dartrax** [comment]
How to create the .mo file, is it simply saving the Slic3r.po with Poedit and renaming the generated Slic3r.po to SuperSlicer.mo? I've tried that and it worked.

Edit: Ah, you are fast. Yes, that's working now! No more encoding issue 👍

**Comment by jfestrada** [comment]
Hi, I can confirm that there is the same issue with the spanish translation on a win64. The linux version is working fine, so is only related with the windows build.

Windows version:

![imagen](https://user-images.githubusercontent.com/7290345/119241453-b567ea80-bb56-11eb-9a1c-00dbe8c92184.png)

Linux version (PopOS amd64):

![spanish_linux](https://user-images.githubusercontent.com/7290345/119241398-45f1fb00-bb56-11eb-9e20-34cc3fe6b53d.png)

**Comment by dartrax** [comment]
Try this one:
[SuperSlicer_ES.zip](https://github.com/supermerill/SuperSlicer/files/6527230/SuperSlicer_ES.zip)

**Comment by jfestrada** [comment]
> 
> 
> Try this one:
> [SuperSlicer_ES.zip](https://github.com/supermerill/SuperSlicer/files/6527230/SuperSlicer_ES.zip)

This file solve the issue for the spanish translation.

![imagen](https://user-images.githubusercontent.com/7290345/119242090-8acc6080-bb5b-11eb-8e47-719ee518b542.png)

**Comment by supermerill** [comment]
good to know.. I'll have to manually create the translation for windows.
