### ISSUE TITLE
A debugging check in this application failed 2.3.56

### ISSUE THREAD

**Issue by Jack77777777** [supermerill/SuperSlicer#1166]
**Describe the bug**
See error in screenshots section

**To Reproduce**
1. Open SuperSlicer 2.3.56

**>> Project File <<**
[Project.zip](https://github.com/supermerill/SuperSlicer/files/6527497/Project.zip)

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/64719909/119247534-9b47ff80-bb8a-11eb-98c0-3f89874787c1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro; 20H2; 19042.985; Windows Feature Experience Pack 120.2212.2020.0
 - Version 2.3.56

**Comment by tome9111991** [comment]
same probleme here.
and btw on german version problems with ö,ä,ü

![superslicer](https://user-images.githubusercontent.com/57866234/119252621-92b4f080-bbad-11eb-9c91-0dbd0b9c379d.png)

**Comment by Jack77777777** [comment]
> Program crash
> i try change temperature first layer extruder or
> Bed other layers
> Only when i type a value with keyboard.
> If i use arrow got debugging check error

Can confirm!

**Comment by cbc02009** [comment]
Same issue here.

**Comment by supermerill** [comment]
can someone test the build https://github.com/supermerill/SuperSlicer/actions/runs/869422325 ?
it's a debug build, so it's a bit slower.

**Comment by cbc02009** [comment]
> 
> 
> can someone test the build https://github.com/supermerill/SuperSlicer/actions/runs/869422325 ?
> it's a debug build, so it's a bit slower.

Works for me!

**Comment by tome9111991** [comment]
> can someone test the build https://github.com/supermerill/SuperSlicer/actions/runs/869422325 ?
> it's a debug build, so it's a bit slower.

works for me too
no error no crash

**Comment by Liger0** [comment]
> 
> 
> can someone test the build https://github.com/supermerill/SuperSlicer/actions/runs/869422325 ?
> it's a debug build, so it's a bit slower.
Crash at start
![debug failed](https://user-images.githubusercontent.com/20385116/119368180-00971000-bcb3-11eb-8694-5ca9fe9c2c0b.png)

**Comment by bttguy** [comment]
Can we expect a prebuilt zip hotfix release for it, or we should wait for the next release you planned?

**Comment by Jack77777777** [comment]
> Can we expect a prebuilt zip hotfix release for it, or we should wait for the next release you planned?

The latest version is working for me when Unicode UTF-8 is enabled in Windows. My Windows is set to german and SS to english.

Control Panel->Clock and Region->Region->Administrative TAB->Change system locale...->Check **Beta: Use Unicode UTF-8 for worldwide language support**

**Comment by supermerill** [comment]
> Can we expect a prebuilt zip hotfix release for it, or we should wait for the next release you planned?

you can use the nightly. The windows build just miss the poedit-compiled localization files.

**Comment by Liger0** [comment]
> 
> I'll do a release this evening if no other bug is reported.

uhm, what about the crash I reported?

**Comment by supermerill** [comment]
> > I'll do a release this evening if no other bug is reported.
> 
> uhm, what about the crash I reported?

Which one?
If it's about the italian translation, I can't reproduce your error, as i don't have the file.
The merging tool is repaired (in the nightly).
If you have a new file, i can include it. Do I include the one in https://github.com/supermerill/SuperSlicer/issues/1128#issuecomment-846606648 ?

**Comment by Liger0** [comment]
> 
> 
> > > I'll do a release this evening if no other bug is reported.
> > 
> > 
> > uhm, what about the crash I reported?
> 
> Which one?
> If it's about the italian translation, I can't reproduce your error, as i don't have the file.
> The merging tool is repaired (in the nightly).
> If you have a new file, i can include it. Do I include the one in [#1128 (comment)](https://github.com/supermerill/SuperSlicer/issues/1128#issuecomment-846606648) ?

Yes, the last one. If you are able to merge the TODO tell me, because the script tells me error and it fails to.
Also the crash is with any traslation, even old ones or the one included in the beta itself.

**Comment by Liger0** [comment]
@supermerill I tried the new release "better spacing". Still same issue! 
![invalid string position](https://user-images.githubusercontent.com/20385116/119816187-b6996e80-beec-11eb-9810-2fbf0a8dedf4.png)

**Comment by bttguy** [comment]
Downloaded the latest build, have no issue since! Thanks the hotfix!
