### ISSUE TITLE
SuperSlicer_2.2.56.0_win64 italian language make program crash

### ISSUE THREAD

**Issue by chicco83** [supermerill/SuperSlicer#1167]
if the software starts in italian it crash immediately.

**Comment by MLiv79** [comment]
Yes and moreover you can't make it start in english. I've the previous version in english (because of known issues with italian language like fan settings) and the latest nightly force start in italian while i've not set it up in italian and like you wrote it force close immediately.

**Comment by MLiv79** [comment]
Yes, i tried also latest release and result is the same. It start in italian and crash
![image](https://user-images.githubusercontent.com/70020275/119254753-7bc7cb80-bbb8-11eb-8a4e-b3da6321be7c.png)

**Comment by chicco83** [comment]
to fix it simply copy eng file into it directory
here
SuperSlicer_2.2.56.0_win64_20210522\resources\localization

**Comment by boromyr** [comment]
Try: https://github.com/supermerill/SuperSlicer/files/6523933/it.zip or https://github.com/supermerill/SuperSlicer/files/6433226/SuperSlicer.it.6.may.2021.zip

**Comment by Liger0** [comment]
Use this nightly: https://github.com/supermerill/SuperSlicer/actions/runs/804896051
And the last posted files at #1128

**Comment by supermerill** [comment]
It's on windows?
I tried each tabs on the italian just to be sure it won't crash.
And I can't make it crash.... maybe because my windows is in utf-8 mode... same problem as with other translations.
does this file works?
[it_2021_05_24.zip](https://github.com/supermerill/SuperSlicer/files/6534795/it_2021_05_24.zip)

**Comment by Liger0** [comment]
> 
> 
> It's on windows?
> I tried each tabs on the italian just to be sure it won't crash.
> And I can't make it crash.... maybe because my windows is in utf-8 mode... same problem as with other translations.
> does this file works?
> [it_2021_05_24.zip](https://github.com/supermerill/SuperSlicer/files/6534795/it_2021_05_24.zip)

It still doesn't work.
Could you use as a base the updated one I posted yesterday in the last post, to see if anything need fixes? 
It works in the old nightly.
Plus there is translated stuff in the TODO but the python scripts fails so I can't merge it.

![debug failed](https://user-images.githubusercontent.com/20385116/119405295-4c60ae00-bce1-11eb-823c-bd2365bf1c27.png)

**Comment by supermerill** [comment]
@Liger0 should be resolved, can you test the action debug_win#9?

**Comment by supermerill** [comment]
nevermind
