### ISSUE TITLE
[2.3.56.0] UI encoding issue, at least with russian language setting

### ISSUE THREAD

**Issue by epson950** [supermerill/SuperSlicer#1170]
![2021-05-23 13 35 10](https://user-images.githubusercontent.com/11770015/119257332-73c65680-bbcd-11eb-865c-50edbadfe524.jpg)

**Comment by ShohninDmitriy** [comment]
файлы киньте в в папку \resources\localization\ru\  предварительно удалив все из нее

[ru.zip](https://github.com/supermerill/SuperSlicer/files/6528792/ru.zip)

**Comment by Alexdad76** [comment]
> 
> 
> файлы киньте в в папку \resources\localization\ru\ предварительно удалив все из нее
> 
> [ru.zip](https://github.com/supermerill/SuperSlicer/files/6528792/ru.zip)

Каракули исправляет. Надо бы чтобы по умолчанию English включался.
Doodle corrects. It would be necessary for the default English turned on.

**Comment by epson950** [comment]
> 
> 
> файлы киньте в в папку \resources\localization\ru\ предварительно удалив все из нее
> 
> [ru.zip](https://github.com/supermerill/SuperSlicer/files/6528792/ru.zip)

Помогло! Спасибо! А продолжение над переводом будет? А то частично осталось на английском...

**Comment by ShohninDmitriy** [comment]
я не участвовал в переводе просто прогнал ее через Poedit  чтоб каракули поправить

**Comment by ShohninDmitriy** [comment]
[ru.zip](https://github.com/supermerill/SuperSlicer/files/6528965/ru.zip)

Частично обновил файлы оригиналов с Английского исходника

**Comment by supermerill** [comment]
does this one works?
[ru_20210524.zip](https://github.com/supermerill/SuperSlicer/files/6534801/ru_20210524.zip)

surely the same problem as with others.

**Comment by shadalik** [comment]
> does this one works?

Still does not work

**Comment by Alexdad76** [comment]
> 
> 
> does this one works?
> [ru_20210524.zip](https://github.com/supermerill/SuperSlicer/files/6534801/ru_20210524.zip)
> 
> surely the same problem as with others.

I confirm - `ru_20210524.zip` still not working 
(Windows 7 64 bit)

**Comment by supermerill** [comment]
I confirmed that gettext isn't creating a nice file for windows.
@ShohninDmitriy how did you transformed your .po in a .mo?

**Comment by ShohninDmitriy** [comment]
> I confirmed that gettext isn't creating a nice file for windows.
> @ShohninDmitriy how did you transformed your .po in a .mo?

using the PoEdit program

**Comment by supermerill** [comment]
Ok, the problem is the lack of header at the top of the .po to say "it's utf-8"
Will be fixed.
