### ISSUE TITLE
Print stops right after it started since 2.3.56

### ISSUE THREAD

**Issue by nicedevil007** [supermerill/SuperSlicer#1175]
**Describe the bug**
After start of the print I get this error:

```
// Move exceeds maximum extrusion (7.901mm^2 vs 2.560mm^2)
// See the 'max_extrude_cross_section' config option for details
```

I imported the profile bundles from 2.3.55 to 2.3.56 and expected that it will work as it does before.

**To Reproduce**
Start a print after it is sliced with recent version.

**>> Project File <<**
*Please* upload a ZIP archive containing the project file used when the problem arise. Please export it just before the problem occur. Even if did nothing and there is no object, export it as it contains your current configuration.

**Expected behavior**
Printer will start printing and not stop after a few seconds

**Screenshots**
![image](https://user-images.githubusercontent.com/17103076/119307980-c014a380-bc6c-11eb-839a-ae851e97c958.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.56.0

**Additional context**

**Comment by Xploder** [comment]
![image](https://user-images.githubusercontent.com/3930461/119314405-ff46f280-bc74-11eb-8030-5b8070206a50.png)
and have a G92 E0 at the end of your start g-code aswell as a G92 E0 in your Before layer change G-Code
![image](https://user-images.githubusercontent.com/3930461/119314519-1f76b180-bc75-11eb-8079-bdfec9af4c89.png)

![image](https://user-images.githubusercontent.com/3930461/119314502-1be32a80-bc75-11eb-96c2-09183e6514e3.png)

**Comment by nicedevil007** [comment]
Thank you, will try it out, G92 E0 was already in my start gcode but I didn't used relative E distances

**Comment by Xploder** [comment]
> Thank you, will try it out, G92 E0 was already in my start gcode but I didn't used relative E distances

Makes sense, if you zero out the extrusion value at the end of your Start GCode but don't use relative distances in your slicer then the next move is going to be something ridiculously long that Klipper rightfully stops.

**Comment by nicedevil007** [comment]
> > Thank you, will try it out, G92 E0 was already in my start gcode but I didn't used relative E distances
> 
> Makes sense, if you zero out the extrusion value at the end of your Start GCode but don't use relative distances in your slicer then the next move is going to be something ridiculously long that Klipper rightfully stops.

ahhhh thank you for clearing this up :) it is working now!
