### ISSUE TITLE
Blurry bed SVG

### ISSUE THREAD

**Issue by qwewer0** [supermerill/SuperSlicer#1176]
**Describe the bug**
Bed SVGs appears blurry on the latest version.
Default `ender3.svg` in this case.

**Expected behavior**
Bed SVGs should appear sharp, as it does on older versions (e.g. `Nigthly windows x64 #308`)

**Screenshots**
Left: `Nigthly windows x64 #308`
Right: `Nigthly windows x64 #313`
![bandicam 2021-05-24 11-14-06-811](https://user-images.githubusercontent.com/57561110/119326045-c95c3b00-bc81-11eb-8123-36bf71d944e7.jpg)

**Desktop:**
 - OS: Windows 10
 - Version: 2.3.56.0 (`Nigthly windows x64 #313`)

The issue might be connected to https://github.com/supermerill/SuperSlicer/issues/1163

**Comment by JasonGuthrie** [comment]
I have the same issue with the Prusa bed image too.

**Comment by supermerill** [comment]
there is a opengl32.dll that shouldn't be here (in the root directory). Delete it.

**Comment by JasonGuthrie** [comment]
> there is a opengl32.dll that shouldn't be here (in the root directory). Delete it.

Aye that's fixed both the blurry build plate and low frame rates. Keep up the good work.

**Comment by qwewer0** [comment]
> there is a opengl32.dll that shouldn't be here (in the root directory). Delete it.

That fixed the blurry SVG, thanks.
