### ISSUE TITLE
A debugging check in this application has failed

### ISSUE THREAD

**Issue by bttguy** [supermerill/SuperSlicer#1179]
Hi!

I downloaded the latest beta release 2.3.56 for win10. Upon opening I get these error msg-s. Than the slicer opens if I click on continue, but when I modify settings the same errors pop up, and after some time the slicer crashes and force close. Anything that I done wrong, or is this a bug? I used the previous releases with success.
![sups](https://user-images.githubusercontent.com/76131447/119383606-d39f2900-bcc3-11eb-854b-65421b4e3b82.png)
![sups2](https://user-images.githubusercontent.com/76131447/119383608-d4d05600-bcc3-11eb-8d72-4de763934fc8.png)

**Comment by tome9111991** [comment]
Look at
https://github.com/supermerill/SuperSlicer/issues/1166

**Comment by bttguy** [comment]
Thanks @tome9111991. Just started to follow the project on github, missed that one. Closing this, and keep watching the mentioned issue :)
