### ISSUE TITLE
Problem using Rechilinear (filled) pattern

### ISSUE THREAD

**Issue by Xoneso** [supermerill/SuperSlicer#118]
### Version
2.1.44

### Operating system type + version
Windows 10 (build 18363), 64-bit edition

### 3D printer brand / version + firmware version (if known)
Prusa MK3S made into Bear running 3.8.1 firmware

### Behavior
Problem using Rectilinear (filled) as pattern where it doesn't connect fully on 1 side.

Using default 0.20mm QUALITY MK3 profile gives the following problem:
Settings: https://i.imgur.com/IF10SkE.png
Result: https://drive.google.com/open?id=12ojSW2DctROeEM1Rd47DjV7h7M1Bnvxz

Changing Bottom and Solid patterns from Rectilinear (filled) to Rectilinear and the problem goes away
Settings: https://i.imgur.com/Vvn1vmc.png
Result: https://drive.google.com/open?id=12n0fgx9NA9q9BUsAtiBHxdFGxXbhxjfv

_Is this a new feature request?_ No

**Comment by supermerill** [comment]
Just to be sure:
The fact that the second one is better isn't due to the fact that the pinda heats up a bit and it may have lower your first layer just a tiny bit?
=> If you print them in opposite order, it's the same result?
