### ISSUE TITLE
Overhang speed reduction and strange infill near overhang walls

### ISSUE THREAD

**Issue by MLiv79** [supermerill/SuperSlicer#1181]
On overhang wall i get this strange infill that is unwanted, which setting make this?
![image](https://user-images.githubusercontent.com/70020275/119411867-630c0280-bceb-11eb-8be9-f695a18ef646.png)
![image](https://user-images.githubusercontent.com/70020275/119411809-47a0f780-bceb-11eb-8131-ad8ca1a22709.png)

And moreover i can't understand where this speed setting works on because on overhangs it doesn't reduce the speed. Moreover there is no setting to tells the angle where i'd like to consider a wall an overhang
![image](https://user-images.githubusercontent.com/70020275/119412246-e2013b00-bceb-11eb-9029-af43c7d4c993.png)

**Comment by supermerill** [comment]
bottom layers

**Comment by supermerill** [comment]
> And moreover i can't understand where this speed setting works on because on overhangs it doesn't reduce the speed. Moreover there is no setting to tells the angle where i'd like to consider a wall an overhang

it's here (print->perimeters)
![image](https://user-images.githubusercontent.com/6536403/119415460-f1838280-bcf1-11eb-835e-d68d9e10a161.png)
50% means 22.5°
100% means 45°
200% means 67.5°

**Comment by MLiv79** [comment]
> bottom layers and/or top layers

Bottom and top layer are only 4 (0.2mm) but this material close to internal walls is until 6 or 7 mm in height. It seems to be related to overhangs because is only where the slope is to be considered an overhang. But as shown in the picture i attach in the first post, i've no options enable to add extra perimeters close to overhang wall.

**Comment by MLiv79** [comment]
> > And moreover i can't understand where this speed setting works on because on overhangs it doesn't reduce the speed. Moreover there is no setting to tells the angle where i'd like to consider a wall an overhang
> 
> it's here (print->perimeters)
> ![image](https://user-images.githubusercontent.com/6536403/119415460-f1838280-bcf1-11eb-835e-d68d9e10a161.png)
> 50% means 22.5°
> 100% means 45°
> 200% means 67.5°

This work thanks. I don't know if it is my lack but reading the tooltip text passing over with the mouse it was impossible to understand that 50% was 22.5° 100% 45° and so on, because the help tooltip text talk about a % of the nozzle diameter...
Does exist somewhere a guide to read for these advanced (and very usefull) features?

**Comment by supermerill** [comment]
> Does exist somewhere a guide to read for these advanced (and very usefull) features?

not made yet. Ideally, https://github.com/slic3r/Slic3r-Manual should be updated
