### ISSUE TITLE
Avoid nonsense curved bridging anchors/edges

### ISSUE THREAD

**Issue by jpedrick-athenacr** [supermerill/SuperSlicer#1185]
**Is your feature request related to a problem? Please describe.**
When supporting a curved wall on top of infill, the slicer generates a curved anchor over the infill and then attaches the bridge infill to that anchor. The unsupported curved infill bridge anchor perimeter either pulls straight on short segments or sags on longer segments.

The result is that the following bridged infill pattern either:

- overshoots the bridge perimeter causing little loops that either sag, lift or tangle with their neighbors.
- undershoots and does not attach to the bridge perimeter.

This happens for me on most prints to one degree or another, usually it gets covered up by subsequent layers, but requires more top layers to overcome, where only one or two top layers may be desired.

**Describe the solution you'd like**

I think a few different solutions would resolve the problem, with various pros and cons for each.

1. On layers that require bridging infill, ensure that the bridging infill always attaches to an external perimeter. This means covering areas with bridging infill that would normally have a hole with a bridge infill perimeter. 
* Pros: this is likely the simplest to implement. Exactly similar to "Solid infill every X layers," except only on layers with bridge infill.
* Cons: when the bridging infill area would have been small and the void very large, this may be sub-optimal and significantly slow down the layer and use more filament.
2.  The slicer intelligently generates straight bridge anchor paths between infill supports and then attach the bridge infill to the straight anchor, for one or more layers.
* Pros: similar to current implementation and will avoid covering large interior voids with bridging infill when unnecessary.
* Cons: If bridging infill would have a lot of small voids( imagine a large lego with lots of pegs ), this could generate complex and slow bridging( solution #1 would be better ).

I would also like more control over the infill bridging in general.
Options like:
- only straight bridge segments where unsupported
- Solid infill on any layer with bridge infill
- number of infill bridge perimeters
- infill bridge perimeter anchor overlap(how much to overshoot bridging infill over bridging perimeters)
- infill bridge perimeter overlap(how much each bridge perimeter overlaps with the previous bridge perimeter)

**Describe how it would work**
I think I've described that above.

**Describe alternatives you've considered**
Described above.

**Additional context**

In the image I've attached, if the bridging had simply covered the "hole" as if the geometry above were unknown, there wouldn't have been any issues.

![Screenshot from 2021-05-27 00-32-01](https://user-images.githubusercontent.com/83477515/119768711-178e5b80-be87-11eb-862b-ba6839707280.png)

**Comment by supermerill** [comment]
Can you post your project file?

**Comment by jpedrick** [comment]
@supermerill I've uploaded the project here: https://github.com/jpedrick/things/blob/main/ovular_planter_mold-inside_part.3mf
```

SuperSlicer
Version:   2.3.55.5
Build:     SuperSlicer_2.3.55.5

Operating System:    Unix
System Architecture: 64 bit
System Version:      Linux 5.8.0-53-generic x86_64
Total RAM size [MB]: 33,581MB
OpenGL installation
GL version:   4.6 (Compatibility Profile) Mesa 20.2.6
Vendor:       X.Org
Renderer:     AMD VEGAM (DRM 3.38.0, 5.8.0-53-generic, LLVM 11.0.0)
GLSL version: 4.60
Installed extensions:

GL_AMD_conservative_depth
GL_AMD_depth_clamp_separate
GL_AMD_draw_buffers_blend
GL_AMD_framebuffer_multisample_advanced
GL_AMD_multi_draw_indirect
GL_AMD_performance_monitor
GL_AMD_pinned_memory
GL_AMD_query_buffer_object
GL_AMD_seamless_cubemap_per_texture
GL_AMD_shader_stencil_export
GL_AMD_shader_trinary_minmax
GL_AMD_texture_texture4
GL_AMD_vertex_shader_layer
GL_AMD_vertex_shader_viewport_index
GL_ANGLE_texture_compression_dxt3
GL_ANGLE_texture_compression_dxt5
GL_APPLE_packed_pixels
GL_ARB_ES2_compatibility
GL_ARB_ES3_1_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_bindless_texture
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_compute_variable_group_size
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_direct_state_access
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_gl_spirv
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_gpu_shader_int64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_parallel_shader_compile
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_polygon_offset_clamp
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_ballot
GL_ARB_shader_bit_encoding
GL_ARB_shader_clock
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_stencil_export
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shader_viewport_layer_array
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_include
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_sparse_buffer
GL_ARB_spirv_extensions
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_filter_anisotropic
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_blend_equation_separate
GL_ATI_draw_buffers
GL_ATI_fragment_shader
GL_ATI_meminfo
GL_ATI_separate_stencil
GL_ATI_texture_compression_3dc
GL_ATI_texture_env_combine3
GL_ATI_texture_float
GL_ATI_texture_mirror_once
GL_EXT_EGL_image_storage
GL_EXT_EGL_sync
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_copy_texture
GL_EXT_depth_bounds_test
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_memory_object
GL_EXT_memory_object_fd
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset_clamp
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_semaphore
GL_EXT_semaphore_fd
GL_EXT_separate_specular_color
GL_EXT_shader_image_load_formatted
GL_EXT_shader_image_load_store
GL_EXT_shader_integer_mix
GL_EXT_shader_samples_identical
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_subtexture
GL_EXT_texture
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_latc
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_mirror_clamp
GL_EXT_texture_object
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_R8
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shadow_lod
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_EXT_vertex_attrib_64bit
GL_EXT_window_rectangles
GL_IBM_multimode_draw_arrays
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_INGR_blend_func_separate
GL_KHR_blend_equation_advanced
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_no_error
GL_KHR_parallel_shader_compile
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_KHR_texture_compression_astc_ldr
GL_KHR_texture_compression_astc_sliced_3d
GL_MESA_framebuffer_flip_y
GL_MESA_pack_invert
GL_MESA_shader_integer_functions
GL_MESA_texture_signed_rgba
GL_MESA_window_pos
GL_NVX_gpu_memory_info
GL_NV_alpha_to_coverage_dither_control
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_copy_image
GL_NV_depth_clamp
GL_NV_fog_distance
GL_NV_light_max_exponent
GL_NV_packed_depth_stencil
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_env_combine4
GL_NV_texture_rectangle
GL_NV_vdpau_interop
GL_OES_EGL_image
GL_OES_read_format
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_border_clamp
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays

```

**Comment by jpedrick** [comment]
Hi @supermerill , I downloaded the latest release 2.3.56.3 AppImage and I'm still getting strange unsupported perimeters of internal infill layers

![Screenshot from 2021-06-09 21-56-07](https://user-images.githubusercontent.com/5932041/121452678-d8273b00-c96d-11eb-9ec6-c2e26194c948.png)

**Comment by supermerill** [comment]
In your first project, I don't really see how to improve the dense infill more...

On the second one, what is strange? If you want more anchor for the bridge, increase the number in the infill tab.

**Comment by jpedrick** [comment]
Hi @supermerill I would expect the solid infill layer to anchor to either a perimeter or the edge of the infill below it. Here it prints onto nothing. From my point of view printing onto thin air is undesired behavior and requiring dense infill for ordinary prints is also undesired behavior. I'm confused how this is "working as intended" when there aren't any FDM printers that would print this situation well. 

Is there a setting to:
a) print a bridged anchor for the infill to attach to?
b) print the entire layer with bridge infill so that the bridge infill attaches to perimeters?
c) ensure the bridge line endpoints attach to infill on the previous layer?

Thanks!

**Comment by supermerill** [comment]
a) dense infill is trying to do that.
b) put 10000 in bridge anchor setting. but be careful, some geometries can create a bridge in every layer.
c) set your sparse fill density to 50%

**Comment by moolight-seashell** [comment]
ok i thik i get it , i have this object to print : 
![Capture d’écran du 2023-05-02 22-40-15](https://user-images.githubusercontent.com/49676861/235782818-d8c2e12a-2882-4541-99f7-18e87470d038.png)

but when i slice it the firsts layers of the top cap look like that : 
![Capture d’écran du 2023-05-02 22-40-42](https://user-images.githubusercontent.com/49676861/235783012-867c14c8-0015-443b-9b51-df3ccfd1e483.png)

and a bridge is form with hole, but there is no hole to properly form the bridge, on the last layers i hav this : 
![Capture d’écran du 2023-05-02 22-40-53](https://user-images.githubusercontent.com/49676861/235783217-00afca71-9b2c-433d-84c4-ad656a3d5a7f.png)

and i will expect something like that for the first layer

**Comment by moolight-seashell** [comment]
i think to solve this probleme the best wold probaly be to create e a new settings like "smallest inside hole allowed" in mm2 (probably intermediate or advanced setting)

and when a inside hole is smaller than the settings , the sliscer must be ingoring the hole making a full bridged surface.

in other hand, when the hole is equals ou greater than the settings, the sliscer generate inside perimeters for at least the first bridged layer
