### ISSUE TITLE
Where are the Bridging Perimeters ?

### ISSUE THREAD

**Issue by neophyl** [supermerill/SuperSlicer#1186]
**Describe the bug**
With a profile that is pretty much a default MK3 0.2 speed profile I was slicing some stuff and noticed I didnt seem to be getting any bridge perimeters anymore.  Its all Bridge Infill or Internal bridge infill (cant tell as the colours are so similar).

I played around with the Overhang thresholds and even setting 1%, 99% or 200% does not get me bridging perimeters where there normally are.  I also tried 0 to disable but its the same for all of them.
Hoping this is just a settings issue.

To illustrate I downloaded a bridging test for this attached project. 

![no bridge perimeters](https://user-images.githubusercontent.com/46955527/119825241-a71b2500-beee-11eb-8bb2-d7be4f6f1c36.jpg)

**>> Project File <<**
[Where is the bridge perimeter.zip](https://github.com/supermerill/SuperSlicer/files/6553893/Where.is.the.bridge.perimeter.zip)

**Expected behavior**
I would expect the bridging perimeter to be detected

**Desktop (please complete the following information):**
 - OS: Windows 10
 - V2.3.56 (Better Spacing version)

**Comment by supermerill** [comment]
That was made for #764
But now that I re-think of this, it was a bad idea, I'll do something to make it better.
