### ISSUE TITLE
glitch when switching to regular layour

### ISSUE THREAD

**Issue by Liger0** [supermerill/SuperSlicer#1188]
**Describe the bug**
there's a white bar on the top when switching from old to regular layour

**To Reproduce**
1. switch to the old layou
2. Switch back to the regular layour

**Expected behavior**
no visual glitch

**Screenshots**
![glitch white bar](https://user-images.githubusercontent.com/20385116/119847361-346c7280-bf0b-11eb-920b-6c3681eed2a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version last debug

**Additional context**

**Comment by supermerill** [comment]
yes, can't find the command that should make that disappear. Lost hope after few hours.
just resize the window and forgot these seconds for the rest of the eternity
