### ISSUE TITLE
Artifact around a box

### ISSUE THREAD

**Issue by Liger0** [supermerill/SuperSlicer#1192]
**Describe the bug**
There's a weird artifact around a box (not translation related)

**To Reproduce**
1. Go to Printer settings -> General
2. Look at the thumbnail category

**>> Project File <<**
*Please* upload a ZIP archive containing the project file used when the problem arise. Please export it just before the problem occur. Even if did nothing and there is no object, export it as it contains your current configuration.

**Expected behavior**
no artifact?

**Screenshots**
![artefact thumbnail](https://user-images.githubusercontent.com/20385116/119894054-6a761a80-bf3c-11eb-85d7-130b187cfbe3.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version Better spacing and others

**Additional context**

**Comment by csch0** [comment]
Its fixed now with this commit: https://github.com/supermerill/SuperSlicer/commit/3ed01dad9cce4035cbd71c3d03363955867a12e4

Nice work, was just about to fix the same.

**Comment by supermerill** [comment]
it was the 'big:' label that was misplaced.
fixed some other bugs, like missing "reset"
