### ISSUE TITLE
Question: Way to control retracted vs un-retracted travels?

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#1193]
SS seems to do both retracted travels and un-retracted travels (combing in Cura). But I can't find any settings that govern which is used, and where. Examples:

- Maximum length of un-retracted travels
- Where are un-retracted travels allowed? (1st layer, solid infill, sparse infill)
- Ooze compensation for un-retracted travels (ideally based on distance or time)

Do any of these controls exist, or would all of these be feature requests?

**Comment by supermerill** [comment]
> Maximum length of un-retracted travels

minimum length after retraction

> Where are un-retracted travels allowed? (1st layer, solid infill, sparse infill)

everywhere

> Ooze compensation for un-retracted travels (ideally based on distance or time)

extra length on restart

**Comment by CCS86** [comment]
> > Maximum length of un-retracted travels
> 
> minimum length after retraction


Isn't this the minimum length of print move required after a retraction, before another retraction is allowed? 

That would be quite a bit different from the "maximum length of un-retracted travel"


> > Where are un-retracted travels allowed? (1st layer, solid infill, sparse infill)
> 
> everywhere


This could be a useful setting to have.


> > Ooze compensation for un-retracted travels (ideally based on distance or time)
> 
> extra length on restart


Again, correct me if I am wrong, but this is an extra length applied to the un-retraction move. Since un-retracted travels don't have this move, I assume it wouldn't be applied.

Ideally this is never used because retraction should be well tuned to not lose filament. But with un-retracted travels, ooze is unavoidable, especially on a bowden printer.

**Comment by supermerill** [comment]
> Isn't this the minimum length of print move required after a retraction, before another retraction is allowed?

the tooltip say: `Retraction is not triggered when travel moves are shorter than this length.`

> This could be a useful setting to have.

you can add a modifier, for the first layer for example. Automated modifiers aren't here yet.

> Again, correct me if I am wrong, but this is an extra length applied to the un-retraction move. Since un-retracted travels don't have this move, I assume it wouldn't be applied.

Oh, yes. As not-retracted moves are only short (because of `minimum length after retraction` setting) there wasn't any need for that. This setting is still a stop-gap.

**Comment by CCS86** [comment]
> > Isn't this the minimum length of print move required after a retraction, before another retraction is allowed?
> 
> the tooltip say: `Retraction is not triggered when travel moves are shorter than this length.`

Maybe the tooltip is wrong? Or does this same setting behave differently in SS?

https://manual.slic3r.org/expert-mode/fighting-ooze#:~:text=Minimum%20travel%20after%20retraction%20%2D%20Triggering,move%20before%20considering%20a%20retraction.



> > Again, correct me if I am wrong, but this is an extra length applied to the un-retraction move. Since un-retracted travels don't have this move, I assume it wouldn't be applied.
> 
> Oh, yes. My bad. As not-retracted moves are only short (because of `minimum length after retraction` setting) there wasn't any need for that. This setting is still a stop-gap.


Depending on the answer about the setting above, there might be a good use for a sister-setting for un-retracted travels, ideally as a length of travel multiplier.

**Comment by CCS86** [comment]
I'm pretty sure that tool tip is wrong. I have minimum length after retraction set to 2mm and it is doing easily 20mm long un-retracted travels.

**Comment by supermerill** [comment]
> Maybe the tooltip is wrong? Or does this same setting behave differently in SS?

Weird, as this tooltip was created by the original slic3r author in 2015. I'll dive into the code to verify, but it should be good.

**Comment by CCS86** [comment]
Check this layer out. That is a **ton** of un-retracted travel:

![image](https://user-images.githubusercontent.com/12439543/119920459-ffbfe180-bf31-11eb-9e52-178f19e5b82a.png)

**Comment by CCS86** [comment]
Well shoot. It appears that the "only retract when crossing perimeters" setting was enabled and causing this behavior. With that disabled, the "minimum length after retraction" setting, while misleadingly named, behaves like the tool tip states. 

I think a more accurate name would be "maximum length for un-retracted travel"; or "minimum travel length to trigger retraction". 

 Cura has a similarly named setting that behaves as the name suggests:

![image](https://user-images.githubusercontent.com/12439543/120226422-c8d91c80-c20c-11eb-9000-a376626ff1d7.png)
