### ISSUE TITLE
[BUG] Support interface generated midair

### ISSUE THREAD

**Issue by qwewer0** [supermerill/SuperSlicer#1199]
**Describe the bug**
Support interface generated midair without any support base bellow it.

**>> Project File <<**
[overhang-test.zip](https://github.com/supermerill/SuperSlicer/files/6564561/overhang-test.zip)

**Expected behavior**
Support interface should have a support base.

**Screenshots**
![bandicam 2021-05-29 13-02-12-524](https://user-images.githubusercontent.com/57561110/120067985-b03afc00-c07e-11eb-91d5-8f696f229317.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.3.56.1

**Comment by supermerill** [comment]
>< Not now!

**Comment by neophyl** [comment]
Given this is the same in PS 2.3 and that the PS 2.4 release when it happens is supposed to be targeting a lot of support issues I would wait until merging with 2.4.  No point try to fix code that will be updated and changing anyway as that sounds like a lot of wasted effort lol.

**Comment by ashleyuk90** [comment]
Was told to move my issue here from 1272, just checked the stl in the ZIP of this issue against PS 2.3.1 and the supports are fine. So the issue is defiantly for both the attached and my example within some code of SS and not what was merged from PS 2.3.1 recently, or may be merged from 2.4.0 unless it would overwrite any custom SS support code?

**Comment by supermerill** [comment]
There is definitely an issue in a change I made last year in the support code.

**Comment by supermerill** [comment]
As expected, it was painful.
it's a difference of 0.00000001 mm in a variable that makes the rectilinear miss the threshold because the float is floored a little bit too early.

**Comment by qwewer0** [comment]
Fixed. Tested it on the latest release.
