### ISSUE TITLE
Gcode preview is missing lines when start_gcode_manual and use_relative_e_distances are turned on

### ISSUE THREAD

**Issue by rsghosh** [supermerill/SuperSlicer#1201]
**Describe the bug**
If both start_gcode_manual and use_relative_e_distances are set to 1, the gcode preview is missing line segments. However, the sliced preview looks fine. The problem only occurs if both of these are turned on, turning either off makes it disappear.

**To Reproduce**
1. Go to printer settings > custom G-code, and check "Only custom Start G-code"
2. Go to printer settings > General, and check "Use relative E distances"
3. Slice a model and look at the Gcode preview

**>> Project File <<**
[calicat.zip](https://github.com/supermerill/SuperSlicer/files/6565651/calicat.zip)

**Expected behavior**
Turning on start_gcode_manual and relative_e_distances should not affect the gcode preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/56000109/120091007-c87d3c00-c0bb-11eb-90dc-f140e5246924.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 2.3.56.1

**Comment by supermerill** [comment]
You forgot to add `M83 ; use relative distances for extrusion` to your start gcode.
If you want it to be added automatically, add `{if use_relative_e_distances}M83 ; use relative distances for extrusion{endif}`

if you select "Only custom Start G-code" be **sure** to put in your custom start gcode all the required init command!

**Comment by rsghosh** [comment]
Ah. I normally use a klipper macro for my start gcode and put `print_start PA=0.0426 EXTRUDER=[first_layer_temperature] BED=[first_layer_bed_temperature]` in the start_gcode, and the macro calls M83. I'll make sure to put M83 before print_start then so the slicer sees it. Thanks!
