### ISSUE TITLE
Display of Creality models is incorrect

### ISSUE THREAD

**Issue by sziga** [supermerill/SuperSlicer#1209]
Only 4 Creality models are displayed in the configuration wizard.
Missing e.g. Ender3V2, Ender5, Ender2 etc.
They are listed in the profile file (Creality.ini).
For the models that are displayed, the images are not displayed.
The images can be found in the Creality library
![creality](https://user-images.githubusercontent.com/49403033/120210814-81648780-c230-11eb-8a36-67f057582614.jpg)

**Comment by supermerill** [comment]
can't reproduce
what is the version?

**Comment by sziga** [comment]
version: SuperSlicer_2.3.56.1_win64_210527

**Comment by supermerill** [comment]
can't reproduce on a fresh install
![image](https://user-images.githubusercontent.com/6536403/120399285-fa043a80-c33b-11eb-9dae-c6bf75cc6033.png)

**Comment by sziga** [comment]
Deleting the file C:\Users\ \AppData\Roaming\SuperSlicer\vendor\Creality.ini solved the problem.
A file version 0.2.5 was in the directory.
Thanks for your help!
