### ISSUE TITLE
Strange Solid infill

### ISSUE THREAD

**Issue by chripink** [supermerill/SuperSlicer#1217]
Hi, 

I installed the last version of SuperSlicer 2.3.56 W64 and I have an issue with the Solid Infill. 

Solid Infill is generated near my perimeters as in the picture. 
Is it a bug or a feature that I have to desactivate (but I don't find where...)
![image](https://user-images.githubusercontent.com/17579251/120281771-a3561c80-c2b9-11eb-80c5-241d8e61d4e4.png)

The used profile is the one for the Sidewinder X1

Here the STL used is a benchy

Thank you,

Christophe

**Comment by supermerill** [comment]
It's often an artefact of the number of bottom layers.
there already many issues about that.
Only way currently is to add a modifier to reduce the number of bottom layers on layers 4-end

**Comment by chripink** [comment]
Ok :)

Thank you for your answer 👍
