### ISSUE TITLE
[FR] XY Deceleration in Machine limits

### ISSUE THREAD

**Issue by qwewer0** [supermerill/SuperSlicer#1222]
**Description**
If there would be a deceleration setting for X and Y axis in Printer Settings/Machine limits, that could make the time estimation to be a bit more precise, if a different deceleration value is used in the printer (Klipper), and if used for printing too, than it might reduce ringing/echo a bit.

**Comment by supermerill** [comment]
why deceleration different than acceleration?

**Comment by qwewer0** [comment]
> why deceleration different than acceleration?
> For the time estimation, it's marlin-based and I don't have time to tune it this year (and the next).

@supermerill
If we take a cube as an example, a relatively high acceleration/deceleration value, would cause more ringing on the following side after the corner, than with a lower value, but for acceleration a higher value is more forgiving for quality.

The main point is, that a lover deceleration value (half?) compared to the acceleration would result a cleaner print surface compared to the same high acc/dec values, or if we would keep the deceleration as default and only increase the acceleration, than the print time would shorten a bit, while the quality would mostly stay the same.

At least this is my idea...

**Comment by supermerill** [comment]
I checked but I can't find a firmware that has a setting to control deceleration. And so I can't separate acceleration from deceleration.

**Comment by qwewer0** [comment]
> I checked but I can't find a firmware that has a setting to control deceleration. And so I can't separate acceleration from deceleration.

In Marlin there isn't an option for that, yet.

But here is a [link](https://github.com/KevinOConnor/klipper/blob/master/docs/Config_Reference.md#printer) for Klipper `max_accel_to_decel`.

**Comment by supermerill** [comment]
> > I checked but I can't find a firmware that has a setting to control deceleration. And so I can't separate acceleration from deceleration.
> 
> In Marlin there isn't an option for that, yet.
> 
> But here is a [link](https://github.com/KevinOConnor/klipper/blob/master/docs/Config_Reference.md#printer) for Klipper `max_accel_to_decel`.

that's not a decel command, but a kind of max_speed.

**Comment by qwewer0** [comment]
> that looks like a kind of max_speed, not a decel command.

I will close this for now.
