### ISSUE TITLE
Extruder retraction calibration produces incorrect retractions for manually entered step sizes

### ISSUE THREAD

**Issue by mhalle** [supermerill/SuperSlicer#1228]
**Describe the bug**
In the extruder retraction calibration, manually typing in a value for "step" changes the incremental retraction distance to a small constant (0.01).
**To Reproduce**
1. Go to 'Calibration -> Extruder retraction calibration'
2. Click on 'step" and type in a values such as "0.3". 
3. Generate the test pattern.
4. Inspect the retraction lengths in the right panel. They go up from 0 by steps of 0.01.

**>> Project File <<**
No project file.

**Expected behavior**
Manually entered setps should be reflected accurately.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 2.3.26.1

**Additional context**
Alternatively, the pulldown could be modified to not allow values to be typed in.

**Comment by supermerill** [comment]
These aren't designed to be modified.
I have to protect them.
