### ISSUE TITLE
Feature Request: Material weight/length with estimated print time for colour changes

### ISSUE THREAD

**Issue by LaserBee** [supermerill/SuperSlicer#123]
Hopefully this is the right place to ask for features...

I do a lot of multi-colour prints, using your absolutely wonderful tool to pause the print at different layer heights. I love the fact that it gives me an estimate for the time for each section. Would it also be possible for it to give me an estimate on how much filament each section will use? It tells me how much filament is used for the whole project, but breaking it down by colour would be amazing. That would be really helpful as I have a ton of small filament samples, and am never quite sure if I will have enough of one colour to do a section. 

It's not a big deal, but it would be helpful!

**Comment by supermerill** [comment]
should be merged.
