### ISSUE TITLE
Debug check failed when switching printer profiles

### ISSUE THREAD

**Issue by kaibsora** [supermerill/SuperSlicer#1232]
**Describe the bug**
when switching profiles, you are presented with a debug check has failed window.

**To Reproduce**

Upon unzipping application on windows, open the app
choose 2 printers and click finish
try to switch between printer a and printer b
debug check appears
vice versa when going from printer b to printer a

**Expected behavior**
no debug check?

**Screenshots**
screenshot attached
![debug check](https://user-images.githubusercontent.com/28906631/120592623-2d15ff00-c40c-11eb-8cb2-21d79737e7b9.png)
**Desktop (please complete the following information):**
 - OS:windows
 - Version 2.3.56.1

**Additional context**
you can click continue and it goes away. but it comes back whenever you switch.
![debug check](https://user-images.githubusercontent.com/28906631/120592623-2d15ff00-c40c-11eb-8cb2-21d79737e7b9.png)

**Comment by supermerill** [comment]
can reproduce with 2.3.56.1 but not with the nigthly, should be fixed

**Comment by kaibsora** [comment]
Thank you so much for the awesome work you do! I know you dont hear that enough!
