### ISSUE TITLE
Wrong settings for extrusion width for new profiles

### ISSUE THREAD

**Issue by uepsie** [supermerill/SuperSlicer#1235]
When creating a new profile with the configuration wizard, the extrusion width defaults are set to mm instead of %

**Screenshots**
![image](https://user-images.githubusercontent.com/304272/120676817-b70aaa00-c496-11eb-987d-485423c3ab3f.png)

![image](https://user-images.githubusercontent.com/304272/120676845-bd992180-c496-11eb-95fb-55ae08224dbb.png)

**Desktop (please complete the following information):**
- Win 10

**Additional context**
SuperSlicer 2.3.56.1

**Comment by supermerill** [comment]
lol, nice catch.
