### ISSUE TITLE
Wrong option (typo) recommended in case of open-gl problem

### ISSUE THREAD

**Issue by uepsie** [supermerill/SuperSlicer#1236]
**Describe the bug**
just two typos:
it's --sw-renderer and not prusa-slicer ;-)

**Screenshots**
![image](https://user-images.githubusercontent.com/304272/120677443-5e87dc80-c497-11eb-9a5a-50553afaf821.png)

**Additional context**
SuperSlicer 2.3.56.1

**Comment by supermerill** [comment]
They put a '-' !

**Comment by uepsie** [comment]
Yeah. Confusing! ;-)
