### ISSUE TITLE
UI shaking before and after slice action

### ISSUE THREAD

**Issue by uocnb** [supermerill/SuperSlicer#1241]
**Describe the bug**
Sidebar and main view UI are jumping / shaking before and after slice due to `Sliced info` section only visible after sliced. 

**To Reproduce**
1. Import model
2. Select model
3. Add object settings to fill the empty space above `Info` section and make sure no scrollbar show yet.
4. Click on Slice button
5. Scrollbar show because of additional section `Sliced info` just added to the sidebar caused the sidebar shaking.
6. 3D Plater tab switched to GCode preview tab caused UI shaking.

**Expected behavior**
Consistence UX without jumping / shaking before and after slice action.

**Screenshots**
Before slice: 
![image](https://user-images.githubusercontent.com/170867/120782371-2397ae80-c554-11eb-9183-fd13702b7111.png)

After slice:
![image](https://user-images.githubusercontent.com/170867/120782446-3316f780-c554-11eb-94d8-743e8fd76eeb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.3.56.1

**Comment by supermerill** [comment]
can you try with the latest nightly? I fixed a "shaking" but I don't know if it's that.

**Comment by uocnb** [comment]
Cool, I will try it tonight.

**Comment by supermerill** [comment]
can't reproduce with my dev build, or I miss something.

**Comment by uocnb** [comment]
Just checked, I'm using the latest build downloaded from git release page already.

**Comment by supermerill** [comment]
https://github.com/supermerill/SuperSlicer/suites/2905660844/artifacts/65159859
from https://github.com/supermerill/SuperSlicer/actions

**Comment by uocnb** [comment]
Thank @supermerill! It's definitely better with the nightly build!
