### ISSUE TITLE
Gaps in first layer

### ISSUE THREAD

**Issue by G-r-i-s-h-U** [supermerill/SuperSlicer#1242]
**Describe the bug**
This version (unlike some previous) leaves unfilled gaps in first layer.

**To Reproduce**
Slice a part with holes around the perimeters (or sharp edges).

**Expected behavior**
Expect to fill them all, not just partly.

**Screenshots**
Attaching screenshots from current version (2.3.56.0) and a previous one (2.3.55.2) (both using same profiles).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.3.56.0

![2 3 55 2](https://user-images.githubusercontent.com/85356169/120821211-efc18680-c55d-11eb-8cab-4cb13ec19d7c.JPG)
![2 3 56 0](https://user-images.githubusercontent.com/85356169/120821618-5050c380-c55e-11eb-97db-3b06f482bc71.JPG)

**Comment by supermerill** [comment]
I need your project file

**Comment by G-r-i-s-h-U** [comment]
Here it is. (I have archived it, since it doesn't want to upload as *.3mf)
[Case_Cap.zip](https://github.com/supermerill/SuperSlicer/files/6599526/Case_Cap.zip)

**Comment by supermerill** [comment]
Same issue as #1214, i'll close this one.
