### ISSUE TITLE
Compile failure: conversion from ‘wxString’ to non-scalar type

### ISSUE THREAD

**Issue by VanessaE** [supermerill/SuperSlicer#1243]
This is in Debian Bullseye, and I last brought in system updates a few days ago.

Git pulled and tried to compile, and got this error part way through:

```cmake
In file included from /home/vanessa/RepRap/SuperSlicer/src/slic3r/GUI/OptionsGroup.hpp:14,
                 from /home/vanessa/RepRap/SuperSlicer/src/slic3r/GUI/Preferences.cpp:2:
/home/vanessa/RepRap/SuperSlicer/src/slic3r/GUI/Preferences.cpp: In member function ‘void Slic3r::GUI::PreferencesDialog::create_settings_mode_widget()’:
/home/vanessa/RepRap/SuperSlicer/src/slic3r/GUI/I18N.hpp:3:47: error: conversion from ‘wxString’ to non-scalar type ‘std::wstring’ {aka ‘std::__cxx11::basic_string<wchar_t>’} requested
    3 | #define _L(s)     Slic3r::GUI::I18N::translate((s))
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
```

While I didn't have the patience :smile: to bisect, I did at least try rolling back a bit.

Only took me one try: it compiles fine at commit f7ecd99f4de17fea6c7d2519f49acecc4311f58c, which Github shows to be the last commit made yesterday, but at commit ce024979effc077aaf0c43405efe367a52472c18, which is HEAD at this moment, it fails with the above error.

**Comment by supermerill** [comment]
I was just celebrating a no-string-conversion error in all three (win, mac & Linux) compilers with my new release.
At least it's an easy fix.
