### ISSUE TITLE
Internal error: invalid string position

### ISSUE THREAD

**Issue by simenon** [supermerill/SuperSlicer#1244]
### Version
2.3.56

### Operating system type + version
Windows

### Behavior
Superslicer crashes at startup 
![image](https://user-images.githubusercontent.com/6181557/120848161-bcd6bd00-c574-11eb-9646-41fc9128eaa2.png)

**Comment by supermerill** [comment]
can you zip and post here your setting directory (should be c:/user/yourname/appdata/roaming/superslicer) ?

**Comment by DKB234** [comment]
I had that same problem as 'simeon' and to fix it I renamed this file ' c:/user/yourname/appdata/roaming/superslicer.ini' and it now loads. I renamed the file just in case I was wrong, bu all good for me. 
![image](https://user-images.githubusercontent.com/33344047/120885910-b73dad80-c62e-11eb-9ce4-509a527cb46d.png)
If this image is vewable you can see the difference. Left one works, right side caused the crash.

**Comment by supermerill** [comment]
should be fixed in nighty

**Comment by simenon** [comment]
[SuperSlicer.zip](https://github.com/supermerill/SuperSlicer/files/6602427/SuperSlicer.zip)
Adjusting only the ini file does not work for me. Included my settings directory
