### ISSUE TITLE
2.3.56 - Bed on thumbnail uncheck still generate bed on thumbnail

### ISSUE THREAD

**Issue by excessnet** [supermerill/SuperSlicer#1245]
**Describe the bug**
If you uncheck the box "Bed on thumbnail", the bed is still shown on the thumbnail on Mainsail.

![image](https://user-images.githubusercontent.com/37947369/120848835-4a011e00-c543-11eb-91f6-3a5d1536b591.png)

Up : with 2.3.56.2
Buttom : with 2.3.55.x
![image](https://user-images.githubusercontent.com/37947369/120848882-5e451b00-c543-11eb-8514-7e7fad0bbdb9.png)

**Comment by millerlarson** [comment]
For what it's worth, I just upgraded to 2.3.56.3 and I'm still seeing the bed image when the "Bed on thumbnail" option is unchecked.

**Comment by supermerill** [comment]
> For what it's worth, I just upgraded to 2.3.56.3 and I'm still seeing the bed image when the "Bed on thumbnail" option is unchecked.

I just checked and there is no more bed on my 3mf, small thumbnail and big thumbnail.
