### ISSUE TITLE
differences with Prusaslicer

### ISSUE THREAD

**Issue by wnc2** [supermerill/SuperSlicer#1250]
**Describe the bug**
the same stl is sliced very different, with a lot of issues
**To Reproduce**

**>> Project File <<**

[Archive.zip](https://github.com/supermerill/SuperSlicer/files/6602314/Archive.zip)

**Expected behavior**
i should see a very similar result

**Screenshots**
![Schermata 2021-06-05 alle 11 39 16](https://user-images.githubusercontent.com/43959480/120887420-0bc33780-c5f3-11eb-9a46-b1d767649520.jpg)
![Schermata 2021-06-05 alle 11 39 06](https://user-images.githubusercontent.com/43959480/120887421-0ebe2800-c5f3-11eb-9b12-06714a325f73.jpg)

**Desktop (please complete the following information):**
MACOS
2.3.56

**Additional context**
i have this issue since a lot of releases

**Comment by supermerill** [comment]
it's because the "only one perimeter on top" is detecting area too thin and so deactivate itself.
Deactivate the option.

**Comment by wnc2** [comment]
![Schermata 2021-06-05 alle 11 57 53](https://user-images.githubusercontent.com/43959480/120887837-61004880-c5f5-11eb-9436-08122a262a98.jpg)

this is the result, not identical but much better.

Thanks

**Comment by supermerill** [comment]
if you want to get back overlapping perimeter, check the option. It will overextrude the letters a bit... nothing to worry in this case.

**Comment by wnc2** [comment]
![Schermata 2021-06-05 alle 12 10 47](https://user-images.githubusercontent.com/43959480/120888173-25667e00-c5f7-11eb-8fa6-6107acfc92b5.jpg)

overlapping is checked by default, checking also "also for all perimeter" result is identical.

many thanks
