### ISSUE TITLE
[BUG] Wrong minimum limit value in legend

### ISSUE THREAD

**Issue by qwewer0** [supermerill/SuperSlicer#1260]
**Describe the bug**
SuperSlicer shows wrong (lower) minimum limit value for flow in legend, than what is used in the print, which is different in the gcode viewer.

**Project File**
[bridge_angle_test_five_arms.zip](https://github.com/supermerill/SuperSlicer/files/6602699/bridge_angle_test_five_arms.zip)

**Expected behavior**
The minimum and maximum values in legend should come from the sliced project.

**Screenshots**
Gcode viewer:
![bandicam 2021-06-05 16-38-08-064](https://user-images.githubusercontent.com/57561110/120895463-44780680-c61d-11eb-8d9f-9467b17d596e.jpg)

Inside SuperSlicer:
![bandicam 2021-06-05 16-40-11-327](https://user-images.githubusercontent.com/57561110/120895466-4772f700-c61d-11eb-9811-2fbc8331a9b0.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.3.56.2 (Nigthly windows x64 [#5](https://github.com/supermerill/SuperSlicer/actions/runs/909270246))

**Comment by supermerill** [comment]
I have min at 2.4 in 2.3.56.2
I have mina t 3.1 in dev build

So maybe fixed...

**Comment by qwewer0** [comment]
> I have min at 2.4 in 2.3.56.2
> I have mina t 3.1 in dev build
> 
> So maybe fixed...

Yes, it seems to be fixed, thanks.
