### ISSUE TITLE
Languages display error

### ISSUE THREAD

**Issue by sziga** [supermerill/SuperSlicer#1261]
There are problems with the display of languages.
Even though it is translated and included in the language files (.po, .mo), many of the terms appear in English.
E.g. "Andvanced", "Remember to check for updates at" and many more.
Version:SuperSlicer_2.3.56.2_win64_210604 but the problem persists with the previous version.
Example images in Italian, Czech and Japanese.
![it](https://user-images.githubusercontent.com/49403033/120896657-cfa7cb00-c622-11eb-8371-7ca3a51f5a3e.jpg)
![cs](https://user-images.githubusercontent.com/49403033/120896671-d8989c80-c622-11eb-8469-297541e6e8ef.jpg)
![ja](https://user-images.githubusercontent.com/49403033/120896684-e0584100-c622-11eb-82ca-9f3ddc9b4992.jpg)

I put the Italian language file into PrusaSlicer-2.3.1 and it displays everything in Italian without any errors.
![itprusa](https://user-images.githubusercontent.com/49403033/120896694-efd78a00-c622-11eb-83b0-aa8b1c4007f0.jpg)

**Comment by supermerill** [comment]
That's because the translations weren't updated. I don't speak japanese.

**Comment by sziga** [comment]
Are typed in Italian .po file and do not appear the same! the file is moved to PrusaSlicer (see picture 4) to display the expressions.
Italian .po file
Line 736
msgid "Advanced"
msgstr "Avanzato"

Line 7876
msgid "Remember to check for updates at "
msgstr "Ricorda di controllare gli aggiornamenti dell'applicazione"

**Comment by supermerill** [comment]
please use the thread #1128 to talk about improving the italian translation.
I work a bit to ease a bit the burden to update a translation (I'm working on the french one when I'm disconnected from the internet). But it's not my absolute priority.
