### ISSUE TITLE
GUI issues related to spacing settings

### ISSUE THREAD

**Issue by JohanAR** [supermerill/SuperSlicer#1270]
**Describe the bug**
See comments on screenshots

**Screenshots**
After starting SuperSlicer 2.3.56.3 with my existing profiles:
![image](https://user-images.githubusercontent.com/4918549/121028233-efb4c700-c7a7-11eb-9892-4c75f7d8831d.png)
1. "spacing" is written with black text
2. "support material" and "skirt" are written with green text, while the others are white. It looks quite arbitrary, but is there some special meaning of green fields?

After resetting spacing by clicking the blue padlock:
![image](https://user-images.githubusercontent.com/4918549/121029002-884b4700-c7a8-11eb-93d6-ff55b785570f.png)
1. "width" is now black
2. "spacing" turns orange
3. skirt resets to "120%" despite the unit type is only listed as "mm"

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 2.3.56.3 and also on current master

**Comment by supermerill** [comment]
For the signification of green and the other colors & icon, clic on the `?` icon

As the system value may ahve been changed with the new version, lock & green text may have changed at the same time.

**Comment by JohanAR** [comment]
Sorry, I guess I was a bit confused by never having seen black before, and I forgot that they turn orange sometimes..

I guess the only remaining error is that skirt says that it can only be "mm" while it ought to be "mm or %" then?

**Comment by supermerill** [comment]
yes
