### ISSUE TITLE
macOS 2.3.56.3 installs as 2.3.56.2

### ISSUE THREAD

**Issue by Jarery** [supermerill/SuperSlicer#1271]
### Version
SuperSlicer_2.3.56.3_macos_210605.dmg

### Operating system type + version
BigSur 11.2.3

### Behavior
- download SuperSlicer_2.3.56.3_macos_210605.dmg
- install
- start application
- application loads, says version is 2.3.56.2 on opening screen and gives notification a new release is available.

**Comment by supermerill** [comment]
seems like the build didn't pick the version change. Seems like only the win build pick the right version file. Weird.
