### ISSUE TITLE
Supports being printed in mid air

### ISSUE THREAD

**Issue by ashleyuk90** [supermerill/SuperSlicer#1272]
Have just tried out SuperSlicer from using Prusa Slicer previously, using the same support settings (have tried all 3 support Patterns) I have noticed SuperSlicer in quite a few places is not building the correct support structure and instead is trying to print the support material interface in mid-air.

PrusaSlicer
![image](https://user-images.githubusercontent.com/14320114/121050773-7212aa80-c7eb-11eb-84b3-56af6bd403ba.png)

SuperSlicer
![image](https://user-images.githubusercontent.com/14320114/121050879-89ea2e80-c7eb-11eb-966b-5ccd8428345c.png)

Support Settings
![image](https://user-images.githubusercontent.com/14320114/121050921-953d5a00-c7eb-11eb-9a48-a6f3d611663e.png)

**Comment by qwewer0** [comment]
https://github.com/supermerill/SuperSlicer/issues/1199 Related?

**Comment by ashleyuk90** [comment]
> 
> 
> #1199 Related/duplicate?

Maybe, but my understanding from that bug the issue also showed in PS? I am running the same version of PS that was recently merged into SS. So it seems more something custom/change in SS that's breaking it compared to the still issues that PS are working on with their supports in general.

**Comment by supermerill** [comment]
please use the thread 1199 .
