### ISSUE TITLE
[FR] Gap Fill Using Fixed Volumetric Rate

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#1275]
Printers (especially bowden) struggle with rapid changes to commanded volumetric flow rate. Gap filling moves have a tendency to create large volumetric rate changes, across small distances. Also, my gut says that it is harder to fill a 0.8mm wide gap, at some given flow rate, than it is to lay down a 0.4mm line, at the same flow rate (0.4mm nozzle). This would further exacerbate the issue of under-extruding in high flow + wide gap fill areas.

The tool tip recommends setting a very slow gap filling speed, to avoid this very issue. But, it creates a new one, which is over-extruding very thin gap fill areas. 

I think that allowing the user to define a volumetric rate to fill gaps would solve both. 

It would make sense to put a speed maximum against this calculation as well.

![image](https://user-images.githubusercontent.com/12439543/121102418-20562a00-c7c3-11eb-88d1-7f13b7c06601.png)

**Comment by qwewer0** [comment]
> But, it creates a new one, which is over-extruding very thin gap fill areas.

I also experiencing it, and always felt weird that the gap fills were overextruding on my well tuned (direct drive) system.

> I think that allowing the user to define a volumetric rate to fill gaps would solve both.

Not sure if I understand it correctly, do you mean, to have an option to control the gap fill flow rate as a percentage?

**Comment by CCS86** [comment]
Not as a percentage, but as a fixed volumetric flow rate.

[Layer height] x [line width] x [speed] = volumetric flow rate

So, if most of your print is 0.2 x 0.4 x 60 = 4.8 mm^3/s, you might want to define gap filling to hold that rate.

Each segment of gap fill would work from that defined flow rate, to calculate the segment speed. A 0.2mm wide gap fill would print at 120 mm/s, and a 0.8mm wide segment would print at 30 mm/s

**Comment by CCS86** [comment]
Correct. At least as an option.

**Comment by CCS86** [comment]
Hey @supermerill , just wanted to ping on this request and see where it stands. I think it would really help the fact that we still have gap fills that range from very wide to very thin.

**Comment by supermerill** [comment]
There is currently max volumetric (from filament) and speed.
If you put a high speed, it should follow the filament max volumetric, but on the small extrusions where it should be capped by the speed.

What I can add is a max volumetric acceleration (mm3/s2) to reduce the speed if the volumetric speed is changing a lot. But this may need a substantial change in the gcode code.

**Comment by CCS86** [comment]
> There is currently max volumetric (from filament) and speed. If you put a high speed, it should follow the filament max volumetric, but on the thin extrusions where it should be capped by the speed.
> 
> What I can add is a max volumetric acceleration (mm3/s2) to reduce the speed if the volumetric speed is changing a lot. But this may need a substantial change in the gcode code.


I think the biggest issue with that approach is if you want to run a significantly higher volumetric flow rate on sparse/solid infill to save time. Inherently, you will have a lower flow rate in your perimeters when looking for good quality, and matching the perimeter flow rate would likely be better for gap filling.

Would it be easier to just allow gap filling to have a 3rd definition type in the same input field (%, mm/s, mm^3/s)? or even just a checkbox to "match perimeter flow rate". When checked, it would calculate the perimeter flow rate, and use that with the width of each gap fill segment to calculate segment speed (capped by the max defined print speed).

**Comment by supermerill** [comment]
the "match perimeter flow rate" is a good idea.

**Comment by CCS86** [comment]
Thank you!

**Comment by CCS86** [comment]
Oh man, this new setting is next level!!!

Thanks again Merill!

![image](https://user-images.githubusercontent.com/12439543/180584056-81dd3c06-59ae-4f09-8cbc-1f5b54b92740.png)
