### ISSUE TITLE
SuperSlicer-ubuntu_18.04-2.3.56.3.AppImage is compiled as 2.3.56.2

### ISSUE THREAD

**Issue by moodytechz** [supermerill/SuperSlicer#1276]
![image](https://user-images.githubusercontent.com/56782273/121109672-df5d1600-c7c0-11eb-9454-d93d3e569d09.png)

![image](https://user-images.githubusercontent.com/56782273/121109740-fbf94e00-c7c0-11eb-89e4-bb4fc040b83e.png)

**Comment by supermerill** [comment]
same bug as the macos version.
