### ISSUE TITLE
[BUG] No perimeters on bridge areas

### ISSUE THREAD

**Issue by qwewer0** [supermerill/SuperSlicer#1277]
**Describe the bug**
There seems to be something wrong with `No perimeters on bridge areas` setting.

**Project File**
[bridge_angle_test_five_arms.zip](https://github.com/supermerill/SuperSlicer/files/6613128/bridge_angle_test_five_arms.zip)

**Expected behavior**
`No perimeters on bridge areas` settings should work as intended.

**Screenshots**
`No perimeters on bridge areas` setting:
- Disabled:
![bandicam 2021-06-08 04-36-18-425](https://user-images.githubusercontent.com/57561110/121114330-ce89c000-c813-11eb-97fb-c794c35517aa.jpg)
- Remove perimeters:
![bandicam 2021-06-08 04-36-36-319](https://user-images.githubusercontent.com/57561110/121114360-dd707280-c813-11eb-9b4c-7753ba48215d.jpg)
- Keep only bridges:
![bandicam 2021-06-08 04-36-49-369](https://user-images.githubusercontent.com/57561110/121114411-ec572500-c813-11eb-89a0-f7e1f11dc298.jpg)
- Keep bridges and overhangs:
![bandicam 2021-06-08 04-37-03-000](https://user-images.githubusercontent.com/57561110/121114440-fbd66e00-c813-11eb-935a-c9e24f1c8a1d.jpg)
- Fill the voids with bridges:
![bandicam 2021-06-08 04-37-18-610](https://user-images.githubusercontent.com/57561110/121114478-0b55b700-c814-11eb-85f9-a4c58bc631d5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.3.56.3 (Nigthly windows x64 [#363](https://github.com/supermerill/SuperSlicer/actions/runs/915714312))

**Comment by supermerill** [comment]
bridge detection for this feature seems to works for the whole object layer, and so can't use different angle for each "bridge island".
I already see some same strange behavior here #1157
Big work.

**Comment by qwewer0** [comment]
Fixed on the latest [2.3.57.4](https://github.com/supermerill/SuperSlicer/releases/tag/2.3.57.4).

@supermerill Thanks for the fix, it looks perfect.
