### ISSUE TITLE
got error a toolpath outside the print area

### ISSUE THREAD

**Issue by tjengbudi** [supermerill/SuperSlicer#1279]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3039807/121122749-31974900-c84c-11eb-8295-918c67bdfe41.png)
![superslicer](https://user-images.githubusercontent.com/3039807/121122776-3a881a80-c84c-11eb-8473-5c16f16863fa.PNG)

latest release test with attached stl have error a toolpath outside the print area. i try slice with prusa slicer it is not got the same error. i already try to fix the stl and still the same. i also check to import the setting from prusa but still got the error

**To Reproduce**
[1. X axis top.zip](https://github.com/supermerill/SuperSlicer/files/6613438/1.X.axis.top.zip)
2. Click on 'slice'

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/121145169-f6424d80-c83e-11eb-8bf8-a58b7cbc5289.png)

can't reproduce, can you post here the project file (.3mf) instead of the stl?

**Comment by tjengbudi** [comment]
tried again after reboot. download superslicer again. put the object like the first picture. it is working. do not know why. i trying slicing several time before. sorry, it might cause by my pc
