### ISSUE TITLE
cannot type lower case 'e'

### ISSUE THREAD

**Issue by jltx1** [supermerill/SuperSlicer#1280]
### Version
2.3.56 (not actually)

### Operating system type + version
MacOS 10.13.6

### Behavior
I cannot type lower case 'e' in any field.  triggers "show labels" instead.

**Comment by supermerill** [comment]
same issue as #1263

**Comment by supermerill** [comment]
should be fixed in latest nightly

**Comment by jltx1** [comment]
confirmed.  closing.
