### ISSUE TITLE
Gap Fill Generated When Disabled

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#1287]
2.3.56.3 / Win10 x64

Despite disabling gap fill, I am still seeing it generated. 

![image](https://user-images.githubusercontent.com/12439543/121456059-0e16f000-c96b-11eb-8fc2-02255cfdbd91.png)

[gap-fill.3mf.txt](https://github.com/supermerill/SuperSlicer/files/6628016/gap-fill.3mf.txt)

**Comment by supermerill** [comment]
that's the infill
That's why it has (filled) in the name.

**Comment by CCS86** [comment]
Sorry

![image](https://user-images.githubusercontent.com/12439543/121532282-d177e280-c9c4-11eb-8791-85e28b6b2878.png)
