### ISSUE TITLE
Error when trying to edit the Filament selection in Configuration Wizard

### ISSUE THREAD

**Issue by Duglum** [supermerill/SuperSlicer#1292]
![2021-06-10 20_03_34-SuperSlicer](https://user-images.githubusercontent.com/85702419/121574926-0d439400-ca27-11eb-8f8f-613cb4624fcc.png)

**Comment by Duglum** [comment]
This is in v2.3.56

**Comment by Sp4rkR4t** [comment]
Just to add a note to this, if I went through the configuration wizard with default filament profiles to complete the wizard then I get a similar error message whenever I select a printer profile from the dropdown list on the main screen.

![image](https://user-images.githubusercontent.com/3926906/121671410-69013200-caa6-11eb-9957-fb6be17a0e49.png)

**Comment by supermerill** [comment]
> Just to add a note to this, if I went through the configuration wizard with default filament profiles to complete the wizard then I get a similar error message whenever I select a printer profile from the dropdown list on the main screen.
> 
> ![image](https://user-images.githubusercontent.com/3926906/121671410-69013200-caa6-11eb-9957-fb6be17a0e49.png)

You should have created a new issue for that, this will pollute this already-fixed issue.
If I understand, this error happens in a printer "swap", even if you don't touch to the wizard?
If so, can you send me your setting directory to help me reproduce that?
