### ISSUE TITLE
It is impossible to select reprapfirmware G-code flavor

### ISSUE THREAD

**Issue by vladimir-poleh** [supermerill/SuperSlicer#1293]
**Describe the bug**
It is not possible to set RepRapWirmware G-code flavor not from UI, not via direct config change.

**To Reproduce**
1. Go to 'Printer Settings'
2. Click on 'G-code flavor dropdown'
3. Scroll down to 'RepRapFirmware'
4. "Unhandled unknown exception; terminating the application." error message appears.
5. Clock "Ok" button
6. "Internal error: invalid map<K, T> key" error message appears.
7. Click "Ok"
8. Application closes.

Alternative way.

1. Open printer definition ini file in the c:\Users\username\AppData\Roaming\SuperSlicer\printer\
2. Find `gcode_flavor` configuration
3. Set `reprapfirmware` value
4. Save file
5. Open SuperSlicer
6. Error message appears
```
Failed loading the preset file:
c:\Users\username\AppData\Roaming\SuperSlicer\printer\printername.ini
Reason: ConfigBase::set_deserialize() failed for parameter "gcode_flavor", value "reprapfirmware"
```
7. Click "Ok"
8. Application closes.

**Expected behavior**
It should be possible to select RepRapWirmware G-code flavor

**Desktop**
 - OS: Windows 10
 - Version 2.3.56.4

**Comment by supermerill** [comment]
omfg, of course, i'm sumb

**Comment by vladimir-poleh** [comment]
Actual nightly build fixed this issue.

**Comment by supermerill** [comment]
yes, replaced the release by that
