### ISSUE TITLE
Setting Gcode Flavor to RepRap causes crash

### ISSUE THREAD

**Issue by Jarery** [supermerill/SuperSlicer#1304]
-open SS 2.3.56
-open Printer tab
- set GCode Flavor to reprap
- message popup 
- - Internal Error: map::at:  key not found
- press "ok"
- program exits 

**To Reproduce**
1. See above

**Desktop (please complete the following information):**
 - MacOS. 11.4

**Comment by supermerill** [comment]
can you test with the latest nightly?
https://github.com/supermerill/SuperSlicer/suites/2979655017/artifacts/67233632
