### ISSUE TITLE
Random seam position is not working

### ISSUE THREAD

**Issue by Miksu80** [supermerill/SuperSlicer#1312]
In at least few latest versions, the random seam is not working as it should:
Random seam on:
![image](https://user-images.githubusercontent.com/48354615/121837214-b7e4dc80-ccdd-11eb-8d9a-b86e1962e647.png)

Aligned seam:
![image](https://user-images.githubusercontent.com/48354615/121837258-cdf29d00-ccdd-11eb-84ed-54600a71a1b2.png)

SuperSlicer
Version: 2.3.56.5
Build: SuperSlicer_2.3.56.5
Operating System: Windows
System Architecture: 64 bit
Windows Version: Windows 10 (build 19043), 64-bit edition

**Comment by supermerill** [comment]
can't reproduce
![image](https://user-images.githubusercontent.com/6536403/121854008-e7054900-ccf1-11eb-89d9-59721caa3dd9.png)

but maybe is you share your project file?

**Comment by Miksu80** [comment]
I've had a few "issues" that could not be replicated. My config is based on a older prusaslicer -I have modified the config and saved it but the base is from 3-4 years back but could it be the reason for these weird symptoms? Ive attached the bundle and project to zip:

[Piston.zip](https://github.com/supermerill/SuperSlicer/files/6646381/Piston.zip)

**Comment by supermerill** [comment]
You're using one-loop perimeters. So the seam is placed where it's possible (where the gap between the outer perimeter and the inner one is the smallest). I didn't add much more options than "near" and "rear" for this one. Now that prusa has moved the seam selection in a new class, maybe i can reuse it a bit to add a bit more options...

**Comment by Miksu80** [comment]
Ok, didnt see their connection to each-other, thanks.
