### ISSUE TITLE
Calibration Cube naming sticky

### ISSUE THREAD

**Issue by a7hybnj2** [supermerill/SuperSlicer#1315]
If you "calibration - calibration cube - standard cube" it will result in the auto generated file names on "export g-code" for all future slices to be "calibration cube". So, once you clear the calibration cube and add a new .stl to be sliced it will have the auto-generated filename be "calibration cube". The only way I could find to fix this was to restart the application.

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Version 2.3.56.5

**Comment by supermerill** [comment]
You have to create a new project: 
File -> new project
or click on the trash icon -> new project
