### ISSUE TITLE
new creality ender 3 bltouch conf will not add to printers

### ISSUE THREAD

**Issue by kaibsora** [supermerill/SuperSlicer#1330]
### Version
_Version: 2.3.56.5_

### Operating system type + version
windows 11 + 10 latest

### Behavior
When trying to add the bltouch version of ender 3, and clicking finish from both brand new unzip of super, you get the prompt that the printer model ffff doesnt have a filament type selected, would you like to select default filament for the model. it doesnt matter what you select, it doesnt get added. 
* _Steps needed to reproduce the problem_
* _Expected Results_
* _Actual Results_
  * _Screenshots if useful_

_Is this a new feature request?_
No

**Comment by supermerill** [comment]
reported here
https://github.com/supermerill/SuperSlicer/issues/896

seems the fix didn't make through

**Comment by kaibsora** [comment]
Awesome! Seems I didn't go back so far. Thanks so much!
