### ISSUE TITLE
Add "Z offset" Filament Override

### ISSUE THREAD

**Issue by martinbudden** [supermerill/SuperSlicer#1334]
Different filaments benefit from being printed at slightly different `Z offset`s, for example PETG likes the hotend slightly further from the bed than PLA and I believe ABS likes to be squished a bit more onto the bed (not sure about ABS though, I don't print it).

**Is your feature request related to a problem? Please describe.**

The `Z offset` is set in the Printer Settings profile, so to change it when changing filaments you either have to edit it manually, or set up multiple Printer Settings profiles for each printer, eg one for PLA and one for PETG.

**Describe the solution you'd like**
I'd like a `Z Offset` setting in the Filament Overrides page of Filament Settings.

**Describe alternatives you've considered**
Currently I have a Printer Settings profile for PLA and PETG for each printer. This gets tiresome.

**Comment by supermerill** [comment]
dupicate of #602
