### ISSUE TITLE
[2.3.56.5] Width / Spacing Issue

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#1341]
Not sure what is going on here, since the new width / spacing has generally been working well for me.

I have a cylindrical shell which is 1.6mm wide:

![image](https://user-images.githubusercontent.com/12439543/122685412-d01e9500-d1d0-11eb-9e07-5cf31d264118.png)

With the following settings, I expect 4 extrusion lines and no gap fill:

![image](https://user-images.githubusercontent.com/12439543/122685425-e0367480-d1d0-11eb-8ac3-7e0b2665fb76.png)

But, here is the result:

![image](https://user-images.githubusercontent.com/12439543/122685433-f0e6ea80-d1d0-11eb-9b9e-e334b21522dc.png)

[WidthIssue.3mf.txt](https://github.com/supermerill/SuperSlicer/files/6682935/WidthIssue.3mf.txt)

**Comment by CCS86** [comment]
It actually looks like this is a front-end / GUI issue. 

I had worked down to spacing values of 0.36mm and still the path hadn't changed. Then, I set the width values to 0.4mm (which bumped the calculated spacing up to 0.37xx, and suddenly I had 4 lines, plus a little gap fill. I then set the spacing values all back to 0.4mm and the path was correct.

It seems like (at least when setting spacing values) something gets "stuck" in the GUI and doesn't pass the correct values to the engine. I'm curious what my imported project looks like to someone else.

**Comment by poernahi** [comment]
Seems to work as expected on my computer (2.3.56.5 windows)

However, I notice my slicer produce different path. Do you see the same result if you restart the slicer, reload the file and re-slice?

![image](https://user-images.githubusercontent.com/10459441/122701594-9921a100-d21b-11eb-9183-ef9478ee5c8a.png)

**Comment by supermerill** [comment]
Modifying a spacing doesn't reset the slicing data like widths do. have to fix that.
