### ISSUE TITLE
frame rate in gcode viewer 

### ISSUE THREAD

**Issue by robthide37** [supermerill/SuperSlicer#1344]
May not be a bug but it seems the newer versions are much slower for the frame rate when preview gcode is on the screen. I have a 5950x with 64gb ram and a 3080 rtx so i am very sure that it is not my system. I even did a fresh windows install to make sure and i have a undervolt and overclock on both the card and the cpu plus the ram is running 3733 at cl14 so i am at a loss. My 1700x ryzen with 32gb ram runs the old ss faster than the slice and gcode preview run on any of the recent releases i am not sure if its just the newer code is heavy or if somehow i lost hardware accel support . Maybe multi monitors cause issue i am going to try that cause i just thought of it as a possible thing that changed as well

**Comment by supermerill** [comment]
I don't know but i will ussume you are on windows and using the version that comes with the extra opngl23.dll in the root directory. Delete that
or delete everything and download latest version.
