### ISSUE TITLE
Crash when slicing with Z offset

### ISSUE THREAD

**Issue by no-mana** [supermerill/SuperSlicer#1347]
**Describe the bug**
When I set Z offset at 0.01 mm, SS crashes when slicing.

**To Reproduce**
1. Go to printer setting
2. Set Z offset to 0.01
3. Slice (select the first calibration for the nozzle height)

**>> Project File <<**
[First layer calibration.zip](https://github.com/supermerill/SuperSlicer/files/6690118/First.layer.calibration.zip)

**Expected behavior**
Crash when slicing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.3.55.5

**Comment by martinbudden** [comment]
I have found the same thing - if you try to generate first layer calibration when `Z offset` is not zero, the slicer crashes.
