### ISSUE TITLE
[FR] Avoid Crossing Perimeters: Inset Distance

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#1349]
When using the "avoid crossing perimeters" function, the engine hugs whichever outer wall it would have crossed. It appears to land directly on the most outer wall's printed path:

![image](https://user-images.githubusercontent.com/12439543/123011855-d191be00-d386-11eb-92b3-b82377f424b4.png)

The problem with this, is that retracing that path at high speed creates visible artifacts in that wall surface. For a lot of the same reasons mentioned in the "poyholes" blog post, you get filament deposited outside of the outer wall.

I think this can be solved completely with an "inset distance" parameter added to the feature. This would define a minimum distance for the travel path, in relation to that outer wall. Maybe it would be even simpler to specify a wall number, and the travel move could move from the outermost wall, in some number of walls.

**Comment by qwewer0** [comment]
I like the wall number solution more, as that would adjusts to the line width.

**Comment by CCS86** [comment]
It could be like many of the settings where you can express as a number in mm, or as a percentage of extrusion width.

**Comment by supermerill** [comment]
It's a bit too complex to go deeper than the second perimeter without creating travelling problems. And nobody would want the previous version, right? So for now, no inset distance.

**Comment by CCS86** [comment]
I'll give it some testing, but I'm pretty sure this will work well.
