### ISSUE TITLE
[FR] Add Minimum Travel Resolution for Avoid Crossing Perimeters

### ISSUE THREAD

**Issue by qwewer0** [supermerill/SuperSlicer#1350]
**Is your feature request related to a problem? Please describe.**
We set up our printer profile so that the resolution/precision is fine, but the printer still could process the smaller segments while printing, but the travel moves are usually faster, so when a travel move is generated along a perimeter with Avoid Crossing Perimeters enabled, some might have problems computing the short segmented fast moves.

**Describe the solution you'd like**
An option to specify the avoid crossing perimeters minimum travel resolution, in order to increase the travel move segments.
It should have a lower boundary of the current set resolution and an upper boundary of a larger sane value.

**Describe how it would work**
When Avoid Crossing Perimeters is enabled, the travel moves along a perimeter - when avoiding - would be at least the set value. (Other travel moves would be unaffected)

**Comment by CCS86** [comment]
https://github.com/supermerill/SuperSlicer/issues/1210
