### ISSUE TITLE
Gap Fill Missing Large Gaps

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#1351]
2.3.56.5 / Win10 x64

Even with Minimum gap fill area set to 0, it is missing some relatively large gaps:

![image](https://user-images.githubusercontent.com/12439543/123035418-e8e5a100-d3b0-11eb-82ee-fc950cdc7805.png)

[gapfillmiss.3mf.txt](https://github.com/supermerill/SuperSlicer/files/6698876/gapfillmiss.3mf.txt)

**Comment by neophyl** [comment]
When I try and open your projectct with 2.3.56.5 on Win10 (same version as you) I get the following error ConfigBase::set_deserialize() failed for parameter "fill_pattern", value ""  So it looks like one of the fill settings is missing when saved.  I'm wondering if that could be contributing to the missing gapFILL.

**Comment by supermerill** [comment]
oh, that saving bug.
I finally succeed to replicate it and fix it not so long ago.
