### ISSUE TITLE
Option to lose "Sliced Preview" tab

### ISSUE THREAD

**Issue by LaserBee** [supermerill/SuperSlicer#1353]
As the title says. I don't really see much point in having a "Sliced Preview" tab AND a "Gcode Preview" tab. I don't think the Sliced Preview tab gives any information that the other one doesn't. 

Would it be possible to give the option to only have the Gcode Preview tab?

**Comment by supermerill** [comment]
select "prusaslicer layout" in preference ->gui

**Comment by LaserBee** [comment]
Sorry I never got back to you on this. Perfect, thank you so much!
