### ISSUE TITLE
Duet (RepRap) Fan speeds

### ISSUE THREAD

**Issue by aceycv8** [supermerill/SuperSlicer#1357]
I want to modify fan speeds to suit the print on the fly - i modify them on my duet and they hold for the 1 layer however once the next layer kicks in my fan speeds default back to what was in the slicer - is there away to fix this by a setting or a bug?

thank you

Version 2.3.56 - however noticed in previous versions

**Comment by supermerill** [comment]
filament settings -> cooling

**Comment by aceycv8** [comment]
Thanks Supermerill
