### ISSUE TITLE
Have you an old Version 2.2.52.1 for win64 to download ?

### ISSUE THREAD

**Issue by sholvatealc** [supermerill/SuperSlicer#1362]
Have you a Link to the Version 2.2.52.1 for win64 as an zip file for me?

Markus

**Comment by neophyl** [comment]
https://github.com/supermerill/SuperSlicer/releases/tag/2.2.52.0

**Comment by sholvatealc** [comment]
Thank you. Markus

neophyl ***@***.***> schrieb am So., 27. Juni 2021, 16:44:
