### ISSUE TITLE
Gcode bloat with circular pattern

### ISSUE THREAD

**Issue by kursatu** [supermerill/SuperSlicer#1367]
**Describe the bug**
Superslicer generates a very large number of gcode moves for circular patterns. This makes SuperSlicer unusable.
I have already a very high minimum extrusion length of 0.1mm but it does not seem to use it at all.
Eg: This is the generated gcode from the the attached project file, at line 76717
G1 X228.691 Y304.774 E0.02387
G1 X228.718 Y304.798 E0.00195
I've exported configuration to Prusa slicer just to see how it behaves.
The gcode file lines are for the exact same config
Superslicer: around 159500
Prusa slicer: around 93500
I was able to match Prusa slicers line count if I set the minimum extrusion length to a super high value of 0.4mm.
This also causes the printer board to choke. I have an SKR2, M4 at 168Mhz and no matter what I tried on the
Marlin side, it just couldn't handle them. It just can't fill the block buffers fast enough so it continuously slows 
down generating terrible vibration.
The Prusa slicer gcode is handled fine. It does not choke or simply is not very noticeable.
I have been using SuperSlicer for a long time, I don't recall this being an issue.
This is happening with the build I've made myself by synching the latest sources on GitHub.

**To Reproduce**
Slice and export the attached project file.
Or observe the gcode that in the zip file

**>> Project File <<**
[Harness loop.zip](https://github.com/supermerill/SuperSlicer/files/6730874/Harness.loop.zip)

**Desktop (please complete the following information):**
 - Windows 10
 - SKR2, M4 processor etc.

**Comment by supermerill** [comment]
that's because you decide to use superslicer features
[Harness loop_lowgcode.3mf.zip](https://github.com/supermerill/SuperSlicer/files/6732069/Harness.loop_lowgcode.3mf.zip)

for exemple, prusa has a fixed resolution of 0.0125
it uses overlapping perimeters
it doesn't have ironing as top pattern.
With these settings, (see project), i have ~90K lines.
