### ISSUE TITLE
Multiple extruder prints doesn't select the correct extruder

### ISSUE THREAD

**Issue by EgonVLC** [supermerill/SuperSlicer#1368]
**Describe the bug**
When printing with more than one extruder, I can't find any working way to especify which extruder prints what. All config options seem broken. Also, if you don't manually select the extruder to match de default extruder for each feature, some retractions are missing when going from one feature to the next, even if it doesn't honour the extruder selected.

**To Reproduce**
1. Have a printer with more than one extruder
2. Load any stl
2. Select a main extruder for the model
3. Go to config and change extruders depending on feature (perimeter, supports...) or add modifiers
4. Slice and check results

**>> Project File <<**
[bug.zip](https://github.com/supermerill/SuperSlicer/files/6731477/bug.zip)

**Expected behavior**
A clear way to print multimaterial objects. Multiextruder config needs a "default" value for each feature which should be the main extruder selected, and then you should be able to override the features' extruder you need.

**Screenshots**
Example 1:
Set extruder 2 as main extruder, then config extruder 3 for supports:
![Extruder_2+support_3_config](https://user-images.githubusercontent.com/60654101/123755670-7008ac80-d8bc-11eb-9466-bf6ade7dca64.jpg)
Result: everything is printed with extruder 2
![Extruder_2+support_3](https://user-images.githubusercontent.com/60654101/123755667-6f701600-d8bc-11eb-9f50-95a0318816ad.jpg)

Example 2:
Set extruder 2 as main extruder, then add modifiers to use extruder 1 as supports: Everything is printed with extruder 1
![Extruder_as_Modifiers](https://user-images.githubusercontent.com/60654101/123755672-70a14300-d8bc-11eb-8ae1-d9b42d547001.jpg)

Example 3:
All set to the same extruder (2)
![Only_Extruder_2_config](https://user-images.githubusercontent.com/60654101/123755676-7139d980-d8bc-11eb-8d04-486729083a7e.jpg)
It prints everything with extruder 2 (the only config that is usable)
![Only_Extruder_2](https://user-images.githubusercontent.com/60654101/123755673-70a14300-d8bc-11eb-9683-63d3fd03bc58.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10, last version
 - Version 2.3.56.6 (Nightly from actions)

**Additional context**
Printer is a custom toolchanger with 4 extruders

**Comment by supermerill** [comment]
remove the character still present in custom "tool change gcode"
will add something to remove these invisible characters from the detection.
