### ISSUE TITLE
[Feature Request] change retraction at different heights

### ISSUE THREAD

**Issue by ProfEngr** [supermerill/SuperSlicer#137]
I've heard a rumor that retraction will be added to the list of settings that can be changed using modifiers. Does (or will) this fork have that option available?

**Comment by supermerill** [comment]
I merge with prusaslicer, so if it's inside prusaslicer, there's a good chance that it's inside this fork as well.
Sometimes i'm a bit behind their latest release and sometimes a bit above, so it's something to check.

**Comment by JS3910** [comment]
The lack of this always annoyed me with PS, makes it hard to do calibration. If it's not coming from upstream I'd request it for S++!

**Comment by supermerill** [comment]
have to work on it for the retraction calibration
