### ISSUE TITLE
Print host Repetier Server not working when the host is not called Repetier-Server

### ISSUE THREAD

**Issue by Prutsium** [supermerill/SuperSlicer#1376]
Version 2.3.56.6
When selecting Repetier as Print Host Upload it wants to see the Repetier to be called Repetier-Server.
This works for standard installs but often Repetier is Branded and have their own name like CR3D-Server due that the Repetier connection wont work as it doesnt pass the version check.

Suggested to have or a naming box or a checkbox to skip the check.

**Comment by supermerill** [comment]
Can you put here the error messages? I can't spot anywhere a 'Repetier-Server' check.

**Comment by CageFox** [comment]
I always using repetier server as host and my host name not even close to "Repetier-Server" and all works well. My host have name "P" and printers named like "P" and "SP" ;)

**Comment by Prutsium** [comment]
It's not related to the host name ....
It's the branding name that can be changed for by resellers.
![image](https://user-images.githubusercontent.com/42968695/124322771-57c8b400-db80-11eb-8088-d39b24eb3c64.png)

**Comment by CageFox** [comment]
Is there a way to check this name in existing installation?

**Comment by supermerill** [comment]
@Prutsium 
Can you put here the error messages? I can't spot anywhere a 'Repetier-Server' check.

**Comment by Prutsium** [comment]
See added screenshots hope they would help
![image](https://user-images.githubusercontent.com/42968695/124952476-91803b80-e014-11eb-8190-7bcdd0f956d7.png)
![image](https://user-images.githubusercontent.com/42968695/124952505-96dd8600-e014-11eb-8cc9-f67310f5b430.png)
![image](https://user-images.githubusercontent.com/42968695/124952528-9e049400-e014-11eb-865d-f40d2489c454.png)

The printers are detected but not possible to add
