### ISSUE TITLE
toolchange_gcode at the beginning of print

### ISSUE THREAD

**Issue by Pavulon87** [supermerill/SuperSlicer#1377]
**Describe the bug**
An unnecessary M600 gcode is added at the start of printing.

**To Reproduce**
![Clipboard01](https://user-images.githubusercontent.com/23641103/124152346-b95f2480-da93-11eb-821e-e8829e4559e5.jpg)
Default setting - single extruder, no filament change
> G1 X150.0 E20  F1000.0 ; intro line
G92 E0.0
M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
M900 K30; Filament gcode
**M600**
M107
;LAYER_CHANGE

or with comments:
> ; custom gcode end: start_filament_gcode
; custom gcode: toolchange_gcode
**M600**
; custom gcode end: toolchange_gcode
;LAYER_CHANGE

**>> Project File <<**
[Shape-Box.3mf.zip](https://github.com/supermerill/SuperSlicer/files/6749354/Shape-Box.3mf.zip)

**Expected behavior**
No toolchange_gcode should be added.

**Desktop (please complete the following information):**
 - OS: Window
 - Version 2.3.56.6

**Comment by supermerill** [comment]
I'll add a switch to not use the custom toolchange gcode  if only one tool.

to fix: 
* add an extruder
* remove everything inside custom toolchange gcode
* remove the second extruder
