### ISSUE TITLE
Confirmation dialogue for deleing print profiles

### ISSUE THREAD

**Issue by Niper8** [supermerill/SuperSlicer#1382]
**Is your feature request related to a problem? Please describe.**
Just clicked the delete profile button thinking it was the discard changes button (good thing I make backups :) )

It would be nice if it confirms that you want to delete a profile.

**Describe the solution you'd like**
Ask the user if they are sure they want to delete.

**Describe how it would work**
Are you sure you want to delete it? yes/no

**Comment by supermerill** [comment]
Can't reproduce, I have a confirm dialog.

![image](https://user-images.githubusercontent.com/6536403/124305889-fa276e00-db65-11eb-9848-bc88106c3b75.png)

Can you explain in detail how you manage to avoid it?

**Comment by Niper8** [comment]
Well, nor can I ,😂. I think I must have been on autopilot
