### ISSUE TITLE
Character display error

### ISSUE THREAD

**Issue by sziga** [supermerill/SuperSlicer#1386]
I started translating SuperSlicer into Hungarian.
Some long accented characters like "ő" and "ű" appear incorrectly in the small windows.
In the main window, in settings they appear fine, in search, Variable layer hight,cut, Gcode preview top left information area window etc the "ő" "ű" characters are replaced by "?".
Version: SuperSlicer_2.3.56.6_win64_210626
Displayed in the settings: 
![error1](https://user-images.githubusercontent.com/49403033/124355005-51354d80-dc0f-11eb-976f-625dc283153d.jpg)
Search windows:
![error2](https://user-images.githubusercontent.com/49403033/124355032-732ed000-dc0f-11eb-81ee-4f64000cca3d.jpg)
Variable layer hight windows:
![error3](https://user-images.githubusercontent.com/49403033/124355056-8fcb0800-dc0f-11eb-94c8-a8ba84259de6.jpg)
Cut windows:
![error4](https://user-images.githubusercontent.com/49403033/124355080-aec99a00-dc0f-11eb-831b-f7b620e3dc68.jpg)
Gcode preview top left information area window:
![error5](https://user-images.githubusercontent.com/49403033/124355196-3fa07580-dc10-11eb-8eb9-26797d2ca356.jpg)
The .po file includes the line "Content-Type: text/plain; charset=UTF-8\n":
![error6](https://user-images.githubusercontent.com/49403033/124355216-534bdc00-dc10-11eb-94a5-2be4893e5c65.jpg)

**Comment by supermerill** [comment]
give me your po, so i can test it.

**Comment by sziga** [comment]
The translation is not yet complete and there are still a lot of mistranslations, but I'll send you the po file.
[hu.zip](https://github.com/supermerill/SuperSlicer/files/6758949/hu.zip)

**Comment by supermerill** [comment]
Found it:
That's because I have to add the hungarian ranges for glyphs creation.
![image](https://user-images.githubusercontent.com/6536403/124369750-9d17df00-dc6f-11eb-9e51-2200bfc4554a.png)
Will be fixed in next version
I'll add a post here when a nigthly will be built with it

**Comment by sziga** [comment]
Okay. Thank you!

**Comment by AntoszHUN** [comment]
It's funny because there is no Hungarian language in it.

**Comment by supermerill** [comment]
there is in the 2.4

**Comment by AntoszHUN** [comment]
> 



> there is in the 2.4

However, it is not included in the new version.
