### ISSUE TITLE
Underextrusion on long distances?

### ISSUE THREAD

**Issue by nicedevil007** [supermerill/SuperSlicer#1400]
**Describe the bug**
![image](https://user-images.githubusercontent.com/17103076/125026993-d42e2c00-e085-11eb-94a1-902ddb65a068.png)

The picture says everything, the left object is printed with SuperSlicer and the right one with IdeaMaker.
I get those underextrusions on every print that has such long lines to print in front of a corner section.

**To Reproduce**
These are my settings in SuperSlicer for the extruder and I use relative Extrusion:
![image](https://user-images.githubusercontent.com/17103076/125026960-ca0c2d80-e085-11eb-982b-953dee192143.png)

[config.zip](https://github.com/supermerill/SuperSlicer/files/6788906/config.zip)
**>> Project File <<**
*Please* upload a ZIP archive containing the project file used when the problem arise. Please export it just before the problem occur. Even if did nothing and there is no object, export it as it contains your current configuration.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.56.6

**Comment by JohanAR** [comment]
I think it will be easier to debug if you save and attach the whole project (a .3mf file) which includes both the model you're slicing and settings

I saw that your config.ini that you have "post_process = ArcWelder.exe".. Did you try printing it without ArcWelder?

**Comment by nicedevil007** [comment]
Ah that is a good point, can try again without! I will report back what the results are! If they are bad I can send the 3mf file :)

**Comment by nicedevil007** [comment]
seems to fixed without acrwelder :) ty
