### ISSUE TITLE
Specific STL crashes on slicing

### ISSUE THREAD

**Issue by RURon** [supermerill/SuperSlicer#1406]
### Version
2.3.56

### Operating system type + version
Win10 x64 20H2

### Behavior
After loading a specific stl and running the slice command, Superslicer crashes to desktop without an error report
[ratrig_cable_tie_tube_remix.zip](https://github.com/supermerill/SuperSlicer/files/6796964/ratrig_cable_tie_tube_remix.zip)

**Comment by supermerill** [comment]
Thanks for the report.
That was an old coding mistake causing this crash.
Fixed in the coming nightly.
