### ISSUE TITLE
Where is elephant foot compensation in SuperSlicer 2.2.53?

### ISSUE THREAD

**Issue by laptop-laptop** [supermerill/SuperSlicer#1424]
**Is your feature request related to a problem? Please describe.**

Hi, there is such feature in PrusaSlicer but I cannot find it in SuperSlicer 2.2.53. Could you please tell  me where it is? Perhaps under different name?

**Comment by neophyl** [comment]
Print Settings>Slicing.  Modifying Slices.  Of course you need to be in advanced or expert mode for that section to appear.
Its called x/y compensation:first layer

**Comment by supermerill** [comment]
You have to insert a negative value to have the same behavior than a positive one from prusaslicer.

**Comment by laptop-laptop** [comment]
Thank you. Besides the sign, is elephant foot compensation in prusaslicer exactly the same as XY compensation-First layer in SuperSlicer?

**Comment by supermerill** [comment]
yes

**Comment by laptop-laptop** [comment]
Thank you
