### ISSUE TITLE
Milling post processing disables raft function

### ISSUE THREAD

**Issue by ReneJurack** [supermerill/SuperSlicer#1426]
**Describe the bug**
On the E3D ToolChanger, I did set up an ASMBL-tool as Tool3, configured as a milling tool.
Now I can't turn on the raft at all. As soon as I change the raftlayers from 0 to 1 or more, the slicing fails.

<img width="1586" alt="Bildschirmfoto 2021-07-18 um 16 48 56" src="https://user-images.githubusercontent.com/24276215/126074519-f374e23c-7200-496a-9abf-4c396ed0717a.png">

**To Reproduce**
1. Set up a milling tool
2. try to enable raft

**>> Project File <<**
I can not export the project file, because of error shown in screenshot. As soon as there is no milling tool configured, export does work.

<img width="1586" alt="Bildschirmfoto 2021-07-18 um 18 12 51" src="https://user-images.githubusercontent.com/24276215/126074533-0b86e84e-d486-4680-a955-8979032f3161.png">

**Expected behavior**
"Enable raft" enables raft

**Desktop (please complete the following information):**

<img width="632" alt="Bildschirmfoto 2021-07-18 um 18 14 06" src="https://user-images.githubusercontent.com/24276215/126074540-4182cf11-8298-47df-89b1-7c46bd938ad7.png">

SuperSlicer
Version:   2.3.55
Build:     SuperSlicer_

Operating System:    Macintosh
System Architecture: 64 bit
System Version:      macOS Version 10.16 (Build 20F71)
Total RAM size [MB]: 34,360MB
OpenGL installation
GL version:   2.1 ATI-4.5.14
Vendor:       ATI Technologies Inc.
Renderer:     AMD Radeon Pro 560X OpenGL Engine
GLSL version: 1.20

**Comment by neophyl** [comment]
Can you at least save the project without the raft enabled so that at least your machine and other profile settings are known.

**Comment by supermerill** [comment]
can't reproduce, can you zip & post your projext here?
