### ISSUE TITLE
Strange stuttering sound on inner brim perimeter

### ISSUE THREAD

**Issue by mrvanes** [supermerill/SuperSlicer#1434]
**Describe the bug**
I have most of the Slicer parameters dialed in, but one weird effect remains: the last (inner) brim perimeter causes a fast stuttering, humming vibration while printing. None of the other layers or features suffer this effect. I've reduced the max_accel and square_corner_velocity in Klipper, no relief.

**To Reproduce**
1. Have my printer (or not?)
2. Load my project
3. Print
4. Listen to the printer while printing the inner brim perimeter

**Project File**
Hope this contains everything needed?
This file is not zipped, only renamed since Linux refuses to zip a zipfile.
[20140205_Marvin_KeyChain.3mf.zip](https://github.com/supermerill/SuperSlicer/files/6855833/20140205_Marvin_KeyChain.3mf.zip)

**Expected behavior**
No vibration/stuttering while printing

**Screenshot**
![image](https://user-images.githubusercontent.com/1901782/126492487-aa7488c3-f8bd-4e31-b6e8-f388867f4901.png)

**Desktop**
 - OS: Linux
 - Version 2.3.56.7

**Comment by supermerill** [comment]
can you try with:
* latest nightly https://github.com/supermerill/SuperSlicer/suites/3291315685/artifacts/76849456
* 0.35 as "min length" (in the printer general setting)
?

**Comment by mrvanes** [comment]
Thx. It seems the 0.35 min length solved most, if not all, of the problem.

**Comment by mrvanes** [comment]
It turns out there is also strange interaction between Klipper's acceleration limiting. I let Klipper do all the limiting (disabled SuperSlicer limits) but this seems to cause the erratic behaviour. I now set SuperSlicer to safeguard and configured all Klipper's limits higher so that they effectively don't interfere with SuperSlicer's limit. This seems to work the best for my printer?

**Comment by supermerill** [comment]
> and configured all Klipper's limits higher so that they effectively don't interfere with SuperSlicer's limit

This shouldn't be necessary. If you are using the limits as safeguards, they should be the same as what you entered in your firmware. If the gcode output something bigger than you have set, then there is a bug.
