### ISSUE TITLE
web access slicer

### ISSUE THREAD

**Issue by tjengbudi** [supermerill/SuperSlicer#1435]
is there any chance to make this slicer can access by web? it is very convenient to access this profile event only local network. it would really nice feature

**Comment by supermerill** [comment]
Do you means cloud-based profiles?
Or webapp that run into a browser?

**Comment by tjengbudi** [comment]
not the 2 of them
it will really nice to have some feature like utorrent. if the web management is activated. i can access them by web with local network setting. it means i just open with ip address that program running and the port.

i believe delphi have component to do that. but i do not know how it works. cause if i remember it is paid component. i do not know either how to implement in c

now i just used remote desktop to do that. but i hope it will have some feature like this. it will really nice

**Comment by supermerill** [comment]
I don't understand

**Comment by tjengbudi** [comment]
sorry for my bad explanation

here is screen capture where utorrent have this feature
![utorrent](https://user-images.githubusercontent.com/3039807/126621002-23fca9a7-ab73-4dba-9e53-9f3a86e948d1.PNG)

**Comment by supermerill** [comment]
what feature? i don't understand a word. Please explain to me like if i was a 5 year old.

**Comment by tjengbudi** [comment]
the web ui is the way to control interface from web browser. it is replicate the main control just like it is control the main apps. the behaviour is the same. just activate the web ui setting. access by web browser ( for example if the port is 8080) url 127.0.0.1:8080 and you can access it. it is the best way to have 1 maintain profile and share connectivity in local network. 

sorry my english might not good to explain. i try my best. thx u

**Comment by supermerill** [comment]
Ok
I won't do that, it's years of man-hour of dev.

**Comment by tjengbudi** [comment]
noted
