### ISSUE TITLE
Strange bug with brim cause enabling "External perimeter first"

### ISSUE THREAD

**Issue by Pavulon87** [supermerill/SuperSlicer#1439]
**Describe the bug**
Same project is creating different gcode after turning brim on/off and reloading

**To Reproduce**
1. Open attached project
2. Enable/disable brim
3. Slice
4. Save project
5. Reopen project
6. Slice again

**>> Project File <<**
[outer_first.3mf.zip](https://github.com/supermerill/SuperSlicer/files/6883745/outer_first.3mf.zip)

[inner_first.gcode.txt](https://github.com/supermerill/SuperSlicer/files/6883785/inner_first.gcode.txt)
[outer_first.gcode.txt](https://github.com/supermerill/SuperSlicer/files/6883786/outer_first.gcode.txt)

**Expected behavior**
 "External perimeter first" should not be affected by brim or other options

**Screenshots**
![inner](https://user-images.githubusercontent.com/23641103/127118172-704f47d1-ed80-4631-84b5-65037cd79b4e.png)
![outer](https://user-images.githubusercontent.com/23641103/127118178-83428118-3060-4d32-a394-258aa2b60ad9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.3.56.7

**Comment by supermerill** [comment]
If you have a brim, the first layer should be with an External perimeter first

**Comment by supermerill** [comment]
can't reproduce with your procedure.
