### ISSUE TITLE
Small movements on external perimeters

### ISSUE THREAD

**Issue by randellhodges** [supermerill/SuperSlicer#1440]
**Describe the bug**
External perimeters movements broken up into multiple 0.10mm moves around 90 degree corners. Doesn't happen with internal perimeters. I'm not sure if this is by design, a configuration option, or a bug.

**To Reproduce**
1. Slice
2. View G-Code
3. Layer: 143

**>> Project File <<**
[Body10.zip](https://github.com/supermerill/SuperSlicer/files/6889959/Body10.zip)

**Expected behavior**
The outer movements shouldn't be broken up and should move like the internal perimeters.

**Screenshots**
Internal Perimeters (working like I expect)
![SuperSlicer-Internal Perimeters](https://user-images.githubusercontent.com/7727467/127255574-dbed3c46-2497-4927-8b0f-f85631a31a53.gif)

External Perimeters (note the 2 small movements of 0.10mm before it finishes out the move)
![SuperSlicer-External Perimeters](https://user-images.githubusercontent.com/7727467/127255620-a1eebfcf-9dc4-4de5-b6be-47edf787b879.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.3.56.7

**Comment by supermerill** [comment]
If you don't want the `cutting corners` feature, deactivate it

**Comment by randellhodges** [comment]
> If you don't want the `cutting corners` feature, deactivate it

Thank you. I can confirm changing this makes it work as I was expecting. Not sure when I cranked that to 100%.
