### ISSUE TITLE
Over-extrusion

### ISSUE THREAD

**Issue by mafotaso** [supermerill/SuperSlicer#1444]
**Describe the bug**
When you laminate, show perimeter around 0.95mm width and I have selected 0.4nozzle and 0.44mm width max. That cause me a lot  of printing obstruction and fail. 

The problem  is the space, slicer doesn't understand that it can print 2 lines and not only 1 with a big width. I have tested it in differents versions, differents size of the piece and nothing work. The onyl thing that you can to do is decrease perimetral width and increase external perimetal and you can improve it a little. 

**To Reproduce**
1. Go to laminate
2. Click on 
3. Scroll down to width view
4. See error around last layers near of the ears.

**>> Project File <<**
[catplanter.zip](https://github.com/supermerill/SuperSlicer/files/6909300/catplanter.zip)

**Expected behavior**
just lamine

**Screenshots**
![2021-07-30 (1)](https://user-images.githubusercontent.com/73241782/127693165-a67f38ec-fa1c-41c0-9a90-c2365061068d.png)
![2021-07-30 (2)](https://user-images.githubusercontent.com/73241782/127693175-b7163d2d-309f-4211-8cfb-82f8b9215138.png)

**Desktop (please complete the following information):**
 - OS: Windows 20H2 19042.1110
 - Version 2.3.56.7

**Comment by graflash** [comment]
Enable "Also for all perimeters"
![image](https://user-images.githubusercontent.com/71028326/127717240-738378b5-6dd0-4a5b-8d51-2b2ce3813c69.png)
![image](https://user-images.githubusercontent.com/71028326/127717304-ab23aa1a-6682-4e72-a713-1b6a4977945f.png)

**Comment by mafotaso** [comment]
you are a genius!!! 

solved! 
![2021-07-31](https://user-images.githubusercontent.com/73241782/127736199-2b987d76-9f7a-47e7-9394-4a44af468c41.png)
