### ISSUE TITLE
The wall in the space for the cage nut is smaller than the outer perimeter

### ISSUE THREAD

**Issue by slimfy1** [supermerill/SuperSlicer#1452]
**Describe the bug**
When the model is printed, the outlines of the place in the wall for the cage nut are visible. In Cura 4.10 i don't see that problem. 
I attach the config file at the end.

**To Reproduce**
1.Thin Wall -> Enabled
2. Gaps -> Enabled 

**Expected behavior**

**Screenshots**

![photo_2021-08-04_00-18-21](https://user-images.githubusercontent.com/39963810/128088551-e706b1c9-103d-4701-83f9-a61f99718f9f.jpg)
![photo_2021-08-04_00-18-32](https://user-images.githubusercontent.com/39963810/128088564-485ef66e-ec3b-4ea1-a1b5-aadb347a0613.jpg)
![photo_2021-08-04_00-18-19](https://user-images.githubusercontent.com/39963810/128088574-8c3d6e14-511f-42a2-8fe0-5698d71844d1.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 2.3.55.7

[config.zip](https://github.com/supermerill/SuperSlicer/files/6927150/config.zip)

**Comment by supermerill** [comment]
You can try with 'overlapping extruder' -> 'all'
You can also reduce the gap fill overlap to 0 (it's in tab `print` -> `flow` )
Please report your results.

**Comment by slimfy1** [comment]
@supermerill Hello!

Yes, that help me, thank you!
![photo_2021-08-05_22-32-42](https://user-images.githubusercontent.com/39963810/128410243-991f3d86-30d0-4857-9748-eefef78496f8.jpg)
