### ISSUE TITLE
Filament Flow Calibration - generated print does not fit inside Prusa Mini build volume

### ISSUE THREAD

**Issue by Sp4rkR4t** [supermerill/SuperSlicer#1457]
**Describe the bug**
When attempting the Filament Flow calibration for the first time I clicked generate the 10% print and it is nowhere near being on the build plate and the layout looks quite different to the tutorial.

**To Reproduce**
1. While you have Superslicer set up for a prusa mini print volume (180x180x180mm) go to Calibration menu > Filament Flow Calibration
2. Click on Generate 10% intervals around current value
3. See that the generated print does not fir in print volume

**>> Project File <<**
[FilamentFlowCalibration.zip](https://github.com/supermerill/SuperSlicer/files/6945354/FilamentFlowCalibration.zip)

**Expected behavior**
For the filament flow calibration model to be generated so that it fits in the print volume

**Screenshots**
![image](https://user-images.githubusercontent.com/3926906/128506779-756e01f4-ba71-4cc0-8fb5-0c0fda6cd9e7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.56.7

**Comment by supermerill** [comment]
You can't print 5 of those in a such small plater.
Delete one, or manually reduce their size.
