### ISSUE TITLE
[BUG] Gap Fill width bigger than perimeter Width 

### ISSUE THREAD

**Issue by DontTakeItForGranted** [supermerill/SuperSlicer#1460]
**Describe the bug**
The Gap fill that is produced has a way higher width than the perimeter width

**To Reproduce**
use a relatively thick extrusion width. (i used 1mm for external perimeters and 1.1 mm for perimeters)
a 3d benchy at original scale is used in the first and second picture.

**Expected behavior**
the Gap fill Width should be in any case smaller than the perimeter width.

**Screenshots**
the perimeter width is 1.1mm but the gap fill width in this picture is more like 2.1mm :
![Bildschirmfoto 2021-08-06 um 23 58 04](https://user-images.githubusercontent.com/87256384/128575550-a6b4c82d-0916-4b8c-b68b-a32b66f35af6.png)
![Bildschirmfoto 2021-08-06 um 23 58 27](https://user-images.githubusercontent.com/87256384/128575559-5201abe4-03a1-4403-a676-952c9e990396.png)

the to thick extrusion of gap fill also leads to a extrusion of gap fill in mid air where a bridge should be that supports a perimeter.  
(not an extra bug, because gap fill, when everything is how it should be, dont needs bridge support because it is hold by the perimeters around it. but because there is gap fill instead of  perimeters the gap fill is hanging in mid air)
![Bildschirmfoto 2021-08-06 um 23 56 07](https://user-images.githubusercontent.com/87256384/128575534-a781b744-e074-4f46-8e25-501b5998525f.png)
![Bildschirmfoto 2021-08-06 um 23 56 34](https://user-images.githubusercontent.com/87256384/128575545-a05aa7f4-d1d8-4a5a-8286-1cceaa50134c.png)

**Desktop (please complete the following information):**
 - OS: Mac os 10.15.7 catalina
 - also tested on Mac os 10.13.6 high sierra

**Comment by neophyl** [comment]
https://github.com/supermerill/SuperSlicer/discussions/1095

**Comment by DontTakeItForGranted** [comment]
yeah that fixed it, 


The overlapping perimeter setting works but will lead to over extrusion 
so i dont understand why a perimeter and a gap fill shouldnt work where there is enough space for it.
I also tested it in  Prusa Slicer, PS seems to have the overlapping for all perimeters enabled, so i guess its fine

**Comment by supermerill** [comment]
> i dont understand why a perimeter and a gap fill shouldnt work where there is enough space for it
> (maybe it would need a to big change in the slicing algorithm).

It's more difficult, as you can't do a loop. So you have to create a fake 'gap-fill-perimeter' a bit on the side, and then fill the rest with the normal gapfill.
Not easy to code.

**Comment by DontTakeItForGranted** [comment]
thanks for the explanation.
i guess it would increase the overhang performance if the gap fill would be disabled if there are only overhanging perimeters around it  , but this could be to complicated to implement it(i dont know how slic3r/PS/SS is working internally)

![Bildschirmfoto 2021-08-07 um 13 20 17](https://user-images.githubusercontent.com/87256384/128599059-6c6e2717-eeee-4726-bf01-81529c79335d.png)
![Bildschirmfoto 2021-08-07 um 13 47 13](https://user-images.githubusercontent.com/87256384/128599083-452fbbc1-3fc0-420f-90f6-5b099cfe4995.png)
gap fill is printed before overhanging perimeter:
![Bildschirmfoto 2021-08-07 um 13 19 47](https://user-images.githubusercontent.com/87256384/128599056-e4066924-82aa-422f-8de4-eb5d53fb4bde.png)
