### ISSUE TITLE
Overhang overlaps External Perimeter

### ISSUE THREAD

**Issue by tome9111991** [supermerill/SuperSlicer#1464]
Hello
don't know how to describe it.
I have the problem that the overhang overlaps the external perimeter.

![Screenshot 2021-08-08 175713](https://user-images.githubusercontent.com/57866234/128638166-a06761e4-a21c-4f09-8ef3-c3660de10781.png)

At first I thought it was a bug in the GUI, but when I printed it it looked very ugly in these places.
with cura the surface looked a lot better.

.3mf
[Giroid_vase.zip](https://github.com/supermerill/SuperSlicer/files/6951082/Giroid_vase.zip)

**Comment by supermerill** [comment]
That's only changing the speed&fan. you can remove it by setting a higher number in perimeter->overhangs->bridgefan & speed, or by deactivating overhang detection with a "0".

**Comment by tome9111991** [comment]
Thats true i can  overhang detection with a "0".

But i like the setting for speed & fan.
 Maybe is possible to get a "clen" overhang layer?

**Comment by supermerill** [comment]
something like that?
![image](https://user-images.githubusercontent.com/6536403/128642998-cf2bb96e-b7ee-4b18-b6fc-f891a0052cec.png)

**Comment by tome9111991** [comment]
Yes thats looks great

**Comment by qwewer0** [comment]
This is how the shared 3mf file looks for me on 2.3.57.0
![Screenshot 2021-09-08 175438](https://user-images.githubusercontent.com/57561110/132543258-0319d276-c457-42c6-8c14-7fdebcbac660.png)
