### ISSUE TITLE
Heavy stringing between print and wipe tower when ”no sparse layers” on

### ISSUE THREAD

**Issue by hagan66** [supermerill/SuperSlicer#1467]
When printing mmu prints with ”no sparse layers” i get heavy stringing to and from the wipe tower. See pics.

Version 2.3.56.7.

In preview mode without ”no sparse layers” retractions looks right, but with ”no sparse” on the hang in mid air. I dont know if that is a clue or not. 

Edit: Prj file now included

![ECD475ED-7C24-44FF-A6AE-2357CE7E065C](https://user-images.githubusercontent.com/9168083/128752117-73ae3977-1ee9-40d4-9e4e-d0f5fa262e49.jpeg)
![Skärmavbild 2021-08-09 kl  19 45 40](https://user-images.githubusercontent.com/9168083/128752167-201d6e90-64a5-4f3c-b76b-d10fcceed148.png)
![Skärmavbild 2021-08-09 kl  19 46 02](https://user-images.githubusercontent.com/9168083/128752196-b9d7d881-b5a8-4b8f-b6f4-97d28763e5a2.png)

[Hulknosparse.3mf.zip](https://github.com/supermerill/SuperSlicer/files/6956466/Hulknosparse.3mf.zip)

**Comment by supermerill** [comment]
should be fixed in the last nightly, can you test?

**Comment by hagan66** [comment]
Hi!

I loaded my project file and now the wipe tower looks right but there are now these gaps in the print. See attached screenshot. I didn't start a print.

/Robert

**Comment by hagan66** [comment]
![Skärmavbild 2021-12-07 kl  11 34 09](https://user-images.githubusercontent.com/9168083/145018233-534a1daa-36aa-4846-9fd3-7c575f0af88e.png)

**Comment by supermerill** [comment]
will be fixed in this next nightly.

**Comment by hagan66** [comment]
Cool, I will test it again then :-)

R

**Comment by hagan66** [comment]
No gaps in the latest nightly build. 

However I get pretty sloppy supports since they vary from 0.1 (print layer height) up to 0.4 layer height. Is there a setting for this? I have looked/searched. I would like to limit support layer height to say, 0.2 mm for example. 

:-)

/Robert

**Comment by supermerill** [comment]
you can reduce max layer height for the printer.
