### ISSUE TITLE
"Thin Walls" Setting Not Working

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#1468]
2.3.56.8 / Win10 x64

With "thin walls" checked, I am still getting two walls printed on top of each other on a thin wall.

[Darkfield 13.3mf.txt](https://github.com/supermerill/SuperSlicer/files/6958365/Darkfield.13.3mf.txt)

**Comment by supermerill** [comment]
uncheck "overllaping perimeters" (thin_perimeters setting)
