### ISSUE TITLE
Is it possible to setup Wipe speed ?

### ISSUE THREAD

**Issue by tirasec** [supermerill/SuperSlicer#1471]
**Describe the bug**
Is there a way to setup the Wipe Speed ? Which value is used for the wipe speed ?
With some strong materials we would like to reduce the wipe speed to a value close to the print speed.

**To Reproduce**
NA

**>> Project File <<**
NA

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Windows 10
2.3.57.0

**Additional context**

**Comment by supermerill** [comment]
> Which value is used for the wipe speed ?

travel speed

> Is there a way to setup the Wipe Speed ?

no yet.

**Comment by tirasec** [comment]
It is a bit strange, the travel speed influence the lenght of wipe and looks to be 80% of Travel Speed... 

With a travel speed of 200 mm/sec
The Wipe Speed is 9600 (160mm/sec)
The wipe length is like that
![image](https://user-images.githubusercontent.com/1278002/129158679-dba44e54-23a2-45aa-b8f4-914bc4f2a28f.png)

With a travel speed of 100 mm/sec
The Wipe Speed is 4800 (80mm/sec)
The wipe length is like that
![image](https://user-images.githubusercontent.com/1278002/129158884-9a43e4c8-ee94-41f2-96c3-85f8483f533a.png)


With a travel speed of 50 mm/sec
The Wipe Speed is 2400 (40mm/sec)
The wipe length is like that
![image](https://user-images.githubusercontent.com/1278002/129159194-477384bb-b425-42e9-8b01-e43970ed288f.png)

It would be good to have the possibility to setup the wipe length and wipe speed...

[WipeLength.ZIP](https://github.com/supermerill/SuperSlicer/files/6973748/WipeLength.ZIP)

**Comment by supermerill** [comment]
Wipe move when you retract. So the time depends of the retraction length and the retraction speed.
So the distance moved depends of the travel speed.
