### ISSUE TITLE
Default value for Max layer height prevents the slicing.

### ISSUE THREAD

**Issue by liftbag** [supermerill/SuperSlicer#1474]
**Describe the bug**
If max layer height limit is set to 0 slicing is not enabled.

**To Reproduce**
1. Set Max layer limit to default value (0)
2. Import any stl file
3. The following error message is shown: First layer height can't be greater than max layer height.

**>> Project File <<**
[45_degree_modifier2.3mf.zip](https://github.com/supermerill/SuperSlicer/files/6968512/45_degree_modifier2.3mf.zip)

**Expected behavior**
The default value 0 should be tolerated and used as described in the tooltip

**Screenshots**
<img width="1388" alt="Schermata 2021-08-11 alle 15 01 51" src="https://user-images.githubusercontent.com/14921654/129033398-0d07fc63-5d05-4fe6-8c60-bfd45a00bc93.png">

<img width="1374" alt="Schermata 2021-08-10 alle 19 40 24" src="https://user-images.githubusercontent.com/14921654/128908383-527ab398-8d21-40a1-b42b-33d4b18cdac7.png">

**SuperSlicer nightly macos 394**
**MacOS 11.2.2**

**Comment by supermerill** [comment]
Oh right.

**Comment by liftbag** [comment]
Solved with the 396 nightly build.
