### ISSUE TITLE
[Fr] skirt and brim translation are inverted in the configuration 

### ISSUE THREAD

**Issue by bax137** [supermerill/SuperSlicer#1479]
skirt and brim translation are inverted in the configuration

Go to « périmètre et enveloppe », « bordure et jupe »

Expected behavior :
« Bordure » should be « jupe » and « jupe »  should be « bordure »

**Screenshots**
Old version and new version.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 2.3.56.8
 
 old version (ok):
![CF9C7895-533F-4315-B8DE-AF9B0636409F](https://user-images.githubusercontent.com/56500375/129171190-211493ae-85d6-4e6b-a3d5-9ffd74095ba6.png)

new version (ko):
![FFEDA335-5236-462F-8B93-3AF5E30425AF](https://user-images.githubusercontent.com/56500375/129171192-520199e8-7021-4634-bcbe-ac651cb399a0.png)

**Comment by supermerill** [comment]
I asked my uncle and dad, (they don't speak english) and that's what they expect (mee too).
Maybe i can change the words. see https://github.com/supermerill/SuperSlicer/discussions/1319#discussioncomment-1125332
