### ISSUE TITLE
Perimeters Printed in Open Space for Overlapping Bridged Areas

### ISSUE THREAD

**Issue by BlueDragonX** [supermerill/SuperSlicer#1484]
**Describe the bug**
Bridging does not behave as expected when slicing a model with bridged areas above overlapping shapes of different heights. Perimeters are printed around the smaller shape instead of bridging. This happens even when the smaller shape starts one layer above the larger.

**To Reproduce**
1. Overlap some shapes in negative space.
3. Slice it.
4. Evaluate the bridging.
5. Wonder how that'll print and yolo it.

**>> Project File <<**
[klicky_superslicer.zip](https://github.com/supermerill/SuperSlicer/files/6979821/klicky_superslicer.zip)

There are two files in this project. The first has a through hole from top to bottom. You can see it print the perimeters. The second has 0.2mm of material at the bottom of the smaller hole at the same height as the bridge. The perimeter is still printed.

**Expected behavior**
It does not print perimeters within a bridged area.

**Screenshots**
The bottom of the two objects. You can see the perimeters printed within the circular areas.
![klicky-bottom](https://user-images.githubusercontent.com/465340/129304028-19119c0e-f3f8-4a03-b3be-976758036a31.png)

This is the problem layer from the top. You can see on the top that these are perimeters.
![klicky-top](https://user-images.githubusercontent.com/465340/129304202-2e3342f0-ad3b-447e-a4ba-b2aa874b4335.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.3.56.8

**Comment by BlueDragonX** [comment]
With a bit of fiddling I was able to improve this by setting "No perimeters on bridge area: Keep only bridges". No other value of this setting had any effect.
![keep-only-bridges](https://user-images.githubusercontent.com/465340/129308288-a61de898-85e0-4d65-b8b7-8e50cc97b0c2.png)

This resulted in a significant improvement with solid bridge across the entire area. However, the overlapping area has some sharp corners and overlapping lines.
![klicky-keep-only-bridges](https://user-images.githubusercontent.com/465340/129308374-e9155766-50dd-4c66-83ef-192bb641f1d7.png)

Setting bridge angle improves it even further:
![klicky-keep-only-bridges](https://user-images.githubusercontent.com/465340/129308589-b4b20f1f-46f5-42a7-876c-4f6298d52bae.png)

I suspect any further improvements will need to be made in the model.

I do have one remaining question: What effect should the other values of "No perimeters on bridge area" have?

**Comment by neophyl** [comment]
I'll just leave you this link to the wiki page https://github.com/supermerill/SuperSlicer/wiki/No-perimeters-on-bridge-area

**Comment by BlueDragonX** [comment]
Thanks. That's enlightening - or it would be if the docs matched the behavior I'm experiencing. It explicitly says not to use the option I've enabled: "Too experimental, please don't use it until it improves a bit." Based on the docs I would think "Fill the voids with bridges" would have fixed the problem here but it has no effect and neither did the other options.
