### ISSUE TITLE
Bridge flow ratio has some crazy behavior.

### ISSUE THREAD

**Issue by celtare21** [supermerill/SuperSlicer#1497]
**Describe the bug**
Bridge flow ratio has some crazy behavior.
Firstly, 100% bridge flow doesn't use the extrusion width defined.
Example: with 0.45 default extrusion width and 100% bridge flow ratio as seen here: https://imgur.com/a/JDXcAtV
The feature type is "bridge infill" as seen here: https://imgur.com/a/JW4zcvy

Even strangly, it's shown to mess with the layer height as well: https://imgur.com/a/IABG0Io

**To Reproduce**
1. Load any STL with bridge infill
2. See in the Gcode preview the values
3. Change the bridge flow ratio
4. See the values change in a strange way

**>> Project File <<**
Project file: https://drive.google.com/file/d/1yk4QUFKzKhB9cQGRZtJDoLCfrelMkg1y/view?usp=sharing
I also added my print profile

**Expected behavior**
100% bridge flow would be the default extrusion width and changing it doesn't change the layer height.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.57, 2.3.56.8

**Comment by supermerill** [comment]
> Example: with 0.45 default extrusion width and 100% bridge flow ratio as seen here: https://imgur.com/a/JDXcAtV

tath's not how it works.
the width is the nozzle diameter.
see https://manual.slic3r.org/advanced/flow-math
