### ISSUE TITLE
Large gaps in 

### ISSUE THREAD

**Issue by laptop-laptop** [supermerill/SuperSlicer#1499]
**Describe the bug**

Print made using 2.2.53 only had two very small holes in between the two big circular holes on the bottom layer. In arm's distance, I can see those two small holes. The rest of the surface looked solid.  However, print made using 2.3.56.6 had those two very small holes turned large gaps. Also, many more big gaps of different sizes between perimeters (both circular and linear) were created for no reason. 

Are there any settings that I should change to eliminate those gaps created in 2.3.56.6?

<img width="1036" alt="gaps" src="https://user-images.githubusercontent.com/85510687/130376883-4c1c122a-0bb8-4c5c-a917-70c2693d7cf6.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 2.3.55.5], Use `Help->About`_: 2.3.56.6

**Comment by supermerill** [comment]
2.2.53 or 2.3.55 ?
I advise to update to latest stable (2.3.56.8).

Can you 

for these gaps, you have two solutions to hide them (beside using a smaller nozzle / width).
 * activate 'one perimeter on top' (with 0 min-width if on version 2.3.55 because it's buggy)
 * use ironing post-process

**Comment by laptop-laptop** [comment]
Thank you. I used to use 2.2.53 but tried 2.3.55 today. Then, I have issues with big gaps.

I will install 2.3.56.8 and print using your suggestion. The gaps are on the first layer at the bottom. How to have more over extrusion only on this layer?

**Comment by supermerill** [comment]
If it's a regression, i need your project file (File->Save As) used to create the gcode from the 2.2.53 and the 2.3.55 version, to check & fix it.

> How to have more over extrusion only on this layer?

Adjust your bel levelling to have elss space between it and the nozzle. Or increase the first layer flow.

**Comment by laptop-laptop** [comment]
Thank you. How can I increase the first layer flow only? Not sure if doing Ironing on the bottom layer helps. Can it be done under SuperSlicer? Prusa Support said that it cannot be done. They just suggested lowering the extruder's height.

**Comment by supermerill** [comment]
> How can I increase the first layer flow only

search for "first layer flow" in the search tool.

> Not sure if doing Ironing on the bottom layer helps

it does not, that's why i wrote 'assuming it's a top surface'

>

**Comment by laptop-laptop** [comment]
Thank you. I am very sorry that I cannot post project file for the public to access as it is work related. If I could, I would do it. If I don't post, it means I cannot post it due to privacy. Hope you understand my situation.

**Comment by supermerill** [comment]
sure.
If you have some time, you can clip the problematic region (~5 cuts) to avoid these kinds of problems.
