### ISSUE TITLE
fuzzy skin

### ISSUE THREAD

**Issue by supermerill** [supermerill/SuperSlicer#15]
like the cura one

edit: or just try to zig-zag between 1st and 2nd perimeter, like for looping perimeters?

**Comment by Gertsch** [comment]
Still on the to-do?

**Comment by supermerill** [comment]
yeah, many things to fix before.

**Comment by supermerill** [comment]
yes

**Comment by wolfgangmauer** [comment]
I need this very badly ;-)

**Comment by supermerill** [comment]
i'll merge the prusaslicer/cura code

**Comment by wolfgangmauer** [comment]
that's fantastic !
One thing to notice:
In PrusaSlicer the first layer has no Fuzzy Skin, in Cura it does.
I've already criticized that in PrusaSlicer, but it was ignored :-(
