### ISSUE TITLE
Need warning when max layer height is > nozzle diameter

### ISSUE THREAD

**Issue by nicedevil007** [supermerill/SuperSlicer#1502]
**Describe the bug**
My support seems to be completly broken with Superslicer. Everything works as expected if I use Ideamaker f.e.
![image](https://user-images.githubusercontent.com/17103076/130514578-eff565f9-182b-4383-9755-d1164feaab4b.png)

**To Reproduce**
1. I used those Support settings with 0.16 layer height and 0.2 layer height
![image](https://user-images.githubusercontent.com/17103076/130514622-b194b7e3-b605-4550-ac70-85b050f8f84a.png)

2. I also tryed these with 0.12 layer height
![image](https://user-images.githubusercontent.com/17103076/130514704-04f7fdf4-8df7-47bc-bfe3-bee2389b90e5.png)

**>> Project File <<**
the problem arise on every print with support, 100% reproduceable.

**Expected behavior**
Support should print like it should

**Screenshots**
posted above

**Desktop (please complete the following information):**
 - OS: Windows 11 22000.160
 - Version 2.3.56

**Additional context**
I didn't want to add a new issue and tryed my best in discord and friends using superslicer, but we couldn't figure it out :( Hope anyone here can help me.

**Comment by supermerill** [comment]
`>> Project File <<`

your project file?

**Comment by nicedevil007** [comment]
[projectfile.zip](https://github.com/supermerill/SuperSlicer/files/7041974/projectfile.zip)

**Comment by supermerill** [comment]
you set a max layer height of 1 for a 0.4 nozzle, that can't work well.
You sohouldn't put more of 80% of your nozzle height as max height.

I have to add a warning for that...

**Comment by nicedevil007** [comment]
Oh man! Thank you very much, 3 guys looked over my settings and nobody found the issue. will test soon, and thank you for the warning included in a future release!
