### ISSUE TITLE
Layer Time Goal is not respected - feature print speeds are not reduced at all

### ISSUE THREAD

**Issue by gpread** [supermerill/SuperSlicer#1515]
2.3.56.8

Creality CR-10, Marlin 2.0.8.2

The layer time view shows some layers with a  very short time (6 sec), when its expected to be 10 secs or more.

Those layers are actually purely auto generated support material layers which are within the object which itself is quite small (30x20x15mm).

Hence without any speed reduction (Support material speed is at 30mm/s) its to be expected that the time of such layers would be very short.

![image](https://user-images.githubusercontent.com/59426970/131266735-73b4fcf3-a3f4-49bf-9de4-c8dd212a7fb5.png)

The Layer Time Goal is set to 10secs, Max Speed Reduction set to 90% and Min Print Speed set to 15mm/s.  I have also tried bumping up the Layer Time Goal to much higher values (e.g. 100 secs) and there is no change in the outcome at all. All the layer times shown stay the same.

![image](https://user-images.githubusercontent.com/59426970/131266797-d05f90ff-36b5-4976-bcd5-df19ee9d0e9d.png)

As can be seen in the Speed view the speed of all the support material for all layers is the same 30mm/s (the current standard setting).  If the goal was being respected in this case, then just those particular support material layers would have the speed cut down to at least 20mm/s

I am printing PETG and trying to use the FAN for other than just bridging/overhangs causes wider issues (exacerbated by the fact that currently the speedup delay/advance for FAN has a bug too, see https://github.com/supermerill/SuperSlicer/issues/939#issuecomment-907836209)

So currently the resulting overheating on those 6 sec support material layers is causing subsequent adjacent layers of the object itself to get messed up.

I can't find an elegant/easy workaround either since a modifier does not allow adjustment of the speeds of support material or apply a specific FAN speed at all ?

In this somewhat unique scenario I can clobber the support material print speed globally though it still adds a lot of time to the print of each object  (~+7%).  For other more complex prints that solution is totally unworkable due to the time penalty incurred, meaning the only good resolution would be to post process/modify the output gcode by hand.

**Comment by supermerill** [comment]
I need your project file to reproduce.

**Comment by gpread** [comment]
Here you go, sorry should have done that right off the bat!

After more efforts to get my print better my sense is that the Layer time goal setting sometimes is having an influence but its not predictable or as expected and currently I am unable to give you additional concrete clues that helps identify further when/why/how it doesn't.

Hence I was tweaking, and I now don't have the project anymore with the exact same settings when I made the screenshots. 

However, the one below has slightly different settings but shows the exact same issue though (Goal of 30secs, 90% & min 1mm/s, supports speed@30mm/s - results in still some layers with 9sec and 25sec times and all supports shown with speed of 30mm/s).

[SSlicr_Bracket for 6mm SQ Arm_SSlicr_Issue#1515.zip](https://github.com/supermerill/SuperSlicer/files/7077072/SSlicr_Bracket.for.6mm.SQ.Arm_SSlicr_Issue.1515.zip)

Good luck and thanks in advance!

**Comment by supermerill** [comment]
I loaded your project file and i have that:
![image](https://user-images.githubusercontent.com/6536403/131353407-69132849-f735-4bfb-b82d-981914834fa8.png)

there is no object layer with time below 30sec.
Also, the algo takes into account the time it takes to print the supports, so if you use more than 30 sec for support +object layer, then it won't trigger

**Comment by gpread** [comment]
Ah ok, so perhaps it was just a misunderstanding (mis-expectation) on my part.  I did say in my initial report that the layers where I was seeing the goal as not being respected were purely support layers (no object extrusions at all were occurring on them).

So yes  now understood and accepted, the algo considers supports in that it won't slow down the object extrusions if the support extrusions take the total layer time to be >= goal time.  However, at the same time, if there is no object extrusion occurring then it allows those layer times to be less than the goal time. 

Thanks for clarifying, though I believe this behaviour can make for problems with melty supports (which may then contact the object in later layers), since the next layer can end up printing on top of the previous support only layer very quickly (in my case within a few seconds).

**Comment by supermerill** [comment]
> However, at the same time, if there is no object extrusion occurring then it allows those layer times to be less than the goal time.

it uses object layer + support layer, to compute the time. So if there is no object layer at a certain height, with too little support, it should slow down the support print.

**Comment by gpread** [comment]
> I loaded your project file and i have that:
> ![image](https://user-images.githubusercontent.com/6536403/131353407-69132849-f735-4bfb-b82d-981914834fa8.png)
> 
> there is no object layer with time below 30sec.
> Also, the algo takes into account the time it takes to print the supports, so if you use more than 30 sec for support +object layer, then it won't trigger

So surely then there should not be those layers shown in shades of blue and green (which represent  22, 17, 12 & 9 secs layers)  ?
And/or if you look at the speed view the supports for those layers/areas of the print they should be shown as having been adjusted down from their normal of 30mm/s ? (but they are not). 

Or does it slow such supports only layers down by adding a dwell or delay in some other way ? 

I believe I also found another clue/scenario where the speed/time is not adjusted as might be expected, it could be atomic or it might overlap and explain why (to me at least) its not currently doing what you are saying it should.

I have been testing/adjusting the settings for "small perimeter speed" and had been using 15mm/s.

I found that the Layer times  don't change towards the goal time - as the speeds are not being changed for small perimeters to less than what is set there, even if the Goal speed allows a slower speed setting (e.g. 1mm/s and 90% ).

![image](https://user-images.githubusercontent.com/59426970/131535787-fb3a0558-0d79-49fb-b205-0c6f4e4ea7db.png)

![image](https://user-images.githubusercontent.com/59426970/131535901-ca1e127d-60b0-473a-bae2-bf55cdb9866d.png)
 
![image](https://user-images.githubusercontent.com/59426970/131536259-01ffb57b-e711-4c9a-9153-0d717808760e.png)

![image](https://user-images.githubusercontent.com/59426970/131536581-313b03c2-9336-4dcc-a18c-0af921458be2.png)

![image](https://user-images.githubusercontent.com/59426970/131537048-82dc6be0-7fd8-4e42-8b6b-c710c7bb1af2.png)

[SSlicr_Bracket for 6mm SQ Arm_SSlicr_Issue#1515 - Small Perims.zip](https://github.com/supermerill/SuperSlicer/files/7085314/SSlicr_Bracket.for.6mm.SQ.Arm_SSlicr_Issue.1515.-.Small.Perims.zip)
