### ISSUE TITLE
Upload to Duet3 SBC generates 404 error

### ISSUE THREAD

**Issue by th0mpy** [supermerill/SuperSlicer#1527]
It's been a well documented issue with Slic3r, Prusa, and Super Slicer: You cannot use the upload interface to send gcode to a Duet 3 running in SBC mode. It does work fine in standalone mode. 

Prusa Slicer has integrated a fix into their code in the last year: https://github.com/prusa3d/PrusaSlicer/pull/4345 can this be integrated into SuperSlicer?

**Comment by supermerill** [comment]
> can this be integrated into SuperSlicer?

It's already integrated.

**Comment by th0mpy** [comment]
Hmmm, ok. I might be having a different issue then. I just noted that the error on my side did change from 404 to error 9. I'll dig.

Thanks!
