### ISSUE TITLE
[BR] 2.3.57.0. Gcode preview don't refresh if "Don't switch" selected

### ISSUE THREAD

**Issue by ldiegos** [supermerill/SuperSlicer#1532]
**Describe the bug**
When you change something in the "print settings", "Filament settings", and "Printer settings" versión 2.3.57.0 with the "change to g-code preview" is active, automatically change to the g-code preview when you change one value... so you have to start jumping to the previous tab again and again. With other versions, jumping to the gcode tab was only made when you repositioned the object in the plate, but not with the other tabs.

If you change the "dropdown list" to "Don't switch" the Gcode-preview tab never update any more(losing the current sliced model) and can't press the button "slice" that appear in the previous versions. It has dissapeared.

![image](https://user-images.githubusercontent.com/29803600/132294118-1e2d9aee-061e-4227-a48a-5514c4eacdbb.png)

![image](https://user-images.githubusercontent.com/29803600/132294155-81485774-dabc-4e38-8b34-75501e80f924.png)

![image](https://user-images.githubusercontent.com/29803600/132294185-13f0d64a-9535-4aa6-8fa3-e54779ff1621.png)

**To Reproduce**
1. Execute the version  2.3.57.0 over the 2.3.56.8 configuration files.
2. Click on preferences change the dropdown list to whatever option, expect "don't switch" and save.
3. Load a stl and try to change some configuration from the filament or printer settings.
4. See bug
5. Change the dropdown list to "don't switch".
6. Gcode preview tab never update again.
7. See bug.
8. 

**>> Project File <<**
*Please* upload a ZIP archive containing the project file used when the problem arise. Please export it just before the problem occur. Even if did nothing and there is no object, export it as it contains your current configuration.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 2.3.57.0

**Additional context**

**Comment by RafaelSchridi** [comment]
Experiencing the same issue here, But if I set switch to preview to something else and I manually click on gcode preview while its slicing it will also not refresh.

**Comment by ldiegos** [comment]
@supermerill  the problem is not just the "don't refresh" is that if you activate any other thing the superslicer starts jumping to the tab g-code preview what every configuration settings you change... That's horrible, annoying and boring.

In version 56.8 and 56.6 that not happen... the gcode is refreshed in background while you change the configuration but the screen not jump to it. only when change the position in the bed in the model tab.

**Comment by locki-cz** [comment]
it is back in latest 2.3.57.11

**Comment by CodeIsJustLikeMagic** [comment]
It is also in the 2.4.58.1 beta. Very annoying.
