### ISSUE TITLE
Disabled acceleration control still applies to print

### ISSUE THREAD

**Issue by nwgruber** [supermerill/SuperSlicer#1537]
**Describe the bug**
When I disable acceleration control by setting the default to 0, the additional acceleration parameters (perimeters, travel, etc.) are still applied to the print if left nonzero. Seeing as these input fields are disabled after default acceleration is set to 0 I don't think this is intended behavior.

**To Reproduce**
1. Enable acceleration control if turned off by setting default to some value
2. Assign a value to one of the other acceleration parameters (perimeters, infill, etc.)
3. Disable acceleration control by setting default to 0
4. Slice and print a model
5. Check the acceleration value on your printer

**Expected behavior**
When acceleration control is disabled and all the other fields are greyed out, I expected that they would not be applied to the print. In my screen shot below, the greyed out travel acceleration value would still be applied to the print.

**Screenshots**
![image](https://user-images.githubusercontent.com/72778707/132613559-d06b77e1-9b30-4e46-bec6-4e80553f25df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.3.57
 - Using klipper gcode flavor

**Comment by Laker87** [comment]
+

**Comment by gpread** [comment]
Yes I have seen this also but....  I saw it with prusaslicer (I think 2.3.1), so I suspect this is an inherited bug. I didn't report it since it was easy enough to get around (setting all the other entries to zero before setting default to 0).
