### ISSUE TITLE
hole_size_threshold = 0 

### ISSUE THREAD

**Issue by 5axes** [supermerill/SuperSlicer#1540]
According to the tooltips if we  set to **0** to let the hole_size_compensation apply fully for all detected holes (Convexe holes).

But If i fix this value to 0 then no compensation is added to the hole.

Tested on release 2.3.56.8 

 **hole_size_threshold fixed to 0 => No compensation**

![image](https://user-images.githubusercontent.com/11015345/132686179-f0a7af92-a2ac-4ab7-a76c-ad8215825677.png)

Extrem copensation with a hole_size_threshold fixed to 9999. In this case every convex hole are modified.

![image](https://user-images.githubusercontent.com/11015345/132686245-de0a009b-1e14-442b-93d4-a0c4c08d5e78.png)

Sample test part :
[Monotonic.zip](https://github.com/supermerill/SuperSlicer/files/7136498/Monotonic.zip)

**Comment by tome9111991** [comment]
confirm on 2.3.57.0
