### ISSUE TITLE
Can we load gcode to SuperSlicer and see how the virtual nozzle moves in the visualization?

### ISSUE THREAD

**Issue by laptop-laptop** [supermerill/SuperSlicer#1558]
**Is your feature request related to a problem? Please describe.**

I don't seem to find an option to allow us to load a gcode back to SuperSlicer and then see how the nozzle moves in the visualization. Is there such option? 

**Describe the solution you'd like**
See above

**Describe how it would work**
Just like loading a project file, load the gcode and play back the virtual nozzle movements.

**Comment by gpread** [comment]
File->G-code Preview is I think perhaps what you are looking for ?

Full features will only work if the g-code was created by slicer from the same bloodline and possibly the same slicer and version.

**Comment by laptop-laptop** [comment]
That is very nice. Thank you.

What you mean by same bloodline?

**Comment by gpread** [comment]
> That is very nice. Thank you.
> 
> What you mean by same bloodline?

Something that shares some of the same code (and hence the constructs, labels, comments, etc in the g-code can be common).

In this example/case with SuperSlicer there is at least (could be others too) overlap/heritage from Slic3r and PrusaSlicer

**Comment by laptop-laptop** [comment]
Thank you

**Comment by laptop-laptop** [comment]
In PrusaSlicer 2.4.0-alpha1, when the user slices and starts moving the horizontal slider in preview, it will show a gcode snippet and move the tool accordingly. When will Super Slicer has this feature perhaps also in File->G-code Preview?

**Comment by supermerill** [comment]
when prusaslicer code will be more stable, at the end of the beta stage.

**Comment by laptop-laptop** [comment]
Thank you. Looking forward to it.
