### ISSUE TITLE
2.3.57: Double Travel Between Perimeters

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#1560]
I wanted to double check if this was expected behavior. It seems like splitting the move like this could slow it down with jerk/accel limits:

![image](https://user-images.githubusercontent.com/12439543/133008837-8c5b3fd8-6e7a-4eab-aea6-924266919167.png)

[Objective Lens Cap.3mf.txt](https://github.com/supermerill/SuperSlicer/files/7150613/Objective.Lens.Cap.3mf.txt)

**Comment by supermerill** [comment]
I don't understand.

**Comment by CCS86** [comment]
Instead of a single travel move, from the end of one perimeter to the start of the next, it is splitting it up into 2 travel moves.

**Comment by supermerill** [comment]
that will add a useless line in the gcode, no?

**Comment by CCS86** [comment]
I don't follow. 

I'm saying the the current build, there are 2 travel moves, instead of one. To me it seems like a useless line of code, that could cause motion control to execute it slower than a single move. I wanted to check if you had a specific reason for doing this.

**Comment by gpread** [comment]
My intuition makes me wonder if this is related to #1550  ?

**Comment by supermerill** [comment]
> I'm saying the the current build, there are 2 travel moves, instead of one. 

weird, I saw only one.

**Comment by qwewer0** [comment]
> > I'm saying the the current build, there are 2 travel moves, instead of one.
> 
> weird, I saw only one.

> Objective Lens Cap.3mf.txt


@supermerill Try at Z=7mm, 40298-40300.

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/134968167-284462fe-b583-4ad1-91ff-1c51ec5781bc.png)
something is wrong.
what version?

**Comment by qwewer0** [comment]
> it's at 7.2
> something is wrong.
> what version?

I tried it with 2.3.57, but here is a video of it:

https://user-images.githubusercontent.com/57561110/135022170-25bbf535-d906-4a19-a02e-91eb60f85ad4.mp4
