### ISSUE TITLE
Max Layer Height Limit Won't Set to Zero

### ISSUE THREAD

**Issue by TD5023** [supermerill/SuperSlicer#1569]
**Describe the bug**
When a nozzle size isn't set to 0.4 or 0.5 (maybe more, but these are the ones I found that work), attempting to set the max height value to zero in order to calculate based off the nozzle will force set it to .005. I can still set it to a hard value manually.

![Capture](https://user-images.githubusercontent.com/55936565/133898299-8477b073-9906-4640-a2f3-d7bbc4efe3bc.JPG)

**>> Project File <<**
[max height issue.zip](https://github.com/supermerill/SuperSlicer/files/7190424/max.height.issue.zip)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.57.0

**Comment by qwewer0** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/57561110/133906243-84885f8f-84e9-40f4-8fb5-f5fa8a9659da.png)
