### ISSUE TITLE
"Ensure Vertical Shell Thickness" conflicts with Spiral Vase instructions

### ISSUE THREAD

**Issue by yonkiman** [supermerill/SuperSlicer#1582]
**Describe the bug**
When you select **Spiral vase** mode, a pop-up appears that says "Ensure vertical shell thickness enabled".  However it does not automatically check the **Ensure vertical shell thickness** box.  When you manually select **Ensure vertical shell thickness**, the pop-up reappears, and the **Ensure vertical shell thickness enabled** becomes unchecked when you close the pop-up.

In other words, while the pop-up says "Ensure vertical shell thickness enabled", it behaves as if it's saying "Ensure vertical shell thickness disabled"

**To Reproduce**
1. Select **Spiral vase** mode.
2. Note that pop-up says "Ensure vertical shell thickness enabled"
3. Attempt to enable **Ensure vertical shell thickness**
4. See what happens

**>> Project File <<**
[spiral vase issue.zip](https://github.com/supermerill/SuperSlicer/files/7211012/spiral.vase.issue.zip)

**Expected behavior**
Would expect pop-up and behavior to match

**Screenshots**
![Screenshot 2021-09-22 06 10 16](https://user-images.githubusercontent.com/12636032/134352295-a282d120-33be-4252-89f8-e93ce32f44cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.3.57.0

**Comment by supermerill** [comment]
oh, it's a bad merge

there is a change by prusa that change from disabled to enabled
`the "ensure vertical shell wall" is enforced in spiral vase mode
to extend the bottom of the vase to the vase hull.`
