### ISSUE TITLE
Gcode seems to be at wrong x/y position

### ISSUE THREAD

**Issue by jesterhead82** [supermerill/SuperSlicer#1583]
**Describe the bug**
When slicing for example the attached files the Gcode seems to be at wrong x/y positions, using 2.3.57
This happens also when i slice other objects.
FYI: This happens only with my second printer profile (first one is 1 300x300 printer, 2nd is a 180x180 printer), this does not happen on the first printer (here it gets centers in the gcode as in the plate view)

Plate:
![image](https://user-images.githubusercontent.com/11690785/134416590-f81204f9-cb54-4719-9a1b-0a5ac0d8d72e.png)

Sliced:
[Mini Bear 2 Left Z-Axis_with Retract.zip](https://github.com/supermerill/SuperSlicer/files/7213589/Mini.Bear.2.Left.Z-Axis_with.Retract.zip)
![image](https://user-images.githubusercontent.com/11690785/134416626-a1b2bd95-92ae-4df9-8999-743211d6ae3d.png)

GCode Preview:
![image](https://user-images.githubusercontent.com/11690785/134416658-a27ee3ea-caf4-4ac7-aa88-d6578ce04974.png)

Gcode In PS Gcode viewer:
![image](https://user-images.githubusercontent.com/11690785/134416939-69dcb6cf-6beb-4d69-91df-519c8cb97fae.png)

[Mini Bear 2 Left Z-Axis_with Retract.zip](https://github.com/supermerill/SuperSlicer/files/7213595/Mini.Bear.2.Left.Z-Axis_with.Retract.zip)

**Comment by jesterhead82** [comment]
Hello,

I found out that only the Gcode view seems to be shifted (for all prints), but when I print the sliced Gcode everything is fine.

**Comment by supermerill** [comment]
maybe something with 32 bit precision somewhere... i'll check.

**Comment by supermerill** [comment]
your start_filament_gcode
```
; Filament gcode
G0 Z0.2;Move to default first layer height
G92 Z0.2-0.04} ; Positive Value means lower z base
G0 Z0.2;Move to adjusted first layer height

; Filament gcode\nM900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.1{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}0{endif} ; Filament gcode
```
look at the third line, there is an error.
do you mean `G92 Z{0.2-0.04}` ?

**Comment by jesterhead82** [comment]
Typo on my side ;)

But still happening after fixing that.

**Comment by supermerill** [comment]
> But still happening after fixing that.

are you sure? it fixes it for me.

**Comment by jesterhead82** [comment]
Hmm, relselectedfilament type then it worked for me too, sorry about that
