### ISSUE TITLE
Printer settings>General>Bed shape > Circular 

### ISSUE THREAD

**Issue by boksbox** [supermerill/SuperSlicer#1584]
### Version
_Version of SuperSlicer used goes here (help->about)_
2.3.56.9
### Operating system type + version
_What OS are you using, and state any version #s_
Mac OS 10.14.6
### Behavior
* _Describe the problem_
* Bed shape diameter entered 160.  When bed shape settings opened again, it shows 159.999999
* 
* _Steps needed to reproduce the problem_  
* The problem appears everytime when the settings are clicked again.
* _Expected Results_
* Entered value should stay the same.
* _Actual Results_
* Slightly smaller value
* 
  * _Screenshots if useful_

_Is this a new feature request?_
No.

Related guides for writing feature requests: http://meta.stackexchange.com/a/259196 http://nickohrn.com/2013/09/write-great-feature-request-bug-report/

#### Project File (.3MF) where problem occurs
_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here_

**Comment by supermerill** [comment]
now rounded to 1um
