### ISSUE TITLE
Graphical glitches in seam

### ISSUE THREAD

**Issue by guestisp** [supermerill/SuperSlicer#159]
### Version
2.2.47

### Operating system type + version

```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

### Behavior

As visibile in the screenshot (i've also atteched a 3mf file), there are some ugly glitches on the seam location (I think it's the seam location)

![Schermata da 2020-01-31 22-01-09](https://user-images.githubusercontent.com/3944655/73886594-39b33300-486a-11ea-8b40-f413f1b1817d.png)

![Schermata da 2020-02-05 22-49-03](https://user-images.githubusercontent.com/3944655/73886607-3e77e700-486a-11ea-8a08-aeb0825e7a91.png)

_Is this a new feature request?_

no

#### Project File (.3MF) where problem occurs

[cube-40-40-40.zip](https://github.com/supermerill/Slic3r/files/4162193/cube-40-40-40.zip)

**Comment by supermerill** [comment]
I forgot to auto-uncheck "vase mode seam" when "external periemeter first" is unchecked.
To correct your issue, check "external periemeter first" , uncheck "in vase mode" then  uncheck "external periemeter first".

**Comment by guestisp** [comment]
Your are right, manually unchecking that solve this issue

**Comment by supermerill** [comment]
forgot to say it's corrected now
