### ISSUE TITLE
add "max overlap" option for viscous filament

### ISSUE THREAD

**Issue by supermerill** [supermerill/SuperSlicer#1590]
Some filament are too viscous to flow under the already printed line next to it.
So it need to be printed just be more spaced apart

Adding a filament parameter to set the max spacing should do the trick. It's like the perimeter overlap but also for solid infill.

from https://discord.com/channels/771316156203270154/771319294113742858/888357553036218430

**Comment by VanessaE** [comment]
This feature seems to have quit working recently (at least, it's broken in 2.4.58.5)..  While trying to sort out a problem I'm having with printing very thin layers, I tried turning the max overlap down... but it has zero effect on the print.  Even all the way down at 1% -- I should be able to basically end up with a sieve with a setting like that, but nope.

Both the parameter in the filament profile and the settings in [Print Settings -> Width & Flow -> Overlap] are inert.
