### ISSUE TITLE
After program completes slicing, there is no preview available

### ISSUE THREAD

**Issue by viperman3** [supermerill/SuperSlicer#1591]
**Describe the bug**
After program completes slicing, there is no preview available on display.
This behavious occurs on both background processing option active and deactive (manual slicing)

**Screenshots**
![image](https://user-images.githubusercontent.com/73435822/134807402-1b85156b-d8ad-4ca0-82fc-0efb84fc9e9f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.57.0

**Additional context**
Issue does not occur on previous release version 2.3.56.8

**Comment by supermerill** [comment]
maybe same problem as #1532 #1533 ?
