### ISSUE TITLE
Hightlight seam location in preview

### ISSUE THREAD

**Issue by guestisp** [supermerill/SuperSlicer#160]
### Version
2.2.47

### Operating system type + version

```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

### Behavior

Please add a "seam" option in preview, to show the seam location, like "Travel", "Retractions", "Unretraction", "Shells", "Legend" and ...... "Seam"

_Is this a new feature request?_

yes

**Comment by supermerill** [comment]
why not. I'll look if it's easy to add.

**Comment by guestisp** [comment]
Did you have a chance to check this ? It's very useful.
Also, I would suggest to differentiate retraction and unretraction colors from the preview. Actually they are both white.

**Comment by supermerill** [comment]
noted.
Didn't took the time for this yet.

**Comment by wesc23** [comment]
+1 on this feature.  visualizing seam placement is very important to reduce reprints due to bad seem locations.

**Comment by stevenignys** [comment]
+1 this would be very useful. Also a way to specify the seam or allowable location maybe like the support allow and stop blocks

**Comment by supermerill** [comment]
> Also a way to specify the seam or allowable location maybe like the support allow and stop blocks

you can discuss on that in #152

**Comment by supermerill** [comment]
implmeented by prusaslicer
