### ISSUE TITLE
Large volume flow rate on seam

### ISSUE THREAD

**Issue by dmitrydprog** [supermerill/SuperSlicer#1602]
**Describe the bug**
Large volume flow rate on seam. 

**To Reproduce**
1. Export my config bundle
[SuperSlicer_config_bundle.ini.zip](https://github.com/supermerill/SuperSlicer/files/7271691/SuperSlicer_config_bundle.ini.zip)
2. Load model (ring with two perimeters)
[Ring.stl.zip](https://github.com/supermerill/SuperSlicer/files/7271694/Ring.stl.zip)
3. Slice model (see on Volumetric flow rate)
![Screenshot 2021-10-02 at 22 05 40](https://user-images.githubusercontent.com/10886027/135722243-ea46cac8-443f-4b9f-b76d-91ef8ebee4f5.png)

**>> Project File <<**

[Ring.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7271696/Ring.3mf.zip)

**Expected behavior**
Volume flow rate in normal value.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Version 2.3.57, also 2.3.56.8

**Additional context**

Video with print this area: https://youtu.be/87PR-eIniQw

**Comment by supermerill** [comment]
you have a `G92 E0.0` at your custom gcode layer cahnge.
as you didn't set the printer to use relatice extrusions, the extruder has to make bigger and bigger extrusion to go back to the absolute value.

**Comment by dmitrydprog** [comment]
Thanks you, it's worked.
