### ISSUE TITLE
Nightly (1f97037) - ConfigBase::get_abs_value(): seam_gap has not a valid option type for get_abs_value()

### ISSUE THREAD

**Issue by TommyC81** [supermerill/SuperSlicer#1606]
**Describe the bug**
When slicing, getting error message "ConfigBase::get_abs_value(): seam_gap has not a valid option type for get_abs_value()"

**To Reproduce**
1. Start SuperSlicer
2. Drag and drop STL
3. Press "Slice"
4. Get error text

**>> Project File <<**
[SuperSlicer Nightly (1f97037) - Error.zip](https://github.com/supermerill/SuperSlicer/files/7275718/SuperSlicer.Nightly.1f97037.-.Error.zip)

**Expected behavior**
Slicing happens without error.

**Desktop (please complete the following information):**
 - OS: Windows 10 (fully updated)
 - SuperSlicer 2.3.57.1 (Nightly 1f97037)

**Comment by Sirage48** [comment]
Also on OS Mac.

This problem does not exist on the previous nightly 2.3.57.1 which works.
