### ISSUE TITLE
[Feature request] measure distance node to node

### ISSUE THREAD

**Issue by SphaeroX** [supermerill/SuperSlicer#1625]
to scale certain objects it would be good if you could measure the distance between two points.

Here is an example: https://discourse.slicer.org/t/distance-measurement/8495

Would something like this also be conceivable for the SuperSlicer? it would already be sufficient in the 2D area.

**Comment by supermerill** [comment]
I'm not against it, far from it.
But it may take days to implement.
And the UI is often changed by prusa, so it may be complicated to merge this far in the future.
Maybe you can ask this feature for prusaslicer? I think there may be already an issue open for that.
