### ISSUE TITLE
Symlink (/usr/bin/superslicer-gcodeviewer) points to slic3r

### ISSUE THREAD

**Issue by LuckyTurtleDev** [supermerill/SuperSlicer#1627]
**Describe the bug**
after building and installing SuperSlicer, I notify that the
Symlink `/usr/bin/superslicer-gcodeviewer` points to slic3r.

**To Reproduce**
* build Superslicer
* install Superslicer

**Desktop (please complete the following information):**
 - OS: Manjaro (probably other Linux distros too)
 - Version  superslicer-git aur package 1a483260c

**Comment by Lukas1818** [comment]
still in 2.3.57.8

**Comment by supermerill** [comment]
yes. It's the same program, but it detects what to launch.
It creates the slicer instead of the gcodeviewer?

**Comment by Lukas1818** [comment]
```bash
ls -l /usr/bin/superslicer-gcodeviewer 
lrwxrwxrwx 1 root root 6  6. Jan 15:52 /usr/bin/superslicer-gcodeviewer -> slic3r
```
`superslicer-gcodeviewer` shows to `slic3r`, witch means that `slic3r` will be started (if installed) instead of `superslicer`, when `superslicer-gcodeviewer` is executed.
I would expect `/usr/bin/superslicer-gcodeviewer -> superslicer` instead of `/usr/bin/superslicer-gcodeviewer -> slic3r`

**Comment by supermerill** [comment]
oh, ok

**Comment by Tapchicoma** [comment]
Can confirm applying this diff fixes the issue on Linux:
```diff
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -273,5 +273,5 @@ else ()
     install(TARGETS Slic3r RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")

     # Install the symlink for gcodeviewer
-    install(CODE "execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink slic3r ${GCODEVIEWER_APP_CMD} WORKING_DIRECTORY \$ENV{DESTDIR}/${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR})")
+    install(CODE "execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${SLIC3R_APP_CMD} ${GCODEVIEWER_APP_CMD} WORKING_DIRECTORY \$ENV{DESTDIR}/${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR})")
 endif ()
```
