### ISSUE TITLE
Crash when creating an Octoprint hardware printer

### ISSUE THREAD

**Issue by laptop-laptop** [supermerill/SuperSlicer#1631]
**Describe the bug**

I am not sure if I did that incorrectly or it is a bug. For the past year on both SuperSlicer and PrusaSlicer, sometimes when I set up an Octoprint connection, the program exited by itself. For example, today I pressed the cogwheel icon under Printer Settings. I entered the name of the printer, octopi.local as the URL and the pasted the API from the web browser. Clicked the Test button and no error. SuperSlicer told me that the name of the printer already existed and asked if I would like to replace it. I clicked OK. Then, the program exited by itself. I had to launch the program again and re-enter the name, URL and API. Then, when through the same thing and the program exited for no reason again. Over the year, sometimes both programs exited when I pressed the Test button. I wonder if my way of setting up the Octoprint connection is wrong.

**To Reproduce**
See above

**Desktop (please complete the following information):**
Windows 10
SuperSlicer 2.3.56.9

**Comment by supermerill** [comment]
thanks
I'll add a bunch of logs to try t pinôint the moment when it crash. I'll come back to you this week.

**Comment by laptop-laptop** [comment]
Thank you. Is there a limit on the number of times I execute "[...]\superslicer_console.exe --loglevel=3"? 

As another test, I entered the printer name, url and API. Then, pressed the return key when the cursor was in the API entry box. Again it crashed. 

I tried to get the logs but I can no longer use the command you listed to launch SuperSlicer. Windows keep telling me that the application cannot be executed on my PC.

**Comment by SW0rden** [comment]
I'm seeing this same issue.  Spent some time setting up everything for print settings etc. and after "Add physical printer" and Octoprint settings, SS crashes to the desktop.  Since I hadn't saved the presets (my bad), all was lost upon restarting SS.

Upon further testing, I have found that if you set your bed size (and a texture in my case), before you "Add physical printer", it will crash every time.  If you set your bed size afterwards, it works fine.

Windows 10
SS Version 2.3.56.9

**Comment by supermerill** [comment]
> Upon further testing, I have found that if you set your bed size (and a texture in my case), before you "Add physical printer", it will crash every time. If you set your bed size afterwards, it works fine.

can't make it crash.
What are the exact steps?

**Comment by SW0rden** [comment]
Open SS, go to Printer Settings tab, Bed Shape/Set, change the bed size and OK, Edit Physical Printer and set it up for Octoprint, hit OK.......crash to desktop.

If you Edit Physical Printer and set up for Octoprint first and then set the bed size, your fine.
