### ISSUE TITLE
Prints pausing during printing and then continuing...

### ISSUE THREAD

**Issue by Durahl** [supermerill/SuperSlicer#1632]
Greetings!

I've recently started using **SuperSlicer** instead of PrusaSlicer since converting over from a Prusa i3 MK3S to a **Voron 2.4** which means I've been changing both the Soft and Hardware I'm familiar with.

Both Systems have / are running via **OctoPrint** ( situated on a **Raspberry Pi4** ) but only the SuperSlicer / Voron combo is displaying a repeating problem where every full moon or so it would pause mid print for like 1-5sec - possibility contemplating about forming a 3D Printer Union - and then continue as if nothing happened.

While technically not a severe issue the area where it stops now has [a tiny blob of filament](https://i.imgur.com/Qibh1Dk.jpg) sticking out that needs to be dealt with ruining the otherwise pristine surface finish ( _that_ surface finish was garbage... I just couldn't find another image showcasing the issue )

What I've noticed so far with this issue is it usually appearing ( I'd be even inclined to say almost always ) at screw **holes** or complex **round** geometry like the transition area between the toothed area of [80T Pulley Wheel](https://github.com/EtteGit/EnragedRabbitProject/blob/main/Carrot_Feeder/Stls/Gear%20box/%5Ba%5D_M4_80T_Wheel.stl) back to the smooth perimeter. It also appears to be an **External Perimeter** related issue.

[On this Slicer Screenshot](https://i.imgur.com/lHXSqQW.png), blobs would in general show up where the **External Perimeter** ( Orange ) and the **Overhang Perimeter** ( Blue ) keep alternating between each other like mad - Could this be the cause? 🤔

**Comment by Durahl** [comment]
Thanks for the support!

Regarding the `Overhang Threshold` I assume you're referring to `Print Settings` > `Support Material` > `Overhang Threshold`?
My currently running print still showcasing this problem has this setting greyed out @ `30°` as the `Auto Generated Supports` has been disabled so assuming it not being used to begin with makes tinkering with it kinda futile? 🤔

As for the `Filtering Resolution` my current setting is `0.002` - Should I bump it to like `0.01`? ( PrusaSlicer has it's set to `0` which I interpret at 1:1 soo... Not the greatest reference starting point 😑 ). The `Advanced` > `Minimum Extrusion Length` was set to `0.035` which I kinda feel like bumping to `0.07` or maybe `0.1`? I mean those are some _really_ tiny values 😮 ( PrusaSlicer is missing this setting completely so again no reference 😥 )

**Comment by terencemuscat** [comment]
Hello,

I just finished my toolchanger using duet 3 with hemera toolboards. I am facing the same issues,  pausing during printing. I'm trying to print a benchy and im having blops constantly on one side from all the pausing being done during the print. I decreased the processing limit (g1 per second)from 1000 to 150, and the minimum extrusion length up to 0.05 but results remained the same.

Did you manage to fix it?

Also, unrelated issue. A toolchanger needs a T0 / T1 etc command at start of print, so to instruct it to pick the tool. This is not happening automatically and had to insert the tool number manually in the start g code. ps, Tool number is added if different extruders are used in a process (through the sliced preview).

Thankyou!

**Comment by supermerill** [comment]
> Also, unrelated issue. A toolchanger needs a T0 / T1 etc command at start of print, so to instruct it to pick the tool.

add `T{current_extruder}` to your start gcode.

> results remained the same.

I have a report that the 'g1 per second' is ignored for wipe moves (have to fix that), does it happens during wipe?

**Comment by terencemuscat** [comment]
Currently wipe is unticked by default. 
I will increase the resolution and model rounding precision this evening. (currently 0.002 & 0.0001 and will increase them to 0.01 and 0.001).
If it does not work I will send a video. Thankyou.

**Comment by terencemuscat** [comment]
@supermerill
All ok now with reducing precision to these values. I still don't understand how the latest board can't handle all this information, anyways, I don't think that such a miniscule increase will make a difference. Thanks for everything and well done on super slicer!
![Capture](https://user-images.githubusercontent.com/95451915/144638744-14a9aa86-c7e4-49ea-8b00-3422b6002130.JPG)
