### ISSUE TITLE
2.2.47 lag

### ISSUE THREAD

**Issue by DirtySteve9600** [supermerill/SuperSlicer#164]
Seeing alot of lag in version 2.2.47 compared to prior releases.

Slow to change tabs, and all settings. Doesn't crash but getting alot of 'Not Responding" time-outs.

Windows 10, 64 bit

**Comment by supermerill** [comment]
You can rename ui_layout to something else. The "advanced" layout it's creating seems just a bit longer to compute.
With the new layout, it's not instant but almost (<0.5s anyway in my weak win64 tablet)

**Comment by DirtySteve9600** [comment]
Same lag problem with  prusaslicer2.2.0-alpha2.
Running on board Intel HD graphics video chipset.

**Comment by supermerill** [comment]
can i close?
