### ISSUE TITLE
"Gap Fill: Min Surface" setting is ignored 

### ISSUE THREAD

**Issue by DontTakeItForGranted** [supermerill/SuperSlicer#1640]
**Describe the bug**
The "Gap Fill: Min Surface" setting is completely ignored, Whatever percentage value or number you put in there no gap fill is placed (picture below).
(gap fill works on smaller gaps when i lower the perimeter extrusion width)

**Expected behavior**
putting a low value in the setting box (below 100% which is the standard) and gap fill will be placed in smaller gaps
**Screenshots**
![Bildschirmfoto 2021-10-13 um 20 26 06](https://user-images.githubusercontent.com/87256384/137213545-98fc9410-e9a8-48b4-8eb7-6c9ff89c2105.png)
(there is gap fill in bigger gaps but there is no gap fill between the external perimeters shown in the center of the picture)

**Desktop:**
 - OS: MacOS Catalina
 - Version 2.3.56.9 and 2.3.57.1
 
[3D PRINTER BOX SHAKER v9.2.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7341519/3D.PRINTER.BOX.SHAKER.v9.2.3mf.zip)

**Comment by JonBerlin** [comment]
![](https://i.imgur.com/0aXxGPK.jpeg)
It took me quite a while to figure out how **Min Surface** for **Gap Fill** works.
It's necessary to enter a high value 500%+ to start seeing an effect at all (and don't forget the %).
