### ISSUE TITLE
filament:Basic PET @VORON inherits *BasicPLA* should be *BasicPET*

### ISSUE THREAD

**Issue by NikosSprocket** [supermerill/SuperSlicer#1661]
**Describe the bug**
Current Voron.ini has:
.............
[filament:Basic PET @VORON]
inherits = *BasicPLA*
.............
[filament:Basic PET VOLCANO @VORON]
inherits = *BasicPLA*

Both entries "inherits = *BasicPLA* should be replaced with "inherits = *BasicPET*"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.3.56.9
[Voron-ini.txt](https://github.com/supermerill/SuperSlicer/files/7376451/Voron-ini.txt)

**Comment by NikosSprocket** [comment]
Sorry! New with GitHub.

Will do next time.

Cheers,
Nikos

**Comment by voron** [comment]
none for now, as long as `voron` is not prefixed by `@`
