### ISSUE TITLE
[FR] Time remaining display with M117

### ISSUE THREAD

**Issue by kb-elmo** [supermerill/SuperSlicer#1693]
**Is your feature request related to a problem? Please describe.**
No. Just a nice to have feature.

**Describe the solution you'd like**
Add an option to display remaining print time via M117 on the printers info screen (similar to how the Cura time remaining plugin does it).
That way printers that don't support the M73 command can show the remaining time as well.

**Describe how it would work**
Send the M117 command with a preconfigured message together with M73 for updating the display with the remaining estimated print time. E.g "M117 Time Left 1h32m15s"

**Additional context**
Example of how the remaining time info looks like generated by the Cura plugin:
![example](https://i.imgur.com/BnEysMul.jpg)

**Comment by WalnutFox** [comment]
@supermerill Can this be adjusted to allow the remaining time to be a placeholder for custom messages such as:

M117 **[time_remain]** to go

sorry to comment on this just figured I would ask here since it is related to 7ac7a0a
