### ISSUE TITLE
Removing pins from imported SLA tree supports

### ISSUE THREAD

**Issue by inspectionsbybob** [supermerill/SuperSlicer#1704]
### Version  2.3.56.9
_Version of SuperSlicer used goes here (help->about)_

### Operating system type + version
_What OS are you using, and state any version #s_
**Win10 current patches**
### Behavior
I am used to using the SL-1 profile in PrusaSlicer to produce really nice tree/pin supports for a filament printers. .. I export that with supports and open it again with the printer I am going to use and slice without supports.  I get a good approximation of TREE SUPORTS.  

Issue is I end up with a forest of pins under my Object.   Since it will be resliced for a filament type printer, is there any way to do a "negative pad" or something like that, otherwise I have to sink the model into a raft or something like it so it doesn't kill its self on all the pins, retracting, retracting, retracting...

If not.... I would like to put thins in for a feature request update thing...

**Comment by supermerill** [comment]
Understood. I'll wait for 2.4 merge.

note: Please use github to post an answer (or be careful), as here you publish your phone numbers and mail on a public internet. And there is no pictures.

**Comment by inspectionsbybob** [comment]
Forgot the photo....
