### ISSUE TITLE
Feature request: Acceleration Control, more options

### ISSUE THREAD

**Issue by TheBoojah** [supermerill/SuperSlicer#1715]
I'd like to see added the following acceleration settings:
Top, solid and sparse infill (matching speed settings basically) 
External perimeters

I would like to print top layers with slower accelerations compared to regular solid infill. On my printer I can see a bunch of ringing on top layers, but I do not want to print solid infill any slower as that could impact printing time a lot. Also the sparse infill could be printed at maximum acceleration while you might want something reasonable on solid infill. Or the opposite where very fast and low fill sparse infill might require slower accelerations to print well. Bridging with the sparse infill usually fails if you accelerate too fast, as the initial line is torn off. As seen on sparse infill that does not go over itself on every layer.

External perimeters could be printed both slower and lower accelerations, especially together with the new perimeter overlap parameter where the internal perimeters can be printed much faster and not show as much ringing trough to the external one.

Thanks for considering!

**Comment by julianschill** [comment]
I think this is already covered by #696
