### ISSUE TITLE
Option to hide lock/dot icons

### ISSUE THREAD

**Issue by comps** [supermerill/SuperSlicer#1729]
**Is your feature request related to a problem? Please describe.**
The lock/dot icons cause noticeable UI clutter which made me stay on an older Slic3rPE version for quite a while. While thy make sense for Prusa and their fine-tuned stock profiles, they're just in the way of people maintaining their own profiles, potentially changing many settings for each print.

**Describe the solution you'd like**
A checkbox in the settings which would enable hiding the lock/dot icons for any presets detached from a parent system preset (or, if too hard to implement, for all presets).

Thanks!

**Comment by liftbag** [comment]
Oops, sorry, I was not aware that there was a specific setting in the latest versions.
<img width="726" alt="Schermata 2021-11-01 alle 09 20 56" src="https://user-images.githubusercontent.com/14921654/139642873-dc214e5e-4c83-4555-87ac-5fdd2b2340cf.png">
