### ISSUE TITLE
Brim Ears and Supports overlap as if the other weren't there.

### ISSUE THREAD

**Issue by Katherine1** [supermerill/SuperSlicer#1745]
**Describe the bug**
When using both brim ears and supports, if the two end up on the same area of the model, they will both be placed down as if the other isn't there.

**To Reproduce**
1. Add a model that has an overhang in an area that brim ears would cover
2. Add support to that area of the model
3. Set a brim width and enable brim ears
4. Observe the intersection of the two extrusions

**Expected behavior**
Either the first layer of supports gets replaced by the brim ear where the brim ear exists, the brim ear should wrap around the supports as a regular brim does, or the brim ear should not be placed in areas that already have supports. Regardless, the two extrusions shouldn't intersect like this.

**Screenshots**
![image](https://user-images.githubusercontent.com/3453183/139559922-44f4d014-aed1-44eb-8fae-8150dc925c54.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 2.3.56.9

**Comment by supermerill** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/6536403/139560613-4be393f0-f7be-4d47-9aca-bafd0a460392.png)

Can you upload your project file?

**Comment by Katherine1** [comment]
I think I can do that. The part is a purchased model, but it is under the Creative Commons Attribution-NonCommercial-NoDerviatives licence, so sharing is technically allowed.

The part in this file comes from VectorFinesse's Head(amame) headphones.
[Spring Clamp.zip](https://github.com/supermerill/SuperSlicer/files/7447742/Spring.Clamp.zip)

**Comment by supermerill** [comment]
you can remove now if it's need, and i can delete it when resolved.

**Comment by Katherine1** [comment]
I'm not sure if putting it in a 3mf file constitutes modifying it as it was originally an stl, so I'll play it safe and remove it.

**Comment by schattenphoenix** [comment]
My issue might be related.
When I have brim set and skirt loops not zero, both are created causing crossing lines.
It's not a huge problem as one or the other can be disabled but it feels like this might have some relation to your issue.

**Comment by supermerill** [comment]
If you ahve this usse, check 'solid first layer' in the raft settings, and the brim should be good.

there seems also that 'skirt dist from brim' doesn't takes into account the support 'offset'

**Comment by schattenphoenix** [comment]
![image](https://user-images.githubusercontent.com/22476644/139596007-37c80bb3-e05a-4abb-a42f-90db69bc7aa7.png)
This is what I currently have, but I assume it only takes effect if I add raft layers (at least 1)?

With these settings the "issue" is not fixed.
It's not a real issue, I was mostly wondering if this could not be solved more elegantly 👍

**Comment by supermerill** [comment]
> With these settings the "issue" is not fixed.

then it's not the same issue.
I don't know what you want to say by "causing crossing lines".
