### ISSUE TITLE
Using a 0.3 height profile with a 0.4mm nozzle raise the error "layer height can't be greater than max layer height"

### ISSUE THREAD

**Issue by jfestrada** [supermerill/SuperSlicer#1748]
**Describe the bug**
Using the Vertex profile (any machine) for 0.4mm nozzle and layer height 0.30mm is raising the error "Layer height can't be greater than max layer height".
The issue only happen with the version 2.3.57.3 using the 2.3.56.x and the same profile is working fine 
I have tested on windows and linux with the same results, and with Vertex and Prusa profiles

**To Reproduce**
1. Add a the Vertex XL machine with nozzle 0.4
2. Add an stl
3. Choose the profile "0.30mm DRAFT"

**Expected behavior**
Slice the stl as usual

**Screenshots**
VERTEX XL 
![imagen](https://user-images.githubusercontent.com/7290345/139577862-47816a97-b888-4107-8efc-20e1da66ff0f.png)
PRUSA MK3S+
![imagen](https://user-images.githubusercontent.com/7290345/139578367-aed6e8d8-9087-463c-9589-e3d86d1c9bc1.png)

**Desktop (please complete the following information):**
 - OS: Linux and Windows 10
 - Version: 2.3.57.3

**Comment by tome9111991** [comment]
hello
you have tried to edit the "Layer height limits" ?

Printer Settings -> Extruder

**Comment by jfestrada** [comment]
> hello you have tried to edit the "Layer height limits" ?
> 
> Printer Settings -> Extruder

You were right, that's the solution, I suppose that this check was not done in previous releases.

**Comment by supermerill** [comment]
yes, it's a new check, to avoid more problems.
