### ISSUE TITLE
UNLOCKED LOCK and WHITE BULLET icons are missing (macos)

### ISSUE THREAD

**Issue by liftbag** [supermerill/SuperSlicer#1755]
**Describe the bug**
Starting from the Nightly 417 and up to the most recent, the lock/unlock and white dot icons next to the parameters seem to be disappeared.

**>> Config bundle <<**

[SuperSlicer_config_bundle.ini.zip](https://github.com/supermerill/SuperSlicer/files/7449510/SuperSlicer_config_bundle.ini.zip)

**Expected behavior**

<img width="1709" alt="Schermata 2021-10-31 alle 19 38 24" src="https://user-images.githubusercontent.com/14921654/139597096-46525b1f-4b80-4a24-b505-3a1bdfbeb243.png">

**Actual behavior**

<img width="1665" alt="Schermata 2021-10-31 alle 19 39 54" src="https://user-images.githubusercontent.com/14921654/139597131-b7384b0e-6d24-4469-8061-c20d3dbc3857.png">

**Desktop:**
 - OS: MacOS 12.0.1 Monterey
 - From nigthly macos 417 to 420.

**Comment by tome9111991** [comment]
Hello.
You can look at https://github.com/supermerill/SuperSlicer/issues/1729
Looks is a new feature

**Comment by supermerill** [comment]
It shouldn't be activated by default...

**Comment by liftbag** [comment]
Oops, sorry, I was not aware that there was a specific setting in the latest versions.

<img width="726" alt="Schermata 2021-11-01 alle 09 20 56" src="https://user-images.githubusercontent.com/14921654/139643089-b8719d5f-14b7-43cc-af95-e19e2a199d9c.png">

**Comment by liftbag** [comment]
I noticed another problem on Macos Monterey.
Starting from the Nightly 416 the tooltips that explain the operation of the White Dots and the padlocks work properly, even all those in the preferences window work. Almost all the tooltips of the configuration parameters instead have disappeared, except for some sporadic case.
They work properly from 415 and previous versions.
If it were a real problem, I will open a new issue if necessary.

**Comment by supermerill** [comment]
> I noticed another problem on Macos Monterey. Starting from the Nightly 416 the tooltips that explain the operation of the White Dots and the padlocks work properly, even all those in the preferences window work. Almost all the tooltips of the configuration parameters instead have disappeared, except for some sporadic case. They work properly from 415 and previous versions. If it were a real problem, I will open a new issue if necessary.
> 
>  Registrazione.schermo.2021-11-01.alle.10.06.01.mp4

that's a try for mitigation of #1720 (tooltip hiding too soon)
It's the setting 'use custom tooltip' just below 'display setting'. **Should I uncheck it by default?** (it's currently checked by default on macos but I'm undecided)
The os tooltip is available on the title and the 'custom' one is available when you let your cursor on a not-focus field (but the 'int' one, you need to hover one of the arrows)

**Comment by liftbag** [comment]
> that's a try for mitigation of #1720 (tooltip hiding too soon) It's the setting 'use custom tooltip' just below 'display setting'. **Should I uncheck it by default?** (it's currently checked by default on macos but I'm undecided) The os tooltip is available on the title and the 'custom' one is available when you let your cursor on a not-focus field (but the 'int' one, you need to hover one of the arrows)
> 
> mmmm. after looking your video, it seems that it's completely broken on macos...

Yes, seems that the "Use custom tooltips" feature is broken on macos starting from version 416. Deactivating it I don't see any problems.

**Comment by liftbag** [comment]
I tried the nightly 422 and the custom tooltips don't seem to be improved on macos.

**Comment by supermerill** [comment]
erf.
I revert the change where they won't open on focus. Seems like this isn't the culprit...
I think I'll really have to find a way to install/find a macos to be able to test things.

**Comment by liftbag** [comment]
> erf. I revert the change where they won't open on focus. Seems like this isn't the culprit... I think I'll really have to find a way to install/find a macos to be able to test things.
Hackintosh could be fine?

**Comment by supermerill** [comment]
> Hackintosh could be fine?

If I have to buy hardware, I'll go directly to a mac mini, to be able to compile&run on an m1. I'll have to do it, sooner or later.

I think I saw a way to have a one-button macos-in-a-vm on linux.
but I don't think it can be launch from a linux VM, have to double-boot.
