### ISSUE TITLE
Missing infill in first layer

### ISSUE THREAD

**Issue by animoose** [supermerill/SuperSlicer#1758]
### Version
2.3.56.8

### Operating system type + version
Windows 10 64 bit.

### Behavior
* _Describe the problem_
When slicing a large and complex gear, the infill for some of the teeth is missing in the first layer. In the attached model, sliced with the 0.20mm speed setting for Prusa Mk3S, you can see that some of the interior teeth have a perimeter but no infill.

* _Steps needed to reproduce the problem_
Load the model (Ring 140). Select 0,20mm speed. Slice. Look at the first layer (only).
* _Expected Results_
All teeth should have infill.

* _Actual Results_
See screenshot.

_Is this a new feature request?_
No.

#### Project File (.3MF) where problem occurs
_*Upload a Pr
[Ring 140.zip](https://github.com/supermerill/SuperSlicer/files/7450663/Ring.140.zip)
oject File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here
![capture_001_31102021_205625](https://user-images.githubusercontent.com/35618085/139619823-7d855686-0455-4545-b920-8d08f243906c.jpg)
_

**Comment by supermerill** [comment]
Was a mitigation for #651
isn't needed anymore.
