### ISSUE TITLE
Feature Request: Exclude area when printing

### ISSUE THREAD

**Issue by LaserBee** [supermerill/SuperSlicer#176]
Here's the idea: If I have a large-ish model, sometimes I only want to print a small section of it, to test some feature (clearance on a moving part, space to insert a nut, &c). Normally what I'd do is either keep flipping it and plane cutting it until it's the size I want, or take it into Meshmixer to cut it in pieces. What would be useful is if we could exclude an area, maybe using the "add shape". We could add a shape, say a rectangle, and position it on top of the area we don't want printed. Use it like the "HOLE" shapes on Tinkercad. 

Just an idea! :)

**Comment by supermerill** [comment]
if you want to exclude an area, add a modifier mesh and set the nb of perimeters, %infill, top layers, bottom layers to 0 for it.

It's 5 settings instead of one, but it's already possible that way.

**Comment by supermerill** [comment]
there's a way now as long as it's not a hole
see #1000
