### ISSUE TITLE
Add Anycubic Vyper

### ISSUE THREAD

**Issue by cryd-s** [supermerill/SuperSlicer#1764]
Hi,

can someone add the Anycubic Vyper as printer?

**Comment by supermerill** [comment]
push request has be done on https://github.com/slic3r/slic3r-profiles

**Comment by Crykor90** [comment]
> Push-Anfrage wurde auf [https://github.com/slic3r/slic3r-profiles gestellt](https://github.com/slic3r/slic3r-profiles)

i cannot find there any push about the anycubic vyper

**Comment by GemsKingz** [comment]
hey, is still not available ....

**Comment by adrianxplay** [comment]
Hi, I would like to help with this. How can I do it?
