### ISSUE TITLE
'No solid over X peri' triggering in the firs layers - [fixed] Walls on overhangs not connecting 

### ISSUE THREAD

**Issue by ristein** [supermerill/SuperSlicer#1766]
**Describe the bug**
If I have an overhanging stairstep (horizontal) that is at least as far as my perimeter count x line width or little bigger, there will be a gap between overhanging wall and wall underneath.
Also there won't be bottom layers (solid infill) but infill instead.

**To Reproduce**
1. Open my project
2. Look at layers 9 - 11

**>> Project File <<**
[BugOverhang.zip](https://github.com/supermerill/SuperSlicer/files/7454492/BugOverhang.zip)

**Expected behavior**
Overhanging wall and wall underneath should be connected with solid infill

**Screenshots**
I have three same parts with 2mm horizontal overhang. Perimeter count set to 3, 4 and 5.
With 3 perimeters it works as expected (left).
With 4 perimeters walls are not connected: there should be solid infill as wide as wall thickness and as high as bottom solid layers as when overhang retraces back (at layer 21), but here is also a gap that does not get filled. Also in layer 9 the infill doesn't even touch the wall.
With 5 perimeters the walls touch each other a tiny little bit and infill touches the wall but should be solid as well. In layer 10 the infill is suddenly solid but not so in layer 11.
layer 9: 
<img width="1505" alt="9" src="https://user-images.githubusercontent.com/55446611/139701906-4fc12b0b-3db4-4d00-a5f2-c260a6b24be9.png">
layer 10:
<img width="1527" alt="10" src="https://user-images.githubusercontent.com/55446611/139702197-97474d7e-8300-4eab-98c7-f82b630fabdd.png">
layer 11:
<img width="1511" alt="11" src="https://user-images.githubusercontent.com/55446611/139702244-d1b3199f-9241-4388-9842-64fa6fa013bf.png">
layer 21:
<img width="1501" alt="21" src="https://user-images.githubusercontent.com/55446611/139703319-8e4cdf8e-1ad2-418c-8324-4f39c7ab0cd5.png">
part measures:
![image](https://user-images.githubusercontent.com/55446611/139703426-4a84c815-190b-456c-964b-950f8fab88c5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.5735

edit:
another file looking weak too:
![image](https://user-images.githubusercontent.com/55446611/139714251-7da7af91-0787-4554-980d-71014ba445a3.png)

**Comment by ristein** [comment]
thank you for this fast response and hopefully fixing it @supermerill .
![image](https://user-images.githubusercontent.com/55446611/139817370-887b9bb1-46a4-43db-9be8-032519cb0073.png)
Will this bug also be fixed or is this a different problem?
Here the bottom solid layers are set to 10, but layer 3 to 5 already get not solid infill.
[DeckelmSpart.zip](https://github.com/supermerill/SuperSlicer/files/7459279/DeckelmSpart.zip)

**Comment by supermerill** [comment]
That's a different problem with "no solid over X perimeters"
As the first layer has bigger perimeters, it considers these area as over perimeters and so prune the infill after 2 layers.
I think i'll have to not consider the X first layers, this will be safer.

**Comment by ristein** [comment]
updated to new version, thank you.
another sample, of strange behavior (yes, I forgot the support, but that's not the point):
[Deckel.zip](https://github.com/supermerill/SuperSlicer/files/7498555/Deckel.zip)
strange cut in infill (might have to do with the parts border is in the first layer):
![image](https://user-images.githubusercontent.com/55446611/140781849-f24a8f94-7cb8-4c32-9cb5-b738bcaf5d6d.png)
bridging partly over solid infill, is this intentional?:
![image](https://user-images.githubusercontent.com/55446611/140781894-28afa506-9145-4b16-b6c0-4cfa81404add.png)
should there be a second bridging layer? Would be nice if there wouldn't be that cut:
![image](https://user-images.githubusercontent.com/55446611/140781973-cdbb52be-d71f-4c44-a934-1ac7a32ad041.png)

**Comment by supermerill** [comment]
isn't it the over-bridge flow?
Currently, it has to split the surface to apply the modified flow. May change that in the future.

**Comment by ristein** [comment]
I didn't change flow nor speed if that's the question

**Comment by supermerill** [comment]
[1766_Deckel_100_above_bridge.zip](https://github.com/supermerill/SuperSlicer/files/7499500/1766_Deckel_100_above_bridge.zip)

**Comment by ristein** [comment]
yes, sorry. Flow above bridges was 120% in my "creality" preset. 
But the first two screenshots won't get solved by this. Any comment on those?
