### ISSUE TITLE
Crash or error on infill generation

### ISSUE THREAD

**Issue by TheBoojah** [supermerill/SuperSlicer#1781]
I get an instant crash or some error message that varies, just after perimeter calculation is done and infill begins.

No problem on 2.3.57.3

[Error on infill.zip](https://github.com/supermerill/SuperSlicer/files/7467839/Error.on.infill.zip)

Version:   2.3.57.4
Build:     SuperSlicer_2.3.57.4_2021-11-02

Operating System:    Windows
System Architecture: 64 bit
Windows Version:     Windows 10 (build 19043), 64-bit edition
Total RAM size [MB]: 34,272MB

**Comment by supermerill** [comment]
Magnificent
![image](https://user-images.githubusercontent.com/6536403/140086633-de7b3669-ddf2-462a-bb9d-17cb6eaa0d32.png)

**Comment by neophyl** [comment]
Wow that looks like its exploding.
