### ISSUE TITLE
Add other options to the quick settings section

### ISSUE THREAD

**Issue by Goodfeat** [supermerill/SuperSlicer#1785]
**Is your feature request related to a problem? Please describe.**
In the slicer, you can have a very small list of quick settings, it would be nice if this list could be greatly expanded

**Describe the solution you'd like**
Is it possible to add additional parameters to quick settings?

**Describe how it would work**
Just click on the add a setting button, select the one you want from the list, and the setting appears in the quick settings menu.
![image](https://user-images.githubusercontent.com/44455128/140244246-0f16e130-dfb6-433f-b499-dfc3c465bd12.png)

**Describe alternatives you've considered**
an alternative addition can be implemented in the settings menu, for example, click on the icon next to the desired setting, and this setting will appear in the quick settings menu
![image](https://user-images.githubusercontent.com/44455128/140244627-cb3b9dce-5766-47f3-a4ee-05905aa63bba.png)

**Additional context**
Add any other context or paint drawing about the feature request here.

**Comment by supermerill** [comment]
It's very hardcoded, and the brim and support one are special, as it's not a real setting, but a placeholder that will then modify the setting.
These kind of "easy mode setting" are interesting, even more so for a "very easy mode". Maybe I should make more of them. But maybe not before a easy-expert tag rework.

If I modify the code to let the user modify this section, it will be via a ui file like for the rest of the setting ui.

**Comment by Goodfeat** [comment]
Yes, I understand you very well. I noticed that this section does not change in any way from version to version of the slicer, although there are other settings that I would like to change immediately.

  I will be grateful if you have time and you can finally modify the code to expand this section to add other settings.

**Comment by supermerill** [comment]
will update the readme in resources/ui_layout.
For now, check my awnser in 2897
