### ISSUE TITLE
Errant mouse

### ISSUE THREAD

**Issue by bigalgeorge** [supermerill/SuperSlicer#1788]
Open up SS (single instantiation)

About 50% time on my Ubuntu/Budgie if I left-click and move mouse the platen does not rotate (desired method)

When this situation, I found if I go to Config/Preferences, and dont do anything, exit, then the mouse will behave as expected (rotational)

This can happen at any time and without loading a Project.
**>> Project File <<**

If required, I can make a short video when problem happens again
![2021-11-04_20-47](https://user-images.githubusercontent.com/6935387/140276165-037cdd09-e896-4f66-9110-7087f1743d04.png)
?

**Comment by supermerill** [comment]
plater rotation should happen even if you press the left button over anything else, as the plater should take the focus every time the mouse hovers it. (and I found that a bit irritating when I try to modify something on the right panel)

Maybe on ubuntu it's different, will test.

**Comment by bigalgeorge** [comment]
When I got time will do a short vid.
I think its likely uncommon, and possibly is not worth considering unless others are reporting similar issues.
