### ISSUE TITLE
[FR] Brim speed

### ISSUE THREAD

**Issue by RURon** [supermerill/SuperSlicer#1789]
Having a CoreXY now that is able to print much faster than my printer before, I often struggle to have enough time to eventually adjust the z-offset before the part starts. Of course I could add many more brims, but I think it would be more economical to have a separate brim speed. I do have a prime line in my start code, but that actually does that, prime the nozzle and given the fact that the slicer is much smarter at slicing a brim correctly (filament specific / variations in different profiles), I feel that the brim is a good way to perfectly adjust the z-offset (or rather check if it is good).

Thanks for reading!

**Comment by supermerill** [comment]
It's currently using the support speed.
But I understand the issue.
Should be easy to add
