### ISSUE TITLE
Color change added between layer 1 and 2 

### ISSUE THREAD

**Issue by CDFI-3d** [supermerill/SuperSlicer#1792]
**Describe the bug**
When i slice my model superslicer add a Color change command at the final of layer 1.

I have 1 extruder 1 material 

**To Reproduce**
1. Slice a model
2. edit the Gcode 
3. look the M600 at the final of layer 1

**>> Project File <<**

[Problem.zip](https://github.com/supermerill/SuperSlicer/files/7476447/Problem.zip)

**Expected behavior**
i hope dont need this M600 at the layer change

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.57.3

**Comment by supermerill** [comment]
I need your project file: `File -> save as` zip it and drop it here.

**Comment by CDFI-3d** [comment]
[Problem.zip](https://github.com/supermerill/SuperSlicer/files/7476538/Problem.zip)

**Comment by CDFI-3d** [comment]
sorry i forgot the project i do it

**Comment by Pavulon87** [comment]
![Schowek01](https://user-images.githubusercontent.com/23641103/140381391-632c97f0-eab0-4af6-921e-15b81f052015.jpg)

**Comment by CDFI-3d** [comment]
ohhh i'm a fucking newb ..... thx !!!!! dont se it ....

**Comment by supermerill** [comment]
in the vertical scrollbar, go to layer 2 and remove the colorchange you added by mistake by clicking on the (X)
