### ISSUE TITLE
'Avoid crossing perimeters' doesn't work with 'Minimum travel after retraction'

### ISSUE THREAD

**Issue by d-schmidt** [supermerill/SuperSlicer#1793]
**Describe the bug**
It seems it only works for retracted travel moves. I hoped it would simulate Curas "Combing"

**To Reproduce**
1. Have a small part. 10 mm 'Minimum travel after retraction' and 'Avoid crossing perimeters'

**Screenshots**
Minimum travel after retraction: 3 mm  
It avoids crossing perimeters and moves a nice curve on the inside:
![grafik](https://user-images.githubusercontent.com/3226483/140393124-e36bbe63-e6a3-46a0-b5af-086a4b90efc4.png)
Minimum travel after retraction: 10 mm  
oozes along the pink arrow while moving directly from red to red:
![grafik](https://user-images.githubusercontent.com/3226483/140393474-cc4fea77-775f-4f3f-bade-8cf457317a7c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version c50452a

**Comment by supermerill** [comment]
Yes, currently it's only doing it if it's long enough to warrant it. When the travel is very short, like between two adjacent perimeters, there isn't much need to spend CPU time to see if it needs to do something smart.

I can add a hardcoded threshold...

**Comment by d-schmidt** [comment]
The first screenshot shows it is long enough to warrant it. The only difference between screenshot one and two is the 'Minimum travel after retraction' distance.

**Comment by d-schmidt** [comment]
can corfirm both options do now work together in fixed in 2.3.57.5
