### ISSUE TITLE
Config Wizard - Custom Printer

### ISSUE THREAD

**Issue by bigalgeorge** [supermerill/SuperSlicer#1801]
My 2nd printer is Voxelab Aquila X2 of which there is no such in printers.
Using the Config Wizard has some non-expected logic:

Config Wizard/Custom/Bowden .4/Next...............screen full of Creality printers
Expected input details for custom printer.
If [Next] is pressed till Custom Printer then its correct; it should automatically skip to this item.

**Comment by supermerill** [comment]
I don't understand exactly.
If I want to create a custom printer from the wizzard, I start here:
![image](https://user-images.githubusercontent.com/6536403/140587486-ae3bd822-0af1-4b7d-8e10-d793c3041d5a.png)

then, clicking next: I go to firmware, bed, temp
and then it goes back to the standards tab: [filaments if any vendor selected], updates, reload from disk, files associations, view mode.

i didn't see any creality printer.

**Comment by bigalgeorge** [comment]
It was my confusion, but could effect others I thought selecting 'Custom' would define the feed for the new printer.
Not so, its a separate setting, as Feeder. Perhaps changing the name from 'Custom' to 'Custom Feed' would help other Newbies?

**Comment by supermerill** [comment]
What's a 'Feed' ?

**Comment by bigalgeorge** [comment]
EG Bowden tube
