### ISSUE TITLE
retracts do not work in the modifier

### ISSUE THREAD

**Issue by Goodfeat** [supermerill/SuperSlicer#1802]
**Describe the bug**
Hello, I tried to adjust the retracts using the layer modifier, but the retracts do not work at all

**To Reproduce**
1 create a range of layers
2 add a retract modifier to each range
3 send to print to calibrate retracts
4 the model is printed, but the retracts do not work

**>> Project File <<**
[retract_calibration_towers_6112021_1853_SSli3r2.3.57.zip](https://github.com/supermerill/SuperSlicer/files/7490149/retract_calibration_towers_6112021_1853_SSli3r2.3.57.zip)

**Expected behavior**
I want to get a different retract at each interval of the part

**Screenshots**
![image](https://user-images.githubusercontent.com/44455128/140604402-1f9f0b2c-5ad8-4ec5-8b79-6f8650e4da07.png)

![image](https://user-images.githubusercontent.com/44455128/140604378-f837bae4-9bf7-4e6b-8983-5c444a191d22.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [e.g. 2.3.57.3], Use `Help->About`_

**Additional context**

**Comment by neophyl** [comment]
Your zip just contains gcode.  Merill will need your saved **Project**.  File>Save project as.  This will save a 3mf with all your settings, the modifiers and model etc.

**Comment by Goodfeat** [comment]
[retract_calibration_towers3fm.zip](https://github.com/supermerill/SuperSlicer/files/7490272/retract_calibration_towers3fm.zip)

**Comment by neophyl** [comment]
The values you have set in your modifiers should not be negative values.  If you want a retaction of 5mm then you need to set 5, not -5.  Remove the negatives and it works.

**Comment by Goodfeat** [comment]
Sorry, I was sure that it was necessary to put a negative value, since the value was specified in the example -1

**Comment by neophyl** [comment]
That's not an example.  -1 is the default value.  If you hover over until you get the tooltip then it actually says set negative to disable.  So the default is disabled.

**Comment by Goodfeat** [comment]
Thank you very much, I did not study the modifier well, I will try to be more attentive
