### ISSUE TITLE
"Only one perimeter" setting causes overlapping infill w/ perimeters when there is no room for top infill

### ISSUE THREAD

**Issue by scottmudge** [supermerill/SuperSlicer#1804]
**Describe the bug**
On smaller objects, the "Only one perimeter" setting causes overlapping infill with perimeters.

![image](https://user-images.githubusercontent.com/19617165/140609244-48496ea9-c400-4f4a-b566-92ed4f43f7a9.png)

**To Reproduce**
Use default settings (0.20 Fast), slice attached model.

**>> Project File <<**

[example_issue.zip](https://github.com/supermerill/SuperSlicer/files/7490422/example_issue.zip)

**Expected behavior**
I would expect that in cases where there is no room for top-layer infill (completely filled by perimeters), the infill would be disabled. 

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Latest nightly (2.3.57.4)

**Additional context**
Disabling "Only one perimeter" corrects the issue.

See screenshot:

![image](https://user-images.githubusercontent.com/19617165/140609377-58f0f198-c922-42b1-b003-19bfa8baebba.png)

**Comment by supermerill** [comment]
haha, yes. I also found it and fix it an hour after the nightly

**Comment by neophyl** [comment]
Looks ok in the previous one 2.3.57.3 so must be a change in the nightly.

**Comment by scottmudge** [comment]
Great, I'll close this issue. If I see it again I'll make a note here. Thanks!
