### ISSUE TITLE
One part affecting top layer of another

### ISSUE THREAD

**Issue by Pavulon87** [supermerill/SuperSlicer#1813]
**Describe the bug**
Why is one part changing top layer of another when it shouldn't? Interface shells turned on. Prusa slicer leaves top layer clean. Susi leaves a trace of the top object. Is there any option to avoid this?

**To Reproduce**
1. Import/create multipart object
2. Place one part just above the other
3. Turn interface shells on
4. Slice
5. See error

**>> Project File <<**
[toplayer.zip](https://github.com/supermerill/SuperSlicer/files/7491143/toplayer.zip)

**Expected behavior**
Leave the top layer unchanged

**Screenshots**
Susi top:
![Schowek08](https://user-images.githubusercontent.com/23641103/140622297-a9319c1c-5714-4724-afe0-423586f17322.jpg)

Prusa top:
![Schowek07](https://user-images.githubusercontent.com/23641103/140622308-8abf3853-6579-4d0a-88b3-f7a9bf12ca85.jpg)

Susi top-1:
![Schowek09](https://user-images.githubusercontent.com/23641103/140622331-5b5265d9-c5b5-4715-b462-e2000d5e7405.jpg)

Susi's weird artifacts:
![Schowek10](https://user-images.githubusercontent.com/23641103/140622429-1eff6d18-d6ec-4488-9ac9-db693d309d18.jpg)

Prusa:
![Schowek11](https://user-images.githubusercontent.com/23641103/140622433-7fb898a4-ddc0-4718-bc21-6cfdbc5256f7.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.57.3

**Comment by supermerill** [comment]
For the first object, it's because you ask for 3 periemters and only 1 visible on top surfaces. That's what it does.
I don't see any problem here.
![image](https://user-images.githubusercontent.com/6536403/140628385-58cc4e3d-f443-4991-bc41-924e4e4e6534.png)

For the second object, i can't test. Maybe the same thing.

**Comment by Pavulon87** [comment]
So what is the purpose of this? Why can't the top layer of square remain unchanged? Better adhesion?
I can change this by inserting the top object as a separate body. But there is a problem to put the second object at the correct height, because the z position is automatically reset if there is only one part.

**Comment by supermerill** [comment]
you asked for 3 perimeters, why remove all of these because some of the layers has a top surface?
you can use a range modifier to modify the perimeter count to 1 if this is what you want.

example where it's (more?) needed
![image](https://user-images.githubusercontent.com/6536403/140642342-342a4f65-7efd-4a3e-80c5-f2f1e23bb7e0.png)

**Comment by Pavulon87** [comment]
Maybe I didn't make myself clear. I asked why the top of the square had a circle on it, while the Prusa slicer leaves a smooth surface. It's not about the number of perimeters on the top layer. I don't see why it should work that way because it causes imperfections. 
But never mind, I found a workaround.
![Schowek01](https://user-images.githubusercontent.com/23641103/140660916-cb131123-7009-4615-968a-0665e2e39ff2.jpg)

[toplayer.zip](https://github.com/supermerill/SuperSlicer/files/7493047/toplayer.zip)
I think the issue can be closed.

**Comment by supermerill** [comment]
> Maybe I didn't make myself clear. I asked why the top of the square had a circle on it, while the Prusa slicer leaves a smooth surface. It's not about the number of perimeters on the top layer. I don't see why it should work that way because it causes imperfections.

oh, it's because on prusaslcier, there is a hardcoded 3mm "anchor". In susi, it's available in "external_infill_margin" and default to 150% (so ~0.6mm).
