### ISSUE TITLE
Error when running calibration tests on NAS storage

### ISSUE THREAD

**Issue by Goodfeat** [supermerill/SuperSlicer#1815]
**Describe the bug**
Hello,
Found a bug when using the program via NAS storage

**To Reproduce**
1 The program to the NAS storage
2 Run the slicer program
3 Go to the calibration section
4 Trying to call any type of calibration (for example a calibration cube)
5 I get the error
 
```
  SuperSlicer Error
    Unable to open requested HTML document: \\Nas\Р°СЂСРёРІ_РїСЂРѕРіСЂР°РјРј\SuperSlicer_2.3.57.4_S\resources/calibration/cube/cube.html
```

**Expected behavior**
Waiting for the calibration settings page to launch

**Screenshots**
![image](https://user-images.githubusercontent.com/44455128/140633028-beff5f60-16ac-4a22-ba47-3b0806e9a6fa.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [e.g. 2.3.57.4], Use `Help->About`_

**Additional context**
the slicer is probably not designed for work via NAS storage, but all the main functions of the program work well.

Most likely, the program cannot find the path correctly, although everything works without problems on a computer and USB media

**Comment by supermerill** [comment]
Can you test this version, (it contains some changes)?
https://mega.nz/file/hoJAQBhS#JiPJNAOQ4j-TKUIkZ85j6mIrX5tbxoXCbRYGjHvUNCY

**Comment by Goodfeat** [comment]
![image](https://user-images.githubusercontent.com/44455128/140643035-c7319f1a-5354-43aa-b326-1010be6c1490.png)
No, this also does not work unfortunately

**Comment by supermerill** [comment]
mmm... maybe an Unicode issue.

**Comment by Goodfeat** [comment]
it seems the program does not work with Cyrillic

![image](https://user-images.githubusercontent.com/44455128/140643773-6b84d5d2-b866-4b5b-bcf7-cfabdfa4b2d6.png)

**Comment by supermerill** [comment]
I tried to reproduce but I can't. maybe because I set my windows to work with uft8...

**Comment by Goodfeat** [comment]
It seems I have windows encoding in cp-1251

![IMG-20211107-WA0012](https://user-images.githubusercontent.com/44455128/140644395-64ff4a05-c9c0-4e30-b4a4-78d275b5f598.jpg)

**Comment by Goodfeat** [comment]
I tried to install in windows using unicode.  On windows, this mode is in beta status.  Most likely bugs will appear in other programs

![IMG_20211107_223345](https://user-images.githubusercontent.com/44455128/140645099-69094baf-01d2-44e0-9bb1-b1e1d98ab5ea.jpg)

**Comment by Goodfeat** [comment]
![IMG-20211107-WA0013](https://user-images.githubusercontent.com/44455128/140645211-4dd4e94a-f933-4b0b-a5e2-b51a3b79474d.jpg)

**Comment by supermerill** [comment]
Can you test this one? only the calibration cube.
if the error message is different, show me the new one.

**Comment by Goodfeat** [comment]
i just checked out a new build
now everything works correctly,

bug has been fixed

![image](https://user-images.githubusercontent.com/44455128/140663897-a41438eb-66f9-4fc9-8d2e-40746cff1c65.png)
