### ISSUE TITLE
Top 3 lines of lcd are blanked with 2.3.57.4

### ISSUE THREAD

**Issue by neophyl** [supermerill/SuperSlicer#1819]
Sliced some gcode with the new 2.3.57.4 release and when printing using it on my Prusa MK3 the lcd details are now missing except for the bottom line.  So basically all the temperature, speeds etc that are normally displayed are blanked out.  
I haven't changed anything in my printer profile, its still set to use the M117 for print time remaining etc.

The printers lcd works normally in that if I go into the menu to change something it displays everything as expected but once I go back to the main screen the only line being shown is the very bottom line with the scrolling name of the print job.  

Slicing the same project from 2.3.57.3 or 2.3.26.9 and printing results in lcd normal operation.
I've compared the gcode produced and the only thing I can see different (besides some of the move/extrude values) are the M73 lines.  The latest one is missing the Q values and repeating the first line.

; generated by SuperSlicer 2.3.57 on 2021-11-07 at 14:07:33 UTC
; 
; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
; first layer extrusion width = 0.42mm

M73 P0 R20
M73 P0 R20  **<--- repeated line**

; generated by SuperSlicer 2.3.56 on 2021-11-07 at 14:32:16 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
; first layer extrusion width = 0.42mm

M73 P0 R21
M73 Q0 S21

Why this should result in a cleared lcd though I have no idea.

**>> Project File <<**
[SS23569_CalibrationCube_v2.zip](https://github.com/supermerill/SuperSlicer/files/7492470/SS23569_CalibrationCube_v2.zip)

**Expected behavior**
Not to clear the lcd screen of all the other information

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - Version 2.3.57.4

**Comment by supermerill** [comment]
That's the silent mode. I didn't see it need different parameters.
Should be an easy fix.
