### ISSUE TITLE
Slicing not progressing past "Generating perimeters: layer"

### ISSUE THREAD

**Issue by Pockrandt** [supermerill/SuperSlicer#1824]
**Describe the bug**
When slicing the stl the slicer stops at "Generating perimeters: layer".
Everything is still usable until "cancel" button is pressed, it freezes.

![plate](https://user-images.githubusercontent.com/45492899/140663670-7d3c76dd-556e-4d37-a805-8e9ef6cafd71.png)

Problem is only with my profile because it contains  "Reverse on odd".
As soon as the option is deactivated everything works again.

![option](https://user-images.githubusercontent.com/45492899/140663511-2c05c1e4-6ca5-45e4-a83f-6506caad0c39.png)

This might be one of those edge cases since other files are fine.

**To Reproduce**
1. Open attached 3mf
2. Slice file
3. GUI still works
4. Press cancel
5. program freeze

Check
1. task kill slicer
2. open file again
3. disable "Reverse on odd"
4. slice successful 

**>> Project File <<**

[reverse_on_odd_issue.zip](https://github.com/supermerill/SuperSlicer/files/7493200/reverse_on_odd_issue.zip)

**Expected behavior**
Slice successful with the option.

**Desktop (please complete the following information):**
 - OS: Linux  5.10.70-1-MANJARO x86_64 GNU/Linux
 - Version: 2.3.57.4

**Comment by supermerill** [comment]
The problem was on the bridge detector, iterating on too many angles.
I've fixed the bug and used the opportunity to improve the pruning algo.
