### ISSUE TITLE
Latest pre-release does not start, stable does start.

### ISSUE THREAD

**Issue by kursatu** [supermerill/SuperSlicer#1832]
**Describe the bug**
I've upgraded to windows 11 recently. 
I';ve got this and it does not work. 
https://github.com/supermerill/SuperSlicer/releases/tag/2.3.57.4
This however works.
https://github.com/supermerill/SuperSlicer/releases/tag/2.3.56.9
I've also had my build and I've recently pulled the sources and then built..
It also stopped working.

**To Reproduce**

**>> Project File <<**
*Please* upload a ZIP archive containing the project file used when the problem arise. Please export it just before the problem occur. Even if did nothing and there is no object, export it as it contains your current configuration.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]
 - Version [e.g. 2.3.55.5], Use `Help->About`_

**Additional context**

**Comment by supermerill** [comment]
Just launching the slicer with the exe?
if you launch it with an empty configuration directory (with --datadir setting or with an empty "configuration" directory next to the exe), does it launch or crash instantly?
if you launch the '_console' one from a command prompt, does it output an error message?

**Comment by kursatu** [comment]
- Just launching the superslicer.exe.
- With -datadir to an empty directory next to the exe,  it works
- superslicer_console.exe starts and exits after splash screen and it prints the following
create_preset_tabs: 3
update_layout1: 3
I can attach my current datadir if it helps.

**Comment by supermerill** [comment]
> I can attach my current datadir if it helps.

yes, please

**Comment by supermerill** [comment]
also, if you can't upload your configuration folder, can you test the latest nightly?

**Comment by kursatu** [comment]
[SuperSlicer.zip](https://github.com/supermerill/SuperSlicer/files/7501604/SuperSlicer.zip)

**Comment by kursatu** [comment]
My latest build, with the latest sources pulled, still does not work.
If I pass the -datadir to an emoty directory next to the .exe it starts up.

**Comment by kursatu** [comment]
I've made a build by pulling the latest sources and it works again.
Thank you.
