### ISSUE TITLE
wxWidgets Debug Alert when closing

### ISSUE THREAD

**Issue by ristein** [supermerill/SuperSlicer#1837]
**Describe the bug**
Had two windows open with same print settings active, saved them in window two, pressed close on window 1, then this:
![image](https://user-images.githubusercontent.com/55446611/140890216-1f8cfbb9-4225-48ae-94ae-076a7552267d.png)
![image](https://user-images.githubusercontent.com/55446611/140890598-e4b84305-46cf-482a-8078-46732f531e95.png)
when clicking continue:
![image](https://user-images.githubusercontent.com/55446611/140891025-05eeed4b-d33a-469d-a305-83fe3309287f.png)
![image](https://user-images.githubusercontent.com/55446611/140891047-b0ddfc3c-778e-438b-a83b-440a6f8328ed.png)
![image](https://user-images.githubusercontent.com/55446611/140891060-96a0059c-eaab-4e76-8d65-977335c79f36.png)

**To Reproduce**
as above

**>> Project File <<**
[Deckel.zip](https://github.com/supermerill/SuperSlicer/files/7503183/Deckel.zip)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.57.4

**Comment by supermerill** [comment]
I can't reproduce.
I think the problem may be in the "unsaved changes dialogs".
what are the fields you changed? and with what value?

**Comment by ristein** [comment]
sorry, reproduced it now as follows:
It doesn't have to do with two windows but with importing a project:
1. open SuperSlicer
2. import project
[1766_Deckel_100_above_bridge.zip](https://github.com/supermerill/SuperSlicer/files/7504245/1766_Deckel_100_above_bridge.zip)
 3. change anything i.e. perimeters
 4. close

**Comment by supermerill** [comment]
can't reproduce either.
can you zip and post here your configuration directory?
it can be found via help -> show conf folder
If you have physical printer with ip & password you don't want to share, you can export the config bundle instead, maybe it's enough (but maybe not).

**Comment by ristein** [comment]
[SuperSlicer.zip](https://github.com/supermerill/SuperSlicer/files/7504420/SuperSlicer.zip)

I use microSDcard 🙈

**Comment by supermerill** [comment]
Strange bug. I can only reproduce it with builds from github, not with builds from my computer.

**Comment by ristein** [comment]
did u try zipping/unzipping?

**Comment by supermerill** [comment]
seems like the mitigation works. can you try the latest nightly?

**Comment by ristein** [comment]
seems to be working on v..57.7
