### ISSUE TITLE
Fan Speed management

### ISSUE THREAD

**Issue by 5axes** [supermerill/SuperSlicer#1847]
**Describe the bug**
I'm not sure if it's a bug, or something I don't understand. When I try to decrease the value of the Fan Speed (it's labeled Default speed but in fact it's a **min_fan_speed**   the fan speed used in some area of the part doesn't respect this value. 

![image](https://user-images.githubusercontent.com/11015345/141162349-f0fc5c09-d1c7-4565-bfe3-03759acb2b83.png)

**Expected behavior**
The fan speed should be for the wall part at the Default Fann Speed except for the first layer where we can have a lover speed

**Screenshots**
![image](https://user-images.githubusercontent.com/11015345/141161215-5838f76a-6250-43a8-b917-1ce4f51a80c0.png)

**Desktop :**
 - OS: , Windows
 - Version 2.3.57.5

**Additional context**
The fan speed calculation is different if we use as Filament settings based on  the ABS or PETG configuration.

**>> Project File <<**
Joined  project file

[Multi_Bridge.zip](https://github.com/supermerill/SuperSlicer/files/7514713/Multi_Bridge.zip)

**Comment by 5axes** [comment]
Ok I think I just understood the problem. The misunderstanding comes more from the logic of the parameters layout. I think it would be better to keep the order and the labels like in Prusa with Mini and Max speed.

**SuperSlicer**
![image](https://user-images.githubusercontent.com/11015345/141164223-b8993713-89c6-43f3-a15e-4c5b66f57101.png)

**PrusaSlicer**
![image](https://user-images.githubusercontent.com/11015345/141164355-6a8ff99d-33e7-47e2-894d-1130a95def86.png)

**Comment by supermerill** [comment]
That 'maximum' is only useful for the "short layer time", and it isn't a maximum as it can be superseeded by the bridge, top and perimeter fan speed.
I moved it here because it was confusing for me to have a max value lost in the top panel that wasn't a max.
The important part is the explanation text below.

**Comment by 5axes** [comment]
Ok this behaviour will really deserve an explanation in the documentation  :)
