### ISSUE TITLE
Latest Version has no Installer

### ISSUE THREAD

**Issue by inspectionsbybob** [supermerill/SuperSlicer#1861]
The current version (GitHub) has no Installer or instructions of what files to put where.

Win10

Went to install and it just has several folders with no "setup" exe or Install or any other method of installing.

**Comment by supermerill** [comment]
Just extract and double-ci on superslicer.exe
No installation needed.

**Comment by film49uk** [comment]
DOES NOT UPDATE TO The LATEST VERSION W10 64

**Comment by inspectionsbybob** [comment]
Out of date
