### ISSUE TITLE
"Empty layers detected. The object is not printable"

### ISSUE THREAD

**Issue by LaserBee** [supermerill/SuperSlicer#187]
### Version
_Latest version

I am trying to print face shields for the NHS. I would like to print the stacks. They are designed to separate after printing, so have an interface layer. I think the slicer doesn't like this, and so won't give anything like print time. Can this be fixed? 
I am attempting the stack of 3 Euro masks from here:

https://retrolabs.com/3d-prints/3d-printed-face-shield-with-10-mil-pvc

**Comment by guestisp** [comment]
Please add support for this, allowing to print object in the air, like cura or s3d

Many covid masks are stacked for night printing and they are impossible to print with PS without adding some artefacts manually

**Comment by guestisp** [comment]
Any chance to get this fixed? Printing almost any covid face shield is impossible with Slic3r due to empty layers

Another good feature would be to add something like very light supports on perimeters/infill like pillars,in this case the upper layer would be supported by pillars

In example, normally you would extrude the 100% of the layer, setting this a % of extrusion, in example 10% would only extrude the 10% leaving the 90% left. This will result in a "support layer" with pillars created automatically. A sort of "dashed extrusion"

**Comment by supermerill** [comment]
todo: add a setting to disable the check about empty layers in GCode::collect_layers_to_print.

**Comment by guestisp** [comment]
Would be great. Slic3r is the only slicer unable to print stacks with gaps

**Comment by guestisp** [comment]
But please also evaluate a feature for discardable layers, layers with a huge underextrusion (or a partial extrusion like pillars) used to keep the objects together during print. When done, these layers would be the weakest points so you could splits parts by breaking these layers

Like this part, but in Z. It's only used to keep the part in place
![01_sprue~2](https://user-images.githubusercontent.com/3944655/79499120-bdd42480-802a-11ea-8c52-ae29205096b9.jpg)

**Comment by supermerill** [comment]
If you want to alter the model, the best way is to do it yourself. If you did it that way, there are a reason.

**Comment by guestisp** [comment]
I dont want to alter the model, just add a sort of "supports" . It's MUCH easier for a slicer to underextrude a path than designing the same manually point by point

As workaround i've manually set a gcode to change the flow at the start of the layer and to restore the flow to 100% After 2 layers. Is working fine, but on a vase with hundreds of thousands of layers is not easy to do manually....

**Comment by guestisp** [comment]
The question Is: how to print two stacked objects, without supports, and without printing in the air like other slicers? Printing in the air Is unpredictable and make the contact layer ugly.

Currently im printing the stack with no gaps in Z but underextruding (flow 10-15%) the contact layer. After the print, the parts will split easily

**Comment by guestisp** [comment]
The first layer over the "hole" should be handled as bridge, i think. (maybe an option for this)
