### ISSUE TITLE
Variable for config dir (Bed Texture)

### ISSUE THREAD

**Issue by tome9111991** [supermerill/SuperSlicer#1875]
Hi
I have a Linux and Windows maschine
I load config dir from my Seafile cloud.

But have issue with Bed Texture.
Have set on my Windows Pc path C:/....
Linux can't find the Path..

Here a Screen from my Linux Ubuntu Mate:
![Bildschirmfoto zu 2021-11-13 22-15-38](https://user-images.githubusercontent.com/57866234/141675365-3c4ea707-20b8-40a7-b676-20c6a196c1f0.png)

My idea
Copy the Bed texture in config dir on my Seafile cloud.

With Variable you can open the Config dir and choose the texture.

This cloud be fix my problem.

**Comment by tome9111991** [comment]
Could be usefull for post-process script

**Comment by tome9111991** [comment]
i have seen this.
https://github.com/supermerill/SuperSlicer/issues/2925

maybe possible to use with bed texture?

**Comment by supermerill** [comment]
A bit more difficult, but okay.

**Comment by supermerill** [comment]
It will save only the relative path if the file is in the exe, configuration or user directory/subdirectory tree.

**Comment by tome9111991** [comment]
thanks works well.

i have copy bed texture in my config folder.
on linux i have set the path to bed texture.svg

windows will use path from config dir.
