### ISSUE TITLE
Bridge flow calibration don't work anymore

### ISSUE THREAD

**Issue by Mitchou** [supermerill/SuperSlicer#1877]
**Describe the bug**
Try to generate Bridge Flow calibration and SuperSlicer crash wit this message "Internal Error: You can't define an option that need nozzle_diameter without defining it". Work like a charm on 2.3.56.9

**To Reproduce**
1. Go to Calibration
2. Click on Bridge Flow Calibration
3. Click on Test Flow Ration

**Expected behavior**
Generate Bridge test

**Desktop (please complete the following information):**
 - OS: Linux Fedora 35
 - Version 2.3.57.5

**Comment by neophyl** [comment]
I'm using the same version on windows and I just tried that calibration option and its working fine for me.
