### ISSUE TITLE
Auto Speed weird behaving

### ISSUE THREAD

**Issue by ocgeek** [supermerill/SuperSlicer#1884]
### Version
SS 3.6.0.9

### Operating system type + version
Windows 10

### Behavior
* AutoSpeed generated feed rates do not match the settings
* One Step - Slice and inspect the resulting G-Code
* Different feed rates as per Auto Speed settings
* Feed rate appears incorrect

I'm using 0 infill speed so to use the Auto Speed setting
I have a Dragon so i set the Volumetric to 15 mm/s^3 (1.75 mm filament / 0.4 mm nozzle)

Case 1)
I set max print rate to 100 mm/s
In the generated g code the resulting feed for _Internal infill_ (mm/min) is ~2971 which is 45 mm/sec.... weird

![screenshot_109](https://user-images.githubusercontent.com/76037248/141752071-f1aa06cb-cf32-488b-b5af-f538c8e5dd4c.jpg)

Case 2) 
I set the max print rate to 300 mm/s (well above the max 15mm/s^3 can do)
in the generated g code the resulting feed appears higher than the one which you calculate given the line width, nozzle dia, ...

![image](https://user-images.githubusercontent.com/76037248/141753095-73ee8762-3cf9-4609-b7ce-7bc6f70860b9.png)

With those settings it shall be 104 but it generates 110
![image](https://user-images.githubusercontent.com/76037248/141753388-5da37d4e-3ff2-4ddb-994d-c1a35e916b40.png)

thanks

_Is this a new feature request?_
No

#### Project File (.3MF) where problem occurs

[Auto Speed Test.zip](https://github.com/supermerill/SuperSlicer/files/7537276/Auto.Speed.Test.zip)

**Comment by csch0** [comment]
I think the first one should be fixed in the latest release just give it a try (https://github.com/supermerill/SuperSlicer/releases/tag/2.3.57.5)

**Comment by ocgeek** [comment]
I confirm the first is fixed in 2.3.57.5

This is gcode out of setting max auto 100 mm/sec

![image](https://user-images.githubusercontent.com/76037248/141767851-7cf1e6eb-babb-42da-b963-38d039ec313a.png)

**Comment by supermerill** [comment]
Did you use spacing for your calculus?
To have the flow per mm, you can multiply the spacing by the height.
If you use the width, you have to remove the bit around the half-circles.
see https://manual.slic3r.org/advanced/flow-math
