### ISSUE TITLE
FR - Add Total Layers to the Gcode metadata

### ISSUE THREAD

**Issue by vajonam** [supermerill/SuperSlicer#1886]
Right now there is a mismatch when supports are used, there is no way for the klipper/moonraker to determine the correct number of layers when using variable layer height or supports which introduces variable layer height.  

**Describe the solution you'd like**
Can we add `total_layer_count` to the medata printed. I know I can add it custom G-code but this is for moonraker / klipper that allows it correctly reflect the total layers. .

**Describe how it would work**
Just an additional parameter at the end gcode along with all the other info. 

```
; total_layer_count = {total_layer_count} 
```

**Describe alternatives you've considered**
adding it to custom G-code.

**Comment by vajonam** [comment]
@supermerill Thanks for the quick response! Do I close this? or will you close it w/ next version?

**Comment by supermerill** [comment]
you can close when you verify that it works as expected.

**Comment by vajonam** [comment]
Confirmed this is work. Will close the issue. Thanks
