### ISSUE TITLE
Crashes with a specific file on slicing

### ISSUE THREAD

**Issue by vndk36** [supermerill/SuperSlicer#1889]
**Description of the bug**
SS crashes when slicing on this particular file. This model is a half of a boat torpedo. The other half works fine but this one crashes all the time.  Same error with the "side 1" mirrored to create a "side 2", it crashes. It works on normal PrusaSlicer

**To Reproduce**
1. Go to SS last version (2.3.57.5)  and (2.3.56.9)
2. Load the torpedo file that contain the slicer parameter as well
3. Try to slice and the program should crash

**>> Project File <<**
[Torpedo_side_2.zip](https://github.com/supermerill/SuperSlicer/files/7541761/Torpedo_side_2.zip)

**Expected behavior**
The slicing should work as it works for the mirror version of this file.

**Desktop (please complete the following information):**
 - OS: Windows 10 Education N
 - Version :21H1

**Comment by supermerill** [comment]
That's again that monotonic thing that crash.
I hope it's fixed in the 2.4.
