### ISSUE TITLE
Crash when generating infill

### ISSUE THREAD

**Issue by pushc6** [supermerill/SuperSlicer#1893]
**Describe the bug**
When slicing a particular plate SuperSlicer will crash when generating the infill

**To Reproduce**
Slice the attached 3mf

**>> Project File <<**
[crash_ss.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7546709/crash_ss.3mf.zip)

**Expected behavior**
For it not to make me sad by blowing up

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 2.3.57 but also happened in 2.3.56

**Additional context**

**Comment by supermerill** [comment]
That's a bug in the monotonous code from prusa.
I don't really know how it works.
Will see if I can create a dirty fixing patch.
ideally, I should create a unit test that show the problem and give that to prusa for debugging.

**Comment by pushc6** [comment]
Thanks for the quick response @supermerill, I was able to get around it by just spinning print 90 degrees. So for anyone else out there that may encounter this, it seems spinning seems to help.
