### ISSUE TITLE
Adding placeholder for current_pos_x &  current_pos_y for custom gcode

### ISSUE THREAD

**Issue by DzzD** [supermerill/SuperSlicer#1898]
It would be nice to have two new placeholders for custom g-code : current_pos_x & current_pos_y (specially for purge bucket script), see original discussion for more details.

_Originally posted by @DzzD in https://github.com/supermerill/SuperSlicer/discussions/1855_

**Comment by supermerill** [comment]
can I add current_pos as an array of two double?
so current_pos[0] for x and current_pos[1] for y

like for relative_correction, print_bed_size, ...

**Comment by DzzD** [comment]
Just to be sure, what is exactly current_pos, the last pos used or the next pos ?

I am wondering if next pos would not be a more interesting data, I mean after a custom gcode you probably want to go to the next pos rather than go back to the last one, no ?

**Comment by supermerill** [comment]
It's the position of the nozzle at the start of the custom gcode section.
