### ISSUE TITLE
Allow color change to set M code to be used. 

### ISSUE THREAD

**Issue by sonic2wb** [supermerill/SuperSlicer#1899]
### Version
_Version of SuperSlicer used goes here (help->about)_
2.3.57.5
### Operating system type + version
_What OS are you using, and state any version #s_
Windows 10 pro 64 bit
### Behavior
Stock Ender 3 does not use the M600 command. would be nice to be able to set M25  or M0 as the command to pause a print

_Is this a new feature request?_
Related guides for writing feature requests: http://meta.stackexchange.com/a/259196 http://nickohrn.com/2013/09/write-great-feature-request-bug-report/

#### Project File (.3MF) where problem occurs
_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here_

**Comment by supermerill** [comment]
printer -> customgcode -> colorprint

**Comment by sonic2wb** [comment]
Thank You!
