### ISSUE TITLE
Function external_perimeter_cut_corners

### ISSUE THREAD

**Issue by macchinette** [supermerill/SuperSlicer#1903]
**Describe the bug**
Maybe it's not a bug, but a function definition.

**To Reproduce**
1. Open 3mf attachment
2. Cut files
3. View the volumetric flow rate
4. See volumetric flow rate in the corners of the cube

**>> Project File <<**

[external_perimeter_cut_corners.zip](https://github.com/supermerill/SuperSlicer/files/7550035/external_perimeter_cut_corners.zip)

**Expected behavior**
I would like to understand how it has to work, because I thought it would reduce the flow before the corner to make the corners sharper and instead the flow remains unchanged.
I have seen that after the angle the flow is the same, but soon after it is increased for a small moment and then it returns to normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/79080486/142070784-cec7c979-982e-43e1-9d28-00b2435a515a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version SuperSlicer_2.3.57.5

**Additional context**
It could be a great feature.

**Comment by macchinette** [comment]
Okay so the function is very good!
It just doesn't apply right, because if I understand when it starts again from the corner it has to reduce the flow and if it does, it immediately increases the flow again and that's not good.
When you have time, can you check if it applies properly?
Thanks

**Comment by supermerill** [comment]
just checked, and there `was a problem.
current:
```
 write1 dist 0.141001, mult1=0.892699, length1 = 0.141
 write1 0.0386785
 write2 dist 0.141, mult2=0.94635, length2 = 0.282
 write2 0.0820068
 write3 dist 3.954, mult=1, length2 = 3.813
 write3 0.0417829
 ```

fixed:
```
 write1 dist 0.141001, mult1=0.892699, length1 = 0.141
 write1 0.0386785
 write2 dist 0.282, mult2=0.94635, length2 = 0.282
 write2 0.0410034
 write3 dist 3.813, mult=1, length2 = 3.813
 write3 0.043328
```
