### ISSUE TITLE
2.3.57.5 impossible floating bridge/overhang perimeter

### ISSUE THREAD

**Issue by d-schmidt** [supermerill/SuperSlicer#1911]
**Describe the bug**
There is a one layer bridge in this model. The slicer starts with the dark blue overhang perimeter in midair.
![grafik](https://user-images.githubusercontent.com/3226483/142283395-795bc78f-a4b6-4bc0-ac7c-2c2a98a492b5.png)
layer 95:
![grafik](https://user-images.githubusercontent.com/3226483/142283445-6ef76abc-900a-49c9-8000-31c887de0e6a.png)
layer 96:
![grafik](https://user-images.githubusercontent.com/3226483/142283469-f5d766d9-43cc-4dbc-95e7-a20327f75419.png)
layer 97:
![grafik](https://user-images.githubusercontent.com/3226483/142283486-ccf53353-8650-424c-902d-9b76cae97435.png)

**To Reproduce**
1. download Cam.stl https://www.thingiverse.com/thing:4945227/files
2. slice at 0.2 layer height

**>> Project File <<**
[btn_Cam.zip](https://github.com/supermerill/SuperSlicer/files/7558032/btn_Cam.zip)

**Expected behavior**
I expect one big bridge.

**Desktop (please complete the following information):**
 - win64

**Comment by supermerill** [comment]
remove one perimeter on top, at least on this layer.

duplicate of #1867

**Comment by d-schmidt** [comment]
weird interaction but okay. I guess it sees the middle circle as top?!
