### ISSUE TITLE
Error unicode at startup

### ISSUE THREAD

**Issue by psusong** [supermerill/SuperSlicer#1924]
Hello, I used the file made by Chinese fusion360. 
After 3mf was generated, the entity was Chinese. This error occurred after opening it.

<img width="406" alt="superslicer_NocDAdhhy3" src="https://user-images.githubusercontent.com/9137231/142616177-88ccb4e9-93dc-4cba-9558-1b29d3dd1096.png">
<img width="566" alt="superslicer_Wx3V9PxWqu" src="https://user-images.githubusercontent.com/9137231/142616296-d47b4c01-8624-4a96-a3e1-7a90e41ddbd0.png">
[1.zip](https://github.com/supermerill/SuperSlicer/files/7569916/1.zip)

**Comment by supermerill** [comment]
Can't reproduce.
what is your os?

**Comment by psusong** [comment]
Solved the problem, thanks
