### ISSUE TITLE
Flow seems way too high or lines way too close in dense layer support

### ISSUE THREAD

**Issue by RomRider** [supermerill/SuperSlicer#1925]
**Describe the bug**
With the last version 2.3.57.6 (and at least with the previous one too as far as I remember), the flow used for the feature "supporting dense layer" seems way too high. It seems to be at least 50% above what it should be.

See below for the project file.

Flow is orange, while it should be yellow (as the same speed is used for the other yellow lines and there is no gap between the lines)
![image](https://user-images.githubusercontent.com/21064206/142663617-36ebacba-7d8f-489b-b9a6-e8c3adf0c75c.png)
As you can see, speed is the same.
![image](https://user-images.githubusercontent.com/21064206/142663655-3e150dfb-0ade-4c5f-9dd0-4162b54dca9a.png)

It get even way worse for when printing the layer 8 (all the other layers above will blob)
![image](https://user-images.githubusercontent.com/21064206/142663809-8d17cfdc-8873-40de-93de-0d36ea1869db.png)

Deactivating the supporting dense layer feature, give the expected results:
* with the setting activated:
  ![image](https://user-images.githubusercontent.com/21064206/142664128-1f3c7798-d03a-4619-a3b0-5fe551771280.png)

* without
  ![image](https://user-images.githubusercontent.com/21064206/142664166-1f006ef2-5c70-4330-9c6b-047e6c165116.png)

**To Reproduce**
See above.

**>> Project File <<**
[Calibration_OctogonV3.zip](https://github.com/supermerill/SuperSlicer/files/7571874/Calibration_OctogonV3.zip)

**Expected behavior**
The proper flow to be used with supporting dense layer feature active. The lines used to be separated which would make this flow rate logical, but not with the way it is now where all the line have no gap between them anymore.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.57.6

**Additional context**

**Comment by supermerill** [comment]
should be fixed in next nightly

**Comment by RomRider** [comment]
Amazing 😊 thanks!
