### ISSUE TITLE
SuperSlicer crash if I use support and brim building

### ISSUE THREAD

**Issue by Jaz939** [supermerill/SuperSlicer#1927]
Hi guys,

The SuperSlicer 2.3.57.5 crash (the application closes) if I tick the brim option and do support at the same time.
I'm attaching the slicer file to try it your self.

BR
Roman
[Andreja2.zip](https://github.com/supermerill/SuperSlicer/files/7572701/Andreja2.zip)
f.

**Comment by supermerill** [comment]
If i load your project, it has the overlapping perimeter selected.
It slices without problem, as expected.
If I unselect it, it still slices...

**Comment by macchinette** [comment]
If I can give my contribution, I tried to open the project and to finish slicing without crashing it is necessary to put the check mark in the parameter.

![image](https://user-images.githubusercontent.com/79080486/142759691-37df2b91-d0f4-431f-8459-ddccf1b11545.png)

**Comment by supermerill** [comment]
brim still have some issues with the support. I'm working on a fix for it.

**Comment by supermerill** [comment]
not good enough, but at least it won't crash and should print.
Will improve it further
