### ISSUE TITLE
Bridges infill not following overhangs perimeter direction

### ISSUE THREAD

**Issue by SellA** [supermerill/SuperSlicer#1939]
**Describe the bug**
Slicing a particular file that has bridges in 2 directions, all are sliced in the same direction, failing following the perimeters path.

**To Reproduce**
1. Open the attached .3mf file
2. Slice it
3. Preview around layer height 10.8mm and look for the first layer of bridges
4. Look at the bridges on the right: overhang perimeters are correctly layed down, bridge infill is turned 90° in the wrong direction.
5. Also bridge overlap is set to 100% but seems that there is some spacing between the extrusions. This is noticeable on the preview, maybe they are correct but that is tricking me.

**>> Project File <<**
[Bridges bug report.zip](https://github.com/supermerill/SuperSlicer/files/7576667/Bridges.bug.report.zip)

**Expected behavior**
Bridges infill should be layed down in the same direction as  overhang perimeters because extrusion must have contact with the solid layers layed on earlier layer. Overhangs perimeters are just "overhangs" that are not squished into previous layers so their width is not large as other extrusion and can't hold infill correctly.

**Screenshots**
![Bridges bug report](https://user-images.githubusercontent.com/2340861/142771469-88ac67c6-d699-4711-9916-89571d68bdae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Version: 2.3.57.

**Comment by SellA** [comment]
So, i found that "Briding angle" was set to 90° and it was forcing the direction on the bridging. Setting it to 0 solved my issue. What is still strange is the bridge infill. Increasing the "bridged_infill_margin" parameters from 200% to 300% i get more lines of bridging,  closing completely all the gaps, also overlapping some of the overhang perimeter. I attach a new screenshot. I don't understand why this parameter influece the number of lines layed down for bridging.
![immagine](https://user-images.githubusercontent.com/2340861/142772042-4193fd05-d80f-42ea-9ebc-6b9e68f3403c.png)

**Comment by supermerill** [comment]
> I don't understand why this parameter influece the number of lines layed down for bridging.

It can change the bounding box used to compute the bridge position & spacing.

Note that the bridge position is updated in the current nightly, so the current behaviour may be updated, hopefully in a good way.

**Comment by SellA** [comment]
Ok so in nightly build i see the correct behaviour. With 200% "bridged_infill_margin" the overhangs are completely filled also there is some overlap that i think is good. I'll try to print it tomorrow and report back and hopefully close the issue!

![immagine](https://user-images.githubusercontent.com/2340861/142778979-ef618c97-3789-4612-9f19-0dcc219b2aaa.png)

**Comment by SellA** [comment]
![20211122_213625](https://user-images.githubusercontent.com/2340861/142931919-6e69772c-22b6-4b5e-9c0c-3f0e3ec03b5e.jpg)

Bridges printed perfectly on latest nightly!
Thanks for the support, glad that super slicer keeps improving!
