### ISSUE TITLE
[FR] Option to enable both M117 and M73 progress reporting at the same time

### ISSUE THREAD

**Issue by kb-elmo** [supermerill/SuperSlicer#1940]
**Is your feature request related to a problem? Please describe.**
No issue. Would just be a nice to have thing

**Describe the solution you'd like**
Add the option to enable both M117 and M73 reporting at the same time.

![image](https://i.aggressive.pizza/superslicer_2021-11-21_22-56-38.png)

**Describe how it would work**
Send the M117 display message and M73 percentage report command together in the Gcode.

**Comment by supermerill** [comment]
It's useful? i had no idea.

**Comment by kb-elmo** [comment]
will this get added? 😄 

> It's useful? i had no idea.

it would be for me (and a few other people that I know)

**Comment by supermerill** [comment]
I would have liked an explanation of the use-case.

**Comment by kb-elmo** [comment]
I thought it was pretty obvious 😄 

The standard display for Marlin shows both a text message and the progress bar.
You need both options to make use of those.

Otherwise either the message text or the progress bar will stay empty.

![image](https://i.aggressive.pizza/ApplicationFrameHost_2022-03-16_13-37-43.png)
