### ISSUE TITLE
Enabling supporting dense layer is not 50% infill after 2.3.57.3

### ISSUE THREAD

**Issue by samwiseg0** [supermerill/SuperSlicer#1945]
**Describe the bug**
I recently updated to 2.3.57.6 from 2.3.57.3 and I noticed that after slicing the bridging layer looked very different from 2.3.57.3. I also tested 2.3.57.4 and it seems the bug may have been introduced in that version. 

**To Reproduce**
1. Go to Printer Settings
2. Enable supporting dense layer
3. Slice

**>> Project File <<**
[mag_board_marker_shelf_v2.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7579307/mag_board_marker_shelf_v2.3mf.zip)

**Expected behavior**
I believe the expected behavior is what I experienced with 2.3.57.3.

**Screenshots**
**Setting:**
![Screen Shot 2021-11-22 at 3 29 22 AM](https://user-images.githubusercontent.com/2241731/142828784-a747bc6a-44c5-48b0-87ab-dee863681594.png)

**2.3.57.3:**
![Screen Shot 2021-11-22 at 3 29 04 AM](https://user-images.githubusercontent.com/2241731/142828837-abe2e12e-2c91-450d-bd8a-c71f01a22c50.png)

**2.3.57.4 - 2.3.57.6:**
![Screen Shot 2021-11-22 at 3 27 19 AM](https://user-images.githubusercontent.com/2241731/142828937-ce5a33f5-9abe-4f61-8847-0e3e7300d546.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 2.3.57.4+

**Additional context**
NA

**Comment by supermerill** [comment]
duplicate of #1925
fixed in the nightly

**Comment by samwiseg0** [comment]
> duplicate of #1925
> fixed in the nightly

Great! Thank you
