### ISSUE TITLE
FR: Seam Position - Overhang Cost

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#1949]
Positioning seams on areas which have a large overhang angle can be problematic. Having a cost factor for overhang could help the cost based algorithm avoid placing seams in overhung areas, when a more vertical wall might exist.

**Comment by supermerill** [comment]
I thought they can't place a seam in an overhang.
Can you give me a project file where this happens?
(file -> save project as  then zip it and drop it here)

**Comment by CCS86** [comment]
I must have been mistaken. Was watching a print and though I saw it making seams on an overhang. I haven't been able to reproduce in SS. If seams on overhangs are already disallowed globally, we can close this request.
