### ISSUE TITLE
Missing Prusa SL1

### ISSUE THREAD

**Issue by pandel** [supermerill/SuperSlicer#1963]
Hi!

I am trying to add a SLA printer but cannot find any profile (Prusa SL1). Doesn't Superslicer support SLA at all?

Superslicer 2.3.57.6 / MacOS 11.6.1

Regards,
Holger

**Comment by supermerill** [comment]
configuration -> wizard -> prusa sla ?

**Comment by neophyl** [comment]
SLA seems to be missing from the wizard when I tried it in 2.3.57.6.  Just updated to the latest config when prompted too.

**Comment by pandel** [comment]
@supermerill 
There is no category Prusa SL atm:

<img width="932" alt="Bildschirmfoto 2021-12-01 um 15 40 10" src="https://user-images.githubusercontent.com/12460002/144255468-d65efd12-2e3c-4927-85da-3354bd4a6f87.png">

**Comment by supermerill** [comment]
oh, right. Weird.

**Comment by supermerill** [comment]
seems like I merged it a bit too aggressively. Will be fixed

If you want to fix it yourself: in the file resources/profiles/prusaresearch.ini:
replace
```
name = Prusa Research
```
by
```
name = Prusa {technology}
full_name = Prusa Research {technology} Technology Printers
technologies = FFF; SLA
```

**Comment by pandel** [comment]
Tried your solution, but the printer still does not show up. But it's ok, you will come up with a solution in the next release :-), many thanks for taking care!

**Comment by supermerill** [comment]
If you laready imported a prusa printer, there is a cache file in your configuration/vendor directory. Modify it or start clean.

**Comment by neophyl** [comment]
Yeah, if you start Super Slicer and use Help>Show configuration folder you can find a sub folder for the vendor that Merill mentions.  In there is a copy of the prusa research.ini file.  If you change that one then run the wizard the sla option appears.  Just tried it on my work pc.

**Comment by pandel** [comment]
Oha! One really has to know about this caching thing. It is working now, many thanks!
