### ISSUE TITLE
[FR] Add option for monotonic bridging pattern

### ISSUE THREAD

**Issue by kb-elmo** [supermerill/SuperSlicer#1964]
**Is your feature request related to a problem? Please describe.**
Right now bridge infill is printed like standard rectiliniar infill which results in the slicer breaking up the infill into mutliple sections.
This can result in different amounts of sagging during the print due to unequal cooling time.

Example:
[![image](https://i.imgur.com/JOlozhPl.png)](https://i.imgur.com/JOlozhP.png)
The bridging infill in the letters is partially printed, then the slicer proceeds to print the normal gyroid infill first before completing the bridging. This results in parts of the bridges to sag more than the rest due to different cooling times.

**Describe the solution you'd like**
Add an option to make the bridging pattern monotonic so that it is printed at once without being broken apart by the slicer.

**Describe how it would work**
Monotonic infill would cause the bridges to cool down evenly and thus reduce irregular sagging.

**Comment by neophyl** [comment]
Nice idea.  Kind of like it. However monotonic is the wrong term, that just means infill is printed in the same direction, it doesn’t mean that it’s not split up into sections.

**Comment by kb-elmo** [comment]
> Nice idea. Kind of like it. However monotonic is the wrong term, that just means infill is printed in the same direction, it doesn’t mean that it’s not split up into sections.

ah ok I just thought that this was what it meant haha :D

**Comment by bwnance** [comment]
@supermerill ok! thanks

**Comment by DanielSmith1239** [comment]
Any updates on this?

**Comment by bwnance** [comment]
@DanielSmith1239 i ended up writing this myself! ([PR here](https://github.com/supermerill/SuperSlicer/pull/2997)) the changes were merged and are in the Arachne 2.5 release - https://github.com/supermerill/SuperSlicer/releases/tag/2.5.59.0

**Comment by bwnance** [comment]
@supermerill good to close this issue due to the merge of #2997

**Comment by DanielSmith1239** [comment]
Ah ok, so it's not in 2.4 then? My issue is similar, where SuperSlicer's bridging pattern isn't continuous (see pictures). Is that what you fixed?

PrusaSlicer:
<img width="587" alt="Screenshot 2023-01-19 at 4 38 22 PM" src="https://user-images.githubusercontent.com/11168127/213568645-41ec4d73-c8b2-4156-a6ee-5770f3af358b.png">

SuperSlicer:
<img width="651" alt="Screenshot 2023-01-19 at 4 38 47 PM" src="https://user-images.githubusercontent.com/11168127/213568650-04292101-2331-44ed-8e1e-bec0a7db1ce1.png">

**Comment by DanielSmith1239** [comment]
Also note that PS has the normal infill before bridging, and SS has the opposite. Might have an impact since it'll be missing anchors.

**Comment by DanielSmith1239** [comment]
Update: looks like your update fixed my bridging issue, thanks! But now I have to figure out how to get the infill to print before the bridges, so I'd really appreciate any input you have on that

**Comment by bwnance** [comment]
@DanielSmith1239 not totally sure on why susli prints sparse infill after bridged - i'd assume that would be an easy addition to the codebase, if i have some time in the next couple weeks i'll take a swing at it.
