### ISSUE TITLE
`Lift Z` missing for some moves

### ISSUE THREAD

**Issue by lijgame** [supermerill/SuperSlicer#1967]
**Describe the bug**
`Lift Z` operation are missing for some moves
Results some unwanted marks/traces on top surfaces(see photo)

**To Reproduce**
Slice attached project

**>> Project File <<**
[case_bug_report_project.zip](https://github.com/supermerill/SuperSlicer/files/7611839/case_bug_report_project.zip)

**Expected behavior**
At layer 5, the z-lift action doesn't happen before a long-distance nozzle move.
Which resulted 

**Screenshots**
![image](https://user-images.githubusercontent.com/301935/143684769-55ff99b8-5192-44b5-ad5e-ce343cc3983c.png)
![image](https://user-images.githubusercontent.com/301935/143685029-351eba20-f039-4221-8348-b1b8787a2e65.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.3.57.6

**Additional context**

**Comment by qwewer0** [comment]
I this helps, that travel move is right before a gap fill.
