### ISSUE TITLE
Insanely high flow rates

### ISSUE THREAD

**Issue by joaoferreira-git** [supermerill/SuperSlicer#2006]
### What happened?

When i slice anything it just gives insane flow rates and almost made my extruder self destruct, it happens with included profiles and also with the ones i tweaked.

![image](https://user-images.githubusercontent.com/19786598/144727838-1ceb1625-cbc9-4c9a-9056-4f1863d029c7.png)

### Project file & How to reproduce

Slice the model and then select view type to volumetric flow rate.

[project-files.zip](https://github.com/supermerill/SuperSlicer/files/7654943/project-files.zip)

### Version

2.3.57.6

### Operating system

Windows 10

### Printer model

Voxelab Aquila

**Comment by supermerill** [comment]
you set 96.77 in your extrusion multipler.
it'a multiplier, not a percentage.
that means a flow of 9677%

**Comment by joaoferreira-git** [comment]
Im sorry for the report i also figured it out today, i was going to delete the bug report now.
