### ISSUE TITLE
Placeholder bounding_box[0] not working

### ISSUE THREAD

**Issue by ding-bat** [supermerill/SuperSlicer#2014]
### win11

Cant get bounding_box[0] to work, I put it in 'Start G-Code' but throws error on slicing
* _Steps needed to reproduce the problem_

In Printer -> 'Start G-Code' :
;klipper macro
;--------------------------------------------------------------
START_PRINT BED=[first_layer_bed_temperature] EXTRUDER=[first_layer_temperature] FLOW=[extrusion_multiplier] XMIN=[bounding_box[0]]
;--------------------------------------------------------------

**Comment by mobilemcclintic** [comment]
Try {bounding_box[0]}

**Comment by ding-bat** [comment]
Yes this works!

Thankyou for your help.

**Comment by ding-bat** [comment]
Just one thing I found.
bounding_box Array order to me is X_min / Y_min / X_max / Y_max.

like bottom corner / top corner.

;--------------------------------------------------------------
;klipper macro
START_PRINT BED={first_layer_bed_temperature} EXTRUDER={first_layer_temperature} FLOW={extrusion_multiplier} XMIN={bounding_box[0]} YMIN={bounding_box[1]} XMAX={bounding_box[2]} YMAX={bounding_box[3]}
;--------------------------------------------------------------

**Comment by supermerill** [comment]
like said in https://github.com/supermerill/SuperSlicer/wiki/Variable-list, no?

**Comment by ding-bat** [comment]
Yes variable list is good, #495 has it different way around, just a bit of confusion.

Anyway, looks like klipper doesn't do M557

12:51:51 
File opened:test_static_0.1_265_85_0.9.gcode Size:1172
12:51:51 
File selected
12:51:51 
// BED 85C, EXT 265C, FLOW 0%
12:51:51 
// XMIN 115, YMIN 105, XMAX 145, YMAX 155
13:01:44 
**// Unknown command:"M557"**
13:01:55 
// probe at 22.000,10.000 is z=1.130156

Will investigate.

Thanks for your help, again. :)

**Comment by supermerill** [comment]
Oh, right.
I have to modify the 495 one, it's not consistent.
