### ISSUE TITLE
Complete Individual Objects

### ISSUE THREAD

**Issue by leesafur** [supermerill/SuperSlicer#2030]
### What happened?

New to Super Slicer so forgive me.. I switched from Cura as I couldn't get a project to print correctly with Klipper.
First time ever using it, I set it up for my printer and to my surprise everything worked and printed perfect. Now when I open two files to print individually, the sliced preview shows them being printed at the same time. I finally gave up and sent the Gcode to the printer and it printed them individually.

<img width="960" alt="2021-12-09 (2)" src="https://user-images.githubusercontent.com/42713329/145421823-21377e9b-e4b5-46ee-8ff1-6c2c59d4c567.png">
<img width="960" alt="2021-12-09 (3)" src="https://user-images.githubusercontent.com/42713329/145421833-38c93383-b62c-499f-b7cf-bb96fc053e06.png">

### Project file & How to reproduce

[SuperSlicer_config_bundle.zip](https://github.com/supermerill/SuperSlicer/files/7686166/SuperSlicer_config_bundle.zip)

### Version

2.3.57.6

### Operating system

Win10

### Printer model

Modified CR6-SE BTTSKR6 Klipper

**Comment by supermerill** [comment]
How did you failed to create a project file when the whole process is explained in the form for issue creation?

**Comment by leesafur** [comment]
Sorry I misunderstood "create a project file" hope this is the right one! 

[18650_8P_base_V2.zip](https://github.com/supermerill/SuperSlicer/files/7686407/18650_8P_base_V2.zip)

**Comment by supermerill** [comment]
the sliced preview show you how the slicer slice the objects.
the gcode preview show you want's going to be printed.
How it's ordered is decided when creating the gcode.
That's why the slider behave differently in the two views.

**Comment by leesafur** [comment]
LOL feeling pretty stupid right now! Thanks for the tip!
