### ISSUE TITLE
Min layer time slows all layers down independent of actual layer time

### ISSUE THREAD

**Issue by theswoosh** [supermerill/SuperSlicer#2033]
### What happened?

Problem:
Full buildplate with pieces to print.
Every perimeter gets reduced to min layer print time even when a layer takes minutes instead of the seconds entered

### Project file & How to reproduce

[slow layer time.zip](https://github.com/supermerill/SuperSlicer/files/7694048/slow.layer.time.zip)

### Version

2.3.57

### Operating system

Windows 11

### Printer model

Qidi X-Plus via Octoprint

**Comment by supermerill** [comment]
please set a retraction speed.
Will add a min to 0.01 on this field

**Comment by theswoosh** [comment]
Great - that solved it!
Thank you :)
