### ISSUE TITLE
Gap Fill Issues

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#2038]
### What happened?

Gap fill is being added in areas I do not expect, and is generated in a way that causes over-extrusion:

![image](https://user-images.githubusercontent.com/12439543/145649064-c454aa21-b9f7-4ee9-8213-bb3cc8e0ac68.png)
![image](https://user-images.githubusercontent.com/12439543/145649096-872dbd1f-2b26-4bc5-822f-d5d3edfd91a9.png)
![image](https://user-images.githubusercontent.com/12439543/145649123-9dfb63b0-d807-41b8-976a-f20649c18ebb.png)

Better here, but weird:
![image](https://user-images.githubusercontent.com/12439543/145649175-63d0045a-feb8-4bfa-8e48-ae63ff65e299.png)

### Project file & How to reproduce

[Gap-fill-issue.3mf.txt](https://github.com/supermerill/SuperSlicer/files/7695762/Gap-fill-issue.3mf.txt)

### Version

2.3.57.6

### Operating system

Windows 10 x64

**Comment by supermerill** [comment]
select a not-`(filled)` for the solid pattern. (use expert mode to show it)

**Comment by CCS86** [comment]
Is this only caused with a sparse infill and filled solid pattern?
