### ISSUE TITLE
Mac Builds are broken

### ISSUE THREAD

**Issue by spuder** [supermerill/SuperSlicer#2055]
### What happened?

The current builds are corrupted for OSX

```
shasum -a 256 SuperSlicer_2.3.57.7_macos-arm_211212.dmg
be332f90c83c26c78a5fed8dd4e8a79b479ca92726874b6f4889bb69ae6f2a48 
```

### Project file & How to reproduce

Download latest build from here: 

https://github.com/supermerill/SuperSlicer/releases/tag/2.3.57.7

Try and run on an M1 mac

By comparison the Intel builds run fine.

I've tried downloading several times to verify it isn't a corrupt download

![Screen Shot 2021-12-13 at 1 40 00 PM](https://user-images.githubusercontent.com/242382/145885947-2699d3a6-b0e1-428c-bb4b-ccd9a8957aa0.png)

### Version

2.3.57.7

### Operating system

OSX

**Comment by spuder** [comment]
Interesting. I don't have to run that command for intel builds. 

I tried `xattr -cr /Volumes/SuperSlicer/SuperSlicer.app`, but its still giving the same error

**Comment by samwiseg0** [comment]
from the screenshot you did not install it into the applications folder. Make sure you install it/move it there first. Do not run it from the disk image

**Comment by spuder** [comment]
🤔  So that worked, but I think there is some improvement that can be done here since that shouldn't be required to run. 

1. I've never had to run `xattr` for any other app on my m1 mac. That seems like an unnecessary hoop to jump through. 
2. Intel builds don't require this manual change. 

I'll also bring up the question, why are there separate builds for arm at all? I do appreciate all the wok that has been done to create ARM builds. I think separate builds are unnecessary because its possible to create universal builds (which is currently what prusa slicer does)
![Screen Shot 2021-12-13 at 1 57 45 PM](https://user-images.githubusercontent.com/242382/145888210-3169f701-aabb-46ae-8665-c6696fff0b5b.png)

**Comment by samwiseg0** [comment]
> 🤔 So that worked, but I think there is some improvement that can be done here since that shouldn't be required to run.
> 
> 1. I've never had to run `xattr` for any other app on my m1 mac. That seems like an unnecessary hoop to jump through.
> 2. Intel builds don't require this manual change.
> 
> I'll also bring up the question, why are there separate builds for arm at all? I do appreciate all the wok that has been done to create ARM builds. I think separate builds are unnecessary because its possible to create universal builds (which is currently what prusa slicer does) ![Screen Shot 2021-12-13 at 1 57 45 PM](https://user-images.githubusercontent.com/242382/145888210-3169f701-aabb-46ae-8665-c6696fff0b5b.png)

The improvement would be to properly sign the application. I doubt that would happen in this case. 

That is because they sign their executables. I doubt the developer would want to jump through that expensive hoop.

**Comment by supermerill** [comment]
I'm trying to get an inexpensive signing certificates.
But I fear it won't work for macos anyway, as I think they want me to own a mac to sign the app.

**Comment by kgleason** [comment]
AFAIK Apple won't let you work with any signing certificate off the shelf. You have to sign up as an Apple developer, and use their signing cert. It's been a minute since I've done any of it, but as I recall it was like $100 / year to sign up to be an Apple dev. Back in the day, you absolutely had to use XCode to sign things. I think that has relaxed of late, but I don't know that you can sign an Apple app on Windows.

The risk with universal builds, especially early on, is that you can't know if your universal build will break across all platforms. If you have a stable code base (intel), and you want to try a platform (ARM), I think it makes sense to do separate builds until all of the kinks are worked out of the process of the new platform.

I'll do some testing on my M1 this weekend to see how it plays.

**Comment by ibash** [comment]
Github actions have a vm for macOS, so it should be possible to let github handle signing: https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development

**Comment by supermerill** [comment]
but that means I have to give the signing key to GitHub, so it's public... so the purpose is defeated.

**Comment by Trackhe** [comment]
I had the Problem too. xattr -cr the app works for me aswell

**Comment by michaelmyc** [comment]
We might want to set up a donation for this purpose and highlight it in README so @supermerill won't need to pay the $100 Apple tax out of his own pocket. At the very least, we should highlight the `xattr -cr /Applications/SuperSlicer.app` workaround in the README.

**Comment by supermerill** [comment]
> We might want to set up a donation for this purpose and highlight it in README so @supermerill won't need to pay the $100 Apple tax out of his own pocket. 

Already done, you can donate with the "sponsor" button here.
I paid the apple tax. Now I'm trying to figure out how to properly sign the app. My problem is that I have only access to a mac computer one time each week.

**Comment by michaelmyc** [comment]
> My problem is that I have only access to a mac computer one time each week.
I recently got a M1 Mac that I'm planning on doing all my personal projects (including 3d printing stuff) on. Happy to assist if you need to run mac-specific stuff. Also happy to help with M1 testing and other stuff Mac-related.

**Comment by supermerill** [comment]
I have to understand the signing stuff myself, i can't share my id.

**Comment by supermerill** [comment]
Here the app & dmg for arm mac, signed.
https://mega.nz/file/YxIyXaxJ#34l9oZLe__2tnLy0QfEfm9ZKdkMDgQYz4T8XtBql2pU
With these, you shouldn't need any xattr things.

**Comment by issic** [comment]
Awesome! I as well have several M1 and M1ProMax computers for testing if you need.

**Comment by th3fallen** [comment]
@supermerill this is still occurring in the latest release 2.4.58.3

**Comment by supermerill** [comment]
@th3fallen The 2.4.58.3 mac arm isn't signed?

**Comment by jfleschler** [comment]
@supermerill I'm seeing the issue with the latest released version as well.

**Comment by supermerill** [comment]
Can you try with this one?
https://mega.nz/file/dogUmRBL#W3t0ZdDiq9YgbErf2L_bDII_cyeSoYo6Mudc3jNzsqo
I verified, and it's signed.
Maybe I have to fresh my Mac certificate...

**Comment by supermerill** [comment]
weird.
It's the same as the one i put in the mega archive. Just renamed.
Maybe github modify something... I'll try some things.

**Comment by alexvonsiebenthal** [comment]
The file from Mega doesn't work either. There are 2 apps in there: one directly in the zip, that won't open because it can't verify the developer:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/6860125/179305820-e8753120-521c-44c8-816a-45024a9acb75.png">

One in another DMG, that can't open for the other error:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/6860125/179305879-73bab5c3-851f-4330-9d67-5691608f3116.png">

**Comment by supermerill** [comment]
Ok, I finally understood what was wrong, and learned how to do it completely.
The dmg from the release page should work, can you test it?

**Comment by alexvonsiebenthal** [comment]
> Ok, I finally understood what was wrong, and learned how to do it completely. The dmg from the release page should work, can you test it?

Yes it works!

> For the universal app, I don't know for now. The intel one is made automatically by a GitHub script, and I have to create the arm manually on an arm Mac. I don't succeed anymore to cross-compile. Last months, I spend the majority of my time messing with Mac and apple instead of doing anything on the slicer... won't do the universal app myself in the current year.

That's absolutely fair and just a minor thing that can wait IMHO. I just raised the idea because Prusa is doing it and I have no idea how much of a hassle it is to merge this process into SuSi.

**Comment by supermerill** [comment]
Hi
here is a test for an universal app:
https://mega.nz/file/01BAVLyJ#D36IjInHUg5_l-uW-x4XY7BRhsQS4jLioeDR5517Shs
can someone:
 * on INTEL: run it without the "brew zstd" (uninstall it if installed), as it should't be needed anymore
 * on ARM: run it after a "xattr -cr /Applications/SuperSlicer.app" (it isn't well signed yet)
 and report.
 Thanks

**Comment by ZerrafRX** [comment]
Universal for ARM is not working with the same error
