### ISSUE TITLE
Autoarrange overlaps objects

### ISSUE THREAD

**Issue by RealDeuce** [supermerill/SuperSlicer#2066]
### What happened?

When "Arrange" is clicked in the attached 3mf file, the parts are arranged overlapping.

### Project file & How to reproduce

[Overlapping.zip](https://github.com/supermerill/SuperSlicer/files/7721842/Overlapping.zip)

To reproduce, click Arrange.

### Version

2.3.57.7

### Operating system

12.2-RELEASE-p3

### Printer model

Voron 2.4 with AB-BN 30

**Comment by supermerill** [comment]
Can't reproduce 
![image](https://user-images.githubusercontent.com/6536403/146245237-8e521bb3-4667-452e-a237-97d3f33b7fae.png)

**Comment by RealDeuce** [comment]
6.00mm Spacing, rotations not enabled.

**Comment by RealDeuce** [comment]
No longer occurs for me on 2.3.57.9.
