### ISSUE TITLE
Holes in sliced part

### ISSUE THREAD

**Issue by DragonHunter274** [supermerill/SuperSlicer#208]
### Version
2.2.49

### Operating system type + version
Windows 10 64 Bit
### 3D printer brand / version + firmware version (if known)
Prusa I3 MK3

### Behavior
If I slice the Skelestruder Omega Fan shroud there is a big hole in the resulting object 
* _Steps needed to reproduce the problem_
Profile: Prusa mk3/s Default Profile 0.15mm
Import file SP_Omega_r1.3mf, Slice 
* _Expected Results_
Part slices without defects like in Prusaslicer:
![Prusaslicer expected](https://user-images.githubusercontent.com/23635514/80146409-17e86300-85b2-11ea-84df-63e6a63495e2.png)

* _Actual Results_
 
![slic3r++ holes in  part](https://user-images.githubusercontent.com/23635514/80146531-45cda780-85b2-11ea-8978-682d31811e72.png)
Large hole in part

#### Project File (.3MF) where problem occurs

[SP_Omega_r1.zip](https://github.com/supermerill/Slic3r/files/4525079/SP_Omega_r1.zip)

**Comment by supermerill** [comment]
There's a bug, it should be printed...
to get the prusaslicer behavior, select "overlapping perimeters"
