### ISSUE TITLE
macOS ARM binary broken

### ISSUE THREAD

**Issue by taglia** [supermerill/SuperSlicer#2091]
### What happened?

The macOS ARM binary does not work on a new MacBook Pro (with the M1 Max CPU), the following error appears when trying to launch it:

`“SuperSlicer” is damaged and can’t be opened. You should eject the disk image.`

<img width="246" alt="CleanShot 2021-12-20 at 13 55 24@2x" src="https://user-images.githubusercontent.com/612306/146718653-4c863ddc-d294-46f8-b8a5-a77266623310.png">

The Intel binary works perfectly with Rosetta 2.

### Project file & How to reproduce

Download the macOS binary from the GitHub release page, open the DMG file, double click on the SuperSlicer app package.

### Version

2.3.57.7

### Operating system

macOS 12.1 (21C52)

**Comment by supermerill** [comment]
duplicate of #2055

**Comment by taglia** [comment]
My bad, apologies for not searching properly, and thanks for pointing me to the solution.
