### ISSUE TITLE
no support at some points

### ISSUE THREAD

**Issue by Lukas1818** [supermerill/SuperSlicer#2115]
### What happened?

The straight surface get not support at one site.
I am not sure if this intended, but I had expected that supperslicer will create support at the full surface.

![image](https://user-images.githubusercontent.com/44570204/147348707-cbb47b06-8554-4672-a025-3399f0c602d0.png)

![image](https://user-images.githubusercontent.com/44570204/147348715-8bb49cf7-15e9-4945-860e-587787d4de32.png)

![image](https://user-images.githubusercontent.com/44570204/147348779-e02f68c1-9477-44e2-a1dc-75ae76bef782.png)

### Project file & How to reproduce

[base plate.stl.zip](https://github.com/supermerill/SuperSlicer/files/7774103/base.plate.stl.zip)

* enable support on print bed
* slice 

### Version

 2.3.57.8

### Operating system

Manjaro

**Comment by supermerill** [comment]
because you didn't uncheck `dont_support_bridges`

**Comment by Lukas1818** [comment]
Thanks
 I had though that this area is the same like the other area, witch get support.

**Comment by Lukas1818** [comment]
Thanks
 I had though that this area is the same like the other area, witch get support.
