### ISSUE TITLE
Superslicer does automatic change values

### ISSUE THREAD

**Issue by Lukas1818** [supermerill/SuperSlicer#2117]
### What happened?

Superslicer does automatic change some values.
I did not save the changes, because I would like to keep the current settings.

![image](https://user-images.githubusercontent.com/44570204/147349654-cdbab640-a986-4248-95c1-7d2a2fce0628.png)

### Project file & How to reproduce

[SuperSlicer.zip](https://github.com/supermerill/SuperSlicer/files/7774176/SuperSlicer.zip)

* open SuperSlicer
* close SuperSlicer

### Version

2.3.57.8, 2.3.57.7, 2.3.57.6 and earlier too

### Operating system

manjaro

**Comment by supermerill** [comment]
width and spacing are exclusive.
If one is active, the other have to be inactive.
In the config, only one have to be set and the other has no value. If it's not the case, the slicer will try to get back to a good state. Here by disabling spacing that are now enable in the default configuration

You can resolve that by saving the configuration, or by adding these lines to your print/default.ini
```
extrusion_spacing = 
external_perimeter_extrusion_spacing = 
external_perimeter_extrusion_spacing = 
first_layer_extrusion_spacing = 
infill_extrusion_spacing = 
perimeter_extrusion_spacing = 
solid_infill_extrusion_spacing = 
top_infill_extrusion_spacing = 
```

**Comment by Lukas1818** [comment]
Thanks for clarification.

![image](https://user-images.githubusercontent.com/44570204/148072488-377d538b-f226-413e-9d04-7efd9470bb25.png)

If I set a `width` value the associated `spacing` value will be automatic adjust.
But how can a `width` value be set to default but the associated `spacing` value  is unequal to the default?

**Comment by Lukas1818** [comment]
thanks for the explanation.
