### ISSUE TITLE
Missing Z Lift

### ISSUE THREAD

**Issue by TerrorzwergOlli** [supermerill/SuperSlicer#2128]
### What happened?

Z Lift don't work on top surface when option "only retract when crossing perimeters" is checkt, although the travel move crossing perimeters. Do not know if this is intended. (Layer 12; Move 8655 this can be found)
![z_lift_3](https://user-images.githubusercontent.com/89738323/147416707-1ccc345b-c98f-44c6-a843-614126f8327b.PNG)
![z_lift_2](https://user-images.githubusercontent.com/89738323/147416709-0b4a6d6a-80fe-47b2-a48c-9f54d0814935.PNG)
 

### Project file & How to reproduce

[missing_z_lift.zip](https://github.com/supermerill/SuperSlicer/files/7777378/missing_z_lift.zip)

### Version

2.3.57.8

### Operating system

Windows 10

### Printer model

Voron 2.4

**Comment by supermerill** [comment]
It's more "only retract when crossing **external** perimeters" currently.

I checked and it's a change in behaviour, I'll fix that.
