### ISSUE TITLE
[Request] Wipe tower Brim size

### ISSUE THREAD

**Issue by Photogad** [supermerill/SuperSlicer#213]
### Behavior
Would like to be able to independently adjust the wipe tower brim size. Sometimes, for very large MMU prints, my wipe tower gets so tall and it becomes unstuck from the bed. Really, being able to make a bigger brim (like a 10mm brim) around it would help immsensely.

_Is this a new feature request?_
YES

Also tagged in Prusa fork:
https://github.com/prusa3d/PrusaSlicer/issues/4149

**Comment by supermerill** [comment]
I tried a long time ago to modify prusa's wipe tower to use first layer width for the first layer, but it was overly complicated because they created an entire new piece of software alongside slic3r for it.
Hopefully, it's now a bit more practical, but no promise.
