### ISSUE TITLE
Question: checksum of 2.3.57.8.tar.gz has changed

### ISSUE THREAD

**Issue by Lukas1818** [supermerill/SuperSlicer#2131]
Why has the checksum of  [2.3.57.8.tar.gz](https://github.com/supermerill/SuperSlicer/archive/2.3.57.8.tar.gz) changed?
A re-release of the same version?

**Comment by supermerill** [comment]
I forgot to push the master to the right position before creating the release.
I have to move the tag when i realized that.
Sorry for the inconvenience. I added a safety check on my script to prevent this issue to happen agin.

**Comment by Lukas1818** [comment]
No problem. I was just a little confused, why the package suddenly failed, because of a wrong checksum.
