### ISSUE TITLE
Solid Infill Issue

### ISSUE THREAD

**Issue by MarcAhoy** [supermerill/SuperSlicer#2141]
2.3.57

Windows 11

Behavior
Solid infill anchors are not connected in some areas but are in others. 
![capture](https://user-images.githubusercontent.com/65318265/147702360-6665c8e7-b578-43bf-8735-3120fa254602.png)

In Prusa slicer 2.4 with the same model and infill set to rectangular 100%, the anchors get connected in all areas. 
![capture2](https://user-images.githubusercontent.com/65318265/147702296-5244f8a1-69f7-4716-959d-67fad05aae85.png)

#### Project File (.3MF) where problem occurs
[Body5 (2).zip](https://github.com/supermerill/SuperSlicer/files/7790580/Body5.2.zip)

**Comment by supermerill** [comment]
Hard to solve in a clean way. Will revert to prusa behaviour in the meantime (no maximum link length)
