### ISSUE TITLE
Gcode Preview does not show / render total model height.

### ISSUE THREAD

**Issue by cdrjameson** [supermerill/SuperSlicer#2145]
### What happened?

My Gcode Preview just seems to stop at Layer 72.  I've checked the setting (printer - max print height) and it's unchanged from the earlier version (2.3.57.7) which shows the full height in gcode preview. 
I've not printed a file from the new version and I still have 57.7 on hand to print from so it's not stopping anything.
![image](https://user-images.githubusercontent.com/4411091/147733773-ac7fa5b1-3b0e-46bc-a021-90853b44e913.png)

### Project file & How to reproduce

[Possible_height_bug.zip](https://github.com/supermerill/SuperSlicer/files/7792047/Possible_height_bug.zip)

### Version

2.3.57.8

### Operating system

Window 10

### Printer model

Ender 3 Pro

**Comment by supermerill** [comment]
can replicate in 2.3.58
can't replicate on the nightly
so should be fixed.
