### ISSUE TITLE
Decimal point with no trailing zeros.

### ISSUE THREAD

**Issue by c9498** [supermerill/SuperSlicer#2151]
### What happened?

I am post processing the gcode from SuperSlicer with Mosaic mfg. Chroma for multimaterial printing. The gcode from Superslicer contains numbers with a decimal point and no trailing zeros. This causes and error in Chroma (see screenshot 1). If I remove the lone decimal points or add a zero it works fine. Screen shot 2 shows one instance of this.(Line 361 - G1 X144.407 Y141. E4.7031).

![Screen shot 1](https://user-images.githubusercontent.com/33936203/147781072-cde07281-3608-4217-b3da-e7c87fc47f01.jpg)

![Screen shot 2](https://user-images.githubusercontent.com/33936203/147781078-523e342a-9b91-4d8d-a1a3-4f083eeed0ec.jpg)
)a 

### Project file & How to reproduce

[4 color test.zip](https://github.com/supermerill/SuperSlicer/files/7794270/4.color.test.zip)

Slice and observe gcode.

### Version

2.3.57.8

### Operating system

windows 11

### Printer model

Railcore 2

**Comment by supermerill** [comment]
yes, that was done to reduce gcode size.
Your parser doesn't like it... It's usual to define a float number. I'll try to remove also the '.'
