### ISSUE TITLE
MacOs arm broken

### ISSUE THREAD

**Issue by BlazingLink** [supermerill/SuperSlicer#2162]
### What happened?

When I open the 2.3.57.8 MacOs arm version, Mac Os tells me that "Superslicer is broken and cannot be opened" The non-arm version opens fine
<img width="260" alt="Screen Shot 2022-01-01 at 18 01 57" src="https://user-images.githubusercontent.com/85244214/147861861-e60920ba-6931-46c9-bd52-14d0ae9a7841.png">

### Project file & How to reproduce

just download and open superslicer 2.3.57.8 MacOs arm version

### Version

2.3.57.8

### Operating system

MacOs Monterey

**Comment by Johnno88** [comment]
I too am having the same issue with MacOs ARM Version

Operating System
MacOS BigSur

MacBook Pro 13" M1 2020

**Comment by viljamip** [comment]
Same here 
<img width="372" alt="image" src="https://user-images.githubusercontent.com/16174789/147878395-1a20218b-46cf-40f2-bae7-0fd8a09bed7e.png">
Macbook Pro 16" M1 Max 2021
MacOs Monterey

Interesting thing is that when I then tried to download and install 2.3.57.7 which used to work, I got the same error. Maybe this can be something related to some MacOs update?

**Comment by viljamip** [comment]
Ah, I'm silly. I forgot this step:
to allow it to run : xattr -cr /Applications/SuperSlicer.app

I managed to get the latest build running, but it appears to be 2.3.57.7.
Version: 2.3.57.7
Build: SuperSlicer_2.3.57.7_2021-12-22

**Comment by Johnno88** [comment]
So,,,  your replies are not clear, 

Will MacOS Arm 2.3.57.8 be fixed or do we run the command line after we install it?

**Comment by viljamip** [comment]
For me this happened:
I downloaded the MacOs ARM build from the 2.3.57.8 release. I dragged it to my Applications folder and then I ran `xattr -cr /Applications/SuperSlicer.app`. When I launched the app, it works fine but it reports its version to be 2.3.57.7. Not sure if the version number is wrong or if that is the same build as before.

**Comment by supermerill** [comment]
It's the version numbering that is wrong. I forgot to build it with the new one. It wasn't added to the auto build process at the time and I borked it.

**Comment by bapski** [comment]
so, decided to try out Superslicer on my macbook pro m1 and i too am having this issue on SuperSlicer_2.3.57.9_macos_arm_220105

how do i get superslicer running?

**Comment by viljamip** [comment]
> so, decided to try out Superslicer on my macbook pro m1 and i too am having this issue on SuperSlicer_2.3.57.9_macos_arm_220105
> 
> how do i get superslicer running?

Open Terminal and run `xattr -cr /Applications/SuperSlicer.app`. Then you can launch the app normally.

**Comment by BlazingLink** [comment]
> Ah, I'm silly. I forgot this step: to allow it to run : xattr -cr /Applications/SuperSlicer.app

Same Lol
