### ISSUE TITLE
GUI Filament Settings

### ISSUE THREAD

**Issue by G3Dmaker** [supermerill/SuperSlicer#2167]
### Version
SuperSlicer-ubuntu_18.04-gtk2-2.3.57.8.AppImage and
SuperSlicer-ubuntu_18.04-gtk3-2.3.57.8.AppImage

### Operating system type + version
Linux Mint 19.3 Tricia

### Behavior
GUI in Filament Settings, Filament Overrides.
wrong positions of Extra Wipe for external perimeters. The record field ist on the left top.

![SuperSlicerGUI](https://user-images.githubusercontent.com/77614515/147928094-7dad1d96-3bea-4978-9c6b-6a7fc51c79f6.png)

When clicking around the program crashes.

**Comment by LazeMSS** [comment]
Same as: https://github.com/supermerill/SuperSlicer/issues/2110

**Comment by G3Dmaker** [comment]
:-) perfect THX
