### ISSUE TITLE
Thin walls Print First on First Layer, Causing Problems

### ISSUE THREAD

**Issue by blex-max** [supermerill/SuperSlicer#2168]
### What happened?

Thin walls print before perimeters/infill on the first layer, often leading to tiny depositions of filament that don't adhere to the bed well. I think thin walls should probably print after perimeters, at the very least on the first layer. My current workaround is to use height modifiers for the first couple of layers and simply disabling thin walls.

### Project file & How to reproduce

[Thin_walls_suggestion.zip](https://github.com/supermerill/SuperSlicer/files/7804530/Thin_walls_suggestion.zip)

### Version

2.3.57.7

### Operating system

Ubuntu 20.04

### Printer model

Creality Ender 3 Pro

**Comment by supermerill** [comment]
also with `print external perimeter first` (same cause)
