### ISSUE TITLE
Calibration gone crazy

### ISSUE THREAD

**Issue by manjaroblack** [supermerill/SuperSlicer#2172]
### Version
2.3.57.8

### Operating system type + version
Linux Mint 20.2

### Behavior
SuperSlicer is progressively going crazy. I tried to go through the calibrations yesterday and succeeded in performing the bed leveling and filament flow calibrations. When I tried to do the filament temperature calibration, klipper kept giving me an error saying "unable to parse move: G1 X- Y5 F5900". I searched the gcode and confirmed that this pattern is common all through out the generated code. Today I attempted to perform the bed leveling again after changing my nozzle. The generated preview looked insane and all over the place. 

![image](https://user-images.githubusercontent.com/42281273/148007444-e11d913e-8c16-4572-a05f-aff8b6006ae1.png)

_Is this a new feature request?_
No

#### Project File (.3MF) where problem occurs
[First layer calibration.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7805257/First.layer.calibration.3mf.zip)

**Comment by supermerill** [comment]
gcode precision -> xyz decimals, set it to something resonable like the default value of 3.

I think ther eis still a problem with 0. Maye the absence of the '.' bugs out the formatter. Will put a min of 1 on it.

**Comment by supermerill** [comment]
I fixed the formatter instead.
But you shouldn't set it to 0 unless you have a house-printing printer.

**Comment by manjaroblack** [comment]
Wow, yeah that was the issue. I am not sure how that got changed. I must have deleted the default by accident!
