### ISSUE TITLE
Only one perimeter - minimum width

### ISSUE THREAD

**Issue by tome9111991** [supermerill/SuperSlicer#2181]
Hello.
im not sure if the setting work as intended or have trouble to understand the effect.
this option:
![Screenshot 2022-01-05 150940](https://user-images.githubusercontent.com/57866234/148241331-a7d1da37-5b8e-4d18-8d37-548f420c4372.png)

I expect that if I am below my minimum width value that Only one perimete will be deactivated.
for a test i instert a high value  80mm
but one perimeter still used.

my project file:
[LedPanelBody.zip](https://github.com/supermerill/SuperSlicer/files/7815846/LedPanelBody.zip)

**Comment by supermerill** [comment]
oups, forgot to multiply by 1000000.
