### ISSUE TITLE
Odd perimeters generated underneath embossed layer

### ISSUE THREAD

**Issue by nchantal** [supermerill/SuperSlicer#2191]
### Version
2.3.57.8

### Operating system type + version
Windows 10 Home

### Behavior
I'm trying to print a simple label that has a rectangular base with embossed text. On the layer prior to the text, the slicer generates these internal perimeters that make the printed label look a lot less clean because they stick out from underneath the embossed text.
![2022-01-06-RoguePerimeters](https://user-images.githubusercontent.com/66767742/148469209-a678b952-f19a-4eef-a335-bd7d1e483d69.gif)

I tried this with similar models where the embossed part is simpler. The slicer also generates some internal perimeters and fill for these, but the upper layers cover these features up.
![2022-01-06-FixingRoguePerimetersOnLabel](https://user-images.githubusercontent.com/66767742/148469254-ad99c6a3-e087-49c7-bbf9-b835b92c73a9.gif)

#### Project File (.3MF) where problem occurs
[FranceLabelTest.zip](https://github.com/supermerill/SuperSlicer/files/7825380/FranceLabelTest.zip)

**Comment by neophyl** [comment]
Turn off single perimeter on top layers tickbox.  Its more complicated than that, theres some other settings you can tweak and there are a couple of other posts around here somewhere with the same issue (so might be closed).  I dont have the time to search right now.  Turning off the option though should clear them right up though.

**Comment by neophyl** [comment]
Just found this in the discussion section , someone else having the same problem https://github.com/supermerill/SuperSlicer/discussions/1896  
New thread too.

**Comment by supermerill** [comment]
you can also just set the "only one periemter" -> 'min width' to 0

**Comment by nchantal** [comment]
Thank you both, that did it!
