### ISSUE TITLE
Spiral vase - incomplete layers

### ISSUE THREAD

**Issue by krankydonkey** [supermerill/SuperSlicer#2192]
### What happened?

When using spiral vase mode, the software creates large gaps in certain layers, resulting in an easily breakable part. This has been tested with 2 different models, both of which slice fine in other software.

![image](https://user-images.githubusercontent.com/30710696/148474713-ce5747b4-a6e6-4f88-a4c3-b892cab4d997.png)

### Project file & How to reproduce

[Spiral Vase Error.zip](https://github.com/supermerill/SuperSlicer/files/7825588/Spiral.Vase.Error.zip)

### Version

2.3.57.9

### Operating system

Windows 11

### Printer model

Voron 2.4

**Comment by supermerill** [comment]
uncheck 'gap_fill_last'

I'll add it to the list of things that need to be switch down for vase mode

**Comment by krankydonkey** [comment]
ah, that'll do it! Cheers
