### ISSUE TITLE
Machine Limits Dialog displays incorrect units

### ISSUE THREAD

**Issue by thetekguy1** [supermerill/SuperSlicer#2194]
### Version
2.3.57

### Operating system type + version
Manjaro Linux, latest rolling build (up to date) running Gnome 41.2

### Behavior
Printer-Machine Limits dialog under Maximum and Minimum Feedrates are all listed as mm/min, should be listed as mm/s

**Comment by supermerill** [comment]
why?

**Comment by thetekguy1** [comment]
they should be corrected to state mm/s, otherwise people will input feedrates into those fields in mm/minute which is a 60x larger value, throwing off print estimates wildly. 40 mm/s = 2400 mm/min...

**Comment by supermerill** [comment]
https://github.com/supermerill/SuperSlicer/issues/440

**Comment by thetekguy1** [comment]
this issue is in the 2.3.57.9 release, if 440 was fixed and closed in 2020,
the issue is back...

**Comment by thetekguy1** [comment]
yes, this is  repeat of #440 from 2020, it has resurfaced in 2022 in the current 2.3.57.9 release.

**Comment by thetekguy1** [comment]
no

**Comment by thetekguy1** [comment]
what do you mean by no?
