### ISSUE TITLE
v 2.3.57 MacOS Intel -hanging generating skirt

### ISSUE THREAD

**Issue by dsundt** [supermerill/SuperSlicer#2200]
### What happened?

When slicing a model SuperSlicer hangs generating the skirt and the slicing fails to complete
[Rusic Bowl Outer.zip.amf.zip](https://github.com/supermerill/SuperSlicer/files/7833871/Rusic.Bowl.Outer.zip.amf.zip)
.

### Project file & How to reproduce

Click Slice Button

### Version

2.3.5.79.9

### Operating system

MacOS 11.6.2

### Printer model

Voron 2.4

**Comment by supermerill** [comment]
Don't put 0 in the filament extrusion multiplier or it won't extrude anything.
