### ISSUE TITLE
Travel speeds not converting from mm/s to mm/min in exported GCODE

### ISSUE THREAD

**Issue by linyongzheng** [supermerill/SuperSlicer#2222]
### What happened?

Problem: Travel moves are 1/60th their intended speed because custom values are not being multiplied by 60 in exported gcode.

Expected: Feed rates should be multiplied properly.

### Project file & How to reproduce

[wasteBinLid.zip](https://github.com/supermerill/SuperSlicer/files/7867767/wasteBinLid.zip)
Slice, export GCODE, open GCODE in text editor, travel moves (like line 24) are not being converted from mm/s to mm/min (multiply by 60).

### Version

2.3.57.9

### Operating system

Windows 10

### Printer model

JGMaker Artist-D Standard

**Comment by supermerill** [comment]
from the sliced gocde:
`G1 X81.25 Y81.25 F15000`
so it's the 250mm/s you entered.
Where is the problematic line?

**Comment by linyongzheng** [comment]
Just resliced, still showing the error.

Lines 35-42 also showing only F250 instead of F15000
![image](https://user-images.githubusercontent.com/29169062/149631620-045632d6-9fad-4c76-9e31-cbb104e16bae.png)
![image](https://user-images.githubusercontent.com/29169062/149631687-0d220125-a0ab-4960-b409-4d1d50e34d75.png)
![image](https://user-images.githubusercontent.com/29169062/149631646-295a7bb8-fad5-4e41-9f87-aed077d596d7.png)

**Comment by linyongzheng** [comment]
Looks like it is isolated to the custom gcode blocks where it is just directly along the values from the profile parameters but not converting proper units.
![image](https://user-images.githubusercontent.com/29169062/149631967-d799d546-97b7-4809-8236-5ca0b9219fcf.png)
![image](https://user-images.githubusercontent.com/29169062/149632010-0ce9a0e3-892d-4aa3-aa18-fac0309c49a4.png)

**Comment by linyongzheng** [comment]
Looks like this is also prevalent in the prusaslicer 2.4.0. Also going to report issue there. Let me know if you want me to close it out here and have prusaslicer fix it.

**Comment by linyongzheng** [comment]
According to Prusa, this behavior is "as intended" I think this is a poor excuse because it can easily be repeated without prior knowledge.

Regardless, since this is as intended, I'll close out this issue.

**Comment by supermerill** [comment]
you can do the conversion yourself:
`G1 X-20 F{travel_speed*60}`
also you don't have to repeat the speed at each line, it's store until there is another F parameter
