### ISSUE TITLE
[Feature request]: Bridge through holes on mid-air flats

### ISSUE THREAD

**Issue by Miksu80** [supermerill/SuperSlicer#2223]
It'd be nice to have an option to make bridge on holes that are on flat surface in mid-air. When doing prints like this:

![image](https://user-images.githubusercontent.com/48354615/149454932-abb8eb46-62a0-4d58-ad07-b349775debcd.png)
![image](https://user-images.githubusercontent.com/48354615/149455514-5ff11d29-806a-4dae-aa5e-9c27080bdd82.png)

You've got to have supports so they can be printed nicely:
![image](https://user-images.githubusercontent.com/48354615/149455058-9c358e62-4e9d-4296-9d4e-a4565cf9d9af.png)

But you can achieve a nice print also by bridging through holes like this, without a need for supports:
![image](https://user-images.githubusercontent.com/48354615/149455335-6a6ff705-84fd-4475-add3-f5c4e6964a54.png)

The bridges are easier to clean than supports and print quality is good this way

When deciding whether if its going to be a bridge or normal support, bridge length would be the ideal parameter -> if bridging length becomes too long, there might be sagging and it wouldn't work.

U can achieve this in CAD but it would be a lot easier and intuitive if it'd be a slicer option 😊

**Comment by Miksu80** [comment]
Thank you, I totally missed this :)
Tested it and it works good although noticed a bug:
![image](https://user-images.githubusercontent.com/48354615/149483996-2e42020a-35fe-4970-ad3e-ddfea09eb2da.png)
![image](https://user-images.githubusercontent.com/48354615/149483494-41a462ad-bc3b-4ea2-8a24-869472f3e36f.png)

[Bridge_voids.zip](https://github.com/supermerill/SuperSlicer/files/7869065/Bridge_voids.zip)

**Comment by neophyl** [comment]
Well it is experimental :)  Also while our human brains can look at that model and go , oh yeah that applies there but not there, its much harder for an algorithm.  Its doing what you asked in all parts of it.  I guess that's why the tooltip says to use a modifier to apply it in the areas you want.  That way you get the human discrimination into the loop.

**Comment by Miksu80** [comment]
Was in a rush so didn't have time to examine it better, Ill close this one
