### ISSUE TITLE
Translation to german

### ISSUE THREAD

**Issue by cryd-s** [supermerill/SuperSlicer#2227]
I want to translate the SuperSlicer to german but the extended Config witch SuperSlicer added to the PrusaSlicer is not in the PO Language Folder. 

How and where can i translate for example this:
![susi](https://user-images.githubusercontent.com/47699362/149555687-8738289d-ed0b-4c87-b6dc-fb85754948f4.jpg)

**Comment by supermerill** [comment]
The tutorial is here:
https://github.com/supermerill/SuperSlicer/tree/master/resources/localization

mostly, you have to modify the setting.ini to reference the file inside the de folder, so something like that
you need python at the very least, 
then grab python-Levenshtein with `python -m pip install python-Levenshtein`
and it's better to have gettext also but not mandatory.

```
data = de/Slic3r.po
data = de/TODO.po
data = de/MyKnowledgeBase.po
data = de/ps24.po

# optional: output all the knowledge base into a file, to be reused in the future.
database_out = de/MyKnowledgeBase.po


# path to the ui_layout dir, to grab all ui string defined here
ui_dir = ../ui_layout
# to allow to keep the msgctxt tags. You need a recent version of gettext to use that.
allow_msgctxt = false
# the tool to ignore the case when comparing msgid if no exact translation is found.
ignore_case = false
# will remove the comments in the output files (not the todo).
remove_comment = true
# flaot between 0 and 1. If higher than 0, the tool may porpose you some similar transaltion from the knowledge base in the comment
#    to help you write the translation. It's useful when only a part of the original string changes, so you can reuse almost everything.
# it's the % of diff (levenshtein distance / msgid length) allowed for an other string to be proposed
percent_error_similar = 0.4
# max number of proposed translation per item. Work with percent_error_similar.
max_similar = 3
# strings written in the header
language = deutch
language_code = de

# input is the pot (or po) where the msgid are picked
input = Slic3r.pot
# the todo will receive the msgid for which no translation are found
todo = de/TODO.po
# the output will receive the other msgid with their translation
output = de/Slic3r.po
```
you can also get the latest PS po, and add it as data (here ps24.po) as that may help a bit more.

once you have that, open a command file, go here and type `python pom_merger.py`

that will generate a TODO.po, up to you to complete it and relaunch the python script to "save your work" (transfert the translations from Todo to Slic3r.po and the knowledgeBase. 
It doesn't prevent you to modify the Slic3r.po if you want to.

here a pic on why there is some comments:
![how_to_translate](https://user-images.githubusercontent.com/6536403/149643442-34ac90f4-62e1-48fa-82dd-b4f34301b2c8.png)
![how_to_translate_poedit](https://user-images.githubusercontent.com/6536403/149643443-42465f20-82f0-4c43-8660-cfbf67b17562.png)

here to help with further questions.
Also it's a good idea to open a discussion to debate with other deutch-speaker on translations, it's a bit better than in issues.

**Comment by thrukk** [comment]
Hi, we have translated some stuff but cant figure out how to convert the .mo file into the .po file. a push in the right way would be nice.

**Comment by supermerill** [comment]
if you want to do pull request, commit the .po, the .mo isn't versionned, it's compiled.
If you want to compile your .po in a .mo, you can use the makefile (in windows Vs, the po_to_mo project).
If you want to transform the .po in a .mo or the .mo into a .po, use gettext. see https://github.com/supermerill/SuperSlicer/tree/master/resources/localization
`msgfmt my.po -o my.mo`
`msgunfmt my.mo -o my.po`
