### ISSUE TITLE
Latest macOS arm build can't be opened

### ISSUE THREAD

**Issue by ornamentist** [supermerill/SuperSlicer#2230]
### What happened?

After downloading the macOS arm build 2.3.57.9 and opening it, I'm seeing a "“SuperSlicer” is damaged and can’t be opened. You should eject the disk image." error from the finder.

### Project file & How to reproduce

Download macOS arm 2.3.57.9 build and open it on an m1 mac.

### Version

2.3.57.9

### Operating system

macOS 12.1

### Printer model

Any

**Comment by supermerill** [comment]
duplicate of #2055 and 3 others

**Comment by ornamentist** [comment]
Closed as duplicate of existing issues.
