### ISSUE TITLE
Support Dense layer not triggering for a large Island in the middle of sparse (10%) infill

### ISSUE THREAD

**Issue by gpread** [supermerill/SuperSlicer#2243]
### What happened?

Support Dense layer (using 50% straight lines) beneath bottom solid layer, is a great feature.

On my test project this worked nicely for the top surface (of a 40mm XYZ Calibration cube) which covers ~75% of the total top surface area (so ~ 1200 of 1600mm2).

However, its not triggered for another significant size Solid layer which is beneath the top and covers ~25% (~400mm2 of 1600mm2).  This results in those solid layers collapsing/containing holes.

I tried all the options available for the support dense layer algorithm and none of them triggered it for those layers.

I expected/would want one of the existing algo options or an additional one which would cause it to be triggered for this (and similar scenarios).   

Here is a screen capture showing the sliced object with the walls (perimeters) and internal infill (10%) filtered out, where you can see the support is there for the top but not for the island).
![Susi_XYZcube_missing_DenseSupportLayerforIsland](https://user-images.githubusercontent.com/59426970/150138268-b9e176f6-8286-4761-8e37-fba6297aa89f.png)

Here is screen capture showing triggered dense support layer for the top solid layers which works and it what I expected/would want to happen also for the island
![Susi_XYZcube_missing_DenseSupportLayerforIsland_TrigLayer](https://user-images.githubusercontent.com/59426970/150138454-34bc772c-a2ec-48d9-8c65-54cefa26a239.png)

But instead this screen capture shows its missing for the island.
![Susi_XYZcube_missing_DenseSupportLayerforIsland_notTrigLayer](https://user-images.githubusercontent.com/59426970/150138599-6b94a254-0abf-4981-b9fd-c7bcfb7e9cde.png)

### Project file & How to reproduce

1. Load the attached project file in Susi
2. Use the vertical layer selection scroll bar
3. Examine layers for Solid Island which has collapses/holes when printed
      Layer 176 (dense support is missing, its sparse infill)
      Layer 177 bridge infill
4. .Examine layers for Top Surface
      Layer 196 (dense support at 50%)
      Layer 197 bridge infill

[xyzCalibration_cube_40-40-40_0.2mm_PETG_Susi_2_3_57_9_Issue#2243.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7897488/xyzCalibration_cube_40-40-40_0.2mm_PETG_Susi_2_3_57_9_Issue.2243.3mf.zip)

### Version

2.3.57.9

### Operating system

Windows 10 21H1 (Build 19043.1466)

### Printer model

CR-10V3 (Modified), BTT_GTR1, Marlin 2.0.9.2

**Comment by supermerill** [comment]
Forgot that infill/perimeter can be 0
