### ISSUE TITLE
Top layer with 1 perimeter below top surface

### ISSUE THREAD

**Issue by rovili** [supermerill/SuperSlicer#2257]
### What happened?

Objects with lower top layers get 1 perimeter option, even if something is on top. External perimeter should go through all height.

1 perimeter layer:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/97400836/150593398-fbf74022-f803-49b4-8406-4ec6a997acfa.png">

above again multiple perimeters:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/97400836/150593454-0e32b20f-93b8-46e4-bb6d-494b672b4b63.png">

### Project file & How to reproduce

[example.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7916357/example.3mf.zip)

### Version

2.3.57.9

### Operating system

macOS 12.2

**Comment by rovili** [comment]
Maybe a misunderstanding from my side. But I think this should only be applied to the last layer? Here it happens in mid of the object.

**Comment by supermerill** [comment]
All red one are top surfaces. A top surface is a surface without anything on top of it.
If you want that only on the topmost layer, you can use a modifier to modify the perimeter count directly.

**Comment by rovili** [comment]
I understand - we can close this ticket. =)
