### ISSUE TITLE
Extra perimeters on overhangs -> crash

### ISSUE THREAD

**Issue by btthrt** [supermerill/SuperSlicer#2261]
### What happened?

I was trying to reproduce my recent crashes with different models and found a way to.

2.3.57.4 - gets stuck on last %
2.3.57.5 - crash
2.3.57.6 - crash
2.3.57.7 - crash
2.3.57.8 - crash
2.3.57.9 - crash

### Project file & How to reproduce

1. Open Cup.stl from attached zip [cup.zip](https://github.com/supermerill/SuperSlicer/files/7918516/cup.zip)

2. Slice it with "extra perimeters on overhangs" option turned on
(.4 nozzle, .2 layer, 4 perimeters, 6 top, 8 bottom)

3. Yep

### Version

2.3.57.9

### Operating system

win 11

### Printer model

voron 2.4

**Comment by DVSVIDEO** [comment]
I tried the Cup.stl file you used and the same thing happened to me: it crashed under Win 10.
Since I have always had this option enabled and it hasn't crashed so far, the error is only with this model.
