### ISSUE TITLE
Bridging at set angle for object regardless of viability

### ISSUE THREAD

**Issue by HopsDa** [supermerill/SuperSlicer#2262]
### What happened?

There should be no overlap of the bridging lines and so the bridge should be in the correct direction to support upper layers. I have cut half the model off to have a second object and there the bridging is correct. sorry for the bad explanation but i think you will understand from the screen shots. 

Thank you!

### Project file & How to reproduce

<img width="1726" alt="Screenshot 2022-01-22 at 19 50 34" src="https://user-images.githubusercontent.com/98230450/150649851-d797ac05-ff90-43c3-bc89-064b9fb9b1b5.png">
[config.ini.zip](https://github.com/supermerill/SuperSlicer/files/7918966/config.ini.zip)

### Version

2.3.57.9

### Operating system

mac with M1 pro

### Printer model

RatRig 400mm, octopus v1.1, raspi4

**Comment by neophyl** [comment]
Looks like your attached project didn’t make it to the issue. I’m just seeing text and not a downloadable link.

**Comment by HopsDa** [comment]
[Bridging not working.3mf.zip](https://github.com/supermerill/SuperSlicer/files/7923284/Bridging.not.working.3mf.zip)

**Comment by neophyl** [comment]
As far as the algorithm is concerned it is a single bridged area.   As either direction is good for one and not for the other it picks one.  
You have the Advanced option "No perimeters on bridge areas" set to keep only bridges.  So its removing all the perimeters. that would normally  support  the edges of the bridge when its printed in the short direction.

The section where you have excised for test purposes only travels one way and so the calculation is different. and it puts it in the best way for that area.

If you set 'No perimeters on bridge areas' to Disabled  or  Keep bridges and overhangs then it should print better.  If you really really dont want perimeters on those sections then you will have to use modifiers to manually set the angles of the bridging in those areas.

**Comment by HopsDa** [comment]
it does indeed make a difference and i haven't thought about modifiers at all. about time to give them a try!

Thank you!
