### ISSUE TITLE
Not slicing model properly when "External Perimeter First" is activated

### ISSUE THREAD

**Issue by WickedInvi** [supermerill/SuperSlicer#2267]
### What happened?

Activated External perimeter. Crashed multiple times when it doesn't the inside outer perimeter does not slice. Tested with the previous version and slices fine. Copied the settings to the backup SS folder I keep.

Here is the model
![image](https://user-images.githubusercontent.com/49752323/150865413-824d33b3-3681-43c7-b488-24919f8f2632.png)
On the current version
![image](https://user-images.githubusercontent.com/49752323/150865437-1fcc45a7-9043-4bbe-984b-143e60e35a65.png)
On version 2.3.57.8
![image](https://user-images.githubusercontent.com/49752323/150865490-cf75d942-c009-45cb-a002-5f675b283004.png)

I also ran a calibration cube with the same settings and runs 2 passes on the inner and outer walls. Thought it was something else until I notice doing 4 walls on every layer but I had 2  set up. Also, G code previewed shows that.

![image](https://cdn.discordapp.com/attachments/395260585895264257/935490208525340672/20220125_120354.jpg)

### Project file & How to reproduce
Activate Eternal perimeter first
[config.zip](https://github.com/supermerill/SuperSlicer/files/7928868/config.zip)

### Version

2.3.57.9

### Operating system

Windows 10

### Printer model

Ender 3 with SKR mini E3 v2, Klipper, Dragon Hot end, Belted Dual Z

**Comment by supermerill** [comment]
can't reproduce the problem
![image](https://user-images.githubusercontent.com/6536403/151075019-68f9c178-8412-4c8e-a378-2c644b50a4a8.png)

Can you share your project file?

**Comment by WickedInvi** [comment]
[Calibration cube.zip](https://github.com/supermerill/SuperSlicer/files/7940175/Calibration.cube.zip)
