### ISSUE TITLE
Wipe Tower have one very slow line

### ISSUE THREAD

**Issue by Siwat2545** [supermerill/SuperSlicer#2271]
### What happened?

![image](https://user-images.githubusercontent.com/8684409/151092655-a757de3f-51c3-4b08-85c5-8ab3f2894b2b.png)
The print is using the Palette 2S with P2PP, however, the issues seem to be from the slicer.
The nozzle moves stupidly slow over these lines and increases print time drastically.

### Project file & How to reproduce

[AnimalCell.zip](https://github.com/supermerill/SuperSlicer/files/7938516/AnimalCell.zip)
https://github.com/tomvandeneede/p2pp

### Version

2.3.57.9

### Operating system

Windows 10

### Printer model

Prusa i3 MK3S with Palette 2

**Comment by Siwat2545** [comment]
Seems to have something to do with ramming, but the p2pp manual tells me to disable it.
However when I enable ramming, this happens
![image](https://user-images.githubusercontent.com/8684409/151093986-addf62fd-2bd8-485e-b5a7-6f5dd939a8d5.png)

Are there any ways to set a constant wipe speed?

**Comment by supermerill** [comment]
I added a limit on speed from filament_max_speed, but i forgot to multiply by 60 [shy]

**Comment by Siwat2545** [comment]
If I don't set the filament_max_speed, P2PP just yeet the nozzle left and right over the wipe tower, haha
![image](https://user-images.githubusercontent.com/8684409/151296873-232dd092-d73d-4115-8903-7397623f39e3.png)
But no worries, I'll use canvas while I want patiently for your wonderful bug fix :)
