### ISSUE TITLE
Ironing also on perimeters

### ISSUE THREAD

**Issue by guestisp** [supermerill/SuperSlicer#228]
Would be possible to add ironing to the whole surface and not only on solid part/infill ? 
In example, a cube with 5 perimeters, ironing will start only on the infill, leaving the perimeters visibile.

If possible, ironing the whole surface, even if made only with perimeters, would be useful to get a flat surface with no visibile lines

**Comment by supermerill** [comment]
I'll integrate prusa ironing with the next merge, so you will be able to use the current, the new one or both if you want.

**Comment by guestisp** [comment]
Which is the new one? New feature from prusa?

**Comment by supermerill** [comment]
https://github.com/prusa3d/PrusaSlicer/issues/458#issuecomment-613348690
