### ISSUE TITLE
Fan Speed Modifier Per Machine

### ISSUE THREAD

**Issue by m157** [supermerill/SuperSlicer#2280]
I have two printers (ender3 with dual 5015s, Mega S with stock part fan) and have realized that the fan speed is tied to the filament
I have my filaments shared between the two printers cause they print similarly enough for all other settings

**Describe the solution you'd like**
A per machine fan modifier setting

**Describe how it would work**
filament fan speed * machine modifier

**Comment by supermerill** [comment]
search extruder_fan_offset
