### ISSUE TITLE
Single Layer, with an Extra Layer on Top?

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#2281]
### What happened?

This one is pretty odd:

![image](https://user-images.githubusercontent.com/12439543/151577970-f5174279-86be-4cba-99f0-5b8ef1d2e5fe.png)

### Project file & How to reproduce

[DoubleLayer.3mf.txt](https://github.com/supermerill/SuperSlicer/files/7959961/DoubleLayer.3mf.txt)

### Version

2.3.57.9

### Operating system

Windows 10 x64

**Comment by CCS86** [comment]
These additional print moves don't show up in the sliced preview, only in the gcode preview.

**Comment by CCS86** [comment]
I think I may have gotten rid of these segments by disabling the variable layer height feature and then reenabling it.

**Comment by supermerill** [comment]
seems like a goce viewer issue.
I'll see if it's still present in the 2.4

**Comment by CCS86** [comment]
I was wondering whether the gcode viewer was just displaying part of the next layer. I did not try to print.

I changed many print settings and the behavior persisted. Once I changed the minimum segment length and disabled variable layer height, the behavior went away and didn't return when I reverted those settings.

**Comment by supermerill** [comment]
Not present in 2.4.
I won't bother fix that in the 2.3 branch.

**Comment by CCS86** [comment]
Sounds good, thanks! I just downloaded the latest 2.4 nightly to poke around. The live gcode viewer is pretty awesome.
