### ISSUE TITLE
Weird top layer 

### ISSUE THREAD

**Issue by Oliv6176** [supermerill/SuperSlicer#2299]
### What happened?

I'm experiencing weird top layers in Superslicer, but not in Prusaslicer 2.4
![Screenshot from 2022-02-01 19-44-08](https://user-images.githubusercontent.com/32340667/152032052-82608379-1675-42b3-9ccd-2fc7a292b78b.png)
![Screenshot from 2022-02-01 19-44-34](https://user-images.githubusercontent.com/32340667/152032057-ac1f9a63-5e64-44f1-b091-2109a7a496a6.png)

### Project file & How to reproduce

[Heart-Body.zip](https://github.com/supermerill/SuperSlicer/files/7981193/Heart-Body.zip)

### Version

2.3.57.9

### Operating system

Ubuntu 21.10

### Printer model

Ender 3 Pro

**Comment by supermerill** [comment]
remove "min width" from "only one perimeter - on top"
