### ISSUE TITLE
New version check seems to have issue with last position

### ISSUE THREAD

**Issue by RealDeuce** [supermerill/SuperSlicer#2301]
### What happened?

Built and ran 2.3.57.10 when 2.3.57.9 is the latest release... SuSl says there's a new version available.

### Project file & How to reproduce

Build current Nigthly, run.

### Version

2.3.57.10 Nigthly

### Operating system

FreeBSD 12.3-RELEASE

### Printer model

Voron 2.4 with Stealthburner

**Comment by RealDeuce** [comment]
![image](https://user-images.githubusercontent.com/9758938/152069842-148a52b4-a94f-4da2-b32a-1e54169cd543.png)

**Comment by RealDeuce** [comment]
```
> grep -r version_online .
./SuperSlicer.ini:version_online = 2.3.57.9
```

**Comment by RealDeuce** [comment]
Oh, this is on purpose maybe?
```C
                //if (*Semver::parse(SLIC3R_VERSION_FULL) < *Semver::parse(into_u8(evt.GetString()))) {
                    this->plater_->get_notification_manager()->push_notification(NotificationType::NewAppAvailable);
                //}
```

**Comment by supermerill** [comment]
problem is "10" < "9"
and I had no time to tinker with it to parse the string correctly into a valid version number.
The real test is at PresetUpdater:l291 anyway
