### ISSUE TITLE
Seam Gap Ignored in Some Areas

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#2302]
### What happened?

![image](https://user-images.githubusercontent.com/12439543/152088383-18326630-c0bc-4427-9354-02b2804b3c2a.png)

### Project file & How to reproduce

[DuctR.3mf.txt](https://github.com/supermerill/SuperSlicer/files/7983360/DuctR.3mf.txt)

### Version

2.3.57.9

### Operating system

Windows 10 x64

**Comment by supermerill** [comment]
you can use the latest nightly, it already has the fix
