### ISSUE TITLE
First top layer problem, it is sliced half only

### ISSUE THREAD

**Issue by nopbit** [supermerill/SuperSlicer#2303]
### What happened?

Hello all,

I had a weird bug, when the top layer sliced, it is sliced in half. Anybody faced smilar problem?

![image](https://user-images.githubusercontent.com/31405701/152135156-04a20229-bd46-4403-9197-4b7828f6cb2c.png)

Thanks for your answers

Mustafa

### Project file & How to reproduce

This problem appears on layer 5 only.
[small-super-slicer.zip](https://github.com/supermerill/SuperSlicer/files/7985585/small-super-slicer.zip)

### Version

2.3.57

### Operating system

Windows 10

### Printer model

Custom Printer

**Comment by nopbit** [comment]
It slices correctly if i choose "ensure vertical thickness".

**Comment by supermerill** [comment]
I had a similar thing on another issue.
It's fixed in the latest nightly
