### ISSUE TITLE
Random shutting down of SuperSlicer

### ISSUE THREAD

**Issue by michaelaswood1980** [supermerill/SuperSlicer#2331]
### Version
2.3.57.10

### Operating system type + version
Windows 11

### Behavior
Superslicer will randomly shutdown when I'm moving objects on the build plate, changing their visibility. if I go to slice lots of objects on a build plate it will randomly shutdown.

_Is this a new feature request?_
NO

#### Project File (.3MF) where problem occurs
This is just one of the files that it is happening with.
[LGX.zip](https://github.com/supermerill/SuperSlicer/files/8022764/LGX.zip)

**Comment by supermerill** [comment]
Comes from the brim
