### ISSUE TITLE
Crash on Slice

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#2338]
### What happened?

Something in my combination of settings and this model seems to cause a fatal issue. I have the project file saved in a condition where it should crash on slice.

### Project file & How to reproduce

[tolerance_test.3mf.txt](https://github.com/supermerill/SuperSlicer/files/8034554/tolerance_test.3mf.txt)

### Version

2.3.57.10

### Operating system

Windows 10 x64

**Comment by supermerill** [comment]
same as #2331, it's a bug in the brim.
You can remove it or use the latest nightly.

**Comment by CCS86** [comment]
Thanks!
