### ISSUE TITLE
small gaps between two objects are joined

### ISSUE THREAD

**Issue by acwest** [supermerill/SuperSlicer#2339]
### What happened?

When two objects are very close together (I am guessing the line width is the magic number) there appears to be no way to cause the slicer to keep the objects separated. When doing print-in-place gears, this tends to be a problem...
`gap fill` seems like it might be pertinent, but turning it off has no effect.

Good walls, gap 0.20mm
![Good walls, gap 0.20mm](https://user-images.githubusercontent.com/55695/153288361-f9956ff9-3c4c-4b93-a99f-5fceaca78b22.png)
Bad walls, gap 0.18mm
![Bad walls, gap 0.18mm](https://user-images.githubusercontent.com/55695/153288449-da974019-27a1-40f6-9749-3e49cc3a6ec0.png)
Really bad walls, gap 0.10mm
![Really bad walls, gap 0.10mm](https://user-images.githubusercontent.com/55695/153288564-cbcb29d1-3310-4694-870f-86fe00cf8394.png)

### Project file & How to reproduce

To reproduce, just slice it, then look through the layers.

[perimeter-bug.zip](https://github.com/supermerill/SuperSlicer/files/8036253/perimeter-bug.zip)

### Version

2.3.57.10

### Operating system

Arch Linux

### Printer model

Ender 3 (not very default)

**Comment by supermerill** [comment]
set `slice_closing_radius` to 0

**Comment by koshisan** [comment]
I think there is still an issue here. I am on 2.4.58.5

Part of my model has a very fine cutout:
![grafik](https://user-images.githubusercontent.com/40839790/227710284-4e3c96ab-9802-4e27-ad8c-7c1173b256f1.png)

When I slice it, they disapear:

![grafik](https://user-images.githubusercontent.com/40839790/227710306-01e2043a-ba14-42cd-b5a4-b3b8b5048143.png)

I tried slicing with absurd values like 0,000000049 slice closing radius and slice resolution of 0,00001, but the result stays the same. Setting the values to 0 also didn't help. 

Real width of the gap should be around 0.25mm. Increasing the printsize by around 10% solves the problem.

**Comment by Thoooomas14** [comment]
Try setting XY-compensation to 0 (slicing-> Modifying slices -> XY compensation)
