### ISSUE TITLE
Unpredictable behavior in automatic bridges

### ISSUE THREAD

**Issue by liftbag** [supermerill/SuperSlicer#234]
### Version
_2.2.50 (also in PrusaSlicer 2.2.0)_
### Operating system type + version
_macOS Catalina 10.15.4_
### Behavior
* _Sorry to report it here, as this is an error imported from PrusaSlicer. If you deem it appropriate, I also report it in PrusaSlicer.
Automatically generated bridges have two types of inaccuracies, which depends on the angle of the part._

This is an object created to evaluate the automatic generation of bridges. As can be seen, the most accurate bridge is the one below. The rest show parallelism defects with the general trend of the perimeters, and a detachment from the perimeters, due to the starting point.

<img width="1040" alt="Schermata 2020-05-11 alle 12 40 13" src="https://user-images.githubusercontent.com/14921654/81556032-eaf5c780-9389-11ea-9e3e-e7defb207ae7.png">

The strategies adopted vary according to the rotation angle of the object: in this case, all bridges do not run parallel to the perimeters

<img width="1040" alt="Schermata 2020-05-11 alle 12 41 21" src="https://user-images.githubusercontent.com/14921654/81556564-d49c3b80-938a-11ea-8bb8-3a88d53aa15b.png">

This is how it would be correct to make a bridge

<img width="397" alt="Schermata 2020-05-11 alle 12 42 07" src="https://user-images.githubusercontent.com/14921654/81564056-7164d600-9397-11ea-856e-18cd024c2553.png">

Here we see the lack of parallelism between the bridges and the perimeters

<img width="650" alt="Schermata 2020-05-11 alle 12 42 29" src="https://user-images.githubusercontent.com/14921654/81564166-9b1dfd00-9397-11ea-9edf-d2477fee100e.png">

This is probably difficult to solve, as the starting point of the bridge filling is determined by the general slicing algorithm.

<img width="562" alt="Schermata 2020-05-11 alle 12 59 50" src="https://user-images.githubusercontent.com/14921654/81564349-e0422f00-9397-11ea-9284-6b2359d66cd1.png">

Simplify3D also suffers from the detachment of the bridges from the perimeters, but the angle is correct instead.

<img width="930" alt="Schermata 2020-05-11 alle 13 29 30" src="https://user-images.githubusercontent.com/14921654/81564468-1384be00-9398-11ea-886f-34a58dfd4220.png">

#### Project File (.3MF) where problem occurs
[bridge_angle_test_five_arms.3mf.zip](https://github.com/supermerill/Slic3r/files/4610038/bridge_angle_test_five_arms.3mf.zip)

**Comment by supermerill** [comment]
yes, it's not optimal and a bit difficult to improve.

It doesn't known where the periemters are. It has an area to fill and an area where it can anchor the bridge. With that, it tries many angle and keep the one where there are the "most area filled" with anchor. Maybe that's why sometimes it's not strait, to try to fill more area... have to add some test cases.
Problem with the gap, is that if it doesn't go just at the right width, the current algorithm isn't smart enough to left a gap in the middle and fill it with a little bridge/gapfill.

**Comment by liftbag** [comment]
> It's a big project to rewrite it.

I actually imagined it.
