### ISSUE TITLE
last linux version (nightly) don't start

### ISSUE THREAD

**Issue by salocain** [supermerill/SuperSlicer#2343]
### What happened?

the last build don't start.

because a new version i remove a config folder (.config/Superslicer) --> superslicer start , all things ok 

but...

next start ...nok --> erreur

 "[2022-02-10 16:16:36.918804] [0x00007f8d2bb9b5c0] [error]   /home/nico1/3d/SuperSlicer/bin/../resources/ui_layout/colors.ini"

i remove the config folder --> ok 
next start...nok --> etc

### Project file & How to reproduce

nothing

### Version

V2.4: merge fixes, fix gui tab, new overlapping peri threshold C/C++ Nigthly ubuntu-GTK3 #67

### Operating system

linux mint

### Printer model

tronxy x5sa + carte octopus + klipper

**Comment by supermerill** [comment]
check in the color.ui if you don't have a missing "carriage return"
It should be like that:
```
Unknown = C0C0C0
Internal perimeter = FFFF66
External perimeter = FFA500
Overhang perimeter = 0000FF
Internal infill = B1302A
Solid infill = D732D7
Top solid infill = FF1A1A
Ironing = FF6868
Bridge infill = 9999FF
Internal bridge infill = AAAADD
Thin wall = FFC000
Gap fill = FFFFFF
Skirt = 845321
Support material = 00FF00
Support material interface = 008000
Wipe tower = B3E3AB
Mill = B3B3B3
Custom = 28CC94
Mixed = 000000
Gui_color_very_dark = 0047C7
Gui_color_dark = 2172eb
Gui_color = 428dfd
Gui_color_light = 8bb9fe
Gui_color_very_light = 428cff
splash_screen_editor = cars.jpg
splash_screen_gcodeviewer = prusa-gcodepreview.jpg
Gui_plater = 3C3C3C
Gui_plater_grid = D0D0D0
```
