### ISSUE TITLE
last linux version can't save modification , only cancel buton

### ISSUE THREAD

**Issue by salocain** [supermerill/SuperSlicer#2347]
after my last post i start superslicer from scratch 

i configure the software and when i want to quit --> he ask for unsaved config but only cancel buton 

only solution --> do a save on each parametre

![Capture d’écran du 2022-02-10 18-26-30](https://user-images.githubusercontent.com/72736639/153464022-0682cf23-fbea-4572-9fd4-5bced28bab4c.png)

**Comment by tpikalek** [comment]
This happens also when switching profiles. There is only Transfer and Cancel. Discard and Save buttons are missing.
![Screenshot_20220214_134645](https://user-images.githubusercontent.com/6442143/153867083-27557666-8ddf-42f5-91d1-a9ad2cbc6caf.png)

**Comment by tpikalek** [comment]
Here is where the buttons are disabled if `__WXGTK__` is defined. I suppose only the cancel button should change based on the condition.
https://github.com/supermerill/SuperSlicer/blob/fbc5d5b8076e2072d6f8289921d9f62cfaaee1c8/src/slic3r/GUI/UnsavedChangesDialog.cpp#L871-L885
