### ISSUE TITLE
SuperSlicer_2.3.57.10 does not know first_layer_temperature_ in Gcode anymore

### ISSUE THREAD

**Issue by TravisWilder** [supermerill/SuperSlicer#2359]
### What happened?

M104 S[first_layer_temperature_[current_extruder]] 

Works in 2.3.57.9 but not in 2.3.57.10

### Project file & How to reproduce

use [first_layer_temperature_[current_extruder]]  GCODE start macro 

### Version

2.3.57.10

### Operating system

MacOS

### Printer model

Voron 2.4 / Voron 0.1

**Comment by supermerill** [comment]
When writing new macro, I advise you to use the new syntax and not the old legacy one (using []).
`[first_layer_temperature_[current_extruder]]` -> `{first_layer_temperature[current_extruder]}`
new syntax: https://help.prusa3d.com/en/article/macros_1775
