### ISSUE TITLE
Force retract on first layer

### ISSUE THREAD

**Issue by tome9111991** [supermerill/SuperSlicer#2361]
Hi
if the option in infill -> Only retract when crossing perimeters enable.
i have some missing retract on first layer durring travel over solid infill.

enable retract when crossing perimeters:
![enable](https://user-images.githubusercontent.com/57866234/153726504-1f17b198-b264-4ac0-ac2a-6957d2dbe4db.png)

disable retract when crossing perimeters:
![disable](https://user-images.githubusercontent.com/57866234/153726513-57ea5554-0397-4386-9431-252396c3d8d7.png)

Maybe there is a way to force retract on first layer only with enable this option?

file:
[Backplate_V3.zip](https://github.com/supermerill/SuperSlicer/files/8054433/Backplate_V3.zip)

**Comment by supermerill** [comment]
> if the option in infill -> Only retract when crossing perimeters enable.
i have some missing retract on first layer durring travel over solid infill.

what are the problematic travels? Can't really spot them.

**Comment by tome9111991** [comment]
for exemple on this travel:
![Screenshot 2022-02-13 114243](https://user-images.githubusercontent.com/57866234/153749578-f9ccc065-e3aa-40df-8771-9a6d50972900.png)

halfway I lose plastic and it sticks to the bed. (because no retract before this travel)
the solid infill then moves over the plastic on the bed and gets artifacts on the first layer

**Comment by supermerill** [comment]
Ok. A little 'not on first layer' choice next to " Only retract when crossing perimeters" should do the trick?

**Comment by tome9111991** [comment]
> Ok. A little 'not on first layer' choice next to " Only retract when crossing perimeters" should do the trick?
> 
Yes sounds good

> Only the first or the X first layers?
I think only the first layer is good.
But know maybe the value from bottom layer are good too

**Comment by tome9111991** [comment]
I was thinking about this issue.

A  'not on first layer' for the X first layers is better choise .

**Comment by supermerill** [comment]
> Maybe a Only retract when crossing perimeters" not for Solid infill is the best way.

so only retract when the travel only goes over some internal perimeters and sparse infill?
and stop if crossing an external perimeter, or a solid infill?

then i guess i can remove the "enforce on first layer", as it's mostly solid infill.

**Comment by tome9111991** [comment]
> > Maybe a Only retract when crossing perimeters" not for Solid infill is the best way.
> 
> so only retract when the travel only goes over some internal perimeters and sparse infill? and stop if crossing an external perimeter, or a solid infill?
> 
Yes, i need retract on external perimeter and solid infill.

**Comment by tome9111991** [comment]
> > I need an extra option to have retract on first layer and solid infill
> 
> but there is almost only solid infill on the first layer, why adding this constraint?

you are right.
only need for solid infill

**Comment by emailcraigs** [comment]
Will a force retract on first layer be implemented? I'm having same issue as OP.
