### ISSUE TITLE
Choose config folder location

### ISSUE THREAD

**Issue by robthide37** [supermerill/SuperSlicer#2366]
Would love to be able to set the config folder so that I can have multiple computers use a network drive and all share the same profiles or I can have some of my clients use folders on my shared drives so that I can maintain and update their profiles for them

**Comment by tome9111991** [comment]
Like https://github.com/supermerill/SuperSlicer/issues/1752#issuecomment-955749830 ?

**Comment by robthide37** [comment]
Sorry i dont know why i didnt see that when I looked if was already asked
