### ISSUE TITLE
Unable to slice a specific model (but PrusaSlicer 2.3.3 can)

### ISSUE THREAD

**Issue by mbravorus** [supermerill/SuperSlicer#2370]
### Version
2.3.57.7

### Operating system type + version
Windows 10 Pro

### Behavior
- a particular STL from this model - https://www.prusaprinters.org/prints/73388-martins-puzzle-rocket/files - namely, part13, is sliced incorrectly. It ends up with indefinite time to print and ultimately fails to print because of NaN values getting into G-code
* Load the STL (or project), slice
* Correct time estimation and valid G-code
* Invalid time estimation because of NaNs and failure to print
  * Screenshots: ![image](https://user-images.githubusercontent.com/593723/153759502-b98dcc7c-7577-4c9f-bcc5-9992f59e1524.png)
  

_Is this a new feature request?_
No

Additionally, I tried slicing the same file with PrusaSlicer 2.3.3 and it slices and prints correctly

#### Project File (.3MF) where problem occurs
[part_13.zip](https://github.com/supermerill/SuperSlicer/files/8055808/part_13.zip)

**Comment by Pavulon87** [comment]
2.3.57.5 - no problems
2.3.57.10 - no problems
2.4.58.0 - no problems
[part_13_0.2mm_PLA_ENDER3BLTOUCH_24m.gcode.zip](https://github.com/supermerill/SuperSlicer/files/8055916/part_13_0.2mm_PLA_ENDER3BLTOUCH_24m.gcode.zip)

**Comment by mbravorus** [comment]
Would you like me to provide the resulting G-code file? The offending piece seems to be:

```G1 E0.8 F2400
;TYPE:Gap fill
;WIDTH:-nan(ind)
G1 F-nan(ind)
G1 X109.656 Y119.658 E-nan(ind)
G1 X109.475 Y119.694 E-nan(ind)
G1 X109.293 Y119.73 E-nan(ind)
G1 X109.111 Y119.766 E-nan(ind)
;LAYER_CHANGE
;Z:18.6
;HEIGHT:0.200001
;BEFORE_LAYER_CHANGE
G92 E0
;18.6

**Comment by mbravorus** [comment]
Also, the other 13 numbered part files from the same project (linked in the original post above) do NOT produce this effect.

**Comment by Pavulon87** [comment]
> Would you like me to provide the resulting G-code file? The offending piece seems to be:
I included the gcode in the previous post.
Just update SuperSlicer as I can confirm this error in version 2.3.57.7
