### ISSUE TITLE
macOS ARM build broken

### ISSUE THREAD

**Issue by malcinator** [supermerill/SuperSlicer#2374]
### What happened?

After installing the latest macOS ARM release I get the message that its broken and I should move it to the trash

### Project file & How to reproduce

Download latest ARM release
Drag to Applications folder
Open application
Error displayed

I don't see the error when installing/upgrading on my MacBook Pro (Intel)

### Version

2.3.57.11

### Operating system

macOS M1 12.2.1

### Printer model

Prusa Bear BMG

**Comment by supermerill** [comment]
duplicate of #2162 and numerous other
