### ISSUE TITLE
Support with sheath around without moving elsewhere

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#2394]
It would be helpful that when printing sheath around where the support will be printed it made it without moving elsewhere.
If there are many supports lying around the bed, it creates too many unnecessary displacements, as the sheath and support can be printed in one go.
I understand that this can be corrected to let the sheath cool down first, but in many cases it is useless and greatly increases the printing time.
Tested with the latest SuperSlicer V2.3.57.

**Comment by supermerill** [comment]
fixed only for 2.4.58
