### ISSUE TITLE
2.4: assert "wxThread::IsMain()" failed in wxTimerImpl::Start(): timer can only be started from the main thread

### ISSUE THREAD

**Issue by matthewlloyd** [supermerill/SuperSlicer#2396]
### What happened?

Infrequently, this assert fails on uploading:

![image](https://user-images.githubusercontent.com/2041996/154117970-ae1a9216-1929-4efb-946b-49ae0b39766b.png)

### Project file & How to reproduce

1. Slice any plate and upload it to a network printer.
2. Repeat a dozen times or more until you hit the bug.

### Version

2.4.58.0

### Operating system

Windows 11

**Comment by supermerill** [comment]
can you test this nightly? https://github.com/supermerill/SuperSlicer/suites/5835274444/artifacts/196041452
it should resolve the issue.

**Comment by matthewlloyd** [comment]
> can you test this nightly? https://github.com/supermerill/SuperSlicer/suites/5835274444/artifacts/196041452 it should resolve the issue.

I merged your latest nightly_dev into my local build and tried to reproduce with a dozen uploads, and it seems fixed.

Thanks again!
