### ISSUE TITLE
Suppress warning about audio dll

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#2406]
I also tried to delete the SuperSlicer folder in Roaming, it regenerates it at the start but then exits immediately after the start screen.
If I can be useful and there is the possibility and activate a debug log to see what happens.

**Comment by robustini** [comment]
Same issue with the accel edition "2.4.58.0".

**Comment by RazorCopter** [comment]
same problem SuperSlicer_2.3.58.0_win64_220214

**Comment by MLiv79** [comment]
Same issue here, after the first run, superslicer won't start anymore

**Comment by tome9111991** [comment]
fix windows crash at startup nightly is starting.
bug got a white space:
![Screenshot 2022-02-18 181532](https://user-images.githubusercontent.com/57866234/154730774-bf6aecc9-67fc-4faa-9485-b3d8da594d30.png)

**Comment by robustini** [comment]
> fix windows crash at startup nightly is starting. but got a white space: ![Screenshot 2022-02-18 181532](https://user-images.githubusercontent.com/57866234/154730774-bf6aecc9-67fc-4faa-9485-b3d8da594d30.png)

Yes, there's white space.

**Comment by supermerill** [comment]
Found the problem. FIxed in nightly. Will update the labels soon.

**Comment by robustini** [comment]
> 

Thanks!
Please also check the add enforced support, if I insert them a block support appears instead.
And the drop down menu inside add block support is not selectable.

**Comment by robustini** [comment]
@supermerill is there a chance to remove this annoying starting waring?

![immagine](https://user-images.githubusercontent.com/3864712/154837865-979aa42e-ad0b-4d69-874b-061f607588c5.png)

**Comment by supermerill** [comment]
for the annoying starting warning, I'll see where I can add a var to disable it after first show.

**Comment by supermerill** [comment]
The modifier will be fixed (note that you can change their type afterwards)

**Comment by robustini** [comment]
> The modifier will be fixed (note that you can change their type afterwards)

If you go to "change type" it already appears as an enforcer, but in the list it is put as "Blocker-Box", not "Support-box".

![immagine](https://user-images.githubusercontent.com/3864712/154966849-f0e09b55-e6f9-460c-8cad-8969aa6108c6.png)

**Comment by supermerill** [comment]
yes, the position of the seam-enforcer was switched.

**Comment by robustini** [comment]
@supermerill the trick of the "NO_DLL_WARNING" dummy file only works if you open SuperSlicer from its executable, but if you open an STL from Windows with the "Open with" option it doesn't work, the message always appears.
So maybe that file should be placed in the folder inside Roaming, and the check done on that directory.

**Comment by supermerill** [comment]
ok

**Comment by robustini** [comment]
@supermerill I also report a problem with the fan, it does not respect what is set.
100% in the top layers and instead turned it off, 40% desired speed and put it at 86.

**Comment by supermerill** [comment]
> I also report a problem with the fan, it does not respect what is set.
100% in the top layers and instead turned it off, 40% desired speed and put it at 86.

please open a new issue with the project file for that.

**Comment by robustini** [comment]
The problem exists and it's boring, I have the ssd full of NO_DLL_WARNING, everywhere! ;-)

**Comment by supermerill** [comment]
the code has been moved. Now it's hidden via a preference entry.

**Comment by robustini** [comment]
@supermerill if the fixed version is the one compiled three hours ago now the situation has worsened, the warning always appears... :-(
