### ISSUE TITLE
View Speed doesn't react to M220

### ISSUE THREAD

**Issue by CuredPrusa** [supermerill/SuperSlicer#2421]
### Version
Version: 2.3.57.11
Build: SuperSlicer_2.3.57.11
Operating System: Windows
System Architecture: 64 bit
Windows Version: Windows 10 (build 19043), 64-bit edition

### Behavior
M220 is not shown on View Speed (color change in preview)
Can this be fixed? 

_Is this a new feature request?_

Bug or new feature?

**Comment by supermerill** [comment]
added via a8dd16 in 2.4
