### ISSUE TITLE
Weird layer shifting, but not in Cura ?

### ISSUE THREAD

**Issue by pjstam** [supermerill/SuperSlicer#2422]
Weird layer shifting, but not in Cura ?

**Bug description**
I got this box stl file and when slicing an printing it I get a layer shift at the same height. When I slice it in Cura it prints fine. I'm using the default .20 profile from SuperSlicer. I attached the files and it looks that the layer shifts at that litte bevel in the top box. So what I did was cut the top line off and also slicing it with SuperSlicer and Cura. Cura prints fine but SuperSlicer did not (again). I loaded boath gcode fiels generated by SS and Cura into a gcode viewer and they look the same. Anybody know where to start from now?

**To Reproduce**
1. Load the stl and slice with default profile...

**Screenshots**
![shift](https://user-images.githubusercontent.com/21356560/154819857-25193b4b-8817-4731-baaf-f1b41ed36951.jpg)

![top part cutoff](https://user-images.githubusercontent.com/21356560/154819870-e9feace3-0b8b-4544-a9c0-88f8816c348b.jpg)

![ss](https://user-images.githubusercontent.com/21356560/154819982-54636381-f687-472b-848c-ebd1d8d81375.png)

![fusion](https://user-images.githubusercontent.com/21356560/154820055-2fb2a880-8f1c-433b-9139-53753801f6b3.png)

**Additional context**
Using the latest SS version 2.3.57.11.

**Comment by supermerill** [comment]
Your printer probably hit something and layer shift. Try using the z-hop, or watch closely when printing to see what's it's hitting.

**Comment by pjstam** [comment]
> Your printer probably hit something and layer shift. Try using the z-hop, or watch closely when printing to see what's it's hitting.

**Comment by pjstam** [comment]
Well it looked like something was hitting the walls, played around with some z-hop settings which solved it. Thank you.
