### ISSUE TITLE
One perimeter on bottom layer doesn't work anymore 

### ISSUE THREAD

**Issue by LazaroFilm** [supermerill/SuperSlicer#2434]
### What happened?

I like to create a layer modifier to make the first layer single walled like the top layer. It used to work well, but on the last version, it keeps the walls and widens the infill, making them overlay
![Screen Shot 2022-02-21 at 2 24 34 PM](https://user-images.githubusercontent.com/18351100/155016030-14fc32b9-3827-4b71-85d7-e20fe012eec2.png)
.

### Project file & How to reproduce

Any file, create a height range modifier for the first layer then chose only one perimeter.

### Version

Final 2.3

### Operating system

MacOS 12.2.1

### Printer model

HEVO

**Comment by supermerill** [comment]
can't reproduce
![image](https://user-images.githubusercontent.com/6536403/155024625-2dad95dc-980d-4ad6-9dd1-2725bf2f4329.png)

your **project file** ?

**Comment by supermerill** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/6536403/155024819-6a1ab901-2d34-4f42-81c2-404d46ffd905.png)
Your **project file** please

**Comment by LazaroFilm** [comment]
Ok, looked deeper. It somehow is linked to the settings of my print profile. I still don't know which combination of settings created that issue, but switching to another print profile solved the issue.

**Comment by supermerill** [comment]
You don't want this combination of setting to be fixed?

**Comment by LazaroFilm** [comment]
I would, but I don't even know what the combination is. I think it has to do with reusing an old Config with the new version and some settings getting mixed up. Also, I just realized that you added a single perimeter on first layer option which works better and is faster to setup than my intricate layer modifier (thank you for that)

**Comment by LazaroFilm** [comment]
After cleaning all old configs and reinstalling, everything works.
