### ISSUE TITLE
Filament -> Cooling missing

### ISSUE THREAD

**Issue by intositeme** [supermerill/SuperSlicer#2445]
### Version
Version: 2.4.58.0
Build: SuperSlicer_2.4.58.0_2022-02-21

### Operating system type + version
Operating System: Windows
System Architecture: 64 bit
Windows Version: Windows 10 (build 22000), 64-bit edition

### Behavior
Filament Cooling section is missing. 
*  Load any 3mf file
*  Cooling section to be displayed in expert mode under Filament settings.
*  Cooling section is not being displayed
![Screenshot 2022-02-24 002741](https://user-images.githubusercontent.com/11328522/155362937-07eb9cc2-a2b6-4199-a26d-c5a642a5335b.png)

**Comment by supermerill** [comment]
fixed in Build: SuperSlicer_2.4.58.0_2022-02-23

**Comment by supermerill** [comment]
you can also delete the line `group:Behavior`  in the filament.ui file.

**Comment by intositeme** [comment]
> you can also delete the line `group:Behavior` in the filament.ui file.

Thanks, but where do I find it?

**Comment by supermerill** [comment]
resources/ui_layout
