### ISSUE TITLE
Drop down menu for modifier is wrong - Superslicer 2.4

### ISSUE THREAD

**Issue by K-Tett** [supermerill/SuperSlicer#2453]
## Problem:
Drop down menu to select modifier and support enforcer/blocker is not what it said.
- Add support blocker becomes seam position sphere
- Add support enforcer becomes support blocker
- Add seam position becomes support enforcer

## Expect:
Expected support blocker to give support blocker modifiers vice versa

NOTE: 
- Add negative volume, modifier and part works as intended

### Project file & How to reproduce

1. Right click on imported object
2. Select either support blocker, support enforcer or seam position
3. Output: as described above

### Version

Beta 2.4

### Operating system

windows 10 1904

**Comment by supermerill** [comment]
fixed in nightly
