### ISSUE TITLE
100% first layer height not allowed?

### ISSUE THREAD

**Issue by remizik** [supermerill/SuperSlicer#2459]
### What happened?

Hi,
I just updated to version 2.3.57.11
My profiles remained unchanged, great.
But I can't slice anymore with the error message : "first layer height can't be greater than max layer height"
These are the settings I think are relevant ?

![image](https://user-images.githubusercontent.com/24875086/155740498-7e9971cb-6179-4899-8b13-2a4367165e1b.png)

![image](https://user-images.githubusercontent.com/24875086/155740543-aed2233b-5324-43c2-a83b-4d8ff09e2bca.png)

I'm getting these messages : 

![image](https://user-images.githubusercontent.com/24875086/155740663-ec5bc76c-efb1-4514-98a4-e040f97c50a2.png)

Changing the "first layer height" to something like 80% works, but I want the first layer to be as thick as the others.
Setting the "first layer height" to 0.25**mm** works ! but I'd like to avoid having to change two text fields every time I want to change the layers thickness :)

### Project file & How to reproduce

Set the settings as described above

### Version

2.3.57.11

### Operating system

windows 10

### Printer model

ender 3

**Comment by liftbag** [comment]
Better to specify the measurement in mm rather than the percentage. The percentage applies to the nozzle diameter. If you have indicated a 0.4 nozzle in the printer tab, that 100% means 0.4mm.

**Comment by remizik** [comment]
> Better to specify the measurement in mm rather than the percentage. The percentage applies to the nozzle diameter. If you have indicated a 0.4 nozzle in the printer tab, that 100% means 0.4mm.

ohhh my bad I didn't read the description popup enough.. I thought it was a %age of the "base layer height" value right above..
oops!

Thanks a lot for your answer

**Comment by remizik** [comment]
I can't read.

**Comment by supermerill** [comment]
It's the % of base layer height in old PrusaSlicer (and old slic3r I think).
But that means you can't change the layer height. It's bad. That maybe why prusa just remove the % option for this field.
