### ISSUE TITLE
Unwanted supports on top of prints

### ISSUE THREAD

**Issue by M4rkusHartmair** [supermerill/SuperSlicer#2468]
### Version
2.3.57.11

### Operating system type + version
Arch Linux 5.16.11-arch1-1 x86_64

### Behavior
Superslicer generates supports on top of printed structures even though "Support on build plate only" is selected.

* _Steps needed to reproduce the problem:_
slicing with option "Support on build plate only" enabled.
occasionally it works as expected, most times there are at least some lines generated on top of printed structures.

* _Expected Result:_ 
No supports on top of printed structures. 
example: Circle of 2cm diameter on build plate 
=> cylindrical area with 2cm diameter over the circle free of any support structures.

* _Actual Results:_
Support lines are generated on top of printed structures, similar but NOT the same as when "Everywhere" is selected for supports.

![supports_problem_2](https://user-images.githubusercontent.com/88549873/155890905-e57dc77b-ea41-454f-9bb5-04ddee260edc.png)
![supports_problem](https://user-images.githubusercontent.com/88549873/155890907-a1020bbc-802f-4617-b308-5e0d95ac1072.png)

#### Project File (.3MF) where problem occurs
[support_problem.3mf.zip](https://github.com/supermerill/SuperSlicer/files/8149009/support_problem.3mf.zip)
(just renamed!)

**Comment by supermerill** [comment]
fixed in 2.4

**Comment by M4rkusHartmair** [comment]
Fix confirmed with Version 2.4.58.0 (AUR package aur/superslicer-prerelease-bin 1:2.3.58.0-1)
Supports on both examples now work as expected.
