### ISSUE TITLE
Filament shrinkage factor not affecting modifier objects

### ISSUE THREAD

**Issue by csdstudio78** [supermerill/SuperSlicer#2472]
### What happened?

Modifier objects are not pre-scaled/repositioned to align with filament shrinkage compensation factor.

### Project file & How to reproduce

Import object.  Add modifier object.  Set filament shrinkage to anything other than 100%.  (Set to 90% to exaggerate the issue).  See attached images for clarity.
![Shrinkage1](https://user-images.githubusercontent.com/66855631/156052384-c6c59efe-0ef6-43d4-ae5d-66f4591b6622.jpg)
![Shrinkage2](https://user-images.githubusercontent.com/66855631/156052393-da33e6bb-e961-40a0-8868-5be7b699b703.jpg)

### Version

2.3.57

### Operating system

Win 10

### Printer model

Prusa, voron...

**Comment by supermerill** [comment]
fix in next 2.4.58

**Comment by csdstudio78** [comment]
Thank you!
