### ISSUE TITLE
The lines of the bed can be seen on the object

### ISSUE THREAD

**Issue by mojamuto** [supermerill/SuperSlicer#2474]
### What happened?

![bug](https://user-images.githubusercontent.com/36079583/156444160-f757b132-aeea-4ec9-9692-d725898ce44d.gif)

The lines of the bed can be seen on the object
this problem was not in version 2.4.58.0, it is new in version 2.4.58.1

### Version

2.4.58.1 (last nightly) C/C++ Nigthly ubuntu-GTK3 & GTK2

### Operating system

Void Linux

### Printer model

Prusa Bear MK3

**Comment by liftbag** [comment]
It's an update from the latest nightly that shows the grid under the bed, but there seems to be a problem. Also present in macOS.

**Comment by tome9111991** [comment]
same on win10 58.1 RC
![Uploading Screenshot 2022-03-07 152811.png…]()

**Comment by supermerill** [comment]
weird, it should only do that for the voron0 (a new feature that had a buggy opengl side-effect).
I tried multiple printers and I don't have that.

**Comment by supermerill** [comment]
It's only on linux/ macos? or also on windows?

**Comment by liftbag** [comment]
> Oh, understood. It's also triggered for custom printer with a texture.

Can you guide me where to set to bed_with_grid = 0? I never set a Voron printer. I only have set a custom printer with Lerdge firmware.
The problem persists even with the latest nightly RC 2.4.1.

**Comment by supermerill** [comment]
> Can you guide me where to set to bed_with_grid = 0? I never set a Voron printer. I only have set a custom printer with Lerdge firmware.

for custom printers, it's a typo in 3dBed.cpp line 298, true instead of false.

**Comment by supermerill** [comment]
will be in nightly in some hours

**Comment by supermerill** [comment]
Did the nightly resolve the issue?

**Comment by liftbag** [comment]
> Did the nightly resolve the issue?

Yes, solved. Thanks!

**Comment by mojamuto** [comment]
solved thank you very much
