### ISSUE TITLE
Help!!! I can't open the project!

### ISSUE THREAD

**Issue by CuredPrusa** [supermerill/SuperSlicer#2481]
### Version
Version: 2.3.57.11
Build: SuperSlicer_2.3.57.11
Operating System: Windows
System Architecture: 64 bit
Windows Version: Windows 10 (build 19043), 64-bit edition

### Behavior
I can't open the project

Failed loading file "FMT3.4.5_SS.3mf" due to an invalid configuration.
Invalid value provided for parameter fill_pattern: 

Can someone help in soon? I have to work on it, but there's nothing I can do. 
 I'm willing to send the project via email, because I don't want it to stay publically here.

**Comment by mojamuto** [comment]
I think the bug is clear, you are using a 3mf that uses a fill type that does not exist in superslicer/prusaslicer.
That 3mf is created with another program, try to open it with cura for example.
without the file little else can help you

**Comment by CuredPrusa** [comment]
nope.
created by and saved in SS.
if you can somehow search the bug inside this 3mf I can send it to you via email. 
I can't even open it in Windows 3D software. There's error in file.

**Comment by supermerill** [comment]
If it's not protected, you can post a zip of it here. If not, you can send it to me via discord.

**Comment by CuredPrusa** [comment]
Thanks Meril! How to use discord?

**Comment by CuredPrusa** [comment]
Ok, i'm just opening the account right now....

**Comment by CuredPrusa** [comment]
Ok Meril, but now I'm really stuck. 
I have created my server on discord and I don't know what to do next to send you a file.

**Comment by CuredPrusa** [comment]
https://discord.gg/RF6eBRWC

the invitation to my server

**Comment by CuredPrusa** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/98842248/156925646-46b96c0c-eac0-48ab-9090-1ad984adbfca.png)

**Comment by CuredPrusa** [comment]
All parameters were without noticeable error, all settings were appropriately saved, then the project was saved.

**Comment by mojamuto** [comment]
I don't know if you have been able to enter discord yet but the superslicer server is located here: https://github.com/supermerill/SuperSlicer/issues/611#issuecomment-907833287

**Comment by CuredPrusa** [comment]
Thanks a lot mojamuto. 
I've just entered. 
Let's see what will happen....

**Comment by CuredPrusa** [comment]
Thank you Merill for soving this case for me!
