### ISSUE TITLE
Slicing shells/perimiters bugged

### ISSUE THREAD

**Issue by Exerqtor** [supermerill/SuperSlicer#2484]
### What happened?

Trying out 2.4.58.1 and i'm getting some weirdness with the slicing.
Everything looks good in the "Sliced preview" tab but when i "Gcode preview" some perimiters are randomly missing.

The bug manifests different depending on what Seam position is used.

Sliced with seam position aligned:
![SS-bug4](https://user-images.githubusercontent.com/41635644/157064872-7196bde6-910a-4d35-8e0d-2111e245a82d.png)

### Project file & How to reproduce

[Shape-Box-slicing_bug.zip](https://github.com/supermerill/SuperSlicer/files/8198820/Shape-Box-slicing_bug.zip)

### Version

2.4.58.1

### Operating system

Win10 x64

**Comment by Exerqtor** [comment]
Sliced with seam position random:
![SS-bug5](https://user-images.githubusercontent.com/41635644/157066642-8135b59c-1404-4a0c-9e74-7be38468b6e1.png)

Sliced with seam position rear:
![SS-bug6](https://user-images.githubusercontent.com/41635644/157066993-ab707e86-de69-4f28-a928-dc516a3395a7.png)

**Comment by supermerill** [comment]
you have checked `start_gcode_manual`
and you didn't add the relativev extrusion gcode.
add `{if use_relative_e_distances}M83 ; use relative distances for extrusion{endif}`

**Comment by Exerqtor** [comment]
I have all that within in my print_start.g macro, and it haven't posed
issues in the previous versions 🤔

man. 7. mar. 2022, 16:55 skrev Merill ***@***.***>:

**Comment by Exerqtor** [comment]
I have all that within in my print_start.g macro, and it haven't posed issues in the previous versions 🤔

**Comment by supermerill** [comment]
Oh right, i added something to add these lines for the gcode preview. I'll look why it's not active anymore

**Comment by nicedevil007** [comment]
This issue is gone with the latest nightly in my case, ty @supermerill
