### ISSUE TITLE
Dark mode causes crash on windows

### ISSUE THREAD

**Issue by stewcop23** [supermerill/SuperSlicer#2485]
**Bug description**
Experimenting in the new 2.4.58.1 pre-release and I tried to enable dark mode. immediately when I click *Enable Dark Mode* I get an error that says `Unhandled unknown error: terminating the application` immediately followed by `Internal error: boost::bad_any_cast: failed conversion using boost::any_cast`

**Project File**
[darkmodecrash.zip](https://github.com/supermerill/SuperSlicer/files/8199461/darkmodecrash.zip)
sorry for zip, i had to to upload to github

**To Reproduce**
1. Go to Configuration
2. Go to Preferences
3. Click on Colors and Dark Mode
4. Click on *Enable Dark Mode*
5. See error

**Screenshots**
first error:
![image](https://user-images.githubusercontent.com/37968460/157081736-43219f17-ec81-4c5e-9f95-844f52d51eea.png)
then immediately:
![image](https://user-images.githubusercontent.com/37968460/157082036-d47e9c86-218a-4b96-a6ee-4b3db44dd269.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 2.4.58.1
 - Anet a8 plus but I dont think that matters

**Comment by supermerill** [comment]
erf, yes.
To try the dark mode, change the `dark_color_mode = 0` to `dark_color_mode = 1` in your SuperSlicer.ini file (it's in help->show configuration folder)
