### ISSUE TITLE
Cannot switch to darkmode

### ISSUE THREAD

**Issue by foreachthing** [supermerill/SuperSlicer#2489]
### What happened?

Switching to darkmode causes crash:

```
 ---------------------------
SuperSlicer
---------------------------
Unhandled unknown exception; terminating the application.

---------------------------
OK   
---------------------------

```

![image](https://user-images.githubusercontent.com/10420187/157184637-50681014-a685-4cff-9b21-717da048819b.png)

### Project file & How to reproduce

1. Start SuperSlicer
2. Go to Preferences -> "Colors and Dark mode"
3. Enable Dark mode -> crash.

### Version

2.4.58.1

### Operating system

Win106x4

### Printer model

UM2

**Comment by foreachthing** [comment]
Dup! Sorry!

**Comment by supermerill** [comment]
should be fixed in nightly
