### ISSUE TITLE
Calibration issues

### ISSUE THREAD

**Issue by liftbag** [supermerill/SuperSlicer#249]
### Version
_2.2.50 commit f1c6cc602d2f97f5e454771c8086de3c4882c673_

_adding the temperature calibration (wip, had to add some pictures)._

### Operating system type + version
_win10_

### Behavior
* _Don't know if it's pc related but the dropdown box appears as follows on my computer. Either way, it works properly._
![Annotazione 2020-05-20 094030](https://user-images.githubusercontent.com/14921654/82421258-098e4980-9a81-11ea-8288-e4ca1f1a816e.png)

Staying on the subject, wouldn't it be preferable to start the temperature tower with the higher temperature? If the extruder become clogged due to a too low temperature, it would be better to happen on top than at the bottom.
Congratulations on the great, really great job on slic3r ++ supermerill.

**Comment by supermerill** [comment]
I happens also on my computer sometimes. I don't know why but it's maybe due to a weird interaction with layouts when the size is near the max. May be hard to diagnose.

> wouldn't it be preferable to start the temperature tower with the higher temperature? 

i was wondering what is the best option between the two, tanks for the input.

**Comment by liftbag** [comment]
Could the temp tower be customizable? For example, establish the start, end and step temperatures.

**Comment by liftbag** [comment]
Another thing. Looking at the Z slider in the temp tower slicing preview, I don't see the temperature changes. Will they have to be entered manually, or when the project will be finalized, the temperature changes will be automatically entered by the configuration assistant?

**Comment by liftbag** [comment]
The issue is not present in the build macos #68: Commit aea2f3b.
However, oddly the calibration menu does not work, producing the following error when starting the assistant (whatever it is).

<img width="1231" alt="Schermata 2020-05-20 alle 17 01 20" src="https://user-images.githubusercontent.com/14921654/82462530-fba9ea00-9abb-11ea-8046-e27436e37284.png">
Maybe _Contents_ is missing in the path?

**Comment by supermerill** [comment]
> Could the temp tower be parameterized? For example, establish the start, end and step temperatures.

The start can be parametrized, as the middle tempis the one you ahve in your current filament setting. I can do better, like adding an input to the number of previous & next temp, and the step, 

But the numbers are pre-made and only available for multiple of 5 starting by 180.
For the step input, maybe i can restrict to 5/10/15/20 ? do you think it's useful to have a 2.5 degree step?

For now i have to print some, test and write some explanations.

> I have just checked the gcode and verified that the temperature changes are already correctly entered. Unfortunately, the preview extrusion temperatures cannot be visually checked.

yeah, i was lazy and just modify the after layer gcode sneakily. (you have to reset it if you want to print somethgin after it.
I forgot about the Z slider, will change for that.

> However, oddly the calibration menu does not work, producing the following error when starting the assistant (whatever it is).

This feature think that the resources directory is inside the slic3r executbale directory (current location). It works in windows, but maybe it's different in macos, true. Have to search it instead of blindly expect it, and display an error if not found.

**Comment by liftbag** [comment]
> For the step input, maybe i can restrict to 5/10/15/20 ? do you think it's useful to have a 2.5 degree step?

2.5 degree step is useless in my opinion.

> I forgot about the Z slider, will change for that.

Ok.

**Comment by liftbag** [comment]
> This feature think that the resources directory is inside the slic3r executable directory (current location). It works in windows, but maybe it's different in macos, true. Have to search it instead of blindly expect it, and display an error if not found.

But the executable directory has those resources. The path is: /Applications/Slic3r++.app/Contents/resources/calibration/

**Comment by supermerill** [comment]
prusa has already made the util function to get the good path, i'll use that.

**Comment by supermerill** [comment]
all that (but the first issue) should be on this nightly build.

**Comment by liftbag** [comment]
> all that (but the title issue) should be on this nightly build.

Wow! Everything works! Thanks :)

**Comment by liftbag** [comment]
Hello @supermerill: the resources for the Bridge pattern tuning and Ironing pattern tuning cannot be loaded again on macOS version of the latest nightly "external_perimeter_cut_corners setting".
This time the wizard is correctly loaded, but not the models to generate the objects for testing.

<img width="909" alt="Schermata 2020-05-22 alle 22 05 06" src="https://user-images.githubusercontent.com/14921654/82705645-5425e680-9c78-11ea-9095-0d7be774c4cc.png">

**Comment by supermerill** [comment]
erf, a bad copy-cut made before the fix.. easy fix.

**Comment by liftbag** [comment]
> erf, a bad copy-paste made before the previous fix.. easy one.

Bridge pattern tuning still need to be fixed, on macOS and win10.

**Comment by liftbag** [comment]
In win10 I managed to load the Bridge pattern tuning after deleting the configuration folder, starting from scratch and loading the saved config bundle.

**Comment by supermerill** [comment]
what's the errors you had?

**Comment by liftbag** [comment]
> what's the errors you had?

I understood why I had errors that seemed random to me. It only happens when you want to load the bridge flow test with 2.5 steps.

<img width="1036" alt="Schermata 2020-05-23 alle 22 28 05" src="https://user-images.githubusercontent.com/14921654/82739974-bb10d180-9d44-11ea-9cbf-a38976774599.png">
