### ISSUE TITLE
ui_layout is overwritten at startup

### ISSUE THREAD

**Issue by foreachthing** [supermerill/SuperSlicer#2490]
### What happened?

* `ui_layout = ANYTHING_HERE` gets overwritten with `ui_layout = Standard` after every restart. Except, when changing the settings to `ANYTHING_HERE` and requested restart. Then it works. Restarting application "manually" resets settings.

### Project file & How to reproduce

1. Change UI-Layout to non-Standard.
2. Let it restart.
3. Restart manually and check settings.

### Version

2.4.58.1

### Operating system

Win 10 x64

### Printer model

UM2

**Comment by supermerill** [comment]
can't reproduce.
can you send me your conf folder?

**Comment by foreachthing** [comment]
As raw as it gets: [SuperSlicer.zip](https://github.com/supermerill/SuperSlicer/files/8206287/SuperSlicer.zip)

I still can reproduce, even after a complete deletion of the profile folder.
PS: After deleting the SuperSlicer profile folder, SuperSlicer wouldn't start anymore.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/10420187/157241221-76a78c0f-0396-4862-82e3-3bb38dcb7ace.png">

**Comment by supermerill** [comment]
launched a nightly build with the fixes.

**Comment by foreachthing** [comment]
Awesome!! 👍🏼 
Thanks a bunch!
