### ISSUE TITLE
Expert mode lacks some features present in Advanced mode

### ISSUE THREAD

**Issue by macchinette** [supermerill/SuperSlicer#2491]
### What happened?

Hi Merill, I have seen that the settings for the seam position are different between the modes Simple / Advanced / Expert.

For the seam position, I would have expected that in Simple mode there was no custom function as it is missing the settable fields.

For the seam position, I would like all the functions of the Advanced mode to be in Expert mode and handled in the same way.

I hope it is possible to do.
Below photos to understand.

Thank you

### Project file & How to reproduce

Simple mode
![Pos Giunzione Semplice](https://user-images.githubusercontent.com/79080486/157232342-63b1bb0b-4648-4181-ad56-bca5026d17a3.png)

Advanced mode
![Pos Giunzione Avanzato](https://user-images.githubusercontent.com/79080486/157232399-14c3d864-91bd-40f7-b5c0-d8fe0792199d.png)

Expert mode
![Pos Giunzione Expert](https://user-images.githubusercontent.com/79080486/157232446-7dcbc40c-a315-4121-a469-d265988fd5dd.png)

### Version

SuperSlicer_2.4.58.1_2022-03-07

### Operating system

Windows 10 Pro 21H2

### Printer model

Anycubic I3 Mega S

**Comment by supermerill** [comment]
Corners and nearest are just pre-defined cost. 
"Personalized" is a way to say "it's not a pre-defined cost, something else".

In expert, as you're an expert, you can enter the cost yourself and you don't need these pre-defined helpers, that's the thought behind it.

the tooltip is a bit succinct...

It's not set in stone, more like an experiment. Tell me what I should do to avoid confusion.

**Comment by macchinette** [comment]
> Corners and nearest are just pre-defined cost. "Personalized" is a way to say "it's not a pre-defined cost, something else".
> 
> In expert, as you're an expert, you can enter the cost yourself and you don't need these pre-defined helpers, that's the thought behind it.
> 
> the tooltip is a bit succinct...
> 
> It's not set in stone, more like an experiment. Tell me what I should do to avoid confusion.

You are right that it is in Expert mode, but to explain the function in detail it would be complicated to do it with a tooltip to be translated into various languages, I would make the setting as in Advanced mode, at least with the two default settings corners and nearest you could have an example of how to use the custom setting.
In addition I ask you how the two cost fields work, must the total always have to be 100?
Because I tried to use it, but didn't understand the function much.
Thank you

**Comment by supermerill** [comment]
In addition I ask you how the two cost fields work, must the total always have to be 100?

if you put 0 to cornern it won't try to hide the seam in a corner.
if you put travel to 0 it will disregard the travel time from the last point (often in infill for the external perimeter) and the seam.

if they aren't 0, it will choose a compromize: a corner not too far away.

There is no upper limit. Some other weight exists and can be trivialized if you put very hight cost here. It's made to have something in the 50-100 range.

**Comment by macchinette** [comment]
> In addition I ask you how the two cost fields work, must the total always have to be 100?
> 
> if you put 0 to cornern it won't try to hide the seam in a corner. if you put travel to 0 it will disregard the travel time from the last point (often in infill for the external perimeter) and the seam.
> 
> if they aren't 0, it will choose a compromize: a corner not too far away.
> 
> There is no upper limit. Some other weight exists and can be trivialized if you put very hight cost here. It's made to have something in the 50-100 range.

Thank you for the explanation, I will try to make good use of it, however I think it is more intuitive to have the same management of Advanced if it does not bother you too much.

Thank you

**Comment by supermerill** [comment]
np, thanks for the feedback
