### ISSUE TITLE
Send to Printer: wxWidgets Debug Alert

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#2492]
### What happened?

I tried to "send to printer" "upload and print" and got this warning:

![image](https://user-images.githubusercontent.com/12439543/157295104-f8ade010-1199-49a9-bae2-45e23fbb863a.png)

The command was executed successfully though.

### Project file & How to reproduce

[Small Handle.3mf.txt](https://github.com/supermerill/SuperSlicer/files/8208471/Small.Handle.3mf.txt)

### Version

2.4.58.1

### Operating system

Windows 10 x64

**Comment by supermerill** [comment]
can you test this nightly? https://github.com/supermerill/SuperSlicer/suites/5835274444/artifacts/196041452
it should resolve the issue.
