### ISSUE TITLE
Infill in the place of Perimeter

### ISSUE THREAD

**Issue by dingyifei** [supermerill/SuperSlicer#2496]
### What happened?

Super slicer infill behaves differently compared to Prusa slicer, where SS has this layer of infill replacing the entire perimeter when top/bottom is removed. The following is in SS:
![image](https://user-images.githubusercontent.com/15083013/157314555-16080c42-1199-41bd-bd34-7e14c9ef5c19.png)
The following is in Prusa slicer with the same 3MF file (minor adjustments on printer settings):
![image](https://user-images.githubusercontent.com/15083013/157314704-7dd44ee3-c279-4b8c-b0f3-b8f43a7bbb4b.png)

### Project file & How to reproduce

[13Pro Case.zip](https://github.com/supermerill/SuperSlicer/files/8209230/13Pro.Case.zip)

Slice without top/bottom and several loops of infill

### Version

I have tested last 4 prerelease/release, all have the same issue.

### Operating system

Fedora 35

### Printer model

Prusa MK3S+

**Comment by neophyl** [comment]
You have Perimeters & Shell>Quality>One One Perimeter>On Top surfaces enabled.  Turn it off and it slices similar to PS.
That option and setting doesn't exist in PS and its turned on by default in SuSi.  

Whenever there is an issue like this there are always certain settings I check, single perimeter is one of them as it often seems to cause weird edge cases.  About as often as Detect thin walls does in PS.

**Comment by dingyifei** [comment]
> Whenever there is an issue like this there are always certain settings I check, single perimeter is one of them as it often seems to cause weird edge cases. About as often as Detect thin walls does in PS.

Thank you! it seems to be the cause. I guess it's just a side effect of single perimeter lol
