### ISSUE TITLE
Option to show/remove Grid from the objects

### ISSUE THREAD

**Issue by kanawati975** [supermerill/SuperSlicer#2497]
I'm using the Release 2.4.58.1 on Windows 10 and it's faster and less crashes when slicing multiple objects.

However, there is a back Grid showing on the objects, and it's kind of annoying if one would like to examine Layers.
Even when using a texture on the build plarform does not hide this Grid.

I hope that there is an option to show/hide this grid

![Screenshot 2022-03-08 211616](https://user-images.githubusercontent.com/60808289/157318504-44af4920-5f32-40a5-b3a3-357aea3ffff0.jpg)

![Screenshot 2022-03-08 211656](https://user-images.githubusercontent.com/60808289/157318587-1002f3be-8d61-4157-8c95-e87fe17baa1b.jpg)

![Screenshot 2022-03-08 212408](https://user-images.githubusercontent.com/60808289/157318864-709cd462-4720-45bb-a3ff-90c328fbda9c.jpg)

**Comment by tome9111991** [comment]
Hi.
Try the latest nigjtly
Should fix this bug

**Comment by kanawati975** [comment]
Great!
Thank you <3
