### ISSUE TITLE
Error while exporting config-bundle and using a printer with Klipper and firmware retraction

### ISSUE THREAD

**Issue by bigsubgit** [supermerill/SuperSlicer#250]
### Version
2.2.49

### Operating system type + version
macOS Catalina 10.15.4

### 3D printer brand / version + firmware version (if known)
A custom ender3 with klipper fw

### Behavior
If you having a klipper 3d printer and you use firmware retraction, when you export config-bundle.ini you have this error.
The problem is only exporting config-bundle, while the use of G10/G11 command is correct; they are correctly used on g-code files exported.

![Screenshot 2020-05-20 at 15 15 17](https://user-images.githubusercontent.com/40430435/82455635-728eb500-9ab3-11ea-9a9f-e3abed1d7264.png)
![Screenshot 2020-05-20 at 15 14 41](https://user-images.githubusercontent.com/40430435/82455644-7589a580-9ab3-11ea-8e73-a428b564d049.png)

**Comment by supermerill** [comment]
i'll add klipper on the list of authorized firmware.

**Comment by bigsubgit** [comment]
Hello, @supermerill the new build works correctly. 
Many thanks.
