### ISSUE TITLE
Overextrusion on Brim for wipe tower

### ISSUE THREAD

**Issue by mann1861** [supermerill/SuperSlicer#2501]
### What happened?

Wipe tower brim prints at same speed as normal brim but at a higher volumetric flow rate resulting in severely over extruded brim which for me then curled upwards removing wipe tower from bed
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/80097034/157449169-3ba4f6f7-0473-4718-a18f-34fea0765256.png">

[2color_treefrog_small_solid (1).zip](https://github.com/supermerill/SuperSlicer/files/8214961/2color_treefrog_small_solid.1.zip)
![20220309_131922](https://user-images.githubusercontent.com/80097034/157449683-c6b11679-cae8-4c16-b794-f4b5c7095117.jpg)

![20220309_131915](https://user-images.githubusercontent.com/80097034/157449694-fbe47910-4656-48a7-a645-675a267413c3.jpg)

### Project file & How to reproduce

[2color_treefrog_small_solid (1).zip](https://github.com/supermerill/SuperSlicer/files/8214961/2color_treefrog_small_solid.1.zip)

### Version

2.4.58.1

### Operating system

Windows 10

**Comment by Kidabah** [comment]
Having exactly the same issue as you.
