### ISSUE TITLE
Strange behavior when resizing a modifier 

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#2504]
### What happened?

As you can see in the video I link when resizing a modifier it doesn't stay in the same position as it should.

### Project file & How to reproduce

[FUSO05.zip](https://github.com/supermerill/SuperSlicer/files/8215773/FUSO05.zip)

https://user-images.githubusercontent.com/3864712/157470695-c7de250f-1b97-45fe-a25e-62795825bebc.mp4

### Version

2.4.58.1 nightly of today

### Operating system

Windows 10 Pro x64

### Printer model

SP

**Comment by robustini** [comment]
There is also another very boring thing, when you resize the cylinder by taking it from the orange cubes, the ones on the corners, you not only resize the diameter but also the height.
It would be useful if it dimensioned only the diameter, leaving the height unchanged.

https://user-images.githubusercontent.com/3864712/157615748-58f8b0e5-87af-414c-92d8-37ad35d90d68.mp4

**Comment by supermerill** [comment]
Also, when the main object is resized, the parts/modifier resize text boxes won't work properly, as it's scaled by the root object.

**Comment by neophyl** [comment]
Please don't change the orange resize function.  It does exactly what its supposed to be doing.  The orange handles resize the object globally, the others just resize a specific axis.

**Comment by supermerill** [comment]
> Please don't change the orange resize function. 

I think that the problem is more the translation than the scaling with the 3d handles.

**Comment by robustini** [comment]
Fixed in the nightly, thanks!

**Comment by supermerill** [comment]
I didin't do anything. Maybe resolved by the prusa 2.4.1.

**Comment by supermerill** [comment]
oh, no that I think of it, it's probably because of 4c3749b1
