### ISSUE TITLE
Minimum  filament extrusion length in skirt option do not work

### ISSUE THREAD

**Issue by TerrorzwergOlli** [supermerill/SuperSlicer#2505]
### What happened?

Minimum  filament extrusion length in skirt option do not have any impact on number of loops.

### Project file & How to reproduce

load stl -> change Minimum  filament extrusion length in skirt option  to a slightly bigger value -> slice. The skirt only have the minimum  number of loops

### Version

2.3.57.11

### Operating system

Windows 10

### Printer model

Voron 2.4

**Comment by supermerill** [comment]
works for me

**Comment by neophyl** [comment]
Works for me too.  Have you considered that the length of one loop could be far far longer than the minimum filament length ?  Without seeing your project and what you are slicing to put a skirt around its impossible to tell but you might have to increase the length by a lot to see more than 1.

**Comment by supermerill** [comment]
A skirt loop is ~135mm, by counting the grid cells.

> how can I add a project file?

zip it or rename it so it's accepted by github. Then grad&drop it here.

**Comment by TerrorzwergOlli** [comment]
did the way it is calculated change? in  2.3.57.9 it looks like the lenghts is calculated according to the tooltip
![image](https://user-images.githubusercontent.com/89738323/157924552-7f79a587-497b-4c28-a4f2-69a67029597a.png)
now it takes the lenght of  the extruded line. If I rate it like that, it works like intended. So maybe only a bit missleading tooltip now because the behaviour has changed (but it is no game breaker)

**Comment by supermerill** [comment]
oh, right, I misunderstood it.
