### ISSUE TITLE
Cutting corners seems broken

### ISSUE THREAD

**Issue by liftbag** [supermerill/SuperSlicer#251]
### Version
_2.2.50 nightly build " external_perimeter_cut_corners setting" (Commit 77468ba)_

### Operating system type + version
_macOS Catalina 10.15.4_

### Behavior
* _I was curious to test the new feature, but it seems broken_
* _Steps needed to reproduce the problem_
  * _enter any non-zero value in "Cutting corners"_
  * _hit Slice now_
* _Expected Results_
  * _it's not clear to me, it's a new feature. I imagined to have a normal slice, and to be able to visualize the changes in the corners with the "volumetric flow rate view"_
* _Actual Results_
  * _The slice is broken into multiple areas on top layers. Vertical corners are cutted, but not homogeneously. Nothing seems to change by changing the value in "Cutting corners", just enter any value other than zero to always get the same result._

Cutting corners set to 0
<img width="984" alt="Schermata 2020-05-22 alle 23 30 15" src="https://user-images.githubusercontent.com/14921654/82710979-7b82b080-9c84-11ea-90ff-db3c798e075d.png">

Cutting corners set to 1%
<img width="984" alt="Schermata 2020-05-22 alle 23 30 27" src="https://user-images.githubusercontent.com/14921654/82711007-8b01f980-9c84-11ea-8658-67faac16c367.png">

Cutting corners set to 100%
<img width="984" alt="Schermata 2020-05-22 alle 23 30 44" src="https://user-images.githubusercontent.com/14921654/82711033-9c4b0600-9c84-11ea-8604-a0a8a5b42ead.png">

#### Project File (.3MF) where problem occurs
[xyzCalibration_cube.3mf.zip](https://github.com/supermerill/Slic3r/files/4670483/xyzCalibration_cube.3mf.zip)

**Comment by liftbag** [comment]
I had the doubt that, somehow, the new feature exalted a mesh problem, but tried with another mesh, the result is similar.

<img width="915" alt="Schermata 2020-05-22 alle 23 40 16" src="https://user-images.githubusercontent.com/14921654/82711503-e2ed3000-9c85-11ea-9d8c-57cd12aa5006.png">

**Comment by supermerill** [comment]
yeah, i didn't had the time to test it, i just pushed it to be able to compile it on an other pc.

**Comment by supermerill** [comment]
should be fixed, but not tested yet. Also the fail macos build is a lie.

**Comment by liftbag** [comment]
> should be fixed, but not tested yet. Also the fail macos build is a lie.

I'll wait for your test, because I didn't see any change when enabled.

**Comment by supermerill** [comment]
Well, you need a big nozzle and very precise flow to be able to see anything. It's a 5% flow difference on a very little distance.
