### ISSUE TITLE
wxWidgets Debug Alert timerimpl.cpp(60) timer can only be started from the main thread [in tread 330]

### ISSUE THREAD

**Issue by FlatEarthDave** [supermerill/SuperSlicer#2512]
### What happened?

This error:
![image](https://user-images.githubusercontent.com/26616994/157801518-69416b61-b92a-4b72-a7d3-f948dac50ff3.png)

### Project file & How to reproduce

Calibration >> bridge flow calibration >> test flow >> G>

### Version

2.4.58.1

### Operating system

windows 11

### Printer model

custom corexy with klipper

**Comment by supermerill** [comment]
Can't reproduce.
Is it easy to reproduce on your side or it's really random?
Do you use the "background processing"?
I may have to send you a special version to have a better log of the error.

**Comment by FlatEarthDave** [comment]
Yes it is extremely easily reproduced. I had the same issue with the initial 2.4 beta release, so I went back to 2.3.57 and it went away. It doesn't seem to affect the print, but it does cause a random crash.

Also, it looks like 2.4 doesn't respect the "complete each object", or at least it didn't for the bridging tests, even though the option was checked.

I would be happy to test a different version to help with debugging it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by julianschill** [comment]
I experience the same when uploading to Moonraker: 
![image](https://user-images.githubusercontent.com/13122110/159122131-395a703a-8fad-4eb6-9b0a-eccd0531059a.png)
 2.4.58.1 Nightly
 Background Processing switched off.
 
![image](https://user-images.githubusercontent.com/13122110/159122188-5ee3e60e-9329-48fd-9e0f-5583232bdff9.png)

**Comment by FlatEarthDave** [comment]
It actually went away after a few times and it hasn't reappeared. I didn't change any settings or builds.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by supermerill** [comment]
can someone use this debug build? the error message should be better.
https://github.com/supermerill/SuperSlicer/suites/5802201336/artifacts/193999699

**Comment by julianschill** [comment]
Tried with the debug build and got this message: 
![image](https://user-images.githubusercontent.com/13122110/160281927-5a5ca638-fef8-4876-90b2-c58588eabf3d.png)

**Comment by supermerill** [comment]
can someone test this nightly? https://github.com/supermerill/SuperSlicer/suites/5835274444/artifacts/196041452
it should resolve the issue.
