### ISSUE TITLE
Elephants foot compensation feature

### ISSUE THREAD

**Issue by ModMike** [supermerill/SuperSlicer#2515]
Would it be possible to build an elephants foot compensation feature to reduce the to use rafts? There may be betters ways to do it than I am envisioning but this is what I was thinking:

Setting 1: Number of **Layers** to apply the compensation to

Setting 2: **Angle** to apply

Setting 3: Not necessary but could be useful, **Shape** of transition, curved or straight.

**Comment by liftbag** [comment]
Elephant foot compensation is named XY first layer compensation in SuperSlicer. You have to put negative value to create an effective elephant foot compensation. Also, the Number of layers is already present, and the angle it's a consequence of the layer height, height in layers, and the compensation value.

<img width="985" alt="Schermata 2022-03-11 alle 17 48 26" src="https://user-images.githubusercontent.com/14921654/157911242-c2852a7d-0154-463c-87f0-da49ed2b8d02.png">

**Comment by ModMike** [comment]
Don’t I feel like a moron. Thanks for the lesson!
