### ISSUE TITLE
Gcodeviewer won't start

### ISSUE THREAD

**Issue by tome9111991** [supermerill/SuperSlicer#2519]
### What happened?

Hi on latest Nightly or Nightly from few days before.
superslicer-gcodeviewer.exe is not starting.
same issue on Superslicer.exe in File -> G-Code Preview.
Windows 10 is short loading but nothing happend.

### Project file & How to reproduce

.

### Operating system

Windows 10

### Printer model

E3v2

**Comment by tirasec** [comment]
Me too, same problem : W11-64 Pro
