### ISSUE TITLE
Nightly (Windows) - The number of top layers is not always respected 

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#2521]
### What happened?

The number of top layers is not always respected.
In some conditions it removes a layer from those declared, for no apparent reason.

### Project file & How to reproduce

3 top layers declared and at that point it generates only 2.
Even removing the modifier the same thing happens.
At the top it generates 3 instead, as it should.

![immagine](https://user-images.githubusercontent.com/3864712/158027623-2ac0e99b-ae16-4cf2-8173-0aaea5770b85.png)

[FUSO05.zip](https://github.com/supermerill/SuperSlicer/files/8237994/FUSO05.zip)

### Version

2.4.58.1

### Operating system

Windows 10 Pro x64

### Printer model

SP

**Comment by supermerill** [comment]
your modifier here modify the top layers to 2

**Comment by robustini** [comment]
Damn sorry!
