### ISSUE TITLE
Can't remove solid top layers

### ISSUE THREAD

**Issue by 53784** [supermerill/SuperSlicer#2522]
**Bug description**
I can't print a model with 0 top layers, unless i also set bottom solid layers to 0 aswell.

**Expected behavior**
I should be able to set 0 top solid layers, and 4 bottom solid layers for example, and i can't.

!!>> Project File <<!!
[TopLayers.zip](https://github.com/supermerill/SuperSlicer/files/8238650/TopLayers.zip)

**To Reproduce**
1. Import model
2. Set 0 top Solid Layers to 0, and bottom solid layers to 4 in the perimeters & shell on the print settings tab
3. Slice

**Screenshots**
![1](https://user-images.githubusercontent.com/67032634/158038105-24e24306-a0c6-4d84-becd-b6279ec436ef.png)
![2](https://user-images.githubusercontent.com/67032634/158038106-49de6df7-7507-4d3e-aed9-36374a784b71.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.3.57
 - Heavily modified Anet A8

**Additional context**
I don't know if this is a bug, or if it's another setting that i should check out. I spent hours already looking for different settings that could cause this, but found nothing.

**Comment by supermerill** [comment]
taht's the bottom layer so see.
split your cube: you'll see it's hollow.
