### ISSUE TITLE
inconsistent (with vertical gaps ) support generated

### ISSUE THREAD

**Issue by netweaver1970** [supermerill/SuperSlicer#2525]
### What happened?

in the latest beta release, 2.58.1, I can see vertical gaps in generated support. Not always steady going up from the buildplate to the object.
I've indicated the gaps with yellow marker.
![image](https://user-images.githubusercontent.com/18028618/158058727-276e83ae-0dc5-4d7d-8279-b7d335491f7a.png)

Even better visible on the 2nd image:
![image](https://user-images.githubusercontent.com/18028618/158058924-de210388-9e26-489b-a39f-5171b91cb052.png)

Supports are jumping around :) 

### Project file & How to reproduce

[support gaps.zip](https://github.com/supermerill/SuperSlicer/files/8239475/support.gaps.zip)

### Version

2.4.58.1

### Operating system

WIndows 10

### Printer model

Voron 2.4 with Mantis

**Comment by supermerill** [comment]
Comes from the prusaslicer 2.4 changes.
Complicated to fix.
Can you ask in the prusaslicer github?

**Comment by netweaver1970** [comment]
As per prusaslicers comment on my issue: works as designed 🤦
