### ISSUE TITLE
Failure when nozzle_diameter = 0.15

### ISSUE THREAD

**Issue by Hashan0** [supermerill/SuperSlicer#2528]
### What happened?

Failure when nozzle_diameter < 0.195m
![Unbenannt-1](https://user-images.githubusercontent.com/101518551/158072128-68286819-a801-445d-aa11-0b3b4d3a8da7.jpg)
![Unbenannt-2](https://user-images.githubusercontent.com/101518551/158072129-a5b77f95-72cb-433e-aa1c-466f62633368.jpg)
m

### Project file & How to reproduce

[config.zip](https://github.com/supermerill/SuperSlicer/files/8240275/config.zip)

### Version

2.4.58.1

### Operating system

windows 10

### Printer model

Custom

**Comment by supermerill** [comment]
Can't reproduce with your config.
Can you post you **project file**?

**Comment by Hashan0** [comment]
Creating Custom or others Printer
nozzle_diameter = 0.15 or 0.1
layer_hight = 0.05
first_layer_height = 50%
all other parameters are standard

Open Calibration cube
Change any parameter -> Failure:   Flow::spacing() produced negative spacing. Did you set some extrusion width too small?

config file:
[config.zip](https://github.com/supermerill/SuperSlicer/files/8240749/config.zip)
project file:
[Calibration cube.zip](https://github.com/supermerill/SuperSlicer/files/8240746/Calibration.cube.zip)
