### ISSUE TITLE
Unwanted solid infill causing bad overhangs

### ISSUE THREAD

**Issue by PuddingBaer91** [supermerill/SuperSlicer#253]
Hi,

I found out that if you set a high number for bottom layers (for example 10) then the whole model will be filled at some places with solid infill. This is causing bad overhangs.

![5BottomLayer-Slicer](https://user-images.githubusercontent.com/61384794/82755969-6cf8de00-9dd7-11ea-9f4d-907bc4f6bc89.PNG)
![5BottomLayer-Print](https://user-images.githubusercontent.com/61384794/82755974-75511900-9dd7-11ea-82ab-50b335c4b367.jpg)

![1BottomLayer-Slicer](https://user-images.githubusercontent.com/61384794/82755971-708c6500-9dd7-11ea-9b4c-c472f3c962f2.PNG)
![1BottomLayer-Print](https://user-images.githubusercontent.com/61384794/82755975-75e9af80-9dd7-11ea-826e-85c62f8500a7.jpg)

![0BottomLayer-Slicer](https://user-images.githubusercontent.com/61384794/82755972-72eebf00-9dd7-11ea-9eeb-3e9df3220457.PNG)
![0BottomLayer-Print](https://user-images.githubusercontent.com/61384794/82755976-76824600-9dd7-11ea-96d9-a8be4a96d94d.jpg)

As you can see this is sliced with Ideamaker but it happens on all the other slicers also. If you set bottom solid layers to 5 both overhangs will print bad. If you set it to 1 only one side will be bad because Ideamaker adds some more solid fill to the left side.. (May Slicer handels this in another way)
If you set the bottom layers to 0 the overhangs will printed fine because no solid fill at the overhang section.
For me i only want solid bottom layers beginning from z=0. For example if you set solid bottom layers to 5 it should stop with them after the 5 FIRST layers

**Comment by supermerill** [comment]
can you post the project file? (.3mf) zipped here?

**Comment by PuddingBaer91** [comment]
Yes i can. I will so later if i am on my pc. In the cura discussion i mentioned above we found the solution for cura. In cura you are able to set initial bottom layers and bottom layers. If you set bottom layers to 0 and initial bottom layers to ur desired value it will work as i want.

**Comment by 64Florian** [comment]
For @supermerill 
-> This thread was discussed in Ultimaker/Cura#7817

**Comment by supermerill** [comment]
If you want a manual solution, you can create a layer modifier and set solid bottoms layers to 0 in it.

**Comment by PuddingBaer91** [comment]
yeah good idea with modifier but may you can do it like cura with **initial** bottom layers option
project file (.3mf) zipped:
[Extrudr-Bunny2017-No_Sunglass.zip](https://github.com/supermerill/Slic3r/files/4675387/Extrudr-Bunny2017-No_Sunglass.zip)

**Comment by supermerill** [comment]
can you try to print it using "concentric (filled)" as solid pattern?

**Comment by supermerill** [comment]
As there is a solution with the layer modifier, as the proof is not made with this slicer (or i misunderstood), i won't do anything until it's proven that it's not reproducible with this slicer (and it's not an obvious configuration problem).

**Comment by supermerill** [comment]
@VanessaE 

> Put it back the way it used to be in the old days

Do you have a commit or a date on slic3r where it was the good "old days"? To compare with the current code / behavior.

**Comment by VanessaE** [comment]
> Do you have a commit or a date on slic3r

Unfortunately no.  All I can remember is it was a few years ago.  But I'm 90% certain this behavior changed when the "ensure top/bottom thickness" feature was added.

> > Also you're a bit difficult to follow:

> That would be fine if it were adding more perimeters to fill it out.
> The solution is just to not add any extra plastic,

By this I meant, if you add any plastic at all, it has to be in the form of lines drawn parallel to, and going in the same direction as the perimeters, whether that be in the form of real perimeter loops or just simple lines that have an equivalent effect.

But if that can't be done -- even if you can't even just "fake it" -- then it's better to just not add this extra material at all, in any form.  Let the user add more perimeters in their config if they want.

**Comment by jesterhead82** [comment]
This gets triggered either by "Ensure Vertical Thickness" to ensure perimters and also "Top/Bot
tom minimum thickness"

Would it be possible to set a different infill type (e.g. concentric fixes this) when the slicer decides to add solid infill to ensure vertical/horizental width?

**Comment by VanessaE** [comment]
> This gets triggered either by "Ensure Vertical Thickness" 

No, as has previously been wrung out, it does not have to do with this.

**Comment by PuddingBaer91** [comment]
@VanessaE please try to set a minimum layer time too slow down your print speed. Or just print slower to test your overhang performance. The slower you print the more time the filament has to cool and harden...

**Comment by supermerill** [comment]
discussion about this issue can continue on #1090
