### ISSUE TITLE
Z-seam aligned 

### ISSUE THREAD

**Issue by tome9111991** [supermerill/SuperSlicer#2535]
Hi
I use almost aligned for Z seam.
But since susi .58 i have some issue with.
I have many random seams looks not really aligend.

Susi
![Screenshot 2022-03-14 194906](https://user-images.githubusercontent.com/57866234/158240739-ca7c30d8-7b33-4060-a589-1f1ac0adc012.png)
PS2.4
![ps](https://user-images.githubusercontent.com/57866234/158241259-64eca1dc-5d08-4c64-8f5f-29153b94bbf4.png)

You can look in 3D benchy the seam on back looks a bit random.
In PS2.4 looks a bit "cleaner"
But best result i have in susi  early .57 or .56 not sure.

Edit
On some project i got seams on arc.
On arc I have a kind of blobs in the print
Susi
![su1](https://user-images.githubusercontent.com/57866234/158242177-aaf31b1b-94f3-4aef-81b1-cfe781c51d06.png)

PS2.4
![ps1](https://user-images.githubusercontent.com/57866234/158242226-843edb7d-baac-4a72-ac2e-2b37500c9a07.png)

Mayve you can look into.
Thx

**Comment by supermerill** [comment]
kinda same bag as #2444

**Comment by Deutherius** [comment]
I have also came across this bug. Beginning with 2.4, I do not think it is related to #2444, which seams to be focused on seam painting. I have an issue with aligned when no painting is used.

Aligned z seam seems to be broken/very unreliable. Where it was previously reliable in that it chose some position and made the seam truly aligned (z seam gap artificially enlarged for better visibility)

![SB_front_2 3](https://user-images.githubusercontent.com/61467766/161614441-d5f27794-22bb-4eab-a067-1c5ec64fd168.PNG)

it will now place the seam randomly

![SB_front_2 4](https://user-images.githubusercontent.com/61467766/161614589-86adfc39-bfad-416a-9c29-81e30f730ae4.PNG)

Furthermore, even if it does place the seam aligned, it will sometimes choose a really weird position, i.e. in the middle of a wall when a suitable corner is nearbly. Example from 2.3.57.9

![Latch_2 3](https://user-images.githubusercontent.com/61467766/161614730-f82630a6-3495-4f70-9724-3088cdc3a338.PNG)

and the same object in 2.4.58.2

![Latch_2 4](https://user-images.githubusercontent.com/61467766/161614810-afaccc23-816c-4fa5-8c4f-21b8cee64502.PNG)

Same profiles were used for both versions of superslicer (with the exception of z seam gap, but I have verified that this has no effect on seam placement). Included 3MFs for ease of checking:
[SB_front_and_latch.zip](https://github.com/supermerill/SuperSlicer/files/8412510/SB_front_and_latch.zip)

**Comment by supermerill** [comment]
seems okay-ish in the nightly.
A final problem is that it seems that the "aligned" may make the seam to jump a little bit on the previous/next point sometimes. Will look why.
