### ISSUE TITLE
Incorrect jerk units

### ISSUE THREAD

**Issue by jullit31** [supermerill/SuperSlicer#2545]
**Bug description**
Minor thing, but the jerk is expressed in mm/s when it should be mm/s³.
Unlike #1184 this does not seem to be limited to certain flavors of G-code.

**To Reproduce**
1. Go to 'Machine limits'
2. Scroll down to 'Jerk limits'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/19243986/158635128-b0c38ca5-bfda-488c-8cea-045b4c51ca3e.png)

**Desktop:**
 - OS:  Windows
 - Version 2.3.57.11

**Comment by jullit31** [comment]
Hmm, interesting. So it's a mistake in the Marlin docs. I mean, the physics is clear: jerk is the rate of change of acceleration, so it must be of the dimension L/T³ (length over time cubed).

P.S. Having the same units in the GUI for all G-code flavors is also easier for the user IMHO, so good choice 👍

**Comment by CCS86** [comment]
I don't think any of the main printer firmwares use "true" jerk. It is just an acceleration "bypass", where the commanded velocity can jump instantaneously up by the max jerk value, continuing from there bounded by acceleration limits.
