### ISSUE TITLE
SuperSlicer_2.4.58.1_win64_220307 crashes on startup | FirstRun

### ISSUE THREAD

**Issue by Xeroxxx** [supermerill/SuperSlicer#2547]
### What happened?

SuperSlicer_2.4.58.1_win64_220307 crashes on startup, if SuperSlicer hasn't been run on this system before.

If running 2.3.x before starting 2.4.x startup went fine.

[2022-03-16 22:52:03.428483] [0x00002cdc] [trace]   Initializing StaticPrintConfigs
SuperSlicer GUI initialization failed: boost::filesystem::create_directory: The system cannot find the path specified: "C:\Users\XXXXX\AppData\Roaming\SuperSlicer\ui_layout"

![Capture](https://user-images.githubusercontent.com/1109954/158697879-cd5b0951-5f8b-4be9-aaea-c66ca93462c8.PNG)

### Project file & How to reproduce

Delete %Appdata%/SuperSlicer
Start 2.4 -> Crash
Start 2.3 -> Runs fine
Start 2.4 -> Runs fine

### Version

2.4.58.1

### Operating system

Windows 10

### Printer model

Irrelevant

**Comment by supermerill** [comment]
https://github.com/supermerill/SuperSlicer/releases/tag/2.4.58.1
4th known issue
