### ISSUE TITLE
Allow multiple angles for sparse infill direction.

### ISSUE THREAD

**Issue by JoeLoginIsAlreadyTaken** [supermerill/SuperSlicer#2557]
I'm looking for a way to create a open line grid pattern with SuperSlicer.
I use this for prints which should be filled with epoxy (just print the outer shell and fill it with resin and maybe sand).
As the pattern is open in X+Y direction, the epoxy can flow in every corner.

In Cura i used the "Lines" infill-pattern with custom directions "[45,45,45,135,135,135]".
Always 3 Layers with lines in the same direction, then 3 layers with lines in the opposite direction (at 0.2mm layers).
The infill have keep the walls in position and prevent them from deforming, as the epoxy causes some pressure.

It would be very nice if SuperSlicer could make this possible
![pattern_settings_cura](https://user-images.githubusercontent.com/35426186/159354098-1b184a97-4ac8-4dee-b897-325251c40b5a.png)
![pattern](https://user-images.githubusercontent.com/35426186/159354128-77365f22-0c00-4861-ac7f-1eedd9ed6d74.jpg)
![pattern_print](https://user-images.githubusercontent.com/35426186/159354164-800803ee-e2f6-4f41-9c32-caf117a7d7e0.jpg)
.

**Comment by neophyl** [comment]
With the release version, just select an infill pattern like grid and then set the increment value to something like 10-15 (Print Settings>Infill>Advanced>Angle>Increment.  Although many of the patterns would work with suitable increment angles.

Those settings are Expert/Advanced level so make sure you aren't in Simple mode.

**Comment by supermerill** [comment]
gyroid is open by construction.
I guess i can create  the same kind of array for direction, instead of only one value.
