### ISSUE TITLE
First Layer Speed modifier partially ignored if auto-speed enabled

### ISSUE THREAD

**Issue by kizza42** [supermerill/SuperSlicer#256]
### Version
2.2.50

### Operating system type + version
Win10

### 3D printer brand / version + firmware version (if known)
Tevo Little Monster with Klipper

### Behavior
It seems the First layer speed modifier is partially ignored in this version, The brim prints at this speed but first layer of the model does not. This issue does not present in PrusaSlicer
![2020-05-29_17-38-31](https://user-images.githubusercontent.com/12605257/83234583-e0ce2880-a1d3-11ea-9c5d-58c4dd8966d3.png)
![slic3r++_2020-05-29_17-38-38](https://user-images.githubusercontent.com/12605257/83234586-e297ec00-a1d3-11ea-92b3-fdec5211d260.png)

#### Project File (.3MF) where problem occurs
[Extrusion_Test.3mf.txt](https://github.com/supermerill/SuperSlicer/files/4700323/Extrusion_Test.3mf.txt)

**Comment by supermerill** [comment]
This only happen if you let the auto-speed algo do the job. Did you let some speed box to 0 (perimeters, solid infill,...) in prusa also?

**Comment by kizza42** [comment]
The same settings in Prusa seem to honour the first layer speed.

![2020-05-29_18-38-14](https://user-images.githubusercontent.com/12605257/83239703-acf70100-a1db-11ea-8bf6-65857d819695.png)
![2020-05-29_18-37-25](https://user-images.githubusercontent.com/12605257/83239710-ae282e00-a1db-11ea-94db-c57cdef03372.png)
