### ISSUE TITLE
filament_shrink no effect

### ISSUE THREAD

**Issue by Ajol3D** [supermerill/SuperSlicer#2561]
### What happened?

Hi, 
**filament_shrink parameter seems have no effect on gcode.**

I noticed that when I tried to correct the shrinkage on ASA filament, my parts were still the same size despite having changed the parameter. Maybe I didn't understand the use of this parameter?

### Project file & How to reproduce

1. Apply 100% to filament_shrink
![image](https://user-images.githubusercontent.com/102210136/159641732-3b70d956-3d4a-4e38-a14a-87b9f1535da2.png)
![image](https://user-images.githubusercontent.com/102210136/159641621-52e68bad-889d-45d3-a8a8-0010ec3e69eb.png)

2. Apply 90% to filament_shrink
![image](https://user-images.githubusercontent.com/102210136/159641945-8e2654f8-f042-4713-90c7-4493b4f4b8d3.png)
![image](https://user-images.githubusercontent.com/102210136/159642110-bddef377-643a-429d-9b7a-fbc0b4e22ba0.png)

-> In all cases on line 59194 of gcode x pos is always 104.14

### Version

2.4.58.1

### Operating system

Windows 10

### Printer model

Sapphire Plus

**Comment by neophyl** [comment]
https://github.com/supermerill/SuperSlicer/issues/2517

**Comment by Ajol3D** [comment]
Ok, Thanks
