### ISSUE TITLE
2.4.58.x: Strange Defect in Perimeter Wall

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#2569]
### What happened?

In a very uniform, in one specific spot, of one specific layer, a very strange defect is generated that affects 2 walls. One wall has a tiny kink inwards, and the next wall has a large jump outwards. Behavior is there in both 2.4.58.1 and 2.4.58.2 nightly:

![image](https://user-images.githubusercontent.com/12439543/159804792-8fdaea44-b2d1-4eed-beed-26d8fe277f90.png)

### Project file & How to reproduce

[OP10-Fix.3mf.txt](https://github.com/supermerill/SuperSlicer/files/8337003/OP10-Fix.3mf.txt)

### Version

2.4.58.1

**Comment by CCS86** [comment]
Found another one:

![image](https://user-images.githubusercontent.com/12439543/159806494-52154901-5f43-445f-9d1d-ecd9d0f6c444.png)

**Comment by liftbag** [comment]
I've found a similar issue with spiral vase, but it appears to be a PrusaSlicer 2.4.1 issue. Can you check with PrusaSlicer too?

**Comment by supermerill** [comment]
can't reproduce.
it's random?

for the "prusaslicer2.4.1 issue", i'm not sure. If it is a perimeter issue, it can't comes from prusaslicer, as i don't use their perimeter code. But if it's a gcode-viewer issue, then maybe.

![image](https://user-images.githubusercontent.com/6536403/159899782-eb8968f0-4f14-482e-a98d-63380f23d34e.png)
