### ISSUE TITLE
Short Layer time cooling approximate seconds

### ISSUE THREAD

**Issue by arne182** [supermerill/SuperSlicer#2574]
**Is your feature request related to a problem? Please describe.**
Short Layer time cooling approximate seconds is an integer:
![image](https://user-images.githubusercontent.com/844102/159983959-a5bdb6b1-4927-4860-a679-df3b870d68f1.png)

**Describe the solution you'd like**
For me I require it to be about 0.4s but as it is an integer I can only set 1s which does not work for my setup.

**Describe how it would work**
same implementation just as float instead of integer 
This was like this in Version 2.3.57.11

**Comment by supermerill** [comment]
why?

**Comment by arne182** [comment]
![image](https://user-images.githubusercontent.com/844102/159991845-1cc19b0c-8b3d-433f-82eb-4841e01c291e.png)
500 x500 x500
The travel speed can easily do 1000mm/s and 2000mm/s with the new 48V drivers
