### ISSUE TITLE
Nightly build incorrect

### ISSUE THREAD

**Issue by dingyifei** [supermerill/SuperSlicer#2581]
### What happened?

The nightly-dev build for Ubuntu-GTK3/Ubuntu is 2.3.57, the wrong branch is probably used 
![image](https://user-images.githubusercontent.com/15083013/160260658-a85bf41c-d4c3-4c26-b7f7-ac63b29e2b41.png)

### Project file & How to reproduce

Download and run the AppImages, they are all the wrong version

### Version

2.3.57

### Operating system

Fedora release 35

**Comment by supermerill** [comment]
btw, i'm moving to nightly_dev for the dev branch (currently 2.4) and nightly_master for the master branch (currently 2.3)

**Comment by dingyifei** [comment]
Additionally I just realized the release candidate for linux doesn't have the UI improvements

**Comment by supermerill** [comment]
oh, i see why. my bad.

**Comment by dingyifei** [comment]
> oh, i see why. my bad.

am I using an old version the whole time lmao

**Comment by supermerill** [comment]
the build is right, my commit message also, but there was a bug in the build script, so it uses the old code to build instead of the one from the commit.

**Comment by dingyifei** [comment]
It works now
