### ISSUE TITLE
NAME objects other than "Object 0" 

### ISSUE THREAD

**Issue by inspectionsbybob** [supermerill/SuperSlicer#2587]
**Is your feature request related to a problem? Please describe.**
When printing Multiple Objects what appears on the Printer is:
"Printing Object 0"
"Printing Object 1"
"Printing Object 2"
and so on...

If I want to cancel an object because of an error or failure but let the rest of the print continue
I would love to have the NAME from the Platter screen be used so I could cancel "Wing #4" rather than wondering which object is which...

**Describe the solution you'd like**
Have the Object Name(s) be picked up from the List on the Platter Page

**Describe how it would work**
Have the Object Name(s) be picked up from the List on the Platter Page
-AND/OR- be able to edit the name(s) on the Platter screen so they FIT into the 12 character printer field

**Describe alternatives you've considered**
None

**Additional context**
![Screenshot (19)](https://user-images.githubusercontent.com/22258531/160432813-e4022798-9889-440d-b5f9-397f88a78e21.png)

so it appears on this screen

![IMG_8356](https://user-images.githubusercontent.com/22258531/160433561-1e42355b-385e-4f8a-a4f4-2e8c3c83fa4d.JPG)

**Comment by supermerill** [comment]
can you send me a project & the gcode file of an example that produce that?

**Comment by inspectionsbybob** [comment]
The Current Version 2.4.58.4 behaves differently as it no longer includes any M117's of "Printing Object 4" or anything like that.

I am now using something Like Octoprint (Actually "Repeatier-Server" but not everyone knows about that) and it does something different that lets me cancel an object.

THIS ticket can be closed as "fixed" but I may open something similar about no M117 messages when moving between objects.
