### ISSUE TITLE
Dark-Mode

### ISSUE THREAD

**Issue by 4noxx** [supermerill/SuperSlicer#2605]
### What happened?

SL crash if i change to darkmode. 

### Project file & How to reproduce

10:08:25: Interner Fehler: boost::bad_any_cast: failed conversion using boost::any_cast

![image](https://user-images.githubusercontent.com/12627059/161008634-686a645c-9b40-40b6-9398-3223fc9df303.png)

### Version

2.4.58.1

### Operating system

Windows 10

### Printer model

Anet AM8

**Comment by supermerill** [comment]
and the nightly? https://github.com/supermerill/SuperSlicer/suites/5835274444/artifacts/196041452

**Comment by 4noxx** [comment]
nightly works...
