### ISSUE TITLE
Outer perimeters alternating direction - can this be disabled?

### ISSUE THREAD

**Issue by AndrewEllis93** [supermerill/SuperSlicer#261]
### Version
2.2.50

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Ender 3 / SKR 1.4 / Klipper
Voron 2.2 / SKR 1.3 / Klipper

### Behavior
The outer perimeters of my prints seem to alternate direction every layer. I can't figure out how to disable this, if such an option exists. It causes my prints to have a rough surface finish, direction seems to affect corner blobbing etc. 

Gold test cube was done with Prusa Slicer, green test cube was done with SuperSlicer.:

![IMG_20200531_144149](https://user-images.githubusercontent.com/34943186/83360196-8062f680-a34d-11ea-8392-a5e844635696.jpg)

### Is this a new feature request?
If this setting doesn't exist, then it might be!

### 3mf/Gcode Files
[3mf.zip](https://github.com/supermerill/SuperSlicer/files/4708201/3mf.zip)

**Comment by supermerill** [comment]
You can uncheck "more perimeters".

duplicate of https://github.com/supermerill/SuperSlicer/issues/206

fixed in the next version, pick a nightly to have the fix right now.

**Comment by AndrewEllis93** [comment]
Excellent, thank you!
