### ISSUE TITLE
2.4.58.2 build has file versions for 2.3.57.12

### ISSUE THREAD

**Issue by strayr** [supermerill/SuperSlicer#2610]
### What happened?

Look at artifacts on https://github.com/supermerill/SuperSlicer/releases/tag/2.4.58.2
Downloaded zip appears to contain 2.3.57.1
Generates the following errors on run
![2022-04-01](https://user-images.githubusercontent.com/43092584/161184526-521abdb8-4de7-470c-8fe8-0be77a2fdfe9.png)
![2022-04-01 (1)](https://user-images.githubusercontent.com/43092584/161184535-f10a84e2-890c-42c5-bd63-7ae9d405c540.png)
![2022-04-01 (3)](https://user-images.githubusercontent.com/43092584/161184542-2a9f306b-349d-45c5-8ced-fd44418af450.png)

Help -> about reports 2.3.57.12
![2022-04-01 (4)](https://user-images.githubusercontent.com/43092584/161184546-9eece679-e6b5-4cc1-8e2d-94642bbcf558.png)
2

### Project file & How to reproduce

download, unzip and run

### Version

2.4.58.2

### Operating system

windows

**Comment by lordIcocain** [comment]
If after that 2.4 wont launch delete this stuff
%AppData%\SuperSlicer
![image](https://user-images.githubusercontent.com/62835225/161189944-d21ba016-4c7d-425e-988c-837407f46752.png)

**Comment by tapir** [comment]
indeed it looks like the 2.4 release is falsely tagged and names as 2.3

**Comment by supermerill** [comment]
I put the asset from the other release i made an hour before ><
fixed

**Comment by strayr** [comment]
Awesome, thanks!
