### ISSUE TITLE
2.4.58.1/2.4.58.2 Crash on startup

### ISSUE THREAD

**Issue by lordIcocain** [supermerill/SuperSlicer#2620]
### What happened?

Got crash on startup in last two version of 2.4
2.4.58.0 working
2.4.58.1 can start only when AppData/SuperSlicer empty 
2.4.58.2 crash in any case (still creating files in AppData/SuperSlicer)
![image](https://user-images.githubusercontent.com/62835225/161356537-c4310d04-d32b-4e1f-aa63-3c59c0614301.png)

Also, my windows user name contains Cyrillic characters, in the console it is written with weird characters.(on screenshot below)

### Project file & How to reproduce

![image](https://user-images.githubusercontent.com/62835225/161355471-96bb8e9f-de9d-495e-be03-da507bc0ab88.png)

### Version

2.4.58.1, 2.4.58.2

### Operating system

win10 

### Printer model

Any

**Comment by lordIcocain** [comment]
Hello, just tested night build, no problem with startup. Thank you.
Still get some errors, but not saw any problems in work.
![image](https://user-images.githubusercontent.com/62835225/161403222-0ea30665-edbd-4db3-9a0d-95a51c31755e.png)

**Comment by supermerill** [comment]
can you help me to debug these errors?
As long as they're here, you won't have quick settings and some settings will be missing.

can you try to add a "configuration" directory next to your superslicer.exe file, and report if it still fail?

**Comment by lordIcocain** [comment]
![image](https://user-images.githubusercontent.com/62835225/161408924-297a2dae-f232-48e1-b799-64443675c371.png)

**Comment by lordIcocain** [comment]
Last night build with folder "configuration"
![image](https://user-images.githubusercontent.com/62835225/161409185-06282f3f-a22a-4cae-8138-58dbecead970.png)
and without
![image](https://user-images.githubusercontent.com/62835225/161409196-e941107d-6470-4691-9a6b-39b5439ea42d.png)

**Comment by lordIcocain** [comment]
![image](https://user-images.githubusercontent.com/62835225/161662871-6c0a58a0-089f-4679-aa9d-326baba9e062.png)

**Comment by lordIcocain** [comment]
Seems like it trying load ui_script files what actually does not exist.
filament.as
sla_material.as
printer.as
These files were not required in previous versions, they were not in the settings directory and there were no errors that these files were not found.
The program began to request these files in a nightly update that fixed bugs with Cyrillic(UTF) path.

**Comment by supermerill** [comment]
> Seems like it trying load ui_script files what actually does not exist.

I know, and it's indenteded. There is currently no scripted widget on these tab, and so i didn't created the scripted file,n as they aren't needed. You can see that now that I added logs, but it's completly harmless.

do you still don't have the quick setting on the platter tab?

**Comment by lordIcocain** [comment]
I'm confused. I dont get any problems in program working. The quick settings window opens and works as it should.

**Comment by supermerill** [comment]
> The quick settings window opens

the "quick settings" are the three widgets here
![image](https://user-images.githubusercontent.com/6536403/162458829-0a2b056d-76bf-42d7-91f2-61fba9b67ffa.png)
and if the script fail, you can only have the "infill" one (as it's the only one that isn't scripted)

**Comment by lordIcocain** [comment]
![image](https://user-images.githubusercontent.com/62835225/162470645-01f98979-6713-4935-a598-83631adb59a6.png)
it ok too

**Comment by supermerill** [comment]
great!
