### ISSUE TITLE
Per-object settings are removed when canceling new setting dialog

### ISSUE THREAD

**Issue by pa0los** [supermerill/SuperSlicer#2627]
### What happened?

It took me a while to discover why/when my per-object settings are getting removed.
On the example of custom "Width Flow" settings assigned to an object:
![image](https://user-images.githubusercontent.com/8580152/161389885-64b39524-c8e3-4696-8c93-7562d2e78dd0.png)
If I now open the dialog to add another Width Flow setting, I can see these 2 options checked:
![image](https://user-images.githubusercontent.com/8580152/161389944-0ff1c470-2a69-4a34-9acb-7165c15cafe2.png)
But when I hit Cancel in this dialog box, the 2 settings that I already had are getting removed:
![image](https://user-images.githubusercontent.com/8580152/161390036-3bc5e1ea-b0e5-4594-a0f7-f9d28676545b.png)

### Project file & How to reproduce

Not related to a particular project.
Just add a per-object setting, open the "Add settings" dialog box again and hit cancel.

### Version

2.4.58.2

### Operating system

Windows 10

**Comment by supermerill** [comment]
If I change the button label to "Apply" and "Remove All", is it okay?
I'll see if I can add a third.

**Comment by pa0los** [comment]
Oh I see - this is how it's supposed to work...
Renaming the buttons like you proposed would make it clear I think.

**Comment by supermerill** [comment]
It took me some hours, but I have fixed it.
* Apply apply the selection, like the ok
*  Remove all (new) now erase the selection and apply.
* Cancel now don't touch the items


In the codebase, it was a bit strange. some code say "cancel don't erase" and then the caller erase everything...

**Comment by supermerill** [comment]
"Remove All" or "Clear" ?

**Comment by pa0los** [comment]
If you ask me, I would only leave "apply" and "cancel" buttons.
Removing is easy enough and I can't imagine having this many settings to justify the "remove all / clear" button.
But "clear" is also ok.
