### ISSUE TITLE
Can't open directory '/home/lukas/.config/SuperSlicer-alpha/vendor'. Config bundles from here can't be loaded.

### ISSUE THREAD

**Issue by Lukas1818** [supermerill/SuperSlicer#2628]
### What happened?

Error message at every start.
![image](https://user-images.githubusercontent.com/44570204/161391377-25feee51-e3fb-4ed7-b3cb-1d73ff2dcad2.png)
### Project file & How to reproduce

* install [superslicer-prerelease from AUR](https://aur.archlinux.org/packages/superslicer-prerelease) 
* start SuperSlicer

### Version

1:2.4.58.2-2

### Operating system

manjaro

**Comment by supermerill** [comment]
can you post me your `/home/lulkas/.config/SuperSlicer-alpha` directory (zipped), so i can test?

**Comment by Lukas1818** [comment]
duplicate
