### ISSUE TITLE
Empty checkbox option under Perimeters & Shell -> Infill

### ISSUE THREAD

**Issue by guaddy** [supermerill/SuperSlicer#2630]
### What happened?

On 2.4.58.2, under Perimeters & Shell -> Infill section, there is a checkbox with no associated text or options. Tooltip reveals the information in the screenshot below.
![Screenshot 2022-04-02 160340](https://user-images.githubusercontent.com/67671414/161404287-a571f1c5-6c36-472a-a8e0-aaec983d2f29.jpg)
![Screenshot 2022-04-02 160359](https://user-images.githubusercontent.com/67671414/161404288-b516972b-0021-48b1-b7bb-dff8034d0674.jpg)

### Project file & How to reproduce

This occurred on start up while changing settings. No project file should be necessary.

### Version

2.4.58.2

### Operating system

Windows 11

### Printer model

Prusa i3 MK3S+

**Comment by supermerill** [comment]
should be already fixed in the nightly
