### ISSUE TITLE
When a modifier is added its action is not immediate 

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#2631]
### What happened?

When i add a modifier and maybe increase the number of perimeters on it, its action is not immediate in the slicing, i've to save and reopen the project to do it.

### Project file & How to reproduce

It does this with any project.

### Version

2.4.58.2

### Operating system

Windows 10 Pro x64

### Printer model

Delta printer

**Comment by robustini** [comment]
https://user-images.githubusercontent.com/3864712/161417049-4ae7e2a6-f436-4f12-890c-f52526d33130.mp4

**Comment by supermerill** [comment]
it's a 2.4.58.2 bug, fixed in the nightly
