### ISSUE TITLE
Failed to load image from file (SuperSlicer icon) upon startup

### ISSUE THREAD

**Issue by bradvaughan** [supermerill/SuperSlicer#2634]
### What happened?

Upon startup, the following error is displayed.  Clicking "OK" does allow the app to continue starting and operation is as expected thereafter.  I verified there is no such file in resources\splashscreen, but there wasn't in 2.3.57.11 either.

![Untitled](https://user-images.githubusercontent.com/56238257/161428668-3153f424-a7b7-4a1f-a05c-de36075ccbc3.png)

### Project file & How to reproduce

Open SuperSlicer, wait for the splash screen to disappear.  This error message appears immediately afterwards.

### Version

2.4.58.2

### Operating system

Windows 10

### Printer model

N/A

**Comment by bradvaughan** [comment]
This error can be resolved by changing the splash screen image from "Default" to "Icon":

Configuration -> Preferences -> General -> Splash Screen -> Splash screen image:  Icon

**Comment by supermerill** [comment]
I guess it was a bad entry in the color.ini that was in your conf dir.

**Comment by bradvaughan** [comment]
Non repro

**Comment by jangrewe** [comment]
Can confirm both the issue and the fix. Happened when updating stable to latest pre-release.
