### ISSUE TITLE
Incorrectly generated parameter "skirt_extrusion_width"

### ISSUE THREAD

**Issue by Hashan0** [supermerill/SuperSlicer#2638]
### What happened?

If the parameter  "_skirt_extrusion_width_"  in  "_vendor\xxx.ini_ "  file is missing or empty, the value **130** instead of **130%** is generated.
![Unbenannt-2](https://user-images.githubusercontent.com/101518551/161445408-6276389e-4000-44a3-9d56-2e2d8f7a8dc0.png)
![Unbenannt-3](https://user-images.githubusercontent.com/101518551/161445412-eddf36d8-21e4-4463-a576-ce441b9098db.png)

### Project file & How to reproduce

[Desktop.zip](https://github.com/supermerill/SuperSlicer/files/8405379/Desktop.zip)

### Version

2.4.58.2

### Operating system

Windows 10

**Comment by supermerill** [comment]
how did you get that? if i open the 2.4.58.2 without (or an empty) configuration directory, I get a 130%.

**Comment by Hashan0** [comment]
The error occurs when the parameter "skirt_extrusion_width = " is entered in the config file (see "vendor\Basic.ini" line 347).
![Basic ini](https://user-images.githubusercontent.com/101518551/161519499-7f72d4b0-23a3-4b48-9697-57a2832ca991.jpg)
[SuperSlicer.zip](https://github.com/supermerill/SuperSlicer/files/8408625/SuperSlicer.zip)
