### ISSUE TITLE
Bad quality with painting tool [2.4.58.2 Fishy edition]

### ISSUE THREAD

**Issue by schnello** [supermerill/SuperSlicer#2639]
Hello.

I want only ask if this issue is know,

If i use the color painting tool with the latest test version the surface quality is bad ([Fishy edition](https://github.com/supermerill/SuperSlicer/releases/tag/2.4.58.2)
[files.zip](https://github.com/supermerill/SuperSlicer/files/8407795/files.zip)

If i do the same with the prusa all is fine

![image](https://user-images.githubusercontent.com/6481341/161499260-0d4edde7-b7fa-4f75-a4c8-5efae5690e67.png)

**Comment by NoSvOrAx** [comment]
I'm having the same issue with the Fishy Edition.  Just tried it on the previous version, 2.4.58.1, and it doesn't have the problem.

![image](https://user-images.githubusercontent.com/54042306/167270255-1ecfcd68-361a-4ab5-86f4-d6d59e4c638b.png)

**Comment by supermerill** [comment]
awfully difficult to fix.
The probem where in the resolution. The paint is made on the raw polygons, and it's compared to the simplified polygon.
The threshold was too small, and it can't find the new lines anymore.

Tell me if artefacts are appearing again.

**Comment by schnello** [comment]
Tested with the lastest nightly. 
left Superslicer, right PrusaSlicer
![image](https://user-images.githubusercontent.com/6481341/190864909-c4c972fc-ca87-4dc8-9866-5d59129f9f89.png)

**Comment by Nerobeus** [comment]
Still have troubles... See the test part from ERCF.

![MMU](https://user-images.githubusercontent.com/19369944/193574191-a81be49c-9b7b-459a-ae2b-a6875e860449.png)

**Comment by fract0id** [comment]
Just saw this, not sure it's still current. I had a similar issue, but it appeared in both PS and SS with the same project, but not when creating a new project in PS. I eventually figured out that it was caused by the "Slice resolution" parameter. PS defaults to 0, in SS I had 0.0125. Setting it to 0 fixed the issue for me, with no noticeable downsides.

**Comment by MarkXYZ-Mtl** [comment]
@fract0id 
It had to adjust "Slice resolution" for  SS 2.5.59.2 (latest pre-release) and 2.4.58.5.
Been looking for a while for a solution!
Thanks
