### ISSUE TITLE
Crasches when adding extruder

### ISSUE THREAD

**Issue by Pairair** [supermerill/SuperSlicer#265]
### Version
2.2.51

### Operating system type + version
Windows 10 Pro 64 bit

### 3D printer brand / version + firmware version (if known)
Flashforge Creator 3

### Behavior
Program crasches every time I try to add an extruder in Printer settings.

![image](https://user-images.githubusercontent.com/66405931/83722323-12644b00-a63d-11ea-84cd-82734766ac0d.png)
![image](https://user-images.githubusercontent.com/66405931/83729359-c23eb600-a647-11ea-8ba3-487041cd1883.png)

**Comment by supermerill** [comment]
should be corrected in the 2.2.51.1
