### ISSUE TITLE
Wipe tower last wipe in mid air

### ISSUE THREAD

**Issue by nikolai-matijevic** [supermerill/SuperSlicer#2650]
### What happened?

When using the wipe tower with the `No sparse layers (EXPERIMENTAL)` option, the last wipe is placed in mid air instead of on top of the wipe tower. This happens on 2.3.57.11 as well as 2.4.58.2. 

![floating wipe tower](https://user-images.githubusercontent.com/61649682/162017096-d6cb8b3e-02ea-448d-94bb-488258e2f2e7.png)

I would expect the last wipe to be on top of the wipe tower which is on a lower layer in this case.

### Project file & How to reproduce

[Support Test v2.zip](https://github.com/supermerill/SuperSlicer/files/8428564/Support.Test.v2.zip)

Be sure to enable `Wipe tower` and `No sparse layers (EXPERIMENTAL)` under `Print Settings` -> `Multiple extruders`

### Version

2.4.58.2

### Operating system

Windows 10

**Comment by neophyl** [comment]
https://github.com/prusa3d/PrusaSlicer/wiki/Frequently-Asked-Questions-(FAQ)  This is from the Prusa slicer faq as this was raised as an issue on their GitHub. Second item down. So not a bug apparently.

**Comment by nikolai-matijevic** [comment]
Thank you. I'll close it then.
