### ISSUE TITLE
Adaptive layer height not working

### ISSUE THREAD

**Issue by StarGate01** [supermerill/SuperSlicer#2652]
### What happened?

My installation does not manage to actually modify the heights of the generated layers when I enable adaptive layer height.

What am I doing wrong? Thank you for any help.

### Project file & How to reproduce

Project file: [Hemisphere_test.zip](https://github.com/supermerill/SuperSlicer/files/8439423/Hemisphere_test.zip)

Images:
![slice_1](https://user-images.githubusercontent.com/6362238/162115622-bbcf153f-e787-48d4-9242-8a953d0936eb.PNG)
![slice_2](https://user-images.githubusercontent.com/6362238/162115627-d3fb704d-7b61-41d7-bcd0-93819e91f9a2.PNG)
![slice_3](https://user-images.githubusercontent.com/6362238/162115636-276f1b27-ef12-4613-8e61-b9fbf37399eb.PNG)

### Version

2.3.57.12

### Operating system

Windows 10 x64

### Printer model

Anet AM8 with SKR2 and BIQU H2

**Comment by qwewer0** [comment]
Works fine on 2.4.58.2
![image](https://user-images.githubusercontent.com/57561110/162119634-790cdcf3-0c2b-4bb2-b4af-42969a417d50.png)

**Comment by StarGate01** [comment]
Oh sorry, I did not realize there was a pre-release branch. Now it works fine for me as well, thank you!

**Comment by supermerill** [comment]
Seems like in the 2.3 branch, stl that are auto-repaired can't have variable layer height, or something like that.
