### ISSUE TITLE
SS 2.4.x No proper G-CODE preview inside app while sliced with Spiral Vase Mode=ON

### ISSUE THREAD

**Issue by shcad** [supermerill/SuperSlicer#2679]
### What happened?

Preview of perimiters is no visible. Everything is fine if loaded generated gcode to the Gcode Viewer  manualy. (Latest stable SS Version works fine, but I miss "Seam" feature in preview :( )

### Project file & How to reproduce

Set Spiral Vase Mode ON

### Version

2.4.58.2

### Operating system

Win 10

**Comment by neophyl** [comment]
Sounds like this one from Prusa Slicer  https://github.com/prusa3d/PrusaSlicer/issues/8032

**Comment by supermerill** [comment]
spiral is fine on my projects

**Comment by shcad** [comment]
Seems like the other one #2711 with the same problem caught more attention then this one so it is time to close it.
