### ISSUE TITLE
Only One Perimeter Top still present and cannot be unchecked in Part Modifiers when Perimeters is 0

### ISSUE THREAD

**Issue by sg000** [supermerill/SuperSlicer#268]
### Version
2.2.51

### Operating system type + version
Win10

### Behavior
When creating a modifier box or slab (probably other shapes too) to use as a blocker to prevent printing (0 perimeters, 0 top and 0 bottom layers, 0 infill %), I could not uncheck the Only One Perimeter Top checkbox in the modifier and as a result you get the single perimeter showing in space. If you make perimeters >0 then you can THEN uncheck the box and THEN change perimeters to 0 to get desired effect. But this is an undesired workaround and not immediately obvious.

I couldn't find this reported already. But I did find #176 (https://github.com/supermerill/SuperSlicer/issues/176) that is slightly related.

**Comment by supermerill** [comment]
can you post your .3mf with these modifiers to help me replicate the issue?
