### ISSUE TITLE
Indicate seam location in sliced/gcode view.

### ISSUE THREAD

**Issue by Lecso11** [supermerill/SuperSlicer#2684]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a visible indication of the location of the Z seam when looking at the sliced/gcode preview.

**Describe the solution you'd like**
I come from Cura, where the seam placement is indicated with a white dot on the beginning of the line:
![kép](https://user-images.githubusercontent.com/78912917/162780153-76964363-2d1f-43e6-9ac1-9023d6246097.png)

**Comment by supermerill** [comment]
available on the 2.4 versions.

**Comment by Lecso11** [comment]
Found it!
