### ISSUE TITLE
"Not a PrusaSlicer / Slic3r PE / SuperSlicer generated g-code" when importing a Slic3r++ generated gcode

### ISSUE THREAD

**Issue by l0calgost** [supermerill/SuperSlicer#269]
### Version
2.2.51

### Operating system type + version
Windows

### Behavior
When trying to import a config from a gcode (File -> Import -> Import Config) that has been generated by Slic3r++ (V2.2.50) (see attached Rippe_test_Speed60... zip file. It includes the generated gcode) an error dialog pops up:
![image](https://user-images.githubusercontent.com/6068534/83848566-596e4100-a70e-11ea-80ae-23d60a3e06e6.png)

I would have expected that I'm able to import Slic3r++ gcodes into SuperSlicer. Or is this expected behavior?

#### Project File (.3MF) where problem occurs
[Ripple_test.zip](https://github.com/supermerill/SuperSlicer/files/4734505/Ripple_test.zip)
[Ripple_test_Speed60-turned45_PLA_0.2_28m.gcode.zip](https://github.com/supermerill/SuperSlicer/files/4734496/Ripple_test_Speed60-turned45_PLA_0.2_28m.gcode.zip)

**Comment by supermerill** [comment]
Oh yeah, i update the check, so now it only check for superslicer, but for slic3r++ anymore, i'll re-add it.
