### ISSUE TITLE
Supports weird behavior control.

### ISSUE THREAD

**Issue by levleon13** [supermerill/SuperSlicer#2690]
### Version
Latest

### Operating system type + version
WIN11 

### Behavior
Supports are being created in a little wider area than the area needed to be supported, creating tiny bits that 100% fail on print.
Happens in any case, i am always fighting these, is there a way to tell the support that it should be ONLY directly under the exact area of the bridge\overhang?

![image](https://user-images.githubusercontent.com/77578163/163125634-9c0aaf6f-aed7-47fe-963c-dfbb565dd8ec.png)

**Comment by supermerill** [comment]
The 2.4 versions have new settings to control that.

**Comment by levleon13** [comment]
> The 2.4 versions have new settings to control that.

uhmm.. so this should be on the latest superslicer(2.3.57) right? what is the name of the setting?

**Comment by supermerill** [comment]
> should be on the latest superslicer(2.3.57) right?

nop, it's on the beta ones. (2.4.58)

**Comment by levleon13** [comment]
> > should be on the latest superslicer(2.3.57) right?
> 
> nop, it's on the beta ones. (2.4.58)

So i guess it will be implemented soon?

**Comment by supermerill** [comment]
It's already implemented in the beta releases, available in the release page.

**Comment by levleon13** [comment]
> It's already implemented in the beta releases, available in the release page.

Thank you!
