### ISSUE TITLE
No object option for "first_layer_flow_ratio"

### ISSUE THREAD

**Issue by TommyC81** [supermerill/SuperSlicer#2695]
### What happened?

Select an object, "Add settings -> Width Flow", there is no option to adjust "first_layer_flow_ratio" (top_layer_flow_ratio is available, for comparison).

### Project file & How to reproduce

Select an object, "Add settings -> Width Flow", fail to locate an option for "first_layer_flow_ratio".

Available first layer options:
![image](https://user-images.githubusercontent.com/1904092/163232220-0331720d-fd05-4698-9025-9b48805fdb4c.png)

### Version

nightly_dev (e941089c075efbdbf7f36959f868ce2b5ee4c633)

### Operating system

Windows 10

### Printer model

Creality CR6 with Sherpa Mini direct drive

**Comment by courtross2010** [comment]
Thank You So Much For This!!!!!!!!
