### ISSUE TITLE
Empty preview when slicing in Vase mode 

### ISSUE THREAD

**Issue by robblot** [supermerill/SuperSlicer#2711]
2.4.58.2 Version

Windows 11

When I slice anything in vase mode I get no preview in the Gcode preview tab.

**Comment by supermerill** [comment]
add `G1 Z1` at the end of your start gcode.
It's just a gcode reader issue from the gcode preview. Fixed in next nightly.

**Comment by robblot** [comment]
Thank you

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CODeRUS** [comment]
> add `G1 Z1` at the end of your start gcode. It's just a gcode reader issue from the gcode preview. Fixed in next nightly.

can you please run nightly build soon? :)

**Comment by supermerill** [comment]
oh, I tough i did it 5 days ago before my break. Sorry. I do it now.
