### ISSUE TITLE
Variable layer height doesn't work properly

### ISSUE THREAD

**Issue by Super-Matter** [supermerill/SuperSlicer#2714]
### What happened?

The box shape is sliced correctly but my custom stl is not.

### Project file & How to reproduce

![изображение](https://user-images.githubusercontent.com/60855176/163594572-c5e2782e-bf06-4f22-a410-20044f83f717.png)
![изображение](https://user-images.githubusercontent.com/60855176/163594579-01840c84-3753-4e1c-9897-383d846ebc7e.png)
![изображение](https://user-images.githubusercontent.com/60855176/163594624-0ec0970f-7410-42d9-8b74-ea55d777145f.png)

### Version

2.4.58.2

### Operating system

Win10

### Printer model

custom

**Comment by Super-Matter** [comment]
[Shape-Box.zip](https://github.com/supermerill/SuperSlicer/files/8496902/Shape-Box.zip)
Here's my 3mf

**Comment by Super-Matter** [comment]
![изображение](https://user-images.githubusercontent.com/60855176/163595445-83200621-3f01-4f3a-b2b1-08f65f9c2038.png)
When I scale it up it starts to work

**Comment by Super-Matter** [comment]
![изображение](https://user-images.githubusercontent.com/60855176/163595798-e3007fea-76f5-4fc3-8185-be8d9d22f0ac.png)
I could trigger it working by adjusting the y scale factor only

**Comment by Super-Matter** [comment]
2.3.57.12 seems to work. Ill stick to it for now. Can't compile a nightly build right now

**Comment by supermerill** [comment]
you don't need to build, just use [download a good file](https://github.com/supermerill/SuperSlicer/suites/6065818425/artifacts/209601478)  from the action menu

**Comment by Super-Matter** [comment]
Bugfix confirmed in 2.4.58.3 
Thanks
