### ISSUE TITLE
Compare presets => copy presets!

### ISSUE THREAD

**Issue by alexvonsiebenthal** [supermerill/SuperSlicer#2717]
**Is your feature request related to a problem? Please describe.**
with new features being added (i.e. acceleration control), we need to update all profiles. It's a lot of work to do so manually.

**Describe the solution you'd like** / **Describe how it would work**
In the compare presets dialog, I'd like the ability to copy some presets from profile A to profile B.
![image](https://user-images.githubusercontent.com/6860125/163711208-9a653d89-fd49-450d-b4e7-b9f4a6d1b86b.png)

**Describe alternatives you've considered**
Doing things manually

**Comment by supermerill** [comment]
duplicate of #2524, i guess

**Comment by alexvonsiebenthal** [comment]
> duplicate of #2524, i guess

Absolutely, sorry! I did not find it prior to creating this issue.
