### ISSUE TITLE
Bridge Flow Calibration Issue

### ISSUE THREAD

**Issue by paulhew69** [supermerill/SuperSlicer#272]
### Version
2.2.51

_Use `About->About SuperSlicer` for release versions_

_For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_

### Operating system type + version
Ubuntu

### 3D printer brand / version + firmware version (if known)
N/A

### Behavior
Error after clicking 'Test Flow Ratio' button in Bridge Flow Calibration.
![image](https://user-images.githubusercontent.com/61477100/83937209-c511e600-a7c2-11ea-91ac-a4160b1c48aa.png)
Workaround, Go to the 3D Editor View, Autoarrange, then click Slice now.

**Comment by supermerill** [comment]
Can you post the project file when the problem appear? thx

**Comment by paulhew69** [comment]
It was using the Bridge Calibration tool in SuperSlicer, so it is part of your suite of tools, not one of my files.

Regards

________________________________

**Comment by supermerill** [comment]
yes, but once you clic on it, you will have the error pop-up and then you can save and send it to me.
It's not only for the generated geometry but also for your printer settings. 
The calibration should generate something for your printer, if it's failing and I don't have your printer conf, i can't replicate nor correct the issue.

**Comment by paulhew69** [comment]
![image](https://user-images.githubusercontent.com/61477100/83961776-5b5f0e00-a88e-11ea-8bb3-d9abc11e34f0.png)
Sorry, now I see what you are referring too.
I have a 300 x 300 bed.

If you click back to the '3d editor view' you see this.
![image](https://user-images.githubusercontent.com/61477100/83961806-ac6f0200-a88e-11ea-9fa3-3211a3a9840f.png)

If you then click Auto-Arrange it puts things where they should be.
![image](https://user-images.githubusercontent.com/61477100/83961815-ce688480-a88e-11ea-83b3-8f0c90f97d49.png)

Then click 'Slice Now' It is able to complete correctly
![image](https://user-images.githubusercontent.com/61477100/83961829-fce65f80-a88e-11ea-8905-c806a7b57bbd.png)

Hope this info helps

**Comment by thierryzoller** [comment]
Have had the same issue, you need to delete a few objects and push them further apart, then it works.

**Comment by supermerill** [comment]
please use File -> save as
then zip the saved .3mf file
then drop it here in a comment.

**Comment by paulhew69** [comment]
As requested

Regards,
Paul
[bridge_test with issue.zip](https://github.com/supermerill/SuperSlicer/files/4742092/bridge_test.with.issue.zip)
