### ISSUE TITLE
Superslicer crashes on clicking 'Add/Remove filaments' or 'Add/Remove Presets'

### ISSUE THREAD

**Issue by Herjanz** [supermerill/SuperSlicer#2720]
### Version
Version 2.3.57.12

### Operating system type + version
Arch Linux 5.17.3.arch1-1
X server, Budgie (Gnome)

### Behavior
Application crashes/terminates when I click (with either left or right mouse button) "Add/Remove Filaments" or "Add/Remove Presets" on top right. This happens in all simple/advanced/expert modes.

journalctl -r -n 40 gives: [https://pastebin.com/6VSx46JQ](https://pastebin.com/6VSx46JQ) 
'Add physical printer' works though. And in PrusaSlicer the 'Add/Remove' features still work.

**Comment by Herjanz** [comment]
@supermerill it actually does crash!

Dialog shown:
Title: SuperSlicer error
Msg: Internal error: boost::filesystem::directory_iterator::construct: No such file or directory [system:2]: "/usr/share/SuperSlicer/profiles"
Button: OK

on clicking "OK" application terminates

**Comment by Herjanz** [comment]
I added a new folder: sudo mkdir /usr/share/SuperSlicer/profiles
And now it doesn´t crash anymore.

**Comment by Herjanz** [comment]
@supermerill No, I do not have any presets. I thought it was weird since in PrusaSlicer I had a lot.

**Comment by supermerill** [comment]
I think it's better to uncompress the .tar instead of using the the appimage on your system.

**Comment by supermerill** [comment]
can't reproduce on ubuntu 22.04
still an issue?
