### ISSUE TITLE
Seam Sphere ignored

### ISSUE THREAD

**Issue by alexvonsiebenthal** [supermerill/SuperSlicer#2721]
### What happened?

Upgraded to 2.4.58.3
Now getting random seams despite setting a seam sphere
![19180F9B-AE53-4CBF-B4A7-C8C66226E21C_1_102_a](https://user-images.githubusercontent.com/6860125/163728761-2b7f10c0-9428-461f-9cd8-faa4a94fae78.jpeg)

### Project file & How to reproduce

[SeamSphereBug.3mf.zip](https://github.com/supermerill/SuperSlicer/files/8502265/SeamSphereBug.3mf.zip)

### Version

2.4.58.3

### Operating system

macOS 12.3

### Printer model

voron 2.4 / stealthburner

**Comment by alexvonsiebenthal** [comment]
Additionally (maybe worth another issue?), I cannot set any seam settings anymore: 
![image](https://user-images.githubusercontent.com/6860125/163729671-87288b17-ebdd-475b-89e2-9a59e9d8c6b5.png)

**Comment by alexvonsiebenthal** [comment]
@supermerill any update?

**Comment by hagan66** [comment]
I noticed this too, and it keeps me from using the 2.4 version.

**Comment by supermerill** [comment]
fixed in latest nightly

**Comment by alexvonsiebenthal** [comment]
Are the nightlies pre-compiled? If so, where can they be found?

**Comment by neophyl** [comment]
https://github.com/supermerill/SuperSlicer/actions  then select one of the builds for your system on the left.

For example for Windows https://github.com/supermerill/SuperSlicer/actions/workflows/ccpp_win.yml
