### ISSUE TITLE
Object sort Lowest Z not working

### ISSUE THREAD

**Issue by 0x3333** [supermerill/SuperSlicer#2725]
### What happened?

I try to set Object Sort(Sequential Printing) to Lowest Z, but it reverts back to Lowest Y, even when the UI says Z.

### Project file & How to reproduce

[stealthburner_toolhead_(dragon)-front-beta5.3mf.zip](https://github.com/supermerill/SuperSlicer/files/8507322/stealthburner_toolhead_.dragon.-front-beta5.3mf.zip)

1 - Set "Object Sort" to "Lowest Z"
2 - Slice
3 - See that the lowest z is not respected.
4 - Change profile, and go back, object sort is now lowest y

(I checked in the init file, it is set to `lowz`, but doesn't seem to fix it).

<img width="353" alt="image" src="https://user-images.githubusercontent.com/289289/163855158-473861c9-dc27-4da5-a8c6-f67e1e40123c.png">

<img width="254" alt="image" src="https://user-images.githubusercontent.com/289289/163855207-bfe61117-0f23-4652-94c9-8b545d353910.png">

<img width="190" alt="image" src="https://user-images.githubusercontent.com/289289/163855231-cf637826-0a71-4479-97e7-fc999f1bb6b5.png">

### Version

2.3.57.12

### Operating system

MacOS 12.3.1

### Printer model

Voron 2.4 with StealthBurner

**Comment by AudreyAP** [comment]
Lowest Y also seems to be broken in 2.5.59.2.
