### ISSUE TITLE
Milling post processing not working

### ISSUE THREAD

**Issue by LuisVinTM** [supermerill/SuperSlicer#2739]
**Bug description**
Iam using a E3D Tool Changer with a milling tool (T3, 4th tool). I am using theE3D config, downloaded from their Github. 
I have tried using the lastest release (2.3.57) and also an older one, the 2.3.55. The result is the same. One thing i can notice is that when i set the number of milling tool to "1", it automatically switches to 0 when i go to an other tab.

**Expected behavior**
Milling tool paths appearing in the gcode or the milling post processing appearing into preview. I see that some users had been using this option with success, and it is appearing in the preview.

!!>> Project File <<!!
The config and the project file:
[Superslicer milling test.zip](https://github.com/supermerill/SuperSlicer/files/8538829/Superslicer.milling.test.zip)

**To Reproduce**
1. Use the attzched config file
2. Click on slice
3. See error: No milling stage in the process (preview or gcode.)

**Screenshots**
Milling config:
![image](https://user-images.githubusercontent.com/94870715/164673538-4d260304-2d6a-4c81-9da9-2eb04fdf2410.png)

Slice preview:
![image](https://user-images.githubusercontent.com/94870715/164673141-085053c2-2604-49c3-9887-f40b552b5539.png)

General config, (switch millin tools to 0)
![image](https://user-images.githubusercontent.com/94870715/164673675-dd6d8032-031d-4143-82f6-8e731ab76b7c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [2.3.57]
 - E3D Tool Changer , Duet Wifi, Reprap

**Additional context**

**Comment by Creatorone** [comment]
### Version
Tested on SuperSlicer_2.4.58.4 and SuperSlicer_2.5.59.0 and a few older versions.

### Operating system type + version
Win10 Version: 21H2

### Behavior
The issue @LuisVinTM described still persists. I am running a Voron V0 and I was experimenting with a few things. When I add a milling cutter, the tool will appear in settings list, but once I try to access it, a error message pops up: 
![grafik](https://user-images.githubusercontent.com/56956950/188319078-da084010-ac3b-4de8-ae2a-0844527a5acc.png)
When continuing, the Slicer works fine but generates G-Code without the milling process. The Number of milling cutters is 0 again, once I switch back to the Printer Settings. I have tried to adjust settings in the following order:
1. Printer Settings -> Milling 1 (Error while clicking) -> Print settings -> Output Options (the Milling options here seem to stay)
2. Output Options (the Milling options here seem to stay) -> Printer Settings -> Milling 1 (Error while clicking)

Both result in the same behavior, where the output G-Code shows no milling moves.
