### ISSUE TITLE
No Z lift at first layer in some rapid movements

### ISSUE THREAD

**Issue by AMT3D** [supermerill/SuperSlicer#2745]
Hello!!

### Version
Superslicer 2.4

### No Z lift 
* Does anyone knows why at first layer some rapid movements doesn't lift the amount required. Is not and all movements I believe is mainly the case when filling gaps from one side to another side.
* Even using up to 5mm Z lift will not improve.
* This leave some marks in the first layer that in my case is the cosmetic view of the part. Parts are coming with good quality no mayor issue but i wonder why not do the Z Lift 
* Z lift 0.5mm
* Avoid crossing perimeters "ON"
* Not in first layer "Not On"
 Changing any combination of this settings doesn't change the outcome.
In the picture below you can see the rapid movement not lifting creating a small string of material.
Direct Drive with 2mm retraction @30mm/s 
![Rapid on first layer](https://user-images.githubusercontent.com/104287373/164954674-8f1a1849-ae92-4bb4-a792-d07acc77a977.JPG)

**Comment by neophyl** [comment]
You haven’t included the requested zipped up project when opening an issue. There are so many interactive settings that a project is required to debug most issues.

**Comment by AMT3D** [comment]
[Frame.zip](https://github.com/supermerill/SuperSlicer/files/8549561/Frame.zip)
Hello 
Sorry for that. 
Attached is the superslicer 3mf and the original STL

**Comment by supermerill** [comment]
seems fixed now.
reopen this if not.
