### ISSUE TITLE
Some print settings drive vase mode nuts and generate travels

### ISSUE THREAD

**Issue by sprior** [supermerill/SuperSlicer#2749]
### What happened?

I printed a large vase mode object with a 1.2mm nozzle and 0.8 layer height and found severe problems with the created gcode.  It generated travel moves through the print and the perimeters are also distorted in the gcode preview.  I have reproduced this in both 2.3.57.12 and 2.4.58.3 (nightly from a few days ago).  I then found that if I created a new print profile from a slightly different source I appear to generate ok gcode, but while I compared the settings for both I don't see anything which should cause such issues.

Attached are bad.jpg which shows the wonky gcode layers as well as the travel moves which shouldn't be there as well as good.jsp which appears fine.  Also bad.init.txt and good.init.txt which shows all the differences between the two files.  I'll also attach the original model stretchlet1.stl and the bad project saved from that with the bad settings.

![good](https://user-images.githubusercontent.com/3361800/164997794-0b0da8cf-a99b-4004-8369-fbaf12f67fb1.jpg)
00/164997790-950c9e8e-3877-4212-b6c4-7e079eca9628.jpg)
[good.ini.txt](https://github.com/supermerill/SuperSlicer/files/8550552/good.ini.txt)

[bad.ini.txt](https://github.com/supermerill/SuperSlicer/files/8550551/bad.ini.txt)

![bad](https://user-images.githubusercontent.com/3361800/164997862-0c3cba07-7eb0-4a24-9a07-9316c81416f8.jpg)

Note for the bad project I forgot to set bottom layers from 2 to 0 for the bad.jpg, but that doesn't change the behavior.

### Project file & How to reproduce

[project.zip](https://github.com/supermerill/SuperSlicer/files/8550549/project.zip)

### Version

both 2.3.57.12 and 2.4.58.3 (nightly from a few days ago)

### Operating system

Windows 10

### Printer model

Voron 2.4 with LGX

**Comment by sprior** [comment]
[updated_project.zip](https://github.com/supermerill/SuperSlicer/files/8550568/updated_project.zip)

Here's an updated project.zip which contains the full print settings for both bad and good.  Since Super Slicer seems to get confused enough to mangle the generated 3mf file you may have to recreate from the original stl which I've included.

**Comment by supermerill** [comment]
The problematic parameter is `gap_fill_last` (deactivate it)
I'll fix
