### ISSUE TITLE
BUG - Usage of "below" instead of above?

### ISSUE THREAD

**Issue by thierryzoller** [supermerill/SuperSlicer#275]
This confused me : )
Printer Settings ->  Machine limits - Usage Tab

It says : "If the setting below it checked" , shouldn't it be "if the setting **above** is checked" ?

**Comment by thierryzoller** [comment]
I just did some tests and yes it should say "above".

Also I would suggest clarifying "This tab" as I understood it as only the "Usage section".

**Comment by supermerill** [comment]
Do you have a suggestion on how i can rephrase it?

**Comment by thierryzoller** [comment]
I would completely relable it for clarity:

Title:  Machine Limits
Checkbox: Enable Limits
Description: The information below information is only used to calculate estimated printing time, unless you actually enable the option.

**Comment by supermerill** [comment]
Done.
I wrote "above" because i added the comment before the checkbox, it's strange that they show in the opposite order, i may have forgot to call something...
