### ISSUE TITLE
Weird perimeter lines underneath logos

### ISSUE THREAD

**Issue by Super-Matter** [supermerill/SuperSlicer#2752]
### What happened?

Bottom surface of a logo has weird perimeters where should be just 100% infill

### Project file & How to reproduce

![изображение](https://user-images.githubusercontent.com/60855176/165090367-80901372-6f14-496a-837a-4278314fa5e0.png)

![изображение](https://user-images.githubusercontent.com/60855176/165090352-d50369b8-1dfc-4401-89b0-924933151922.png)
[jeeep_logo.zip](https://github.com/supermerill/SuperSlicer/files/8554590/jeeep_logo.zip)

### Version

2.4..58.3 18.04.21

### Operating system

Win10

### Printer model

custom

**Comment by Super-Matter** [comment]
Thanks!

**Comment by supermerill** [comment]
note that you can just deactivate the "min width" from that option, it's enough to remove that artifact.
