### ISSUE TITLE
FR: flag to make timestamps in files optional

### ISSUE THREAD

**Issue by vajonam** [supermerill/SuperSlicer#2753]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add a flag/launch argument that will not create/update timestamps when writing out a config  file or print profile. I use git to manage the whole config folder and this creates a lot of extraneous changes, especially when I auto commit on a saved file. 

**Describe the solution you'd like**
Setting or Arg to not output or update the timestamp on the save of a config/print profie/ini file. 

**Describe how it would work**
Setting or Arg to not output or update the timestamp on the save of a config/print profie/ini file. 

**Describe alternatives you've considered**
None really.

**Additional context**
None.

**Comment by supermerill** [comment]
check your output options -> output filename format (expert mode).
remove `{timestamp}`

**Comment by vajonam** [comment]
Sorry this was not for the output file, this is for the config files / print profiles.

for example: 

```
# generated by SuperSlicer 2.3.57 on 2022-04-27 at 16:29:47 UTC
allow_empty_layers = 0
avoid_crossing_not_first_layer = 1
avoid_crossing_perimeters = 0
```
every time a setting is saved even it doesn't have any other changes it causes a commit for my auto-commit script.

**Comment by vajonam** [comment]
@supermerill 

Tried this works as I need to but sadly breaks moonraker/klipper version number parsing 

[moonaker](https://github.com/Arksine/moonraker/blob/3d9f5dc6d9d106973dc636b1512d0ce26720ce34/moonraker/components/file_manager/metadata.py#L302)

```
        aliases = {
            'PrusaSlicer': r"PrusaSlicer\s(.*)\son",
            'SuperSlicer': r"SuperSlicer\s(.*)\son",
            'SliCR-3D': r"SliCR-3D\s(.*)\son"
        }
``` 

which basically looks the ` on` string to determine end of the line and hence the version. So this feature will break that.. I am okay to revert this and live with my commits.. unless you are okay the leave the `" on"` text in there.

**Comment by vajonam** [comment]
the original issue is with config files rather than gcode output maybe can me only apply to settings file saves?

**Comment by supermerill** [comment]
I'll add the " on".
but I don't know why moonraker want to parse that. It can't be modified to `'SuperSlicer': r"SuperSlicer\s(.*)\s",` ?

**Comment by vajonam** [comment]
I know the same utils is used to generate both files, possibly can we remove the date only on the save files? if not I can work on co-ordinate a PR with both teams on better parsing. 

Thanks for adding back the "on" !
