### ISSUE TITLE
Single nozzle/Dual materials+Klipper Gcode flavor issues

### ISSUE THREAD

**Issue by Alonso3D** [supermerill/SuperSlicer#276]
SuperSlicer_2.2.51

Windows 10 64bit

Voron 2.2 running Klipper on Dual SKR 1.3 boards with RPi 3b+ and Dual extruders with single nozzle

1. Slicing preview fails to display colors for each extruder when set up for single nozzle with multimaterials (2ea in this case)

This seems to be correlated with the Gcode flavor as this problem does not occur when using Marlin Gcode flavor.
Using Marlin gcode flavor displays the colors for each extruder correctly.

2. The print errors out and cancels due to the gcode calling "ACTIVATE_EXTRUDER EXTRUDER=extruder0" in lieu of "ACTIVATE_EXTRUDER EXTRUDER=extruder" with klipper gcode flavor selected.
Perhaps it should be users choice what to name the extruder/tool within SuperSlicer or have it use standard tool change Gcode, such as T0 and T1, etc. Thus the user would need T0/T1 tool activation macros in their printer cfg file in order to use standard Tool switching gcode.

One should notice that klipper configs never have "0" in the name for when a single component is used. Numbers are used when multiple components are used such as steppers or heaters. 
e.g. - Stepper_z, Stepper_z1, Stepper_z2 and so 

<img width="1280" alt="Klipper flavored Benchy" src="https://user-images.githubusercontent.com/66043338/83978390-c2031c80-a8cc-11ea-97cc-98716177bf11.png">
<img width="1280" alt="Marlin flavored Benchy" src="https://user-images.githubusercontent.com/66043338/83978391-c29bb300-a8cc-11ea-82a1-4934293c77e3.png">

[Projects.zip](https://github.com/supermerill/SuperSlicer/files/4742780/Projects.zip)

3. @supermerill I just noticed strange behavior related to the wipe tower. After slicing it gives me a time estimate of 1270856d 21h 54m.
If I rotate the wipe tower the time estimate changes to -2147483648s. If I disable the wipe tower, then the time estimate becomes a sane 2h 5m.
[3DBenchy_-_Dualprint_-Marlin flavor_WIPE TOWER TIME.zip](https://github.com/supermerill/SuperSlicer/files/4743057/3DBenchy_-_Dualprint_-Marlin.flavor_WIPE.TOWER.TIME.zip)
<img width="1280" alt="time1" src="https://user-images.githubusercontent.com/66043338/83980843-85402100-a8de-11ea-9e40-a40b6cb5ec45.png">
<img width="1280" alt="time2" src="https://user-images.githubusercontent.com/66043338/83980844-85d8b780-a8de-11ea-9e06-eb12d3a456a2.png">

**Comment by supermerill** [comment]
right now, extruders doesn't have name. SO there is multiple possibilities:
 - add a name field, that can be a number (for marlin) or a string (for klipper)
or
 - detect when the right g-code is added in the toochange custom g-code and use this one instead of the auto-generated one.

in the meantime, i can remove the '0' for klipper.

**Comment by Alonso3D** [comment]
Extra name field for Marlin isn't necessary as T code for selecting tools is standard.

Klipper is the special case as it can go either way by using a standard command to activate extruder,  extruder1, extruder2 etc or it can use T tool change codes as long as the user has macros to support the T codes for tool changing. Perhaps have a check box when selecting klipper gcode flavor to have the option to use T codes or not(beginning with T0 like marlin)

**Comment by kackle1998** [comment]
Hello, I am also experiencing this issue, where I need to customize my T0, T1, T2...etc... otherwise will run into a crash.

**Comment by supermerill** [comment]
> Hello, I am also experiencing this issue, where I need to customize my T0, T1, T2...etc... otherwise will run into a crash.

Can you create a new issue, with project file...etc... otherwise I can't understand your problem.

**Comment by kackle1998** [comment]
> > Hello, I am also experiencing this issue, where I need to customize my T0, T1, T2...etc... otherwise will run into a crash.
> 
> Can you create a new issue, with project file...etc... otherwise I can't understand your problem.

Sure, I apologize, I'm new to Git. I'll make an issue.
