### ISSUE TITLE
Minimum extrusion length

### ISSUE THREAD

**Issue by guestisp** [supermerill/SuperSlicer#278]
is possible to add a setting to prevent very very short extrusions that most of the time would lead to blobs and artefacts ?

In example here:

![image](https://user-images.githubusercontent.com/3944655/84117126-51c1db80-aa31-11ea-8061-586aa419bf2f.png)

The "point" inside the circle is very very very short. With bowden setups and PETG, most of the time this is overextruded due to oozing and similiar.

Is possible to skip this , by setting a min length (in mm) somewhere?

**Comment by supermerill** [comment]
did you tried to increase gapfill -> min surface ?

**Comment by guestisp** [comment]
No, because it isn't a gap-fill, it isn't marked in white in the preview.

**Comment by supermerill** [comment]
oh, right. I'll make something to transform it to gapfill (that can be better printed or be eliminated).

**Comment by guestisp** [comment]
That would be perfect

**Comment by supermerill** [comment]
i've added a min length feature, but it's more to avoid congestion in serial communication.
can i have your .3mf to debug this?

**Comment by StrikeEagleCC** [comment]
I think the default value for this is a bit too conservative, and/or something changed between 2.3.52 and 2.3.55. In 2.3.55, a 50mm "arc" with minimum extrusion length set to the default of 0.035 results in 2mm line segments, and visible vertices on the arc surface. However, I like that the setting is there, so thank you.

**Comment by supermerill** [comment]
@StrikeEagleCC  I found recently a bug in the min_length feature, so now it should behave more sanely.

**Comment by JonBerlin** [comment]
Where can I find the **min_length setting**?

**Comment by neophyl** [comment]
Its under Printer Settings>General>Firmware>Processing Limit.
