### ISSUE TITLE
Bridge lines density values get modified each time you enter the width tab

### ISSUE THREAD

**Issue by celtare21** [supermerill/SuperSlicer#2782]
### What happened?

Long story short, everytime you click _Width & Flow_, the _min_ and _max_ values for _Bridge lines density_ as well as the _Simulate Prusa 'no thick bridge'_ toggle.
Picture for reference:
![Untitled](https://user-images.githubusercontent.com/29823626/166801486-88d52e27-5b0c-43a1-94f2-a356f2f6307f.png)

Important mensions: 
1) Only happens when you have  _Simulate Prusa 'no thick bridge'_ enabled.
2) I didn't change the values at all myself, nor do the values actually change. I.E: If I hit save, restart the slicer, go to _Width & Flow_ they're "modified" again but no value change 

### Project file & How to reproduce

In print settings:
1) Go to _Width & Flow_
2) Activate _Simulate Prusa 'no thick bridge'_ toggle
3) Save profile changes
4) Restart slicer
5) do 1) then observe the "modified" fields

### Version

2.4.58.3

### Operating system

windows 11

### Printer model

custom ender 5

**Comment by supermerill** [comment]
rounding issue, will fix
