### ISSUE TITLE
Milling options in Add settings

### ISSUE THREAD

**Issue by liftbag** [supermerill/SuperSlicer#279]
### Version
_2.2.51.1 Commit 7738e2a win10_
_2.2.51.1 Commit 055cfb8 macOS_

### Operating system type + version
_windows and macOS, linux not tested_

### Behavior
In the object browser editing, there is an "error" voice in Add settings.
<img width="580" alt="Schermata 2020-06-10 alle 11 30 16" src="https://user-images.githubusercontent.com/14921654/84251569-d5e99100-ab0d-11ea-8fca-003474795d73.png">

If you choose the "error" settings, the following windows is showed.
<img width="338" alt="Schermata 2020-06-10 alle 11 28 13" src="https://user-images.githubusercontent.com/14921654/84251653-f1ed3280-ab0d-11ea-98f9-3e63008135bb.png">

**Comment by supermerill** [comment]
yes, forgot to create the section name.
