### ISSUE TITLE
Infill/perimeters encroachment - inconsistent outcomes

### ISSUE THREAD

**Issue by TommyC81** [supermerill/SuperSlicer#2807]
### What happened?

Using different settings for Infill/perimeters encroachment yields wildly different top layer results.

Example images:

0% encroachment:

![Testpiece20 - 0 percent encroachment](https://user-images.githubusercontent.com/1904092/168460883-926c487e-36f4-4320-b93d-73aca6e8e1a9.png)

10% encroachment:

![Testpiece20 - 10 percent encroachment](https://user-images.githubusercontent.com/1904092/168460896-56e6a9a5-ada4-4e10-8dec-dbb40dc4df40.png)

15% encroachment:

![Testpiece20 - 15 percent encroachment](https://user-images.githubusercontent.com/1904092/168460903-98d780fc-6f47-4c49-9ce0-8d066b719665.png)

20% encroachment:

![Testpiece20 - 20 percent encroachment](https://user-images.githubusercontent.com/1904092/168460904-06e343ee-0234-4a20-b4d5-005e3d3da819.png)

25% encroachment:
![Testpiece20 - 25 percent encroachment](https://user-images.githubusercontent.com/1904092/168460910-b76c13e1-583f-4309-8a7f-941c65dd65cf.png)

### Project file & How to reproduce

Open attached project file, change "Infill/Perimeters encroachment" setting - observe top layer differences.
[Testpiece20.zip](https://github.com/supermerill/SuperSlicer/files/8694437/Testpiece20.zip)

### Version

nightly_dev (2e11c485266cf22987ae0f7be395df6a1295148c)

### Operating system

Windows 10

### Printer model

Creality CR6 with Sherpa Mini direct drive

**Comment by Sirnut** [comment]
I have been noticing issues like this as well, but on all solid surfaces like this:
![image](https://user-images.githubusercontent.com/67026260/168902252-fd9c7486-b9be-416d-8756-329864a5a598.png)
None of this started until I began tweaking the infill encroachment values, because I realized my horrible overextrusion on solid infill only was somehow related to it
I've gone ahead and attached the project file I'm working on at the moment. Please let me know if I should open a new issue, I just somehow feel like these are related
[Solid infill bug.zip](https://github.com/supermerill/SuperSlicer/files/8711303/Solid.infill.bug.zip)

**Comment by supermerill** [comment]
@Sirnut
i don't see anything in common.
if you want the top fill to be larger, increase the default anchor.

**Comment by Sirnut** [comment]
@supermerill sorry to bring this up again, but is the solid fill in this area not inappropriate?
Layer 22:
![image](https://user-images.githubusercontent.com/67026260/169106061-91064a1d-1281-4d5f-afd1-334390587b80.png)
Layer 23:
![image](https://user-images.githubusercontent.com/67026260/169105919-2f239e94-9273-422c-b625-2b266f345719.png)
Layer 24:
![image](https://user-images.githubusercontent.com/67026260/169105963-ecfe15ca-28ad-4f39-9e39-daafcdb0cac4.png)

In layer 23 you can see where there is gap fill and solid infill where the sparse infill should be placed

**Comment by supermerill** [comment]
that's not that issue. See #253 #1090

**Comment by Sirnut** [comment]
I'll look into that. Thanks Merill

**Comment by dehmlowm** [comment]
Thank you Super Merill. I noticed that this issue is about 50% better since upgrading to 2.5 ( its been a while since I upgraded). 

Wish there was a complete fix appreciate your contributions~
