### ISSUE TITLE
Unable to build current master_dev with -DSLIC3R_WX_STABLE=1

### ISSUE THREAD

**Issue by orjanekeberg** [supermerill/SuperSlicer#2832]
Recent changes in the master_dev branch (presumably commit b4e541c53) now gives an error when compiling src/slic3r/GUI/Plater.cpp when the system has the stable version of wxwidgets (3.0) installed.

The cmake flag -DSLIC3R_WX_STABLE=1 is supposed to allow building with wxwidgets-3.0, but Plater.cpp now needs a method "GetCurrentlySelectedFilterIndex", which does not seem to exist in 3.0.

I am running Debian GNU/Linux (stable), and everything has been working fine (both compiling and running) until this change.

**Comment by supermerill** [comment]
I'll remove GetCurrentlySelectedFilterIndex for linux. It's not supported on linux anyway.
