### ISSUE TITLE
Add a new language

### ISSUE THREAD

**Issue by AntoszHUN** [supermerill/SuperSlicer#2834]
So I did the first complete 100% Hungarian translation for a program called SuperSlic3r. A little more low-cost.

  - This translation is only the first version.
  - There is still room for improvement.
  - Translation and spelling errors may occur.
  "I did it all by myself, so it's up to me."
  - I am constantly checking and improving the translation.

I have attached the zip folder in which the necessary files are included. I hope someone can unite. I can't upload a folder.

Thanks!

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

[hu.zip](https://github.com/supermerill/SuperSlicer/files/8765619/hu.zip)

**Comment by AntoszHUN** [comment]
hmmm.

**Comment by supermerill** [comment]
merged, will be available in next nightly/release.
note: if the english text has '%%', that means it need to be doubled to output a '%', or it will crash.
same for '%1%%%'
