### ISSUE TITLE
Missing retraction on first layer

### ISSUE THREAD

**Issue by MarkoAnte** [supermerill/SuperSlicer#2836]
### Version
2.4.58.2

### Operating system type + version
Windows 10

### Behavior
* Missing retraction on first layer
* Make a box with cut out and toggle "Only retract when crossing perimeters" disabled
* First layer should have the same status at top layer
* No retraction happens when not crossing perimeters, making the extruder leak on long moves on large objects, leaking blobs on first layer. Those get printed over resulting in imperfections on bottom of parts.
  * Missing Retraction
![MissingRetraction](https://user-images.githubusercontent.com/32730948/170232310-69d6d13a-2aac-4418-9d56-7dd8262a266e.png)
  * Retraction forced with "Only retract when crossing perimeters" disabled. 
   ![Retraction](https://user-images.githubusercontent.com/32730948/170232527-97877894-f50b-4f11-9278-ce3b51ec45e6.png)

_Is this a new feature request?_
I think this is a bug. 

If its not a bug, it would be nice to have an extra option "Only retract when crossing perimeters" = Disable for first layer only. 

#### Project File (.3MF) where problem occurs
[RetractionFirstLayerProblem.zip](https://github.com/supermerill/SuperSlicer/files/8769816/RetractionFirstLayerProblem.zip)

**Comment by MarkoAnte** [comment]
I checked in PrusaSlicer. 

![RetractioninPrusaSlicer](https://user-images.githubusercontent.com/32730948/170284068-6e386335-07ab-4f02-a8bc-86a3f6950741.png)

This is with "Only retract when crossing perimeters" enabled. So I think its more of a bug then a feature to be.

**Comment by tome9111991** [comment]
could be true.
maybe related with
https://github.com/supermerill/SuperSlicer/issues/2802

**Comment by fungreenfox** [comment]
Is it solved? This issue is still present in version 2.4.58.4

**Comment by tome9111991** [comment]
> Is it solved? This issue is still present in version 2.4.58.4

you have a checkbox now to enanle retract on first layer
