### ISSUE TITLE
Bridge flow ratio only has an effect when bridge flow baseline is set to nozzle diameter

### ISSUE THREAD

**Issue by DKS-18** [supermerill/SuperSlicer#2837]
### What happened?

Trying to adjust bridge flow when i had similate prusa "no thick bridge" selected I noticed that no matter what setting I entered (tried all the way from 5% to 100%) the lines in the gcode visualiser would be the same width and the used plastic would stay the same.
this was also the case when "keep current flow" or "layer height" was selected as a baseline. without simulate prusa option selected.
When nozzle diameter is selected as baseline bridge flow responds correctly. Lines change width and printed part weight changes. i have attached screenshots to show that the settings have no effect.

### What behavior would i expect to happen?

I believe that you should be able to use bridge flow ratio regardless of what baseline calculation is used. it is often that we need to make a slight flow adjustment for different materials and i feel that this functionality is missing on these new flow baselines possibly because it is such a new implementation 

keep current flow:
![same flow 100s](https://user-images.githubusercontent.com/16251488/170297525-70e2bff0-4ae4-4a45-b1d0-0bd029fd66db.png)
![same flow 5](https://user-images.githubusercontent.com/16251488/170297533-51a79969-ee01-496a-8b7d-46d878a0c073.png)
![same flow 5s](https://user-images.githubusercontent.com/16251488/170297544-4865f97a-25be-4aea-b812-0ed7401396b1.png)
![same flow 100](https://user-images.githubusercontent.com/16251488/170297546-9f7e4e73-1332-4715-852b-719d267ddd95.png)

layer height:
![layer 100s](https://user-images.githubusercontent.com/16251488/170297867-e297e637-1925-4610-96c7-257530db2d95.png)
![layer 5](https://user-images.githubusercontent.com/16251488/170297874-56b4a348-3ded-4dfa-9f93-e28970bb7f69.png)
![layer 5s](https://user-images.githubusercontent.com/16251488/170297879-26bda6d3-5d94-427d-9089-a3d9cf121637.png)
![layer 100](https://user-images.githubusercontent.com/16251488/170297881-761b3416-4d38-41c0-8572-9fdc9ced4b18.png)

Nozzle diameter:
![nozzle dia 100s](https://user-images.githubusercontent.com/16251488/170297970-b7b1a43d-7820-4266-a939-4160c5ea632b.png)
![nozzle dia 100](https://user-images.githubusercontent.com/16251488/170297986-c28dd81f-3a92-4747-8fa1-e47b48c85faf.png)
![nozzle dia 5s](https://user-images.githubusercontent.com/16251488/170297984-5f5da334-098d-4a08-a14d-0d54b1f1d2a1.png)
![nozzle dia 5](https://user-images.githubusercontent.com/16251488/170297976-0c05a3a6-cc40-4dbf-89ae-55dd20fb985c.png)

### Project file & How to reproduce
[bridge flow 100mms.zip](https://github.com/supermerill/SuperSlicer/files/8783022/bridge.flow.100mms.zip)

![slicer version](https://user-images.githubusercontent.com/16251488/170298803-34113bb9-65a6-412b-8b39-a406d597c5db.png)

### Version

Version: 2.4.58.3 Build: SuperSlicer_2.4.58.3_2022-05-18

### Operating system

win 10

Edit due to people being distracted by the number 500

**Comment by tome9111991** [comment]
look at volumetric flow view?
![Screenshot 2022-05-26 194858](https://user-images.githubusercontent.com/57866234/170546227-5815a4bc-b643-4aa9-a1b1-4513ebb5c1a0.png)

**Comment by Jamin82** [comment]
> look at volumetric flow view? ![Screenshot 2022-05-26 194858](https://user-images.githubusercontent.com/57866234/170546227-5815a4bc-b643-4aa9-a1b1-4513ebb5c1a0.png)

using that view as you suggested confirms the issue that i brought up
here is using 5% flow
![5percent flow](https://user-images.githubusercontent.com/16251488/170604377-af2a2af2-ce45-4935-be53-66961891a2b8.png)


here is 500% flow
![500percent flow](https://user-images.githubusercontent.com/16251488/170604401-f91dd945-0a05-43e2-bc4b-4ee7c54887d0.png)

**Comment by jeedee23** [comment]
Yes I searched a lot for that, especially to have a good result.  Speed, temp, distance between the lines, etc all are in play to have a good result (result differs from view). If I gave you my settings, maybe they won't work with you. Difficult, but doable. I don't use the 'prusa' option. Just nozzle diameter , temp, speed and distance between lines are important. (this for Abs)

**Comment by Jamin82** [comment]
I have inspected even the gcode and the flow does not change unless you have selected nozzle diameter as the flow reference.

This is not about me looking for good print settings. This about functionality that is not working properly within the slicer

**Comment by jeedee23** [comment]
Can you send both project files? (save as ...3mf or ...amf) I tweak myself through the gcode with my own scripts afterwards, in order to achieve good results, but  it could be that I am inventing the warm water...

**Comment by jeedee23** [comment]
you can use this, SS will revert (as in many settings, in our favor) 
![image](https://user-images.githubusercontent.com/38980341/170824494-e07d1100-fb20-4c6f-bb79-062c47fa7ad8.png)

**Comment by Jamin82** [comment]
Have you read any or my issue that I filled out above.. I get the same extrusion rates at 5% as at 500%

**Comment by Jamin82** [comment]
Also when you use nozzle diameter it is possible to go above 100% as long as you use nozzle diameter as the flow reference.

So to summarise my whole reason for opening this issue:
Flow ratio behaves as expected when you use nozzle diameter as bridge flow reference.
It does not work as expected when you use keep current flow or layer height as flow reference

**Comment by jeedee23** [comment]
![image](https://user-images.githubusercontent.com/38980341/170825251-189d5bd4-c8a2-4ed2-b902-ecdba8135e4b.png)

I think I understand what you mean now, but is that an issue?

**Comment by jeedee23** [comment]
![image](https://user-images.githubusercontent.com/38980341/170825326-18b550f7-c6d7-46c3-856e-43b37cd6605e.png)

This is what you mean: so the values  below in the recatangle shoud be greyed out when choosing 'keep current flow'
![image](https://user-images.githubusercontent.com/38980341/170825388-7f128c62-e4f0-4b28-9e09-123c8f1b89db.png)

**Comment by jeedee23** [comment]
also in this case:
![image](https://user-images.githubusercontent.com/38980341/170825492-4e1631fe-000b-40b0-a41c-88a16896cf2c.png)

**Comment by jeedee23** [comment]
To confirm my 'saucage' reasoning:
![image](https://user-images.githubusercontent.com/38980341/170825697-a7824adb-2a4c-4749-beef-9270a5dd28a7.png)

**Comment by jeedee23** [comment]
but possible if you choose nozzle diameter, resulting in grinding extruder, here are your saucages:
![image](https://user-images.githubusercontent.com/38980341/170825898-4445f75d-b6b9-492c-a20f-e6eb8c0337f0.png)

**Comment by jeedee23** [comment]
> Also when you use nozzle diameter it is possible to go above 100% as long as you use nozzle diameter as the flow reference.
> 
> So to summarise my whole reason for opening this issue: Flow ratio behaves as expected when you use nozzle diameter as bridge flow reference. It does not work as expected when you use keep current flow or layer height as flow reference

Please accept my correction of your statement:

Flow ratio behaves as expected when you use nozzle diameter as bridge flow reference. It does not work, as expected, when you use keep current flow or layer height as flow reference, so the 'flow ratio' settings should be greyed out.

Do you agree on that?

**Comment by Jamin82** [comment]
No I do not agree with that at all. If I wanted to not be able to tune individually all parameters of flow I would use prusaslicer.
At its core superslicer is about having fine control of all parameters of your slicing.
If I want my bridging to be calculated off of layer height but then I would like a little more or less flow the bridging multiplier should work in the same fashion as it does when I select nozzle diameter as the basis for calculation

**Comment by jeedee23** [comment]
I think all of my above example show that you can indeed have fine control over bridging. If you want layerheight, then you can't adjust that because there is nothing below or above, so it's a cilinder with the diameter of the layerheight.  If you want the current flow as baseline, it will follow the flow you indicated in your settings. The only way to tweak and or refine is like I show here above.
The problem is that you think the settings can have influence where they can not, and that should be approached by greying them out.. You can tune anything you want, but you don't follow the logic.

**Comment by Jamin82** [comment]
Following your logic we should not be able to adjust bridging flow when it's selected as nozzle diameter. Because then it would no longer be the nozzle diameter

**Comment by jeedee23** [comment]
No you are wrong: you can choose 3 baselines :

1.  nozzle diameter (in your case 0.4 mm) you can increase
2. layer height  (in your case 0.2 mm) you can only decrease
3. keep current flow.  (in your case the perimeter flow of 0.48 mm * 0.2mm * 1mm = appr 0.1mm³/mm) you can only decrease
It is all very well (extremely well) explained in the pop-up help:
![image](https://user-images.githubusercontent.com/38980341/170852962-1d75c227-7ca5-40fc-b5b4-f2728f288eb6.png)

**Comment by Jamin82** [comment]
OK.. But why when I reduce flow on layer height or keep current flow does it have no effect?

**Comment by jeedee23** [comment]
you are right there:
![image](https://user-images.githubusercontent.com/38980341/170856792-9eb7710e-342a-4d03-b8a8-55e630ce6555.png)
![image](https://user-images.githubusercontent.com/38980341/170856810-0160c5d1-1b5a-431a-b242-96b443126428.png)

**Comment by jeedee23** [comment]
conclusion: there should be only one option present: nozzle diameter. the rest is obsolete

**Comment by Jamin82** [comment]
So you now finally understand why I named this very issue **Bridge flow ratio only has an effect when bridge flow baseline is set to nozzle diameter**

All the other points you have tried to discuss have nothing to do with the entire reason i opened this issue. It has taken you all these messages to finally get on to the target that i **CLEARLY** outlined in my very first post. That flow does not have en effect when you set the calculation based on layer height or current flow.

> conclusion: there should be only one option present: nozzle diameter. the rest is obsolete
Obsolete? You do realize that these additional options for flow calculation are brand new in the 2.4 beta build? And the fact that they are so new easily explains why the bridge flow modifier was likely overlooked in this new implementation (Again this is why i opened this issue to help point out this small bug in the brand new implementation of flow calculation)

![image](https://user-images.githubusercontent.com/16251488/170857423-531bd4c9-b914-4f71-8274-094850eff647.png)
I tried to point this out multiple times to you. But you insist on highlighting text from the tooltip for some strange reason. which again has nothing to do with the title and intent of the issue 

and not only that you have contradicted yourself multiple times in this thread:

first you say that i can only reduce flow when set to options not nozzle diameter
![image](https://user-images.githubusercontent.com/16251488/170857587-cf7e9317-19da-434f-9b03-cff7cf9f92c3.png)

then you say i cant change flow
![image](https://user-images.githubusercontent.com/16251488/170857571-942213ed-3d32-401f-84e7-ced4eed1d771.png)

Then you say i can only reduce flow again:
![image](https://user-images.githubusercontent.com/16251488/170857632-d882552e-5337-4a80-90d4-d9aea3f100ac.png)

**Comment by jeedee23** [comment]
You are right, but I used the tooltip as a base for my explanation.  But I remain with the fact that both other options are obsolete, if you can adjust the amount of bridging flow, speed and density, there is enough. A useful option would be: the longer the bridge the more the pressure advance system should work and the acceleration should be adapted. 
Anyway, thanks for your response and intelligent remarks. I think the programmers have enough to optimize this overtime.
Could you give your remarks to my opinion on this (another thing): https://github.com/supermerill/SuperSlicer/discussions/1800#discussioncomment-2842728
have a nice day!

**Comment by supermerill** [comment]
Sorry, i didn't read the psot, as the first one was enough to find & fix the bug. If there is another problem, please tell me.

**Comment by jeedee23** [comment]
It's ok, just check my question about even and odd layer perimeter width option please. If odd-even perimeter widths can change, structural behaviour is much better.
