### ISSUE TITLE
Part fan for bridges only

### ISSUE THREAD

**Issue by dmit2k** [supermerill/SuperSlicer#2872]
### Version
2.3.57.12

### Operating system type + version
MacOS

### Behavior
Not able to turn on part fan for bridges only, it also turns that on for all overhangs.

I'm priting with PETG which does not like part cooling (warping or getting poor interlayer adhesion) but overhangs are printing nice without cooling. Still for long bridges part cooling is required. But when I turn on fan for bridges it always turns on fan for overhangs. 

Please let me know if I miss something and there is a specific option for this.

**Comment by legend069** [comment]
that would be "overhangs_width_speed"

i'm currently working on more cooling options that should help with this problem.
