### ISSUE TITLE
Version 2.4.58.2 - Error messages displayed without lithuanian characters

### ISSUE THREAD

**Issue by GKucinskas** [supermerill/SuperSlicer#2876]
### Version
2.4.58.2

### Operating system type + version
Windows 11

### Behavior
This is the first time when I writing the issue - sorry about too little experience...
I translated user interface into Lithuanian language. Also translated the calibration html files (made copies and renamed, after adding "lt_" prefix). Also edited the source file "GUI_App.cpp" - added the 2195 line: "{ "lt",		"lt_LT", }," and recompiled project.
Now all works fine, interface showing corect Lithuanian characters, after switching to Lithuanian language calibration screens also switching into translated pages. 
One problem - error messages display text without Lithuanian letters - only question marks. 
During the translation of calibration files I noticed that these html cannot show lithuanian characters in superslicer browser (all other browsers works perfect), but after changing characters to their codes (for example: ą -> & # 2 6 1 ; (sorry for that type of writing - cannot find how to write non converting code) I can see lithuanian characters also in SuperSlicer. 
But in error mesages this solution not work - if I use clean lithuanian character (in translated and compiled SuperSlicer.mo file), I can see only question mark (ą -> ?). If I trying to write code instead of character, I can see only code, but not character ( & # 2 6 1 ; -> & # 2 6 1 ;).
Maybe there are some problems with error messages fonts? Or maybe somewhere is another source file with missing national character setting?
And question is - how I can solve this problem?

* _Steps needed to reproduce the problem_
Use lithuanian localisation files.
Try to put something big (bigger than bed size) on the bed. And there you can see message without national characters.
There are translated files (resources ->localization -> lt):
[SuperSlicer_lt.zip](https://github.com/supermerill/SuperSlicer/files/8879703/SuperSlicer_lt.zip)

* _Expected Results_
National characters in error messages

* _Actual Results_
screenshot
![Clipboard01](https://user-images.githubusercontent.com/105075878/173085530-dcd4bd9e-4cbd-49ef-ac4b-403619641321.png)

_Is this a new feature request?_ - No
Related guides for writing feature requests: http://meta.stackexchange.com/a/259196 http://nickohrn.com/2013/09/write-great-feature-request-bug-report/

#### Project File (.3MF) where problem occurs
_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here_

**Comment by supermerill** [comment]
That's because i have to set what font to use for Lithuanian  when drawing letters on the 3D canvas.

like for #5479
