### ISSUE TITLE
Missing M204 commands with Klipper

### ISSUE THREAD

**Issue by shiftingtech** [supermerill/SuperSlicer#288]
### Version
2.2.51

### Operating system type + version
Linux/debian testing
### 3D printer brand / version + firmware version (if known)
Voron2 with klipper 
### Behavior
I have a series of accelerations set in my profile, under Acceleration Control (Advanced).  If I have my printer type set to RepRap, a series of M204 commands are inserted into the gcode, adjusting the acceleration for various feature types. If, On the other hand, I set printer type to "Klipper"  only the very first M204 command appears, and the printer then stays at that acceleration for the entire print.
_Is this a new feature request?_
No
#### Project File (.3MF) where problem occurs

[voron_design_cube_v6.zip](https://github.com/supermerill/SuperSlicer/files/4774267/voron_design_cube_v6.zip)

**Comment by supermerill** [comment]
I though machines limits weren't used in the gcode, but it seems that i was wrong. Sorry for that.

machines limits : maximum acceleration while extruding is at 1500, so it stay at 1500 for all the print. Put a bigger value here.

**Comment by shiftingtech** [comment]
So there's probably a new bug there: machine limits not enforced in reprap
mode...

Still, that's awesome, and easy to fix.  Thanks for the quick response!

**Comment by TheMrCaveman** [comment]
how to remove machine limits from reprap profile. Don't want this and in prusaslicer this is automaticly disabled when choosing reprap. Mayby make it an option?

**Comment by supermerill** [comment]
They don't do anything, they just act as a failsafe in case your print profile isn't in sync with your machine one (reusing a profile with an other printer). Also, they are needed to compute a time estimate.

Prusa hide them, but they are always here.
