### ISSUE TITLE
Only one perimeter

### ISSUE THREAD

**Issue by espr14** [supermerill/SuperSlicer#289]
There's single perimeter for top solid infill. But it is useful for bottom solid infill and bridges as well. 
Bridge overlap works for infill only so removing extra bridge perimeters makes sense.

**Comment by supermerill** [comment]
for the bottom, you mean for every bottom or only on the first layer?

**Comment by espr14** [comment]
Are there other bottoms than first layer? Other bottoms are sliced as overhangs (bridges).

**Comment by supermerill** [comment]
All surfaces that don't have a layer printed below is considered as bottom. If you use a dissoluble filament for support with 0 offset, they are treated like on the build plate.

**Comment by espr14** [comment]
It makes sense for them as well.

**Comment by fwdixon** [comment]
yes, please!
