### ISSUE TITLE
i have issue to brim 

### ISSUE THREAD

**Issue by godbnc** [supermerill/SuperSlicer#2899]
![Untitled](https://user-images.githubusercontent.com/64687621/175975576-cf4f5825-5a2f-4a78-88ae-ed586612d8ee.png)
### Version
_Version of SuperSlicer used goes here (help->about)_  
Version 2.3.57.12

### Operating system type + version windows 7 64
_What OS are you using, and state any version #s_ 

### Behavior
* _Describe the problem_       the problem with brim no consistent to round 
* _Steps needed to reproduce the problem_
* _Expected Results_
* _Actual Results_
  * _Screenshots if useful_

_Is this a new feature request?_
Related guides for writing feature requests: http://meta.stackexchange.com/a/259196 http://nickohrn.com/2013/09/write-great-feature-request-bug-report/

#### Project File (.3MF) where problem occurs
_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here_

**Comment by supermerill** [comment]
please put here your project file so i can replicate

**Comment by godbnc** [comment]
https://www58.zippyshare.com/v/mewLwa0p/file.html

**Comment by godbnc** [comment]
25mb allow i have 35mb.... stl file

**Comment by supermerill** [comment]
it's the object file, not the project file.
you have to do File->save project and give me this file

**Comment by godbnc** [comment]
https://www.gfile.ro/?do=fD&fI=965a344b9e35472002cecb840949365b

is ok now :)
