### ISSUE TITLE
Prusa Slicer 2.5?

### ISSUE THREAD

**Issue by dingyifei** [supermerill/SuperSlicer#2905]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe how it would work**
Be as descriptive as your skill level allows you.

**Describe alternatives you've considered**

**Additional context**
Add any other context or paint drawing about the feature request here.

**Comment by neophyl** [comment]
I'm not the developer but I've been around here for awhile :)  Given that the merge of 2.4 still has outstanding issues and also given that Merill doesnt start porting a new version until its been officially released to avoid merging in bugs then I'd say its going to be awhile.
