### ISSUE TITLE
Solid infill overlap

### ISSUE THREAD

**Issue by espr14** [supermerill/SuperSlicer#291]
The Bridge overlap could be used for all (bottom, top, support) solid infills as well. I can imagine something like 400% overlap for top solid infill. This will create 0.1 mm paths (0.4 mm nozzle) that are hardly noticeable in comparison to standard infill. Moreover, it would push extra filament to the layer below instead of over the perimeter like in case of ironing.

**Comment by supermerill** [comment]
not convinced.
It's like a solution in search of problem.

**Comment by espr14** [comment]
It's an option.
