### ISSUE TITLE
With start_gcode_manual, some prologue is omitted that is hard for custom gcode to recreate

### ISSUE THREAD

**Issue by bjj** [supermerill/SuperSlicer#2916]
### What happened?

I turned on start_gcode_manual because I'm using klipper and I wanted to avoid generated M109 etc.

That code suppresses other things, in particular the initial retraction. The corresponding *deretraction* is still emitted in the code as usual. There is no variable with retraction length, so the custom start gcode must know the retraction length and must know it needs to have a retraction to balance the following gcode.

There are other things that are suppressed by that option which are important defaults (units: mm, absolute positioning) or are controlled by other slicer settings (such as relative E) that must occur in the custom start gcode for proper operation.

### Project file & How to reproduce

[20mm-box.zip](https://github.com/supermerill/SuperSlicer/files/9075681/20mm-box.zip)

### Version

2.4.58.2

### Operating system

windows 20

### Printer model

makergear m2 v3a with klipper

**Comment by rstanislav** [comment]
I have noticed this too, in print start i have purge sequence, but deretraction at start causes gaps on first layer, any solution to this ?
