### ISSUE TITLE
.mf3 files won't open 2.4.58.3 

### ISSUE THREAD

**Issue by 2Sondad** [supermerill/SuperSlicer#2939]
Clicking on .mf3 file does not force SuperSlicer to open.  Works on stable version.

**Comment by supermerill** [comment]
Most of them works for me, but i find one that won't launch.
It's a little piece of code added alone to "Conversion from older PrusaSlicer which applied brim separation equal to elephant foot compensation."
I missed it, and so it writes the opposite value, and so can't validate the config.
It's also unneeded, I'll delete that.
