### ISSUE TITLE
Mosaic: failed in wxBitmap

### ISSUE THREAD

**Issue by foreachthing** [supermerill/SuperSlicer#2940]
### What happened?

Any .png I've tried, all fail with the same message:

![image](https://user-images.githubusercontent.com/10420187/179154658-b0258f1b-dc5d-4236-ba83-ed7e51defda8.png)

### Project file & How to reproduce

Generate -> Mosaic from picture -> File... -> [OK] leads to crash.

### Version

2.4.58.3_win64_220714

### Operating system

Win106x4

### Printer model

Ultimaker 2

**Comment by supermerill** [comment]
can you give me your png?
mine are working.

**Comment by foreachthing** [comment]
Um ... trying different png at home now.
Do you have a size restriction? I got on 32x32 but it just shows white.

Any .png with transparency will crash.

Ok! I got this image 
![image](https://user-images.githubusercontent.com/10420187/179298715-35f12c2d-4fcd-4330-94fc-b71949aa612c.png)
working with these settings: 
![image](https://user-images.githubusercontent.com/10420187/179298792-eb2c70a3-fcdb-454b-b905-25bc87c073cb.png)

I didn't pay close enough attention to the settings - there was an offset still in place.
Also, on the first try, I've lost the generate button in the lower left corner.

Now I got to boost contrast so I won't need 102 extruders 😏

**Comment by supermerill** [comment]
in the second tab, you can define the acceptable colors (your spools).
Then, you can choose the function to merge colors.
