### ISSUE TITLE
SuperSlicer 2.4.58.3 no infill over bridge

### ISSUE THREAD

**Issue by aragor88** [supermerill/SuperSlicer#2955]
### What happened?

On the layer where is bridging and last solid bottom layer, there is no solid infill over bridge.

### Project file & How to reproduce

[longplank2.zip](https://github.com/supermerill/SuperSlicer/files/9134535/longplank2.zip)
At 3. layer is last solid bottom layer and bridge
![SSlicer](https://user-images.githubusercontent.com/84587110/179583024-cd4f7d76-d30e-41b2-991c-acd644096bdf.JPG)
When bridge is at different layer then last solid bottom layer, solid infill over bridge is correct
![SSlicer2](https://user-images.githubusercontent.com/84587110/179583032-4874d248-2912-4068-99fb-b31e1e46199f.JPG)

### Version

2.4.58.3

### Operating system

Windows 10

### Printer model

MK3S+

**Comment by supermerill** [comment]
set solid_over_perimeter (no solid infill over X perimeters) to 0

**Comment by TaffoFox** [comment]
I have the same issue. Set it to 0 for now.
