### ISSUE TITLE
Specific flow rate for overhangs

### ISSUE THREAD

**Issue by Pveska** [supermerill/SuperSlicer#2958]
**Is your feature request related to a problem? Please describe.**
Well, it's kinda problem, for me at least, because it degrades the quality of some model with overhangs.

**Describe the solution you'd like**
Ok so, we have an option to detect overhangs and apply specific speed/fan speed for them, and this feature caused me to use SS as main slicer, but there is one thing that just ruin this all. It's a flow handling. If SS detects overhang, it's applying flow rate from bridges for him, and this flow rate depends of "Bridge flow baseline":
- Nozzle diameter. Applies high flow rate for overhang, and just corrupt model while printing. 
How it looks on slicer:
https://i.imgur.com/nceEWcN.png
- Keep current flow. A bit fixing my problem, but still worse than "Layer height" option, because it applies highter flow than I need.
How it looks on slicer:
https://i.imgur.com/X9SlVXt.png
How it looks on printed model:
https://i.imgur.com/tfwNlmY.jpg
- Layer height. It fixing my issue, but brokes bridges flow and makes him very little.
How it looks on slicer:
https://i.imgur.com/lLdoQg3.png

**Describe how it would work**
Would be nice to add option to set specific flow rate for overhangs, or just keep current flow
So literally, I want it to be looks like a normal sliced layer, but with applied specific speed/fan speed.
https://i.imgur.com/5hk7odm.png

**Comment by tome9111991** [comment]
whats about to set 0 in overhangs threshold for Bride flow?

**Comment by Pveska** [comment]
> whats about to set 0 in overhangs threshold for Bride flow?

If you mean this section, then it just disabling overhangs detection, since his name kinda wrong
[https://i.imgur.com/epKLN81.png](url)

**Comment by tome9111991** [comment]
it just dissable the flow settings for overhangs.
you still have speed/fan 

you have to set Bridge speed and fan to % like 55%

**Comment by Pveska** [comment]
> it just dissable the flow settings for overhangs. you still have speed/fan
> 
> you have to set Bridge speed and fan to % like 55%

When I set it to 0, it just stop detects overhangs
[https://i.imgur.com/qq8bYTl.png](url)
[https://i.imgur.com/BNVlksH.png](url)
And fans speed section does nothing in this case
[https://i.imgur.com/Po00tTR.png](url)

**Comment by tome9111991** [comment]
it is because to have  Bridge speed and fan: 100
use  Bridge speed and fan: 100%

your % is missing

**Comment by Pveska** [comment]
> it is because to have Bridge speed and fan: 100 use Bridge speed and fan: 100%
> 
> your % is missing

Ahhh, yeah, I understand now, lul. Thank you so much for explaining!

**Comment by tome9111991** [comment]
btw
usw a lower value like 40% you have more detection

**Comment by Pveska** [comment]
> btw usw a lower value like 40% you have more detection

Yeah, I using 30% in most cases

**Comment by tome9111991** [comment]
but @supermerill 

i think there is a bug ?
Bridge flow will override bride speed and fan


for exp:
if your Bridge flow value lower as speed/fan
speed and fan still changes

**Comment by supermerill** [comment]
> if your Bridge flow value lower than speed/fan value
speed and fan still changes

yes, because you have to use bridge fan & speed when extruding with bridge flow.
It's useful when you set one settgin in % and the other in absolute.
