### ISSUE TITLE
[BUG] No Filament Cooling Control - on multiple Extruders

### ISSUE THREAD

**Issue by SphaeroX** [supermerill/SuperSlicer#2961]
### What happened?

I wanted to set the filament cooling for the PVA to 0% with my dual extruder. But unfortunately the settings are not applied during slicing.

It only works if I do it manually via the filament GCode....

### Project file & How to reproduce

Like the projectfile
![1](https://user-images.githubusercontent.com/6785110/180181196-0547cd40-696d-4a0e-bcd6-15a090ba94b4.jpg)

My Workaround now: 
![2](https://user-images.githubusercontent.com/6785110/180181205-c6a6cc0a-fca3-4c89-8738-f00523132ae4.jpg)

[no_fan_control.zip](https://github.com/supermerill/SuperSlicer/files/9158127/no_fan_control.zip)

### Version

Version 2.4

### Operating system

windows 11

### Printer model

Other

**Comment by supermerill** [comment]
Currently, the cooling is a post-process script that works on the generated gcode.
That's because the cooling buffer don't recognize `T1` as a toolchange command, as the toolchange command for klipper is 
`ACTIVATE_EXTRUDER EXTRUDER=1`
So it can't detect the extruder change, and so can't change it.

**Comment by supermerill** [comment]
won't rely ont he gcode only for next version.

**Comment by themacboy** [comment]
Good morning, Im not sure what that commit does. I look at the genereted code for my idex printer and I dont see any diference, in gcode. Probalby I missunderstood something, my english is very poor.

**Comment by themacboy** [comment]
Personally I control all that in klipper using a personal macro that I activate in every tool_change_gcode (i think all people do that way).
 But not sure if this commits improve something about this.
