### ISSUE TITLE
Recomended min wall thickness calculation

### ISSUE THREAD

**Issue by cfytrok** [supermerill/SuperSlicer#2968]
1. The recommended min wall thickness does not take into account width and spacing settings.
2. It doesn't show results for odd number of perimeters, like Prusa Slicer. Even if check "Thin walls".
3. Results are different with Prusa slicer. Who is right?
SuperSlicer:
![image](https://user-images.githubusercontent.com/29511727/180595484-43c5d486-5ba0-425d-b351-50e976a4a56d.png)
PrusaSlicer:
![image](https://user-images.githubusercontent.com/29511727/180595600-3ee7dda8-fbde-4823-a016-df847aa2db90.png)

**Comment by supermerill** [comment]
> The recommended min wall thickness does not take into account width and spacing settings.

it is, just checked.

> It doesn't show results for odd number of perimeters, like Prusa Slicer. Even if check "Thin walls"

it show the result up to the amont of periemter loop you set above.

> Results are different with Prusa slicer. Who is right?

I'm right, I spend a good amount of time to refine it.

**Comment by pedroloco2** [comment]
I did several tests and I think cfytrok recommendation may be correct. I clarify that I have not tried with thin wall.

**Comment by cfytrok** [comment]
> it is, just checked.

Sorry, it seems changing esternal perimeter width changes recomended thickness. But I changed default width and set other width to 0. According to the hint, external perimeter should use default width. And gcode preview confirms it. But Recomended thickness doesn't change.
![2022-07-23_23-41-41](https://user-images.githubusercontent.com/29511727/180622251-b5286416-a3af-43ce-a65d-86fd08ce3c7d.png)
![image](https://user-images.githubusercontent.com/29511727/180622235-c46e7faa-dd25-42dc-9f5c-ded24110b08e.png)

>it show the result up to the amont of periemter loop you set above.

Prusa slicer shows min thickness per line instead of per loop. It's more accurate.

**Comment by supermerill** [comment]
> Prusa slicer shows min thickness per line instead of per loop. It's more accurate. 1 loop=2 lines

you can't have an odd number of perimeter "lines" anyway in Prusaslicer, so there is no point.

> But I changed default

Right, it's not updated if using the default width. will fix.
Seems like the spacing text isn't updated as well when the default change.
