### ISSUE TITLE
FreeCAD python script on linux

### ISSUE THREAD

**Issue by mojamuto** [supermerill/SuperSlicer#2969]
### What happened?

I have FreeCAD installed, when I generate a script it tells me : 
"Error, freecad python (version 0.19 or higher) is not found in 'bin/python', please update the freecad python path in preferences".

![error 1](https://user-images.githubusercontent.com/36079583/180602625-b81c122a-d056-40bd-990b-e3be6ff6a5e9.png)

Check where FreeCAD is installed:

![freecad-problem](https://user-images.githubusercontent.com/36079583/180602718-48c9cf9c-3f2d-4b01-97c4-a11aee4df312.png)

I type the path in FreeCAD preferences path: /usr/lib/freecad.

![Captura de pantalla_2022-07-23_13-02-01](https://user-images.githubusercontent.com/36079583/180602654-a94adad6-36f9-4a9f-a08b-6d169e866422.png)

and it tells me this
Error, freecad python (version 0.19 or higher) is not found in '/usr/lib/freecad/bin/python', please update freecad python path in preferences.

![2](https://user-images.githubusercontent.com/36079583/180602721-c7ffc74b-1833-46d1-9435-374fb0e1f5fd.png)

What am I doing wrong?

### Project file & How to reproduce

...

### Version

2.4.58.3

### Operating system

void linux

### Printer model

prusa bear

**Comment by supermerill** [comment]
I don't remeber if it was really the case, but freecad can come with a python install.
I check, and there isn't one in the 0.19 on ubuntu22.04.
I'll change the software to revert to python3 system python if it can't find any freecad python.

In the meantime, you can create a symlink from `/usr/lib/freecad/bin/python` to your python3

**Comment by mojamuto** [comment]
that worked, thank you very much
