### ISSUE TITLE
Language localization not working and not available in the menu. Only for English

### ISSUE THREAD

**Issue by ositobio** [supermerill/SuperSlicer#297]
There is a problem in SuperSlicer 2.2.51 when you try to change the language. I only shows English.

Using Procmon I got the cause of the issue, and is that the files inside localization\XX are still called Slic3r++ while the new tool looks for SuperSlicer.

WORKAROUND: Rename the files inside your language to SuperSlilcer.po and SuperSlicer.mo (in my case, inside es for Spanish). Start SuperSlicer and choosing language should show up your language. 

![2020-06-15 15_56_12-Process Monitor - Sysinternals_ www sysinternals com](https://user-images.githubusercontent.com/43320706/84673497-af6a9200-af21-11ea-80f1-6c060b47a33f.png)
![2020-06-15 15_58_00-SuperSlicer_2 2 51 based on PrusaSlicer   Slic3r](https://user-images.githubusercontent.com/43320706/84673495-aed1fb80-af21-11ea-8905-78f288d59a36.png)

Hope this helps people and developers to correct it for future versions :)

**Comment by supermerill** [comment]
yes, see #273

**Comment by Anakinsw83** [comment]
Funciona!

**Comment by patrickb08** [comment]
Language Fr does not work by renaming
