### ISSUE TITLE
Update URL wrong

### ISSUE THREAD

**Issue by sanscorp1** [supermerill/SuperSlicer#2977]
### What happened?

![image](https://user-images.githubusercontent.com/33477802/180656587-9e9dfa0f-3456-4e3d-8b88-fa353658417c.png)

Updat link does not work, directs to:
https://github.com/supermerill/SuperSlicer/releases/tag/version_2.4.58.3

### Project file & How to reproduce

Click on update button.
Page not found, 404.

### Version

2.3.57

### Operating system

Windows 11

**Comment by supermerill** [comment]
yes, thanks for the report
https://github.com/supermerill/SuperSlicer/pull/2954
