### ISSUE TITLE
Skirt draft shield consuming massive time and filament

### ISSUE THREAD

**Issue by gswatkins** [supermerill/SuperSlicer#2978]
### What happened?

Enabling a draft shield significantly increases the time and filament usage estimates
<img width="366" alt="Screen Shot 2022-07-24 at 1 16 44 PM" src="https://user-images.githubusercontent.com/14927089/180658970-70a45543-3e85-452a-bf61-c444009d5ee9.png">
.

### Project file & How to reproduce

[Calibration cube.3mf.zip](https://github.com/supermerill/SuperSlicer/files/9176284/Calibration.cube.3mf.zip)
Steps to reproduce:
1. Generate a calibration cube
2. Enable draft shield in Print Settings -> Skirt & Brim
3. Slice

### Version

2.4.58.3

### Operating system

macos 12.4

### Printer model

vcore 3

**Comment by supermerill** [comment]
I don't have the same result on my 2.4.58.3

![image](https://user-images.githubusercontent.com/6536403/180664563-52293b4e-ca5d-460b-b32b-8a5c71fc9d7b.png)

**Comment by gswatkins** [comment]
Interesting. It happens reliably every time for me. Works as expected when I go back to 2.3.57.12. I even tried using presets to rule out any of my specific config settings:
<img width="1187" alt="Screen Shot 2022-07-24 at 5 54 12 PM" src="https://user-images.githubusercontent.com/14927089/180667428-c59442ed-8769-443f-9793-38bbfc014b18.png">
<img width="1235" alt="Screen Shot 2022-07-24 at 5 55 25 PM" src="https://user-images.githubusercontent.com/14927089/180667429-6f02b6a8-1ff8-4b5c-ac7e-da92ad1b226a.png">
Anything else I should try?

**Comment by supermerill** [comment]
You can try with the latest nightly, maybe it will fix itself.

**Comment by gswatkins** [comment]
The latest macOS arm nightly had failed, but I was able to build from source. I still see the same issue.

**Comment by ElliottBridge** [comment]
Maybe it's macos specific?

**Comment by supermerill** [comment]
can't reproduce with latest nightly, maybe it corrected itself.

**Comment by gswatkins** [comment]
I also tried with the latest nightly and it appears to be fixed. Thanks for your help.
