### ISSUE TITLE
Variable Layer Height Not Working in 2.4.58.3

### ISSUE THREAD

**Issue by LordFlashmeow** [supermerill/SuperSlicer#2979]
### What happened?

I have "Enable variable layer height feature" enabled in settings, but it's not working when slicing.

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/33206210/180670642-ed8e468d-9c9d-4110-ab4f-c0efa1a5d7a6.png">
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/33206210/180670662-ac821461-be74-489c-b9ea-e4d7baaad1c7.png">

### Project file & How to reproduce

[Stock-bearing04.3mf.zip](https://github.com/supermerill/SuperSlicer/files/9176951/Stock-bearing04.3mf.zip)

### Version

2.4.58.3

### Operating system

macos 12.4

**Comment by supermerill** [comment]
you can fix it for your model by stretching just a little bit to 30.01 height.

**Comment by inspectionsbybob** [comment]
NOT FIXED in 2.4.58.4....
Get a "Infill failed" message
