### ISSUE TITLE
Jerk and acceleration control disable

### ISSUE THREAD

**Issue by danis101** [supermerill/SuperSlicer#299]
### Behavior
*When I'm using acceleration and jerk control on slicer Im getting poor wall quality
Photo here - https://www.dropbox.com/s/3jx31wlfpg25auj/104232971_930928014091501_962199983343950252_n.jpg?dl=0
I mean those random lines that looks like layer shifts but they are here becouse of jerk and acceleration control
Without those settings walls look way better so for this moment I stuck with sloooooooow CURA with I don't really like
I would be glad just to have opportunity to disable acceleration and jerk control in slic3r++ (I like the way of support generating and infill)

_Is this a new feature request?_ Probably yes

**Comment by supermerill** [comment]
I think your concern has already been explained at issue #237

If you have some comments to do about the discussion, please comment on the #237 thread.

tip: on github, you can drag& drop your picture directly in the text area. You don't even need a file, you can "impr.sys" and then ctrl-v directly.

I'm going to close the issue, as further discussion should occur on the other thread. It doesn't mean i'm ignoring your problems, it's just a way to have a cleaner board when i search for soemthing.
