### ISSUE TITLE
VBO id assertion triggers in GUI/3DScene when slicing process finishes

### ISSUE THREAD

**Issue by dflemstr** [supermerill/SuperSlicer#3002]
### What happened?

Using version `2.4.58.3` of superslicer (packaged on arch linux as `2.4.58.3-2`), when I press the Slice button, and when slicing finishes/the view switches to a view of the sliced object, the following assert triggers:

```
superslicer: /build/superslicer/src/SuperSlicer/src/slic3r/GUI/3DScene.cpp:263: void Slic3r::GLIndexedVertexArray::render(const std::pair<long unsigned int, long unsigned int>&, const std::pair<long unsigned int, long unsigned int>&) const: Assertion `this->vertices_and_normals_interleaved_VBO_id != 0' failed.
```

Here's a link to the assert for convenience: https://github.com/supermerill/SuperSlicer/blob/f266b18176f8aec05553648c85e99a0039cd37bd/src/slic3r/GUI/3DScene.cpp#L263

This does not seem to happen with version `2.4.58.2` but maybe there are other factors that affect this bug.

I'm not sure what might lead to this state so please let me know if there's anything I can do to help debug.

### Project file & How to reproduce

(This happens for literally any object/configuration, e.g. just do `Right click -> Add Shape -> Box`)

### Version

2.4.58.3

### Operating system

Arch Linux

### Printer model

Voron 2.4 (klipper), Voron 0.1 (klipper), Prusa i3 MK3S (marlin), Jubilee (rrf)

**Comment by supermerill** [comment]
should be fixed with 3ce5d1a4e1ea3fce0a8f869cad581370a49e7dcd
