### ISSUE TITLE
ERROR at FreePySCAD 

### ISSUE THREAD

**Issue by Hashan0** [supermerill/SuperSlicer#3005]
### Version
2.5.59.0  (Nightly windows x64 #597)

### Operating system type + version
Windows 10

### Behavior

ERROR at FreePySCAD 

* _Describe the problem_
* _Steps needed to reproduce the problem_
* _Expected Results_
* _Actual Results_
  * _Screenshots if useful_

_Is this a new feature request?_
Related guides for writing feature requests: http://meta.stackexchange.com/a/259196 http://nickohrn.com/2013/09/write-great-feature-request-bug-report/

#### Project File (.3MF) where problem occurs
_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here
![Unbenannt-1](https://user-images.githubusercontent.com/101518551/181916324-6cf4c9cd-d034-4c7d-9658-e78f17917457.png)
_

**Comment by supermerill** [comment]
Can you make a screenshot with the slicer in english version?

**Comment by Hashan0** [comment]
Version 2.4.58.3 OK.

Version 2.5.59.0 crash due to error
![2 5 59 0_error](https://user-images.githubusercontent.com/101518551/182848858-1dbd5268-cde9-442e-a7c0-1663922f700f.png)

Have a test of FreeCAD-Path from "C:\....\FreeCAD 0.20" to nonexistent directory "C:\....\FreeCAD 0.21"  changed.

![Preference](https://user-images.githubusercontent.com/101518551/182854215-db45be00-3b33-459a-ba79-62784b4ee16b.png)


Error message Version 2.4.58.3
![2 4 58 3](https://user-images.githubusercontent.com/101518551/182853924-5af0c1e9-6577-4b7e-b6c4-8faae1f2206f.png)


Error message Version 2.5.59.0
![2 5 59 0](https://user-images.githubusercontent.com/101518551/182853990-1f4e143b-f2f3-4d81-93c1-7f7379fa4cf9.png)

**Comment by supermerill** [comment]
Dang, right. I forgot to remove the linux test.
