### ISSUE TITLE
Feature request - Z-hop and travel at the same time. 

### ISSUE THREAD

**Issue by simpat1zq** [supermerill/SuperSlicer#3019]
So I have tall prints that needs z-hop because sometimes a corner will curl up or something and the print would get knocked over without zhop. 

However, because of zhop, it leaves tiny wisps of stringing. If I disable z-hop, there is no stringing at all. I think is is because the printer pauses, goes straight up, and then travels. 

I would love for there to be a feature that does the z travel at the same time as the travel. There would of course need to be some considerations. The vertical move would need to start just after it leaves the print, and it would need to be at max height before it crosses anything on th
![Untitled](https://user-images.githubusercontent.com/22940871/182456939-c56430d0-33e5-4e7b-8af1-e2814b5d1dd2.png)
e layer or 2 below the current layer. 

Not only would something like this create cleaner prints, it should shave off a few minutes on prints using z-hop. The second or so it takes to do the zhop would pretty much be cut down to 0.  

I've attached a picture of what I'm trying to say here.

**Comment by neophyl** [comment]
Sounds a lot like https://github.com/supermerill/SuperSlicer/issues/927

**Comment by simpat1zq** [comment]
You're right. I'll close this one and move some of this info into that one. I searched for z-hop and it didn't pick up that one in the search.
