### ISSUE TITLE
bridge infill interrupted by overhang perimeters resulting in mid air print

### ISSUE THREAD

**Issue by rolandjohann** [supermerill/SuperSlicer#3027]
### What happened?

As seen in the pictures I want to print a cylinder with a cutout cylinder from the inner bottom that gets smaller after some layers. To achieve that without supports, I inserted an artificial layer acting as bridge where the small diameter cylinder cutout perimeters can be printed on. Unfortunately the slicer doesn't treat the bridge as bridge only, but interrupts it with overhang perimeters.

Can someone explain what's happening here and if it's solvable by tweaking settings, or if it's a bug?

EDIT: loading PrusaSlicer with the attached project file results in an expected sliced object: the artificial layer has been sliced as one single feature resulting in complete lines acting as brindge.

<img width="1220" alt="Bildschirmfoto 2022-08-04 um 18 22 07" src="https://user-images.githubusercontent.com/5725466/182905067-14000f78-427b-44bf-b44a-7c86ac828d0f.png">

### layer 48
<img width="755" alt="Bildschirmfoto 2022-08-04 um 18 20 25" src="https://user-images.githubusercontent.com/5725466/182905088-38274cb4-67b0-4d18-8243-3e618d4e9bfd.png">

### layer 49
<img width="625" alt="Bildschirmfoto 2022-08-04 um 18 19 58" src="https://user-images.githubusercontent.com/5725466/182905110-103827f3-53ce-4b99-bd88-e8c5bf96faba.png">

### layer 50
<img width="761" alt="Bildschirmfoto 2022-08-04 um 18 20 30" src="https://user-images.githubusercontent.com/5725466/182905129-7e12c869-7b5e-4a6f-b5b2-46fa782f6fd5.png">

### Project file & How to reproduce

[adapter_problem.3mf.zip](https://github.com/supermerill/SuperSlicer/files/9261615/adapter_problem.3mf.zip)
Slice and navigate to layer 49

### Version

2.4.58.3

### Operating system

macos 12.1

### Printer model

RatRig V-Core 3

**Comment by Pavulon87** [comment]
Maybe try to reduce layer height or increase artificial layer height, or change `No perimeters on bridge areas` to `Fill the voids with bridges`.

49:
![49](https://user-images.githubusercontent.com/23641103/183007360-0907328f-f745-4900-b7c9-c135cb0b3c4e.png)

50:
![50](https://user-images.githubusercontent.com/23641103/183007374-30fe828b-55e1-4ff1-a0dd-3e8d364c18e4.png)

**Comment by rolandjohann** [comment]
@Pavulon87 thanks a lot. That resolves it.

Can you explain why superslicer behaves like this and we need to take care about bridges with perimeters manually? I want to understand the slicer better.

**Comment by supermerill** [comment]
You have "only one perimeter on top" activated.
This setting works by detecting areas with top surface and excluding them from the perimeter generation.
Here your sacrificial layer is a single layer, and so contain a top surface. Perimeters will be created where the top surface ends + 'default infill anchor'.

* If you increase the default anchor (to 350%) , the perimeters are so pushed that they go outside of the bridge and disappear.
* Or if you remove the 'only one perimeter on top' (for all layer or only this one with a height range modifier), the problem disappear.
* Or if you use the 'No perimeters on bridge area -> fill the voids' like said on the answer above, then it will create a sacrificial layer even if the model doesn't have one! (you can also apply it only at the layer you want with a height range modifier)

**Comment by rolandjohann** [comment]
@supermerill thanks for the explanation. The problem is now clear to me.
