### ISSUE TITLE
Wipe tower brim width incorrectly calculated

### ISSUE THREAD

**Issue by Pavulon87** [supermerill/SuperSlicer#3031]
### What happened?

Previous versions of SuSi had the default value of 150% and everything was fine(now it is 2mm).
But in latest build something is wrong in calculation algorithm and brim could be bigger than a build plate when using percentage value.

150%
![brim150](https://user-images.githubusercontent.com/23641103/183009489-577a2e56-b797-4b3e-b611-648a6026ea2e.png)

15%
![brim15](https://user-images.githubusercontent.com/23641103/183009478-f9d00250-2c93-409d-90f2-8466de64b89b.png)

### Project file & How to reproduce

[Shape-Box.zip](https://github.com/supermerill/SuperSlicer/files/9265674/Shape-Box.zip)

### Version

2.4.58.3 / 2.5.59.0

### Operating system

windows 10

### Printer model

not relevant

**Comment by Pavulon87** [comment]
I'm not sure, but maybe the point is that percentages are used as mm?
```
m_wipe_tower_brim_width(float(config.wipe_tower_brim_width)),
(...)
size_t loops_num = (m_wipe_tower_brim_width + spacing / 2) / spacing;
```

Previously:
`double unscaled_brim_width = m_config->wipe_tower_brim.get_abs_value(m_nozzle_diameter);`

**Comment by supermerill** [comment]
Correct. Maybe another merge quirk.
Merged for next nightly
