### ISSUE TITLE
Arachne inconsistency.

### ISSUE THREAD

**Issue by Dx-Dx-Dx** [supermerill/SuperSlicer#3032]
### What happened?

I find SS's Arachne unusable:
![image](https://user-images.githubusercontent.com/102039778/183074206-173eb5f0-2821-4e39-a20f-36466078cbe9.png)
PrusaSlicer looks much better:
![image](https://user-images.githubusercontent.com/102039778/183074486-f10064b4-decc-42f4-ace3-57a588e503d0.png)

Settings between SS and PS seems to be the same.

### Project file & How to reproduce

[TriHorn Duct Default.zip](https://github.com/supermerill/SuperSlicer/files/9268428/TriHorn.Duct.Default.zip)

### Version

Version: 2.5.59.0 Build: SuperSlicer_2.5.59.0_2022-08-05

### Operating system

Win7 64

**Comment by supermerill** [comment]
working the same if I use the code only avaialble at the alpha3 time.
There is something in prusa fix or (more probable) in my fixes that mess it up.

**Comment by supermerill** [comment]
if you deactivate the overhangs detection, it returns back to normal.

**Comment by supermerill** [comment]
should be fixed in the next nightly (currently ubuilding)
forgot to tag it.

**Comment by Dx-Dx-Dx** [comment]
Tnx, looks good. How it is better than classic is not apparent but arachne at least can be faster.
![2022-08-08 19 18 09](https://user-images.githubusercontent.com/102039778/183466300-4f56167f-4447-40ec-9334-ad24636515fd.jpg)

**Comment by locki-cz** [comment]
It is fixed?

![image](https://user-images.githubusercontent.com/30490842/189540484-a75667cd-ea18-44d0-97b3-d6ed481b6b74.png)

**Comment by supermerill** [comment]
> It is fixed?

what?
