### ISSUE TITLE
App not opening on Mac

### ISSUE THREAD

**Issue by jimmyD30** [supermerill/SuperSlicer#3038]
### What happened?

Hello, the latest app version is not opening on Mac.

### Project file & How to reproduce

Install app onto Mac then try to open it.

### Version

2.4.58.3

### Operating system

Mac OS 11.6.5

### Printer model

Custom with Klipper

**Comment by mlowin63** [comment]
same here

**Comment by hairydalek** [comment]
I get the following error:
Internal error: basic_string

This is when the splash screen is displayed
<img width="1003" alt="Screenshot 2022-08-07 at 12 00 33" src="https://user-images.githubusercontent.com/9365378/183287550-cd6d1622-3209-487d-9332-363f4c356b41.png">
.

**Comment by supermerill** [comment]
intel version on intel mac?

**Comment by jimmyD30** [comment]
> intel version on intel mac?

For me, yes.

**Comment by hairydalek** [comment]
Yes, Intel Mac and Intel version.

**Comment by jimmyD30** [comment]
So latest release version 2.3.57.12 works, but not the latest daily. Here is my macbook pro info:
<img width="588" alt="Screen Shot 2022-08-07 at 5 33 27 PM" src="https://user-images.githubusercontent.com/36546847/183311758-035ff9a1-533f-4767-a125-92f3f76dd540.png">

**Comment by jimmyD30** [comment]
This is the error i get with 2.4.58.3:
<img width="267" alt="Screen Shot 2022-08-07 at 5 43 37 PM" src="https://user-images.githubusercontent.com/36546847/183312086-472a5e73-8f55-4d36-974a-3cc854a9f18a.png">
:

**Comment by supermerill** [comment]
should be fixed in latest release, can you test?

**Comment by jimmyD30** [comment]
> should be fixed in latest release, can you test?

Hi, yes, will try in a day or two, thank you!

**Comment by jimmyD30** [comment]
> should be fixed in latest release, can you test?

She opens and slices (did not try gcode output yet), but I get this error message:
<img width="1373" alt="Screen Shot 2022-08-24 at 7 53 36 AM" src="https://user-images.githubusercontent.com/36546847/186412317-d3707c88-37ed-4b2d-bfae-a83bed402493.png">

**Comment by boksbox** [comment]
SuperSlicer_2.4.58.5_macos_220924 opens but refuses to stay open.  Mac OS 10.6.2
