### ISSUE TITLE
arachne is make under extrusion width

### ISSUE THREAD

**Issue by wonsuhna1** [supermerill/SuperSlicer#3043]
### What happened?

![ㅣ 2022-08-08 06 40 21](https://user-images.githubusercontent.com/104687650/183312374-179ef4bc-7c02-44b4-a7f0-6fd4b7315b7a.jpg)

![ㅣ 2022-08-08 06 40 2ss1](https://user-images.githubusercontent.com/104687650/183312377-d56f2ed4-d626-44e2-ae3f-0ddffc446390.jpg)

0.6 nozzle, 0.65~0.7 extrusion width
like that image,
perimeter is under extrusion width problum.
Doesn't match the shell

what happend?

It has been confirmed that this problem does not occur with prusaslicer.

### Project file & How to reproduce

[temp Mo.zip](https://github.com/supermerill/SuperSlicer/files/9277654/temp.Mo.zip)

### Version

nightley

### Operating system

windows10

**Comment by supermerill** [comment]
there is currently a bug in the arachne: the widths are wrong. fixed in next nightly, can you check it tomorrow?

**Comment by wonsuhna1** [comment]
> 현재 아라크네에 버그가 있습니다. 너비가 잘못되었습니다. 다음 밤에 수정, 내일 확인할 수 있습니까?

yes, - thankyou!

**Comment by pemerick07** [comment]
When I tried Arachne it required an EM of 1.2 to get to the same measured part weight that I got from Classic with an EM of 1.075. I found this issue and tested the 05585fd nightly which seems to have resolved it - Thanks!

Note the Used Filament.

**2.5.59 Classic with 1.075 EM**
![image](https://user-images.githubusercontent.com/243142/188968235-37f51ba7-724e-4cdd-b4a3-8a1f4777e598.png)

**2.5.59 Arachne with 1.2 EM**
![image](https://user-images.githubusercontent.com/243142/188967735-6cf5e471-8993-40df-92da-da9533e66442.png)

**Nightly with 1.2 EM**
![image](https://user-images.githubusercontent.com/243142/188967315-8274223b-7b0d-4c44-9390-a861bf802d26.png)

**Nightly with 1.075 EM**
![image](https://user-images.githubusercontent.com/243142/188967941-ba8837fb-ee4a-41e2-a68c-e6551d67605c.png)
