### ISSUE TITLE
Arachne , infilled bottom layer with monotnic/filled

### ISSUE THREAD

**Issue by jesterhead82** [supermerill/SuperSlicer#3046]
### What happened?

On todays nightly, active one perimeter in first layer, bottom monotonic filled.

Can be fixed by chosssing monotonic fill (so small area gets filled), or by deselecting single perimeter on first layer.

![image](https://user-images.githubusercontent.com/11690785/183348410-84f4e90c-1228-4612-9a28-85e230865c27.png)
[Uploading 3D4U_Coffee_Clip_Standard_V2.zip…]()

### Project file & How to reproduce

Small features dont get filled by "filled" infill

### Version

2.5.59.0 nigtly

### Operating system

Win10

### Printer model

Other

**Comment by supermerill** [comment]
I think your link is broken. can you try again to add it?

**Comment by jesterhead82** [comment]
[3D4U_Coffee_Clip_Standard_V2.zip](https://github.com/supermerill/SuperSlicer/files/9280415/3D4U_Coffee_Clip_Standard_V2.zip)

sure

**Comment by Dx-Dx-Dx** [comment]
It seems all filled infills are no longer.
![image](https://user-images.githubusercontent.com/102039778/183469239-fbc91c90-2a1c-4912-8b88-433aaa47bbd8.png)
Especially noticeable on concentric infill - in classic mode both concentric and concentric filled are almost the same. In arachne mode concentric infill is arachned and looks good but concentric filled is not and not filled.

**Comment by Dx-Dx-Dx** [comment]
[heartgear8.zip](https://github.com/supermerill/SuperSlicer/files/9283605/heartgear8.zip)
Version: 2.5.59.0
Build: SuperSlicer_2.5.59.0_2022-08-07

**Comment by supermerill** [comment]
@Dx-Dx-Dx fixed
