### ISSUE TITLE
Aligned Seem doesn't work correctly?

### ISSUE THREAD

**Issue by TjardF** [supermerill/SuperSlicer#3047]
### Version
Version: 2.4.58.3
Build: SuperSlicer_2.4.58.3_2022-07-13

### Operating system type + version
Mac OS Catalina 10.15.7 (19H1030)
### Behavior

I inserted this Part to SuSi, its from Voron Design, Trident Build current Version and sliced it, my default setting is aligned Z Seam, but the seam doesn't align. not at all. in the full print.
In each hole etc

![Bildschirmfoto 2022-08-08 um 17 54 10 PM](https://user-images.githubusercontent.com/37928929/183460986-235554d2-e7f8-42f2-adbd-3389f087088c.png)

#### Project File (.3MF) where problem occurs
[zSeam.3mf.zip](https://github.com/supermerill/SuperSlicer/files/9283237/zSeam.3mf.zip)

**Comment by locki-cz** [comment]
In latest PS 2.5.0 Alfa 3 are seams so nice! Also drawed seam is aligned very nice. Can it be imported to SS?

**Comment by supermerill** [comment]
> In latest PS 2.5.0 Alfa 3 are seams so nice! Also drawed seam is aligned very nice. Can it be imported to SS?

Will be merged

**Comment by locki-cz** [comment]
still buggy - not fixed in today version
![image](https://user-images.githubusercontent.com/30490842/183881234-285fc3f9-326f-4456-baa6-1e6c7f2d3894.png)

![image](https://user-images.githubusercontent.com/30490842/183881307-e4de455a-2104-41dc-a135-8ebd92606d54.png)

**Comment by supermerill** [comment]
It work on the provided project file.
you can use a seam-sphere if you want a precise control over it.
also, did you try the "contiguous" ?

**Comment by locki-cz** [comment]
Yes used Contiguous. Arachne destroy it, also my drawed line is ignored :) 
[[a]_stealthburner_main_body.zip](https://github.com/supermerill/SuperSlicer/files/9299937/a._stealthburner_main_body.zip)
Seam-sphere

**Comment by supermerill** [comment]
> Seam-sphere? Googled but not found anything related.

https://github.com/supermerill/SuperSlicer/search?q=seam+sphere

right-clic -> seam

**Comment by locki-cz** [comment]
Oh this is interesting but useless in this case, it make seam on both sides :(

![image](https://user-images.githubusercontent.com/30490842/184109386-20c7920e-74c5-4c59-8dfa-d6f84c0b39f1.png)

in prerelase it is stil broken, ignoring drawed position
![image](https://user-images.githubusercontent.com/30490842/184109806-d72938d3-82a4-44d5-b117-2cb61a494d8e.png)
![image](https://user-images.githubusercontent.com/30490842/184109894-b45d032d-8f17-4219-91fe-5461f8715188.png)

But I must say, other is alligned really awesome way!

**Comment by supermerill** [comment]
I forgot. Tu use the aligned, you should only put a little painted seam in the first layer(s). It will follow on from here.

**Comment by locki-cz** [comment]
I dont know about this! There sould be something like tips about how to use some feacures :)
Perimeter generator: classic
![image](https://user-images.githubusercontent.com/30490842/184223778-1c5e1d1d-c9d2-408a-859a-145570f3c72f.png)

Perimeter generator: arachne  is broken :( 
![image](https://user-images.githubusercontent.com/30490842/184223979-9ac98474-2604-4e6d-9612-46a44b89b74a.png)
