### ISSUE TITLE
Brim height not respecting first layer height when expressed as percentage

### ISSUE THREAD

**Issue by Wil-Storch** [supermerill/SuperSlicer#305]
### Version
SuperSlicer v2.2.5.1

### Operating system type + version
Win 10 LTSB v1607

### 3D printer brand / version + firmware version (if known)
Creality Ender 3 profile 0.4mm nozzle, Klipper firmware (using Marlin as g-code flavour)

### Behavior
* _Describe the problem_
When using an initial layer height expressed as a percentage (in this case 75%) the Brim layer height is too large. A 0.4mm nozzle results in a 0.42mm high brim height, rather than 0.3mm as expected.
The 0.3mm value is respected for other line types - skirt and support in this case.

* _Steps needed to reproduce the problem_
Set initial layer height as a percentage
Enable brim

Expected behaviour: 0.3mm brim height
![image](https://user-images.githubusercontent.com/34592159/84613302-59d4bc00-af06-11ea-8410-39ef4ad939b8.png)
Actual behaviour: 0.42mm brim height
![image](https://user-images.githubusercontent.com/34592159/84613397-6f49e600-af06-11ea-8531-c022ebca2f78.png)

_Is this a new feature request?_
No

#### Project File (.3MF) where problem occurs
Can toggle between 0.3mm and 75% initial layer in attached file
[Percentage1stLayer_Bugreport.zip](https://github.com/supermerill/SuperSlicer/files/4808698/Percentage1stLayer_Bugreport.zip)

**Comment by supermerill** [comment]
seems to be a visualisation issue, the gcode extrude the whole first layer at 0.3mm height in the gcode.
