### ISSUE TITLE
Could the new "contigous" seam follow the seam sphere?

### ISSUE THREAD

**Issue by hagan66** [supermerill/SuperSlicer#3058]
I just love how smooth the new contigous seam is, I just want to be able to place it where I want without rotating the model. 

Thanks, and fantastic work btw!

/robert

**Comment by supermerill** [comment]
I don't understand the issue.
The seam sphere has priority over the seam algorithm.
Can you explain more? with pictures, or/and project file?

**Comment by hagan66** [comment]
OK, what I mean is that the contiguous seam is much more in-line-smooth than the seam-sphere-seam. 
I would like to place the contiguous seam in any direction, like with a seam sphere. :-)

![Skärmavbild 2022-08-28 kl  14 51 08](https://user-images.githubusercontent.com/9168083/187075839-68c8fa3b-e731-4ddd-8d99-ce3b1e3a6917.png)


![Skärmavbild 2022-08-28 kl  14 52 38](https://user-images.githubusercontent.com/9168083/187075846-a713a31c-a489-46d7-a933-2575cf0c4094.png)

**Comment by supermerill** [comment]
Understood.

Did you try to put a little dot of seam paint (the left widget) just at the very bottom of where you want it to go?

![image](https://user-images.githubusercontent.com/6536403/187083614-f2641d01-dd9f-4467-9dcd-7b911dce123f.png)

**Comment by hagan66** [comment]
I tried it now. It works with ”aligned” but not with ”contiguous”.
