### ISSUE TITLE
Link to PrusaSlicer download page is shown when new version o SuperSlicer is detected

### ISSUE THREAD

**Issue by MrDix** [supermerill/SuperSlicer#3069]
### What happened?

I have SuperSlicer 2.4.58.3 installed and it shows that there is a new version 2.4.58.4 available for download on application start. If I click on the shown link my browser opens PrusaSlicer Download page and not the SuperSlicer download page.

![image](https://user-images.githubusercontent.com/22680551/184510066-8b353f8f-883e-4c78-9f51-b081cd6d0c1a.png)

![image](https://user-images.githubusercontent.com/22680551/184510093-3848c323-98c8-4091-a7b2-cc44dbff8053.png)

![image](https://user-images.githubusercontent.com/22680551/184510111-d7900f45-ad4d-4796-bc58-4e67130b11f8.png)

### Project file & How to reproduce

Install SuperSlicer version 2.4.58.3 or SuperSlicer 2.4.58.2 and check the update link shown on application start.

### Version

2.4.58.3

### Operating system

Windows 10

### Printer model

Voron 2.4 - 350 and others

**Comment by Pavulon87** [comment]
#2989 
#2977
