### ISSUE TITLE
MMU Tool Name extruder=extruder2 error

### ISSUE THREAD

**Issue by Kidabah** [supermerill/SuperSlicer#3073]
### Version
2.5.59 Arachne

### Operating system type + version
Windows 11
### Behavior
* _Describe the problem_
*Since updating to Arachne version  SET_PRESSURE_ADVANCE ADVANCE=0 EXTRUDER=extruder2 gets sent when tool name = [blank] causing error in klipper
* _Steps needed to reproduce the problem_
* Have tool name = [blank] this will cause the error
* _Expected Results_
* SET_PRESSURE_ADVANCE ADVANCE=0 
* _Actual Results_
* SET_PRESSURE_ADVANCE ADVANCE=0 EXTRUDER=extruder2
  * _Screenshots if useful_
 Old tool change gcode
![old](https://user-images.githubusercontent.com/89975321/184527207-37233146-daa7-4370-85a5-fba59983d00b.png)
New tool change gcode
![extruder2](https://user-images.githubusercontent.com/89975321/184527214-f9b363d7-65d9-48e6-b3fa-848d977fe8a1.png)

_Is this a new feature request?_
No
Related guides for writing feature requests: http://meta.stackexchange.com/a/259196 http://nickohrn.com/2013/09/write-great-feature-request-bug-report/

#### Project File (.3MF) where problem occurs
_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here_

**Comment by rsheng118** [comment]
i'm having the same issue.

**Comment by Kidabah** [comment]
Unfortunately not much we can do. Until the error is fixed. I've gone back
to the mosaic version. But thanks for letting me know , Hopefully now there
are the 2 of us the issue may get addressed.

**Comment by thatinkerer** [comment]
Same problem here with my Voron 2.4 and ercf. At the second Filament change inprint set_pressure_advance advance=extruder1 gives the toolname error and stops the print.

**Comment by zuch95701** [comment]
Posted this same question on the commit where this change was implemented. Im having the same issue. Used a gcode replacement as an interim fix.  EXTRUDER=EXTRUDER1, EXTRUDER=EXTRUDER2 etc, replace with a simple space. Works for me but hope it gets fixed.

**Comment by kovmarci86** [comment]
I just ran into this problem. I have my extruders named in the config, but I did not expect this to be included in the gcode. I got `Malformed command 'SET_PRESSURE_ADVANCE ADVANCE=0 EXTRUDER=ERCF 1'`

As a workaround I will remove the names from my config. I'm happy I found this issue.

**Comment by GabrieleCastellani** [comment]
Hi I did in this way and it seems fixing the issue
![image](https://user-images.githubusercontent.com/8189074/196043726-ea746be0-d633-427c-ae40-dd81774fbbaf.png)

**Comment by julianjc84** [comment]
Many work around methods until the next version.
this works for me with a ERCF 9 tool
![image](https://user-images.githubusercontent.com/14962510/209234054-35776f56-e96e-4e96-92ee-fff97474601b.png)
