### ISSUE TITLE
Random Sciling Crash

### ISSUE THREAD

**Issue by Super-Matter** [supermerill/SuperSlicer#3090]
### What happened?

It just crashes after adding 3mfs

### Project file & How to reproduce

[HextrudORT ZAV.zip](https://github.com/supermerill/SuperSlicer/files/9357620/HextrudORT.ZAV.zip)

### Version

2.5.59.0

### Operating system

Win10

**Comment by supermerill** [comment]
same bug as https://github.com/supermerill/SuperSlicer/issues/3128, fixed in next nightly
