### ISSUE TITLE
Underextrusion with arachne engine

### ISSUE THREAD

**Issue by strayr** [supermerill/SuperSlicer#3105]
### What happened?

Filament (polymaker polylite ABS) profile has been producing nice parts with this filament across several versions, (pressure advance is maybe a tiny bit off but that only really shows in the corners and not what I'm having trouble with here).

Printed an updated toolhead part and it came out with some gaps in the perimeters along the straight lines. 

![IMG_20220820_155547296](https://user-images.githubusercontent.com/43092584/185754538-ab041fa6-cab5-4f11-957c-46e8ff4692c4.jpg)

Thinking I got my calibration wrong i printed a calibration print modified to show the perimeters and isolate the top layers from the bed with a bit of infill, this has been working more consistently fro me than the stock print. This showed great solid infill at the extrusion multiplier (0.96) I was using but with gaps in the straight sections of perimeter. 

![IMG_20220820_144726560_HDR](https://user-images.githubusercontent.com/43092584/185754739-14172a50-f46c-4b98-a309-5ff05f48f20f.jpg)

I tried with the classic engine and got the expected results

![IMG_20220820_145050668_HDR](https://user-images.githubusercontent.com/43092584/185754757-799f3344-42b7-49a3-8cd0-efaba2f6c24b.jpg)

I also tried with prusa 2.5.0RC1 and got consistent results (unmarked chips, bottom)

![IMG_20220820_153336909_HDR](https://user-images.githubusercontent.com/43092584/185754784-ef0aa659-37a1-411b-b9a6-3c5e36e11426.jpg)

### Project file & How to reproduce

Open the 3mf in SuperSlicer 2.5.59.0, select a filament that needs an extrusion multiplier a little below 1, and appropriate printer. Print with arachne and classic engines.

[Arachne-flow-isues.zip](https://github.com/supermerill/SuperSlicer/files/9387585/Arachne-flow-isues.zip)

### Version

2.5.59

### Operating system

windows 10

### Printer model

stealthburner/v6 on a prusa mk2 frame and alsop with VS373

**Comment by wonsuhna1** [comment]
#3043
is that the kind of problem? i'm waiting for a bug fix update.

**Comment by strayr** [comment]
I think that's the same problem
