### ISSUE TITLE
Auto speed percent input being resolved as normal speed

### ISSUE THREAD

**Issue by bitingsock** [supermerill/SuperSlicer#3110]
### What happened?

Auto speed > Max print speed says it supports input as percent of max feed rate for x axis.
My machine limit for x axis for example is 300mm/s.
Setting max speed to 80% actually resolves to 80mm/s when slicing.
![Screenshot 2022-08-21 130001](https://user-images.githubusercontent.com/6302101/185808779-bc377450-5d04-4da3-b4a7-4bc1de77ce4e.jpg)
![Screenshot 2022-08-21 130027](https://user-images.githubusercontent.com/6302101/185808780-1f6eec0f-b694-4ffe-9641-77982a26960e.jpg)
![Screenshot 2022-08-21 130048](https://user-images.githubusercontent.com/6302101/185808782-2ffdd229-67cc-48af-8958-c0129771338e.jpg)

### Project file & How to reproduce

[coaster.zip](https://github.com/supermerill/SuperSlicer/files/9389869/coaster.zip)

### Version

2.5.59

### Operating system

Win10pro

### Printer model

Ender 3 pro

**Comment by jhlchu** [comment]
Was just about to post same issue. I have it on nightly build as well.
