### ISSUE TITLE
Arachne error - thin wall on the first layer goes to Z minus the first layer and  part of the overhang is in the air

### ISSUE THREAD

**Issue by Creo2005** [supermerill/SuperSlicer#3125]
### What happened?

first layer
![Снимок экрана 2022-08-25 в 13 50 19](https://user-images.githubusercontent.com/10849149/186655036-4508111b-96fb-43d2-8694-7d416f268f18.png)
and overhang
![Снимок экрана 2022-08-25 в 13 59 00](https://user-images.githubusercontent.com/10849149/186655243-8af3e300-ba24-4756-b0dd-13fcea1f833f.png)

### Project file & How to reproduce

[nozzle-fan-45deg.stl.zip](https://github.com/supermerill/SuperSlicer/files/9424248/nozzle-fan-45deg.stl.zip)

### Version

2.5.59.0 night last night build

### Operating system

MacOS 12.5.1

### Printer model

SapphirePlus

**Comment by supermerill** [comment]
can't reproduce.
![image](https://user-images.githubusercontent.com/6536403/187075051-8d24f011-f1fa-4f96-bce6-dab08f50c152.png)

can you send the project file instead of the stl?

**Comment by Creo2005** [comment]
> 

checked a minute ago
![Снимок экрана 2022-08-28 в 19 36 55](https://user-images.githubusercontent.com/10849149/187084843-617fc0fc-61af-4851-b6ca-99fc1d78fc18.png)

**Comment by Creo2005** [comment]
[SS_config.zip](https://github.com/supermerill/SuperSlicer/files/9440079/SS_config.zip)

archive with slicer settings

**Comment by Creo2005** [comment]
[screen.zip](https://github.com/supermerill/SuperSlicer/files/9440081/screen.zip)
archive with screenshots

**Comment by Creo2005** [comment]
Model from this https://www.thingiverse.com/thing:3404785

**Comment by supermerill** [comment]
`File`->`Save project as...` then zip it & drop it here

**Comment by Creo2005** [comment]
> nozzle-fan-45deg.stl.zip

[nozzle-fan-45deg.3mf.zip](https://github.com/supermerill/SuperSlicer/files/9449653/nozzle-fan-45deg.3mf.zip)

**Comment by supermerill** [comment]
A little gcode viewer issue. The gcode file is fine.

**Comment by Creo2005** [comment]
> A little gcode viewer issue. The gcode file is fine.

OK, this is good :)
