### ISSUE TITLE
Time Estimation Overflow

### ISSUE THREAD

**Issue by thierryzoller** [supermerill/SuperSlicer#313]
- Download attached
- Slice
- See Time estimation

[overflow.zip](https://github.com/supermerill/SuperSlicer/files/4825040/overflow.zip)
![overflow](https://user-images.githubusercontent.com/958490/85547431-2ee11b00-b61e-11ea-8366-adedd11e4c90.PNG)

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/85550644-75844480-b621-11ea-8c6a-8bba826e52ec.png)

**Comment by thierryzoller** [comment]
This happens sporadically and I don't know why. I had minimised the window, sliced again and it estimated correcty now...

**Comment by thierryzoller** [comment]
2147483647 is the max value of a 32 bit integer, so it is certainly not just a fluke.

**Comment by thierryzoller** [comment]
Maybe signed/unsigned error?

**Comment by supermerill** [comment]
i really don't know.

**Comment by thierryzoller** [comment]
Happen sporadically, let's close this until we are able to reproduce

**Comment by robthide37** [comment]
i can make this happen pretty consistently usually by editing line width and almost alway with editing individual settings for multiple items
