### ISSUE TITLE
Failed Bridge Detection

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#3136]
### What happened?

I can't seem to do anything to get this bridged area properly detected:

![image](https://user-images.githubusercontent.com/12439543/186900297-03494303-3fc6-4b94-aacd-76629cea50fa.png)

### Project file & How to reproduce

[Bridgefail.3mf.txt](https://github.com/supermerill/SuperSlicer/files/9433025/Bridgefail.3mf.txt)

### Version

2.5.59.0

### Operating system

Windows 10 x64

### Printer model

UMO+

**Comment by Creo2005** [comment]
Incorrect slicer settings
![Снимок экрана 2022-08-26 в 16 56 42](https://user-images.githubusercontent.com/10849149/186920163-423a4d25-0072-4008-b16b-b7a1e9653b0f.png)

**Comment by neophyl** [comment]
[Bridgefail_neo.zip](https://github.com/supermerill/SuperSlicer/files/9433812/Bridgefail_neo.zip)

Yep.  Firstly you are removing all perimeters from bridges.  But thats sort of ok.  biggest issue is you have bottom layers set to zero.  A bridge is a type of bottom layer.
![image](https://user-images.githubusercontent.com/46955527/186922779-03d554a5-6673-4435-a719-34805eead24a.png)


Try the attached zipped project.

**Comment by CCS86** [comment]
Man, I am 0 for 2 today!

I normally run at least 1 bottom layer for this purpose, but must have changed the setting for another print and missed it. 

Thank you!
