### ISSUE TITLE
Skirt Missing in Gcode Preview

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#3137]
### What happened?

Skirt shows up in sliced preview:

![image](https://user-images.githubusercontent.com/12439543/186914119-64de561b-20d4-4d37-b195-fb3496473d00.png)

But disappears from the gcode preview, despite being in the gcode:

![image](https://user-images.githubusercontent.com/12439543/186914176-ab2a9db1-758f-4804-bb0a-f8df24a54b20.png)

### Project file & How to reproduce

[Skirt-missing.3mf.txt](https://github.com/supermerill/SuperSlicer/files/9433487/Skirt-missing.3mf.txt)

### Version

2.5.59.0

### Operating system

Windows 10 x64

### Printer model

UMO+

**Comment by neophyl** [comment]
Well its there when i use your project file in the same version and same OS.

Basic question but you do have skirt enabled on the key dont you ?  The images you posted are cropped to cut out the key so I cant tell.

**Comment by CCS86** [comment]
Ooof! 

I didn't even realize that you could click features in the key to show/hide. Must have been an errant mouse click, thanks!
