### ISSUE TITLE
Too many digits in Z movement when z_step is set to 0.01

### ISSUE THREAD

**Issue by celtare21** [supermerill/SuperSlicer#3143]
### What happened?

Even tho the z_step is set to 0.01, I can see many way too precise Z movements in the gcode:
`;LAYER_CHANGE
;Z:0.798675
;HEIGHT:0.198675
G92 E0
G1 Z0.798675 F300
G1 E-0.6 F1800
G1 X131.82 Y132.152 F24000
G1 E0.6 F1800`

`;LAYER_CHANGE
;Z:0.499338
;HEIGHT:0.099338
G92 E0
G1 Z0.499338 F300
G1 E-0.6 F1800
G1 X131.82 Y132.152 F24000
G1 E0.6 F1800`

### Project file & How to reproduce

Gcode + project file:
[middle-finger.zip](https://github.com/supermerill/SuperSlicer/files/9437792/middle-finger.zip)
Just search for `Z` in the gcode file

### Version

2.4.58.4

### Operating system

Windows 11

### Printer model

custom ender 5 pro

**Comment by supermerill** [comment]
fixed in 2.5.59, as the support material slicing is updated.
Won't be fixed in the 2.4 branch, as the old support slicing logic can't use z_step .
