### ISSUE TITLE
Arachne settings disabled when installed using chocolatey 

### ISSUE THREAD

**Issue by MrBlackmidi** [supermerill/SuperSlicer#3156]
### What happened?

When i tried to install using chocolately, the arachne setting are either disabled or missing
![SuperSlicer_2 4  based on PrusaSlicer 31_08_2022 2_30_11 PM](https://user-images.githubusercontent.com/108060582/187593181-229f1b46-f01f-481a-8871-36d5fcad90fe.png)

### Project file & How to reproduce

Installed using chocolatey

### Version

2.4.58.4

### Operating system

Windows 11

### Printer model

All

**Comment by MrBlackmidi** [comment]
![New Issue · supermerill_SuperSlicer - Brave 31_08_2022 2_33_18 PM](https://user-images.githubusercontent.com/108060582/187593403-23a6a3a3-b413-4dad-9005-7dd310c75e04.png)
img incorrectly cropped

**Comment by jhlchu** [comment]
Arachne available in Pre-release SuperSlicer 2.5.59.0, not Latest 2.4.58 (you have this one). If you want arachne version, you can get it from releases page.
