### ISSUE TITLE
Curly brace added in filename

### ISSUE THREAD

**Issue by Stooovie** [supermerill/SuperSlicer#3157]
### What happened?

SS adds a single closing curly brace into the filename, between the layer height number and "mm". This caused issue with the moonraker-telegram plugin.
![Screen Shot 2022-08-31 at 08 39 22](https://user-images.githubusercontent.com/10572373/187611110-c0ab41be-bf08-4109-af96-40fcb4cf0c55.jpg)

### Project file & How to reproduce

Slice a file and send into a printer.

### Version

2.5.59.0

### Operating system

Macos 12.5

### Printer model

Ender 3

**Comment by neophyl** [comment]
Check what you have defined in your print profile for the name field.  If you could attach your zipped up 3mf project file as requested when opening an issue we could take a look and check.

**Comment by Stooovie** [comment]
Ah,, it's an Expert setting! This is what I have (I don't recall changing or even seeing this before):
`{input_filename_base}_{print_time}_{digits(layer_height,1,2)}}mm_{temperature[0]}C_{filament_type[0]}_{printer_model}.gcode`

I see an extra closing curly brace there, maybe a small bug? Issue solved though, thank you.

**Comment by supermerill** [comment]
creality profile error, yes.
Thanks for the report.
