### ISSUE TITLE
Window size of Calibration tools does not obey display scaling

### ISSUE THREAD

**Issue by SigmaRelief** [supermerill/SuperSlicer#316]
### Version
2.2.51 and 2.2.52

### Operating system type + version
Windows 10 1903 64bit Pro
17" laptop with 4k screen and scaling set to 225% (or any other value)

### Behavior
Enhancement request

First, thanks for adding the calibration tools options, I foresee this as having tremendous opportunities for future growth and providing some amount of standardization for new users and time savings for advanced users.

The only small issue I have is that with a 4k screen and windows scaling set to anything other than 100% (required for 4k laptops), the calibration windows are very small and need lots of horizontal and vertical scrolling te see all the content.  The windows do not allow a drag resize which would be a nice backup, but taking the scaling factor into account when setting the windows size would be ideal.  The actual content and text appears to obey scaling and is a reasonable size.

The screenshot is at 225% scaling, but the same issues arise even at small scaling values.
![Calibration screenshot](https://user-images.githubusercontent.com/52761081/85642292-1a714280-b65f-11ea-81e0-a5cb26f026aa.png)

**Comment by supermerill** [comment]
oh, yeah... i used th dpi dialog, thinking that it may automatically change its size, but it seems like it's only for the content...
