### ISSUE TITLE
retraction firmware with wipe error (I think)

### ISSUE THREAD

**Issue by Chukozor** [supermerill/SuperSlicer#3163]
### What happened?

I think there is an issue when firmware retraction and wipe are activated at the same time.
I set a retraction of 0.2mm length without extra length on restart, and here are two screenshot of the gcode generated :
Here the first one with only wipe activated : the retraction length is 1.9+0.1 = 0.2, and the restart length is also 0.2mm so it's fine.
https://cdn.discordapp.com/attachments/771319294113742858/1014265537632669737/unknown.png
but here is the gcode generated while firmware retraction is also activated.
so, there are a first retraction with G10, and then another one of 0.19mm, and then follow the unretraction with G11 .... so the global retraction is of 0.2(of G10) + 0.19(in the gcode)= almost twice one retraction length, and the the unretraction is of only one retraction length ... 
Can somebody confirm if this is an actual issue or not. Thanks
https://cdn.discordapp.com/attachments/771319294113742858/1014265696097681438/unknown.png

### Project file & How to reproduce

profile here : [SuperSlicer_config_bundle-2022-09-01-00h40.zip](https://github.com/supermerill/SuperSlicer/files/9465546/SuperSlicer_config_bundle-2022-09-01-00h40.zip)

### Version

2.5.59.0

### Operating system

windows 10

**Comment by supermerill** [comment]
you send me your config, instead of the project file.
But  understand the issue, it's not really needed here.
