### ISSUE TITLE
Slicing weird holes

### ISSUE THREAD

**Issue by Assholer91** [supermerill/SuperSlicer#3172]
### What happened?

Trying to print a coffe machine tray and it has couple of coffe grain shaped holes and two larger oval holes for water drainage on the bottom. When I slice the model it makes a mess where the holes are suposed to be. It is the same in Prusa slicer. It was sliced normally in Cura when I printed it the first time. 

![Coffe tray SS problem 1](https://user-images.githubusercontent.com/37813158/187965893-beffbf0b-fcb9-459c-9488-7f91563205ab.JPG)

![Coffe tray SS problem 2](https://user-images.githubusercontent.com/37813158/187965899-251f6ffa-3e0c-4faf-9535-e8805ad115f3.JPG)

I tried with diferent orientations and settings, with no success.

### Project file & How to reproduce

[TXXPRO_podstavek_za_kafetiero_v2.1SS.zip](https://github.com/supermerill/SuperSlicer/files/9471736/TXXPRO_podstavek_za_kafetiero_v2.1SS.zip)

### Version

2.4.58.4

### Operating system

Win 10

### Printer model

Tronxy X5SA Pro

**Comment by 3Dxdream** [comment]
It shows "98820 open edges" in your stl-model.
But you can press the blue warning sign symbol and repair it. 
Then it works!

**Comment by Assholer91** [comment]
Now this was simple. 

Thank you for solution, I will look up why this happened with the model to prevent it next time.
