### ISSUE TITLE
[FR] Clearer Guidance on Printer Settings & Seperate Printing Accell from Travel accell.

### ISSUE THREAD

**Issue by thierryzoller** [supermerill/SuperSlicer#318]
Printer Settings -> Machine Limits

1. Seperating Printing acceleration from "Retraction". In Superslicer it says "M204 T Maximum Acceleration when retracting" - Can we make that "Maximum acceleration when travelling" OR change the description to fit the action ? The T Parameter is not retraction.
2. "Maximum Acceleration when extruding" is described as "M204 S". This should be M204 P
3. Can we add a dedicated  "Retract Acceleration" ? M204 R ?

**Overall:** Can we align all of this to non legacy marlin ? https://marlinfw.org/docs/gcode/M204.html 
It appears I cannot seperatly configure Printing and Travel accell . Which can help reduce stringing (rampup Travel accell)

**Comment by supermerill** [comment]
added the travel speed. It's only set for marlin firmware, and it's almost never used. But it's here.

**Comment by thierryzoller** [comment]
My description may be not very clear, sorry for that. I was also pointing out that the descriptions/labels do not match the function, which leads to misunderstandings. Can this be aligned to 1. what really is happening in slicer 2. the correct nomenclature ?

**Comment by thierryzoller** [comment]
> added the max travel speed. It's only set for marlin firmware, and it's almost never used. But it's here now.

Do you mean "travel accell" or speed?

**Comment by supermerill** [comment]
acceleration, sorry.

correct nomenclature is the inverted 'R' and 'T', right? if yes, it's done.

**Comment by thierryzoller** [comment]
I'll check once a new release is out :) Thanks
