### ISSUE TITLE
Flow::mm3_per_mm() produced negative flow

### ISSUE THREAD

**Issue by DKS-18** [supermerill/SuperSlicer#3184]
### What happened?

Error when slicing files. The project file is attached. happens on 2.5RC and latest nightly

![Screenshot 2022-09-06 233547](https://user-images.githubusercontent.com/16251488/188649493-3f5d8728-bd21-43f9-99b7-ecf78564fdbd.jpg)

### Project file & How to reproduce

[project file.zip](https://github.com/supermerill/SuperSlicer/files/9497458/project.file.zip)

### Version

SuperSlicer_2.5.59.0_2022-08-31

### Operating system

win 11

**Comment by Jamin82** [comment]
slices fine on 2.4
