### ISSUE TITLE
Strange perimeters whit MMU paint

### ISSUE THREAD

**Issue by efradc** [supermerill/SuperSlicer#3193]
### What happened?

hi, Ihave these strange perimeter problems with SS, with PS it doesn't happen to me...
Also try to export 3mf from PS and open with SS, same problems... maybe a bug?

I have tried with 2.4 and 2.5.

PS slice:
![prusaslicer](https://user-images.githubusercontent.com/113169627/189301082-c5914010-7444-4cfb-a107-e4f7e38d3643.png)

SS Slice:
![superslicer](https://user-images.githubusercontent.com/113169627/189301264-e0468824-4b55-4dc7-914b-0b960162339f.png)

Thanks!

### Project file & How to reproduce

Import painted 3mf or paint a new one and slice

### Version

2.4.58.4

### Operating system

windows 10

**Comment by supermerill** [comment]
I just fixed it
#2639

**Comment by efradc** [comment]
thanks, sorry. I was looking if it was solved but I didn't find

**Comment by supermerill** [comment]
forgot to tell you about how to solve it:
If you increase the resolution (reduce the number, to 0), then it can apply the paint on the surface again.

**Comment by efradc** [comment]
After trying many things I have seen today the answer hahaha now it is perfect, thank you very much for the work you do
