### ISSUE TITLE
Vase mode doesn't change to one vertical shell

### ISSUE THREAD

**Issue by JacTheMaker** [supermerill/SuperSlicer#3204]
### Version
SS 2.5.59.0

### Operating system type + version
Windows 11 Pro

### Behavior
Check Vase Mode, Click Yes
Doesn't change number of vertical shells to 1.
Still slices with multiple walls.
![image](https://user-images.githubusercontent.com/109631417/189566317-a24f8bfc-ac62-4430-b743-15af651af901.png)
![2022-09-11](https://user-images.githubusercontent.com/109631417/189566169-b87c5772-4d7a-416a-b03d-1579237a7cb1.png)
[ribbon2.zip](https://github.com/supermerill/SuperSlicer/files/9544298/ribbon2.zip)

Just change file extension, not actually zipped

**Comment by JacTheMaker** [comment]
![2022-09-11](https://user-images.githubusercontent.com/109631417/189566169-b87c5772-4d7a-416a-b03d-1579237a7cb1.png)
[ribbon2.zip](https://github.com/supermerill/SuperSlicer/files/9544298/ribbon2.zip)

Just change file extension, not actually zipped

**Comment by supermerill** [comment]
use classic slicing.
Also, the object ahs a section with walls thinner than your nozzle diameter, so it won't be able to vase-slice it there.

**Comment by paulgiordano** [comment]
This code appears to cause a segfault at PrintConfig.cpp line 8058, 
`this->opt<ConfigOptionEnum<PerimeterGeneratorType>>("perimeter_generator", true)->value = PerimeterGeneratorType::Classic;`
