### ISSUE TITLE
Inaccurate seam alignment

### ISSUE THREAD

**Issue by bdwilson** [supermerill/SuperSlicer#3217]
### What happened?

In order to get a completely straight seam, I have to rotate the object to have the corner towards the back of the bed and select back.  This is a shape with rounded corners (standard fillet in Fusion).  All other seam options, even painted straight line result in off seams.  I'm completely unhappy with Cura and the quality of the new version, so I've spent a ton of time getting my settings correct in SuperSlicer. The one area I'm struggling with is seams.  I have reviewed other issues (#2478 #2535 #2444 #3047 #2435) and not had any success. 

### Project file & How to reproduce

[Box with Circle.3mf.zip](https://github.com/supermerill/SuperSlicer/files/9584048/Box.with.Circle.3mf.zip)

Nearest
![image](https://cdn-std.droplr.net/files/acc_601089/PMqC2d)

Corners
![image](https://cdn-std.droplr.net/files/acc_601089/X7NJEo)

Aligned
![image](https://cdn-std.droplr.net/files/acc_601089/JEBBZw)

Contiguous
![image](https://cdn-std.droplr.net/files/acc_601089/wN4WBF)

Rear
![image](https://cdn-std.droplr.net/files/acc_601089/eKddmm)

Rear (with object rotated - the BEST of them all)
![image](https://cdn-std.droplr.net/files/acc_601089/AzwJxr)

Custom (painted seam with mouse keys to ensure straight line)
![image](https://cdn-std.droplr.net/files/acc_601089/LM8Hxr)
![image](https://cdn-std.droplr.net/files/acc_601089/h8JHV2)

Simply change the seams in the attached project file.  You will see that the only way to get a straight seam on a corner is to rotate the object so the corner is in the back of the build plate.  This seems bonkers that none of the other options (even the corner option), can deliver a straight seam.  

### Version

2.5.59 and 2.4.58.4

### Operating system

Mac OS 12.4 (arm)

### Printer model

KP3S (using modified Hornet template in SuperSlicer)

**Comment by jhlchu** [comment]
SuperSlicer_2.5.59 f8c9106
## Seam sphere
![Screenshot 2022-09-16 062926](https://user-images.githubusercontent.com/5092505/190650582-15ce9211-af1c-4f2c-bec4-76f6a722afb2.jpg)
Orientation doesn't matter
## File
Don't unzip this, just rename to *.3mf.
[Box with Circle.zip](https://github.com/supermerill/SuperSlicer/files/9584418/Box.with.Circle.zip)

**Comment by jhlchu** [comment]
Also better seam placement is coming once PS 2.5 changes are merge.

**Comment by bdwilson** [comment]
> SuperSlicer_2.5.59 [f8c9106](https://github.com/supermerill/SuperSlicer/commit/f8c9106c0119b6373b8ace5436a756a0c0003dd8)
> 
> ## Seam sphere

Is seam sphere a new setting? I have seen it referenced but not sure how to use it.

**Comment by jhlchu** [comment]
You can also scale and rotate to get it very precise like in the file I sent back. It can be combined with seam painting for finer control. It may not always behave as you think, see #3183 for details.
