### ISSUE TITLE
Auto speed perimeters not adhering to % based values

### ISSUE THREAD

**Issue by kizza42** [supermerill/SuperSlicer#323]
### Version
2.2.52

### Operating system type + version
Win10 2004

### 3D printer brand / version + firmware version (if known)
Tevo Little Monster

### Behavior
Maybe I'm misunderstanding Auto speed but I always assumed it gave a max speed and then every component under it would run at a arbitrarily slower speed due to detail or adhere to the overrides provided. In this case I expect my outer perimeters to go at 30% of whatever I set my Max speed to but it seems to ignore the % value. When entering a absolute value the override is enforced.
![2020-06-28_18-54-27](https://user-images.githubusercontent.com/12605257/85943131-5e22bf80-b971-11ea-90cd-1fd45f735d4f.gif)

#### Project File (.3MF) where problem occurs
[20200628 - Fanatec Keyboard Holder.zip](https://github.com/supermerill/SuperSlicer/files/4841971/20200628.-.Fanatec.Keyboard.Holder.zip)
Possible to allow uploading 3mf direct?

**Comment by supermerill** [comment]
you have to set the field to 0 to use the autospeed for it

**Comment by kizza42** [comment]
I understand that but when filling the fields with % values they're not enforced at all.
