### ISSUE TITLE
Fan Speed Problem

### ISSUE THREAD

**Issue by mcham** [supermerill/SuperSlicer#3232]
Set Filament>Cooling to 50%
GCODE created  M106 S50
I expected M106 S127 (50% of 255)

[FanIssue.zip](https://github.com/supermerill/SuperSlicer/files/9592431/FanIssue.zip)

 - OS: Windows 10
 - Version: [2.4.58.4]
 - Printer model: Voron 2.4 (klipper)

**Comment by jhlchu** [comment]
Uncheck `Printer Settings > Cooling Fan > Fan PWM from 0-100` in your project. Close issue.
![Screenshot 2022-09-17 190850](https://user-images.githubusercontent.com/5092505/190882561-86b7a926-b306-4370-a380-e09096026fb7.jpg)
![Screenshot 2022-09-17 190824](https://user-images.githubusercontent.com/5092505/190882562-ad6742cc-b2d7-42f3-9d9f-22981f8fa8df.jpg)
