### ISSUE TITLE
[Feature Request] Search Feature

### ISSUE THREAD

**Issue by MarcPot** [supermerill/SuperSlicer#325]
_Is this a new feature request?_ Yes

With all the awesome features and options you're adding the UI is getting a little crowded, so maybe a new feature could be a search and/or visibility setting?

Kinda like Cura, but the way Cura did it is really slow, so not like Cura. I think the problem with Cura is that it works like a filter on your current UI, making the whole UI reload every time (I'm not a coder so I could be completely wrong).

**Comment by supermerill** [comment]
will be added when merged against prusa 2.3

**Comment by thelandinlook** [comment]
Hello!

**Comment by thelandinlook** [comment]
I've been looking for this, has it been added yet?

thanks xo

**Comment by MarcPot** [comment]
Not sure if it's in the stable release yet since I don't use that one. But 
![image](https://user-images.githubusercontent.com/7275765/104559977-7f18dc80-5645-11eb-9e99-381eec66eed6.png)
