### ISSUE TITLE
Version check checks PRUSA not SS.

### ISSUE THREAD

**Issue by inspectionsbybob** [supermerill/SuperSlicer#3262]
### Version
2.4.58.4

Win10

### Behavior
Got Notified of a New Release when I opened SS.
Clicked on LInk and it took me to PRUSA SLICER 

There IS a new SS release, 2.4.58.5   but that is not where it took me...

_

**Comment by neophyl** [comment]
Did you not read the release notes for the latest version ?  It mentions fixing the hard coded PRUSA download page.

**Comment by inspectionsbybob** [comment]
Sorry, I went through the read me and the change log but there was no mention of that that ai saw of the first pass...

**Comment by neophyl** [comment]
I think it’s this one 
change download page from hardcoded prusa 
At least that’s the way I read it.

**Comment by inspectionsbybob** [comment]
With a description like that, no wonder I missed it.  Anyway, so long as the development team knows, close this one as a duplicate.

**Comment by inspectionsbybob** [comment]
Duplicate
