### ISSUE TITLE
Sparse fill pattern modifier for parts are not retained over save files

### ISSUE THREAD

**Issue by feketeimre** [supermerill/SuperSlicer#3263]
### Version
2.4.58.5

### Operating system type + version
Windows 10

### Behavior
* _Describe the problem_
Sparse fill pattern modifier for parts are not retained over save files
* _Steps needed to reproduce the problem_
Create new project, Add shape/Box, Right-click on box, select Infill option to add modifier, save project, load the just saved 3mf file.
* _Expected Results_
The part from the loaded file should have the sparse fill pattern modifier
* _Actual Results_
The part from the loaded file does not have a parse fill pattern modifier, only infill percent. Infill pattern type set for the part is lost when saved.
I looked into the 3mf file and the infill type data is not even saved in the Metadata\Slic3r_model.config file
![image](https://user-images.githubusercontent.com/15861028/192101847-527fc989-40bc-4c02-8443-ce17b4ffdc21.png)

_Is this a new feature request?_
No

**Comment by NameOfTheDragon** [comment]
FYI, this is working correctly in 2.5.59.0

**Comment by feketeimre** [comment]
@NameOfTheDragon
Thanks for pointing it out!
