### ISSUE TITLE
Small details lost on surfaces with 2.2.52.0

### ISSUE THREAD

**Issue by dkatzdev** [supermerill/SuperSlicer#327]
### Version
2.2.52.0

### Operating system type + version
Windows 10 v1909

### 3D printer brand / version + firmware version (if known)
Creality Ender 5 Pro

### Behavior
When using the latest version of SS (2.2.52.0), small details are lost in the surface of objects. These details were maintained with identical settings in version 2.2.51.2. Likely related to the new thin wall changes in the slicer. See below

The model:
![image](https://user-images.githubusercontent.com/933792/86057799-d18a0700-ba2d-11ea-90be-83fabadf05dd.png)

Sliced in 2.2.51.2
![image](https://user-images.githubusercontent.com/933792/86057861-ebc3e500-ba2d-11ea-9f96-8a48e87d5df5.png)

Sliced in 2.2.52.0
![image](https://user-images.githubusercontent.com/933792/86057882-f4b4b680-ba2d-11ea-8179-b8eee696917c.png)

#### Project File (.3MF) where problem occurs

[filament_sensor_cover.zip](https://github.com/supermerill/SuperSlicer/files/4848122/filament_sensor_cover.zip)

**Comment by supermerill** [comment]
try with 0 on "xy compensation - hole", it's a known issue on this release i haven't the time to fix yet. (see release page)

**Comment by dkatzdev** [comment]
Yep, that fixes it, but I'd like to be able to maintain my hole adjustment for more complex parts.

**Comment by dkatzdev** [comment]
Resolved in latest bugfix 2.2.52.1
