### ISSUE TITLE
Corrupting Simple Box File

### ISSUE THREAD

**Issue by inspectionsbybob** [supermerill/SuperSlicer#3270]
### Version
2.4.58.5

### Operating system type + version
Win10

### Behavior
Really Mangled Simple Glove Box
Not sure what it did, but it did it good
Looks like it extended the Keyholes all the way around the Box.
Checked Gcode file with Viewer and it looks the same, ie. corrupted...

Pulled into CURA  5 and it sliced it fine without any reported errors or fixes.

_Is this a new feature request?_
NO

#### Project File (.3MF) where problem occurs
[Glove Box  Crash.zip](https://github.com/supermerill/SuperSlicer/files/9642201/Glove.Box.Crash.zip)

**Comment by neophyl** [comment]
Slices fine when not in vase mode.  As the model isn't an unbroken solid with those keyholes in it then its not really designed to be printable in vase mode anyway.
