### ISSUE TITLE
Need function infill one direction for Print Glass ?

### ISSUE THREAD

**Issue by Witawat** [supermerill/SuperSlicer#3282]
Need function infill one direction for Print Glass ?

https://www.printables.com/model/15310-how-to-print-glass/comments

![image](https://user-images.githubusercontent.com/4926369/192548414-24a803be-4ed3-418c-b2b1-eba20d8ca0f8.png)
![image](https://user-images.githubusercontent.com/4926369/192548463-e64537d9-7550-4ebe-97b6-e233f605e004.png)
![image](https://user-images.githubusercontent.com/4926369/192548520-72b863e0-7757-45bf-9d59-11c30d27074c.png)

but prusa can use

![image](https://user-images.githubusercontent.com/4926369/192548643-e539909d-19d1-4f21-843e-aca3074c722e.png)
![image](https://user-images.githubusercontent.com/4926369/192548751-121de182-9bcb-4ab3-98e4-fe1a66e47753.png)

**Comment by jhlchu** [comment]
Set `Print Settings > Infill > Angle > Increment = 90`. Close issue.

**Comment by neophyl** [comment]
Or use aligned rectilinear with zero top and bottom layers.

**Comment by Witawat** [comment]
> Set `Print Settings > Infill > Angle > Increment = 90`. Close issue.

not work
![image](https://user-images.githubusercontent.com/4926369/192664097-75a13e95-15be-4614-9303-32a38ec8405e.png)
![image](https://user-images.githubusercontent.com/4926369/192664115-52350271-193a-4da3-a5fa-f7209120959f.png)
![image](https://user-images.githubusercontent.com/4926369/192664131-8d72af13-caf7-4cf9-9a46-7ae3b993abaf.png)

**Comment by jhlchu** [comment]
Re-read what I wrote. You changed `Fill Angle` not `Increment Angle`.

**Comment by Witawat** [comment]
> Increment Angle

![image](https://user-images.githubusercontent.com/4926369/192685477-bd8dfe93-fb70-487a-9805-8d19f8cad7d1.png)

thank you work
