### ISSUE TITLE
HELP: Something Hidden Corrupted, Flows off the chart

### ISSUE THREAD

**Issue by inspectionsbybob** [supermerill/SuperSlicer#3326]
### Version
2.4.58.5

### Operating system type + version
Win10

### Behavior
After a few successful prints and some successful Profile edits, the Flow value becomes Multiplied by 10-100

My purge lines down the side are perfect, but as soon as it starts to draw the Skirt, the FLOW IS MAXED OUT and I get BLOBS not lines.  The Gcode is whacky as soon as it starts with the calculated stuff.  My manual purge lines are perfect.

What should be a 4g calibration Cube, is showing as over a 1Kg
Looked at all the Flows, widths, and speeds, and compared them, and can't see anything....
When I look at the RAW Gcode, the (E)xtrusion values are 10-100X what they should be.

_Is this a new feature request?_
NO

PS... went looking for 2.4.58.4  to compare with, can't find that ZIP file.... can't even find the GitHub repository for that branch

#### Project File (.3MF) where problem occurs
Including 3Mf
Preview File showing MANY MANY Gs to many
Gcode file generated....

[Too Much Flow.zip](https://github.com/supermerill/SuperSlicer/files/9736301/Too.Much.Flow.zip)

**Comment by neophyl** [comment]
Bob you have in your start gcode block the following
M83 ;extruder only Relative mode
but in Printer Settings>General>Advanced  down towards the bottom you have  Use Relative E distances UNTICKED.  IF you tick that so it matches what type of extrusion values you have set in your start code then it slices with normal values.

2.4.58.5 is on the releases page https://github.com/supermerill/SuperSlicer/releases  third one down currently, 2.4.58.5, then the arachne version 2.5.59.0, then 2.4.58.4.  The zip files are in the assets link (click and it expands to show them).

**Comment by inspectionsbybob** [comment]
Fantastic!

I figured it was something like that, but couldn't "see" it.

I will take a look at the start gcode and make sure there are no other
issues, or set the extruder differently.


Please don't wait for me to respond when booking an inspection. I turn off
my devices when on appointments and someone else could get your spot.
Please CALL our service or book yourself online to save the spot as soon as
you know the time you want.

Bob Sisson ACI, BVI
Inspections by Bob
ASHI Member # 212016
MD Home inspectors License #29666*
*MAC-ASHI Chapter President 2010-2012
ASHI Mid-Atlantic Group Leader 2009-2012
ASHI National Board Of Directors 2012-2015, 2017,2018-2020
***@***.***
www.inspectionsbybob.com
(301) 208-8289 Scheduling/Pricing
