### ISSUE TITLE
xy compensation removes hole completely 

### ISSUE THREAD

**Issue by AmyTheCute** [supermerill/SuperSlicer#334]
### Version
2.2.52

_Use `About->About SuperSlicer` for release versions_

_For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
The Doot changer, Klipper

### Behavior
XY Compensation makes a hole completely go away in one of my VERY similar parts but not in the other.
![Screenshot (137)](https://user-images.githubusercontent.com/44164611/86531402-08e92f80-bed6-11ea-9b88-6f2fec7f0364.png)

![Screenshot (138)](https://user-images.githubusercontent.com/44164611/86531405-0b4b8980-bed6-11ea-89d6-b90413435aa8.png) 
I've included two photos. One with 0.0mm compensation and another with 0.05mm compensation. happens with any value. the right part is just fine while the left one gets the inner/smaller hole completely removed

#### Project File (.3MF) where problem occurs

[GitHub ISssue.zip](https://github.com/supermerill/SuperSlicer/files/4874811/GitHub.ISssue.zip)

**Comment by supermerill** [comment]
duplicate of #327 and #317 
fix in 2.2.52.1

**Comment by AmyTheCute** [comment]
Oh I'm sorry! I did google but I didn't find those
