### ISSUE TITLE
Garbled slicer paths for both released version and nightly_dev build

### ISSUE THREAD

**Issue by kursatu** [supermerill/SuperSlicer#3345]
### What happened?

I have been using nightly_dev build that I've made few weeks ago, in order to use Arachne.
It somehow seems to have messed up a persistent state for both the released superslicer and nightly_dev version.
Now I'can't slice with neither of them. Prusa slicer works fine.
I see this error message on the console, which might indicate something.
I've checked "Only custom start G-Code" in the printer options, bu that did not change anything either.
"[2022-10-16 12:46:04.050459] [0x00003d08] [error]   GCodeProcessor encountered an invalid toolchange, maybe from a custom gcode."

![Screenshot 2022-10-16 123412](https://user-images.githubusercontent.com/1686475/196054667-5ec771ac-d068-49ed-8d8c-3de9faa7ca63.png)
![Screenshot 2022-10-16 123904](https://user-images.githubusercontent.com/1686475/196054691-ba8290fd-1d58-4687-a449-66bf5f1e408f.png)

### Project file & How to reproduce

There is no reproduction steps. I am attaching a project from nightly_dev build.
The screenshots above are from the released Superslicer.
[Fuselage new.zip](https://github.com/supermerill/SuperSlicer/files/9795524/Fuselage.new.zip)

**Comment by jhlchu** [comment]
You have fuzzy skin on. `Print Settings > Perimeter & Shell > Advanced > Fuzzy Skin = None` fixes it. If it fixes the issue, close.

**Comment by kursatu** [comment]
The fuzzy skin setting was apparently causing it.
