### ISSUE TITLE
Unnecessary Solid Infill

### ISSUE THREAD

**Issue by ssjbardock** [supermerill/SuperSlicer#3405]
### What happened?

Solid infill is added in random areas instead of standard infill, greatly increasing filament usage and time.

Seems to occur with pretty much any model that has smaller cross\-section areas.

![Screenshot 2022-11-05 123303](https://user-images.githubusercontent.com/18308623/200150094-ddcf32f7-08b2-4ca1-95c1-e50f1f9df794.png)

### Project file & How to reproduce

[solid ifill problem.zip](https://github.com/supermerill/SuperSlicer/files/9944390/solid.ifill.problem.zip)

### Version

2.5.59.0

### Operating system

Windows 10

### Printer model

Custom

**Comment by jhlchu** [comment]
`Print Settings > Infill > Advanced > Solid infill threshold area` I used `5mm^2` and it used sparse infill instead. Close if solved issue.

**Comment by ssjbardock** [comment]
Yup that'll do it. Thanks!
