### ISSUE TITLE
libopenvdb.so.9.1: cannot open shared object

### ISSUE THREAD

**Issue by Big-Al81** [supermerill/SuperSlicer#3421]
### What happened?

superslicer: error while loading shared libraries: libopenvdb.so.9.1: cannot open shared object file: No such file or directory

expected superslicer to launch

### Project file & How to reproduce

Fails to load when launching from desk top. 

From terminal type : superslicer
returns: superslicer: error while loading shared libraries: libopenvdb.so.9.1: cannot open shared object file: No such file or directory

All system files are up to date.  Error started after installing system updates earlier this week. 

investigating "openvdb 10.0.0-1" found installed on system. 

### Version

1:2.4.58.5-2

### Operating system

manjarolinux 22.0.0 Sikaris

### Printer model

cr10s5 heavily modified

**Comment by Damien2s** [comment]
Exact same issue here.
Same version, same os
libopenvdb.so.9.1 is missing, only libopenvdb.so.10.0. Tried to create a link libopenvdb.so.9.1 to libopenvdb.so.10.0 and of course it doesn't work:
superslicer: symbol lookup error: superslicer: undefined symbol:_ZNK7openvdb4v9_12io19DelayedLoadMetadata7getMaskEm

**Comment by exetico** [comment]
Same thing here. On Arch it should be part of the `openvdb` package - but here I'm also rocking 10.0.0-1...

**Comment by Damien2s** [comment]
OK problem solved with version 1:2.4.58.5-3 on Manjaro

**Comment by Big-Al81** [comment]
Thank you Guys.  I opted to wait for the version release which has fixed the the issue.
