### ISSUE TITLE
Add perimeter around solid infill layers

### ISSUE THREAD

**Issue by meltiseugen** [supermerill/SuperSlicer#3424]
I would like to have the slicer create a perimeter around the solid infill, before printing the solid infill.

This way, when using a low infill density, the solid layer will not be totally printed in the air, and it would have a perimeter to attach to.

<img width="169" alt="image" src="https://user-images.githubusercontent.com/18147746/201466612-be293dff-0555-4246-978a-e8814b0d71fa.png">

**Comment by jhlchu** [comment]
That's not `solid infill` (purple), that is `internal bridge infill` (blue). It's fine for it to print in mid air in some places as it's only meant to support the solid fill above it. It also uses lower flow and density than solid fill.

You can improve its support by using `Print Settings > Infill > Supporting dense layer`, which will print a less dense (but anchored) layer below it.
