### ISSUE TITLE
Mirrored Part gets cut off

### ISSUE THREAD

**Issue by afkfurby** [supermerill/SuperSlicer#344]
### Version
2.2.52

### Operating system type + version
Windows 10 Build 1909

### 3D printer brand / version + firmware version (if known)
It's a big printer (700x700x1700mm) but irrelevant

### Behavior
When slicing the attached file, everything works as expected (parts is big).
But when you mirror the part (doesn't matter if in 3DBuilder or SS) the Preview cut's it off at some point.
The Gcode is complete (I found out after fiddeling the whole morning)

_Is this a new feature request?_
no

#### Project File (.3MF) where problem occurs
[stosstange.zip](https://github.com/supermerill/SuperSlicer/files/4919104/stosstange.zip)
![works](https://user-images.githubusercontent.com/13721934/87431557-180f6200-c5e7-11ea-9c72-b5c160aab11d.png)
![dontwork](https://user-images.githubusercontent.com/13721934/87431560-18a7f880-c5e7-11ea-9593-6a90c896ea4b.png)

[system info.txt](https://github.com/supermerill/SuperSlicer/files/4919113/system.info.txt)

**Comment by supermerill** [comment]
seems to be fixed in 2.3
