### ISSUE TITLE
Missing slicing parts some models

### ISSUE THREAD

**Issue by BTopbas** [supermerill/SuperSlicer#349]
### Version
2.2.52

### Operating system type + version
MacOSx Catalina

### Behavior
On Superslicer some parts of models not slicing. Here is one of example. 

Superslicer:
![Screen Shot 2020-07-17 at 18 49 48](https://user-images.githubusercontent.com/6390054/87805825-a5a8b700-c85e-11ea-8c08-e39db021d002.png)

PrusaSlicer or other slicers:

![Screen Shot 2020-07-17 at 18 50 13](https://user-images.githubusercontent.com/6390054/87806066-fa4c3200-c85e-11ea-8fa5-5bf32a685753.png)

This is only one model I looked 3 different models but some parts not slicing and disappearing on the super slicer. I checked and unchecked thin walls and overlapping perimeters combinations then resliced but same happened. Maybe edit any other setting?

**Comment by supermerill** [comment]
Duplicate of #335  #334 , #327 and #317
fix is in 2.2.52.1

**Comment by BTopbas** [comment]
> Duplicate of #335 #334 , #327 and #317
> fix is in 2.2.52.1

Oh, my bad! I didn't look at the latest releases. Sorry about that! Closing issue.
