### ISSUE TITLE
Layer 2 not Slowed at all by Layer Time Goal

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#3495]
### What happened?

In the attached project all the lower layers are slowed by the filament>cooling setting for layer time goal. But, for some reason, no slowing is applied to layer 2.

### Project file & How to reproduce

[Sphere.3mf.txt](https://github.com/supermerill/SuperSlicer/files/10201386/Sphere.3mf.txt)

### Version

2.5.59.0

### Operating system

Windows 10 x64

**Comment by CCS86** [comment]
@supermerill

**Comment by supermerill** [comment]
can't reproduce on latest nightly.
seems fixed.

**Comment by CCS86** [comment]
Cool. I just checked in 2.5.59.3, and it is still an issue, but haven't tried the nightly.
