### ISSUE TITLE
Bridge infill comes in at unwanted places, with no option to disable it.

### ISSUE THREAD

**Issue by Hamrbooo** [supermerill/SuperSlicer#3535]
**Is your feature request related to a problem? Please describe.**
When slicing models with overhangs, SuperSlicer (version 2.4.58.5) creates this thing called 'Bridge infill' in the sliced model. The problem is that even though it's called infill, it mostly generates on the **outside** of the mesh. It doesn't stop there, because it can also generate inside other perimeters, making the extruder try to extrude filament in a place where it already extruded filament. This can be seen when slicing a benchy (which I got from here https://www.thingiverse.com/thing:763622):
![image](https://user-images.githubusercontent.com/121578403/209865484-513afc84-1a22-4b61-b153-fcb0a42ee92e.png)

A Benchy has some inlayed text on the bottom, which shouldn't be filled with filament. In the screenshot above you can see SuperSlicer filled it with Bridge infill (and no, supports are turned off). You can also see the Bridge infill overlapping with the Internal and External perimeters.

To give an example of what I would expect, here is what Cura did:
![image](https://user-images.githubusercontent.com/121578403/209865945-801d2219-c710-4632-817b-58b39e1f5d26.png)

You can see Cura didn't fill up those letters.

This issue can also be seen on vertical holes:
![image](https://user-images.githubusercontent.com/121578403/209866181-b365d17f-a1d6-4895-9cfc-3917807b83b4.png)
Here SuperSlicer puts all layers nicely around the hole except for the top where it puts a Bridge infill line inside the hole.

Since SuperSlicer is based on PrusaSlicer, I checked how PrusaSlicer handles this. PrusaSlicer 2.4 did the exact same thing with Bridge infill as SuperSlicer 2.4 did. So the same issue exists there. I also checked PrusaSlicer 2.5, but to my surprise it gets even worse:
![image](https://user-images.githubusercontent.com/121578403/209866764-f92651b6-82fb-4eb1-be76-f055aad2b435.png)
It still fills up the text (which is wrong) but it also overlaps with almost the whole bottom of the benchy!

I searched the internet and tried finding a way to turn this bridge infill off, but there is no option to do that. Even setting bridge flow to 0% doesn't work, because 2% is the lowest.

**Describe the solution you'd like**
Ideally, I would like to see he bridge infill getting generated **inside** the mesh and not overlapping with other perimeters. I see why the bridge infill gets generated; bridging is a good way to be able to make horizontal overhangs and the bridge infill does a good job finding the shortest bridging length. It just has to be generated a few layers higher so it ends up inside the model.
I would also accept the option to just turn the bridge infill off. Although this is less ideal since you don't get the power of bridging on overhangs, at least your model will print in the intended shape.

**Describe how it would work**
For the ideal solution, the slicer would take the thickness of the bridge infill into account and makes it so that it doesn't get generated lower than it should. (I found out that the bridge infill has the same diameter as the nozzle, and doesn't have anything to do with the set layer height.) It also shouldn't overlap with other perimeters like it does in PrusaSlicer 2.5.
The other option, just being able to disable it, could be implemented as a checkbox in the settings. Maybe it could also be implemented in the gcode tab:
![image](https://user-images.githubusercontent.com/121578403/209867924-86a63d56-8c97-4eb1-afea-94e70c67d175.png)
Maybe it's possible to have checkboxes in this list, so the user is able to extract a certain feature type from the gcode with one click. Or maybe something like right mouse click -> exclude from gcode would work.

**Describe alternatives you've considered**
The alternative is going back to Cura, but I really don't wanna do that since I like SuperSlicer's UI a lot more. For now I slice my models with SuperSlicer first, and when Bridge infill shows up, then I'll slice it with Cura.

**Additional context**
Sometimes, even Overhang perimeters can get generated lower than they should:
![image](https://user-images.githubusercontent.com/121578403/209868609-02408c26-9200-41a7-a0bc-bca965982cb6.png)
This isn't that much of a problem, but since it's somewhat similar to what bridge infill can do, I figured I'll just mention it.

**Comment by lucascarvalho** [comment]
I have the same issue while printing these https://github.com/VoronDesign/VoronUsers/blob/master/printer_mods/richardjm/snap-latch-2020/STL/NewLatch-3.0mm.stl
![Screenshot 2023-03-09 at 7 47 31 PM](https://user-images.githubusercontent.com/281615/224219562-43d4076d-ba6b-42b3-984b-15a9afc0d346.png)

**Comment by Hamrbooo** [comment]
> Selecting the settings "Simulate Prusa No Thick Bridge" fixed the issue for me.

This seems to solve the issue for me as well.

**Comment by roe3dd** [comment]
> Selecting the settings "Simulate Prusa No Thick Bridge" fixed the issue for me.

Where do I find this setting? Please thx!
