### ISSUE TITLE
Crash when saving project with infill modifier

### ISSUE THREAD

**Issue by aligator** [supermerill/SuperSlicer#3549]
**Bug description**
It just crashes with this output in the terminal
```
superslicer: /build/superslicer/src/SuperSlicer/src/libslic3r/Format/3mf.cpp:3296: bool Slic3r::_3MF_Exporter::_add_model_config_file_to_archive(mz_zip_archive&, const Slic3r::Model&, const Slic3r::DynamicPrintConfig&, const IdToObjectDataMap&, const std::string&): Assertion `false' failed.
Abgebrochen (Speicherabzug geschrieben)
```
When saving a project with an infill modifier applied to an object.

**Expected behavior**
No crash and valid project file which can be re-opened afterwards.

**Project File**
Not possible, as it crashes when doing so. Instead I can provide a video.

**To Reproduce**
1. Add a Cube shape
2. Add a modifier box to it
3. Add Infill to it
4. Save the project

**Video**
https://user-images.githubusercontent.com/663900/210231233-78b3c583-65cc-4fa7-8d54-5fe3a9e47481.mp4

**Desktop (please complete the following information):**
 - OS: Linux Manjaro (XFCE)
 - Version: 2.4
 - Printer model: Anet A8

**Comment by ld-cd** [comment]
[ERROR_FILE_TO_SEND_TO_MERILL_PLZZZZ.txt](https://github.com/supermerill/SuperSlicer/files/13839239/ERROR_FILE_TO_SEND_TO_MERILL_PLZZZZ.txt)

Drops this, appears to be from around here
