### ISSUE TITLE
can't drag and drop .STL to the window anymore?

### ISSUE THREAD

**Issue by Photogad** [supermerill/SuperSlicer#357]
### Version
2.2.52.1

### Operating system type + version
win64

### Behavior
I used to be able to drag-and-drop a .STL file from a window to the super slicer window, to add it to the build plate. I can't seem to do this anymore with latest update -- it just gives me a "cancel" mouse button icon when I try to drop it in.

Or maybe you have a suggestion of something I can try to fix it.

**Comment by neophyl** [comment]
I just tried it with Super Slicer 2.2.52.1 on Windows 10 and it dropped a stl there without a problem.  When I drag it over I get a 'copy' tooltip on the icon for the stl.

**Comment by ioma8** [comment]
it works for me too
