### ISSUE TITLE
Dual Filament Issues

### ISSUE THREAD

**Issue by utzy79** [supermerill/SuperSlicer#3575]
### Version 2.5.59
_Version of SuperSlicer used goes here (help->about)_

### Operating system type + version Windows 11
_What OS are you using, and state any version #s_

### Behavior
Multi Material Prints not working correctly

When slicing a multi material print that has been setup from the Multimaterial printing option, 
It still leaves parts of the print using the wrong tool

Can confirm that the same file works in Prusa Slicer

#### Project File (.3MF) where problem occurs
_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here_

![image](https://user-images.githubusercontent.com/45909092/212525278-b95fba02-3dae-4c32-ba9c-c0cf595a1f2e.png)
![image](https://user-images.githubusercontent.com/45909092/212525306-f7a6c17f-b737-4518-9c70-2f8bb41be488.png)

**Comment by mjfsch** [comment]
under print settings, slicing, change the resolution to 0, this fixed it for me

![image](https://user-images.githubusercontent.com/99204506/212540078-0bae8851-e246-4200-8995-998c1891124f.png)

**Comment by utzy79** [comment]
Thank you, this got rid of most of it but left it in a couple of spots, then did a simplify model to cause a remesh and it worked.
