### ISSUE TITLE
Flow Calibration doesn't finish slicing or has empty preview with a certain filament profile

### ISSUE THREAD

**Issue by paul-arnold** [supermerill/SuperSlicer#358]
### Version
2.2.52

### Operating system type + version
Win 10 Pro 

### 3D printer brand / version + firmware version (if known)
P3Steel Self built, running Klipper (latest)

### Behavior
I tried to calibrate a new spool today.
However, the 5 flow calibration objects (-20 - +20) wont finish slicing or dont show a preview with a certain filament profile .
Any other filament profile works good.
It is reproducable. 
Screenshot:
![image](https://user-images.githubusercontent.com/7791335/88225637-20ad0b80-cc6b-11ea-93c3-1c4358525ee2.png)

[Supermerrill_issue.zip](https://github.com/supermerill/SuperSlicer/files/4962454/Supermerrill_issue.zip)

#### Project File (.3MF) where problem occurs
-> attached with filament profile

**Comment by supermerill** [comment]
an extrusion multiplier of 0?
I should try to add a safeguard on this setting.

**Comment by paul-arnold** [comment]
> an extrusion multiplier of 0?
> I should try to add a safeguard on this setting.

Yikes, indeed. How could I not see that?
Setting it back to 1 fixed the issue.
I probably tried to set it to 0.something and the dot plus "something" was lost somewhere.
Thanks for helping out.
