### ISSUE TITLE
Continuous Perimeter Required

### ISSUE THREAD

**Issue by swpaxton66** [supermerill/SuperSlicer#3588]
**Is your feature request related to a problem? Please describe.**
Perimeters are split for overlapping models.

**Describe the solution you'd like**
Would like to have 1 continuous perimeter for all imported models so the outline is smooth on the first layer (and other layers if required) (This is how it works in Simplify3D)

**Describe how it would work**
Be as descriptive as your skill level allows you.
Import multiple models. Overlap at least 2 models.  The perimeter should flow around both objects and not completed on each object separately.

**Describe alternatives you've considered**
I've done some SuperSlicer internet research and tried changing perimeter settings.  No luck.

**Additional context**
Add any other context or paint drawing about the feature request here.
<img width="708" alt="image" src="https://user-images.githubusercontent.com/10367776/213888264-266db0fc-e4ad-4d32-a3d6-d3a528d49ceb.png">

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/10367776/213888288-923f09fa-e5c3-4493-bbb8-3a975da9abea.png">

**Comment by swpaxton66** [comment]
Found it as merge but the perimeters are a bit weird 
<img width="859" alt="image" src="https://user-images.githubusercontent.com/10367776/213889238-0901d874-ffd6-4b5b-8ac3-60cb69d0479c.png">

**Comment by swpaxton66** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/10367776/213889293-e7d84f66-f952-41ff-a2cb-e50db29bb04a.png">
<img width="943" alt="image" src="https://user-images.githubusercontent.com/10367776/213889347-e5746173-92a4-4b99-b565-3dfb4337b2de.png">

**Comment by neophyl** [comment]
Without your project file its going to be impossible to know.  Please attach a zipped up project file  (File>Save Project As).  

Also would be helpful if you listed which version you were using.  You know, all the basic info that's asked for when opening a new issue.

**Comment by swpaxton66** [comment]
Thank you for the prompt response.  Yeah makes perfect sense.  I was blinded by a million things on the go, blindly following along the questions from the boiler plate issues list.  Here is the project file.  Would it be possible to add all of said requirements to the list of questions?  (Might be good to have it right in front of the user's face).

Windows 10
[Merged.zip](https://github.com/supermerill/SuperSlicer/files/10473278/Merged.zip)

SuperSlicer 2.4.58.5

**Comment by neophyl** [comment]
You have Perimeters & Shell>Quality>Only one Perimeter ticked for On top surfaces.  Those helper disks are one layer thick and are top surfaces.  As such its applying that to the entire shape which is what is pushing the inner perimeters around it.

**Comment by swpaxton66** [comment]
Got it.  Thanks for investigating.
