### ISSUE TITLE
Crash spiral vase selection 2.5.59.2

### ISSUE THREAD

**Issue by dentinox** [supermerill/SuperSlicer#3630]
### What happened?

When doing a calibration cube https://cdn.help.prusa3d.com/wp-content/uploads/2021/04/cube-40-40-40.zip and you select spiral vase, superslicer asks to adjust some settings. When you click yes it crashes back to windows.

settings 0.32
per 2
Wall thickness 0.8
Layers 4

### Project file & How to reproduce

Print settings
select spiral vase
Dialogbox YES.

### Version

2.5.59.2

### Operating system

Windows 10

### Printer model

Ender 5

**Comment by yuri-rage** [comment]
Identical behavior here with 2.5.59.2 nightly. Easily reproducible (crashes every time vase mode is attempted).

**Comment by JacTheMaker** [comment]
Same here Windows 11
On multiple print and filament settings.

**Comment by cypeks** [comment]
Same here 2.5.59.2 nightly build GTK3 - Ubuntu 22.10

**Comment by kymlalu** [comment]
Same here - Win10. 
For me last version where vase mod didn't crash SS was/is 2.5.59.0. Everything after just crashing.

**Comment by cypeks** [comment]
Last 2.5.59-2 pre-release also crashing.

**Comment by Lemcott** [comment]
same - WIn11 Ryzen - SuperSlicer_2.5.59.2_win64_230304

**Comment by liftbag** [comment]
Latest mac version crashes too.

**Comment by shadowdro** [comment]
Same issue here.

**Comment by Fropzs** [comment]
How to fix it? Same crash here.

**Comment by artemen** [comment]
one more here

**Comment by EvilGremlin** [comment]
do not exist in https://github.com/supermerill/SuperSlicer/actions/runs/5548343816

**Comment by EvilGremlin** [comment]
its already fixed, update more

**Comment by jaitti** [comment]
Just started with superslicer and noticed that both win and linux versions crash when trying to activate spiral mode. There is a message here pointing to a newer build which does not have any actual builds. All artifacts has been expired. It looks like it has been broken for 9 months now.. Is this slicer dying?
