### ISSUE TITLE
Typo in wiki (yer should be year)

### ISSUE THREAD

**Issue by RandomGgames** [supermerill/SuperSlicer#3632]
### What happened?

https://github.com/supermerill/SuperSlicer/wiki/Macro-&-Variable-list

Special macro variables:

- current_object_idx
- current_position[2] (x,y)
- yer **<---**
- month
- day
- 

### Project file & How to reproduce

n/a

**Comment by RandomGgames** [comment]
I would assume this is an easy fix... still hasn't gone through!

**Comment by supermerill** [comment]
thanks fixed
