### ISSUE TITLE
Using Height range modifier to change #perimiters does not work on final layer

### ISSUE THREAD

**Issue by EmanuelStassar** [supermerill/SuperSlicer#3636]
### Version
Version 2.5.59
### Operating system type + version
Windows 10 Pro 21H2

### Behavior
* _Describe the problem_ I want to print a single wall airplane wing, but the first and last few layers I want 2 perimeters. I am using height modifiers to do this. This print has 0 top and bottom layers.
* _Steps needed to reproduce the problem_
* _Expected Results_ I expected 2 perimiters on the sections I specify, but that does not work for the top layer. At the bottom it works as expected
* _Actual Results_ The final layer only has one perimeter.
  * _Screenshots if useful_ Added 2 screenshots, one of the 3D model, one of the sliced result.
![SSlicer issue top layer 1](https://user-images.githubusercontent.com/6449527/217798609-65a9781b-6b7c-41c8-abe2-b9631b01b783.JPG)
![SSlicer issue top layer 2](https://user-images.githubusercontent.com/6449527/217798630-debdf6e1-93f7-4fdd-8ff5-fe11c971f15e.JPG)
_Is this a new feature request?_ No, maybe a bugfix.
Related guides for writing feature requests: http://meta.stackexchange.com/a/259196 http://nickohrn.com/2013/09/write-great-feature-request-bug-report/

#### Project File (.3MF) where problem occurs
[Wing-1_2.zip](https://github.com/supermerill/SuperSlicer/files/10696546/Wing-1_2.zip)

_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here_

**Comment by neophyl** [comment]
You do realise that your print settings profile has 'only one perimeter on top surfaces'  enabled ?  Can you guess what happens when you untick that setting ?  ;)

**Comment by EmanuelStassar** [comment]
Oooh, I must have overlooked that one. Sorry for the trouble and thanks for your help! This slicer has soo many options that its easy to miss stuff like this.
