### ISSUE TITLE
Super slicer doesn't open on Mac, just crashes

### ISSUE THREAD

**Issue by robmc7683** [supermerill/SuperSlicer#3655]
### What happened?

The application crashes before it opens.

I have tried the latest 2.4 edition from September 23, 2022

As soon as you try to open or install the program it crashes.

This is the report I get.
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               SuperSlicer [66223]
Path:                  /private/var/folders/*/SuperSlicer.app/Contents/MacOS/SuperSlicer
Identifier:            com.merill.slic3r/
Version:               SuperSlicer SuperSlicer_2.4.58.5_2022-09-23 (SuperSlicer_2.4.58.5_2022-09-23)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2023-02-16 13:01:39.2667 -0600
OS Version:            macOS 12.6.3 (21G419)
Report Version:        12
Anonymous UUID:        D47A2F83-AB55-76AA-D507-2A2DC712F5A3

Sleep/Wake UUID:       968D5BCC-2E14-45AF-A068-86C6D9DC1C80

Time Awake Since Boot: 38000 seconds
Time Since Wake:       713 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/usr/local/opt/zstd/lib/libzstd.1.dylib'
Referenced from: '/private/var/folders/*/SuperSlicer.app/Contents/MacOS/SuperSlicer'
Reason: tried: '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x10dc4e98e __abort_with_payload + 10
1   dyld                          	       0x10dc64a72 abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x10dc64aa4 abort_with_payload + 9
3   dyld                          	       0x10dc12699 dyld4::halt(char const*) + 615
4   dyld                          	       0x10dc0e5b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	       0x10dc0d4e4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b9f5b528  rdx: 0x00007ff7b9f5b990
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b9f5b570  rsp: 0x00007ff7b9f5b528
   r8: 0x00007ff7b9f5b590   r9: 0x0000000000000000  r10: 0x00000000000000d8  r11: 0x0000000000000246
  r12: 0x00000000000000d8  r13: 0x00007ff7b9f5b990  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x000000010dc4e98e  rfl: 0x0000000000000246  cr2: 0x000000010dc14da4
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x10dc08000 -        0x10dc73fff dyld (*) <006a3e6f-3cd3-34d9-b0f2-ed6bd67a95a6> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=48.8M resident=0K(0%) swapped_out_or_unallocated=48.8M(100%)
Writable regions: Total=9396K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9396K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                            1824K        3 
__DATA_CONST                        80K        1 
__LINKEDIT                        15.6M        4 
__TEXT                            33.2M        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                            115.7M       16 

-----------
Full Report
-----------

{"app_name":"SuperSlicer","timestamp":"2023-02-16 13:01:39.00 -0600","app_version":"SuperSlicer SuperSlicer_2.4.58.5_2022-09-23","slice_uuid":"ea3f7209-f390-3268-9c90-d8081dcedc30","build_version":"SuperSlicer_2.4.58.5_2022-09-23","platform":1,"bundleID":"com.merill.slic3r\/","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.3 (21G419)","incident_id":"BE0325D7-8CE1-4717-B50E-4391716268F9","name":"SuperSlicer"}
{
  "uptime" : 38000,
  "procLaunch" : "2023-02-16 13:01:39.2372 -0600",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro11,4",
  "procStartAbsTime" : 38746860521135,
  "coalitionID" : 4201,
  "osVersion" : {
    "train" : "macOS 12.6.3",
    "build" : "21G419",
    "releaseType" : "User"
  },
  "captureTime" : "2023-02-16 13:01:39.2667 -0600",
  "incident" : "BE0325D7-8CE1-4717-B50E-4391716268F9",
  "bug_type" : "309",
  "pid" : 66223,
  "procExitAbsTime" : 38746888885874,
  "cpuType" : "X86-64",
  "procName" : "SuperSlicer",
  "procPath" : "\/private\/var\/folders\/*\/SuperSlicer.app\/Contents\/MacOS\/SuperSlicer",
  "bundleInfo" : {"CFBundleShortVersionString":"SuperSlicer SuperSlicer_2.4.58.5_2022-09-23","CFBundleVersion":"SuperSlicer_2.4.58.5_2022-09-23","CFBundleIdentifier":"com.merill.slic3r\/"},
  "storeInfo" : {"deviceIdentifierForVendor":"6F796972-1F42-59D7-A274-9B826114E73E","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.merill.slic3r\/",
  "crashReporterKey" : "D47A2F83-AB55-76AA-D507-2A2DC712F5A3",
  "wakeTime" : 713,
  "sleepWakeUUID" : "968D5BCC-2E14-45AF-A068-86C6D9DC1C80",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '\/usr\/local\/opt\/zstd\/lib\/libzstd.1.dylib'","Referenced from: '\/private\/var\/folders\/*\/SuperSlicer.app\/Contents\/MacOS\/SuperSlicer'","Reason: tried: '\/usr\/local\/opt\/zstd\/lib\/libzstd.1.dylib' (no such file), '' (no such file), '' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":735115,"threadState":{"r13":{"value":140701953538448},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701953537424},"cr2":{"value":4525739428},"rdx":{"value":140701953538448},"r10":{"value":216},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4525975950,"matchesCrashFrame":1},"rbp":{"value":140701953537392},"rsp":{"value":140701953537320},"r12":{"value":216},"rcx":{"value":140701953537320},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":289166,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":0},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":0},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4525686784,
    "size" : 442368,
    "uuid" : "006a3e6f-3cd3-34d9-b0f2-ed6bd67a95a6",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703520571392,
  "size" : 19331678208,
  "uuid" : "b6d97ead-9d19-3228-adaa-cca8452c02d2"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=48.8M resident=0K(0%) swapped_out_or_unallocated=48.8M(100%)\nWritable regions: Total=9396K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9396K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                            1824K        3 \n__DATA_CONST                        80K        1 \n__LINKEDIT                        15.6M        4 \n__TEXT                            33.2M        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                            115.7M       16 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    },
    {
      "rolloutId" : "61301e3a61217b3110231469",
      "factorPackIds" : {
        "SIRI_FIND_MY_CONFIGURATION_FILES" : "6348493aa52bb16adc4e4d06"
      },
      "deploymentId" : 240000023
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro11,4, BootROM 476.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.2 GHz, 16 GB, SMC 2.29f24
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Display: Color LCD, 2880 x 1800 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB30Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

### Project file & How to reproduce

{"app_name":"SuperSlicer","timestamp":"2023-02-16 13:01:39.00 -0600","app_version":"SuperSlicer SuperSlicer_2.4.58.5_2022-09-23","slice_uuid":"ea3f7209-f390-3268-9c90-d8081dcedc30","build_version":"SuperSlicer_2.4.58.5_2022-09-23","platform":1,"bundleID":"com.merill.slic3r/","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.3 (21G419)","incident_id":"BE0325D7-8CE1-4717-B50E-4391716268F9","name":"SuperSlicer"}
{
"uptime" : 38000,
"procLaunch" : "2023-02-16 13:01:39.2372 -0600",
"procRole" : "Default",
"version" : 2,
"userID" : 502,
"deployVersion" : 210,
"modelCode" : "MacBookPro11,4",
"procStartAbsTime" : 38746860521135,
"coalitionID" : 4201,
"osVersion" : {
"train" : "macOS 12.6.3",
"build" : "21G419",
"releaseType" : "User"
},
"captureTime" : "2023-02-16 13:01:39.2667 -0600",
"incident" : "BE0325D7-8CE1-4717-B50E-4391716268F9",
"bug_type" : "309",
"pid" : 66223,
"procExitAbsTime" : 38746888885874,
"cpuType" : "X86-64",
"procName" : "SuperSlicer",
"procPath" : "/private/var/folders//SuperSlicer.app/Contents/MacOS/SuperSlicer",
"bundleInfo" : {"CFBundleShortVersionString":"SuperSlicer SuperSlicer_2.4.58.5_2022-09-23","CFBundleVersion":"SuperSlicer_2.4.58.5_2022-09-23","CFBundleIdentifier":"com.merill.slic3r/"},
"storeInfo" : {"deviceIdentifierForVendor":"6F796972-1F42-59D7-A274-9B826114E73E","thirdParty":true},
"parentProc" : "launchd",
"parentPid" : 1,
"coalitionName" : "com.merill.slic3r/",
"crashReporterKey" : "D47A2F83-AB55-76AA-D507-2A2DC712F5A3",
"wakeTime" : 713,
"sleepWakeUUID" : "968D5BCC-2E14-45AF-A068-86C6D9DC1C80",
"sip" : "enabled",
"isCorpse" : 1,
"exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
"termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '/usr/local/opt/zstd/lib/libzstd.1.dylib'","Referenced from: '/private/var/folders//SuperSlicer.app/Contents/MacOS/SuperSlicer'","Reason: tried: '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '' (no such file), '' (no such file)"]},
"extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
"faultingThread" : 0,
"threads" : [{"triggered":true,"id":735115,"threadState":{"r13":{"value":140701953538448},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701953537424},"cr2":{"value":4525739428},"rdx":{"value":140701953538448},"r10":{"value":216},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4525975950,"matchesCrashFrame":1},"rbp":{"value":140701953537392},"rsp":{"value":140701953537320},"r12":{"value":216},"rcx":{"value":140701953537320},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":289166,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":0},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":0},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
"usedImages" : [
{
"source" : "P",
"arch" : "x86_64",
"base" : 4525686784,
"size" : 442368,
"uuid" : "006a3e6f-3cd3-34d9-b0f2-ed6bd67a95a6",
"path" : "/usr/lib/dyld",
"name" : "dyld"
}
],
"sharedCache" : {
"base" : 140703520571392,
"size" : 19331678208,
"uuid" : "b6d97ead-9d19-3228-adaa-cca8452c02d2"
},
"vmSummary" : "ReadOnly portion of Libraries: Total=48.8M resident=0K(0%) swapped_out_or_unallocated=48.8M(100%)\nWritable regions: Total=9396K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9396K(100%)\n\n VIRTUAL REGION \nREGION TYPE SIZE COUNT (non-coalesced) \n=========== ======= ======= \nSTACK GUARD 56.0M 1 \nStack 8192K 1 \nVM_ALLOCATE 12K 3 \n__DATA 1824K 3 \n__DATA_CONST 80K 1 \n__LINKEDIT 15.6M 4 \n__TEXT 33.2M 2 \ndyld private memory 1024K 1 \n=========== ======= ======= \nTOTAL 115.7M 16 \n",
"legacyInfo" : {
"threadTriggered" : {

}
},
"trialInfo" : {
"rollouts" : [
{
"rolloutId" : "5fb4245a1bbfe8005e33a1e1",
"factorPackIds" : {

  },
  "deploymentId" : 240000021
},
{
  "rolloutId" : "61301e3a61217b3110231469",
  "factorPackIds" : {
    "SIRI_FIND_MY_CONFIGURATION_FILES" : "6348493aa52bb16adc4e4d06"
  },
  "deploymentId" : 240000023
}
],
"experiments" : [

]
}
}

Model: MacBookPro11,4, BootROM 476.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.2 GHz, 16 GB, SMC 2.29f24
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Display: Color LCD, 2880 x 1800 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort:
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB30Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

### Version

2.4

### Operating system

Mac OS 12.6.3

### Printer model

Creality ender 3 S1 Pro, Anycubic Vyper

**Comment by Morcegolas** [comment]
I'm getting the same problem in my Mac running the same OS 12.6.3.
I'm compiling the software now to see if it helps.

**Comment by Morcegolas** [comment]
brew install zstd

This resolved my problem.

**Comment by Darkstar77** [comment]
This is your problem:

```
Termination Reason: Namespace DYLD, Code 1 Library missing
Library not loaded: '/usr/local/opt/zstd/lib/libzstd.1.dylib'
Referenced from: '/private/var/folders/*/SuperSlicer.app/Contents/MacOS/SuperSlicer'
Reason: tried: '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)
```

You're missing a library, as @Morcegolas has pointed out. Install the missing library, and you should be good to go.
