### ISSUE TITLE
756 Open Edge

### ISSUE THREAD

**Issue by raymadigan** [supermerill/SuperSlicer#3659]
### What happened?

I have an stl file that was generated in freecad from two different bodies.  The bodies were combined using the lattice2 workbench and Attached Placement feature.  
![image](https://user-images.githubusercontent.com/63692124/219971525-2d7fe992-5ea1-4f74-a4b1-dbf186284b89.png)
If I look at each of the two objects individually, they both have zero errors.  

### Project file & How to reproduce

[IIRing.zip](https://github.com/supermerill/SuperSlicer/files/10777791/IIRing.zip)

### Version

2.4.58.5

### Operating system

Ubuntu 22.04.2 LTS

### Printer model

Ender 3 S1 Pro

**Comment by Pavulon87** [comment]
What does this have to do with SuSi?
Blender also shows 756 non manifold edges.
![Zrzut ekranu z 2023-02-23 21-54-41](https://user-images.githubusercontent.com/23641103/221028489-4158f0ab-ab06-4a22-ab5b-6cc5284e23b1.png)

**Comment by raymadigan** [comment]
I attempted to close it after I submitted it but couldn't sort it out.
