### ISSUE TITLE
Brim not being in contact with object

### ISSUE THREAD

**Issue by Tinchus2009** [supermerill/SuperSlicer#367]
### Version
2.2.52

### Operating system type + version
win64
### 3D printer brand / version + firmware version (if known)
Custom, reprapfirmware

### Behavior

When I activate the brim and supports together, the brin as not in contact with the object in many places. 

_Is this a new feature request?_

**Comment by supermerill** [comment]
it's the way the support work.
If you want a brim instead of a raft under the supports, check supports->raft->solid first layer
