### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by Coffee0297** [supermerill/SuperSlicer#368]
### Version
All

### Operating system type + version
All
### 3D printer brand / version + firmware version (if known)
All

### Feature request
![image](https://user-images.githubusercontent.com/43273303/88574900-56733b00-d043-11ea-96bb-82b32d7936e0.png)
Is it possible to make the slicing multithreaded? and the gcode generation? its real slow when enabeling features that is clearly single threaded.

**Comment by supermerill** [comment]
> Is it possible to make the slicing multithreaded? 
it is where possible

> and the gcode generation? its real slow when enabeling features that is clearly single threaded.

yes, it's not possible to multi-thread a sequential process like writing the gcode file, as you need the result of the previous move to compute the next one.

**Comment by Coffee0297** [comment]
So it wuld not be possible to "slice" the model and assigning parts of the model to difrent threads? and just use 1 core to "merge" them? im asking bc slicing a high res model it takes like 10-30min just for the gcode generation.

Kind Regards Tonny

**Comment by supermerill** [comment]
problem is you can't know where to start in the "part" if you don't know where the last extruder position is, or you'll have absurd travels.

**Comment by supermerill** [comment]
You can send me your project, and i may be able to maybe speed it up a bit if i found a bottleneck that can be optimised.

**Comment by Coffee0297** [comment]
yea i just wait on it completes, i was just wondering if it was possible

Kind regards Tonny
