### ISSUE TITLE
Super Slicer crashes when attempting to enable vase mode on a 25mm cube on a Mac

### ISSUE THREAD

**Issue by bobsponsler** [supermerill/SuperSlicer#3715]
### Version
Version: 2.5.59.2
Build: SuperSlicer_2.5.59.2_2023-02-24

### Operating system type + version
Operating System: Macintosh
System Architecture: 64 bit
System Version: macOS Version 13.2.1 (Build 22D68)
Total RAM size [MB]: 17,180MB

### Behavior
25mm box -> Print Tab -> Vase Mode -> Yes -> Super Slicer crashes and closes, apple sends report and reopens, click vase and yes again, crashes again.  I have not been able to enable vase mode at all.  

#### Project File (.3MF) where problem occurs

[Super Slicer Vase Bug.3mf.zip](https://github.com/supermerill/SuperSlicer/files/10951401/Super.Slicer.Vase.Bug.3mf.zip)

(not zipped - i just added .zip to the end)

**Comment by paulgiordano** [comment]
There is a bug in src/slic3r/PrintConfig.cpp on line 5086. Are you using pre-packed or compiling yourself?
