### ISSUE TITLE
[Bug] Variable layer height sometimes not working

### ISSUE THREAD

**Issue by Pavulon87** [supermerill/SuperSlicer#372]
### Version
SuperSlicer_2.2.52.0_win64_20200623
SuperSlicer_2.2.52.1_win64_20200703

### Operating system type + version
Windows 10

### Behavior
Since the 2.2.52 "Variable layer height" sometimes don't work as it should. May be related to "Z full step"(set to 0.04).

Project from 2.2.51 imported in 2.2.52 lose variable layer height settings/profile, but after applying it is ok.

2.2.51 - working:
![Zrzut ekranu 2020-07-28 07 07 13](https://user-images.githubusercontent.com/23641103/88624288-f7dfa880-d0a6-11ea-8be4-e043ed64aac2.png)
**2.2.52 - not working:**
![Zrzut ekranu 2020-07-28 07 07 18](https://user-images.githubusercontent.com/23641103/88624287-f7471200-d0a6-11ea-8bb9-cc5d6d8c3de1.png)
2.2.52 - preview:
![Zrzut ekranu 2020-07-28 07 07 36](https://user-images.githubusercontent.com/23641103/88624283-f6ae7b80-d0a6-11ea-88f9-035062ab919a.png)

2.2.51 - working:
![Zrzut ekranu 2020-07-28 07 10 31](https://user-images.githubusercontent.com/23641103/88624278-f615e500-d0a6-11ea-9155-2b9c6219f23d.png)
**2.2.52 - not working:**
![Zrzut ekranu 2020-07-28 07 10 33](https://user-images.githubusercontent.com/23641103/88624277-f57d4e80-d0a6-11ea-8278-a95afb179e6d.png)
2.2.52 - preview:
![Zrzut ekranu 2020-07-28 07 10 38](https://user-images.githubusercontent.com/23641103/88624274-f57d4e80-d0a6-11ea-952f-b81d8b5d7dc8.png)
2.2.52 - working accidentally
![Zrzut ekranu 2020-07-28 07 33 43](https://user-images.githubusercontent.com/23641103/88624271-f4e4b800-d0a6-11ea-82ab-3f2890caa24f.png)

2.2.51 - working:
![Zrzut ekranu 2020-07-28 07 06 07](https://user-images.githubusercontent.com/23641103/88624284-f7471200-d0a6-11ea-9710-197eb53e6b94.png)
2.2.52 - working:
![Zrzut ekranu 2020-07-28 07 06 15](https://user-images.githubusercontent.com/23641103/88624289-f7dfa880-d0a6-11ea-839b-3c40d3ffa1c1.png)

2.2.51 - working:
![Zrzut ekranu 2020-07-28 07 08 44](https://user-images.githubusercontent.com/23641103/88624281-f6ae7b80-d0a6-11ea-95b6-571800be2969.png)
2.2.52 - working:
![Zrzut ekranu 2020-07-28 07 08 45](https://user-images.githubusercontent.com/23641103/88624280-f615e500-d0a6-11ea-940b-122c09182930.png)

#### Project File (.3MF) where problem occurs
2.2.52 - [Body1(1).3mf](https://github.com/supermerill/SuperSlicer/files/4986238/Body1.1.zip)
2.2.51 - [Body1(2).3mf](https://github.com/supermerill/SuperSlicer/files/4986239/Body1.2.zip)

**Comment by kursatu** [comment]
It is an essential feature.
Any possibility that it can this be fixed soon?
I have observed this as well. 
I've the "Enable variable layer height" enabled in the printer setting, but still does not work.
Not sure if it ever works or ever worked.
@Pavulon87 Where is that "Z full steps" setting?
Or is there any pattern for it working accidentally?

**Comment by neophyl** [comment]
I loaded in both your body 1(1) and body 1(2) projects into 2.2.52,  I can confirm that (1) the variable layer settings are loaded with the project and that with (2) the variable layer heights have been reset and are not there (I assume they are supposed to be ?).

One difference I did notice between the projects though is that in (1) the Z stepping is set to your 0.04 value that you mentioned but (2) the stepping value is set at 0.005.  

The Z stepping value isnt being saved in (2) naturally as this project was saved by 2.2.51 which doesnt have the Z stepping value. I suspect when its imported in to 2.2.52 it gets set to the default of 0.005 which in turn invalidates the variable layer settings so you have to do them again but once generated it works ok as the steps match what is used for stepping when generated.  

If you look inside the 3mf files in the Slic3r_PE.config files then the (1) contains at the very bottom ; z_step = 0.04 but the same file for (2) does not have that configuration entry.  Doing a compare on the 2 config files there are several more entries that the one saved in 2.2.52 has over the one saved by 2.2.51.  This isnt surprising as 2.2.52 has more settings.  

So in practice it looks like variable layer maps are not compatible between projects saved with 2.2.51 and 2.2.52 at the moment.

**Comment by Pavulon87** [comment]
It seems that some values are working and some are not.
0.01 - OK
0.02 - not OK
0.03 - OK
0.04 - not OK
0.05 - not OK
0.06 - not OK

But after resizing model height to round millimeters(18.51mm ->19mm) there is everything OK.

**Comment by Pavulon87** [comment]
After changing default value in source files it works great. Legend is correct either.
def->set_default_value(new ConfigOptionFloat(0.04));
![Zrzut ekranu 2020-07-30 20 28 14](https://user-images.githubusercontent.com/23641103/88960197-72751780-d2a3-11ea-92d2-c24f3058fba7.png)

I'm sure that default value is used instead of config where it should not, but i'm too dumb to figure out where is the problem.

**Comment by kursatu** [comment]
The problem happen w/o a project file as well.
That what it makes this feature unusable.
I did not find a workaround yet. Changing the Z full steps to the default value did work as a workaround.
Please see the attached images.

![Defect3_1](https://user-images.githubusercontent.com/1686475/88980009-a0dcfd80-d277-11ea-83ca-e1d996ae7786.png)
![Defect3_2](https://user-images.githubusercontent.com/1686475/88980016-a4708480-d277-11ea-86a3-d161c7e004f9.png)

**Comment by Pavulon87** [comment]
ohh... Plater.cpp 
Works great now.
