### ISSUE TITLE
Perimeters aren't generated properly on 2.5.59 release

### ISSUE THREAD

**Issue by HitLuca** [supermerill/SuperSlicer#3720]
### What happened?

Looks like the latest pre-release has some issues dealing with perimeters in certain cases:

![image](https://user-images.githubusercontent.com/7645621/224768556-42d08c26-2616-46d5-8613-b7a95a127293.png)

![image](https://user-images.githubusercontent.com/7645621/224768406-baec3214-32b8-496f-ad55-ebc6118cb61c.png)

Tested the same stl using the latest officail release and the issue isn't visible there

### Project file & How to reproduce

[Hinge_Top_Right.zip](https://github.com/supermerill/SuperSlicer/files/10959591/Hinge_Top_Right.zip)

### Version

2.5.59

### Operating system

Windows 10

### Printer model

voron 0.2 with custom profile

**Comment by JanB97** [comment]
![image](https://user-images.githubusercontent.com/7881168/224769789-ef74e30a-2919-4c18-a3bb-0614d77a89df.png)

Yes I also have issues with this. 
They just are in mid air for me without any reason for that.

**Comment by Gizzzle** [comment]
![grafik](https://user-images.githubusercontent.com/49840050/225127793-ad0f8ede-ba07-44ea-a941-a4876e4c2ccb.png)

Can confirm.

**Comment by DiomedesDominguez** [comment]
Had the same issue last weekend, where a threaded part was creating a lot of inconsistency. Here is the preview and a test print
![WhatsApp Image 2023-03-12 at 00 43 08](https://user-images.githubusercontent.com/4379316/225139909-86a971cc-1a05-422e-ada5-66d7852388e3.jpg)

![WhatsApp Image 2023-03-12 at 00 44 14](https://user-images.githubusercontent.com/4379316/225140126-04d414cb-1015-4d59-bc13-cb7556cd552b.jpg)

As you can see, the slicer was trying to print in mid air. I had to go back to 2.4 version.

**Comment by mia-0** [comment]
Possible duplicate of #3681

**Comment by DiomedesDominguez** [comment]
> Possible duplicate of #3681

it is

**Comment by HitLuca** [comment]
Closing as duplicate of #3681 then
