### ISSUE TITLE
Crash in vase mode

### ISSUE THREAD

**Issue by digiTALker** [supermerill/SuperSlicer#3722]
### Version
Версия 2.5.59

### Operating system type + version
Operating System: Windows
System Architecture: 64 bit
Windows Version: Windows 10 (build 19045), 64-bit edition

### Behavior
At the begining I tryed to use my config "PLA Vase" (see in attachment). It worked good on previous release.
Now when I choose this config SS is crashing immediately.
After that I decide to make new config for vase mode. Wnen I pick check box "vase mode" SS also closed without any messages.

_Is this a new feature request?_
Related guides for writing feature requests: http://meta.stackexchange.com/a/259196 http://nickohrn.com/2013/09/write-great-feature-request-bug-report/

#### Project File (.3MF) w
[1.2 Flsun V400.zip](https://github.com/supermerill/SuperSlicer/files/10964501/1.2.Flsun.V400.zip)
here problem occurs
_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here_
[1.2 PLA Vase V400.zip](https://github.com/supermerill/SuperSlicer/files/10964496/1.2.PLA.Vase.V400.zip)
![chrome_NRVIuJXejZ](https://user-images.githubusercontent.com/13745784/224906958-0ca0779b-7010-4ca2-82e5-f4c8d9b5e4fb.gif)

**Comment by andrewmherren** [comment]
I am having the same issue.

Version 2.5.59.2

Windows 10 64 bit

I click the vase mode checkbox and get the modal showing settings that will be changed. Click yes and it immediately crashes as demonstrated in the image by digiTALker
