### ISSUE TITLE
Is flow rate baked into the extrusion for multi-material?

### ISSUE THREAD

**Issue by slavedas** [supermerill/SuperSlicer#373]
### Version
FreeCad Edition
### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Ender 3 Pro + Klipper

### Behavior
This is a question about behavior.  I am playing with a DIY MMU and I like that I can set a filament and get the temperature to change etc, but I'm assuming the flow rate is baked into the extrusion distances since I don't see M221s being issued.  But it's hard to know then if flow rate has changed when tools/filaments change.  I just wanted to check to see if they are.  Would it be possible to just comment in the gcode what the new extrusion multiplier is?

**Comment by supermerill** [comment]
It's the one in the filament profile used for the extrusion.

> Would it be possible to just comment in the gcode what the new extrusion multiplier is?

It's possible, but why not printing all settings that change at every tool change? It's a bit too verbose.

If you want to test, use a 0.001 multiplier, you'll clearly see were there is almost no extrusion.
