### ISSUE TITLE
Layer_Z reporting wrong

### ISSUE THREAD

**Issue by Exerqtor** [supermerill/SuperSlicer#375]
### Version
2.2.52

### Operating system type + version
Windows 10 x64

### 3D printer brand / version + firmware version (if known)
Home made CoreXY / Duet 2 running RRF 2.05.1 and DWC 3.1.1

### Behavior
When using ";[layer_z]" in "Before layer change G-code" section the sliced file reports the z-height AFTER layer change.

**Comment by supermerill** [comment]
yes, you can write something before the move to this Z.

I'll add a 'previous_layer_z' for before_layer_gcode and layer_gcode.
It will be equal to 0 if there are no previous layer.

**Comment by Exerqtor** [comment]
Should do the trick, awesome!
