### ISSUE TITLE
Wild external perimeters

### ISSUE THREAD

**Issue by Xeroxxx** [supermerill/SuperSlicer#3771]
### What happened?

Currently improving my printer with parts. However I get strange external perimeters that are actually not present within the model. Its easy to remove with pliers. See this as report to have more data to reproduce, as it doesnt happen in 2.5.59.0.

![Capture](https://user-images.githubusercontent.com/1109954/229472575-8859d030-c8f4-45b0-8a76-56ae26e74edd.JPG)
![Capture2](https://user-images.githubusercontent.com/1109954/229473257-177d480c-019a-4662-8eb4-d22373f7074f.JPG)
![Bottom](https://user-images.githubusercontent.com/1109954/229473269-44de2ec2-cd05-4f3c-a9da-12fe74df45a0.JPG)

### Project file & How to reproduce

[Tap_Magnet_Left_r2.zip](https://github.com/supermerill/SuperSlicer/files/11136863/Tap_Magnet_Left_r2.zip)

### Version

Version 2.5.59.2

### Operating system

Windows 10

### Printer model

Voron 2.4r2

**Comment by DVSVIDEO** [comment]
The same was observed with the calibration cube on the finished print. They are in the X and Y recesses.
In addition, on one occasion there was a strange movement: the head went out to the X and Y max without extruding, then went back in and continued printing.
So many BUGs have accumulated in the SuperSlicer that I am suspending its use.

**Comment by DVSVIDEO** [comment]
https://github.com/supermerill/SuperSlicer/issues/3769

**Comment by Xeroxxx** [comment]
Duplicate
