### ISSUE TITLE
Arachne doesn't generate top surfaces properly

### ISSUE THREAD

**Issue by theodiem** [supermerill/SuperSlicer#3783]
### What happened?

When using arachne, top surface, except for the tallest one, doesn't get generated with the same "top surface settings", for example single perimeter and flow/speed settings.

First screenshot with "classic" selected
![image](https://user-images.githubusercontent.com/1006506/230462249-597f1949-9616-4d9e-9051-3bd09e3f5f64.png)

second screen with only changing to arachne
![image](https://user-images.githubusercontent.com/1006506/230462272-457b26cb-6875-43b2-aeeb-be41802172c0.png)

### Project file & How to reproduce

But it happens with any file I use, if I keep "classic", top surfaces are as expected.

### Version

2.5.59.2

### Operating system

windows 11

### Printer model

voron 2.4 with afterburner/galileo

**Comment by gaifeng8864** [comment]
> ### What happened?
> When using arachne, top surface, except for the tallest one, doesn't get generated with the same "top surface settings", for example single perimeter and flow/speed settings.
> 
> First screenshot with "classic" selected ![image](https://user-images.githubusercontent.com/1006506/230462249-597f1949-9616-4d9e-9051-3bd09e3f5f64.png)
> 
> second screen with only changing to arachne ![image](https://user-images.githubusercontent.com/1006506/230462272-457b26cb-6875-43b2-aeeb-be41802172c0.png)
> 
> ### Project file & How to reproduce
> But it happens with any file I use, if I keep "classic", top surfaces are as expected.
> 
> ### Version
> 2.5.59.2
> 
> ### Operating system
> windows 11
> 
> ### Printer model
> voron 2.4 with afterburner/galileo

I have read the instructions, the arachne mode is like this, it is not a BUG. But I also want the single outline top in arachne mode, it's very beautiful.

**Comment by theodiem** [comment]
> 
> I have read the instructions, the arachne mode is like this, it is not a BUG. But I also want the single outline top in arachne mode, it's very beautiful.

Can you provide a link to said instructions?

I find a bit odd because the tallest surface does take the "only one perimeter" in consideration. If it is the intended behavior I find at least a bit confusing since the affected option is neither "grayed out" or something that tells it works "only in a given condition".
