### ISSUE TITLE
Overhang threshold transforming curves into straight lines

### ISSUE THREAD

**Issue by theodiem** [supermerill/SuperSlicer#3785]
### What happened?

After migrating to 2.5 beta, I've noticed that overhang lines are being converted to straight connections.
I know it makes sense in a bridge which is kinda very very difficult to make corners in a unsupported line .. but overhangs are not the case. I would like to apply overhang speeds and fan but not treat those lines as "bridges".

![image](https://user-images.githubusercontent.com/1006506/230462035-1be693ef-81f0-416b-ae2f-fc44228176bf.png)

### Project file & How to reproduce

1. Draw a cilinder
2. make a tapered hole inside it (so you create overhangs on the inside)
3. set your overhand threshold to lower the angle (but keep the bridge flow threshold higher than that, so the lines aren't marked as bridge)
4. watch and cry as the slicer makes 4 straight lines in your perfect overhung circle.

### Version

2.5.59.2

### Operating system

windows 11

### Printer model

voron 2.4 with afterburner/galileo

**Comment by Kerman-ap** [comment]
having the same issue here

**Comment by blandown** [comment]
Same here.
When unchecking the "threshold for" option in "Overhangs", the problem disappears

![2023-05-20_19-22](https://github.com/supermerill/SuperSlicer/assets/26684985/b8ae2741-aef8-4433-802d-e70be25b691f)
![2023-05-20_19-22_1](https://github.com/supermerill/SuperSlicer/assets/26684985/0508ca7c-179a-44e6-8317-25acbfb63125)
![Imagem do WhatsApp de 2023-05-20 à(s) 19 23 03](https://github.com/supermerill/SuperSlicer/assets/26684985/a40bb537-797b-4525-a842-a8fdbf4c242c)

**Comment by abrasius** [comment]
> Got this interesting slicing result with runaway external perimeter: ![image](https://user-images.githubusercontent.com/95570029/246558033-c70806eb-47d4-4d6f-8c2d-9e6e0705db35.png)
> 
> ..And got it to behave by adding curve smoothing of 0.1mm: ![image](https://user-images.githubusercontent.com/95570029/246558100-ddd495a7-0dcb-4391-b5b5-c27d06c56680.png)

**Comment by theodiem** [comment]
Unfortunately that solution doesn't work on my models :( .. would have loved if it did. Makes a bit difficult to use overhang speed modifier on 2.5 :(

**Comment by VanessaE** [comment]
Another thing I've found that sometimes helps to mitigate this bug is simply changing the (base) layer height.  For example if it's 0.2 mm, lower it to 0.17 mm or so, and the problem goes away, at least at that moment.

**Comment by j-snijder** [comment]
Not working for me, as moving the object away from mid bed isn't either.

It could be something with profiles because when I loaded a profile from an older cura the problem also happened on files that sliced okay before.

Anyway I reverted to 5.3.1 and it looks like its okay, for now.

Thanks for a good slicer anyway 😁

**Comment by Murrdo** [comment]
![image](https://github.com/supermerill/SuperSlicer/assets/146051709/65022698-6a1e-4d7d-98d9-b004bb4e5830)

The bug remained in the latest version, I checked it against the version taken from here - 
https://github.com/supermerill/SuperSlicer/releases/tag/2.5.59.6
And here - 
https://github.com/supermerill/SuperSlicer/actions/runs/7372223946
[model.zip](https://github.com/supermerill/SuperSlicer/files/13802584/model.zip)
l/SuperSlicer/actions/runs/7372223946

**Comment by Murrdo** [comment]
I removed all print and printer profiles, the defect was reduced by 95%
(when cutting arachne and the threshold for overhangs is set)
Now artifacts appear if you change the extrusion width (for perimeters) other than the default one.
For example:
![image](https://github.com/supermerill/SuperSlicer/assets/146051709/0b6ae25c-790a-4465-a3d0-5aa072e588b7)
Gives:
![image](https://github.com/supermerill/SuperSlicer/assets/146051709/aa2910f7-2087-4354-a88d-2da329b327ef)


But after a couple of saves and changes in the wall thickness, the defect disappeared...
I don’t understand what exactly causes the artifacts to appear, but now it’s clearly related to the extrusion width settings
