### ISSUE TITLE
Extrude Loop: wipe_inside_start

### ISSUE THREAD

**Issue by NerdHarder615** [supermerill/SuperSlicer#3803]
### Version
2.5.59.2

### Operating system type + version
Linux

### Behavior
Slicing 2 files and getting an error "Error while writing gcode: two points are at the same position. Please send the .3mf to the dev team."

_Is this a new feature request?_
No

#### Project File (.3MF) where problem occurs
File is 36MB so I can't upload it here, this is a link to the file:
Zip:
https://drive.proton.me/urls/87DBASPTZW#9UQJsxQwqakM
tar.gz:
https://drive.proton.me/urls/RNY685FK0G#kUGOzISGdVv9

STL Files:
https://drive.proton.me/urls/KFDFYS4EC4#0aOMOSgfULT4

**Comment by legoman27** [comment]
Version - 2.5.59.8
OS - Win 10 home 10.0.19045



had the same issue slicing a file

STL has some errors that may or may not be related
auto repair says it did the following;
4 edge fixed
1 facet removed
22 open edges remaining

the file slices successfully when 'Print Settings > perimeters & shell > overhangs > threshold for' is set to FALSE



3mf project file
https://drive.google.com/file/d/1ILJbISQ8Ko8ZIGQi95BD_MKwFxLs6Ezd/view?usp=sharing

**Comment by supermerill** [comment]
Thanks for the report.
It's an arachne bug, fixed in latest release
