### ISSUE TITLE
Acceleration Control: "Decel w/ Target" Broken [RRF]

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#3821]
### What happened?

When acceleration control is used and "decelerate with target acceleration" enabled, the gcode is incorrect:

![image](https://user-images.githubusercontent.com/12439543/235332198-5134b3d4-8f0f-4d44-9f20-9d85677a2510.png)

Despite splitting the travel moves to allow the target decel, no M204 command is given between, so the travel move decelerates at the full 5000 mm/s^2, instead of the desired 1200.

### Project file & How to reproduce

[decel-to-target.3mf.txt](https://github.com/supermerill/SuperSlicer/files/11360447/decel-to-target.3mf.txt)

### Version

2.5.59.2

### Operating system

Windows 10 x64

### Printer model

UMO+

**Comment by CCS86** [comment]
![image](https://github.com/supermerill/SuperSlicer/assets/12439543/73a2d956-a67d-4987-ab5e-538bc1e0f93b)

**Comment by CCS86** [comment]
@supermerill

**Comment by supermerill** [comment]
fixed.
It was only checking the main accel to check if it write it.
but in your first picture, it's 3650 as it began by the internal perimeter.
