### ISSUE TITLE
Support base layer count and base offset

### ISSUE THREAD

**Issue by ricosander** [supermerill/SuperSlicer#3828]
I'm trying to improve support settings and two things came to mind.

It would be nice, if one could change the BASE of the support.
WIth base I'm thinking of the 1st Layer below the support pattern.

A) The **offset** from the support itself, as in the distance from the support pattern
and
B) the **height** of the support-base, as in more solid layers above the 1st layer of the support structure.

![image](https://user-images.githubusercontent.com/61231999/235764301-cb7dedb9-757e-44a5-b9f7-a56406096203.png)

**Comment by neophyl** [comment]
Offset from the support is already there as its part of Prusa Slicer, called First Layer Expansion.  Is SuSi its located in Print Settings>Support Material>Raft> First Layer.  There are 2 settings on that line 
![image](https://user-images.githubusercontent.com/46955527/235995845-42d3273d-607a-4702-8134-5fd4287d9b6c.png)
the second one controls how much the first layer of the supports expands outwards.  

The number of base layers is not yet available.  That one has been requested multiple times between the prusa github and this one.
