### ISSUE TITLE
Inside brim sometimes prints one ring per object at a time, moving the tool around far more than needed

### ISSUE THREAD

**Issue by zbrozek** [supermerill/SuperSlicer#383]
### Version
2.2.52.1

### Operating system type + version
Windows 10

### Behavior
Inside brim when using multiple objects gcode prints usually-but-not-always prints one ring of the brim per object, then moves to the next object. It eventually prints all of the brim, but takes vastly longer to do it than it should. There's some chance that I have a magic combination of settings to trigger this bug. I suspect looping perimeters but am away from a real computer to try it just at the moment.

- Import multiple objects that have interior first-layer gaps.
- Enable inside brim.
- Slice and print.
- Observe that rings are printed one-at-a-time-per-object.

It would be great if all of the rings for an object printed at once rather than moving the tool all over the place.

**Comment by supermerill** [comment]
#351
