### ISSUE TITLE
SuperSlicer crash when turn on spiral vase mode

### ISSUE THREAD

**Issue by UchihaYuki** [supermerill/SuperSlicer#3852]
### What happened?

When I tick the spiral vase mode and choose yes. The software crashed.

### Project file & How to reproduce

Just click on spiral vase mode and choose yes.

### Version

2.5.59.2

### Operating system

windows 10

**Comment by UchihaYuki** [comment]
If you need any log files. Please let me know.

**Comment by Creo2005** [comment]
Known bug in 2.5.59.2. Use 2.5.59.0

**Comment by UchihaYuki** [comment]
> Known bug in 2.5.59.2. Use 2.5.59.0

Thank you!
