### ISSUE TITLE
Improper first layer of large print

### ISSUE THREAD

**Issue by hansratzinger** [supermerill/SuperSlicer#3875]
### Version
Version 2.4.58.5

### Operating system type + version
Win 10 Version 22H2 Build 19045.3086

### Behavior
* Slicing a very large print (185 x 226 x 235 mm) for Anycubic Vyper (max 245 x 245 x 260).
![Screenshot 2023-06-17 000440](https://github.com/supermerill/SuperSlicer/assets/50781679/79b239e1-b71b-422d-9470-02334af4200d)

After slicing the first layer represents only a fraction of the entire bottom of the model.
![Tube_without_thread_front_2nd_layer](https://github.com/supermerill/SuperSlicer/assets/50781679/7c828235-5698-442a-8e36-8892725619d4)

* Steps:
1. import model
KT-Muffe_DN150-20_Grad_mit_50_Schlauchanschluss_teilbar v18.3mf
2. rotate x 90°
3. place on face
4. slice now
5. go to level 1 bottom view 
![grafik](https://github.com/supermerill/SuperSlicer/assets/50781679/a0eab0f5-f686-48f6-af37-1da0b2e6bea7)

* Result in Cura:
![Cura_vyper_Tube_without_thread](https://github.com/supermerill/SuperSlicer/assets/50781679/998db406-3300-4701-a517-6ff171242b78)

#### Project File (.3MF) where problem occurs
[KT-Muffe_DN150-20_Grad_mit_50_Schlauchanschluss_teilbar v18.zip](https://github.com/supermerill/SuperSlicer/files/11778155/KT-Muffe_DN150-20_Grad_mit_50_Schlauchanschluss_teilbar.v18.zip)

**Comment by Arakon** [comment]
Your model isn't 90° flat on that side. It's at a slight angle.
Using 2.5.59.2, after "place on face", it looks fine.
![image](https://github.com/supermerill/SuperSlicer/assets/12016360/a621e1c1-e56e-4b47-9184-d25788332e8c)

**Comment by hansratzinger** [comment]
The same bug appears in PursaSlicer.
https://github.com/prusa3d/PrusaSlicer/issues/10831

**Comment by hansratzinger** [comment]
Many thanks @Arakon . I used F (Place on face) but did not know to klick afterwards at the bottom. Now it is working!
Same issue in https://github.com/prusa3d/PrusaSlicer/issues/10831#issuecomment-1595693686
