### ISSUE TITLE
Can not install in OSX

### ISSUE THREAD

**Issue by AnakinSpain** [supermerill/SuperSlicer#3877]
### What happened?

trying to install

### Project file & How to reproduce

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               SuperSlicer [77496]
Path:                  /Volumes/VOLUME/*/SuperSlicer.app/Contents/MacOS/SuperSlicer
Identifier:            com.merill.slic3r/
Version:               SuperSlicer SuperSlicer_2.4.58.5_2022-09-23 (SuperSlicer_2.4.58.5_2022-09-23)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-06-19 21:07:02.3552 +0200
OS Version:            macOS 13.4 (22F66)
Report Version:        12
Anonymous UUID:        8FA44F8E-4E22-0588-01C4-F260FB6CFC76

Sleep/Wake UUID:       9E3D3296-81FF-4687-8D76-D6320D6ED7A4

Time Awake Since Boot: 1200000 seconds
Time Since Wake:       1928 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/zstd/lib/libzstd.1.dylib
Referenced from: <EA3F7209-F390-3268-9C90-D8081DCEDC30> /Volumes/VOLUME/*/SuperSlicer.app/Contents/MacOS/SuperSlicer
Reason: tried: '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x1074539a8 ???
1   <translation info unavailable>	       0x1074d5954 ???
2   dyld                          	       0x203deffd7 abort_with_payload_wrapper_internal + 82
3   dyld                          	       0x203df0009 abort_with_payload + 9
4   dyld                          	       0x203d748f0 dyld4::halt(char const*) + 375
5   dyld                          	       0x203d71b71 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4526
6   dyld                          	       0x203d703bd start + 1805

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffc0f694 0x7ff7ffc0b000 + 18068

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x0000000308658870   x3: 0x00000000000000d8
    x4: 0x0000000308658470   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000002080d85d88
    x8: 0x0000000308658470   x9: 0x0000000000000000  x10: 0x00000000000000d8  x11: 0x0000000308658470
   x12: 0x00000000000000d8  x13: 0x0000000308658870  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010f4b8b80  x19: 0x0000000107449000
   x20: 0x00000000000007ff  x21: 0x000000010f4bdfa0  x22: 0xffffffffffffffff  x23: 0x000000010745397c
   x24: 0x0000000203deffd7  x25: 0x0000000107453248  x26: 0x00000001074d3ba8  x27: 0x0000000000000000
   x28: 0x0000000203dd5c42   fp: 0x000000002c000000   lr: 0x00000001074d5954
    sp: 0x000000010f4b8b80   pc: 0x00000001074539a8 cpsr: 0x80001000
   far: 0x0000000203deff85  esr: 0x56000080  Address size fault

Binary Images:
       0x203d6a000 -        0x203e05fff dyld (*) <9e98a840-a3ac-31c1-ab97-829af9bd6864> /usr/lib/dyld
    0x7ff7ffc0b000 -     0x7ff7ffc3afff runtime (*) <c4d322c3-30c5-3c52-adb8-2fd12ec92bc0> /usr/libexec/rosetta/runtime
       0x10f453000 -        0x10f4a6fff libRosettaRuntime (*) <c8f25cdc-b334-3f67-bc30-50e9852f8da2> /Library/Apple/*/libRosettaRuntime
       0x1007f0000 -        0x1028c3fff com.merill.slic3r/ (SuperSlicer SuperSlicer_2.4.58.5_2022-09-23) <ea3f7209-f390-3268-9c90-d8081dcedc30> /Volumes/VOLUME/*/SuperSlicer.app/Contents/MacOS/SuperSlicer
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=49.7M resident=0K(0%) swapped_out_or_unallocated=49.7M(100%)
Writable regions: Total=157.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=157.4M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    916K      226 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       15.9M        7 
VM_ALLOCATE (reserved)              44K        1         reserved VM address space (unallocated)
__DATA                            1904K        6 
__DATA_CONST                        32K        1 
__DATA_DIRTY                        16K        1 
__LINKEDIT                        15.8M        8 
__TEXT                            34.0M        4 
dyld private memory                260K        2 
mapped file                        6.9G       34 
===========                     =======  ======= 
TOTAL                              7.2G      300 
TOTAL, minus reserved VM space     7.2G      300 

-----------
Full Report
-----------

{"app_name":"SuperSlicer","timestamp":"2023-06-19 21:07:03.00 +0200","app_version":"SuperSlicer SuperSlicer_2.4.58.5_2022-09-23","slice_uuid":"ea3f7209-f390-3268-9c90-d8081dcedc30","build_version":"SuperSlicer_2.4.58.5_2022-09-23","platform":1,"bundleID":"com.merill.slic3r\/","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4 (22F66)","roots_installed":0,"name":"SuperSlicer","incident_id":"355AD0D8-3604-497F-9A17-98571B4F7E77"}
{
  "uptime" : 1200000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac21,2",
  "coalitionID" : 63996,
  "osVersion" : {
    "train" : "macOS 13.4",
    "build" : "22F66",
    "releaseType" : "User"
  },
  "captureTime" : "2023-06-19 21:07:02.3552 +0200",
  "incident" : "355AD0D8-3604-497F-9A17-98571B4F7E77",
  "pid" : 77496,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-06-19 21:06:58.2629 +0200",
  "procStartAbsTime" : 30549960480197,
  "procExitAbsTime" : 30550057617350,
  "procName" : "SuperSlicer",
  "procPath" : "\/Volumes\/VOLUME\/*\/SuperSlicer.app\/Contents\/MacOS\/SuperSlicer",
  "bundleInfo" : {"CFBundleShortVersionString":"SuperSlicer SuperSlicer_2.4.58.5_2022-09-23","CFBundleVersion":"SuperSlicer_2.4.58.5_2022-09-23","CFBundleIdentifier":"com.merill.slic3r\/"},
  "storeInfo" : {"deviceIdentifierForVendor":"127CB4D2-C478-5CCD-BE8D-4A0D9915063B","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.merill.slic3r\/",
  "crashReporterKey" : "8FA44F8E-4E22-0588-01C4-F260FB6CFC76",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 1928,
  "sleepWakeUUID" : "9E3D3296-81FF-4687-8D76-D6320D6ED7A4",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/usr\/local\/opt\/zstd\/lib\/libzstd.1.dylib","Referenced from: <EA3F7209-F390-3268-9C90-D8081DCEDC30> \/Volumes\/VOLUME\/*\/SuperSlicer.app\/Contents\/MacOS\/SuperSlicer","Reason: tried: '\/usr\/local\/opt\/zstd\/lib\/libzstd.1.dylib' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/usr\/local\/opt\/zstd\/lib\/libzstd.1.dylib' (no such file), '\/usr\/local\/opt\/zstd\/lib\/libzstd.1.dylib' (no such file), '\/usr\/local\/lib\/libzstd.1.dylib' (no such file), '\/usr\/lib\/libzstd.1.dylib' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":18926766,"threadState":{"x":[{"value":6},{"value":1},{"value":13025773680},{"value":216},{"value":13025772656},{"value":0},{"value":0},{"value":139600616840},{"value":13025772656},{"value":0},{"value":216},{"value":13025772656},{"value":216},{"value":13025773680},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041406352256},{"value":4416901120},{"value":2047},{"value":4551597984},{"value":18446744073709551615},{"value":4416944508},{"value":8654880727,"symbolLocation":82,"symbol":"abort_with_payload_wrapper_internal"},{"value":4416942664},{"value":4417469352},{"value":0},{"value":8654773314,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4417476948},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4551576448},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4416944552,"matchesCrashFrame":1},"far":{"value":8654880645}},"frames":[{"imageOffset":4416944552,"region":"Rosetta Runtime Routines","symbolLocation":10664,"imageIndex":4},{"imageOffset":4417476948,"region":"<translation info unavailable>","imageIndex":4},{"imageOffset":548823,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":0},{"imageOffset":548873,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":43248,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":0},{"imageOffset":31601,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4526,"imageIndex":0},{"imageOffset":25533,"symbol":"start","symbolLocation":1805,"imageIndex":0}]},{"id":18926889,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18068,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8654331904,
    "size" : 638976,
    "uuid" : "9e98a840-a3ac-31c1-ab97-829af9bd6864",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703124467712,
    "size" : 196608,
    "uuid" : "c4d322c3-30c5-3c52-adb8-2fd12ec92bc0",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4551159808,
    "size" : 344064,
    "uuid" : "c8f25cdc-b334-3f67-bc30-50e9852f8da2",
    "path" : "\/Library\/Apple\/*\/libRosettaRuntime",
    "name" : "libRosettaRuntime"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4303290368,
    "CFBundleShortVersionString" : "SuperSlicer SuperSlicer_2.4.58.5_2022-09-23",
    "CFBundleIdentifier" : "com.merill.slic3r\/",
    "size" : 34422784,
    "uuid" : "ea3f7209-f390-3268-9c90-d8081dcedc30",
    "path" : "\/Volumes\/VOLUME\/*\/SuperSlicer.app\/Contents\/MacOS\/SuperSlicer",
    "name" : "SuperSlicer",
    "CFBundleVersion" : "SuperSlicer_2.4.58.5_2022-09-23"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 140703142526976,
  "size" : 21474836480,
  "uuid" : "9bdf650c-7fc0-3de1-bac4-8535aea9b6aa"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=49.7M resident=0K(0%) swapped_out_or_unallocated=49.7M(100%)\nWritable regions: Total=157.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=157.4M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    916K      226 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       15.9M        7 \nVM_ALLOCATE (reserved)              44K        1         reserved VM address space (unallocated)\n__DATA                            1904K        6 \n__DATA_CONST                        32K        1 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                        15.8M        8 \n__TEXT                            34.0M        4 \ndyld private memory                260K        2 \nmapped file                        6.9G       34 \n===========                     =======  ======= \nTOTAL                              7.2G      300 \nTOTAL, minus reserved VM space     7.2G      300 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "848ce30fc9c786ffa16aa2661996ca92ba7546ab",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62c73fd17cce0d1b0bcb8a02",
      "factorPackIds" : {
        "SIRI_DIALOG_ASSETS" : "645e39c59e69a025b0a37ea1"
      },
      "deploymentId" : 240000113
    },
    {
      "rolloutId" : "6297d96be2c9387df974efa4",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000013
    },
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000005
    }
  ]
}
}

Model: iMac21,2, BootROM 8422.121.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: iMac, Retina 4.5K (4480 x 2520), Main, MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Jan 12 2023 05:51:25 version 18.20.383.14.7.8.149 FWID 01-f03416d4
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: iMac, Apple Inc.
Thunderbolt Bus: iMac, Apple Inc.

### Operating system

Mac OS ventura 13.4

### Printer model

ender 3

**Comment by mtaumike** [comment]
This has been an issue for a while and you have 2 choices:
- build yourself from source and it will run
- use the Intel version and allow Rosetta2 to do things; I don't find this slow

**Comment by mtaumike** [comment]
> Use 2.5.59.0 https://github.com/supermerill/SuperSlicer/releases/tag/2.5.59.0

This release works if the user uses the Intel build as the ARM build (M-series) still fails anyway.

**Comment by AnakinSpain** [comment]
I have one  M1

**Comment by supermerill** [comment]
see supermerill/SuperSlicer#3948
arm will comme, as now there seems to be arm runner on github.
