### ISSUE TITLE
retract_length_toolchange  not applied on first layer

### ISSUE THREAD

**Issue by kakou-fr** [supermerill/SuperSlicer#389]
### Version
2.2.52

### Operating system type + version
os x

### 3D printer brand / version + firmware version (if known)
klipper

### Behavior
I set retract_length_toolchange to 2 and extra to -0.5. (my retract is 0.3)

For the first layer tool change ( 5 changes ), I have this gcode generated : 
```
M104 S190 ; set temperature
; Filament gcode
G1 E-0.30000
M73 P8 R22
G1 X98.741 Y124.287 F9000.000
G1 E0.30000 F3600.00000
G1 F2400.000
```

For the other layer, the good behaviour is generated : 
```
M104 S190 ; set temperature
; Filament gcode
G1 X123.991 Y133.967 F9000.000
G1 E1.50000 F3600.00000
G1 F4800.000
```

**Comment by supermerill** [comment]
Can i have your project file?
(I don't know all your settings like single_extruder_multi_material_priming)
