### ISSUE TITLE
Missing some retractation in single extruder MM

### ISSUE THREAD

**Issue by elpopo-eng** [supermerill/SuperSlicer#3913]
### What happened?

Some retractions are missed when moving to the next fill area, so the color is contaminated by other colors along the way.
In layer 3 is more visible
![image](https://github.com/supermerill/SuperSlicer/assets/68954733/6da5c6a0-8c5a-4032-9fe5-069e33e0e325)

### Project file & How to reproduce

[BugSusie_Milti.zip](https://github.com/supermerill/SuperSlicer/files/12261023/BugSusie_Milti.zip)

### Version

2.5.59.2

### Operating system

Windows 10

### Printer model

ERCF

**Comment by bchnrq** [comment]
Hi, i'm experiencing the same issue :(
miss some Z-hop for travels. beetween pieces.

**Comment by bchnrq** [comment]
i think i found something 
uncheck in print settings > Infill > Advanced > Only retract when crossing perimeters
