### ISSUE TITLE
Unwanted 'Top Solid Infill' halfway on the front deck slope lines part of a benchy

### ISSUE THREAD

**Issue by Blinker73** [supermerill/SuperSlicer#3917]
Hello, 

**Description:**
I am trying to find the cause for unwanted 'Top Solid Infill' on the front deck part of a benchy.
On some layers only, SS mixes "Top Solid Infill" and "Internal perimeter" lines halfway trough the width of the deck
Having this change in the middle of a line leaves a visible change on the final print

**Expected behavour:**
I would expect each visible part of the front deck layers to be sliced as a single line type (either one) throughout the width of the deck as Cura slicer does
![Cura_DeckLines](https://github.com/supermerill/SuperSlicer/assets/100171067/9ed9d9a8-c568-4038-a00a-2303c3e77958)

**Actual behavour:**
Most of the lines SS generates for this part of the model are Internal or external perimeters
But, SS has some layers that print part of a deck line as "Top Solid Infill" mixed with "Internal perimeter" lines halfway trough the width of the deck
![SS_DeckLines](https://github.com/supermerill/SuperSlicer/assets/100171067/4fbf0eec-b413-486a-ae36-16410a0a8bd9)
![SS_Layer79Example](https://github.com/supermerill/SuperSlicer/assets/100171067/062f44c8-1b56-473e-b771-ebab093718ee)

One thing I noticed is that the layers showing the problem change if I rotate the model around the Z axis
Sliced as is, I see issues at layers 77, 79 and 87
Rotated 90deg counter clockwise, i see issues at layer 79 and 94
Rotated 180deg counter clockwise, i see issues at layer 77 and 79
Rotated 270deg counter clockwise, i see issues at layer 75, 79 and 94

What could be the cause of these inconsistent choice of line types

Thanks, 

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Version 2.5.59.0
 - Voron 2.4

**Additional context**
Cura version for the compare screenshot is 4.13.1

[SaveAs.zip](https://github.com/supermerill/SuperSlicer/files/12330401/SaveAs.zip)

**Comment by legend069** [comment]
this happens from your unusual extrusion width numbers.
![image](https://github.com/supermerill/SuperSlicer/assets/40685552/60228f39-c885-4ea5-b487-a5a8ca629b05)

![image](https://github.com/supermerill/SuperSlicer/assets/40685552/c9a5efc7-e25a-466d-94bc-6490e5955573)

**Comment by Blinker73** [comment]
Thanks, 
I would have never found the cause.

Now I have to find out where i initially got those values because I don't remember changing them

**Comment by Blinker73** [comment]
Thanks,
I would have never found the cause.

Now I have to find out where i initially got those values because I don't remember changing them
