### ISSUE TITLE
SuperSlicer2.4 bed PNG loading black

### ISSUE THREAD

**Issue by Jax1er** [supermerill/SuperSlicer#3918]
Version2.4

Device name	Reinheitsgebot
Processor	AMD Ryzen 7 5700U with Radeon Graphics            1.80 GHz
Installed RAM	12.0 GB (9.85 GB usable)
Device ID	CDA427D2-B209-407A-97E4-DC34BABCB0A2
Product ID	00342-21987-91309-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points

### Behavior
In 3d view of the slicer, the PNG file for bed plate loads black

load PNG file from (https://github.com/VoronDesign/Voron-Extras/blob/main/Bed_Models/SuperSlicer/V2/V2_bed_smooth_pei.png)
go to 3d view and PNG shows for a sec then goes black.

  * _Screenshots if useful_

_Is this a new feature request?_
Related guides for writing feature requests: http://meta.stackexchange.com/a/259196 ht
![voron 2 4 bed ](https://github.com/supermerill/SuperSlicer/assets/106282829/8bac115e-423c-4a5e-955e-e4340b4feb1f)
tp://nickohrn.com/2013/09/write-great-feature-request-bug-report/

#### Project File (.3MF) where problem occurs
_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_
_You have to zip it (or rename it to .zip) to be able to drag& drop it here_
![SS Testured bed](https://github.com/supermerill/SuperSlicer/assets/106282829/0c85b39c-3ad4-4090-bc06-bf9b8dcadacc)

**Comment by supermerill** [comment]
svg works but png seems broken

**Comment by supermerill** [comment]
prusaslicer 2.5 has the same problem and it's fixed in 2.7
i guess an opengl somthign taht has to be updated with newer graphics drivers.
Should be fixed after the merge.
