### ISSUE TITLE
Feature request: Gyroid infill, "don't connect only to the external perimeters"

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#393]
For the parts I'm printing it would be very convenient if the Gyroid infill had an option to not connect it only in the outer perimeter of the piece, but in the internal structures yes.
Now it is possible to enable "don't connect" but it is obviously also disconnected in any internal structures.
I'm printing wings and this option would save me a lot of weight while maintaining solidity in the internal structures.

SupserSlicer V2.2.52
Windows 10 x64
Delta printer custom build

**Comment by robustini** [comment]
"Don't connect" enabled in the first image, and disabled in the second.
You can see that the seat for a tube is wound thick, almost doubled in thickness, and that is fine, but I'd like the outer edge to remain as with "don't connect" enabled instead.

![immagine](https://user-images.githubusercontent.com/3864712/89729771-2eb7a600-da39-11ea-9652-3cd7e94543a7.png)

![immagine](https://user-images.githubusercontent.com/3864712/89729776-36774a80-da39-11ea-8534-e85a4afc5228.png)

**Comment by supermerill** [comment]
I can create a box that let you choose from:
- connect to everything (default)
- don't connect
- connect to outer shell only
- connect to holes (inner shell) only

that's that?

**Comment by robustini** [comment]
@supermerill when do you think you can make these changes?

**Comment by supermerill** [comment]
I don't need it personally, so I don't know.
If you need it quickly, you can pay me for it.

**Comment by robustini** [comment]
Thanks @supermerill!
