### ISSUE TITLE
Small (intentional) gaps are being widened

### ISSUE THREAD

**Issue by cy1der** [supermerill/SuperSlicer#3930]
**Bug description**
SS is making gaps (that were made on purpose) wider, which is unwanted for some models (e.g I am printing a protractor, and these gaps are kinda crucial?).

**Expected behavior**
The gaps stay the same.

!!>> Project File <<!!
[Protractor.3mf.zip](https://github.com/supermerill/SuperSlicer/files/12577326/Protractor.3mf.zip)

**To Reproduce**
1. Slice

**Screenshots**
![2023-09-09_13:14:31](https://github.com/supermerill/SuperSlicer/assets/67352978/f61c3e83-b577-40d3-ab57-ee0eea0108fb)
![2023-09-09_13:14:46](https://github.com/supermerill/SuperSlicer/assets/67352978/b1cac6e2-cb2d-47e1-b1e5-e5f262e6013a)

**Desktop (please complete the following information):**
 - OS: Void Linux
 - Version: 2.5.59.2
 - Printer model: Irrelevant

**Comment by Vanilla009** [comment]
Do you have an X-Y horizontal offset set? If so, that might be the cause of this issue.

**Comment by cy1der** [comment]
Where would I find that setting, is it this?
![image](https://github.com/supermerill/SuperSlicer/assets/67352978/c797fc42-8bbf-41de-a700-df27630d626c)

**Comment by supermerill** [comment]
XY compensation.
it shrink your entire object.
