### ISSUE TITLE
Errant internal perimeters going where they shouldn't.

### ISSUE THREAD

**Issue by gerthalberg** [supermerill/SuperSlicer#3935]
### What happened?

I'm having trouble with errant internal perimeters going where they shouldn't. I'm using 2.5.59.2 on Windows 11 Anyone got a fix?
<img width="567" alt="image" src="https://github.com/supermerill/SuperSlicer/assets/15729261/91074fca-06fd-4f20-8897-861d78963f3d">

### Project file & How to reproduce

[Mantis Fanduct Mount L.zip](https://github.com/supermerill/SuperSlicer/files/12600431/Mantis.Fanduct.Mount.L.zip)

### Version

2.5.59.2

### Operating system

windows 11

### Printer model

Custom - corexy - Klipper

**Comment by macchinette** [comment]
Disable arc_fitting

**Comment by Saturn49** [comment]
I'm having the same problem.  Enabling/disabling arc fitting had no effect.

**Comment by gerthalberg** [comment]
Thank's - It solved the problem for me. However I didn't disable G2/G3 arc fitting but instead I lowered the tolerance from 5 to 0.01%

**Comment by macchinette** [comment]
> I'm having the same problem. Enabling/disabling arc fitting had no effect.

I have the last night.
