### ISSUE TITLE
Preview screen "View->Feature type", "Show Feature types" selection boxes not showing selected features

### ISSUE THREAD

**Issue by JPTa** [supermerill/SuperSlicer#394]
### Version
2.2.52

### Operating system type + version
Operating System:    Windows
System Architecture: 64 bit
Windows Version:     Windows 7 (build 7601, Service Pack 1), 64-bit edition
Total RAM size [MB]: 16,901MB
OpenGL installation
GL version:   4.6.13547 Compatibility Profile Context 0
Vendor:       ATI Technologies Inc.
Renderer:     AMD Radeon R7 M265 Series
GLSL version: 4.60
(I cut out the rest as it is quite likely irrelevant to fix this)

### 3D printer brand / version + firmware version (if known)
Irrelevant.

### Behavior
* Tried to see gap fills but it showed top fill, selecting only "Skirt" shows gap fills.
* Slice any model with gaps to fill, or more features as they seem to be indexed wrong.

![image](https://user-images.githubusercontent.com/42002897/89731707-d214b500-da51-11ea-8fa9-efdf21efed82.png)

Note: This does not happen with PrusaSlicer 2.2.0.

#### Project File (.3MF) where problem occurs
[Washer.zip](https://github.com/supermerill/SuperSlicer/files/5047457/Washer.zip)

**Comment by supermerill** [comment]
there is now "thin wall" before gap fill, forgot to add it so all other below are desync
