### ISSUE TITLE
Roundness margin tooltip

### ISSUE THREAD

**Issue by tocguy** [supermerill/SuperSlicer#3941]
### Version
2.4.58.5

### Operating system type + version
Win10 21H2

### Behavior
Not a behavioral issue. Rather, a grammatical one. The tooltip associated with "Roundness margin" should be corrected as follows.

1. "Maximum defection (missing an "l"; replace with deflection) of a point to the estimated radius of the circle."
2. "This setting allows you some leway (missing an "e"; replace with leeway) to broaden the detection."

_Is this a new feature request?_
No

#### Project File (.3MF) where problem occurs
N/A

**Comment by supermerill** [comment]
thanks fixed
