### ISSUE TITLE
Spoolman ID integration 

### ISSUE THREAD

**Issue by mlee12382** [supermerill/SuperSlicer#3945]
I would love to see an additional variable added to the filament profiles for defining the Spool ID for those using Spoolman: (https://github.com/Donkie/Spoolman) .
 I currently have a filament start gcode that I pass to my START_PRINT macro which "works" but then the printer also sees that line on tool changes and obviously gives the unknown command error which could be fixed if there was an available entry in the UI for the filament profile that could be called instead, thus leaving the filament start gcode for actual gcode needs.
The highlighted section is my spool macro in case that provides some insight, I  have SPOOLMAN_ID=<value> in the filament code and then in my printer start gcode I call the filament gcode in my START_PRINT line and pass it to the printer.
![20231003_175042.jpg](https://github.com/supermerill/SuperSlicer/assets/89716126/465f5f55-e74e-4505-9fbd-3b297204e290)

Thanks for your consideration and help 🙂 

P.S. glad you're back! Looking forward to seeing what you have planned for the project!

**Comment by rufinus** [comment]
whats wrong with using SET_ACTIVE_SPOOL directly in the filament GCODE section?

**Comment by mlee12382** [comment]
> whats wrong with using SET_ACTIVE_SPOOL directly in the filament GCODE section?

Nothing if all you want to do is something super basic. For my ERCF system I have set it up to check the filament assigned in the slicer against the spools that are actually loaded in the ERCF and if they don't match it pauses and prompts for user interaction. 
Currently the only way to pass the spool ID is through the filament gcode which means that it's also inserted in the normal filament gcode entries for the sliced file. If there was a field that you could call in macros it would be a lot cleaner and wouldn't result, in my case, in SPOOLMAN_ID=<id> not recognized when the filament gcode runs. 
As far as I can tell there's no other way to pass custom filament specific data other than using the filament gcode field.  In the slicer start gcode I have SPOOLMAN_ID=[start_filament_gcode] as part of my PRINT_START line.

Here's some excerpts from my PRINT_START macro:
{% set SPOOLMAN_ID = params.SPOOLMAN_ID|default(None) %}
  {% set TOOL = params.TOOL|default(None) %}
  {% set tool_to_gate = {
    'T0': 0,
    'T1': 1,
    'T2': 2,
    'T3': 3,
    'T4': 4,
    'T5': 5
  } %}
    {% if TOOL in tool_to_gate %}
    {% set index_to_check = tool_to_gate[TOOL] %}
    {% if mmu_state_gate_spool_id|length > index_to_check %}
        {% set value_to_check = mmu_state_gate_spool_id[index_to_check] %}
        # Now, you can use the 'value_to_check' in your logic
        {% if value_to_check != SPOOLMAN_ID %}
            {action_respond_info("Please Check Spools Against Current Print")}
            cancel_print
        {% endif %}
    {% endif %}
    {TOOL}
  {% endif %}
  
  And then for my Tool change gcode I pass the ID there also and use the following macro formatting:
  [gcode_macro T0]
description: Tool change macro
  useage: T0 [SPOOLMAN_ID=<id>]
gcode: 
    {% set SPOOLMAN_ID = params.SPOOLMAN_ID|default(None) %}
    {% if SPOOLMAN_ID != None %}
      {% set index_to_check = 0 %}
      {% if mmu_state_gate_spool_id|length > index_to_check %}
          {% set value_to_check = mmu_state_gate_spool_id[index_to_check] %}
          {% if value_to_check != SPOOLMAN_ID %}
              {action_respond_info("Please Check Spools Against Current Print")}
              PAUSE
          {% endif %}
      {% endif %}
    {% endif %}
    MMU_CHANGE_TOOL TOOL=0

**Comment by rufinus** [comment]
maybe i miss something or straight dont understand you correctly.

You want to match your spools in the ERCF with the given spool from the slicer. How does your macro know which spools are loaded in the first place?

But besides that - your macro needs to know which spool id its gonna use. As long as we cant get the current active spool from moonraker ( see https://github.com/Arksine/moonraker/issues/702 ) you may use the filament gcode and set your variable to the spool_id
like:
SET_GCODE_VARIABLE MACRO=my_ercf_makro VARIABLE=spoolman_id VALUE=123

This would only be then a problem if you use something like continous spools and have multiple instances of the same spool in the ercf - when using the same filament profile.

**Comment by mlee12382** [comment]
> maybe i miss something or straight dont understand you correctly.
> 
> You want to match your spools in the ERCF with the given spool from the slicer. How does your macro know which spools are loaded in the first place?

Happy Hare has a variable with a string of values that identifies which spools are loaded in each channel. My macro can check the slicer assigned spool against the spools assigned in the printer. That's no problem and works the way I have it set up.

My goal with this feature request is to get better way to pass the spool ID variable to the printer without needing to use the filament specific gcode section. By using the gcode section I get unknown command errors, which don't really affect the print but are annoying to dismiss on KlipperScreen and have in my console and logs.

**Comment by supermerill** [comment]
you can add a variable for your filament in the `notes` tab
here an exemple:
[3945_exemple_spoolman_id.zip](https://github.com/supermerill/SuperSlicer/files/13418853/3945_exemple_spoolman_id.zip)
I added `spooman_id=42` in filament->notes->custom variables
I added `{default_int(spoolman_id, 0)}` at the beginning of the custom_start_gcode (needed to avoid it being undefined)
I can then call it like a normal variable, and also the exist() (look at the custom_start_gcode )
the available functions are at the bottom of https://github.com/supermerill/SuperSlicer/wiki/Macro-&-Variable-list (for other default types)

If you have multiple extruder, you can use `{spoolman[0]} and {spoolman[1]}` to have the spoolman id of the first and the second.
the exist will return true if at least one filament has a spoolman id.
the filaments that won't have one will return the default value (see above), so you can identify them with a comparison (`{if spoolman_id==0}`)

**Comment by supermerill** [comment]
> no sparse layers

Can you link me the issue?

**Comment by mlee12382** [comment]
> > no sparse layers
> 
> Can you link me the issue?

https://github.com/supermerill/SuperSlicer/issues/3768

It also seems to be hit or miss on if the first layer of the purge block goes to the bed or not.
