### ISSUE TITLE
Klipper test connection fail (ss trying connection to octoprint?)

### ISSUE THREAD

**Issue by sedovserge** [supermerill/SuperSlicer#3962]
### What happened?

If printer works on Klipper and choose klipper.

SS try to connect to octoprint when klipper choose and test connection is fail.
This bug issued in clean run (without settings):
![изображение](https://github.com/supermerill/SuperSlicer/assets/6526798/f030e975-a4db-44b5-844b-8d5fa400804f)

Meanwhile in version 2.4.58.5 test connection is ok:
![изображение](https://github.com/supermerill/SuperSlicer/assets/6526798/c909351f-37dc-4ea3-b1a2-50cad5e23cf3)

### Project file & How to reproduce

Printer settings > Add phisical printer > set klipper connection > press test

### Version

2.5.59.2

### Operating system

windows 10

### Printer model

Custom

**Comment by supermerill** [comment]
Can you verify that if you check the `enable 2-way ssl`, there is nothing in the `client certificate file`.
That's mostly the only change between the two, and a possible gui malfunction.

**Comment by sedovserge** [comment]
> Can you verify that if you check the `enable 2-way ssl`, there is nothing in the `client certificate file`. That's mostly the only change between the two, and a possible gui malfunction.

The same problem
![изображение](https://github.com/supermerill/SuperSlicer/assets/6526798/4f852844-48aa-4ad7-aabc-ae41a1e5ca11)

**Comment by DaTTcz** [comment]
When I tested it, I got this: 
Nelze se připojit k Klipper: Timeout was reached:
Connection timed out after 10003 milliseconds
[Error 28]

**Comment by sedovserge** [comment]
v2.5.59.3 Resolved! Tnx
