### ISSUE TITLE
No option to change the overhang fan speed

### ISSUE THREAD

**Issue by Pavulon87** [supermerill/SuperSlicer#3963]
### What happened?

After 083655475a3a1c9dfb11638778bfc9b12bc92333 , the "Overhang perimeter fan speed" option is missing in filament.ui file.
At this moment Overhang Perimeter use default fan speed.

### Project file & How to reproduce

Go to Filament Setting -> Cooling -> [missing] Overhang perimeter fan speed

### Version

overhang_perimeter_fan_speed

### Operating system

Windows 11

**Comment by supermerill** [comment]
was fixed the 17th
