### ISSUE TITLE
Toolpath outside print area

### ISSUE THREAD

**Issue by Calcousin55** [supermerill/SuperSlicer#3969]
### What happened?

After slicing there can be seen a toolpath outside print area was detected in gcode preview.
![image](https://github.com/supermerill/SuperSlicer/assets/3459898/4f8c3185-35a0-4bd0-aeb4-a15eae7c353f)

### Project file & How to reproduce

[idler_bearing_cover.zip](https://github.com/supermerill/SuperSlicer/files/13465105/idler_bearing_cover.zip)
Using the default Voron V2 300mm3 0.4mm nozzle profile with 0.10mm layer height
Using the following settings causes toolpath error
Skirt & Brim -> Draft shield -> Enable
Infill -> Sparse -> 40% Cubic

### Version

2.5.59.3

### Operating system

Windows 10

### Printer model

Voron V2

**Comment by supermerill** [comment]
It's because if you use complete_objects and brim_per_object, the brim needs to be shifted. But it shouldn't if no complete_objects.

**Comment by Calcousin55** [comment]
acorreya's issue looks to be fixed in 2.5.59.4 but my issue still persists in 2.5.59.4 but looks like its fixed in 2.5.59.5
