### ISSUE TITLE
Crash when adding custom printer as printer or second printer

### ISSUE THREAD

**Issue by j1and1** [supermerill/SuperSlicer#3977]
### What happened?

When I run `SuperSlicer-ubuntu_18.04-gtk2-2.5.59.3` and I try to add my old printer the slicer crashes after config wizard finishes.

### Project file & How to reproduce

To reproduce this:
1. Open up the Add printer dialog
2. Select `Custom Printer`
3. Check `Define a custom printer`
4. Click Finish (you can also go through the whole setup process, nut it always crashes when clicking finish)
5. observe crash

if the config contains other printer like Creality Ender 3 the printer configs are dropped after crash

### Version

2.5.59.3

### Operating system

Pop!_OS 22.04 LTS (64 bit)

### Printer model

Custom bedslinger with Marlin 2 firmware

**Comment by nedavime** [comment]
I can confirm this. I tried to define a custom printer using Reprap Firmware gcode flavor, the bed size is 500x500, everything else default. it crashes with the messages attached as screenshots.
![Screenshot 2023-11-28 181023](https://github.com/supermerill/SuperSlicer/assets/56366031/f459208f-1c0c-4787-879e-cfc56783b4d8)
![Screenshot 2023-11-28 181003](https://github.com/supermerill/SuperSlicer/assets/56366031/44a9141d-e889-42f4-84b8-89c24cbc9826)

**Comment by j1and1** [comment]
Looks like it's fixed now. Thanks!
