### ISSUE TITLE
Artefacts. Perimeter lines in between the part.

### ISSUE THREAD

**Issue by mypaxa00** [supermerill/SuperSlicer#3980]
### Version
2.5.59

### Operating system type + version
Windows 10 Enterprise 22H2

### Behavior
I have wierd artifacts after slicing with my model
Actual Results:
![superslicer_KnmTzNtVjK](https://github.com/supermerill/SuperSlicer/assets/36297589/2dcca324-1d6e-4589-85d3-869e074796b7)
![superslicer_GTV78ouhiP](https://github.com/supermerill/SuperSlicer/assets/36297589/17456cc8-b3cb-4c6c-8a69-a94ac57f6042)

#### Project File (.3MF) where problem occurs
[Battery_Pack_Cap_No_Supports.zip](https://github.com/supermerill/SuperSlicer/files/13513868/Battery_Pack_Cap_No_Supports.zip)

**Comment by Murrdo** [comment]
+1 
![image](https://github.com/supermerill/SuperSlicer/assets/146051709/5268a5ac-8b26-4959-b947-a31d0231b3cc)

**Comment by drone777** [comment]
Got such artefacts many times too.
+1

**Comment by neophyl** [comment]
Its basically this one https://github.com/supermerill/SuperSlicer/issues/3785

**Comment by Alohacajun** [comment]
As described in [this ](https://github.com/supermerill/SuperSlicer/issues/3785#issuecomment-1556030404)response of #3785 it is related to overhang generation. Unchecking overhangs completely fixes the issue in your model. If you still need overhang generation, a temporary fix is to reduce the "Bridge speed & fan threshold".

**Comment by mypaxa00** [comment]
Duplicate
https://github.com/supermerill/SuperSlicer/issues/3785
