### ISSUE TITLE
Superslicer exits with error when starting

### ISSUE THREAD

**Issue by gerthalberg** [supermerill/SuperSlicer#3988]
### What happened?

Starting Superslicer results in the application stopping with an exception. copying opengl32.dll from the mesa folder to the root directory stops this behaviour and runs the program normally.
<img width="1362" alt="Skærmbillede 2023-12-04 155930" src="https://github.com/supermerill/SuperSlicer/assets/15729261/2d3d0f0b-d6cf-4295-b2c2-2abe448a64ba">

### Project file & How to reproduce

Start Superslicer without the opengl32.dll present

### Version

2.5.59.3

### Operating system

windows 11 Udgave	Windows 11 Pro Version	23H2 Installeret d.	‎14-‎12-‎2022 Operativsystemets build	22631.2715 Serienummer	PF49DQCM Visning	Windows Feature Experience Pack 1000.22677.1000.0

### Printer model

Custom - corexy - Klipper

**Comment by supermerill** [comment]
I guess i'll have to isntall windows 11

**Comment by gerthalberg** [comment]
Pls. let me know if I can help or otherwise assist. It puzzles me, that it logs, that it's unable to parse the version of the AMD driver. I'm not running any AMD devices It's an Intel CoreI9 HX and an NVIDIA RTX A2000 8Gb GPU. It's a Lenovo Thinkpad P16 with an 3840x2400 OLED display.

**Comment by supermerill** [comment]
I think it's an opengl graphic dirver issue with win11.
I guess prusa already fixed it, we'll see.

**Comment by gerthalberg** [comment]
Have just downloaded PS 2.7.1 and yes, it runs - so I'll wait until you merge down the road.
