### ISSUE TITLE
"Spiral vase" mode leaves new "Seam notch" settings active creating hole in vase perimeter

### ISSUE THREAD

**Issue by PsyonicOne** [supermerill/SuperSlicer#3997]
### What happened?

When turning on Spiral vase mode, the settings for Seam notch stay active
This creates a hole in the perimeters at every "layer"

`Seam notch for round perimeters` set to 1
![image](https://github.com/supermerill/SuperSlicer/assets/46242800/54cab294-8d00-4f19-a4ba-6c0bc0cf19fe)

`Seam notch for round perimeters` set to 0
![image](https://github.com/supermerill/SuperSlicer/assets/46242800/6f654a70-e84e-4c63-b801-452b04210cff)

Expected:
When setting `Spiral vase mode` settings for `Seam notch` get turned off

### Project file & How to reproduce

[Seam Issue in Spiral Vase Mode.zip](https://github.com/supermerill/SuperSlicer/files/13627373/Seam.Issue.in.Spiral.Vase.Mode.zip)

### Version

2.5.59.3

### Operating system

Linux Fedora 5.19.11-200.fc36.x86_64

### Printer model

Modified Ender 3 running Klipper

**Comment by supermerill** [comment]
thanks for the report.
It's an easy fix.
