### ISSUE TITLE
Too much gap fill

### ISSUE THREAD

**Issue by VMQ09** [supermerill/SuperSlicer#400]
### Problem
Too much gap fills and retracts for this, resulting in the filament being squeezed flat and stuck at extruder!

Example with PrusaSlicer 2.2.0 (same setting)
![gapfill]
(https://user-images.githubusercontent.com/64824429/89894501-5d35ac80-dc04-11ea-88c5-a7028e732349.png)

**Comment by supermerill** [comment]
?
