### ISSUE TITLE
Walls printed one layer height higher when using semi-paralell printing

### ISSUE THREAD

**Issue by Lecso11** [supermerill/SuperSlicer#4004]
### What happened?

When printing multiple part with semi paralell printing, every part except the first has the walls printed one layer height higher (in my case 0.2mm) than it should be printed.
My first layer is 0.25mm, others 0.2. First part's first layer is perfect, but the other's walls are printed on 0.45mm height, then the infill on 0.25. 
On the picture: left is first, rest are identically printed wrong.

### Project file & How to reproduce

[kampov3.zip](https://github.com/supermerill/SuperSlicer/files/13697565/kampov3.zip)
![IMG_20231217_203811](https://github.com/supermerill/SuperSlicer/assets/78912917/340a065a-4324-4723-a7f7-707431aa6da7)

### Version

2.5.59.3

### Operating system

windows 10

### Printer model

Voron 2.4 klipper

**Comment by vovodroid** [comment]
I opened project, but it's configured to be printed by layer

![image](https://github.com/supermerill/SuperSlicer/assets/8691781/8a63d57d-006e-4ef0-b3ad-29d8f316023f)

What are your settings here?

**Comment by Lecso11** [comment]
> I opened project, but it's configured to be printed by layer
> 
> ![image](https://private-user-images.githubusercontent.com/8691781/291181768-8a63d57d-006e-4ef0-b3ad-29d8f316023f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODcxNzUsIm5iZiI6MTcwMjg4Njg3NSwicGF0aCI6Ii84NjkxNzgxLzI5MTE4MTc2OC04YTYzZDU3ZC0wMDZlLTRlZjAtYjNhZC0yOWQ4ZjMxNjAyM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMDgwNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzBjZGM5NjkxZmM3NjE3OWJmOWQ5MDAzYjQyZGQ0MTc2YTlkZDU2YmViNTIwYzQwMDRlZjc4NTU2ZDA5YjMwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fB6Ehs4hbEwgEJYTrx5xG3jxZXfGbSuL0Wkqrpjj-oA)
> 
> What are your settings here?

Hi!
Weird... Here they are:
![image](https://github.com/supermerill/SuperSlicer/assets/78912917/9c484200-d437-4a96-81b5-8fc1b3330533)

**Comment by vovodroid** [comment]
> My first layer is 0.25mm
0.3 actually - 75% of 0.4 nozzle. 

> others 0.2.
You have variable layer height, so it varies.

I don't see such issue. Second layer of all parts is printed at 0.505:

![image](https://github.com/supermerill/SuperSlicer/assets/8691781/e8157e47-9df1-494e-a79d-fc24209e6d9c)

![image](https://github.com/supermerill/SuperSlicer/assets/8691781/ac588a96-03c6-4011-beb7-229f0d595332)

But actually despite putting efforts and time in this feature development, I'm now thinking that it's not necessary. I was initially thinking about stringing and printing time, but eventually stringing is not issue for me, and printing time also is almost the same. And it's better to print small objects by layer to allow better cooling.

**Comment by Lecso11** [comment]
> > My first layer is 0.25mm
> > 0.3 actually - 75% of 0.4 nozzle.
> 
> > others 0.2.
> > You have variable layer height, so it varies.
> 
> I don't see such issue. Second layer of all parts is printed at 0.505:
> 
> ![image](https://private-user-images.githubusercontent.com/8691781/291203764-e8157e47-9df1-494e-a79d-fc24209e6d9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTA3MzIsIm5iZiI6MTcwMjg5MDQzMiwicGF0aCI6Ii84NjkxNzgxLzI5MTIwMzc2NC1lODE1N2U0Ny05ZGYxLTQ5NGUtYTc5ZC1mYzI0MjA5ZTZkOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMDkwNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJkYjE1NjFkODE1MWFjMWMwOTY1NjMyZDQ5NTMxNDEzMjQ0MDAyNWY4ZDNhNjI0ZGJhMDE4OGY2ZmUzOTlhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2y30FMGdwKKfUwrWqBfFCy-zzDq39Dz50Qn6q4Hnj24)
> 
> ![image](https://private-user-images.githubusercontent.com/8691781/291203886-ac588a96-03c6-4011-beb7-229f0d595332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTA3MzIsIm5iZiI6MTcwMjg5MDQzMiwicGF0aCI6Ii84NjkxNzgxLzI5MTIwMzg4Ni1hYzU4OGE5Ni0wM2M2LTQwMTEtYmViNy0yMjlmMGQ1OTUzMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMDkwNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzFjYjgxNjY1Y2E5N2NjNzg0YzRiOWZjYjFjNzA3M2VhZmU4NTYzMzNmZDU5YjMyZjg4OWUxZjJkM2NiNGFmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XvNYr1dhcaZ0nuSQcb3FS7xx4lLmLm6upKhUQ-xglss)
> 
> But actually despite putting efforts and time in this feature development, I'm now thinking that it's not necessary. I was initially thinking about stringing and printing time, but eventually stringing is not issue for me, and printing time also is almost the same. And it's better to print small objects by layer to allow better cooling.

Not the second, the first layer's walls are printed on wrong height. But now that I thought about it, that 0.2mm higher, which results in the 0.45 might be my z-hop.
See: 
![image](https://github.com/supermerill/SuperSlicer/assets/78912917/ae9263d6-db6d-4a57-acbb-fdffb3a9c051)

Actually this part of the infill is still too high:
![image](https://github.com/supermerill/SuperSlicer/assets/78912917/e22a04bc-5ff4-47b1-ad1e-259f6fb72941)

But this is fine:
![image](https://github.com/supermerill/SuperSlicer/assets/78912917/3c246c9a-b473-499b-9c02-f5bde157f688)

What you say is partly true, but I think it is still a very useful feature. While you might have no issue with stringing, there are materials that are pretty bad. And with middle-sized parts, or where cooling is not an issue, it still makes sense to use. 
I think the feature has its use-case, I wanted this for a long time.

**Comment by vovodroid** [comment]
> I don't know what happened, but you pretty much cannot see my settings.

I downloaded SS release, but didn't run config wizard, I guess all settings should be included in project file, isn't it?

> there are materials that are pretty bad.

I've read about it. But I printed PLA, PETG, ASA, Nylon, Polycarbonate and TPU. TPU indeed is stringing. Other - nothing special.

**Comment by Lecso11** [comment]
> > I don't know what happened, but you pretty much cannot see my settings.
> 
> I downloaded SS release, but didn't run config wizard, I guess all settings should be included in project file, isn't it?
> 
> > there are materials that are pretty bad.
> 
> I've read about it. But I printed PLA, PETG, ASA, Nylon, Polycarbonate and TPU. TPU indeed is stringing. Other - nothing special.

Yes the projekt file should contain it.

Anyway, if you find the time looking into it, I would be thankful. I would like to use this feature.

**Comment by vovodroid** [comment]
> the project file should contain it.

So something strange here. I loaded you projects and all setting are default:

![image](https://github.com/supermerill/SuperSlicer/assets/8691781/69d7099e-58aa-41ac-b293-7ddaac17e34f)

**Comment by Lecso11** [comment]
> > the project file should contain it.
> 
> So something strange here. I loaded your project and all setting are default:
> 
> ![image](https://private-user-images.githubusercontent.com/8691781/291254706-69d7099e-58aa-41ac-b293-7ddaac17e34f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjE0NzUsIm5iZiI6MTcwMjkyMTE3NSwicGF0aCI6Ii84NjkxNzgxLzI5MTI1NDcwNi02OWQ3MDk5ZS01OGFhLTQxYWMtYjI5My03ZGRhYWMxN2UzNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMTczOTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM0NmQ0N2I4Yjk3MjNlNTk2MjYzMDdjN2E1OTU4ZWEwOTdlNjY0MTAzMTZiYTVhNmFjNDU1MjY2ZTE1YzZhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.41UYPYS0VIU-fb5tBxpHOBRDPKU1uljrnrw_uiRyF-w)

[kampov3forgithub.zip](https://github.com/supermerill/SuperSlicer/files/13706835/kampov3forgithub.zip)
try this one, It works for me. Loads everything.

**Comment by vovodroid** [comment]
They should be separated objects:
![image](https://github.com/supermerill/SuperSlicer/assets/8691781/fa3e2611-f541-4229-88a1-329499a09c0c)

And full config is still not loaded:
![image](https://github.com/supermerill/SuperSlicer/assets/8691781/8470d8f0-7d96-40f5-8e28-80f4f57e6a7c)

Can you try open project in fresh SS installation, better on other machine?

**Comment by supermerill** [comment]
note: i can reproduce, and can open your project on latest nightly.

**Comment by supermerill** [comment]
Fixed.
That was a quite serious one.
The bug originates from the part that remove superfluous feedrate ( `F3000`). In this case, it's a wrong check: it has to check the line to remove the whole of it if it's only a `G1 F3000`, but not if it's `G1 X1 Y2 F3000`. The check was completely insufficient.

**Comment by Lecso11** [comment]
> Fixed. That was a quite serious one. The bug originates from the part that remove superfluous feedrate ( `F3000`). In this case, it's a wrong check: it has to check the line to remove the whole of it if it's only a `G1 F3000`, but not if it's `G1 X1 Y2 F3000`. The check was completely insufficient.

Thank you!
