### ISSUE TITLE
Archwiki link on readme is broken

### ISSUE THREAD

**Issue by arlarzelere3** [supermerill/SuperSlicer#4005]
### What happened?

Currently the archwiki badge points to https://archlinux.org/packages/community/x86_64/superslicer/

Needs to be updated to https://archlinux.org/packages/extra/x86_64/superslicer/

### Project file & How to reproduce

https://archlinux.org/packages/community/x86_64/superslicer/

Link leads to a 404 error page

### Operating system

any

### Printer model

any

**Comment by supermerill** [comment]
thanks for the heads-up
should be fixed for the main page and next versions.
