### ISSUE TITLE
Seam position doesn't show up in search 

### ISSUE THREAD

**Issue by orangetruth** [supermerill/SuperSlicer#4010]
### What happened?

Seam position doesn't show up in the search under any of the terms "seam", "seam position", or even the parameter name "s_seam_position"

### Project file & How to reproduce

From 3D View tab (or any of the settings tabs), hit ctrl + f and search for any of the terms "seam", "seam position", or "s_seam_position". You won't find s_seam_position anywhere

![image](https://github.com/supermerill/SuperSlicer/assets/76987378/ccfa42e1-3802-45e6-ae68-b4c49725bf2a)
![image](https://github.com/supermerill/SuperSlicer/assets/76987378/3d2ebe22-bcec-450e-8b97-d51896366134)
![image](https://github.com/supermerill/SuperSlicer/assets/76987378/f75947a1-ec00-45ce-9f16-a812c3a5bf0c)

### Version

2.5.59.2

### Operating system

Windows 10

**Comment by 5axes** [comment]
Also in 2.5.59.3

**Comment by supermerill** [comment]
already done in the nightly, but still need a bugfix.
