### ISSUE TITLE
Nigtly 2.5.59.3 windows  crash using the "Search in Settings" function

### ISSUE THREAD

**Issue by 5axes** [supermerill/SuperSlicer#4013]
### What happened?

SueprSlicer Crash when using the "**Search in Settings**" function in the last nightlies.

![image](https://github.com/supermerill/SuperSlicer/assets/11015345/acfb0b65-695c-48ba-919c-1d552d8722be)
Version: 2.5.59.3
Build: SuperSlicer_2.5.59.3_2023-12-23

### Project file & How to reproduce

In the Print settings , Filament Settings or Printer Settings press on the Search in setting magnifying glass icon.  and SuperSlicer Crash

### Version

2.5.59.3

### Operating system

Windows 10

### Printer model

not revelent

**Comment by supermerill** [comment]
thanks for the report.
