### ISSUE TITLE
The speed does not decrease when the layer time is lower than the set one

### ISSUE THREAD

**Issue by ShohninDmitriy** [supermerill/SuperSlicer#4015]
### What happened?

The speed does not decrease when the layer time is lower than the set one
2.5.59.2
![2023-12-25_19-45-41](https://github.com/supermerill/SuperSlicer/assets/20542738/9fddb73b-9fb3-4b18-8e76-e63eee5e35a1)
2.5.59.3
![2023-12-25_19-49-22](https://github.com/supermerill/SuperSlicer/assets/20542738/35f71a6b-e42b-4a30-8a3d-f09ef7fbe4c4)
2.5.59.4
![2023-12-25_19-48-03](https://github.com/supermerill/SuperSlicer/assets/20542738/b39d5b75-5907-4154-8a2c-8f863e7775fb)
 How can this be fixed?

### Project file & How to reproduce

[1.zip](https://github.com/supermerill/SuperSlicer/files/13766837/1.zip)

### Version

2.5.59.3, 2.5.59.4

### Operating system

Windows 10

**Comment by supermerill** [comment]
thanks for the report.
There was a little bug from the cooling rework from 59.3, a wrong if.
