### ISSUE TITLE
changing 'Connection Length' infill causes crash

### ISSUE THREAD

**Issue by veehexx** [supermerill/SuperSlicer#4025]
### What happened?

SuSi crashes with: `Internal error: boost::bad_any_cast: failed conversion using boost::any_cast` when changing the Connection Length away from the default 0mm setting.

![image](https://github.com/supermerill/SuperSlicer/assets/1247183/a004f707-3ff1-406a-bfde-399267ed119b)

### Project file & How to reproduce

1. open SuSi
2. goto Print Settings > Infill. Change 'Connection Length' to 1mm.
3. SuSi crashes with error.

### Version

2.5.59.4-rc-2ad8bf0 GTK3 Appimage

**Comment by veehexx** [comment]
Same occurs in the latest current RC (commit feb5782)

**Comment by supermerill** [comment]
oh, yes, i can see why.
