### ISSUE TITLE
Gap fill threshold Min width affects gap fill flow rate

### ISSUE THREAD

**Issue by Lajbror** [supermerill/SuperSlicer#4029]
### What happened?

When I set Gap fill threshold Min width, in this case 0,3mm, it affects gap fill flow and overextrudes all gap fills.
In my opinion, it just should leave out gap fills thinner than this threshold, but **it definitely should not affect gap fill flow rate in any way.**
When set to 0, it prints flawlessly.

This is the print when Gap fill threshold Min width is to 0,3mm. Heavily overextruded gap fill.
![0,3mm](https://github.com/supermerill/SuperSlicer/assets/68657004/cd96d1cf-64ac-4ba8-84ef-d2105bcf3001)

This is the print when Gap fill threshold Min width is to 0mm. No signs of overextrusion.
![0](https://github.com/supermerill/SuperSlicer/assets/68657004/5ff8e999-5e05-419a-8aeb-81b8e849c2f1)

### Project file & How to reproduce

[Bug.zip](https://github.com/supermerill/SuperSlicer/files/13799396/Bug.zip)

### Version

2.5.59

### Operating system

Windows 11

### Printer model

Heavily modified Prusa Mini+

**Comment by supermerill** [comment]
thanks for the report.

I use the min to remove too thin areas, but sometimes in circles it's right in-between the peaks and lows and generate many very small chunks, so I also try with a 60% higher min width to check if the number of gap fills created can't be reduced a bit where a fill is spit in too many pieces. But I inverted the 100% and 160% size when reverting back (mistake).
now fixed.
