### ISSUE TITLE
crash when open filament tab (Win64)

### ISSUE THREAD

**Issue by linux-paul** [supermerill/SuperSlicer#4030]
### What happened?

All latest builds (59,4 / 59.5) crashes when open filament tab
![2023-12-31_00h17_11](https://github.com/supermerill/SuperSlicer/assets/34230387/37cad8dd-9aeb-4ab8-beb8-f84b1b13fd4c)

### Project file & How to reproduce

Open Superslicer, open filament tab, Tried deferent profiles selected from 3D View tab without result

### Version

2.5.59.4 / 5

### Operating system

Windows10

### Printer model

n.a.

**Comment by JWRu** [comment]
I get the same error on a Mac (Intel).

**Comment by linux-paul** [comment]
https://github.com/supermerill/SuperSlicer/issues/4031#issuecomment-1872865095

**Comment by supermerill** [comment]
can't reproduce, can you send me a zip of your configuration directory?

**Comment by JWRu** [comment]
[SuperSlicer.zip](https://github.com/supermerill/SuperSlicer/files/13801202/SuperSlicer.zip)
I downgraded to 2.5.59.2 in the meantime to get SuperSlicer working again.

**Comment by linux-paul** [comment]
https://github.com/supermerill/SuperSlicer/issues/4031#issuecomment-1872939256
Don't know why I place my posts to the other topic :)

**Comment by linux-paul** [comment]
> [SuperSlicer.zip](https://github.com/supermerill/SuperSlicer/files/13801202/SuperSlicer.zip) I downgraded to 2.5.59.2 in the meantime to get SuperSlicer working again.

In my case ....
    file -> export -> config bundle with printer (from current working version)
    close superslicer
    rename superlicer dir in user profile
    start superslacer latest version
    Cancle new config wizard
    import previous saved config bundle
works ....

**Comment by supermerill** [comment]
short answer: fixed for next nightly. To go to the newer version, just erase the ui_layout directory from your configuration dir.

long answer:
the ui_layout is copied from the resources to the configuration.
I made this to be able to have a "library" and to update it when a new version is shipped with the software.
But i didn't included a real version detection, to select the right one.
I doesn't matter, as everything was compatible.
But the 59.3 made a radical change: all filament now has to have an id to work.
This kind of broke the layout compatibility (I should have made it the 2.5.60...)
So now, the layout from 59.3 can't be used by previous version and vice-versa.
Fix: I won't copy the shipped layout anymore, i use the one in the resources and the ones in the  configuration if the name is different.
