### ISSUE TITLE
A tool path outside the print area was detected on latest 2.

### ISSUE THREAD

**Issue by metzenw** [supermerill/SuperSlicer#4032]
### What happened?

What is the problem?
The tool tip exits the print area after just a few layers of printing.
![toopath](https://github.com/supermerill/SuperSlicer/assets/1939968/05d79942-dd19-41f5-99b1-97172d26c93c)

What did you expect?

I expected the tooltip not to exit the print area with such a small object.

### Project file & How to reproduce

To reproduce, use the v6_Cartridge_Straight filter STL and generate gcode for a Voron 2.4 R2 350mm bed.

https://github.com/nevermore3d/Nevermore_Micro/tree/master/V6/STL

**Project file Zipped**
[v6_Cartridge_Straight.zip](https://github.com/supermerill/SuperSlicer/files/13801828/v6_Cartridge_Straight.zip)

### Version

2.5.59.5

### Operating system

Windows 11 Pro

### Printer model

Voron 2.4 R2 afterburner

**Comment by supermerill** [comment]
can you `save_as` -> zip the saved .3mf -> paste it here?
It's easier to share stl&settigns in one go

**Comment by metzenw** [comment]
I just added a header to it in the description. The two links were squashed together, so it was unclear that it was there. Cheers!

**Comment by supermerill** [comment]
thanks

**Comment by supermerill** [comment]
It's an error from the arachne algorithm.
I'll add a little hack to remove these points for now.
