### ISSUE TITLE
Fan speed does not respect default fan speed value if the value is lower then 35%.

### ISSUE THREAD

**Issue by MichalDuban** [supermerill/SuperSlicer#4035]
**Bug description**
Fan speed does not respect default fan speed value if the value is lower then 35%.

**Expected behavior**
Fan speed should respect any value provided in the default fan speed.

**To Reproduce**
1. Go to 'Filament Settings'
2. Click on 'Cooling'
3. Set 'Default fan speed' to value lower then 35%
4. Set 'Max fan speed' to value lower then 35%
5. Go to 'Platter'
6. Import some model and slice it
7. Show 'Fan speed' 
8. Displayed fan speed is 35% even if the value was set to lower value (on higher values it is working properly)

**Screenshots**
![image](https://github.com/supermerill/SuperSlicer/assets/33526296/1a68ff15-831f-49f7-be27-5cb876d4caf5)
![image](https://github.com/supermerill/SuperSlicer/assets/33526296/0c129f4a-5fbc-4640-9fb0-136855c81462)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 2.5.59.6
 - Voron 2.4

**Additional context**
It is working as expected in SS 2.5.59.3

**Comment by Nbeknel** [comment]
The variable for minimum fan speed has been moved to printer settings.
![image](https://github.com/supermerill/SuperSlicer/assets/57685377/ab8ac224-514e-4d52-803b-b35a5238e87c)

**Comment by MichalDuban** [comment]
Thanks, I missed this note. It is working as expected.
