### ISSUE TITLE
Changing full fan speed at layer causes crash 

### ISSUE THREAD

**Issue by Donpilkerton** [supermerill/SuperSlicer#4038]
### What happened?

I was trying to adjust the layer height at which the fan would run at full speed. Any value greater than 3 causes an error then a crash of the entire slicer if you hit ok on both dialog boxes. If you go back and change the value from 4 to 3  the error clears. Now this could be an issue on my end. I used super slicers last stable release and had no issues until I updated to the "Christmas" release. So if it is an issue on my end I apologize, as well as curious on how to make it work properly. Thanks! 

![super slicer 3](https://github.com/supermerill/SuperSlicer/assets/51349238/2a4cdf34-06ec-4bb9-8cc5-c757852a0bf8)
![super slicer 2](https://github.com/supermerill/SuperSlicer/assets/51349238/e0641913-e0b4-40dc-afd8-eb256c4aacf0)
![super slicer 1](https://github.com/supermerill/SuperSlicer/assets/51349238/ee9a80cb-24fe-4cb9-9c06-87c36dab4dd1)

### Project file & How to reproduce

[mammoth rapido fan mount 30x30.zip](https://github.com/supermerill/SuperSlicer/files/13811647/mammoth.rapido.fan.mount.30x30.zip)

### Printer model

Voron 2.4 with ebb36 canbus, and stealthburner with cpap cooling.

**Comment by supermerill** [comment]
I think it's the same error as #4047 as i couldn't reproduce after fixing it.
