### ISSUE TITLE
"Infill > Supporting dense layer" causes crash on second slice operation

### ISSUE THREAD

**Issue by lolwat97** [supermerill/SuperSlicer#4039]
**Bug description**
SuperSlicer crashes when slicing a complex model for second or third time (after modifications to slicing parameters. The crash seemingly occurs when using Infill > Supporting dense layer.

**Expected behavior**
No crash.

**Project File**
[crash_slice.zip](https://github.com/supermerill/SuperSlicer/files/13813279/crash_slice.zip)

**To Reproduce**
Seemingly, the crash occurs when using Infill > Supporting dense layer, not 100% sure that is the problem, but the crash does not occur when the dense layer checkbox is empty.
0. Make sure Infill > Supporting dense layer is active
1. Slice the object for the first time, it slices as expected
2. Make modifications to the slicing parameters, such as changing infill density
3. Try to slice again
4. Hangs a bit on "Infilling layers"
5. Crash:
```
superslicer: /usr/src/debug/superslicer/SuperSlicer/src/libslic3r/Fill/Fill.cpp:655: void Slic3r::Layer::make_fills(Slic3r::FillAdaptive::Octree*, Slic3r::FillAdaptive::Octree*): Assertion `dynamic_cast<ExtrusionEntityCollection*>(priority_fill->entities()[i3]) != nullptr' failed.
[1]    251520 IOT instruction (core dumped)  superslicer
```

**Screenshots**
Not applicable.

**Desktop:**
 - OS: Endeavour OS (Arch Linux kernel 6.6.8-zen1)
 - Version 2.4.58.5
 - Ender 3 Pro with several modifications

**Additional context**
No additional context.

**Comment by supermerill** [comment]
can't reproduce on windows, has to test on linux

**Comment by supermerill** [comment]
succeed to reproduce.

**Comment by supermerill** [comment]
Seems like it's just an old assert that isn't relevant anymore.
