### ISSUE TITLE
Missing perimeters when one perimeter on top is enabled with arachne.

### ISSUE THREAD

**Issue by Nbeknel** [supermerill/SuperSlicer#4041]
### What happened?

When I enable arachne, one perimeter on top and set the number of perimeters to a value larger than 2 (in my case 3) and slice a model, if a layer contains a top surface, I expect the rest of the model (that is not a top surface) to have the same number of perimeters as I have set in the profile (3), however it only has 2 perimeters.
Extra perimeter on odd is disabled.

Layer 32, z = 6.4
![image](https://github.com/supermerill/SuperSlicer/assets/57685377/72dd77f0-9b8a-4468-ac3e-02c35b4c2614)

layer 33, z=6.6
![image](https://github.com/supermerill/SuperSlicer/assets/57685377/c1c2391f-8e0b-4dc8-9e3b-34ada620f69a)

Things I have changed and the corresponding behaviour in a layer with a top surface:

- changed the number of perimeters to 4: the rest is still printed with 2 perimeters;
- changed the engine to classic: the rest is printed with the set number (3 -> 3, 4 -> 4) as is expected;
- changed the wall thickness to 1.2mm (3 * nozzle diameter): the rest is still printed with 2 perimeters;
- selected a system profile (Prusa i3 MK3S, 0.2 QUALITY) and selected arachne, 3 perimeters: the rest is still printed with 2 perimeters;
- changed the number of perimeters to 1: the rest is printed 1 perimeter as is expected;
- disabled extrusion change on odd layers: the rest is still printed with 2 perimeters.

### Project file & How to reproduce

[One_perimeter_on_top_Arachne_3dbenchy.zip](https://github.com/supermerill/SuperSlicer/files/13818024/One_perimeter_on_top_Arachne_3dbenchy.zip)

### Version

2.5.59.6

### Operating system

windows 11

### Printer model

any

**Comment by supermerill** [comment]
sorry for the delay, i missed this issue.
