### ISSUE TITLE
 Infinite freezing when trying to cut a complex model.

### ISSUE THREAD

**Issue by Murrdo** [supermerill/SuperSlicer#4062]
Version: 2.5.59.6
Build: SuperSlicer_2.5.59.6_2024-01-05
Operating System: Windows
System Architecture: 64 bit
Windows Version: Windows 10 (build 19045), 64-bit edition

When I try to cut the attached model, the process takes forever, I waited 20 minutes - nothing changes.
In PrusaSlicer this model was processed in 2 minutes.
[Endless.zip](https://github.com/supermerill/SuperSlicer/files/13855886/Endless.zip)

![image](https://github.com/supermerill/SuperSlicer/assets/146051709/a397bb3f-a03f-4ae3-9c2d-214a80839799)

**Comment by supermerill** [comment]
that's and arachne bug that is also present in PrusaSlicer 2.5
Will be fixed with the 2.7
