### ISSUE TITLE
Seam gap in filament section keep reactivating

### ISSUE THREAD

**Issue by MLiv79** [supermerill/SuperSlicer#4065]
**Bug description**
Is impossible to deactivate seam gap in filament overrides, it keeps reactivating with strange values like 17976900000000000

![image](https://github.com/supermerill/SuperSlicer/assets/70020275/7f305a37-b7a6-4a65-a12c-d35d8d3c6cd8)

**Comment by senseisimple** [comment]
same here and when unchecking, it re-checks itself but with N/A value (as expected) and doesn't disable the edit field
![Screenshot_2024-01-10_23-47-43](https://github.com/supermerill/SuperSlicer/assets/528414/30a6acc2-c6fa-41cf-a507-6856e2b73a07)
![Screenshot_2024-01-10_23-43-42](https://github.com/supermerill/SuperSlicer/assets/528414/795a5b6a-830a-40d1-bfc2-cc93934a875d)
