### ISSUE TITLE
[Feature request] Custom G-code section in Print Settings

### ISSUE THREAD

**Issue by Murrdo** [supermerill/SuperSlicer#4081]
It would be very convenient to have a custom g-code section in the Print Settings section.
It would be possible to create print profiles for frequent tests/calibrations.

**Comment by supermerill** [comment]
Add it to to print variable
then in your gcode, you can add it where you want.
in print custom variable (note tab)
```
start_gcode_print="; start gcode from print profile\nM42\nG42 S42\n; end start gcode from print profile"
```
where you want to put it in your printer custom gcode (like the start gcode)
```
{default_string(start_gcode_print,"")}{start_gcode_print}
```
if it's not present in the print setting, it will just write an empty line.
note: you need the latest nightly for this to work correctly.

Is it enough?
I think this way it's more versatile. It avoid the need a hundreds of specialized unused fields.

**Comment by Murrdo** [comment]
Thank you, this is more than enough)

**Comment by Murrdo** [comment]
I’ll leave here an example of how it works, I didn’t understand it right away.
1.
![image](https://github.com/supermerill/SuperSlicer/assets/146051709/97081180-ca46-49a3-919f-65651e643232)
2.
![image](https://github.com/supermerill/SuperSlicer/assets/146051709/1de95de8-2dfd-4996-988d-3a3e8c5f2484)
Result
![image](https://github.com/supermerill/SuperSlicer/assets/146051709/d7e9e8dd-a45b-4885-956b-04dd81a11506)
