### ISSUE TITLE
SuperSlicer Crashes when selecting a filament cooling option in version 2.5.59.6

### ISSUE THREAD

**Issue by michaelaswood1980** [supermerill/SuperSlicer#4085]
### What happened?

When trying to edit the cooling feature of a filament profile, SuperSlicer will crash giving an unexpected handling error.
[log.txt](https://github.com/supermerill/SuperSlicer/files/14022818/log.txt)
![Screenshot 2024-01-23 111951](https://github.com/supermerill/SuperSlicer/assets/80465964/f4a25d34-87e2-4844-86ae-0b88f3f5f3f3)
![Screenshot 2024-01-23 112031](https://github.com/supermerill/SuperSlicer/assets/80465964/de14b836-a6ca-4abe-9029-64e2fdabbda4)

### Project file & How to reproduce

Open SuperSlicer, navigate to the Filament tab, try selecting the cooling option and then the application will crash.
[Crash.zip](https://github.com/supermerill/SuperSlicer/files/14022930/Crash.zip)

### Version

2.5.59.6

### Operating system

Windows 11

### Printer model

RatRig VC3 - Orbiter2  - Rapido UHF

**Comment by supermerill** [comment]
same problem as the last post of #4031
