### ISSUE TITLE
Single extruder MM setup tab hidden at startup

### ISSUE THREAD

**Issue by BOAndy1985** [supermerill/SuperSlicer#4086]
In the new version, the cooling tube position cannot be adjusted.  All of the settings that go with it are missing

**Comment by legend069** [comment]
can you please elaborate more?

**Comment by BOAndy1985** [comment]
The entire menu item mmu Single extruder setup is missing

**Comment by supermerill** [comment]
are you sure you have multiple extruder and have activated the `single_extruder_multi_material` just below?

**Comment by BOAndy1985** [comment]
Very strange, I just took out the hook for the single extruder and put it back in again.  Now the menu is suddenly there for whatever reason

**Comment by BOAndy1985** [comment]
You have to chop it out and put it back in every time you finish the slicer, otherwise the menu item isn't there
