### ISSUE TITLE
Unknown scalar variable type {perimeter_generator}

### ISSUE THREAD

**Issue by veehexx** [supermerill/SuperSlicer#4096]
### What happened?

when using {perimeter_generator} in the gcode filename, it fails to export file/send to printer with the following error:

```
Failed processing of the output_filename_format template.
Parsing error at line 1: Unknown scalar variable type
{perimeter_generator}_{input_filename_base}_{print_time}_{digits(layer_height,1,2)}mm_{temperature[0]}C_{filament_type[0]}.gcode
 ^
```

issue does not occur in prusaslicer.

I've also tried some random settings to see if the problem persists. Some work (`seam_notch_inner`), but others also fail like `s_seam_position` with 'not a variable name'.

### Project file & How to reproduce

add `{perimeter_generator}` or `{s_seam_position}` to the output filename & export/send to printer.

### Version

GTK3 ubu64 nightly 2053c1b AppImage

**Comment by supermerill** [comment]
Fixed.
enum type wasn't serialized.
