### ISSUE TITLE
Support Interface missing on some overhangs

### ISSUE THREAD

**Issue by 78MC-Prime** [supermerill/SuperSlicer#4104]
### What happened?

I have noticed that after build 2.5.59.3, support interface is missing for some overhangs.  Is there a setting I am missing in versions later than 2.5.59.3 that restores the support interface for all overhangs?
![Support_2 5 59 3](https://github.com/supermerill/SuperSlicer/assets/20864194/28969d2b-6c9d-4411-aec3-5eb9ac8be3e5)
![Support_2 5 59 4-6](https://github.com/supermerill/SuperSlicer/assets/20864194/cfdc2669-94d3-4a6e-83f2-4f27aa9a480e)

### Project file & How to reproduce

Here is the STL model used to discover this issue.

[Orbiter_V2_Mount-Orbiter_Head_Mount.zip](https://github.com/supermerill/SuperSlicer/files/14152065/Orbiter_V2_Mount-Orbiter_Head_Mount.zip)

### Version

2.5.59.3 to 6

### Operating system

Windows 10

### Printer model

Tronxy X5SA Pro

**Comment by supermerill** [comment]
![image](https://github.com/supermerill/SuperSlicer/assets/6536403/e2097fcd-1697-43b2-a723-be24fb9b0d02)
can't reproduce.
can I have your project file instead of just the stl, to be able to reproduce the issue?

**Comment by 78MC-Prime** [comment]
Supermerill,
That's interesting, maybe I have the wrong build.  I just reproduced the issue in the software.
![SuperSlicer 2 5 59 3](https://github.com/supermerill/SuperSlicer/assets/20864194/f9559b1a-33c9-4705-a3f0-b64343124bd7)
![SuperSlicer 2 5 59 6](https://github.com/supermerill/SuperSlicer/assets/20864194/7b1dc935-ec8a-4de1-844e-a0e9344861f8)
[Orbiter_V2_Mount-Orbiter_Mount_Side.zip](https://github.com/supermerill/SuperSlicer/files/14195562/Orbiter_V2_Mount-Orbiter_Mount_Side.zip)

**Comment by supermerill** [comment]
can reproduce with 2..5.59.6
can't reproduce on my nightly, so seems already fixed.
seems like it's time for a new release.

**Comment by 78MC-Prime** [comment]
Is the nightly build available for me to use?  I like the support interface on your post.  Looks like it would produce a cleaner surface.

**Comment by supermerill** [comment]
in the action menu below, choose your os, then the download link is a bit below.

**Comment by 78MC-Prime** [comment]
Thank you for addressing this.
