### ISSUE TITLE
Modifiers such as speed and extrusion multiplier do not work

### ISSUE THREAD

**Issue by inovatorius** [supermerill/SuperSlicer#4108]
### What happened?

Adding a modifier such as speed or extrusion multiplier to a part doesn't apply to it.

Settings:
![image](https://github.com/supermerill/SuperSlicer/assets/122360472/735e38f4-6130-474e-9380-88a7bcd7ae6b)

Preview (speed):
![image](https://github.com/supermerill/SuperSlicer/assets/122360472/3d686d38-3659-4c48-b92e-656dd8d3434a)

Preview (extrusion multiplier):
![image](https://github.com/supermerill/SuperSlicer/assets/122360472/9bc95d7a-63d0-4110-80b9-c2789457414b)

### Project file & How to reproduce

[Flat sheet v3.zip](https://github.com/supermerill/SuperSlicer/files/14157305/Flat.sheet.v3.zip)

### Version

2.5.59.6

**Comment by supermerill** [comment]
Fixed the print_extrusion_multiplier.
Can't see any issue with external perimeter speed.

**Comment by inovatorius** [comment]
I saved the project and reopened SuperSlicer and now everything loads correctly. For whatever reason, it happens only when you start new project. I'll test the changes once they area ready, thanks a lot!
