### ISSUE TITLE
Layer time (log) become crazy

### ISSUE THREAD

**Issue by Nerobeus** [supermerill/SuperSlicer#4111]
### What happened?

The Layer Time (log) is completly wrong on last version and the layer time goal still not good.

![image](https://github.com/supermerill/SuperSlicer/assets/19369944/f003050d-cad4-40c7-8f6b-fb7424b32088)

Here the previous version to compare 

![image](https://github.com/supermerill/SuperSlicer/assets/19369944/d50a9258-f487-4968-b64e-fabffa0f3476)

### Project file & How to reproduce

[Part.zip](https://github.com/supermerill/SuperSlicer/files/14210696/Part.zip)

**Comment by legend069** [comment]
maybe related to https://github.com/supermerill/SuperSlicer/issues/3890 ?

**Comment by legend069** [comment]
your attached Zip file only contains the STL.
can you please attached the project file.

**Comment by supermerill** [comment]
not fixed in current nightly, but in the next one. It needed a little more.
