### ISSUE TITLE
Partcooling fan to 100% i.s.o. to 30% setpoint (max_fan_speed) in case layer time < fan_below_layer_time

### ISSUE THREAD

**Issue by Arthur-de-Partuur** [supermerill/SuperSlicer#4113]
### What happened?

The partcooling fan goes to 100% in stead of to the setpoint of 30% in case the layer time is below 10 seconds (fan_below_layer_time)

Setpoints:
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/b9bde68f-aaee-459f-be86-bb206c81f317)

Gcode preview fan speed:
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/86405864-bf28-4f72-848f-42c1d72d2eb0)
Gcode preview Layertime:
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/9dae5d1b-488c-4b2a-a69f-b0c3f9f963cb)

In case I set the fan_below_layer_time to 0 the fan stays at the 25% (default fan speed) 
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/8e78c467-aa05-455a-9250-a0faaf8f7d85)

Gcode preview fan speed:
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/7a013917-5277-4f06-93a0-c3e4f511e328)
Gcode preview Layertime:
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/65b444f6-dda1-4ff5-8b76-8335a55d2a4e)

I would expect that the fan goes to 30% in stead of 100%, as that is what is set at max_fan_speed

### Project file & How to reproduce

[Andrew Ellis EM-calibration cubes COARSE STEPS.zip](https://github.com/supermerill/SuperSlicer/files/14223649/Andrew.Ellis.EM-calibration.cubes.COARSE.STEPS.zip)

### Version

2.5.59.7

### Operating system

win11

### Printer model

Ratrig VCore 3.1-300

**Comment by supermerill** [comment]
You have the fan kickstart activated. That bring the fan to &00% for a short amount of time.
But it's weird that you have a full layer of full fan speed.
I have that: 
![image](https://github.com/supermerill/SuperSlicer/assets/6536403/55a24585-02e2-4b34-aae5-e2ad501c1450)
I'll check if I modified something else that may create your issue.

**Comment by Arthur-de-Partuur** [comment]
I am puzzled as well. With theoriginal .3mf file, I can reproduce the issue. If I open another project, the issue is not present.
[Andrew Ellis EM-calibration cubes MEDIUM STEPS 0860-1000.zip](https://github.com/supermerill/SuperSlicer/files/14232107/Andrew.Ellis.EM-calibration.cubes.MEDIUM.STEPS.0860-1000.zip)

**Comment by supermerill** [comment]
I tried again with a fresh 59.7, in an empty configuration, and I still can't reproduce.

**Comment by Arthur-de-Partuur** [comment]
I have loaded 2.5.59.7 with the default datadir (my regular profiles are on  non-default location, loaded with the --datadir switch)
I have opend the above .3fm and notice the problem is NOT there when fan_below_layer_time =5 or smaller. When set to  6 or higher the fan goes to 100% is.o. the max 30% max_fan_speed.

**Comment by Paradisebaker** [comment]
I noticed something similar, not based on the fan_below_layer_time, but for fan increase for overhangs.
in my case, I want the fan to give 100% for overhangs and I have specified kickstart time.
As soon as the fan goes 100%, it doesnt go back down anymore.
Could it be that the kickstart time is longer than the duration of printing the overhang and this is kind of cancelling the fan reducing signal? with Klipper and high speed printing this might occur.
I also tried the 2.5.59.7, same thing.
I am not at home right now, but I can include the 3mf if wanted.

**Comment by supermerill** [comment]
> I am not at home right now, but I can include the 3mf if wanted.

Yes.
And if somethign like that happens, can you try without any speedup/kickstart? If the output if good without, you can also include the two gcode files, as that's what I use anyway to create test for the fan mover.

**Comment by Quarterblad** [comment]
Kickstart duration of 0.2s (0.2 is just my number) with checkbox  "only on overhangs"  is causing 100% fan speed on random block of layers, even if it`s layer doesn't have any overhangs. 
![image](https://github.com/supermerill/SuperSlicer/assets/26858463/92f33d92-55ff-4e5a-be83-1965e902f463)
Same config and model sliced in 2.5.59
![image](https://github.com/supermerill/SuperSlicer/assets/26858463/beda5a25-8ca8-4cbc-a7f4-f7c96fbbf389)

When I found that if "internal bridges" is set form "1", which was in all my old contigs, to "1" it will fix the problem.

**Comment by Arthur-de-Partuur** [comment]
Changing the parameter fan_speedup_overhangs does not trigger any change with me.
fan_kickstart = 0 resolves the 100% fan-on. Setting it to 0.46shows the problem (so anything between 0 and 0.459 does not show it in my calibration-square example). Assessed Layertime for this layer is approx.10s.

However, after I restarted Superslicer due to a crash (when resizing the window it hangs,... probably a different issue :-)) the values are slighlty different:
Setting it to 0.459 shows the problem (so anything between 0 and 0.458 does not show it in my calibration-square example).

##YES Problem
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/3ee03d45-64fa-482b-a1d7-879bfb7771c4)
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/3f5d9c1a-411b-4e70-acc9-6d515da38f8f)
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/2fc2fa85-34c6-4a6c-adf8-8bc6b4fb3ea6)


##No Problem
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/287fc28d-e59e-4ea4-89a5-60887a551ffe)
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/cb29abd0-5a87-494a-8f49-9c7489144a0c)
![image](https://github.com/supermerill/SuperSlicer/assets/23432540/b2cb239f-1d34-4fca-baa8-dc17d0ff6bcf)


Hope above helps,

**Comment by supermerill** [comment]
Can I have the gcode files?

**Comment by Arthur-de-Partuur** [comment]
[problem.zip](https://github.com/supermerill/SuperSlicer/files/14249366/problem.zip)

.3mf + gcode

On a different computer and I have problems to recreate (but I managed). That's why i included 3mf

**Comment by supermerill** [comment]
I also need the gcode generated without the kickstart (so without the bug) to be able to compare them.

**Comment by supermerill** [comment]
nevermind, I sliced with your project, and the two files are the same.
I guess the problem may come from the gcode viewer, and not th gcode.

**Comment by supermerill** [comment]
I sliced your project, I can replicate the issue. thanks.

**Comment by Arthur-de-Partuur** [comment]
I changed Slowdown_below_layer_time to 0
[No problem.zip](https://github.com/supermerill/SuperSlicer/files/14249569/No.problem.zip)
