### ISSUE TITLE
Height calculation failed (gcode viewer)

### ISSUE THREAD

**Issue by vladi552** [supermerill/SuperSlicer#4116]
### What happened?

![PCB jig](https://github.com/supermerill/SuperSlicer/assets/30374390/3582702d-5c61-4850-8aa2-fa7eb6d836fe)

### Project file & How to reproduce

[PCB jig.zip](https://github.com/supermerill/SuperSlicer/files/14230721/PCB.jig.zip)

### Version

2.5.59.7

### Operating system

windows 11-64

### Printer model

TEVO Black Widow under the custom firmware

**Comment by legend069** [comment]
what is your monitors resolution/ windows scaling set to?

**Comment by vladi552** [comment]
resolution 2560*1440
windows scaling 100%
