### ISSUE TITLE
Full version of slicer in G-code file

### ISSUE THREAD

**Issue by user32rtu** [supermerill/SuperSlicer#4118]
**Is your feature request related to a problem? Please describe.**
Sometimes, when re slicing a file in a new version of the slicer, you need to know the full name of the slicer version.

**Describe the solution you'd like**
In G-code you need to specify the slicer version in the form "2.5.59.7".

**Comment by legend069** [comment]
i like this small feature, good suggestion!
currently it's missing a few numbers ``; generated by SuperSlicer 2.4 on 2024-02-08 at 11:23:41 UTC``
