### ISSUE TITLE
Vertical hole shrinking compensation works in wrong direction

### ISSUE THREAD

**Issue by kevwo90** [supermerill/SuperSlicer#4119]
### What happened?

The explanation states that the setting should usually be negative because the holes are usually too small. In my case, however, negative values make the hole smaller and positive values make the hole larger. I think this is just a typo but it does cause some confusion if you have never used the feature before.

### Project file & How to reproduce

There is no specific project file!

### Version

2.5.59

### Operating system

Debain 12

### Printer model

Sovol SV01 Pro Klipper

**Comment by supermerill** [comment]
should be already fixed in 2.5.59.7
