### ISSUE TITLE
Fatal error for old projects (befoe 2.5.59.7)

### ISSUE THREAD

**Issue by vladi552** [supermerill/SuperSlicer#4120]
### What happened?

If the old projects have been updated and loaded to 2.5.59.7 the SuperSlicer enter into broken state and generate an error when Slice cmd executed. One of this project is included for investigation. For the new projects all works OK.

### Project file & How to reproduce

[Cable clip.zip](https://github.com/supermerill/SuperSlicer/files/14232879/Cable.clip.zip)

### Version

2.5.59.7

### Operating system

windows 11-64

### Printer model

TEVO Black Widow under the custom firmware

**Comment by supermerill** [comment]
set then unset `Simulate prusa 'no thick bridge'` (`s_not_thick_bridge`)
then you'll be able to print (relaunch before)
will fix
