### ISSUE TITLE
Missing layers when printer Z-offset set to a specific values

### ISSUE THREAD

**Issue by TheLongRunSmoke** [supermerill/SuperSlicer#4124]
### What happened?

Hello. I'm running into this problem, sometimes gcode skips the entire layer. Trace this to a negative Z offset equal to an integer number of layers, such as -0.8mm for a 0.2mm layer height, -0.5mm for a 0.25mm layer height, etc. Seems to be an old problem, but I didn't find any issues related to it.
![image](https://github.com/supermerill/SuperSlicer/assets/5612507/14d0d08d-dbde-4c5f-bda2-473f7c6a6b87)

### Project file & How to reproduce

1. Add any model, for example, calibration cube. Calibration->Calibration cube.
2. Set printer Z-offset to a -<any int>*<height>.
3. Slice.

### Version

2.5.59.7

### Operating system

Win10

**Comment by supermerill** [comment]
Because of rounding, the gcode writer write `G1 Z-0` and the gcode viewer doesn't understand that.
fixed, now it will write `G1 Z0`
