### ISSUE TITLE
Error encountered when slicing files stored in a Google Drive or network folder

### ISSUE THREAD

**Issue by MrShaky** [supermerill/SuperSlicer#4129]
### Version
2.5.59.7

### Operating system type + version
Windows 11 23H2 build 22631.3007

### Behavior
The following error generated when clicking Slice now on any object/project:
![image](https://github.com/supermerill/SuperSlicer/assets/104584849/2b9241f5-9785-477a-b663-9e9f51774ef5)

Same error if run as admin
-download folder is on a mapped network drive, windows server 2019
-no issue with last (January) build

#### Project File (.3MF) where problem occurs
[klickyNG_parts.zip](https://github.com/supermerill/SuperSlicer/files/14284526/klickyNG_parts.zip)

**Comment by supermerill** [comment]
can reproduce with 2.5.59.7 but not with 2.5.59.8 that was just published.
I guess already fixed?
