### ISSUE TITLE
Incorrect display in g-code preview

### ISSUE THREAD

**Issue by Den2016** [supermerill/SuperSlicer#4132]
### What happened?

The line number in the scroll below and the line number in the g-code preview seem to match, but the g-code is not what I currently have selected

![image](https://github.com/supermerill/SuperSlicer/assets/17118034/b0497287-8c0e-4312-b08b-801a7996a131)

But if I load this file into superslicer-gcodeviewer - everything is fine there 

![image](https://github.com/supermerill/SuperSlicer/assets/17118034/5662bbb4-37f5-4c10-85bf-766a03a514d2)

### Project file & How to reproduce

[case v2.zip](https://github.com/supermerill/SuperSlicer/files/14295264/case.v2.zip)

### Version

2.5.59.8

### Operating system

windows 7

### Printer model

kingroon kp3s

**Comment by supermerill** [comment]
same as #4036
there is also #4121

**Comment by Den2016** [comment]
ok, close as duplicate
