### ISSUE TITLE
cutting this model and slicing it results in an error. (ordering objects by Y)

### ISSUE THREAD

**Issue by OCautomotive** [supermerill/SuperSlicer#4147]
### Version
2.5.59.8

### Behavior
* _Describe the problem_
When i cut this model and then try to slice it, an error is thrown. If the model is not cut, it slices correctly.

* _Steps needed to reproduce the problem_
Cut the model and keep the bottom half. Try to slice the model.

* _Expected Results_
I expect the model to slice.

* _Actual Results_
Pop up message with error.

  * _Screenshots if useful_
  * 
![image](https://github.com/supermerill/SuperSlicer/assets/33736638/6cc59535-94fa-4c30-9e82-c9601e4b0034)

#### Project File (.3MF) where problem occurs
_*Upload a Project File* (.3MF) `Plater -> Save Project as...`_

[CarrigeV2.zip](https://github.com/supermerill/SuperSlicer/files/14378780/CarrigeV2.zip)

**Comment by supermerill** [comment]
The bug came from "Object sort" : "lowest y", use "Right panel and it should be able to slice
