### ISSUE TITLE
seam :) superslicer vs orcaslicer 

### ISSUE THREAD

**Issue by godbnc** [supermerill/SuperSlicer#4150]
### What happened?

![orca](https://github.com/supermerill/SuperSlicer/assets/64687621/07faf02a-a15f-46aa-b5ce-31e1a21a6fc3)
![superslicer](https://github.com/supermerill/SuperSlicer/assets/64687621/2e575eaa-b3e3-4492-a148-e750022b5826)

the seam is to big superslicer vs orca but i dont know why 

### Project file & How to reproduce

[cate lateral 55mm-orca.zip](https://github.com/supermerill/SuperSlicer/files/14394395/cate.lateral.55mm-orca.zip)
[cate lateral 55mmsuperslicer.zip](https://github.com/supermerill/SuperSlicer/files/14394396/cate.lateral.55mmsuperslicer.zip)

### Version

2.5.59

### Operating system

windows 10

### Printer model

voron 2.4

**Comment by supermerill** [comment]
you mean, the size of the ball to visualize where the seam is is too big?

**Comment by godbnc** [comment]
No dimension of x seam

**Comment by supermerill** [comment]
I don't understand

**Comment by confuzled-dev** [comment]
@supermerill they are saying that the white section is larger in SS than it is in OS. For instance, if the OS seem looks 1mm wide, it looks 2mm wide in SS. This may only be in slicer and not reflected in prints

**Comment by godbnc** [comment]
> @supermerillei spun că secțiunea albă este mai mare în SS decât în ​​OS. De exemplu, dacă sistemul de operare pare să aibă 1 mm lățime, în SS pare 2 mm lățime. Acest lucru poate fi doar în slicer și să nu fie reflectat în printuri

yes is true :)
