### ISSUE TITLE
Seam-Sphere does not work sometimes. 

### ISSUE THREAD

**Issue by JoduWei** [supermerill/SuperSlicer#416]
### Version
f741e280310df9b98638db684208fb429fca4bd5

### Operating system type + version
Win10 64

### Behavior
Seam Placement does not work always.

<img width="976" alt="seam_placement" src="https://user-images.githubusercontent.com/23301345/90778125-8dfc9c80-e2fc-11ea-9cc9-5309c47ba177.PNG">
<img width="985" alt="seam_placement2" src="https://user-images.githubusercontent.com/23301345/90778769-53473400-e2fd-11ea-9b2c-e1b439b4be8f.PNG">

3mf File:
[seam_placement.zip](https://github.com/supermerill/SuperSlicer/files/5103488/seam_placement.zip)

**Comment by supermerill** [comment]
I'll explain a bit more how it works

- for each object (here, you have only one)
- for each layer
- it get the sphere with the center point z-coordinates nearest of the z position of the layer. It doesn't use xy coordinates at all (and as it use the center, stretching it doesn't do anything)
- it will put the seam at the nearest point, taking only into account the xy position of the center of the sphere.

I can change the behavior.

**Comment by JoduWei** [comment]
Thanks for your reply.
I'm using plater to create these plates. There is no option to create 3fm/amf files unfortunately.
Combinig Plater and SSlicer would be great idea. :D 

> it get the sphere with the center point z-coordinates nearest of the z position of the layer. It doesn't use xy coordinates at all (and as it use the center, stretching it doesn't do anything)
Okay understood. It's only the direction. It's like Kisslicer but always visible. An improvement. :)


https://github.com/Rhoban/Plater

**Comment by JoduWei** [comment]
I thought it would work like this example. It would hide all seams perfectly. :D 
<img width="704" alt="example" src="https://user-images.githubusercontent.com/23301345/90813186-80a8d780-e327-11ea-8b21-b0f03040fe4f.PNG">

**Comment by supermerill** [comment]
I'll change it to:
 - if sphere: nearest xyz
 - if cylinder: nearest xy, if it's inside the height of the cylinder.

**Comment by JoduWei** [comment]
Great. Ty. :)
