### ISSUE TITLE
Model does not slice

### ISSUE THREAD

**Issue by kozross** [supermerill/SuperSlicer#4175]
### What happened?

When I click 'Slice now', there doesn't seem to be anything happening with this project. I don't get a progress bar, nor do I see any result from slicing no matter how long I wait. If I switch to slice view, I get an empty plate.

### Project file & How to reproduce

[does-not-slice.zip](https://github.com/supermerill/SuperSlicer/files/14505414/does-not-slice.zip)

### Version

2.5.59

### Operating system

Arch Linux

### Printer model

Anycubic Photon Mono 2

**Comment by foreachthing** [comment]
You'd need to fix your model first:
![image](https://github.com/supermerill/SuperSlicer/assets/10420187/21bf490e-a03b-478c-9e13-7e8e74c562d5)

Blender has found many, many more errors:
![image](https://github.com/supermerill/SuperSlicer/assets/10420187/aac409ef-b203-4b8f-8b54-5fbb422f3921)

If you have a clean model, try slicing again.

**Comment by kozross** [comment]
@foreachthing - I asked the model creator to do a repair, and that did indeed fix it. Thanks!
