### ISSUE TITLE
[Feature request]Add PETG to filament type list

### ISSUE THREAD

**Issue by Nesquirt** [supermerill/SuperSlicer#4198]
It would be nice to add PETG in filament list instead PET, or adding over PET.
It would fix the spoolman plugin advice "The material of the selected filament does not match the selected material in the slicer. Are you sure you want to continue?".
I tried after slicing the stl, to manually change from PET to PETG in gcode and the advice disappear
Thanks in advice mate

**Comment by sboehle** [comment]
Hmm, isn't it possible to enter it manually?
![image](https://github.com/supermerill/SuperSlicer/assets/60656814/5bfa4f62-e3c4-456e-9d83-4debf67a1ec9)

When you don't use the dropdown, but click in the field and enter "PETG" - will this be removed or corrected in any way?

**Comment by Nesquirt** [comment]
> Hmm, isn't it possible to enter it manually?
> 
> ![image](https://github.com/supermerill/SuperSlicer/assets/60656814/5bfa4f62-e3c4-456e-9d83-4debf67a1ec9)
> 
> 
> 
> When you don't use the dropdown, but click in the field and enter "PETG" - will this be removed or corrected in any way?
> 
> 

Uhm i dont think it keep the value stored in gcode,ill give a try this evening!

**Comment by anonymousaga** [comment]
The value isnt stored. When you type in a custom value, it doesnt let you save and it reverts back to the old choice.

**Comment by anonymousaga** [comment]
Something that does seem to work is going into the filament's .ini file and editing it to a custom value. For macOS the ini files are at ~/Library/Application Support/SuperSlicer/filament/

**Comment by anonymousaga** [comment]
> I can confirm that changing manually the value to PETG doesn't seem to be correctly stored, as the GCODE generated still shows "PET" instead of "PETG". This becomes a problem when using something like Spoolman to manage spools, which tries to match the `filament_type` with the inventory of filaments in it's database.

Try editing the ini files directly. For me editing the ini files directly worked.

**Comment by sboehle** [comment]
Very strange. I tried it again with the latest sc version. I entered "abcdef". It was saved in the filament preset and the generated gcode contained "abcdef" as filament_type.

**Comment by Nesquirt** [comment]
> > I can confirm that changing manually the value to PETG doesn't seem to be correctly stored, as the GCODE generated still shows "PET" instead of "PETG". This becomes a problem when using something like Spoolman to manage spools, which tries to match the `filament_type` with the inventory of filaments in it's database.
> 
> Try editing the ini files directly. For me editing the ini files directly worked.

FIXED WITH THIS COMMENT

**Comment by AlejandroRivera** [comment]
> > I can confirm that changing manually the value to PETG doesn't seem to be correctly stored, as the GCODE generated still shows "PET" instead of "PETG". This becomes a problem when using something like Spoolman to manage spools, which tries to match the `filament_type` with the inventory of filaments in it's database.
> 
> Try editing the ini files directly. For me editing the ini files directly worked.

Yes, i had done this, but every time i saved something in the filament section, the PETG type was replaced with PET :/
