### ISSUE TITLE
Why oh why am I stuck at as simple adjustment as printing speed???

### ISSUE THREAD

**Issue by CuredPrusa** [supermerill/SuperSlicer#4215]
### What happened?

In the attached example are exaggerated values just to see that nothing is changing regarding the speed. I've noticed that when I normally used percentage, when I increased default speed over certain value, the print speed doesn't increase anymore. Lower speeds and percentage splitting work fine. I'm sure I have set something wrong, I can't believe that advanced slicer as SS could have a bug at something as crucial as printing speed. Please help, this is getting quite frustrating. Thanks

### Project file & How to reproduce

Just try to increase the speed, that's all. Please tell how did you get to printing speed of 200mm/s in this project. Thanks.
[speedtest.zip](https://github.com/supermerill/SuperSlicer/files/14975902/speedtest.zip)

### Version

2.5.59.7

### Operating system

windows 10

### Printer model

FLSUN V400

**Comment by sboehle** [comment]
I think it is limited by max volumetric flow rate ...

![image](https://github.com/supermerill/SuperSlicer/assets/60656814/b6e6669f-709a-4bf3-bbe0-1e4e3800a8fe)

**Comment by CuredPrusa** [comment]
Tired and exhausted, therefore blind and confused.... 
But thankfully, there's a generous helpful community just around the corner!
