### ISSUE TITLE
Version 2.5.59.7 can not generate seams properly 

### ISSUE THREAD

**Issue by CuredPrusa** [supermerill/SuperSlicer#4217]
**Bug description**
I can not tame travel paths with seam orientation. There are many options to adjust the seam but none is delivering a uniform travel pattern as it was before. Maybe it works on simple models, but on a bit more complex, the seam travels are exiting and entering without much sense. Paint seam doesn't help.  The seams looks like it's in the back (white dots), but shuffling the start and end point of the layer line messes up the appearance of the wall surface. I don't see a logical reason why creating a layer line should be as random as it is. 

**Expected behavior**
Seam in the BACK should be seam in the back, without some wobble and catching up "better positions".  That's how Prusa has it still (2.7). Now I have to use SS 2.4.58 and drop additional settings from 2.5, because seam generator and travel algorithm just doesn't work as expected. I'm using now 2.4.58.4 and it works just fine. 

!!>> Project File <<!!
Here is the project, you can see that same project gives different seam in 2.4.58.4 compared to 2.5.59.7. Especially the travel moves. 
[test.zip](https://github.com/supermerill/SuperSlicer/files/15010070/test.zip)

**To Reproduce**
Select seam in the BACK. You can also see that using cost of angle and travel in 2.5.59.7 doesn't make significant changes. 
Changing to archane gives expected results, but that is archane not a workaround. 

**Screenshots**

![Prusa_2 7 4](https://github.com/supermerill/SuperSlicer/assets/98842248/45a74ab3-c0c2-486c-a29a-b45a427ebf6a)
![Prusa_2 7 4 (2)](https://github.com/supermerill/SuperSlicer/assets/98842248/f504aa0d-0ec5-4ca0-81e1-bbbd706c68c6)
![Prusa_2 7 4 (3)](https://github.com/supermerill/SuperSlicer/assets/98842248/b43c909a-6950-42c2-87be-f3260fb26199)
![SS_2 5 59 (3)](https://github.com/supermerill/SuperSlicer/assets/98842248/6b73fd13-ed90-4c1b-a606-4e852de561ce)
![SS_2 5 59 (2)](https://github.com/supermerill/SuperSlicer/assets/98842248/89939242-69c4-469a-b0a7-39d948126a7e)
![SS_2 5 59](https://github.com/supermerill/SuperSlicer/assets/98842248/46df4e9b-6fdd-4fe7-ab12-408e6fd03690)

**Desktop (please complete the following information):**
 - OS: W10
 - Printer model FLSUN V400

**Comment by CuredPrusa** [comment]
Here's the slicing in 2.4.58.4:
![Screenshot 2024-04-17 123129](https://github.com/supermerill/SuperSlicer/assets/98842248/522cd3dd-cc09-441f-9483-886bc26588eb)
This is what I call "seam on the back side" !

**Comment by supermerill** [comment]
I fixed it, simplifying the overhangs detection.
Not sure on exactly what prusa did here.

**Comment by CuredPrusa** [comment]
Thanks heaps!
Now let's see about that nasty M106 :)

**Comment by CuredPrusa** [comment]
II have tried the same project on 
Version: 2.5.60.0
Build: SuperSlicer_2.5.60.0_2024-05-21
Operating System: Windows
System Architecture: 64 bit
Windows Version: Windows 10 (build 19045), 64-bit edition

and unfortunately it isn't any better .

**Comment by supermerill** [comment]
on 59.10 release (an my edv branch, so should be on nightly also):
![image](https://github.com/supermerill/SuperSlicer/assets/6536403/08006a1c-257d-485a-b265-5a6e9a9853fd)

isn't what's you wanted?

**Comment by CuredPrusa** [comment]
The seam point is fine though, but travels are still messed up. 
On such thin wall entering and exiting are visible, and it's not insignificant. In 2.4 (and Prusa any version) this model is sliced with uniform travels: 
![image](https://github.com/supermerill/SuperSlicer/assets/98842248/80acb7e6-6a15-4b02-9d51-0fdfd5c1fdb6)
not so in 2.5:
![image](https://github.com/supermerill/SuperSlicer/assets/98842248/99111f6d-07c4-46b8-81b4-c6c23ad0b782)

**Comment by supermerill** [comment]
fixed for next version, that was gapfill that discarded (wrongly) their reversibility.
