### ISSUE TITLE
First layer sparse infill not stacked on open models

### ISSUE THREAD

**Issue by Flipqy777** [supermerill/SuperSlicer#4218]
### What happened?

When models are sliced in "open" mode (no top, no bottom, only perimeters and sparse infill), the first layer infill is not stacked with subsequent layers. it seems "shifted", which is not the way it's intended to be.
This issue doesn't happen on PrusaSlicer 2.7 branch using the same parameters.

### Project file & How to reproduce

How to reproduce :

1. Open any model
2. Make it "open" : no top and no bottom solid layers, only sparse infill and perimeters. Infill density/pattern doesn't matter, since the issue happens with any infill density/pattern.
3. Slice it and look at the first layer : infill is shifted with regard to subsequent layers, though all infills should be stacked correctly.

[Trigorilla to SKR3.zip](https://github.com/supermerill/SuperSlicer/files/15009308/Trigorilla.to.SKR3.zip)
![Capture d'écran 2024-04-17 115405](https://github.com/supermerill/SuperSlicer/assets/84709547/9d6d45a2-8710-47f3-8d5c-1a6c72332858)
![Capture d'écran 2024-04-17 115755](https://github.com/supermerill/SuperSlicer/assets/84709547/a6f34e5e-8f80-4755-a0cf-cd1b4fe32676)

### Version

2.5.59.8

### Operating system

Windows 11

### Printer model

Anycubic i3 Mega-S

**Comment by neophyl** [comment]
Your first layer Extrusion width and spacing is set differently so that first layer is sliced different.  With actual bottom layers configured you don't notice the effect as much but for your configuration you do.
