### ISSUE TITLE
Feature request: fixed fan speed settings for each section of the printed object

### ISSUE THREAD

**Issue by robustini** [supermerill/SuperSlicer#422]
It would be interesting to be able to set the fan speed for each individual printed section, for example:

Default fan speed: 30%
Bottom layers: 50%
Top Layers: 100%
External perimeters: 50%
Internal perimeters: 20%
Infill: 50%
Bridge: 100%
Supports: 100%

It seems to me that this is currently not possible.

**Comment by supermerill** [comment]
What is the use-case?

**Comment by robustini** [comment]
The case is precisely what is written above.
We may need to have a higher separation of fan settings, currently it is not possible to do the above.
"All other extrusions" in my opinion it is too generic for some printed object.
My two cents...

**Comment by robustini** [comment]
For example these are my settings, and I don't understand why the fan is running at 34% during the infill.
If there was a specific value for the infill it wouldn't happen.

![immagine](https://user-images.githubusercontent.com/3864712/91178746-e14c6180-e6e5-11ea-8052-5d2f145c97eb.png)

**Comment by supermerill** [comment]
> I don't understand why the fan is running at 34% during the infill.

> Attiva centola se la stampa del layer impiega meno di 60 secondi

If you read the tootip, it says that it will increase the fan speed from the base speed set below (for infill, it's the default at 1%) to the top speed set at 100% (the field just below

**Comment by robustini** [comment]
In fact the percentage modulation can be convenient, but personally I would have preferred separate settings declared, for each section.
If it is not possible to implement it no problem, mine was just an idea perhaps useful in some cases.
Thanks anyway!

**Comment by supermerill** [comment]
You can disable the percentage modulation for short layer.
