### ISSUE TITLE
arachne ...

### ISSUE THREAD

**Issue by godbnc** [supermerill/SuperSlicer#4229]
### What happened?

problem is in arachne mode classic works
![Untitled](https://github.com/supermerill/SuperSlicer/assets/64687621/f439c081-9224-45c7-878e-a5ed05067a0d)

### Project file & How to reproduce

[bujori 3 30mm 0.3.zip](https://github.com/supermerill/SuperSlicer/files/15100784/bujori.3.30mm.0.3.zip)

### Version

Version 2.5.59

### Operating system

windows 10

### Printer model

voron 2.4

**Comment by supermerill** [comment]
seems fixed in latest release
