### ISSUE TITLE
SuperSlicer G-code Viewer crashes when opening (Slic3r.dll could be faulty)

### ISSUE THREAD

**Issue by TheRaf974** [supermerill/SuperSlicer#4236]
### What happened?

When I start superslicer-gcodeviewer.exe, he'll show the loading popup then nothing
![image](https://github.com/supermerill/SuperSlicer/assets/63546335/6f4b74a7-0ebd-4e07-a8ef-56a7b1b38272)

According to Windows Error Reporting, the "Failing module name" is "Slic3r.dll"
[Report.wer.txt](https://github.com/supermerill/SuperSlicer/files/15177063/Report.wer.txt)

### Project file & How to reproduce

Double click superslicer-gcodeviewer.exe

### Version

2.5.59.9

### Operating system

windows 11

**Comment by supermerill** [comment]
thanks, a regression from the updates of frequent settings (forgot to not apply it to gcode viewer)

#4248
