### ISSUE TITLE
Infill not generated correctly when using !0.2mm layer

### ISSUE THREAD

**Issue by Tau512** [supermerill/SuperSlicer#4243]
### What happened?

using a layer heigh of something other than 0.2 results in infill not being correctly generated.

0.32:
![image](https://github.com/supermerill/SuperSlicer/assets/1247183/738e3fe6-bdf3-4594-a1a4-da5f27011a10)

0.20:
![image](https://github.com/supermerill/SuperSlicer/assets/1247183/92eea3dc-651a-467b-aee0-aba8eb10ce2c)

0.12:
![image](https://github.com/supermerill/SuperSlicer/assets/1247183/bca955e4-c9a3-4cd8-9af6-626aaa6fe045)

### Project file & How to reproduce

Affects any model i've tried. for the example i've just added a 'cube' shape. resize large enough to see infill (i used 175^3 for example)
verify infill generation with 0.2mm layer
change layer height away from 0.2mm.

### Version

2.5.59.9 Stable

**Comment by supermerill** [comment]
can't reproduce, can you post here two project file, one "good" and one "bad" ?

**Comment by Tau512** [comment]
both requests in the zip. one with 0.2(good), the other with 0.3(broken) with a default box shape. Due to my other #4242 bug, i've had to use my user profiles to generate them:
[4243project.zip](https://github.com/supermerill/SuperSlicer/files/15208240/4243project.zip)

This is on the current latest stable SuperSlicer-ubuntu_18.04-2.5.59.9.AppImage, Fedora40 KDEspin.

**Comment by Tau512** [comment]
I'm not sure if i'm jumping on this discovery too quickly but I've doing some more slicing and found that combine infill layers (`infill_every_layers`) appears to be exhibiting the same issue; 1 layer, 31% cubic infill:
![image](https://github.com/supermerill/SuperSlicer/assets/1247183/1ed76d79-393d-406a-95ec-bc63bcef8560)

Set it to 2 or 3 and it generates correctly. 
2layers:
![image](https://github.com/supermerill/SuperSlicer/assets/1247183/c3dbecfb-2d68-4bb0-839c-ba4c9e3fa26c)
3layers:
![image](https://github.com/supermerill/SuperSlicer/assets/1247183/c162e82e-c7ba-49ce-a87c-add466a90298)

**Comment by Tau512** [comment]
I've done more testing with a default box shape primative...
looks like there are 2 issues here.

Theres the issue as originally reported with different layer heights (with example project files).
Theres also the `infill_every_layers` issue where even on 0.2mm layer, it can generate incorrectly.

**Comment by Tau512** [comment]
i've tested some more on the RC ubuntu-GTK3 appimages.
issue first occurred on this commit: https://github.com/supermerill/SuperSlicer/commit/3a044453b7deec4c9d19feaab90b96b3df41773d

i understand that new versions may contain new features but when i used my profiles on the https://github.com/supermerill/SuperSlicer/commit/fb26f352922fbdf9a01c8985a1a3f09324b01602 appimage release, then i get the following notification. I assume expected, but just giving you all the info i can incase it helps:
![image](https://github.com/supermerill/SuperSlicer/assets/1247183/fa45754b-d8d1-4bfd-b800-c4d71196aec3)

**Comment by Nighthawk3D** [comment]
Also having this issue

**Comment by supermerill** [comment]
weird, can't reproduce on windows. I'll try on linux.

**Comment by justvlade** [comment]
Oh, I have similar problem under Linux Mint 21 (Ubuntu 22.04)
But I did not think about layer height thingy. I print with 0.32 layer height. And too had trouble, that not always, but on some models it for some reason slice with low % of infill, and ignores percent I choose like 25% 50% or even 100%. It slices like it is 5% or 10% selected. But I had this issue not on every model.
I will try to replicate this too and post here my information later.

**Comment by justvlade** [comment]
Ок, here are my two projects of the same model. It uses different profiles. On one profile infill is ok. But on the other infill is strangely very low percent. I could not really understand what difference is. But when I open the 'no' project (in the archive) in 2.4.58.5 version it slices infill correctly. There are two projects the 'ok' and the 'no'. Also screenshots of how they are slice.
Will gladly provide additional information or tests if needed.
[test infill v1.zip](https://github.com/supermerill/SuperSlicer/files/15339954/test.infill.v1.zip)

**Comment by n3ws** [comment]
Also having problems with infill.

**Comment by supermerill** [comment]
can reproduce with @justvlade project on latest stable.

**Comment by n3ws** [comment]
Added my project file if it helps. Stable 2.5.59 on Debian bookworm.

![screen_20240521](https://github.com/supermerill/SuperSlicer/assets/43077456/605b4ad4-3488-426c-851f-b1ddb52b87d1)
[infill_very_sparse.3mf.zip](https://github.com/supermerill/SuperSlicer/files/15394443/infill_very_sparse.3mf.zip)

**Comment by justvlade** [comment]
I will try to reproduce this on clean VirtualBox Ubuntu then, will try to create some step by step guide or something. Also will check in Windows. May be it is hardware or profile dependent.

**Comment by Nighthawk3D** [comment]
I’m on a Mac arm build. Just pulled the latest stable build down from yesterday (2.5.59.10) and it’s still doing it in that build too. If I go back a month or so in nightlies it’s fine.

**Comment by supermerill** [comment]
can reproduce on linux

**Comment by Nighthawk3D** [comment]
Checked the last 2 nightlies for Mac-arm and I see the same issue, and also not generating top/bottom layers as well if using 3d honeycomb. If I switch to Grid or Cubic it generates top and bottom layers but no infill.

![image](https://github.com/supermerill/SuperSlicer/assets/41883401/bbe07127-96fc-4c75-a1e5-1c9c57d8d4b8)

Here are the two project files.
[PR-4243.zip](https://github.com/supermerill/SuperSlicer/files/15419135/PR-4243.zip)

Let me know if grabbing any kinds of debug logging etc would be helpful in tracking this down.

**Comment by justvlade** [comment]
Oh, looks like I am too late = ) But anyway. I installed Ubuntu 24.04 with all defaults, had to install libfuse2 to run 2.5.59.10 AppImage. Chose Creality Ender 3 with 0.6 nozzle. Opened my 'no' project and here we are.

![image](https://github.com/supermerill/SuperSlicer/assets/7622616/db1e0a7f-ef24-4954-a693-419dfa564ad0)

**Comment by AlessandroEmm** [comment]
I have the same issue and same for me,  combining infill set to anything but 1 seems to fix it as well.

**Comment by supermerill** [comment]
seems like the fix from @Icenowy #4258 also fix this issue.

**Comment by justvlade** [comment]
I checked 2.5.59.11rc by this link
https://github.com/supermerill/SuperSlicer/actions/runs/9370711092
And my "no" project works as intended on both host Linux Mint system and on Virtual Box's Ubuntu 24.04.
Infill generates correctly.
