### ISSUE TITLE
Fan speedup time produces strange results

### ISSUE THREAD

**Issue by vovodroid** [supermerill/SuperSlicer#4249]
### What happened?

Fan start is moved too far in some layers:

![image](https://github.com/supermerill/SuperSlicer/assets/8691781/799211a1-7067-43c6-893c-8e61c10e9de5)

Decreasing speedup time from 0.2 to 0.1 makes it even worse:

![image](https://github.com/supermerill/SuperSlicer/assets/8691781/c57e4ea5-bf5f-47d1-a1a5-4573e2852495)

### Project file & How to reproduce

[Shape-Box-ss.zip](https://github.com/supermerill/SuperSlicer/files/15202603/Shape-Box-ss.zip)

### Version

Version 2.5.59

### Operating system

Win10x64

**Comment by legend069** [comment]
this is a tricky one to fix because of the acceleration times are assumed to be instantaneous. so any time based features will always be a bit off till that main issue for calculating time from movement speed is fixed.(ignoring any time it takes for the physical fan to speed up)

**Comment by vovodroid** [comment]
Latest code (not released yet) produces better results, so still quite strange sometimes.

**Comment by supermerill** [comment]
In this case was putting the fan at the start instead of the end.
Also increased precision for long lines.
