### ISSUE TITLE
Wipe tower starting speed as % generates incorrect speed

### ISSUE THREAD

**Issue by dpeart** [supermerill/SuperSlicer#4251]
### What happened?

When I used the defaults wipe tower speed of 80mm/s and wipe tower starting speed of 33% (should be 26.6mms/s) I got 594mm/s.
`; CP TOOLCHANGE WIPE
G1  X75.552  E3.2299 F35640`

When I changed 33% to 26.64 I got the proper value
`; CP TOOLCHANGE WIPE
G1  X75.552  E3.2299 F1598`

### Project file & How to reproduce

[First_Layer_Square_0.25.debug.zip](https://github.com/supermerill/SuperSlicer/files/15204906/First_Layer_Square_0.25.debug.zip)

### Version

2.5.59.6

### Operating system

windows 11

### Printer model

voron 2.4 with stealthburner

**Comment by supermerill** [comment]
When using a %, it was multiplied by 60 twice.
so you need to put 1.8% to get 33%

fixed in next nightly & release
