### ISSUE TITLE
Fan speed control generates invalid g-code moves randomly

### ISSUE THREAD

**Issue by shengyan** [supermerill/SuperSlicer#4254]
### What happened?

I have noticed some missing lines on external perimeter on multiple prints since I switch to 2.5.59.8, previously I use 2.3.57.12.
By checking the g-code file, I found something like `M106 S255G1 X56.624 Y28.869 E0.09313` on multiple location. It should take up two lines if it was generated correctly.

### Project file & How to reproduce

- default fan speed: 80%
- overhangs perimeter fan speed: 100%
- speedup time: 1s
- kickstart duration: 1s
- slice a large object, or the invalid line may not occur.
[bug report - invalid lines.zip](https://github.com/supermerill/SuperSlicer/files/15212717/bug.report.-.invalid.lines.zip)

### Version

2.5.59.9

**Comment by supermerill** [comment]
nice catch.
