### ISSUE TITLE
Incorrect/inconsistent info in sliced info section

### ISSUE THREAD

**Issue by Tirpitz93** [supermerill/SuperSlicer#4262]
### What happened?

Sliced info for an MMU print shows inconsistent values:

I cant make sense of the weights shown below:
Totdal 77.88g filament but the two colours only add up to 31.95+0.43=32.38 ≠77.88
I thought it was an issue with multiple copies but the same applies to the single copy
3 identical items sliced with two colours:

![image](https://github.com/supermerill/SuperSlicer/assets/6187560/2cb6a2a0-d27e-411a-8ff8-89a6defffab1)
![image](https://github.com/supermerill/SuperSlicer/assets/6187560/b11638e9-7e2f-447e-aba7-3a4ba7a8197c)

Single copy of the same item:
![image](https://github.com/supermerill/SuperSlicer/assets/6187560/2c27c2f2-5d3c-4d26-ba5f-4868fb88fb9d)
![image](https://github.com/supermerill/SuperSlicer/assets/6187560/d7fb5db5-dbcf-41bd-97a1-f57796e33ae2)

### Version

2.5.59

### Operating system

Windows 11

### Printer model

Prusa MK2.5s MMU2S

**Comment by supermerill** [comment]
volume was used instead of length at some place, thanks for the report.
