### ISSUE TITLE
Proposal: Gap fill generated in more lines

### ISSUE THREAD

**Issue by CuredPrusa** [supermerill/SuperSlicer#4266]
ver 2.5
When gap fill line gets beyond a max width, there will be no gap fill. So the space stays empty.
But I want a gap fill, just not that thick because it disturbs the nozzle pressure. 
How about gap fill goes in two lines instead of one while maintaining setpoint of min and max width? 
Similar to what archane does.

**Comment by CCS86** [comment]
I requested this here: https://github.com/supermerill/SuperSlicer/issues/4192
