### ISSUE TITLE
slowdown_below_layer_time doesn't appear in search

### ISSUE THREAD

**Issue by orangetruth** [supermerill/SuperSlicer#4267]
### What happened?

the slowdown_below_layer_time variable doesn't appear in search, nor do any of the keywords

### Project file & How to reproduce

![image](https://github.com/supermerill/SuperSlicer/assets/76987378/4115ea83-df2f-49f7-b68a-3e9674f60da5)
![image](https://github.com/supermerill/SuperSlicer/assets/76987378/0a53fc9c-cb3e-4bf6-9d23-eaab973a2f1f)
![image](https://github.com/supermerill/SuperSlicer/assets/76987378/f6a2021d-f54a-479b-925d-b8f60862fe4e)
![image](https://github.com/supermerill/SuperSlicer/assets/76987378/644f362f-fdd3-4b81-bd3d-e574731343b0)

### Version

2.5.59.8

**Comment by supermerill** [comment]
all filaments settings basically
