### ISSUE TITLE
External lines protruding from others when using archene and external line width 

### ISSUE THREAD

**Issue by GalvanicGlaze** [supermerill/SuperSlicer#4269]
### What happened?

Weird external artifacts when using archene and suggested external line width on per model bases. Was fine in 2.5.59.3 but no good in 2.5.59.9/10

I'll work around it but thought I'd share just in case 

![lines](https://github.com/supermerill/SuperSlicer/assets/79122142/9c3b742c-b127-4c51-a504-3e28d7fed906)
![20240509_232406](https://github.com/supermerill/SuperSlicer/assets/79122142/2f1c8edb-acb9-405f-bb56-ab568349a2ef)

### Project file & How to reproduce

[SB cover.zip](https://github.com/supermerill/SuperSlicer/files/15402090/SB.cover.zip)

### Version

2.5.59.10

### Operating system

Windows 10

### Printer model

Voron Trident

**Comment by supermerill** [comment]
Seems like the overhang flow is just at the threshold. just increase it a little bit, or deactivate it.
Your project has fired many assert  checks, I use my entire day to fix most of the little issues it undercover (pesky unreliable arachne generator)

**Comment by GalvanicGlaze** [comment]
> Seems like the overhang flow is just at the threshold. just increase it a little bit, or deactivate it. Your project has fired many assert checks, I use my entire day to fix most of the little issues it undercover (pesky unreliable arachne generator)

Hi, im not sure how this all works but though I would mention the problem is still currently in the latest RC and night_dev for me

**Comment by supermerill** [comment]
increase the threshold for overhang flow.

**Comment by GalvanicGlaze** [comment]
Yeah I know the work around, I thought it was something you were fixing so though it would be good to keep you updated. I changed mine to 100% permanently to work around it. Thanks
