### ISSUE TITLE
SPEED IS STRANGE.

### ISSUE THREAD

**Issue by FoldZero** [supermerill/SuperSlicer#4282]
### What happened?

![image](https://github.com/supermerill/SuperSlicer/assets/12484386/7f7da959-3070-4411-b877-a7bd485a5861)

inner perimeter is set to 100% in slicer - comes out at 300m/s on print.
MAX speed on slicer is 200.  
so 100% of max speed is 300m/s

Whats going on here?

### Project file & How to reproduce

[speedissues_czfa_flexframe_screw_NoSupport.zip](https://github.com/supermerill/SuperSlicer/files/15444052/speedissues_czfa_flexframe_screw_NoSupport.zip)

### Version

Version: 2.5.59.10

### Operating system

Win10

### Printer model

cr6 MAX

**Comment by CuredPrusa** [comment]
Max  speed (which you refer to =200mm/s) is used for auto speed function, when you set 0 at certain speed parameter.
Don't use percentage in Default speed. 
Just put there speed in mm/s at which you want to print. For example 100mm/s. From there you can set perimeter speed for example 200% =200mm/s, and other speeds accordingly.
Check another place of possible speed restriction:
filament_max_speed
filament_max_volumetric_speed

**Comment by supermerill** [comment]
as CuredPrusa said, the max speed is a max auto-speed, i'll change the label.

for your speed,  your x maximum feedrate is 300: 
![image](https://github.com/supermerill/SuperSlicer/assets/6536403/763be5be-097f-4b5d-b169-ee84de21d0b8)
and your filament max speed isn't defined, so evrything is as expected, I think

**Comment by FoldZero** [comment]
is feed rate inclusive of travel speed? I want to have a 250 300 travel speed, but dont neccesarily want to print at those speeds, for quality or flow reasons.

**Comment by supermerill** [comment]
it shouldn't
