### ISSUE TITLE
Allow "Ironing post-process" for print setting with 0 top layers

### ISSUE THREAD

**Issue by Phil1988** [supermerill/SuperSlicer#4286]
**Is your feature request related to a problem? Please describe.**
I want to print with aligned infill and then ironing in the same direction for transparent materials.
Aligned infill is possible by setting this:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/d8712bc3-b5bb-49b3-ae15-458a0cf8174e)
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/a65c403a-82f0-45a5-8245-cf95628029ec)

layer 30:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/069bfd61-c671-4c85-bff3-9e4a6c72801d)

layer 31:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/24b40447-d970-4ccf-b921-2e14c3dd423a)
So infill works good.

Problem comes when I want to iron in the same direction only.
I neet to set top layers to 0, otherwise it will add "features", see layer 31 with 1 top layer:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/1917c6c9-eb48-488e-9b6e-69c9fc3b1a08)
This will destroy transparency to a huge extend.

If I set top layers to 0, I can not activate ironing in the post-process:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/e09d0cf0-6888-4fa9-9116-ceec1cf3d1d4)

Only option then is to use "Ironing" as infill pattern:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/825e0b77-c046-4dc5-8e95-7d466cf776e2)

But then there is no option to modify the infill angle:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/7bee50ca-9761-4142-91f8-81e3db865dca)

**Describe the solution you'd like**
There are 3 possible solutions that I can think of:
1. Allow Ironing post-process to being activated even if you set 0 top layers
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/ee388e0b-a65f-4e11-942a-42d4672f768a)

2. Give the option to set the ironing angle in the "Advanced infoll options" with the option for "not alternating ironing"
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/11fa8377-230f-4be7-bf94-7da60c3bcf97)

3. Give the option for "aligned" solid infill
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/31df3654-1746-494c-8105-afcb812dbf48)

Then we all can print aligned infill with aligned ironing to create more transparent looking objects :)

**Comment by supermerill** [comment]
you can also grow your top layer so it takes the whole layer (anchor solid infill).

> see layer 31 with 1 top layer:

I don't have your project file to see in details.

> 2) Give the option to set the ironing angle in the "Advanced infill options" with the option for "not alternating ironing"

I can. It's not hard.

> 3) Give the option for "aligned" solid infill

This don't makes sense. here "aligned" is in the Z direction. I should make it clearer.

**Comment by Phil1988** [comment]
> you can also grow your top layer so it takes the whole layer (anchor solid infill).
> 
> > see layer 31 with 1 top layer:
> 
> I don't have your project file to see in details.
Yeah I thougt the screenshot would be sufficient, but you are right, a project file makes it easier :)

I hope you have an idea how this aligned (in x-y direction) ironing could be achieved in every layer!
Created with SuperSlicer_2.5.59.10_win64_240521:
 [(SuperSlicer)_Transparent.zip](https://github.com/supermerill/SuperSlicer/files/15479381/SuperSlicer._Transparent.zip)

**Comment by supermerill** [comment]
[4286_(SuperSlicer)_Transparent.zip](https://github.com/supermerill/SuperSlicer/files/15480262/4286_.SuperSlicer._Transparent.zip)

> Isn't this what I want?

by aligned in z, it means the holes of sparse extrusions are on top of each other. It doesn't do anything when it's a solid infill, as there is no hole.

**Comment by Phil1988** [comment]
How do I now make the ironing match the infill alignment?
ironing direction on eg. layer 30:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/9c4f982f-57b6-4378-8139-667fca3d1b2f)

should be as eg layer 29:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/972ba97b-7be8-488f-93f4-a5de7329e1c5)

So no alternating orientations.
Is this possible?

**Comment by supermerill** [comment]
in next nightly:
without 'Alternate Fill Angle', ironing pattern & post-process ironing won't add a 90° angle anymore.

**Comment by Phil1988** [comment]
You are a beast!
I will update and close this as soon as I tested it (if you didnt closed it by then already.
Thanks!

**Comment by Phil1988** [comment]
I dont know how to make it work :(
(see attached)
I already tested SuperSlicer_2.5.59.11_win64_240605 before and thought it was not included yet.


Setting1:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/af1fb9e8-d324-433f-8c6c-1121470c1c4d)
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/c5f88e02-169f-4179-a38f-0e3cf9f8b83f)

Setting2:
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/5cabb5ab-b670-4e70-98e8-55b21fe5d602)
![image](https://github.com/supermerill/SuperSlicer/assets/6054234/00fb1dd9-1f3b-49e1-a3bd-4a4a916f5e03)

what to activate where? :D 
[settings.zip](https://github.com/user-attachments/files/15812855/settings.zip)
