### ISSUE TITLE
Start gcode

### ISSUE THREAD

**Issue by Tinchus2009** [supermerill/SuperSlicer#4289]
**Is your feature request related to a problem? Please describe.**
When creating a custom printer, I can configure the start and end gcodes. But superslicer adds its own start gcode. If detects m109 or M104 this is not done. But in the case of reprapfirmware, these 2 commands are in process of being deprecated. So for the ones using new updated firmware this is causing problems because gcode is being inserted.
Also, the start gcode seems to nopt be adding command to heat heated chamber.
Also it introduces M107 wich is also deprecated on reprapfirmware (M106 S0 must be used now)

**Describe the solution you'd like**
Superslicer should also recognize the new commands (G10 and M141 for heated chambers too) Bed commands should be ignores because some printers with heated chambers dont use heated beds.

**Describe how it would work**
Be as descriptive as your skill level allows you.

**Describe alternatives you've considered**

**Additional context**
Add any other context or paint drawing about the feature request here.

**Comment by supermerill** [comment]
* add chamber gcode (M141, M191) automatically like for bed: In next nighlty
 * G10 detection: already done for reprap firmware.
 * Bed commands are ignored if their temperature is zero. If you printer need very specific start gcode, use `only custom start gcode` and don't forget to add `G21; G90; M82/M83`

> But in the case of reprapfirmware, these 2 commands are in process of being deprecated. So for the ones using new updated firmware this is causing problems because gcode is being inserted.

G10 are already used for reprapfirmware, what is the issue?
