### ISSUE TITLE
Infill, Advanced, Only retract when crossing perimeter - threshold too far outwards

### ISSUE THREAD

**Issue by CuredPrusa** [supermerill/SuperSlicer#4294]
Version: 2.5.60.0
Build: SuperSlicer_2.5.60.0_2024-05-21
Operating System: Windows
System Architecture: 64 bit
Windows Version: Windows 10 (build 19045), 64-bit edition

"Infill, Advanced, Only retract when crossing perimeter" - doesn't retract when travel line is on the edge.
It leaves visible lines on otherwise smooth wall surface of the model.
Workaround: I change infill density, travel line gets another exiting point, slicer recognizes "outside perimeter" and retracts.
That works, but after a wasted print which didn't pass quality check. I think slicer should retract before leaving the travel marks on the model surface for being to close to the outer perimeter. 

![image](https://github.com/supermerill/SuperSlicer/assets/98842248/8615a748-7796-413a-8b66-240bc33a34a2)
![image](https://github.com/supermerill/SuperSlicer/assets/98842248/a18e7836-c051-4d7c-b9c3-519fcb3bc9cc)

**Comment by supermerill** [comment]
can i have your project file?

**Comment by CuredPrusa** [comment]
Here it is. 
Problem is at layers 348-371
[test4.zip](https://github.com/user-attachments/files/15535784/test4.zip)
