### ISSUE TITLE
Floating Skirt (Sequential Printing, Supports)

### ISSUE THREAD

**Issue by Dobarekk** [supermerill/SuperSlicer#4300]
### What happened?

If I slice my models with sequential printing enabled and using "Supports Everywhere", it produces 2 Skirts.
One on Layer 1 as expected and one on Layer 8.
This only happens when both sequential printing and Supports everywhere is enabled.
If either of the options aren't enabled (even only support on buildplate), this doesn't happen.

### Project file & How to reproduce

- Screenshot from Bottom for better visual distinction
- Zip includes obj, mtl, 3mf files (don't know if this is the right way to export)
![Screenshot 2024-06-05 005641](https://github.com/supermerill/SuperSlicer/assets/95767183/d8ef8e76-8634-4a7a-ae9a-bd639b38fc6b)
[a.zip](https://github.com/user-attachments/files/15571238/a.zip)

### Version

2.5.59.9

### Operating system

Windows 11

### Printer model

Voron 2.4 with Afterburner (Mostly default Profile)

**Comment by supermerill** [comment]
It tried to put the skirt also on the first support layer, and when this one isn't on the bed... double skirt.
fixed.
In the meantime, you may have to use the "allow only one skirt loop" `complete_objects_one_skirt`

**Comment by Dobarekk** [comment]
Thank you very much for both the fix and the workaround.
People like you is what makes this community is so great.
I love your work, keep it up <3
