### ISSUE TITLE
Crashing and closing when slicing 

### ISSUE THREAD

**Issue by GalvanicGlaze** [supermerill/SuperSlicer#4301]
### What happened?

When selecting Gcode viewer and while slicing my file it crashes and exits

### Project file & How to reproduce

[red.zip](https://github.com/user-attachments/files/15587636/red.zip)

### Version

2.5.59.11

### Operating system

Windows 10

### Printer model

Voron Trident

**Comment by fbeauKmi** [comment]
Same issue with this project
[crash_2.59.11.3mf.zip](https://github.com/user-attachments/files/15614114/crash_2.59.11.3mf.zip)
no crash log

Crash occures generating gcode for layer 59 (last layer of the smallest object)
![image](https://github.com/supermerill/SuperSlicer/assets/88246672/0f358193-3bc3-4048-b6e1-915d6955178d)

### Version:
from 2.5.59.11 to nightly-dev (2.5.60.0)

### Operating system:
Windows 11

**Comment by Tehvan** [comment]
Same issue. 2.5.59.10 slices but 2.5.59.11 won't. This is the crash log.
[crash_log.txt](https://github.com/user-attachments/files/15710616/crash_log.txt)
And here are the files I was trying to slice.
[Shuttle_MGN12H.zip](https://github.com/user-attachments/files/15710623/Shuttle_MGN12H.zip)

**Comment by roykrikke** [comment]
I have the same issue with 2.5.59.11 on windows 10.

I'm willing to share a crash.log.txt But don't know where to get the file.

And is the files I was trying to slice. 
[LDO_LED_PCB_spacer_narrow_rev01.zip](https://github.com/user-attachments/files/15747660/LDO_LED_PCB_spacer_narrow_rev01.zip)

**Comment by OldCurmudgeon3DP** [comment]
Similar issue, but crashes/closes while slicing if I select "No" when the "Mutli-part object detected" dialog appears.
2.5.59.11 and alpha 728 for windows.

**Comment by roykrikke** [comment]
> I have the same issue with 2.5.59.11 on windows 10. With version 2.5.59.9 slicing is working without the crash.
> 
> I'm willing to share a crash.log.txt But don't know where to get the file.
> 
> And is the files I was trying to slice. Crash @ layer 21. [LDO_LED_PCB_spacer_narrow_rev01.zip](https://github.com/user-attachments/files/15747660/LDO_LED_PCB_spacer_narrow_rev01.zip)

I did some more testing with regardig this issue with 2.5.59.11 on windows 10. 

If I merge all the parts in my shared file, there is no crash. I wonder if others can test this also and share there results.

**Comment by fbeauKmi** [comment]
> 
> I did some more testing with regardig this issue with 2.5.59.11 on windows 10.
> 
> If I merge all the parts in my shared file, there is no crash. I wonder if others can test this also and share there results.
Done with my project , it doesn't crash when merged too, thanks.

**Comment by jaminmc** [comment]
Downloaded the nightly build from the actions section, and it fixed my problem of slicing. If I had more than one .stl, it would crash when slicing, Now it works great! :)

I am using MacOS, arm version.
