### ISSUE TITLE
Heads up - unresponsive iron angle manipulation in 2.5 Nightly 240605

### ISSUE THREAD

**Issue by CuredPrusa** [supermerill/SuperSlicer#4303]
Hi
Maybe this is irrelevant, could be I just jumped into a work in progress. 
But maybe you will find it as a serious consequence of some ongoing tweaks:

Ironing angle doesn't change ironing lines angle when I adjust it from height range modifier.

**Comment by supermerill** [comment]
your project? it's working fine for me.

**Comment by CuredPrusa** [comment]
I'm sorry. It was a mistake from my side. 
Thanks.
