### ISSUE TITLE
Crash when trying to slice a model

### ISSUE THREAD

**Issue by Skorki51** [supermerill/SuperSlicer#4308]
### Version
2.5.59.11

### Operating system type + version
Windows 11 Pro / 10.0.22631 22631

### Behavior
* Crash when trying to slice a model

* When I tried to change the values ​​in the XY compensation, the program crashed.
Everything works fine with these settings:
![superslicer_OMM41dTBZY](https://github.com/supermerill/SuperSlicer/assets/149414795/7352570f-c944-4c1d-9a4c-5d916412ed34)

* But when I change the external or internal compensation, the program crashes.
e.g. for such values:
![superslicer_9fuAbUy03o](https://github.com/supermerill/SuperSlicer/assets/149414795/86989e31-86b0-4bf9-acb1-7b4ab280196f)

#### Project File (.3MF) where problem occurs
[project.zip](https://github.com/user-attachments/files/15750795/project.zip)

**Comment by roykrikke** [comment]
Is this the same as https://github.com/supermerill/SuperSlicer/issues/4301?

**Comment by Skorki51** [comment]
Possibly because it looks similar. 

But it doesn't always crash. depends on XY compensation settings. With this model that I added -0.05 and -0.1, the program works properly, but with other values ​​it crashes.

With another model, the values ​​-0.05 and -0.01 also did not cause a problem, -0.05 and -0.2 also worked, but something between, e.g. -0.05 and -0.015 crashed.
