### ISSUE TITLE
Fan speed bug with MMU

### ISSUE THREAD

**Issue by hagan66** [supermerill/SuperSlicer#431]
### Version
2.2.53.1

### Operating system type + version
MacOS 10.15.6

### 3D printer brand / version + firmware version (if known)
Prusa MK2.5S FW 3.9.0

### Behavior
Fan speed gets messed up with MMU prints. For example I set up the simplest 100% fan speed in filament settings. But when I inspect the preview the fan drops to 50% at the first filament change. If I set up different fan speed for infill, perimeters etc, it looks even worse.

![Skärmavbild 2020-08-30 kl  10 13 56](https://user-images.githubusercontent.com/9168083/91654526-d14bcd80-eaa9-11ea-913b-4a4865366d9a.png)

#### Project File (.3MF) where problem occurs

[Kub1.3mf.zip](https://github.com/supermerill/SuperSlicer/files/5146487/Kub1.3mf.zip)

**Comment by hagan66** [comment]
This is really bad actually. I havent been able to find a workaround and it prevents me from printing multi material prints. And I love Superslicer too much to go back to Prusaslicer.

**Comment by supermerill** [comment]
that wipe tower.... one day, it needs to be nuked and redone with the gcode writer.
