### ISSUE TITLE
Error while writing gcode: two points are at the same position

### ISSUE THREAD

**Issue by treeman** [supermerill/SuperSlicer#4312]
### What happened?

Got the error

```
Error while writing gcode: two points are at the same position
```

When slicing the model.

### Project file & How to reproduce

[v3-case-right.zip](https://github.com/user-attachments/files/15756886/v3-case-right.zip)

### Version

2.5.59.11

### Operating system

Void Linux

### Printer model

Voron Trident

**Comment by supermerill** [comment]
can't reproduce on windows, will try on ubuntu.

**Comment by supermerill** [comment]
same, can't reproduce.
Can you give me your project file instead of just the stl?

**Comment by treeman** [comment]
[cosmo.zip](https://github.com/user-attachments/files/15792163/cosmo.zip)

Sorry, my bad.

**Comment by treeman** [comment]
I updated to the new version [2.5.59.12](https://github.com/supermerill/SuperSlicer/releases/tag/2.5.59.12) and the problem has disappeared.
