### ISSUE TITLE
Feature Request: Jerk settings within acceleration control

### ISSUE THREAD

**Issue by SnowDrifterr** [supermerill/SuperSlicer#436]
I'd love to see jerk settings aside the acceleration settings. The two go hand-in-hand and can be very useful in reducing print time  with complicated infill settings such as gyroid without risk of introducing  ringing artifacts elsewhere in the print.

In reprap firmware, the nomenclature is: M566

**Comment by supermerill** [comment]
please use the issue https://github.com/supermerill/SuperSlicer/issues/237 for that.
