### ISSUE TITLE
min layer time broke

### ISSUE THREAD

**Issue by robthide37** [supermerill/SuperSlicer#442]
Newest update broke min layer time . I didn't bother loading a file cause i tried on two computers and multiple installs with pinhole edition

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/91978050-c9975d80-ed23-11ea-9ef1-92fe58d61794.png)

**Comment by robthide37** [comment]
set min layer time to 60 sec and check speed reduction . It won't slow the print no matter if you have it set at 90 % and 10mms min speed it will just stay at the speed you have set

**Comment by robthide37** [comment]
![image](https://user-images.githubusercontent.com/64717944/92036618-84ccf000-ed3e-11ea-8b9d-760ddbee6071.png)
![image](https://user-images.githubusercontent.com/64717944/92036639-8d252b00-ed3e-11ea-9e75-529c516aef8b.png)

**Comment by robthide37** [comment]
![image](https://user-images.githubusercontent.com/64717944/92036704-a4641880-ed3e-11ea-8952-fa7f393369a0.png)

**Comment by supermerill** [comment]
can i have your .3mf? (saveas -> zipped/renamed -> dropped here)

**Comment by robthide37** [comment]
[Fan_Shraud_ELF (1).3mf.txt](https://github.com/supermerill/SuperSlicer/files/5165250/Fan_Shraud_ELF.1.3mf.txt)

**Comment by robthide37** [comment]
diff one but still has the same prob

**Comment by supermerill** [comment]
ok, it's an old switch (cooling) that i don't use anymore but was set in this filament profile to false.
The bug it that It's doing something, and it shouldn't.

For now, to re-activate it, you can add
```
setting:cooling
```
below
```
page:Cooling:time
group:Fan speed - default
```
in resources/filament.ui
