### ISSUE TITLE
Incorrect gap fill width

### ISSUE THREAD

**Issue by kursatu** [supermerill/SuperSlicer#443]
### Version
_Version of SupserSlicer used goes here_
2.2.53 built with the latest commit from 8/27/2020
_Use `About->About SuperSlicer` for release versions_

_For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_

### Operating system type + version
_What OS are you using, and state any version #s_
Windows 10
_In case of 3D rendering issues, please attach the content of menu Help -> System Info dialog_

### 3D printer brand / version + firmware version (if known)
_What 3D printer brand / version are you printing on, is it a stock model or did you modify the printer, what firmware is running on your printer, version of the firmware #s_
Custom CoreXY, Vking derivative
### Behavior
* _Describe the problem_
Slice the attached .3mf file.
Observe the gap fill width at the attached screenshot. 
It is 0.84mm.
It causes surface artifacts, in this case just above this layer because of Multimaterial transition.
In the usual cases, this should cause on artifacts the perimeters / surface of the print. 
I've tried changing the min gap fill width, 
That setting does not seem to have an effect, which may be another defect. 
This might be my testing oversight though.

* _Steps needed to reproduce the problem_
  * _If this is a command-line slicing issue, include the options used_
* _Expected Results_
* _Actual Results_
  * _Screenshots from __*SuperSlicer*__ preview are preferred_

_Is this a new feature request?_

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`Plater -> Export plate as 3MF` for Slic3r PE 1.41.2 and older, `File -> Save` / `Save Project` for SuperSlicer, Slic3r PE 1.42.0-alpha and newer)_
![Defect7_1](https://user-images.githubusercontent.com/1686475/92019414-6ef20780-ed0b-11ea-888f-06edb61b352a.png)
[Defect7.zip](https://github.com/supermerill/SuperSlicer/files/5163980/Defect7.zip)

**Comment by supermerill** [comment]
sort of duplicate of #284

**Comment by neophyl** [comment]
The minimum gapfill setting is to stop the slicer putting really small amounts of gapfill down, it’s not related to its width I believe.

**Comment by supermerill** [comment]
The max width for gapfill is ~2*perimeter width. Shouldn't be a problem, unless gapfill speed is extremely high.

**Comment by kursatu** [comment]
Makes sense, thanks.
