### ISSUE TITLE
Seams not being placed on inside corners

### ISSUE THREAD

**Issue by VanessaE** [supermerill/SuperSlicer#445]
### Version

2.2.53 (git commit 95318d66d10c8456f4508834928199c11b809546)

### Operating system type + version

Debian bullseye

### 3D printer brand / version + firmware version (if known)

Custom-built Hypercube running Marlin, but that doesn't matter :stuck_out_tongue: 

### Behavior

Seams are not being placed on "inside" corners, rather "outside" corners and even overhangs are being chosen where inside corners would hide the seam better:

![image](https://user-images.githubusercontent.com/1733537/92074560-5c67e480-ed84-11ea-8862-5968b2fd7cbc.png)

Pictured here are two views of the rear, right corner of a popular retraction test object (3mf below).  Here you can see that the outside corner is chosen for the seam position in this area of the object, until it gets up to where the overhanging part turns vertical, then the seam moves there.  The silver diamonds are the unretract moves (since the retracts take place between the perimeters).

The other three main corners demonstrate similar behavior.

The green line marks where I would have expected the seam to be placed along the entire height of the part.

"Nearest", "Aligned", "Rear", and "Corners" seam modes all produce this result.  Seam position objects don't help; even when I put one right next to an inside corner, a different spot is chosen anyway.  It's as if SS is expressly avoiding inside corners.  Shouldn't it try to avoid *outside* corners instead?

Upstream Slic3r (https://github.com/slic3r/Slic3r/commit/28d5e879) puts the seams in the inside corners, at least in the part of the print pictured above.  Prusaslicer (https://github.com/prusa3d/PrusaSlicer/commit/0cfa64e24568188516506f94d310d9c46688e053) has the same behavior as SuperSlicer.

#### Project File (.3MF) where problem occurs

[Retraction.3mf.zip](https://github.com/supermerill/SuperSlicer/files/5166310/Retraction.3mf.zip)

**Comment by supermerill** [comment]
It's the wipe.

**Comment by supermerill** [comment]
should be fixed on 2.3.55, as prusa reworked a bit the seam algo, I use that opportunity to tune it a bit more.
