### ISSUE TITLE
SuperSlicer crashes when clicking on Gcode Thumbnails settings. [solved]

### ISSUE THREAD

**Issue by LazaroFilm** [supermerill/SuperSlicer#452]
### Version
2.2.53

### Operating system type + version
MacOS 10.15.6

### 3D printer brand / version + firmware version (if known)
HEVO / Klipper

### Behavior
SuperSlicer crashes when clicking on Gcode Thumbnails: setting. The whole window closes instantly. 

#### Project File (.3MF) where problem occurs
Happens without any opened project.

**Comment by supermerill** [comment]
maybe something related to #222

Can't replicate

**Comment by LazaroFilm** [comment]
Yes, the value in the config file was `thumbnails =`
I had imported settings from PrusaSlicer for this printer, that might be the reason why my values were empty? Maybe implementing a check on this value, if it's empty, make it equal to the default value?

**Comment by supermerill** [comment]
The check is done, in the nightly build.
