### ISSUE TITLE
Bug - Disable only for outter side

### ISSUE THREAD

**Issue by VectorPort** [supermerill/SuperSlicer#459]
[bandicam 2020-09-09 15-51-32-196.zip](https://github.com/supermerill/SuperSlicer/files/5195246/bandicam.2020-09-09.15-51-32-196.zip)

### Version
2.2.53

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
-

### Behavior
If you enable External perimeter first, then only for outter side and only for inner side are enabled. Then, if you turn off only the only for outter side, the program is immediately closed. All this happens if there is a model on the table. If there is no model, nothing happens.

#### Project File (.3MF) where problem occurs
-

**Comment by supermerill** [comment]
If you save your project, close the slicer, start again, open your project then uncheck the fireld, does it crash?
If yes, can you post your project file (zipped)?

**Comment by VectorPort** [comment]
Recorded a video when an error occurs. Maybe it will be easier to understand. The error occurs with any file.
[bandicam 2020-09-09 15-51-32-196.zip](https://github.com/supermerill/SuperSlicer/files/5195260/bandicam.2020-09-09.15-51-32-196.zip)

**Comment by supermerill** [comment]
yet, it doesn't crash on my computer with my settings.

**Comment by neophyl** [comment]
Doesn't crash on mine either.  Same version , windows 10.

**Comment by VectorPort** [comment]
Deleted the entire folder with settings, and restarted. No more crashes. Sorry for the fake call)

**Comment by VectorPort** [comment]
I tried it on another PC. As soon as I press Slicer now, he throws an error.
