### ISSUE TITLE
Feature Request: Disable Retraction on First Layer

### ISSUE THREAD

**Issue by Poofjunior** [supermerill/SuperSlicer#464]
### Version
2.2.53

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Jubilee 2.1.x (Toolchanging CoreXY, Duet + RepRapFirmware 2.x)

### Behavior
* First layer adhesion has been hit-or-miss using superslicer with retraction in between closed contours. For small contours (like a 3mm hole), retracting can rip them off the plate while operating without retraction seems to do a bit better.
* Would it be possible to add a checkbox that disables retraction on the first layer?
* Extra Info
  * This machine has some fairly zippy travel moves (333mm/sec or higher), which may be partly why first layer adhesion of small contours can be a bit tricky with its max speed turned all the way up. Nevertheless, I think this would be a wonderful tickbox option for faster printers.

_Is this a new feature request?_ --> yes :)

Cheers--and thanks for all your sincere efforts making this project awesome!

**Comment by supermerill** [comment]
duplicate (sorta) of #137
