### ISSUE TITLE
Print time estimate showing negative seconds amount

### ISSUE THREAD

**Issue by toskium** [supermerill/SuperSlicer#468]
### Version
2.2.53

### Operating system type + version
Windows 10 Pro

### 3D printer brand / version + firmware version (if known)
Klipper gcode flavor
DIY Printer

### Behavior
After slicing objects an estimated print time is usually displayed, but instead a negative amount of seconds is displayed.

![image](https://user-images.githubusercontent.com/15872792/93047798-93c87200-f65d-11ea-847b-2b6d4c1b9b42.png)

#### Project File (.3MF) where problem occurs
[printtime_3mf.zip](https://github.com/supermerill/SuperSlicer/files/5216359/printtime_3mf.zip)

**Comment by neophyl** [comment]
#364  #437

**Comment by toskium** [comment]
Ah, sorry for the duplicates, I'll close it.
