### ISSUE TITLE
Doesn't add support modifier inside height range modifier

### ISSUE THREAD

**Issue by afkfurby** [supermerill/SuperSlicer#476]
### Version
2.2.53.1

### Operating system type + version
windows 10

### Behavior
Add a height range modifier to a model, try to add a support modifier to that height range modifier.
No support settings added, perimeter or infill works.

[ss_suport_height_error.zip](https://github.com/supermerill/SuperSlicer/files/5225494/ss_suport_height_error.zip)

**Comment by supermerill** [comment]
These only works with objects.

Nothing show up because there is no modifier that can be applied on a modifier.
The bug is more that the "interface" sub-menu is shown.
