### ISSUE TITLE
Seam-Sphere too big

### ISSUE THREAD

**Issue by dartrax** [supermerill/SuperSlicer#477]
### Version
2.2.53

### Operating system type + version
Win 10 x64

### Behavior
Thanks for making a up to date Slicer version with individual control over seam placement available! I'll use this from now on over my old Prusa 1.4 mod.

I've noticed the seam sphere being rather huge, it would be easier to guess the actual seam position if it would be smaller. The cause may be the large print bed (430 x 390), may be using the object size as size reference?

![image](https://user-images.githubusercontent.com/15105943/93353708-83bab900-f83c-11ea-965e-ed71083ecbbc.png)

**Comment by supermerill** [comment]
For the time being, you can change its size with the size widget at the bottom right.

**Comment by dartrax** [comment]
Ah I didn't see that. Great!
