### ISSUE TITLE
Klipper Mode does support progress bar on Ender 3

### ISSUE THREAD

**Issue by madsi1m** [supermerill/SuperSlicer#487]
### Version
2.20.53

### Operating system type + version
Win 10

### 3D printer brand / version + firmware version (if known)
Ender 3 + SKR mini + Klipper

### Behavior
When "g-code flavor" is set to klipper the progress bar on my lcd is always at 0%
Perhaps progress isn't put in the gcode?

**Comment by supermerill** [comment]
Probably.
i'll look to add M73 also to klipper

**Comment by 1N4148** [comment]
M73 are already written in the gcode when using klipper flavoured gcode. Just tick "Supports remaining times" in the printer settings dialog.

**Comment by madsi1m** [comment]
Hi @1N4148 thanks for the info, that did the trick, can probably close the issue.

In PrusaSlicer+Marlin, this tickbox triggers the display of time remaining rather than progress bar. And the progress bar is always "on".
