### ISSUE TITLE
Keep view selection after slicing

### ISSUE THREAD

**Issue by carloshespanhol** [supermerill/SuperSlicer#492]
### Version
2.2.53

### Operating system type + version
Ubuntu 18.04

### 3D printer brand / version + firmware version (if known)
Hypercube / Klipper

### Behavior
- after slicing select speed view
- change printing settings
- reslice

I think it should keep the selected view, instead it always change to tool  view

Is this a new feature request?  No

**Comment by supermerill** [comment]
should have been corrected by #147 / commit 498c48580a9e7ddec544f18860559ad4339a6d52

found a bad line. will correct that.

**Comment by carloshespanhol** [comment]
Thanks
