### ISSUE TITLE
Ironing creating gaps

### ISSUE THREAD

**Issue by furbyhaxx** [supermerill/SuperSlicer#498]
### Version
2.2.53.2

### Operating system type + version
win10

### Behavior
Tried to dial in ironing with petg on one of our big machines, nozzle size 0.8mm
but doesn't matter what I change, it's creating gaps betweend shells and solid infill of the ironing pass,
This does not appear when using rectilinier (filled).
It's also appearing with PLA Carbon.
Doesn't make a change if I use one or multiple shells on top layer.

![ironing](https://user-images.githubusercontent.com/13721934/94258292-ebec5780-ff2c-11ea-9c5b-632f6b7bf0fe.jpg)

#### Project File (.3MF) where problem occurs
[ironing.zip](https://github.com/supermerill/SuperSlicer/files/5282255/ironing.zip)

**Comment by supermerill** [comment]
In the ironing infill, the first pass is done without overlap. (but not the second one).
Maybe that's why.
I did that to avoid overextrusion on narrow surfaces.
I'll have to change that, maybe it's possible to have an overlap on large areas but (almost) none in thin one...

**Comment by robthide37** [comment]
one thing is when ironing is on it changes the top infill speed to the ironing speed and then your solid infill becomes your top layer speed

**Comment by fishcu** [comment]
I've also come across this and would consider this a bug. I would prefer the overlap setting to apply everywhere.

Compare the following two screenshots that show top infill as "monotonous filled" vs. "ironing":

![monotonous_filled](https://user-images.githubusercontent.com/25356186/100005366-1f325200-2dc9-11eb-8e0d-1f461e910244.png)
![ironing](https://user-images.githubusercontent.com/25356186/100005369-20fc1580-2dc9-11eb-8fb2-1e1c89797c78.png)

**Comment by supermerill** [comment]
if you have "enforce 100% fill volume", you have the same amount of plastic on the two cases.
and i have done that to prevent overextrusion on thin area.

**Comment by supermerill** [comment]
the behavior has changed in the last releases, with a bit more overlap.
