### ISSUE TITLE
Feature Request: Retrieve printhost_apikey from file

### ISSUE THREAD

**Issue by ReneRebsdorf** [supermerill/SuperSlicer#499]
### Version

2.2.53

### Operating system type + version

Windows 10

### 3D printer brand / version + firmware version (if known)

Ender 3 / Klipper

### Behavior

printhost_apikey is exposed in config files

I have a private repository where I track currently used config files for both SuperSlicer and Klipper. 
The only reason these are not public is to avoid exposing the printhost_apikey.
Although the printer itself is not exposed on any public network, I see no reason to expose the API Key to Octoprint where unneeded.

My suggestion is to add support for "printhost_apikey" to be able to take file path as input as well as the current "hard coded" (for compatibility and ease of use for most). I would suggest at least relative file path support, or both relative and absolute file path support.

The file structure could be either key/value pairs (like in current config files) or a one-line value file support.
The UI could either reference file path or resolve the value.

This is a feature request.

#### Project File (.3MF) where problem occurs

N/A

**Comment by supermerill** [comment]
since prusa created the 'hardware printer' separate profile, it's not printed in the gcode file.
since last nightly, you can export them yourself these settings with a custom gcode script line if needed.
