### ISSUE TITLE
[FEATURE REQUEST] REMOVE HOLES IN AIR

### ISSUE THREAD

**Issue by banolka** [supermerill/SuperSlicer#504]
It would be awesome to implement the option to add 1 sacrificial layer to unsupported holes in the air. Taht would greatly improve prints quality and reduce time and plastic.

**Comment by neophyl** [comment]
Have a read of this page from the wiki https://github.com/supermerill/SuperSlicer/wiki/No-perimeters-on-bridge-area

**Comment by banolka** [comment]
I was thinking more lice automatic solution not adding manual additional parts etc.
