### ISSUE TITLE
Inconsistent retract and unretract when extra length parameter is set

### ISSUE THREAD

**Issue by tionebrr** [supermerill/SuperSlicer#520]
### Version
SuperSlicer_2.2.53_2020-09-18

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Ender 3 running on Klipper

### Behavior
- retraction and unretraction lengths are inconsistent

Here before the first perimeter:
![image](https://user-images.githubusercontent.com/8854321/94870877-f89b0f00-0448-11eb-9af0-ef26eeda252e.png)

And after the first layers:
![image](https://user-images.githubusercontent.com/8854321/94870910-09e41b80-0449-11eb-9e59-6c475ff6f8fd.png)

I have set the extra retract length as ratract+extra to get these values.
I am gladly joining the 3mf file.
#### Project File (.3MF) where problem occurs

[pot_l50.0xL50.0xH60.0_v2.3mf.zip](https://github.com/supermerill/SuperSlicer/files/5315178/pot_l50.0xL50.0xH60.0_v2.3mf.zip)

**Comment by supermerill** [comment]
there is a `G92 E0 ; reset extrusion distance` in between in the first picture, so no error.

**Comment by tionebrr** [comment]
Thanks @supermerill, the problem is that my settings are as following:
![image](https://user-images.githubusercontent.com/8854321/94874268-e40f4480-0451-11eb-9a1e-3e704076a6f1.png)
(Note: I changed the extra amount from 2.05 to 2.01 since the first post, still calibrating)

**Comment by tionebrr** [comment]
I am rereading my first post of this issue and it is misleading. You had to go in the parameters of the file to notice that, so my bad. I'm going to close this issue as a reference and open another more specific one.
