### ISSUE TITLE
"Extra length on restart" is applied as unretract length altogether

### ISSUE THREAD

**Issue by tionebrr** [supermerill/SuperSlicer#521]
### Version
SuperSlicer_2.2.53_2020-09-18

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Ender 3 + Klipper/Mainsail

### Behavior
I am noticing that somhow, with my install, the unretract extra length is actually the unretract length.

If you set a retract length of 2mm, and add 0.01mm as extra length, the gcode shows an actual unretract length equal to the extra amount.

Shouldn't the unretract length be `retract+extra`, 2.01mm instead of 0.01mm?

![image](https://user-images.githubusercontent.com/8854321/94874878-749a5480-0453-11eb-8fa9-ef16a94256ca.png)
![image](https://user-images.githubusercontent.com/8854321/94874853-66e4cf00-0453-11eb-8db7-bda66fc48e4d.png)

Edit: Other users noticed me that they cannot reproduce the issue.

**Comment by supermerill** [comment]
Are you in relative or absolute E ?

**Comment by tionebrr** [comment]
Aaaah thanks @supermerill, that's explaining everything.
I am in absolute.

I am using a 1mm nozzle which kind of behave strangely (underextruding). The retract/unretract was one of the first thing I checked and those values seemed weird. Didn't thought about the positioning mode.

Thanks again and sorry for the noise.
