### ISSUE TITLE
What is the purpose of Rectilinear (Solid)?

### ISSUE THREAD

**Issue by ManIkWeet** [supermerill/SuperSlicer#523]
This is more a question than a bug (or is it?).
The description in the slicer wasn't very clear.

"Rectilinear (filled) replace zig-zag patterns by a single big line & is more efficient for filling little spaces."

What I personally see it doing is adding a large amount of travel moves instead.
It seems to be extruding the lines in a single direction only. For large surfaces this seems to add a lot of printing time, especially with multiple layers doing it. I wouldn't say the print quality improved in any way.

Is it a feature that only works well on small areas? Should it be the actual default setting then?

**Comment by supermerill** [comment]
rectilinear
![image](https://user-images.githubusercontent.com/6536403/95024406-0936c980-0683-11eb-8f65-3482c824a0f9.png)

rectilinear with gap fill
![image](https://user-images.githubusercontent.com/6536403/95024420-1fdd2080-0683-11eb-87ec-f5a3aad23a93.png)

**Comment by ManIkWeet** [comment]
@supermerill That makes a lot of sense!
But what I don't understand then, is that it also seems to add a lot of travel moves, is this considered a bug?

Both images have travel moves visualized
Rectilinear:
![image](https://user-images.githubusercontent.com/4006814/95024497-a98cee00-0683-11eb-8aed-22bcf3b78878.png)

Rectilinear (filled):
![image](https://user-images.githubusercontent.com/4006814/95024523-cb867080-0683-11eb-8925-fd691284c434.png)

**Comment by supermerill** [comment]
what version do you have?
lokk at right of the infill patter, is "connected" selected?

**Comment by ManIkWeet** [comment]
> what version do you have?
> look at right of the infill patter, is "connected" selected?

Version: 2.2.53
Build: SuperSlicer_2.2.53_2020-09-18

Yes, that was connected! Turning it off does remove the travel moves, so that's great!
I turned it off for the following reason:
![image](https://user-images.githubusercontent.com/4006814/95024963-8a439000-0686-11eb-9c8a-b63c3ba19893.png)
This is a big object and the (very sparse 1%) infill was following the edge creating practically another perimeter. I didn't realise this setting also effected solid infills for top/bottom layers.

**Comment by supermerill** [comment]
You can modify it on a Height range modifier, if you need it.

**Comment by ManIkWeet** [comment]
Ah that is very cool, I didn't know that.
I'm coming from PrusaSlicer and when messing with layer settings or object modifiers there really weren't that many settings to change. Still getting the hang of SuperSlicer! :)
