### ISSUE TITLE
colorprint doesn't change default color

### ISSUE THREAD

**Issue by wnc2** [supermerill/SuperSlicer#534]
### Version
2,54

### Operating system type + version
MacOS catalina 10.15.7

### 3D printer brand / version + firmware version (if known)
MK3S with palette

### Behavior

it is impossible to change the default extruder in coloprint, if i change, the right color blinks for a second, then returns grey again, no problem for additional layer change.
Feature is ok in the last 2.53 and previous

![Schermata 2020-10-06 alle 18 52 09](https://user-images.githubusercontent.com/43959480/95232677-21365680-0805-11eb-93b9-a5e4e8ad251f.jpg)

_Is this a new feature request?_

no

**Comment by supermerill** [comment]
yeah, i think it's the same bug as the other one. I initialized the extruder too early...
I'm correcting it.

**Comment by wnc2** [comment]
Hope this helps

Bye

⁣Ottieni BlueMail per Android ​

Il giorno 7 ott 2020, 00:56, alle ore 00:56, Merill <notifications@github.com> ha scritto:
