### ISSUE TITLE
Retraction Calibration not correctly generating.

### ISSUE THREAD

**Issue by afkfurby** [supermerill/SuperSlicer#538]
### Version
2.2.54 

### Operating system type + version
win10

### Behavior
The retraction calibration is generating some strange plate below the actual test and has an air gap.
That way you get an empty layer detected while slicing

![image](https://user-images.githubusercontent.com/13721934/95300534-96df0880-087f-11eb-9022-bd37a5bc37aa.png)

**Comment by afkfurby** [comment]
ah found out what this is, It's the temperature label placed at -1.33 instead of 0 or +0.4

**Comment by supermerill** [comment]
can you post your project file ? i can't reproduce... it's with a big or little nozzle diameter?

**Comment by zervin** [comment]
Seeing the same issue with a 0.5mm nozzle.
[retraction_calibration.zip](https://github.com/supermerill/SuperSlicer/files/5417290/retraction_calibration.zip)
