### ISSUE TITLE
Slicing adds extra material

### ISSUE THREAD

**Issue by mattchan-tencent** [supermerill/SuperSlicer#549]
### Version
2.2.53.3 and 2.2.54

### Operating system type + version
MacOS 10.15.6

### 3D printer brand / version + firmware version (if known)
Ender 5 pro

### Behavior
Slicing a particular model ends up adding extra material from the stl. Several holes get filled (inverted). The STL renders correctly in several programs. 

<img width="2560" alt="Screen Shot 2020-10-09 at 12 27 58 AM" src="https://user-images.githubusercontent.com/49500504/95543430-82f1ee80-09c6-11eb-81bb-cec1eca401f2.png">
<img width="2560" alt="Screen Shot 2020-10-09 at 12 28 11 AM" src="https://user-images.githubusercontent.com/49500504/95543440-86857580-09c6-11eb-8866-35702aff4d81.png">
<img width="2560" alt="Screen Shot 2020-10-09 at 12 28 16 AM" src="https://user-images.githubusercontent.com/49500504/95543445-89806600-09c6-11eb-9628-1e7960fab402.png">

_Is this a new feature request?_
No

#### Project File (.3MF) where problem occurs

[saw_handle.zip](https://github.com/supermerill/SuperSlicer/files/5352524/saw_handle.zip)

**Comment by neophyl** [comment]
The model has 4 non manifold edges.  Prusa Slicer and Super Slicer sometimes has trouble coping with these.  However when you fix the underlying model errors (say with Netfabb or using Blenders 3dPrint tool like I did) then it slices correctly.

[saw_handle_neo.zip](https://github.com/supermerill/SuperSlicer/files/5352863/saw_handle_neo.zip)
