### ISSUE TITLE
"Only one perimeter on Top surfaces" affects previous layers

### ISSUE THREAD

**Issue by Zulaner** [supermerill/SuperSlicer#550]
### Version
2.2.53 (Retraction calibration edition)

### Behavior
"Only one perimeter on Top surfaces": Unchecked
![image](https://user-images.githubusercontent.com/38788588/95616407-a5851580-0a61-11eb-8ae7-805021241e08.png)

"Only one perimeter on Top surfaces": Checked
![image](https://user-images.githubusercontent.com/38788588/95616519-d1080000-0a61-11eb-9245-7e970a74219b.png)
the arrow is to highlight this perimeter, that is not even part of the drawing

[Superman_Ear_Saver.zip.amf.zip](https://github.com/supermerill/SuperSlicer/files/5356773/Superman_Ear_Saver.zip.amf.zip)

**Comment by neophyl** [comment]
On your 1 perimeter for top layers setting in the main configuration you have it set to Minimum Width 200%.  While that is great for sloping walls (and is pretty much what I use) in this case its causing the issue.  If you set it to 100-150% then it slices correctly.  Not sure why its doing that though.

**Comment by supermerill** [comment]
can't solve
