### ISSUE TITLE
Latest artifact "#493 separate bridge fan/speed for overhang from bridg..." not starting

### ISSUE THREAD

**Issue by 1N4148** [supermerill/SuperSlicer#552]
Latest build (#493 separate bridge fan/speed for overhang from bridg...) won't start with existing config. Starting without config works. But after importing a config bundle SuperSlicers is closing and refusing to run.

**Comment by supermerill** [comment]
erf.

**Comment by 1N4148** [comment]
When starting from scratch: Checking "Generate Supports" also terminates SuperSlicer.

**Comment by supermerill** [comment]
I fixed the second bug, but I fail to reproduce the first one. Do you have a config / config bundle that makes it crash?

**Comment by 1N4148** [comment]
See the attached bundle. If I delete all profiles in the settings/print, SuperSlicer starts. But as soon as I try to import a backuped print-profile it terminates.

[SuperSlicer_config_bundle.zip](https://github.com/supermerill/SuperSlicer/files/5359745/SuperSlicer_config_bundle.zip)

**Comment by 1N4148** [comment]
PS: The "#533 #534 fix bad extruder initialisation (from 0d775d9ec829fd04" build works, but has the bug with the wrong temperature for the first layer

**Comment by supermerill** [comment]
can't make it crash even with your bundle on an empty setting folder.
![image](https://user-images.githubusercontent.com/6536403/95663321-988a2400-0b3e-11eb-8a32-4fe38da79c6d.png)

**Comment by 1N4148** [comment]
Strange. Can I provide anything more for debugging? Maybe cause of the "generate supports" in my configs? Then I'll wait for the next build where the second bug is fixed.

**Comment by 1N4148** [comment]
Did a quick test and changed the "support_material = 1" to "support_material = 0" in the print-configs. Now it works. So, first bug is caused of the second bug.

**Comment by supermerill** [comment]
should be fixed in last nightly

**Comment by 1N4148** [comment]
Ok, will test it :)

**Comment by 1N4148** [comment]
Ok, works! Thx a lot! :)
