### ISSUE TITLE
Auto speed and Top Layer with change at height

### ISSUE THREAD

**Issue by Zulaner** [supermerill/SuperSlicer#553]
### Version
2.2.53 (Retraction calibration edition)

### Behavior
when using height change modifying only the TOP Layer count to 1
the entire printing speed is affected
![image](https://user-images.githubusercontent.com/38788588/95658927-ca3ac500-0b15-11eb-947d-e9eeb860991f.png)
![image](https://user-images.githubusercontent.com/38788588/95658922-c444e400-0b15-11eb-9a46-89ef1763ade0.png)

**Comment by Zulaner** [comment]
[Heart_EKG_Ear_Saver.zip.amf.zip](https://github.com/supermerill/SuperSlicer/files/5359265/Heart_EKG_Ear_Saver.zip.amf.zip)

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/95662577-35958e80-0b38-11eb-97c0-601566306dfa.png)

for layer range is from 0.6mm so it affect everything after 0.6mm

i don't really understand what's wrong

**Comment by Zulaner** [comment]
See the speed...

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/95662955-3b40a380-0b3b-11eb-9cd1-7adb0c433822.png)
Sure, the "short layer time" Colling option kicks int (see filament-> cooling, you can set 'enable fan if time below' and 'layer time goal' to 0 to check their effects)

**Comment by supermerill** [comment]
Ok, that's the gapfill inside the 'rectilinear / monotonous with gapill' that makes the auto-speed go to very low speed (because of very thin extrusion).
