### ISSUE TITLE
Hang when adaptive slicing an STL.

### ISSUE THREAD

**Issue by ayerlock** [supermerill/SuperSlicer#555]
### Version
2.2.53.x

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Voron 2.4 300x300

### Behavior
* Adaptive slicing at 0.25/4 hangs the slicer on the attached STL.
* Load piggybank.stl w/0.4mm nozzle defaults and set the adaptive slicer to 0.25 w/radius of 4 smoothing.  Slice.
* Slices file, outputs GCode.
* Hangs after render.

#### Project File (.3MF) where problem occurs

[Piggy_Bank.zip](https://github.com/supermerill/SuperSlicer/files/5361563/Piggy_Bank.zip)

**Comment by supermerill** [comment]
Just tested on the nightly.
It's just horribly slow, particularly with the avoid crossing perimeter.
