### ISSUE TITLE
Feature request: RaiseCloud

### ISSUE THREAD

**Issue by Coffee0297** [supermerill/SuperSlicer#558]
Can we get support to upload direct to RaiseCloud? its soo nice and makes so you don't have to mess with octorpint's bad UI

Kind regards Tonny

**Comment by supermerill** [comment]
I need more informations and links to how to do that.

**Comment by Coffee0297** [comment]
https://github.com/Raise3D/OctoPrint-Raisecloud
thats the octo plugin, i can't seem to find how to manually upload tho

**Comment by supermerill** [comment]
Isn't this to add an octoprint printer to the Raisecloud?

> i can't seem to find how to manually upload tho

you can't manually upload to raisecloud?

You have to explain me how to use or upload to 'raisecloud'.
It doesn't have an api?

**Comment by Matts-Hub** [comment]
According to this thread there isn't currently any api to upload to the raise cloud https://forum.raise3d.com/viewtopic.php?t=20763

**Comment by supermerill** [comment]
!remindme 1 year
