### ISSUE TITLE
Typos in Retraction Calibration Screen

### ISSUE THREAD

**Issue by girrrrrrr2** [supermerill/SuperSlicer#566]
### Version
2.2.54

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Unnecessary

### Behavior
Extruder Retraction calibration has a typo and the title says Flow Calibration
Typo - Multiply it by your step parameter (0.2, 0.2, 0.5 or 1)
Should be - Multiply it by your step parameter (0.1, 0.2, 0.5 or 1)

Title Box Says - SuperSlicer - Flow Calibration
Should be - Super Slicer - Retraction Calibration

Super simple issues, nothing really that crazy, just thought id point them out so that you knew.

**Comment by supermerill** [comment]
>Multiply it by your step parameter (0.2, 0.2, 0.5 or 1)
>Multiply it by your step parameter (0.1, 0.2, 0.5 or 1)

can you put in bold the characters that are wrong? I can't spot them.

**Comment by digitalentropy** [comment]
Multiply it by your step parameter (**0.2**, 0.2, 0.5 or 1)

**Comment by girrrrrrr2** [comment]
> Multiply it by your step parameter (**0.2**, 0.2, 0.5 or 1)

Yes this. 0.2 is listed twice.
