### ISSUE TITLE
Cover whole area at once over bridges

### ISSUE THREAD

**Issue by chaicracker** [supermerill/SuperSlicer#570]
Hello :)

What I am trying to accomplish is to make a printed business card. The bottom looks like expected and clean but the top shows these areas that are above the bridging. Don't know what these could be called so haven't found anything online about this specific phenomenon.

Example photos:
![SlicerMerge2](https://user-images.githubusercontent.com/15281002/96186024-1e411180-0f3b-11eb-9ae6-5a459b875f66.jpg)
![SlicerMerge](https://user-images.githubusercontent.com/15281002/96186028-1f723e80-0f3b-11eb-89dc-0fb93ff035ff.jpg)

So far I only found the option "Don't connect" at "Pattern" under "Infill" but that leaves holes in the print.

Is there any option to kill that specific stacking functionality and prints the whole area over bridges like it doesn't even know that is anything below it?

So far I have seen on Cura that it does exactly that, but it has to many bugs and other issues to be a slicer to rely on..
![SlicerMergeCura](https://user-images.githubusercontent.com/15281002/96188010-41b98b80-0f3e-11eb-88a7-f26cb3aa8a84.jpg)
![SlicerMergeCura2](https://user-images.githubusercontent.com/15281002/96188013-42eab880-0f3e-11eb-8565-b6b0624d580e.jpg)

But so far SuperSlicer has been a blessing! Precise and reliable tool. Great job! :)

Cheers

SuperSlicer 2.2.53
Win 10 Pr0
Ender 3 Pro Marlin 2.0.5.3

**Comment by supermerill** [comment]
put 100% in "over-bridge flow"
