### ISSUE TITLE
Seam setting changed between 2.2.53 & 2.2.54

### ISSUE THREAD

**Issue by neophyl** [supermerill/SuperSlicer#572]
### Version
2.2.54

### Operating system type + version
windows 10 64bit

### 3D printer brand / version + firmware version (if known)
modified mk3

### Behavior
Had a .3mf file saved in version 2.2.53.2 and the print settings had the seam value set to 'Rear'.  When I loaded it into 2.2.54 the seam had been set to 'Random'.  After noticing that I am now wondering if other settings also get changed for projects saved in older versions.

#### Project File (.3MF) where problem occurs

[120mm lens silencer slotted and holes.zip](https://github.com/supermerill/SuperSlicer/files/5391574/120mm.lens.silencer.slotted.and.holes.zip)

**Comment by supermerill** [comment]
your .3mf contains `seam_position = random`
Does this .3mf is really showing as 'Rear' on 2.2.53.2 ? On mine, it also shows "random".
