### ISSUE TITLE
First layer temperature

### ISSUE THREAD

**Issue by xFuryx87** [supermerill/SuperSlicer#574]
### Version 
2.2.54

### Operating system type + version
Windows 10 

### 3D printer brand / version + firmware version (if known)
Anycubic I3 Mega S,  Marlin 2.0.5.4

### Behavior
First layer temperature only applies to brim.

![image](https://user-images.githubusercontent.com/71753515/96279886-90673400-0fd7-11eb-9c1b-2ca6598d980b.png)
![image](https://user-images.githubusercontent.com/71753515/96279938-9e1cb980-0fd7-11eb-8e97-84ed776448ba.png)

**Comment by supermerill** [comment]
Thanks for the report.
But already reported fixed, and warned about in the release page. download the nighlty, or wait some days to let me correct other bugs.
