### ISSUE TITLE
Filament Start Commands Ignored 

### ISSUE THREAD

**Issue by nullibyte** [supermerill/SuperSlicer#575]
### Version
SuperSlicer 2.2.53

### Operating system type + version
Windows 10 x64 build 2004

### 3D printer brand / version + firmware version (if known)
Voron V2.2 with Klipper V0.8.0 (I think but not entirely certain) 

### Behavior
I have a SET_GCODE_OFFSET Z=-0.085; under my filament start gcode, however upon generation of the gcode it's not included in the start gcode commands when reviewing the generated gcode file, hence my z offset never changes at print start and has to be manually done, this was not an issue when I ran the Voron Edition of superslicer (last version I had before updating) 

#### Project File (.3MF) where problem occurs
[1st 2.4 parts.zip](https://github.com/supermerill/SuperSlicer/files/5394854/1st.2.4.parts.zip)

**Comment by supermerill** [comment]
Thanks for the report.
You can use the 2.2.53.3 version, it's the stable one.
Already reported & corrected. Fix will be released soon.
