### ISSUE TITLE
[Feature Request] Brim inside in Vase Mode with no bottom layer

### ISSUE THREAD

**Issue by th33xitus** [supermerill/SuperSlicer#576]
### Version
Build from src (https://github.com/supermerill/SuperSlicer/commit/2291bd76de6ee2912dbe826a43d2a8941bd9b926)

### Operating system type + version
Win10

### 3D printer brand / version + firmware version (if known)
Klipper

### Feature Request
Make inside brim also available in vase mode prints with no bottom layer.
I think there can be some situations where this can be beneficial, like tacking a vase with no bottom to the print surface.

[![Bild 20-10-17_11-32-17_sup72k1e.png auf abload.de](https://abload.de/img/20-10-17_11-32-17_sup72k1e.png)](https://abload.de/image.php?img=20-10-17_11-32-17_sup72k1e.png)
[![Bild 20-10-17_11-32-24_supo5k6x.png auf abload.de](https://abload.de/img/20-10-17_11-32-24_supo5k6x.png)](https://abload.de/image.php?img=20-10-17_11-32-24_supo5k6x.png)

**Comment by supermerill** [comment]
The vase thing is a hack, if you really need an internal brim layer, add a range modifier for the first layer and set the bottom layer count to 1
