### ISSUE TITLE
Bridge/Overhang Fan Speed 

### ISSUE THREAD

**Issue by xFuryx87** [supermerill/SuperSlicer#578]
### Version
2.2.54 nightly

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Anycubic I3 Mega S, Marlin 2.0.5.4

### Behavior
The fan speed is not only applied to bridges and overhangs, which results in unsightly perimeters when printing with PETG (red layers in the screenshots)
  * _Screenshots from __*SuperSlicer*__ preview are preferred_
![image](https://user-images.githubusercontent.com/71753515/96377669-66ed0a80-1187-11eb-8517-c7f082c21090.png)
![image](https://user-images.githubusercontent.com/71753515/96377692-7f5d2500-1187-11eb-91a4-97d7354cc3d4.png)

#### Project File (.3MF) where problem occurs
[frame_older_and_elite.zip](https://github.com/supermerill/SuperSlicer/files/5403517/frame_older_and_elite.zip)

**Comment by supermerill** [comment]
can you post your project file?

**Comment by xFuryx87** [comment]
> can you post your project file?

I will post it as soon as I'm home again.

**Comment by xFuryx87** [comment]
> can you post your project file?
Done!

**Comment by supermerill** [comment]
printer setting -> fan startup delay, put 0.

**Comment by xFuryx87** [comment]
> printer setting -> fan startup delay, put 0. It's a setting to let some time for the fan to start. Or it won't even has a chance to ramp up its speed.

worked! you are my hero! thank you very much
