### ISSUE TITLE
first layer - extra perimeter

### ISSUE THREAD

**Issue by rkoehler2017** [supermerill/SuperSlicer#580]
latest 64Bit SS
Windows 64

Maybe it's a wrong setting but SS slices me an extra perimeter on the first level,
0.8mm Nozzle, 0.4 Layer, no brim
![image](https://user-images.githubusercontent.com/31540737/96399899-c2db8180-11cf-11eb-9bfa-8fc3ee6f77bb.png)

**Comment by supermerill** [comment]
your first layer compensation is positive instead of negative.

**Comment by rkoehler2017** [comment]
i checked all settings in SuperSlicer but i can not find - first layer compensation


[FilaTrenner v1_PLA.zip](https://github.com/supermerill/SuperSlicer/files/5439052/FilaTrenner.v1_PLA.zip)

**Comment by supermerill** [comment]
in print->slicing->modifying slices->XY compensation->First layer

**Comment by rkoehler2017** [comment]
Great, Thanks, 
that was the clue
