### ISSUE TITLE
First layer temperature applied only on skirt instead of on entire first layer

### ISSUE THREAD

**Issue by bigsubgit** [supermerill/SuperSlicer#581]
### Version
2.2.54

### Operating system type + version
MacOS Catalina

### 3D printer brand / version + firmware version (if known)
Custom printer with RRF, but I have the same problem also with another printer, with Klipper on board.

### Behavior
I noticed that first_layer_temperature is applied (now, but I don't know when start this behavior) only on the skirt, then all the first layer is printed at temperature_layer, and so on the rest of the print.
I think it's a mistake to setting new temperature after skirt, or not?

![Screenshot 2020-10-19 at 09 57 33](https://user-images.githubusercontent.com/40430435/96417440-96d0f800-11f1-11eb-8fe9-3671e484dd41.png)

![Screenshot 2020-10-19 at 10 02 55](https://user-images.githubusercontent.com/40430435/96418046-7bb2b800-11f2-11eb-8160-0e30616c6646.png)

![Screenshot 2020-10-19 at 10 05 24](https://user-images.githubusercontent.com/40430435/96418193-abfa5680-11f2-11eb-9c31-4d26d4f8da0e.png)

What could I check?
Regards.

**Comment by bigsubgit** [comment]
Here is more visible the temperature of first layer

![image](https://user-images.githubusercontent.com/40430435/96440843-cf300080-1208-11eb-80fc-79eff24c40c9.png)

**Comment by supermerill** [comment]
Thanks for the report.
But already reported fixed, and warned about in the release page. download the nighlty, or wait some days to let me correct other bugs.

**Comment by bigsubgit** [comment]
@supermerill many thanks and sorry if didn't check before.
