### ISSUE TITLE
Wrong calculation.

### ISSUE THREAD

**Issue by mmeulstee** [supermerill/SuperSlicer#586]
On the Print settings tab -> Perimeters & Shells theres a information part telling you: "recommended object etc etc,
I think the calculation is wrong for 1 Perimeter, because its saying 1 perimeter: 0,86.
With a 0.4 Nozzle, 0.2 Layer Height, Default Extrusion Width: 0.45.

Its just info so no rush

**Comment by supermerill** [comment]
A perimeter has to comes back.

**Comment by mmeulstee** [comment]
A perimeter is just 1 line right, ... just for me i'm trying to understand

**Comment by supermerill** [comment]
A perimeter is a loop.
It's a thin wall that as two dead end.
