### ISSUE TITLE
Filament start Gcode doesn't work

### ISSUE THREAD

**Issue by DevILLz** [supermerill/SuperSlicer#588]
### Operating system type + version
Win10 pro last update (2004 i guess)

### Behavior
Filament start Gcode doesn't work
  * _Screenshots from __*SuperSlicer*__ preview are preferred_
![image](https://user-images.githubusercontent.com/24200544/96593183-df6fda80-12f1-11eb-9804-0123e5103721.png)
![image](https://user-images.githubusercontent.com/24200544/96593201-e4348e80-12f1-11eb-9c87-a972cf654f87.png)
![image](https://user-images.githubusercontent.com/24200544/96593221-e991d900-12f1-11eb-9aae-c1b045abef9d.png)

it's only added in the end of gcode file

**Comment by supermerill** [comment]
Thanks for the report. I'm assuming it's the buggy 2.2.54.0 version.
But already reported (7 times) & fixed, and warned about in the release page. download the nightly, or wait some days to let me correct other bugs.
