### ISSUE TITLE
higher speed on external wall bridge than set

### ISSUE THREAD

**Issue by Coffee0297** [supermerill/SuperSlicer#589]
### Version
2.2.54

### Operating system type + version
Win 10

### Behavior
When slicing this model i get a higher speed on external wall when there is a bridge. Not sure where it gets that speed from bc its not a different feature. 
Layer time goal is set to 0 so should not be an issue.
![image](https://user-images.githubusercontent.com/43273303/96601630-80f72c00-12f2-11eb-8c69-5ce7703a855e.png)
![image](https://user-images.githubusercontent.com/43273303/96601650-85bbe000-12f2-11eb-85de-2e7cba9eba6e.png)

#### Project File (.3MF) where problem occurs
[Test cube 3030.zip](https://github.com/supermerill/SuperSlicer/files/5409401/Test.cube.3030.zip)

**Comment by supermerill** [comment]
that's your small_priemter_speed kick's in, set it to 50%, same as external.

**Comment by Coffee0297** [comment]
Allright, that makes sense, and i see you made it a label in the legend 👍 thanks!
