### ISSUE TITLE
Possible issue with No Perimeters On Bridge Areas

### ISSUE THREAD

**Issue by neophyl** [supermerill/SuperSlicer#593]
### Version
2.2.54.1 ( but looks same in 2.2.53 )

### Operating system type + version
Windows 10 64 bit

### 3D printer brand / version + firmware version (if known)
N/A

### Behavior
I am possibly not meeting some criteria correctly but no matter what option I select on the No Perimeters On bridge areas the slice doesn't appear to change.  Also changing the option doesn't trigger a re-slice button appearance.  I was nudging the part to get it to re-slice after changing the options.  I have tried ALL options on the dropdown.

I was expecting the counterbore hole in the part to be filled in for a layer as that's what the wiki description says when I have Fill the voids with bridges but maybe I have it set up wrong or I just don't understand what should be happening.

(Note -  the Ctrl-R shortcut or menu item also doesn't re-slice for me either, although that probably needs a separate issue opening)

#### Project File (.3MF) where problem occurs
[Remove Bridge Test.zip](https://github.com/supermerill/SuperSlicer/files/5422169/Remove.Bridge.Test.zip)

**Comment by supermerill** [comment]
That was a bad copy-paste that replaced a line by a botched counterpart. Also present in 2.2.53.3 but not in 2.2.53.2
