### ISSUE TITLE
monotonous crash the slicer

### ISSUE THREAD

**Issue by supermerill** [supermerill/SuperSlicer#597]
### Version
2.2.54.1

### Operating system type + version
win

### Behavior
when slicing darth-vader-bust-body-by-eastman.3mf with monotonous (filled) on bot & top, it crash.

**Comment by skellatore** [comment]
Doesn't seem to do it if you just use Monotonous just on the bottom layer

**Comment by Matts-Hub** [comment]
Also, setting infill to 100% with monotonous pattern selected causes a crash for me with any model

**Comment by supermerill** [comment]
If you can link the projects where it crahsh, currently i only have on and the object is very big. It's super slow to debug.

**Comment by Matts-Hub** [comment]
Sure thing, here it is. Just bump infill % up from 99 to 100 and it will crash
[x_end_idler.zip](https://github.com/supermerill/SuperSlicer/files/5450947/x_end_idler.zip)

**Comment by supermerill** [comment]
Seams like prusa has also discover and correct it.
Their patch for yesterday works well.
