### ISSUE TITLE
slic3r.dll was not loaded, error code: 126 Visual Studio 2019

### ISSUE THREAD

**Issue by userosos** [supermerill/SuperSlicer#604]
Hi! I use the manual for make dev-build for windows 10 (Noob guide (step by step)):
https://github.com/supermerill/SuperSlicer/blob/dev/doc/How%20to%20build%20-%20Windows.md
In step:
`Debug->Start Debugging or Debug->Start Without debugging PrusaSlicer should start. You're up and running! `
I can see cmd line with slic3r.dll was not loaded, error code: 126 Visual Studio 2019 error
I want make dev build. Maybe someone has already make this?

**Comment by supermerill** [comment]
you miss a dll. copy libgmp-10.dll and libmpfr-4.dll next to your exe.
