### ISSUE TITLE
Feature Request: Z-Lift Only on Top Layers

### ISSUE THREAD

**Issue by Matts-Hub** [supermerill/SuperSlicer#607]
With particularly stringy filaments, z lift makes the stringing even worse. I only use z-lift to stop scarring on top solid infill from the nozzle dragging across. For these reasons, it would be great if there was a tick box similar to what we already have for z lift "not on top", except this new feature would be "only on top"

**Comment by supermerill** [comment]
duplicate of #395, please use the other issue for commenting.
