### ISSUE TITLE
Maybe create Discord server?

### ISSUE THREAD

**Issue by cab404** [supermerill/SuperSlicer#611]
It would be nice to have a community hub around the best fork of the best slicer)

**Comment by wildjokerss** [comment]
I second this. Actually in the past I've been looking for it as I thought it already existed :D

**Comment by supermerill** [comment]
https://discord.gg/QaJj92

I may need some people willing to do the moderation stuff.

**Comment by cab404** [comment]
> https://discord.gg/QaJj92
> 
> I may need some people willing to do the moderation stuff.

I've pinged you about that. I'm cab.

**Comment by homewerken** [comment]
Is the discord Server still Open ?

**Comment by supermerill** [comment]
it can close?

**Comment by supermerill** [comment]
as some bots have discovered the previous link, here a new one.
It's only the key, you have to add the 'discord.gg' before it:

`Sb6pekEKQh`

**Comment by D-Dub24** [comment]
The link appears to be expired again.

**Comment by DatenThielt** [comment]
> https://discord.gg/ygBBdRRwJY
> 
> I may need some people willing to do the moderation stuff.

Read the messages above, there is a valid link that is just missing the discord.gg part, due to bots

**Comment by cab404** [comment]
updated the top comment, just so it's more obvious

**Comment by D-Dub24** [comment]
> > https://discord.gg/ygBBdRRwJY
> > I may need some people willing to do the moderation stuff.
> 
> Read the messages above, there is a valid link that is just missing the discord.gg part, due to bots

I figured it out, but when I asked on the Voron discord, someone told me, regardless of if I figured it out or not, the next person that comes along is going to probably do the same thing. So they told me to post the issue so it gets fixed so others do not make the same mistake.

Thank you for making it more obvious for us illiterate people.

**Comment by psi-4ward** [comment]
So do we have an discord? Seems all invites are expired

**Comment by cab404** [comment]
> So do we have an discord? Seems all invites are expired

I think the one in the top message should still be valid :\

**Comment by psi-4ward** [comment]
Es it's working. Thx.
Why not simply update the badge-button in README?

**Comment by vkhodygo** [comment]
@cab404 it's dead again

**Comment by Creo2005** [comment]
> @cab404 it's dead again

https://discord.gg/4TVUG4VRzP

**Comment by Creo2005** [comment]
> 

NO! 
just checked

**Comment by vkhodygo** [comment]
@Creo2005 
Bloody dicsord, it needs the app to be installed to handle the invite correctly.

**Comment by cab404** [comment]
> > 
> 
> NO! just checked

Open in a private browser link and report, please

**Comment by Creo2005** [comment]
> https://discord.gg/4TVUG4VRzP

![Снимок экрана 2023-07-22 в 21 05 01](https://github.com/supermerill/SuperSlicer/assets/10849149/2984eae3-5650-47df-a730-73c4023f5926)
sorry - screen in russian.
