### ISSUE TITLE
 Artifacts when XY-compensation and Holes compensation are enabled.

### ISSUE THREAD

**Issue by Slatkey** [supermerill/SuperSlicer#612]
### Version
2.2.54.2

### Operating system type + version
Windows 10 x64

### 3D printer brand / version + firmware version (if known)
Zav3D. Klipper firmware 0.9.1, mainsail interface.

### Behavior

![02](https://user-images.githubusercontent.com/63398258/97564291-69f0c200-19f5-11eb-968a-9b44a17ea577.jpg)
![01](https://user-images.githubusercontent.com/63398258/97564298-6bba8580-19f5-11eb-96b9-ab5ecfc006a5.jpg)

When the XY and / or hole size compensation functions are activated, artifacts appear on the model, which are then transferred to the printed model.

#### Project File (.3MF) where problem occurs

[side_fan_support_x2.zip](https://github.com/supermerill/SuperSlicer/files/5458108/side_fan_support_x2.zip)

**Comment by supermerill** [comment]
your zip is corrupted

**Comment by supermerill** [comment]
that's because of the hole.
for these layers, there is no more "internal" space.

1) Holes compensation isn't useful for this model, so you should deactivate it : it only apply to areas and layers where these big hexagon are.
2) If you need the xy compensation, set the same value for both outer & inner.

**Comment by Slatkey** [comment]
I was more worried about XY compensation, your advice to set the same value for internal and external did fix the problem! Thanks for the answer

**Comment by supermerill** [comment]
i'll update the tooltips to makes it more obvious.
