### ISSUE TITLE
Accelaration control "Default" based on printer settings

### ISSUE THREAD

**Issue by wildjokerss** [supermerill/SuperSlicer#614]
### Version
2.2.54

### Behavior
I often mess around with my acceleration and so on. The Acceleration control on the "print settings" is grayed out unless you set a default in there. Would be good I'd say to have a checkbox to "inherit" the acceleration from the printer settings, so whenever I mess the printer settings the print settings remain the same. 
Why am I asking this. All the other settings are grayed out without the Default one, however, I want to change only bridges to some way slower acceleration. The problem with setting a default there is that I might end up changing the Acceleration on printer settings and forget that I still have a different default.

![Screenshot_1](https://user-images.githubusercontent.com/72793424/97625303-3e370180-1a20-11eb-8fc4-2c8fe6523b4e.png)

This is indeed a feature request :D Let me know if I can clarify this any better :)

**Comment by supermerill** [comment]
i can set it as a mm/s² or % ?

**Comment by wildjokerss** [comment]
well yeah, that would be quite dope too! setting % based on printer settings acceleration

**Comment by supermerill** [comment]
I'm using the max of the x/y max, or the min of the max ?
min should be safer.

**Comment by wildjokerss** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/72793424/97631268-9b36b580-1a28-11eb-92d0-562fd247d8e5.png)
I would suggest the printing and not the maximum @supermerill, I believe it would be a better, safer idea. Maximum could be there for travel purposes for example

**Comment by wildjokerss** [comment]
So, to clarify, the Default acceleration on the print profile, expressed as a percentage, would grab data from the "Maximum acceleration when extruding"
