### ISSUE TITLE
wiki documentation fix - FreePySCAD script window

### ISSUE THREAD

**Issue by matthewfallshaw** [supermerill/SuperSlicer#615]
### Behavior

_Problem_  
**how to write python code** example does not work. It produces an error (below).

_Steps needed to reproduce the problem_  

1. Generate > FreeCad python script
2. Enter the `uni = …` example from the wiki

_Expected Results_  
Generate a 4×10×1 cuboid.

* _Actual Results_  
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 3
    for pos in range(0,4) :
    ^
SyntaxError: invalid syntax

Error, no object generated.
```

_Suggested Fix_  
Change references to `redraw` into `scene().redraw`. Diff follows.

<pre><code>
diff --git a/FreePySCAD-script-window.md b/FreePySCAD-script-window.md
index d6a3a98..badc320 100644
--- a/FreePySCAD-script-window.md
+++ b/FreePySCAD-script-window.md
@@ -14,13 +14,13 @@ Each object at root level will create an object in the platter.
 All available functions are documented [here](https://github.com/supermerill/FreePySCAD)
 ## how to write python code
 As it's a python script, you can also write plain python function, object and loops.
-But to be able to do that, you have to say what portion of the code is the object collection and what is the python code. This is done with the redraw() function.
+But to be able to do that, you have to say what portion of the code is the object collection and what is the python code. This is done with the scene().redraw() function.
 Example:
 ```
 uni = union("lines")
 for pos in range(0,4) :
     uni.add( cube(1,10,1).move(x=pos) )
-redraw(
+scene().redraw(
   uni
 )
 ```
</code></pre>

(I also humbly suggest changing `.move(x=pos)` to `.move(x=2*pos)` so that the generated code has clearly created four lines, matching the loop, instead of creating one block, which may be harder for some readers to follow.)

**Comment by supermerill** [comment]
done.
I though i had created a little function to automatically add the scene(). before the redraw...
not that a big of a deal.
