### ISSUE TITLE
Polyholes - Unexpected number of vertices

### ISSUE THREAD

**Issue by Matts-Hub** [supermerill/SuperSlicer#623]
### Version
Version 2.2.53

### Operating system type + version
Windows 10

### Behavior
I just came across this feature and I'm very excited to try it out.
When using the polyholes feature, the number of vertices in the generated polyholes is lower than expected.

According to the code, n = max(round(2 * hole diameter * 0.4 / nozzle diameter), 3).
With nozzle diameter set to 0.4, I am getting half the number of vertices than what I would expect, for example an 8mm hole is giving 8 vertices, 5mm hole is giving 5 vertices etc.

![Screenshot 2020-11-02 181519](https://user-images.githubusercontent.com/26502465/97840362-f376fb80-1d37-11eb-8711-122274568e0c.png)

Setting nozzle diameter to 0.2mm creates the expected number of vertices (two times what is shown above).

Also as you can see in the image, the polyhole is not being generated on the first layer due to my -0.1mm XY compensation on the first layer.

#### Project File (.3MF) where problem occurs

[polyholes.zip](https://github.com/supermerill/SuperSlicer/files/5473286/polyholes.zip)

**Comment by supermerill** [comment]
found the problem in the code:

`float radius = diameter / 1`
