### ISSUE TITLE
Positionning Error before wipe tower brim

### ISSUE THREAD

**Issue by elpopo-eng** [supermerill/SuperSlicer#629]
### Version
 2.2.54.0

### Operating system type + version
Windows 10x64

### 3D printer brand / version + firmware version (if known)
Voron 2.4 with Klipper 0.9.1

### Behavior
When using susie in multi extruder in single extruder multi material mode the gcode generated before the wipe tower has an error. There is G1 very far on x see line 706 of gcode.

#### Project File (.3MF) where problem occurs
[WipeTower_Error.zip](https://github.com/supermerill/SuperSlicer/files/5479967/WipeTower_Error.zip)

**Comment by supermerill** [comment]
Seems like it's fixed in the 2.3, so will be fixed for the 2.3.55 release.
