### ISSUE TITLE
Superslicer not applying bridge fan speeds properly

### ISSUE THREAD

**Issue by pheonix3330** [supermerill/SuperSlicer#630]
### Version
Version 2.2.53.3 and 2.2.54.2

### Operating system type + version
Windows 10 64 bit

### 3D printer brand / version + firmware version (if known)
Voron V1.8 and Klipper Firmware (default Voron profile in SS)

### Behavior
Superslicer is not applying bridge fan speeds to certain bridges resulting in poor bridge performance. I verified the behavior in both 2.2.53.3 and 2.2.54.2. In both versions, the bridging looks like this:

![image](https://user-images.githubusercontent.com/62308091/97993160-ae8fab00-1db1-11eb-8628-8b58ee3d0982.png)
 
even though Superslicer is properly identifying this section as a bridge:

![image](https://user-images.githubusercontent.com/62308091/97993221-c36c3e80-1db1-11eb-9787-b359228e6b45.png)

In Prusaslicer 2.2.0, the same model looks like this:

![image](https://user-images.githubusercontent.com/62308091/97993340-eeef2900-1db1-11eb-8236-e58a4d9d3fc9.png)

![image](https://user-images.githubusercontent.com/62308091/97993387-0201f900-1db2-11eb-9469-a0103202c546.png)

Just to confirm, I set up a "bridge flow calibration" print in Superslicer to make sure that bridge fan speed was being set correctly there and it was:

![image](https://user-images.githubusercontent.com/62308091/97995772-f49a3e00-1db4-11eb-8f9b-c71bb7189ca2.png)

![image](https://user-images.githubusercontent.com/62308091/97995804-ffed6980-1db4-11eb-841f-dbb010ed81c7.png)

#### Project File (.3MF) where problem occurs
[AB-BN-5015-BlowerFront-24.zip](https://github.com/supermerill/SuperSlicer/files/5481630/AB-BN-5015-BlowerFront-24.zip)

EDIT: Just checked in the latest Prusaslicer 2.3 Alpha and the bridging is working correctly there so seems to be a Superslicer specific issue.

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/98127614-301d3100-1eb7-11eb-8003-0b62a309a990.png)

will be fixed in 2.3.55
