### ISSUE TITLE
Wrong chronology preview

### ISSUE THREAD

**Issue by Yordan1976** [supermerill/SuperSlicer#631]
### Version
_Version of SupserSlicer used goes here, Use `About->About SuperSlicer`_
2.2.54

### Operating system type + version
_What OS are you using (and version)_
Win 10 Pro

When I use sequential printing / Complete individual objects the chronology preview doesn't reflect this. 
Maybe it is related to this issue, that the remaining time to completition in OctoPrint is also wrong until it reaches the last object.

![ScreenShot 362 ](https://user-images.githubusercontent.com/35901879/97999492-ad7b6f80-1deb-11eb-806a-211929ea8329.jpg)

**Comment by supermerill** [comment]
It's revamped in the next version with the new prusa gcode-viewer, I'll check if it stay that way.

**Comment by supermerill** [comment]
It's fixed in the 2.3.55 version
