### ISSUE TITLE
Only one perimeter on top - Is this the way it should work?

### ISSUE THREAD

**Issue by thierryzoller** [supermerill/SuperSlicer#633]
### Version
Latest "re-repetier version"

Is this supposed to happen on a cube with 2 perimeters ? Airing on the side caution and reporting this. May be as designed.

![image](https://user-images.githubusercontent.com/958490/98164868-3aeeba80-1ee5-11eb-9fca-6e3811e83589.png)

**Comment by supermerill** [comment]
no
![image](https://user-images.githubusercontent.com/6536403/98165798-c6b51680-1ee6-11eb-8b72-9547b12c9212.png)

**Comment by thierryzoller** [comment]
`unless you have a simple cube and removed all infill & top infill`

That's exactly what I have.

**Comment by supermerill** [comment]
You have an empty top infill, but you keep it.
