### ISSUE TITLE
Complete individual Objects -> too tall

### ISSUE THREAD

**Issue by Yordan1976** [supermerill/SuperSlicer#634]
I don't know, if it is a bug or if I am just expecting another behavior.

### Version
2.2.54
### Operating system type + version
Win10 Pro

### 3D printer brand / version + firmware version (if known)
Caribou MK3s 320 (similar to Prusa MK3s)

### Behavior
The extruder clearance settings are radius=45 and height=20

My expectation is, that objects should be printable individually if they max 20mm high (not the case here) OR outside the radius, especially on the y-axis (which is the case here). If the object on the back is completed first, the will be no crash when printing the object on the front. Or am I missing something?

![ScreenShot 250 Kleiderstangenhalter - SuperSlicer_2 2 54 based on PrusaSlicer   Slic3r](https://user-images.githubusercontent.com/35901879/98165206-c405f180-1ee5-11eb-9b05-f465b02d68a8.png)

**Comment by supermerill** [comment]
The slicer doesn't know how your printer is built.
If you're sure there is no problem, then put a big value in z clearance for this print.

**Comment by Yordan1976** [comment]
Ok, how will it move to the next object? x/y first, z when in place?

**Comment by supermerill** [comment]
yes

**Comment by Yordan1976** [comment]
Ok, thanks!
