### ISSUE TITLE
-2,147,483,647

### ISSUE THREAD

**Issue by capter987** [supermerill/SuperSlicer#635]
this is not a major bug but its wierd 
![image](https://user-images.githubusercontent.com/73920413/98183824-007e2100-1ed7-11eb-9109-a40100462c00.png)

the print time is bugged

**Comment by neophyl** [comment]
#364 #437

**Comment by thierryzoller** [comment]
@capter987 : Have you overwritten your SuperSlicer installs with the newest Zip file? If yes, can you try to cleanly install into a new folder and work with that version and tell us whether it reproduces?
