### ISSUE TITLE
Defect: Slicing does not seem to work with MMU, stuck in negative flow message.

### ISSUE THREAD

**Issue by kursatu** [supermerill/SuperSlicer#639]
### Version
_Version of SupserSlicer used goes here, Use `About->About SuperSlicer`_
Latest release
### Operating system type + version
_What OS are you using (and version)_
Windows
### 3D printer brand / version + firmware version (if known)
_What 3D printer brand / version are you printing on, is it a stock model or did you modify the printer, what firmware is running on your printer, version of the firmware #s_

### Behavior
* _Describe the problem_
Slice the attached project file
Observe the error
Change one model to use the same extruder.
The problem goes away
All width settings are set to 0, changing them does not help to avoid the defect.
![Defect13_1](https://user-images.githubusercontent.com/1686475/98326778-deec6a80-1fa6-11eb-8a98-67313e2b6481.png)

* _Steps needed to reproduce the problem_
  * _If this is a command-line slicing issue, include the options used_
* _Expected Results_
* _Actual Results_
  * _Screenshots from __*SuperSlicer*__ preview are preferred_

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_
[Defect13.zip](https://github.com/supermerill/SuperSlicer/files/5499117/Defect13.zip)

**Comment by supermerill** [comment]
I computed the wipe tower brim in an unsafe way.
I'll fix that.
in the meantime, you can set a width for the the first layer instead of 0.

**Comment by kursatu** [comment]
The attached .3mf file did not show the reported problem, pulled and built with the latest sources on github.
