### ISSUE TITLE
External Perimeter produces slight overhang on rounded surfaces (?)

### ISSUE THREAD

**Issue by thierryzoller** [supermerill/SuperSlicer#640]
### Version
Latest

Airing on the side of caution and reporting this.
[Wave Square.zip](https://github.com/supermerill/SuperSlicer/files/5502151/Wave.Square.zip)

**TOP View**
![image](https://user-images.githubusercontent.com/958490/98386143-23801080-2050-11eb-883b-6a333f398c90.png)

**BOTTOM VIEW**
![image](https://user-images.githubusercontent.com/958490/98386274-401c4880-2050-11eb-9168-20e3bfc786e3.png)

**Comment by supermerill** [comment]
change 'thin wall' -> 'min width' to 100% and it should go away.

**Comment by thierryzoller** [comment]
It's better but not gone 
![image](https://user-images.githubusercontent.com/958490/98395876-2c2b1380-205d-11eb-889f-99c8df120528.png)

**Comment by supermerill** [comment]
I set it to 100 and i can see the change.

**Comment by thierryzoller** [comment]
I made you a video of it not working 


[b3cf0f82-8494-4269-af21-14fed9b4d562.zip](https://github.com/supermerill/SuperSlicer/files/5510438/b3cf0f82-8494-4269-af21-14fed9b4d562.zip)

**Comment by thierryzoller** [comment]
> I set it to 100% and i can see the change.

I downloaded your example and still see the overalp, I believe you might be looking at another place.

**Comment by supermerill** [comment]
or maybe you're not at the version i am.

**Comment by supermerill** [comment]
my video, on 2.2.54.2:
https://mega.nz/file/d0pSiDyS#SAhv3yuGIlHenV4aIpnMfCAMYITVxHzsmiIG5fhg6LY

**Comment by thierryzoller** [comment]
Are there any other settings not included in the 3MF that would somehow influence this behaviour? I can't explain it otherwise

**Comment by supermerill** [comment]
all settings are in the .3mf

**Comment by thierryzoller** [comment]
What I did in the past was that I overwrote each new SS release with a new one. So I did delete the folder and cleany unziped the release. Problem solved.  It seems that for whatever reason (maybe it didn't overwrite every file, or used an older version) I was running a problematic version.

**Problem solved through clean re-install.**
