### ISSUE TITLE
Top solid infill not detected

### ISSUE THREAD

**Issue by toskium** [supermerill/SuperSlicer#641]
### Version
SuperSlicer 2.2.54.2

### Operating system type + version
Windows 10 Pro

### 3D printer brand / version + firmware version (if known)
Klipper 0.90
DIY delta printer

### Behavior
Superslicer does sometimes not detect top solid infill in gcode preview.
![image](https://user-images.githubusercontent.com/15872792/98439037-12d2a780-20ef-11eb-8ef8-7bf71fefa55c.png)

The parts are manifold and I can not spot an obvious reason for its behaviour.

#### Project File (.3MF) where problem occurs
[top_infill_issue.zip](https://github.com/supermerill/SuperSlicer/files/5504599/top_infill_issue.zip)

**Comment by supermerill** [comment]
seems fixed in the next 2.3.55 version

**Comment by toskium** [comment]
alright, will check on the next version!
