### ISSUE TITLE
Brim failing

### ISSUE THREAD

**Issue by Tinchus2009** [supermerill/SuperSlicer#650]
### Version
latest stable

### Operating system type + version
win

### 3D printer brand / version + firmware version (if known)
custom made coreXY
### Behavior
I have been printing tests and leanring supersilcer new features, definitly this is one of the best finds I have done in terms of slicing, super thanks for this great version.
During tests, I print a lot of ABS, im suffering of warpings and I have just noticed the reason. Not exactly in the example Im showing in the capture because it is just a test of my new dual material profile, but it shows the problem: when you have a model that needs supports, regardless if it is soluble or not, when you activate the brim to help with the warping, if there is support around the object, the brim is not created around the object but around the support, and makes the brim useless.
The proper behaviour I think would be the brim to be created and support to be createn on the second layer on top of the brim.

![wrong_brim](https://user-images.githubusercontent.com/14299602/98733879-f7320000-237f-11eb-957b-f4f3367eccf3.png)

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/98734646-90720e00-23a2-11eb-9ebc-728528d1ae56.png)

**Comment by Tinchus2009** [comment]
I tried that option, but the result is a solid initial layer but not conected to the object. Look at this picture, it has that option activated. The red square i the center is the object, then you can see the support, solid layer in green and then the brim surrounding the support layer. And even with this option, take a lok at the separation between the solid layer and the object.
![not_connected](https://user-images.githubusercontent.com/14299602/98748183-eb523800-2397-11eb-9382-fdcd85f3443b.png)

**Comment by supermerill** [comment]
oh, right.

**Comment by bung69** [comment]
A hacky temporary fix is to use the "Brim Ears" option with the max angle set to 180deg

However this causes the support's raft to be printed inside the brim which could cause a bit of a mess / nozzle build up.

IMO the raft under support should just be out right disabled and instead allow independently configurable top and bottom support interface layers.  

![support brim raft](https://user-images.githubusercontent.com/55783483/99506423-a55b2c80-29b4-11eb-842d-da934207b92b.PNG)
