### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by kursatu** [supermerill/SuperSlicer#653]
### Version
Pulled the sources to the latest , ie. commit a44039c3
### Operating system type + version
Windows 10
### Behavior
* _Describe the problem_
I was building before this pull both via commandline and from within VS.
Followed the steps https://github.com/supermerill/SuperSlicer/blob/master/doc/How%20to%20build%20-%20Windows.md#how-to-build
The build always fails with the following for both Release and Debug
       "C:\Users\kursa\Documents\GitHub\SuperSlicer.1\build\INSTALL.vcxproj" (default target) (1) ->
       (PostBuildEvent target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.ta
       rgets(153,5): error MSB3073: The command "setlocal [C:\Users\kursa\Documents\GitHub\SuperSlicer.1\build\INSTALL.
       vcxproj]
After  these failure, the VS project is not usable, it just does not build, it always succeeds. 
All the subprojects are marked as incompatible.
Strangely, the executables are generated via command line, but they don't run. They seem to exit immediately.
Since I can't even debug, I can't trace the problem at all.

There is also an error in the documentation. The line should read this, otherwise cmake does not run.
cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH="PATH_TO_SuperSlicer\deps\build\destdir\usr\local"

  * _Screenshots 
![Defect14](https://user-images.githubusercontent.com/1686475/98770615-7d0d7580-2397-11eb-8cd3-dc68a4a5a31b.png)

**Comment by supermerill** [comment]
thanks you for the fix for the doc.
I have no problem building it with widows10x64 from a clean fresh clone, on my computer and in the continous integration server.

**Comment by supermerill** [comment]
oh, it seems that the windows build has a problem and create a SuperSlicer.dll instead of a slic3r.dll, you may have to rename it until i correct it.

**Comment by kursatu** [comment]
I've created a symlink , otherwise development would be hard.
mklink slic3r.dll SuperSlicer.dll

**Comment by kursatu** [comment]
Closing this, there is a workaround and another defect filed for it.

**Comment by supermerill** [comment]
now it should use the SuperSlicer.dll, doesn't need to rename.
