### ISSUE TITLE
Unable to locate in SuperSlicer where to put gcode for purge bucket for multiprinting.

### ISSUE THREAD

**Issue by fatdaddypaul** [supermerill/SuperSlicer#655]
### Version
2.2.53

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Custom bult printers was geetech a10m

Current code in cura is like this:
; Start Extruder 1
M104 T0 S{material_print_temperature} ;set hotend temperature
G1 X-7 F6000 ; Go to X=-7
G92 E0 ; Reset extrusion distance on new tool
G1 E105 F300 ; Extrude 100 mm
G92 E0 ; Set current extruder position to 0mm
G0 F10000 ; Increase feed rate before next travel.
G1 E-1 F1000
; End Extruder 1
G91 ; Switch to relative positioning
G1 E-5 F600
G1 Z10 F1000 ; Lift nozzle by 10 mm
G90 ; Return to absolute positioning
G1 X-7 F6000
G1 E-60 F300; Retract 65 mm
G92 E0 ; Reset extrusion distance on old tool

; Start Extruder 2
M104 T1 S{material_print_temperature} ;set hotend temperature
G1 X-7 F6000 ; Go to X=-7
G92 E0 ; Reset extrusion distance on new tool
G1 E105 F300 ; Extrude 100 mm
G92 E0 ; Set current extruder position to 0mm
G0 F10000 ; Increase feed rate before next travel.
G1 E-1 F1000
; End Extruder 2
G91 ; Switch to relative positioning
G1 E-5 F600
G1 Z10 F1000 ; Lift nozzle by 10 mm
G90 ; Return to absolute positioning
G1 X-7 F6000
G1 E-60 F300; Retract 65 mm
G92 E0 ; Reset extrusion distance on old tool

**Comment by supermerill** [comment]
* filament ->end_filament_gcode is printed
* printer -> custom gocde -> toolchange_gcode is printed, 
* the `TX` is printed
* the filament ->start_filament_gcode is printed
[in custom gocde, you can access the special variables](https://github.com/prusa3d/PrusaSlicer/wiki/Slic3r-Prusa-Edition-Macro-Language) next_extruder, previous_extruder, * layer_num, layer_z and all the normal ones

**Comment by fatdaddypaul** [comment]
I wrote this code but missing something =, it retracts the previous_extruder, but does not prime the next_extruder.
[previous_extruder]
M104 T[previous_extruder] S[first_layer_temperature] ;set hotend temperature
G91 ; Switch to relative positioning
G1 E-5 F600
G1 Z10 F1000 ; Lift nozzle by 10 mm
G90 ; Return to absolute positioning
G1 X-7 F6000
G1 E-60 F300; Retract 65 mm
G92 E0 ; Reset extrusion distance on old tool

[next_extruder]
M104 T[next_extruder] S[first_layer_temperature] ;set hotend temperature
G1 X-7 F6000 ; Go to X=-7
G92 E0 ; Reset extrusion distance on new tool
G1 E105 F300 ; Extrude 100 mm
G92 E0 ; Set current extruder position to 0mm
G0 F10000 ; Increase feed rate before next travel.
G1 E-1 F1000

**Comment by supermerill** [comment]
your [next_extruder] gcode isn't printed?

**Comment by fatdaddypaul** [comment]
My code when sliced produces this in the gcode..
M104 T-1 S215 ;set hotend temperature
G91 ; Switch to relative positioning
G1 E-5 F600
M73 P0 R78
G1 Z10 F1000 ; Lift nozzle by 10 mm
G90 ; Return to absolute positioning
G1 X-7 F6000
G1 E-60 F300; Retract 65 mm
G92 E0 ; Reset extrusion distance on old tool

0
M104 T0 S215 ;set hotend temperature
G1 X-7 F6000 ; Go to X=-7
G92 E0 ; Reset extrusion distance on new tool
G1 E105 F300 ; Extrude 100 mm
G92 E0 ; Set current extruder position to 0mm
G0 F10000 ; Increase feed rate before next travel.
G1 E-1 F1000

**Comment by fatdaddypaul** [comment]
My extruders are T0 and T1.

**Comment by supermerill** [comment]
to avoid to write the custom gcode whne the exruder isn't here yet (-1) if the if:

```
{if previous_extruder >= 0}
M104 T[previous_extruder] S[first_layer_temperature] ;set hotend temperature
G91 ; Switch to relative positioning
G1 E-5 F600
G1 Z10 F1000 ; Lift nozzle by 10 mm
G90 ; Return to absolute positioning
G1 X-7 F6000
G1 E-60 F300; Retract 65 mm
G92 E0 ; Reset extrusion distance on old tool
{endif}
```

There is something else that is not right? (if yes, please write the expected gcode vs the one you have nd your custom gcode, or even better: your zipped project file)
