### ISSUE TITLE
How to print with 2 temperature?

### ISSUE THREAD

**Issue by skink32** [supermerill/SuperSlicer#656]
### Version
????

### Operating system type + version
????

### 3D printer brand / version + firmware version (if known)
Tenlog TL-3D Pro

### Behavior
where can I set the temperature values in the Super Slicer for extruders 1 and 2? 
I wish to print with 2 different temperatures.

#### Project File (.3MF) where problem occurs
????

**Comment by supermerill** [comment]
you set the temperature in the filament.
you can duplicate your filament, and set an other temp into the is new one.
then affect the filament to the extruder in the right panel
![image](https://user-images.githubusercontent.com/6536403/98848522-22851f80-2452-11eb-8542-1a32ac0e31aa.png)
