### ISSUE TITLE
Label of the edit box 'large thumbnail' is not correctly positioned

### ISSUE THREAD

**Issue by elpopo-eng** [supermerill/SuperSlicer#658]
### Version
2.3.55.0

### Operating system type + version
Win10

### 3D printer brand / version + firmware version (if known)
N/A

### Behavior
Label of the edit box 'large thumbnail' is not correctly positioned
![image](https://user-images.githubusercontent.com/68954733/98860219-9da30180-2463-11eb-92e4-0e74231cd46d.png)

#### Project File (.3MF) where problem occurs
N/A

**Comment by Nandox7** [comment]
Same happens in OSX version.
