### ISSUE TITLE
External perimeters cutting off

### ISSUE THREAD

**Issue by TD5023** [supermerill/SuperSlicer#659]
### Version
2.3.55

### Operating system type + version
Win 10

### 3D printer brand / version + firmware version (if known)
N/A

### Behavior
In the newest update, there are points where the external perimeter does not connect, leaving gaps to the internal perimeter. As far as I can see, all of the internal perimeters complete full loops as expected. I have not done a print, but loading into a separate gcode viewer shows that it is definitely a code issue and not just a visual error in SS. I'm not sure if it's just a setting issue on my end, but since I imported an old working config file and only adjusted the new settings, I don't think that's the case. It actually appears that instead of completing the loop, the extruder doubles back over itself.

<img width="168" alt="external 1" src="https://user-images.githubusercontent.com/55936565/98875770-81429d00-2442-11eb-86c0-f83df35bb492.PNG">
<img width="330" alt="external 2" src="https://user-images.githubusercontent.com/55936565/98875772-81db3380-2442-11eb-9cac-be0c3c2185f0.PNG">
<img width="270" alt="external 3" src="https://user-images.githubusercontent.com/55936565/98875774-81db3380-2442-11eb-8a62-71d4915d4416.PNG">

#### Project File (.3MF) where problem occurs
[external perimeter issue.zip](https://github.com/supermerill/SuperSlicer/files/5527353/external.perimeter.issue.zip)

**Comment by supermerill** [comment]
That's the cooling fan speed-up time, that cut the perimeter in a wrong way. set it to 0 to deactivate it.

**Comment by TD5023** [comment]
Thanks! That fixed the problem for me since I don't care about running a different fan speed on the outer layers. Wouldn't this be a bug for the people who do, though?
