### ISSUE TITLE
BUG Support incorrectness

### ISSUE THREAD

**Issue by karabas2011** [supermerill/SuperSlicer#661]
### Version
2.2.54

### Operating system type + version
Win8

### 3D printer brand / version + firmware version (if known)
marlin

### Behavior
Support bridges no matter  on or off "Dont support bridges"
Support goes through walls of model !!!

#### Project File (.3MF) where problem occurs
![ss2](https://user-images.githubusercontent.com/2634978/98921857-d1713c00-24e2-11eb-8ca5-dbcce51e1fec.jpg)
![ss1](https://user-images.githubusercontent.com/2634978/98921864-d33aff80-24e2-11eb-9b39-bea18c21805b.jpg)

_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_

**Comment by karabas2011** [comment]
[ss.zip](https://github.com/supermerill/SuperSlicer/files/5529534/ss.zip)

**Comment by supermerill** [comment]
You may want to increase the XY separation a tad.

**Comment by karabas2011** [comment]
5mm
![ss3](https://user-images.githubusercontent.com/2634978/98967717-dd2e2400-251d-11eb-83a5-2b82219cfc38.jpg)

**Comment by supermerill** [comment]
There are overhangs, and these are not considered as bridges, i think that's your problem. Ideally, it should detect that your overhangs are strait and so should be considered as bridges, but there is nothing in the software currently for that.

OS if it's what you ask for, it's a new feature/improvement to create.
