### ISSUE TITLE
Latest nightly won't start

### ISSUE THREAD

**Issue by 1N4148** [supermerill/SuperSlicer#664]
### Version
Latest nightlies

### Operating system type + version
Windows 10 H2 64bit

### 3D printer brand / version + firmware version (if known)
Creality Ender 3/5

### Behavior
>superslicer_console.exe
create settings  print.ui
No overhangs_width_speed in ConfigOptionsGroup config, tab print.ui.
No seam_angle_cost in ConfigOptionsGroup config, tab print.ui.
No seam_travel_cost in ConfigOptionsGroup config, tab print.ui.
No hole_size_threshold in ConfigOptionsGroup config, tab print.ui.
No infill_connection in ConfigOptionsGroup config, tab print.ui.
No ironing in ConfigOptionsGroup config, tab print.ui.
No ironing_type in ConfigOptionsGroup config, tab print.ui.
>

**Comment by supermerill** [comment]
delete slic3r.dll, rename superslicer.dll to slic3r.dll

**Comment by 1N4148** [comment]
Ok, now it's working 👍

**Comment by kursatu** [comment]
I've created a symlink via the command below, otherwise development would be hard.
mklink slic3r.dll SuperSlicer.dll

**Comment by kursatu** [comment]
I've verified and found this to be working, no need to rename nor create a symlink.
This is done by pulling and building the latest sources on GitHub.
