### ISSUE TITLE
Z-Seam position settings (Question)

### ISSUE THREAD

**Issue by LordMelkor** [supermerill/SuperSlicer#667]
### Version
2.3.55

### Operating system type + version
Windows 10 Pro

### 3D printer brand / version + firmware version (if known)
PRUSA i3 MK3S

### Behavior
![image](https://user-images.githubusercontent.com/6434954/99119118-bd066f80-25c6-11eb-887d-b9dc1b26c431.png)

Sharpest corner is no longer an option for z-seam position. How can I replicate that functionality with the "Cost-based" parameters?

**Comment by supermerill** [comment]
You have to use 100% angle cost and 20% travel cost.

if you want earest, you should use 100% angle cost and 100% travel cost

**Comment by Really01101001** [comment]
"cost" based z seam location? Seriously? What's wrong with user defined coordinates location for z seam/layer start location? Just trying to make producing excellent prints harder than it needs to be?
