### ISSUE TITLE
Standby temperatures

### ISSUE THREAD

**Issue by Tinchus2009** [supermerill/SuperSlicer#674]
### Version
latest stable 2.2.53

### Operating system type + version
win10
### 3D printer brand / version + firmware version (if known)
custom corexy reprapfirmeare

### Behavior
I have just downloaded latest version and generated a code (calibration of offsets)
And this behaviour just happened: there a a standby temperatures added to the begining of the gcde, and I dont know where they are coming from

G10 P0 R200 S240 ; sets the standby temperature
G10 P1 R200 S240 ; sets the standby temperature

[nozzle_vernier_fixed_large.zip](https://github.com/supermerill/SuperSlicer/files/5552462/nozzle_vernier_fixed_large.zip)

[test_calibration.zip](https://github.com/supermerill/SuperSlicer/files/5552468/test_calibration.zip)

**Comment by supermerill** [comment]
that's because you're using reprapfirmware and have a multi-extruder setup.
something is wrong with these gcodes?

**Comment by Tinchus2009** [comment]
ok. then it might be another problem, if you take a look at the project file: toolchange temperature enabled was not activated, so I though those configuration option wouldnt affect the gcode.

**Comment by supermerill** [comment]
yes, now that switch is taken in account

**Comment by bsjoelund** [comment]
I can not get rid of this  line   G10 P0 R225
W10
SS 2.5.59
Reprap   Only one toolhead T1
