### ISSUE TITLE
Q modified gcode at the beginning ?

### ISSUE THREAD

**Issue by balloni55** [supermerill/SuperSlicer#675]
### Version
2.2.53

### Operating system type + version
WIN10 64

### 3D printer brand / version + firmware version (if known)
Anycubic I3 mega, Marlin 1.1.9

### Behavior
I have only been using SuperSlicer for a short time, so sorry

10 days ago i got another gcode when i slice the identical .stl , this process i like better and want it back.
Unfortunately I could not discover what I have changed by mistake.

thank you for the help
![gcode](https://user-images.githubusercontent.com/73615599/99387309-0ced7b00-28d4-11eb-86d6-b744bc2e56c0.png)

**Comment by supermerill** [comment]
seems like you changed your start_gcode (printer-> custom gcode -> start)

**Comment by balloni55** [comment]
i think it´s default, isn´t it?
![Start](https://user-images.githubusercontent.com/73615599/99389913-0e20a700-28d8-11eb-8193-5a07397a5701.png)

**Comment by supermerill** [comment]
if you want your gcode to start with 
```
M190 S65
M109 S200
G28
G1 Z5 F5000
```
you can copy-paste
```
M190 S[first_layer_bed_temperature] ; set and wait for bed temp
M109 S[first_layer_temperature] ; set and wait for extruder temp
G28 ; home all axis
G1 Z5 F5000
```

**Comment by balloni55** [comment]
Thanks for your help, this work
