### ISSUE TITLE
Print color

### ISSUE THREAD

**Issue by Zulaner** [supermerill/SuperSlicer#677]
### Version
2.3.55

The object is not appearing with the colors I put on the M600

![image](https://user-images.githubusercontent.com/38788588/99398275-1e3a8580-28dc-11eb-8264-21615d61c869.png)

**Comment by supermerill** [comment]
can you post your project file? (flie -> save as, put it here in a zip)

**Comment by Zulaner** [comment]
[Shape-Box.zip](https://github.com/supermerill/SuperSlicer/files/5554873/Shape-Box.zip)
