### ISSUE TITLE
SuperSlicer uses smaller area for bridges than PrusaSlicer 

### ISSUE THREAD

**Issue by carloshespanhol** [supermerill/SuperSlicer#678]
### Version
2.3.55

### Operating system type + version
Ubuntu 20.04

### 3D printer brand / version + firmware version (if known)
Hypercube - Klipper

### Behavior
SuperSlicer 2.3.55 uses smaller area for bridges than PrusaSlicer 2.3.0-alpha3
IMHO  bigger area helps bridging

PrusaSlicer 2.3.0-alpha3:
![prusaslicer](https://user-images.githubusercontent.com/51170706/99402267-e9bcce80-28c7-11eb-9be2-3d6aef951701.png)

SuperSlicer 2.3.55:
![superslicer](https://user-images.githubusercontent.com/51170706/99402285-f04b4600-28c7-11eb-9a2e-a5f55334489c.png)

**Comment by supermerill** [comment]
set infill -> advanced -> anchor solid infill by Xmm -> bridged to 3 to replicate prusa values

**Comment by carloshespanhol** [comment]
In a simple bridge it works, but not in this case. I attached the stl file.

What I find confusing is that you said to change "anchor solid infill"  but the color is of bridge and not solid infill, it's not intuitive.

stl file compacted
[hole_bridge.zip](https://github.com/supermerill/SuperSlicer/files/5560115/hole_bridge.zip)

**Comment by supermerill** [comment]
can't reproduce
![image](https://user-images.githubusercontent.com/6536403/99534816-4e4f5a80-29a8-11eb-8899-f1605654a8ba.png)

maybe export your project fie?

**Comment by carloshespanhol** [comment]
I found my error. I have set "No perimeters on bridge area" just disabled it and worked.
Thanks for your help.

**Comment by Hywelmartin** [comment]
I can't get the "slab" back in my part..
![bild](https://user-images.githubusercontent.com/33714214/101681438-6f184680-3a62-11eb-94fa-f98f6255630a.png)

![bild](https://user-images.githubusercontent.com/33714214/101681340-4d1ec400-3a62-11eb-9ec0-3b3d09d35bfd.png)

![bild](https://user-images.githubusercontent.com/33714214/101681389-5c9e0d00-3a62-11eb-81eb-73872257a6ae.png)

**Comment by supermerill** [comment]
infill -> anchor -> bridge

**Comment by Hywelmartin** [comment]
Doesn't work.. there must be some setting I'm screwing up.. cant get rid of the perimiters around the "slab"
[magic_bridge.zip](https://github.com/supermerill/SuperSlicer/files/5674797/magic_bridge.zip)

**Comment by supermerill** [comment]
maybe because of the buggy 'one peri on top' that plague the 2.3.55
reopen if the error persist.
