### ISSUE TITLE
Mac OS 2.2.53 error on generate calibration model

### ISSUE THREAD

**Issue by vvhh2002** [supermerill/SuperSlicer#687]
### Version
2.2.53

### Operating system type + version
Macosx 10.15.7

### 3D printer brand / version + firmware version (if known)
VORON 2.4

### Behavior
* Use Calibration
* generate any test model
* 
![image](https://user-images.githubusercontent.com/2248917/99530272-0fd39300-29dc-11eb-9000-cf5109d04e0c.png)

**Comment by supermerill** [comment]
There is a problem with your start gcode.
can you post it here?

**Comment by vvhh2002** [comment]
I use default start G-CODE:

in printer:
```
print_start EXTRUDER={first_layer_temperature[initial_extruder] + extruder_temperature_offset[initial_extruder]} BED=[first_layer_bed_temperature]
```
```
print_end    ;end script from macro
```

```
;BEFORE_LAYER_CHANGE
;[layer_z]
```

```
;AFTER_LAYER_CHANGE
;[layer_z]
```

filament none

**Comment by supermerill** [comment]
that print start don't work for 2.2.53, only next versions
you have to use
`print_start EXTRUDER=[first_layer_temperature] BED=[first_layer_bed_temperature]`
