### ISSUE TITLE
[BUG] SS Crashes when hitting "Slice"

### ISSUE THREAD

**Issue by wildjokerss** [supermerill/SuperSlicer#693]
### Version
2.3.55.1

### Operating system type + version
Win 10

### 3D printer brand / version + firmware version (if known)
Marlin

### Behavior

* _Describe the problem_ Slicer crashing without error
* _Steps needed to reproduce the problem_ the below 3MF just crashes the slicer. If oriented laid down, everything works fine, if I rotate it to the orientation above and hit slice, it crashes without error
* _Expected Results_ not to crash
* _Actual Results_ crash :D 
  * _Screenshots from __*SuperSlicer*__ preview are preferred_ cannot, crashes

![Screenshot_1](https://user-images.githubusercontent.com/72793424/99710927-0f4d0200-2a99-11eb-909e-9289526a47cf.png)

as discussed on Discord, sometimes also gives this:
![image](https://user-images.githubusercontent.com/72793424/99710971-1d028780-2a99-11eb-956e-83c48835d003.png)

#### Project File (.3MF) where problem occurs
[US65_light_frame.zip](https://github.com/supermerill/SuperSlicer/files/5569049/US65_light_frame.zip)

**Comment by supermerill** [comment]
Was a fan kickstart bad implementation.
