### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by shift** [supermerill/SuperSlicer#694]
Not SuperSlicer specific.

Set a profile picture, we sponsor you but you just have a generic profile pic which shows up on the profiles of sponsors. If you set one maybe it gets some recognition going forwards. Doesn't need to be a photo of you, a logo or something, i'm sure we could crowdsource a logo if required.

**Comment by supermerill** [comment]
why not.
I'll use the current superslicer logo.
I'll see to change it to a real photo when I'll grab one good one.

**Comment by shift** [comment]
:D
