### ISSUE TITLE
Custom First Layer G-code

### ISSUE THREAD

**Issue by espr14** [supermerill/SuperSlicer#700]
### Version
v2.2.54

### Operating system type + version
all

### 3D printer brand / version + firmware version (if known)
all

### Behavior
User can enter custom G-code for Start and End of the print, before, after each layer etc. But could be great to have custom code before and after the first layer. User can adjust e.g. acceleration, jerk, filament flow, sound, retraction speed etc. without post processing saved G-code.

For example, user wants to maximize acceleration and jerk of motors (ringing does not matter much) while decreasing printing speed and acceleration. Also unretraction could be little slower to ensure starting point adhesion.

#### Project File (.3MF) where problem occurs

**Comment by supermerill** [comment]
just add a if
