### ISSUE TITLE
Brim Thickness ignoring first layer height and extruder height limits

### ISSUE THREAD

**Issue by bung69** [supermerill/SuperSlicer#704]
### Version
2.2.53

### Operating system type + version
Win10 1803

### 3D printer brand / version + firmware version (if known)
_What 3D printer brand / version are you printing on, is it a stock model or did you modify the printer, what firmware is running on your printer, version of the firmware #s_

### Behaviour
Brim Thickness is ignoring first layer height and extruder height limits, seems to be fixed to nozzle diameter.

nozzle 0.4, layer height max limits of 0.3, first layer height 50% = 
![brim](https://user-images.githubusercontent.com/55783483/99911188-3881c280-2d25-11eb-80c8-1676523221fa.PNG)

**Comment by supermerill** [comment]
fixed in 2.2.53

**Comment by bung69** [comment]
Perfect thank you.
