### ISSUE TITLE
Bridge infill fails to use straight lines, prioritizes curves

### ISSUE THREAD

**Issue by haleypearse** [supermerill/SuperSlicer#705]
[64mm grinder geared v9-2.3mf.zip](https://github.com/supermerill/SuperSlicer/files/5580612/64mm.grinder.geared.v9-2.3mf.zip)
### Version
_2.3.55

### Operating system type + version
Mac OS 10.15.6

### 3D printer brand / version + firmware version (if known)
Prusa m3ks,

### Behavior
Bridge infill fails to use straight lines, prioritizes curves. But a curved bridge is impossible. I noticed this in an earlier version of superslicer too, had to use prusaslicer. 

Superslicer:
![image](https://user-images.githubusercontent.com/10296672/99920308-76f09080-2cd7-11eb-9f64-a38100171962.png)

I'm trying to print countersunk bolt holes btw. Another hole on the left is handled a bit better but still poorly. 
![image](https://user-images.githubusercontent.com/10296672/99920380-f7af8c80-2cd7-11eb-98e2-8fab60c456a8.png)

Prusaslicer:
![image](https://user-images.githubusercontent.com/10296672/99920339-aacbb600-2cd7-11eb-8fe2-2240dfd018fc.png)
![image](https://user-images.githubusercontent.com/10296672/99920438-5543d900-2cd8-11eb-8fdc-c2f8766b141c.png)

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_

**Comment by haleypearse** [comment]
Oh man SuperSlicer is so awesome! I'm finding features I've wanted for ages, unconnected infill, supporting dense layer, even better than I imagined.

**Comment by supermerill** [comment]
It's because of the "one peri on top". You ahve to deactivate it for this layer (or on the full print if it's not needed)

note that for replicating the prusa behavior on that, you need to set your `infill -> advanced -> Anchor solid infill by X mm -> DEfault & Bridged` to 3 (mm)

**Comment by haleypearse** [comment]
Confirmed, that fixes it. Great to have so many configurable options and features. I'm like a kid in a candy shop. Thanks for your work on this. I hope I can contribute some day.
