### ISSUE TITLE
Enhancement: Add Custom G-Code tab to Print Profile

### ISSUE THREAD

**Issue by rngSplat** [supermerill/SuperSlicer#707]
### Version
2.2.53

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Heavily modified CR-10S, running Klipper

### Behavior
Requesting a custom G-Code option for print profiles, to facilitate calibration prints using Klipper's Tuning_Tower command (although there are probably other use-cases)

#### Project File (.3MF) where problem occurs
NA

**Comment by supermerill** [comment]
https://github.com/supermerill/SuperSlicer/issues/282

> Requesting a custom G-Code option for print profiles

and it's trigger when/where?

**Comment by rngSplat** [comment]
Most interested in start/end triggers. For example, I could make a print profile that included the gcode for pressure advance calibration, as described [here](https://www.klipper3d.org/Pressure_Advance.html).

I see that you marked it as duplicate. I searched for a similar one, but didn't see it. Happy to take my comments there, if you let me know what it's a duplicate of.

**Comment by supermerill** [comment]
That's because there is already an issue for Pressure Advance calibration print, if it's the goal. Ultimately, if it's the only thing you need.

For inserting gcode to a print, you can right-click on the (+) 
![image](https://user-images.githubusercontent.com/6536403/100230380-f6739f00-2f25-11eb-8056-385633262b52.png)

**Comment by rngSplat** [comment]
That method adds it to a single print, not a print profile. Having custom g-code for print profiles would make it easier and have fewer manual steps.

I did find issue #496 which this seems to be an exact duplicate of. I'll close this as a duplicate of that. (Sorry I didn't find that one earlier; I was looking for enhancement tag, not New Feature)
