### ISSUE TITLE
Sentences not translated in French

### ISSUE THREAD

**Issue by tirasec** [supermerill/SuperSlicer#710]
### Version
2.3.55.1

### Operating system type + version
W10

### 3D printer brand / version + firmware version (if known)
Any

### Behavior
Several sentences are not translated in French. 
![Translation00](https://user-images.githubusercontent.com/1278002/100078715-1894f080-2e44-11eb-85e1-00ad4827c2f2.JPG)

I followed the page :
https://github.com/supermerill/SuperSlicer/wiki/Creating---updating-a-translation
Maybe I made a mistake...
Translation made by Deepl.com, corrected to 50% by a human. I will check it completely 

#### Project File (.3MF) where problem occurs
[fr.zip](https://github.com/supermerill/SuperSlicer/files/5588420/fr.zip)

**Comment by supermerill** [comment]
oh, i understand the problem.
I moved some string on files that aren't taken into account.
Currently, you have to add them manually to the .po

I'll have to create a fair bit of code to correct that.
