### ISSUE TITLE
Fan kickstart time causing issues

### ISSUE THREAD

**Issue by ardyesp** [supermerill/SuperSlicer#714]
### Version
2.3.55.2

### Operating system type + version
Windows 7, Win64

### 3D printer brand / version + firmware version (if known)
Klipper on Custom CoreXY

### Behavior
If the `Printer -> General -> Cooling Fan` specifies a `Kickstart duration` which is not 0, the fan runs at 100% regardless of max/default fan speed in the Filament.

#### Project File (.3MF) where problem occurs
3DBenchy
Kickstart duration = 0.1, Fan running at 100% all the time
![image](https://user-images.githubusercontent.com/12713441/100112728-9275ab80-2e3d-11eb-9b1a-948a2578eaae.png)

Kickstart duration = 0, Fan at 60% as configured, 100% over bridges and overhangs
![image](https://user-images.githubusercontent.com/12713441/100112992-dbc5fb00-2e3d-11eb-846a-8de750d55ccc.png)

**Comment by supermerill** [comment]
can i have your .3mf?

**Comment by ardyesp** [comment]
Sure, project file attached here, with XYZ calibration cube. The print should show 100% on overhangs, and 60% fan elsewhere.
Thanks.
[xyzCalibration_cube.zip.zip](https://github.com/supermerill/SuperSlicer/files/5612313/xyzCalibration_cube.zip.zip)

**Comment by supermerill** [comment]
Seriously, i won't touch it anymore before my gcode rewrite.
You can disable it by putting 0 on it, and i'll change the default value to 0, so it will be deactivated.
I will be rewritten later.

**Comment by ardyesp** [comment]
I understand. For now, I have set the fan kickstart parameter in the Klipper instead.
