### ISSUE TITLE
Max size of printer, is it possible to increase ?

### ISSUE THREAD

**Issue by tirasec** [supermerill/SuperSlicer#715]
### Version
2.3.55

### Operating system type + version
Any

### 3D printer brand / version + firmware version (if known)
J3D

### Behavior
One of our printer has a 1800x1000x1000mm print volume, unfortunately SuperSlicer is limited to 1200x1200.
![J3d](https://user-images.githubusercontent.com/1278002/100104199-29eef480-2e66-11eb-8b14-a049f879ad0c.jpg)

Is there a way to increase the max print volume in SuperSlicer ?

**Comment by supermerill** [comment]
That's a 2.3 merge quirk.
