### ISSUE TITLE
Bridge overlap not working

### ISSUE THREAD

**Issue by bhuynh2012** [supermerill/SuperSlicer#716]
### Version 
2.3.55.2

### Operating system type + version
Win 10 Enterprise x64

### 3D printer brand / version + firmware version (if known)
Voron 2.4

### Behavior
When changing "bridge overlap" percentage nothing is being applied when sliced. 
You can see the percentage of overlap on the bottom right of the photos and when looking at the two items on the print bed they look exactly the same.

![1](https://user-images.githubusercontent.com/8386995/100117876-20479b80-2e2a-11eb-81b0-2e5822500148.JPG)
![2](https://user-images.githubusercontent.com/8386995/100117881-2178c880-2e2a-11eb-8465-aff2496de523.JPG)

**Comment by supermerill** [comment]
typo in merge ><
that's what happen when I don't do a proper unit test.
