### ISSUE TITLE
Import 3mf w/o the saved profile

### ISSUE THREAD

**Issue by ProfEngr** [supermerill/SuperSlicer#717]
Is/will it be possible to open a 3mf w/o loading the attached profile? Seems more people are saving in 3mf on the Prusa site. Other people's profiles are useless on my rig. I can always just delete them, but the option to not load them when opening the file would be nice. Thanks.

**Comment by supermerill** [comment]
in theory, adding it via the+ button on the platter or file->import->stl/3mf... won't add the config (but it may be checked, have to remove that).

**Comment by ProfEngr** [comment]
Ok, adding from within the slicer just adds the STL. Drag-n-drop (my main way to do it) pulls the profile in too.
