### ISSUE TITLE
ExportToPS Ironing problems (double layer prints?)

### ISSUE THREAD

**Issue by mocksoul** [supermerill/SuperSlicer#718]
### Version
ExportToPS Edition (2.3.55.2)

### Operating system type + version
Windows 10 x64

### 3D printer brand / version + firmware version (if known)
klipper / voron

### Behavior
Sometimes SuperSlicer tries to print layers twice oO.
In the included 3mf top prusa ironing made 2 times (with huge overextrusion).

[over_bridge_flow_test.zip](https://github.com/supermerill/SuperSlicer/files/5592886/over_bridge_flow_test.zip)

You can see this in this screen:

![image](https://user-images.githubusercontent.com/307574/100154088-1e2b1e80-2eb6-11eb-8394-f63f23dda514.png)

But if you change top pattern to "ironing" and turn off "ironing post process" (e.g. switch to superslicer ironing) - for some reason second layer is printed twice with same huge overextrusion:

![image](https://user-images.githubusercontent.com/307574/100154242-54689e00-2eb6-11eb-9ee1-b3347e453a58.png)

Here two (both strange :)) results:

![image](https://user-images.githubusercontent.com/307574/100154586-deb10200-2eb6-11eb-95fd-21b01bfcf053.png)

**Comment by mocksoul** [comment]
Fixed in nightly? Should I try?

**Comment by supermerill** [comment]
not yet. The commit has to show here, and then you can grab the nightly that will be built after that.

**Comment by mocksoul** [comment]
Thanks! I see 👍

**Comment by mocksoul** [comment]
Tried latest build. Original issue fixed, but still where is problems:

sometimes superslicer tries to put perimeters on top of prusa-style ironing layer. In the image below top ironing was done properly, but where is perimeter on top of ironing in the bottom of the image:

![image](https://user-images.githubusercontent.com/307574/100482349-25496b00-3108-11eb-9c92-3239bda2dccf.png)

![image](https://user-images.githubusercontent.com/307574/100482399-4ad67480-3108-11eb-9598-1ad1e8b52cf5.png)

[front_rear_skirt_a_300_x2.zip](https://github.com/supermerill/SuperSlicer/files/5609478/front_rear_skirt_a_300_x2.zip)
