### ISSUE TITLE
objects too close, faulty automatic centering

### ISSUE THREAD

**Issue by dadoblu2000** [supermerill/SuperSlicer#720]
**### Version**
SupserSlicer 2.3.55.1

**### Operating system type + version**

windows 10 64bit

**### 3D printer brand / version + firmware version (if known)**

Voron2_350_after

**### Behavior
*** _Describe the problem_****
the problem is related to the objects that I insert in the print bed, when I insert more objects the software tells me that they will be hit by the extruder, even if I move them manually the problem remains, if I duplicate the problem remains, if I perform the automatic centering it positions the pieces off the print bed

**Comment by supermerill** [comment]
i need your project file
