### ISSUE TITLE
XY compensation

### ISSUE THREAD

**Issue by Slatkey** [supermerill/SuperSlicer#723]
### Version
2.3.55.2

### Operating system type + version
Windows 10 64

### 3D printer brand / version + firmware version (if known)
Corexy / Klipper

### Behavior
Hello. Artifacts appear on the model when XY compensation is turned on.

#### Project File (.3MF) where problem occurs

[z_drive_retainer_b_x2.zip](https://github.com/supermerill/SuperSlicer/files/5602503/z_drive_retainer_b_x2.zip)

Without compensation:
![01](https://user-images.githubusercontent.com/63398258/100343980-2b98f380-2ff1-11eb-82e8-271b0c449ee8.jpg)
![02](https://user-images.githubusercontent.com/63398258/100343985-2cca2080-2ff1-11eb-8e40-4032ab9f2359.jpg)

With compensation included
![03](https://user-images.githubusercontent.com/63398258/100343986-2d62b700-2ff1-11eb-8f67-a05904bd3525.jpg)
![04](https://user-images.githubusercontent.com/63398258/100343987-2d62b700-2ff1-11eb-9141-6d60a1e7fdf3.jpg)

**Comment by supermerill** [comment]
Where is the artifact? can't spot it

**Comment by Slatkey** [comment]
![04](https://user-images.githubusercontent.com/63398258/100350716-58520880-2ffb-11eb-8784-819d14cbe7a7.jpg)

**Comment by TheDoc13** [comment]
Sorry to revive a presumably dead issue, but I got the same problem in V2.4.58.5
![grafik](https://user-images.githubusercontent.com/121322142/209413871-f1df93f4-bf20-4beb-908b-e924320cfa0d.png)

Layer 71 (0.2mm layer height) is using the compensation, everything below not)

Is the bug back?
