### ISSUE TITLE
2.3 Vase mode broken

### ISSUE THREAD

**Issue by supermerill** [supermerill/SuperSlicer#730]
On master.

It creates enormous extrusion moves.

put a cube, activate it
![image](https://user-images.githubusercontent.com/6536403/100530221-797b4a80-31ef-11eb-8ced-731c008c6e80.png)

**Comment by supermerill** [comment]
It's because if there is a `G92 0` and not relative extrusion, then the M92 mess up the extrusions
solution : remove these useless G92

**Comment by hkr955** [comment]
thanks:-)

**Comment by unkn0wndude** [comment]
This bug is still present in version 2.3.55.5
