### ISSUE TITLE
FEATURE REQUEST: Only one perimeter on Bottom surfaces

### ISSUE THREAD

**Issue by LazaroFilm** [supermerill/SuperSlicer#750]
I would love to see an option similar to the already existing `Only one perimeter on Top surfaces:`, but for the Bottom layer.
This would be really useful for prints that have letters on the bottom layer (like Benchy) and parts that need to look symmetrical between the top and bottom layers. 
Thanks for your consideration.

**Comment by MarcPot** [comment]
However I love the `Only one perimeter on Top surfaces:` function, it has a real reason, your model can have like 20 top surfaces, a model only has 1 bottom surface though.
I don't see the use of extra clutter in the UI (It's quite full already) to add an automated way of just doing a `Height Modifier` and setting the perimeters to `1`.

![Screenshot 2020-12-04 085133](https://user-images.githubusercontent.com/7275765/101136879-3f0a1700-360e-11eb-85eb-1fea02412adc.png)
![Screenshot 2020-12-04 085321](https://user-images.githubusercontent.com/7275765/101136883-3fa2ad80-360e-11eb-9e76-8e7c7c2e343a.png)

**Comment by supermerill** [comment]
> What I would like to see though (And basically fixes what you want) is a preset modifier tab that sets up an entire modifier that you have preset before. (With the option of math added so that you can say 1*{layerheight} instead of 0.2)

sort of duplicate of #412

yeah, a tab for overrides for first layer, and maybe a script window to add more complex ones.

**Comment by LazaroFilm** [comment]
I'll mark this as closed since there is a solution for it. Looking forward to see a tab for overrides in the future.

**Comment by bigsubgit** [comment]
Hi everyone, I setup all as indicated, I obtained one perimeter on the bottom, but now it makes only one bottom layer instead of 5 that I want. Is there a way to solve?

**Comment by MarcPot** [comment]
Yea it’s a bug, everything after a height modifier won’t be considered bottom layer.

**Comment by bigsubgit** [comment]
> 
> 
> Yea it’s a bug, everything after a height modifier won’t be considered bottom layer.

Many thanks.

**Comment by pranas** [comment]
The current solution is rather cumbersome. You have to do a lot of steps for every single part. Global modifiers would help but I wish there was an option in print settings, just like there's one for 1 perimeter on top. I think I would just keep it in my profile and use it most of the time since I prefer the finish with 1 perimeter. @supermerill any chance you would reconsider?
