### ISSUE TITLE
Incorrect tooltip or temperature control not working

### ISSUE THREAD

**Issue by ardyesp** [supermerill/SuperSlicer#756]
### Version
v2.3.55_

### Operating system type + version
Windows 64

### 3D printer brand / version + firmware version (if known)
Custom

### Behavior
The tooltip for filament- other layers temperature says setting it to 0 will disable temperature control commands in output gcode. However setting this to zero inserts a 
``` M104 S0 ; set temperature``` 
gcode command at layer# 2.

![image](https://user-images.githubusercontent.com/12713441/101226818-b6b66100-3663-11eb-9fe1-e38b2a08256e.png)

**Comment by liftbag** [comment]
Isn't this the expected behavior?

**Comment by ardyesp** [comment]
> 
> Isn't this the expected behavior?

No, because **disable** would mean the line ```M104 S0``` is not output into the gcode file.

**Comment by liftbag** [comment]
> > Isn't this the expected behavior?
> 
> No, because **disable** would mean the line `M104 S0` is not output into the gcode file.

True. You are right.
