### ISSUE TITLE
Object Outside Toolpath Error - Filament Flow Calibration

### ISSUE THREAD

**Issue by dmpmassive** [supermerill/SuperSlicer#758]
### Version
Version 2.3.55.2

### Operating system type + version
Windows 10 Pro 64bit Ver 2004 OS Build 19041.630

### 3D printer brand / version + firmware version (if known)
Modified CR-10 S4 runing Duet Boards and RepRap firmware version 3.1.1 Stable

### Behavior
1. Calibration menu >> Filament Flow Calibration
2. Click the "Generate 10% intervals..." Button
3. Generates the five test objects and slices, but it creates a duplicate centred at 0,0,0 and throws an error "Toolpath outside the print area" 

![Screenshot 2020-12-05 121059](https://user-images.githubusercontent.com/19830503/101262424-8ae2bc00-36f3-11eb-80c2-291178b09810.png)

4. Switching back to the 3d Editor view, the duplicate object at 0,0,0 vanishes. (See attached)

![Screenshot 2020-12-05 121357](https://user-images.githubusercontent.com/19830503/101262425-8f0ed980-36f3-11eb-9f71-98873dc7164b.png)

5. Simply can't create properly sliced file.  

#### Project File (.3MF) where problem occurs
Not Applicable

**Comment by supermerill** [comment]
can i have your project file?

**Comment by dmpmassive** [comment]
Of course!  Attached.
[filament_flow_test.zip](https://github.com/supermerill/SuperSlicer/files/5648269/filament_flow_test.zip)

**Comment by supermerill** [comment]
Found an other bug, maybe that's that or maybe not, but with the fix it's okay.
