### ISSUE TITLE
[Bug OR Feature Request] "Enable fan if print layer time is below:"

### ISSUE THREAD

**Issue by wildjokerss** [supermerill/SuperSlicer#759]
### Version
2.3.55.3

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Marlin

### Behavior
* _Describe the problem_ The "Enable fan if print layer time is below:" setting is not applying properly (from my POV)
* _Steps needed to reproduce the problem_
> make a cube, something small, with 1 perimeter, where the layer time is e.g below 4 (mine is 2 seconds)
> Set the "Enable fan if print layer time is below:" to 4
> External perimeter fan is set to 15% **and** Max fan speed for short layer time set to 100%
> Since the external perimeter is set to 15%, even though the layer time is below 4, the fan is not kicking in as per "short layer time" parameters. I think it should since this causes a one wall print to melt.

* _Expected Results_ The "Short layer time" Fan speed to override the "External perimeter fan speed" set above.
* _Actual Results_ "External perimeter fan speed" is taking precedence over "short layer time" parameters.
  * _Screenshots from __*SuperSlicer*__ preview are preferred_
![Screenshot_1](https://user-images.githubusercontent.com/72793424/101266177-6ebb3b00-3744-11eb-847e-8c9c1bea0859.png)
![Screenshot_2](https://user-images.githubusercontent.com/72793424/101266183-7844a300-3744-11eb-9cdf-6e59093aee09.png)
![Screenshot_3](https://user-images.githubusercontent.com/72793424/101266186-7a0e6680-3744-11eb-9881-f5d33b77fcb8.png)

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_
[Shape-Box.zip](https://github.com/supermerill/SuperSlicer/files/5647915/Shape-Box.zip)

**Comment by supermerill** [comment]
The external perimeter fan speed is an override, to be sure to not over-cool it. But in your use-case, it's not wanted, so you should disable it.

**Comment by wildjokerss** [comment]
Well I don't think that disabling is the answer. I love External perimeter fan speed for the sole purpose of providing better looking external perimeters, however, **if** the layer time is so low, it need to kick in the short layer time parameter.
In this use-case (that isn't much in this specific, I just use this method to calibrate my filaments) I'd have to change the external perimeter setting to compensate for the low layer time.
having it this way, I believe that "Enable fan if print layer time is below:" should override the upper parameters, or at least having a setting that would allow it both ways, so everyone can have it based on what they prefer :P

**Comment by supermerill** [comment]
I agree but it's not possible with the current gcode writer, i don't have the "there is only external perimeter" information anymore. Maybe after the rework.

**Comment by wildjokerss** [comment]
that's fine, thank you!

**Comment by FishFPV** [comment]
How do I get the fan to stay on 100% after the first layer?

**Comment by supermerill** [comment]
> How do I get the fan to stay on 100% after the first layer?

tick `run fan at default speed when possible` and set `default fan speed` to 100%

**Comment by corrado-c** [comment]
sorry if I add the comment here, but I noticed in several prints that this function related to the SMALL PERIMETER would be useful, not at the time of the whole layer, am I bullshit?
for example on a time layer of 30 seconds there could be small details that would need to be cooled in order not to collapse.
could help FAN FOR SMALL PERIMETER.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/22625950/153771725-971f458a-00d2-4288-a759-6dc4798b42f2.png">

**Comment by supermerill** [comment]
@corrado-c please open a new issue.
