### ISSUE TITLE
Non-straight collapsing bridge infill structure

### ISSUE THREAD

**Issue by belotv** [supermerill/SuperSlicer#761]
### Version
2.3.55.2

### Operating system type + version
macOS Big Sur 11.0.1

### 3D printer brand / version + firmware version (if known)
Anycubic Mega i3 / Klipper

### Behavior
* _Describe the problem_
When slicing the xyzCalibration cube with no infill and 3 perimeters, SuperSlicer creates an angled bridge infill, which is not realistic as filament cannot solidify in the air with an angle.
* _Steps needed to reproduce the problem_
Slice xyzCalibration_cube with 3 perimeters and no infill
  * _If this is a command-line slicing issue, include the options used_
N/A
* _Expected Results_
Bridge infill structure is made of straight lines.
* _Actual Results_
An angled line is created, which collapse in the model during printing.
  * _Screenshots from __*SuperSlicer*__ preview are preferred_
![Capture d’écran 2020-12-06 à 10 14 00](https://user-images.githubusercontent.com/58705127/101276262-deb0dc00-37ab-11eb-8cf9-f90f2e5d0e98.png)

#### Project File (.3MF) where problem occurs
[xyzCalibration_cube.3mf.zip](https://github.com/supermerill/SuperSlicer/files/5648528/xyzCalibration_cube.3mf.zip)

**Comment by supermerill** [comment]
Oh...
It compute each "island" separately
![image](https://user-images.githubusercontent.com/6536403/101429318-f77fd580-3902-11eb-94d8-5bfe0cc24f36.png)
Then, it merge the result...
It should do the compute for all of them at the same time.
