### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Zulaner** [supermerill/SuperSlicer#763]
### Version
2.3.55 (nightly build Dec 02, 2020)

### Operating system type + version
Win 10

### Behavior
Crashing when slicing with supports, if I remove the supports already slice correctly

[Duct.zip](https://github.com/supermerill/SuperSlicer/files/5648830/Duct.zip)

**Comment by supermerill** [comment]
that's the new rectilinear code that is still a little buggy.
