### ISSUE TITLE
Import Config Bundle from 2.2.5.4

### ISSUE THREAD

**Issue by thierryzoller** [supermerill/SuperSlicer#766]
### Version
2.3.55.2

Importing a config bundle that I exported from 2.2.5.4 results in the following error:
ConfigBase::set_deserialize() failed for parameter "solid_fill_pattern", value "monotonous". No settings are loaded.

**Comment by supermerill** [comment]
Can i have the config bundle?

**Comment by thierryzoller** [comment]
[Uploading SuperSlicer_config_bundle.zip…]()

**Comment by thierryzoller** [comment]
[SuperSlicer_config_bundle.zip](https://github.com/supermerill/SuperSlicer/files/5658931/SuperSlicer_config_bundle.zip)

**Comment by supermerill** [comment]
Can't reproduce.
You used this menu entry?
![image](https://user-images.githubusercontent.com/6536403/101478829-93d0c900-3951-11eb-8c09-c692be640521.png)

**Comment by thierryzoller** [comment]
Video 
https://youtu.be/6I8oUeBMTAE
