### ISSUE TITLE
Slicer crash after slicing

### ISSUE THREAD

**Issue by AMBARCAPOOR** [supermerill/SuperSlicer#767]
### Version
SuperSlicer_2.3.55.2_win64_20201124
### Operating system type + version
WIN X 64

### 3D printer brand / version + firmware version (if known)
creality ender 3 pro with skr mini e3v2

### Behavior
after slicing program closes
if i do manage to slice, during printing after a few layers, filament extrusion is stopped, yet print head continues on its path
  * _If this is a command-line slicing issue, include the options used_
* _Expected Results_
* _Actual Results_
  * _Screenshots from __*SuperSlicer*__ preview are preferred_

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_

**Comment by supermerill** [comment]
i need your project file to reproduce.
