### ISSUE TITLE
Version reporting in "About SuperSlicer" incomplete

### ISSUE THREAD

**Issue by TheAndr0id** [supermerill/SuperSlicer#768]
### Version
_Version of SupserSlicer used goes here, Use `About->About SuperSlicer`_
About shows: 2.2.53 
I know this install was compiled from release 2.2.53.2

About shows 2.2.53
System Information shows 2.2.53+UNKNOWN

Windows 7/x64 shows 2.2.53_date for the version under the System Information.  My test install has a date of 2020-10-04 which I think is 2.2.53.3.  About also shows 2.2.53 without any point release.

### Operating system type + version
LInuix x86_64
Windows 7/x64

### Behavior
The about/system information is not including the "point" release for the version.  While  2.2.53 is a good start, there are differences with 2.2.53.2 vs 2.2.53.4 (I haven't moved to 2.2.53.4 since the changes are non-impacting for me).

About/System Information should include the full version to be very clear what release is installed.

This might be an upstream change as PrusaSlicer is showing similar limitations.

**Comment by supermerill** [comment]
already fixed in the 2.3.55 branch
