### ISSUE TITLE
Overlapping external perimeter

### ISSUE THREAD

**Issue by sverzijl** [supermerill/SuperSlicer#771]
### Version
2.3.55.2

### Operating system type + version
Win10

### 3D printer brand / version + firmware version (if known)
Prusa MK3s

Under Print Settings -> Perimeters and Shells I've noticed that using the generated profiles for Prusa MK3S @ 0.6 mm (I haven't checked 0.4) that 'Overlapping External Perimeters' are on by default. When I read the description my impression is that it's a bad idea as it states that it 'results in over extruding and undefined behavior'.

Is it meant to be on by default? Is this, all things being equal, meant to improve the print?

**Comment by supermerill** [comment]
It's to replicate the prusaslicer behavior. If I don't do that, I have a ton on comment "why it's not the same on this thin wall that print perfectly in ps".
