### ISSUE TITLE
Link Setting to Profile / Custom Default Settings 

### ISSUE THREAD

**Issue by CCS86** [supermerill/SuperSlicer#774]
I'm trying to figure out the best way to manage my print settings.

The general theme is that I keep refining some base print settings, that work best on my machine (line widths, overlaps, acceleration, etc), and with those applied globally, I have different profiles setup for different: layer height, speed, infill, etc.

Currently, any time I improve a "base" setting, I have to manually push it across into all of my profiles. This is very time consuming, and I hope there is a better way. 

Seemingly, the built in "default setting" lock/unlock functionality is perfect for this. It seems like allowing for a toggle between [default / custom default] would allow a clean way for the user to tune their own baseline default settings. Maybe just having a "nuclear option" to nuke all custom defaults, and restore the Superslicer defaults. Or, having that option on a per setting basis.

Another idea is instead of worrying about "defaults":

 Settings could just have a "link to profile" button. Click to link, then select the profile you want to link to. This could be even more powerful, without disrupting the existing default setting functionality.

Thoughts?

**Comment by supermerill** [comment]
create you own vendor profile.
take a simple one like the voron.ini (it's in resources/profile), copy it and rename things, change settings, create new printer, etc...

**Comment by CCS86** [comment]
I guess if I had solid default values, that could work for me.

But since my defaults are always evolving, it seems even more cumbersome to update them via text editing.

**Comment by CCS86** [comment]
Another idea is instead of worrying about "defaults":

 Settings could just have a "link" button. Click to link, then select the profile you want to link to. This could be even more powerful, without disrupting the existing default setting functionality.

**Comment by supermerill** [comment]
There is an issue about a "write/erase on vendor profile".
But I don't have time for that in the medium term.

**Comment by Sebazzz** [comment]
@supermerill Is it correct that `inherits` only works when it refers to a vendor profile?

**Comment by supermerill** [comment]
@Sebazzz
yes, it's to shorten the file, to avoid repeating ad nauseum the same settings on each section.

**Comment by CCS86** [comment]
> Another idea is instead of worrying about "defaults":
> 
> Settings could just have a "link" button. Click to link, then select the profile you want to link to. This could be even more powerful, without disrupting the existing default setting functionality.



No interest in this suggestion?

**Comment by supermerill** [comment]
I was mass-cleaning open derelict issues. 

I don't have time this year for revamping profiles bundles anyway.
If something new happens, feel free to open a new issue or re-open this one.
