### ISSUE TITLE
SuperSlicer crash on filament cooling menu

### ISSUE THREAD

**Issue by darkspawn91** [supermerill/SuperSlicer#775]
### Version
SuperSlicer 2.3.55.2

### Operating system type + version
macOS 11.0.1

### 3D printer brand / version + firmware version (if known)
Prusa MK3s MMU2s

### Behavior
Filament cooling crash.

This message appears

![image](https://user-images.githubusercontent.com/59616059/101494994-414ed700-3968-11eb-9a8d-30b3b7dd922b.jpg)

**Comment by supermerill** [comment]
Can you Upload your Project File?

**Comment by darkspawn91** [comment]
No Project still imported. It crash with or without project. Every project. 
Another thing, only with “Generic ABS” I can go on cooling menu. Every other filament crash app. If I change from generic abs in cooling menu, to another filament, this message appears.

**Comment by supermerill** [comment]
I was thinking about a bad italian translation string, but the nightly doesn't crash even in italian.
![image](https://user-images.githubusercontent.com/6536403/101507144-87ab3280-3976-11eb-996d-2a22dd14e8be.png)

**Comment by darkspawn91** [comment]
Can you try to switch on “run the fan default speed when possible”?

Let me know if crash also for you.

**Comment by supermerill** [comment]
it's the traduction of `will run at %1%%% by default` that crash.

**Comment by darkspawn91** [comment]
Ok. Solved. It’s true. Something is wrong in the Italian version. I switched to English version, no crash with “run the fan...” activated.

**Comment by axl12ap** [comment]
> it's the traduction of `will run at %1%%% by default` that crash. It doesn't have the %1%
> ping #619

Thanks, but how can I solve in my translation file??? what I need  to replace with ??

**Comment by supermerill** [comment]
> Thanks, but how can I solve in my translation file??? what I need to replace with ??

now, the pomè_merger.py tool will warn you if the number of '%' isn't the same.
in these string %1% will be replaced by a number or a name.
'%%' means '%'

=> you must have %1% in your translation string if it's present in the English one.

There are now much more recent issues about Italian translation.
