### ISSUE TITLE
Git Repo Name

### ISSUE THREAD

**Issue by reloxx13** [supermerill/SuperSlicer#78]
Rename your git repo to Slic3r++ or PrusaSlicer++ (make a decision or get a new name) and make ur release names and versions constant 👍 

its hard to find your fork.

would be nice to have a ci script building nightly releases or make more beta/alpha releases if u fixed important stuff.

**Comment by supermerill** [comment]
I tried to rename to Slic3r++ but the '+' isn't allowed by github :-/

**Comment by domesticatedviking** [comment]
Slic3r++ evaluates to Slic4r as far as I'm concerned.   Though I was never a big fan of the 'leet '3' in the name.

**Comment by photog0411** [comment]
SuperSlic3r
SuperPrusaSlicer
PrusaSlicer Ultimate Edition

**Comment by sci-phi** [comment]
Slic3r-Plus ?

**Comment by combolek** [comment]
It would be great if we could drop the '3'.
Maybe SlicerPP ?

**Comment by Photogad** [comment]
Super Prusa Slicer

**Comment by guestisp** [comment]
slic3r-plus-plus like notepad++:
https://github.com/notepad-plus-plus/notepad-plus-plus ?

**Comment by supermerill** [comment]
5l1c3r++ to be sure that Thomas Sanladerer can't pronounce it.

good idea for the -plus

**Comment by neophyl** [comment]
That’s just cruel.  Funny but cruel 😂

**Comment by supermerill** [comment]
I think I'll go with SuperSlicer, so the @Photogad proposal but without the '3'.
And as i add 'super' when my username is already taken, it's fitting.

**Comment by cab404** [comment]
I propose prepending "Legendary" to the name. It will fix "SS" acronym!

**Comment by supermerill** [comment]
The new acronym seems to be Susie.
Found it used on a discord.
