### ISSUE TITLE
Speed is not adopted in thin places

### ISSUE THREAD

**Issue by SphaeroX** [supermerill/SuperSlicer#800]
### Version
2.2.0

### Operating system type + version
Windows 10

### Behavior
At a very thin spot (blue 19.3) I just noticed that the printing speed is very slow. So I wanted to search for this setting and have gradually put all the speed parameters up.

But I could not find any option that would have made it faster, is this a mistake on my part or is it the slicer itself?

![pe1](https://user-images.githubusercontent.com/6785110/102017048-bead8980-3d64-11eb-8bd5-8ce3e2ca5d00.JPG)

![pe2](https://user-images.githubusercontent.com/6785110/102017068-e56bc000-3d64-11eb-8f64-2dbf41829ed3.JPG)

**Comment by tecnopolis-ve** [comment]
perhaps the printer cannot reach the top speed due to short movements.

**Comment by SphaeroX** [comment]
Physically, maybe yes, but the slicer should still make the specification... 

I would already be satisfied with 30mm/s, the 100 were only for testing purposes

**Comment by k2dp2k** [comment]
Same here on macOS. 
Tried with different printers, all show the same behavior.

**Comment by supermerill** [comment]
There is now speed settings for thin things. Can you post your project file if it's not fixed?
