### ISSUE TITLE
Crash with monotonic filled top infill

### ISSUE THREAD

**Issue by robthide37** [supermerill/SuperSlicer#801]
It happens no matter what but here is a project. and its the newest nightly 
[retraction_calibration.3mf.txt](https://github.com/supermerill/SuperSlicer/files/5684966/retraction_calibration.3mf.txt)

Also non related i seem to only be able to have 2 profiles save to a physical printer i have to redo it every time i load ss

**Comment by MarcoZ76** [comment]
i have same issue

**Comment by 1N4148** [comment]
This is the error message
<img width="412" alt="20201222_Error" src="https://user-images.githubusercontent.com/5457370/102923851-c7067280-4490-11eb-8539-1cbf29215c3d.png">

**Comment by sugar012** [comment]
same problem on 2.3.55.2
