### ISSUE TITLE
Flow calibration doesn't scale well with nozzle size

### ISSUE THREAD

**Issue by sverzijl** [supermerill/SuperSlicer#805]
2.3.55.1

Win 10

Prusa MK3s

When doing Filament Flow calibration with a 0.15 mm nozzle, the size of the various generated parts don't scale correctly.

![calibration](https://user-images.githubusercontent.com/21155144/102334753-28d36200-3fe3-11eb-9f3e-dbb08e72ab9d.PNG)

**Comment by Gilliearnie** [comment]
Hello
I have the same bug but vice versa with an 1,0mm nozzle.
The first layer is printed 0,5mm over the bed and is dedicated as a overhang perimeter.

![image](https://user-images.githubusercontent.com/40803627/103873306-e7107580-50cf-11eb-9d4b-646c472c9dfc.png)
