### ISSUE TITLE
Avoid crossing perimeters creates huge travel moves

### ISSUE THREAD

**Issue by OldCurmudgeon3DP** [supermerill/SuperSlicer#810]
### Version
2.3.55.3 nightly 245

### Operating system type + version
Win7

### Behavior
See attached image. With the option checked, the travel moves are jumping all over the bed unnecessarily. The majority of the blue lines dart across the open space in the middle only to return to the infill or part not far from where the move started (relative to the distance the avoidance algorithm took).

![avoid-paths](https://user-images.githubusercontent.com/44645861/102506976-b9488b80-4051-11eb-9973-b5cb9fc3ed7d.png)

**Comment by AeroNib** [comment]
I'm encountering this same bug when slicing objects with small islands. Between islands, the gcode will quickly jog the tool to just outside the overall perimeter at its nearest vertex. @ProfEngr's post shows it happens with supports, too, although I'm encountering it with no supports enabled. Maybe it's moving to some nearby point to avoid crossing the islands, but I haven't had a chance to look at the code to see how that algorithm works.

I'm running build 2.3.55.2.

This seems to be the same issue as slic3r/Slic3r#3721 which was opened in 2017, marked as potentially fixed but needed testing, and no updates after that.

**Here's with `avoid_crossing_perimeters = true`**
![Avoid Crossing On](https://user-images.githubusercontent.com/48144540/108634582-2e688080-7448-11eb-9ba4-b4c2cd2086e2.PNG)

**and with `avoid_crossing_perimeters = false`**
![Avoid Crossing Off](https://user-images.githubusercontent.com/48144540/108634583-2e688080-7448-11eb-81de-a415638379d9.PNG)

**Comment by supermerill** [comment]
If it's not fixed in the next version, please report.
