### ISSUE TITLE
Maximum volumetric speed hardcoded?

### ISSUE THREAD

**Issue by Phil1988** [supermerill/SuperSlicer#811]
### Version
2.2.53

### Operating system type + version
Win10 x64

### 3D printer brand / version + firmware version (if known)
Duet Wifi with RepRap Firmware 2

### Behavior
I am trying to print fast with an 0.8mm Vulcano nozzle.
I noticed, that it is not possible to print faster then 14mm³/s 

I have set this:
![grafik](https://user-images.githubusercontent.com/6054234/102509960-6ee20180-4087-11eb-9e6b-48c47eff14fe.png)

![grafik](https://user-images.githubusercontent.com/6054234/102510041-7f927780-4087-11eb-94cb-12474eeadf57.png)

![grafik](https://user-images.githubusercontent.com/6054234/102510092-8b7e3980-4087-11eb-973c-71d031bcdb18.png)

![grafik](https://user-images.githubusercontent.com/6054234/102510203-a781db00-4087-11eb-9c9b-a9be4890e7b6.png)

But the speed is somehow "limited" to 14mm³/s
![grafik](https://user-images.githubusercontent.com/6054234/102510276-be283200-4087-11eb-8841-2e3ccc2806b6.png)

Do I miss something here or is it internally set to maximum 14?

**Comment by neophyl** [comment]
Zip up and post your project and we can take a look at it. That way we can see all your settings.

**Comment by Phil1988** [comment]
how to do so?
save to project as 3mf and then zip it or zip a special folder or something else?

**Comment by supermerill** [comment]
as you like, but you have to drag-drop a zip file here that contains your project file.

**Comment by Phil1988** [comment]
[4github.zip](https://github.com/supermerill/SuperSlicer/files/5713983/4github.zip)

I hope this is what you wanted :)

**Comment by neophyl** [comment]
When I load your saved project in you have the max volumetric rate on your filament profile set to 14. 

I have seen this before with a user on the prusa forum that was also using a multi extruder/filament setup.  Its one of the often overlooked problems with a multi filament setup. 
On the plater screen you have the drop downs that are used to assign SAVED filament profiles to each extruder.  When you go to the filaments tab and edit the filament profile, you are editing a sort of live copy.  With a single extruder setup the changes are applied 'live'.  As theres only one extruder the software knows it can apply the changed profile.  When using a single extruder setup you will see the  filament profile name in the drop down change to xxxxxxxx (modified) as its using the settings from the filament tab that have been changed.
However with more than one extruder it cant know which (if any) of the extruders to apply the (modified) filament profile to.  Notice on the plater that the filaments refer to the saved profiles.  You will have to SAVE the filament profile and assign it for any changes to be used.

**Comment by Phil1988** [comment]
Thanks a lot neophyl!
This helped a lot and I didnt saw that before.

Its works and the issue will be closed now.

**Comment by Tinchus2009** [comment]
That is true! "problem" solved.

**Comment by darksnakezero** [comment]
I ran into the same problem on 2.2.58 and it took me 5 days to figure out why my extruder was clipping.

Can we integrate a fat warning sign on top of the filament settings, as soon as multiple extruders are configured?
