### ISSUE TITLE
[Feature request] Dark mode on Windows 10

### ISSUE THREAD

**Issue by vidpugelj** [supermerill/SuperSlicer#814]
The title says it all. This would be a really welcome addition as it seems that Mac users already have it.

Thanks for all the work you do on this slicer!

**Comment by novarlynx** [comment]
Would love to have this too.

**Comment by supermerill** [comment]
duplicaye of https://github.com/supermerill/SuperSlicer/issues/413

**Comment by DRA6N** [comment]
+100000 to this. Prusaslicer is built on the old Win32 API and the devs over at Prusaslicer use that as an excuse to not build a workaround. Isn't the point of Superslicer to be better? So be better, give us darkmode! :)

**Comment by supermerill** [comment]
Prusa has created a workaround in 2.4
It's a huge dev effort, as it means recreating many widget so they can be colored the right way.
No tab, no status bar, no dialogs, etc.
