### ISSUE TITLE
Ironing how to enable?

### ISSUE THREAD

**Issue by aceycv8** [supermerill/SuperSlicer#817]
### Version
2.2.53

Hi Guys,

This is probably a user issue more than anything, but how do i enable ironing?
the only settings i see are in - inflill- "advanded infil" iron tuning but it's all greyed out.
![image](https://user-images.githubusercontent.com/28552756/102677424-4ff58380-41dd-11eb-80ac-cea42eeceb7c.png)

i can't right click the model and add in a new modification to add in ironing etc so i assume it's something i've enabled along the way but i dont know what?
![image](https://user-images.githubusercontent.com/28552756/102677446-6ef41580-41dd-11eb-9fc5-5ccfbfc4cf71.png)

**Comment by Wil-Storch** [comment]
"External pattern Top" must be set to "Ironing" in the version you are using.

Later versions this functions slightly differently
![image](https://user-images.githubusercontent.com/34592159/102684325-9540a200-422b-11eb-99bd-6a0aef2464c4.png)

**Comment by aceycv8** [comment]
Thank you Wil-Storch!

**Comment by Phil1988** [comment]
@aceycv8 or @supermerill 
This can be closed.
