### ISSUE TITLE
Custom pause command

### ISSUE THREAD

**Issue by Pavulon87** [supermerill/SuperSlicer#821]
It would be nice if there was an option for custom pause command.

I'm using `M118 action:runout_detected` just to inform about filament problems. Sometimes it's just a problem with the sensor and the M600 isn't needed.

I changed file smartilamentsensor_settings.jinja2 but maybe someone would also use it.

**Comment by neophyl** [comment]
As the ability to customise the pause/colour change gcode has been added to the 2.3.x versions of Prusa Slicer already then it is available in Super Slicer releases based on the PS 2.3 , no namely the 2.2.55 release of SuSie.  So its already done.

**Comment by Pavulon87** [comment]
Omg, Sorry, wrong repository.
