### ISSUE TITLE
filament flow calibration breaks bl touch probe

### ISSUE THREAD

**Issue by raymwe** [supermerill/SuperSlicer#825]
Version 1.2.5.3
w10
ender 3 pro

Printed the flow calibration, the height of the blocks are above retracted posn. of bl touch probe. This needs a serious warning message, or separate the blocks further apart, or print singly. snapped off the probe tip.

**Comment by bangor-flyer** [comment]
No issue with my BL touch done 3 levels yesterday.
This would mean your probe is below your nozzle poss?

**Comment by raymwe** [comment]
No, It is retracted, just above nozzle, but this test prints a block at a time, so the block height is greater than the difference between retracted probe tip and nozzle tip. Also, it will collide with cooling fan ducting. If you want to print an item at a time, it needs to have enough distance between the items. This does not. Afaik, there is no specified distance for probes to be above the nozzle. Just because it worked OK for you, it does not mean that the test is safe for others. fwiw, the earlier bl touches had a shorter retraction distance.

**Comment by bangor-flyer** [comment]
![image](https://user-images.githubusercontent.com/58892221/102921703-b9e38680-4484-11eb-8c38-98210c1930b9.png)

**Comment by raymwe** [comment]
The information on setting up the printer for flow calibration is not adequate. If others think it is, so be it. I've reported a problem. It would be trivial to correct it.
