### ISSUE TITLE
[Feature Request] Infill angles

### ISSUE THREAD

**Issue by wildjokerss** [supermerill/SuperSlicer#831]
### Behavior
* _Describe the problem_ Currently SS only allows to set a certain degree of rotation for infill, problem is that this rotation affect all the infills, either solid or not. This is far from ideal. 
* _Expected Results_ I would like a approach similar to Ideamaker, with a box where I can add the degree of infill I want and slicer does it by that order, per layer. Also, splitting infill from solid infill, I might want my solid fill at 0 or 90º angle, or even 0º then 45º then 90º and leaving my standard infill untouched.
* _Actual Results_ When using the rotation of the infill this is affecting every infill, so it kinda "breaks" some of them by making them very weak.
  * _Screenshots from __*SuperSlicer*__ preview are preferred_
![Screenshot_1](https://user-images.githubusercontent.com/72793424/103131419-955ff800-4698-11eb-93b6-77ee5da05a7f.png)
![Screenshot_2](https://user-images.githubusercontent.com/72793424/103131420-95f88e80-4698-11eb-81a2-d2e2f4365db3.png)
![Screenshot_3](https://user-images.githubusercontent.com/72793424/103131421-96912500-4698-11eb-9ff4-86af7f21cc41.png)

**Comment by andybrice** [comment]
Yes, this is something I often find myself wanting too. I might want my top and bottom faces angled a certain way for aesthetics, and my infill angled another way for strength.

Perhaps it could be achieved with something like this? (Although it would add clutter.) ![Superslicer Angle](https://user-images.githubusercontent.com/106819/122920036-d3448d00-d358-11eb-9374-e09286f3b97a.png)

**Comment by marcel-isler** [comment]
I would love to see this feature added as well... it's one of the main reasons I have not switched from S3D yet...

I have my infill angles set like this:
![image](https://user-images.githubusercontent.com/16922876/175464379-d570fedf-0a3e-4865-94c1-e5a1d1187e6e.png)

This gives me great coverage, especially over low % infill.  It's also much less likely to have a checkerboard pattern.
