### ISSUE TITLE
Tool change G-code input box not editable

### ISSUE THREAD

**Issue by vvchik** [supermerill/SuperSlicer#838]
### Version
_2.3.55.2_

### Operating system type + version
_MacOS Big Sur 11.1_ 

### 3D printer brand / version + firmware version (if known)
_Doesnt matter, Have ender3 But same issue with the Prusa printer profile_

### Behavior
* In `Printer Settings` `Custom G-code` `Tool change G-code` input box not editable (same bug present in Prusa slicer)

### Expected behaviour
 This input box should be editable

**Comment by neophyl** [comment]
You have to have more than 1 extruder defined for the Tool change gcode field to be editable.  

So not a bug as why would you need tool change code if you don't have multiple tools ?
