### ISSUE TITLE
Gcode Preview doesn't display extrusion width above 1mm

### ISSUE THREAD

**Issue by bung69** [supermerill/SuperSlicer#840]
![gaps](https://user-images.githubusercontent.com/55783483/103297067-18cb7180-4a2a-11eb-8661-a3392eadd9dd.PNG)

### Version
2.3.55.2

### Operating system type + version
Win10

Gcode Preview doesn't display extrusion width above 1mm.   attached screenshot is with a 1.4mm nozzle with auto extrusion width.  confirmed with manual extrusion widths set > 1,4mm 

Edit:
I should add that automatic extrusion width for the gcode output also seems to be broken for large nozzles.  with a 1.4 mm nozzle when extrusion widths are left at 0, the output extrusion width is probably around 1mm.  manually entering extrusion widths is a work around for single tool, though no good for a tool changing printer.

**Comment by liftbag** [comment]
I can confirm this behavior. It almost feels like a limit set in the slicing engine. In fact, if you set an extrusion width greater than 1mm, a dialog box appears to confirm the choice. But even confirming the choice, refusing to use the percentage, the extrusion width cannot exceed 1mm.

<img width="372" alt="Schermata 2021-01-04 alle 19 04 07" src="https://user-images.githubusercontent.com/14921654/103565210-35e7c080-4ec0-11eb-9592-298abf9f5924.png">


<img width="1250" alt="Schermata 2021-01-04 alle 19 10 13" src="https://user-images.githubusercontent.com/14921654/103565435-a098fc00-4ec0-11eb-8779-ae5eb4256313.png">

**Comment by supermerill** [comment]
it's just a min(1, ....) somewhere as a failsafe that was a bit too broad.
I also changed the check message, for some fields. If it's still a bit too trigger happy, please let me know to change it.

**Comment by bung69** [comment]
Looks good now.  thanks
