### ISSUE TITLE
monotonic vs monotonic filled?

### ISSUE THREAD

**Issue by totalitarian** [supermerill/SuperSlicer#842]
Hi, what is the difference between filled vs non filled monotonic infill?

**Comment by liftbag** [comment]
Solid infills sometimes leave uncovered areas due to the spread angle relative to the perimeter angle (or for other reasons). The filled mode (also present in other types of filling), takes care of going to fill these empty gaps once the filling is completed.

**Comment by totalitarian** [comment]
Ah, so it's similar to gap fill?

**Comment by liftbag** [comment]
Yes, the gap fill operates between the perimeters. In this case, the gaps in the infill are filled.
