### ISSUE TITLE
Bed wants to heat up to nozzle temp at start!

### ISSUE THREAD

**Issue by hagan66** [supermerill/SuperSlicer#846]
### Version
2.3.55.2

### Operating system type + version
MacOS Big Sur

### 3D printer brand / version + firmware version (if known)
Prusa MK2.5S MMU2s

### Behavior
I think its a typo in the start gcode. Will try fixing it myself.

**Comment by supermerill** [comment]
If it's not present in the start gcode, i add it myself. to prevent problems and people making issues because it doesn't heat.
If you don't want it, put a M109 in your start gcode. Even a M109 S0 works to remove that extra check.

**Comment by supermerill** [comment]
please post your project file.

**Comment by hagan66** [comment]
[xyzCalibration_cube.3mf.zip](https://github.com/supermerill/SuperSlicer/files/5792784/xyzCalibration_cube.3mf.zip)

I fixed the problem by changing the start gcode from this:

M140 S[first_layer_bed_temperature] ; set bed temp
M190 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; wait for bed temp

to this:

M140 S[first_layer_bed_temperature] ; set bed temp
M190 S[first_layer_bed_temperature] ; wait for bed temp

**Comment by hagan66** [comment]
This is still a problem in the latest release.

**Comment by supermerill** [comment]
what you have in your star gcode:
```
M104 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; set extruder temp
M140 S[first_layer_bed_temperature] ; set bed temp
M190 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; wait for bed temp
M109 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; wait for extruder temp
```
what you want:
```
M104 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; set extruder temp
M190 S{first_layer_bed_temperature] ; wait for bed temp
M109 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; wait for extruder temp
```

**Comment by hagan66** [comment]
Hi again! Thanks for your suggested g-code. I have it working. :-) My concern was that the default start g-code is wrong (maybe just for my printer model?) and could cause overheat problems for other users. Every time I reinstall Superslicer this comes back, that the bed gets the nozzle temp in the start code.

**Comment by supermerill** [comment]
If the prusa default settings bad?
if so, it's a serious bug.
