### ISSUE TITLE
Crashes on wizard configurator.

### ISSUE THREAD

**Issue by Chazy12** [supermerill/SuperSlicer#851]
### Version
2.2.54

### Operating system type + version
Windows 10 64 bit

when tring to add an mk3s printer by wizard configurator, the software crashes.

https://user-images.githubusercontent.com/6653347/103631107-de3e6900-4f42-11eb-90ec-3da15811c2e1.mp4
![2021-01-05_104020](https://user-images.githubusercontent.com/6653347/103631141-e8f8fe00-4f42-11eb-977e-4d16e271500f.jpg)

**Comment by supermerill** [comment]
monotonous has been renamed to monotonic.
This bug has been corrected in the 2.3.55 branch and isn't present in the 2.2.53
you can also edit the vendor files in resources/profile and changing all monotonic by monotonous.
