### ISSUE TITLE
line infill seems not to work

### ISSUE THREAD

**Issue by knickohr** [supermerill/SuperSlicer#856]
### Version
2.3.55.2

### Operating system type + version
Win 7 64bit

### 3D printer brand / version + firmware version (if known)
Prusa Bear with SKR 1.4 Turbo, Marlin 2

### Behavior
Testing some infill pattern. I recognize that the line infill does "nothing".

**Comment by supermerill** [comment]
it's doing something in my dev build. So it should be resolved in the next release.
