### ISSUE TITLE
Variable layer height appears inverted

### ISSUE THREAD

**Issue by ProfEngr** [supermerill/SuperSlicer#860]
### Version
Last alpha from Dec '20

### Operating system type + version
Win 7

### Behavior
Enabled the feature. Clicked Adaptive then Smooth. Details are showing high layer heights where vertical, low-detail walls are showing minimum layer height.

![adaptive reversed](https://user-images.githubusercontent.com/44645861/103832917-8d676700-504d-11eb-8bd9-aecef54bd3a0.png)

**Comment by theophile** [comment]
That looks right to me. What are you expecting to see?

**Comment by ProfEngr** [comment]
Areas that have filets should be at 0.12 while featureless walls should be 0.3.

**Comment by theophile** [comment]
It's hard to see the problem without being able to see the rest of the model. What did it look like before you smoothed it?

**Comment by limited660** [comment]
@theophile the area in green doesn't need low layer height because it's straight, the area in orange needs it because of the fillets.

**Comment by theophile** [comment]
Something on the other side of the model presumably has more details in the green area. It looks like it tried to use a lower layer height for the fillets but it was smoothed out. Try it again without smoothing.

**Comment by supermerill** [comment]
I'll look into it when i'll have some more time and less serious bugs.

**Comment by ProfEngr** [comment]
> Something on the other side of the model presumably has more details in the green area. It looks like it tried to use a lower layer height for the fillets but it was smoothed out. Try it again without smoothing.

All 4 corners are the same geometry. It's a simple box for a NodeMCU. I'll try some other parts and see if it was just a fluke.

**Comment by ProfEngr** [comment]
I think it might just be that specific geometry. I tried a few other STLs and the algorithm seems to be ok. Sorry to bother everyone.
