### ISSUE TITLE
Is this a bug? Ironing on every raft interface layer?

### ISSUE THREAD

**Issue by scott0122** [supermerill/SuperSlicer#861]
### Version
Latest Master (2.3.55.3)

### Operating system type + version
Windows 10 x64

### Behavior
Setting: 
 Raft layers:3
 Interface layer:3
 Interface pattern: Ironing

Layer 1(raft interface 1) is ironing
![image](https://user-images.githubusercontent.com/39105828/103846662-969e1580-50d9-11eb-8f18-3aa2fe4950e0.png)

Layer 2(raft interface 2) is ironing
![image](https://user-images.githubusercontent.com/39105828/103846707-b1708a00-50d9-11eb-8190-85719e261d21.png)

Layer 3(raft interface 3) is ironing
![image](https://user-images.githubusercontent.com/39105828/103846750-c9480e00-50d9-11eb-858f-6220e1fffc29.png)

**Comment by supermerill** [comment]
did you select ironing as interface pattern? IIRC, it's the pattern used for the raft (there is already an issue to change that)

**Comment by scott0122** [comment]
@supermerill Yes, interface pattern is Ironing. Should it be only ironing on top raft layer?
Setting:
Raft layers:3
Interface layer:3
Interface pattern: Ironing

**Comment by supermerill** [comment]
I have to create more pattern settings to decouple things.
