### ISSUE TITLE
Ironing post-process ironing one more times on the same surface.

### ISSUE THREAD

**Issue by scott0122** [supermerill/SuperSlicer#863]
### Version
Latest Master (2.3.55.3)

### Operating system type + version
Windows 10 x64

### Behavior
Changing any value which will post steps.emplace_back(posPrepareInfill) in PrintObject.cpp cause Ironing post-process ironing one more times on the same surface.

https://user-images.githubusercontent.com/39105828/103903364-c7606800-5136-11eb-96f5-647dd45e571b.mp4

**Comment by supermerill** [comment]
maybe there is a clear() missing somewhere.
