### ISSUE TITLE
Support structure problems

### ISSUE THREAD

**Issue by Balu0127** [supermerill/SuperSlicer#867]
Hello 

Have a question, is there the possibility so in the kind of tree supports as in Cura in Superslicer to integrate or can the slicer already! Or can you set the support structure somehow that not so much is supported.

**Comment by supermerill** [comment]
Tree support is not implemented yet.
There is a trick: add the sl1 printer, slice the object with sl1 tree, export the platter geometry with support, re-import it in the fff mode, with your printer (I didn't test it, just someone talked about it).
