### ISSUE TITLE
Strange artifacts on curves and misaligned perimeters

### ISSUE THREAD

**Issue by uepsie** [supermerill/SuperSlicer#869]
### Version
2.3.55.4

### Operating system type + version
Windows 10 64Bit Build 19042.685

### 3D printer brand / version + firmware version (if known)
Prusa MK3 + Klipper

### Behavior
When slicing a benchy with default parameters for Prusa MK3 (0.4 nozzle, Prusament PLA, 0.2 Quality Profile) there are strange artifacts also reflected in the print.

![image](https://user-images.githubusercontent.com/304272/104134759-eefc3e00-538b-11eb-917f-5dee8f7a0f7a.png)
![image](https://user-images.githubusercontent.com/304272/104134864-8eb9cc00-538c-11eb-885d-b90626ebc03d.png)

#### Project File (.3MF) where problem occurs
added the zipped 3mf:
[#3DBenchy.zip](https://github.com/supermerill/SuperSlicer/files/5793278/3DBenchy.zip)

**Comment by uepsie** [comment]
I just tried the same model with same settings in 2.3.55.1

![image](https://user-images.githubusercontent.com/304272/104928252-b3bcc900-59a2-11eb-837c-c9c8d4a0d3b8.png)

![image](https://user-images.githubusercontent.com/304272/104928355-d3ec8800-59a2-11eb-8c24-d4786c073ab1.png)

It seems to work flawless here

**Comment by supermerill** [comment]
seems like the printer -> general -> min extrusion length is too high,  it's better with a value of 0.001

**Comment by uepsie** [comment]
interestingly this fixed it.. so is it a problem with Prusa's default settings?

**Comment by uepsie** [comment]
Fixed by setting min extrusion length to 0.001
Closing this one
