### ISSUE TITLE
Internal Error: boost::bad_any_cast

### ISSUE THREAD

**Issue by uepsie** [supermerill/SuperSlicer#870]
### Version
2.3.55.4

### Operating system type + version
Windows 10 64Bit Build 19042.685

### 3D printer brand / version + firmware version (if known)
Prusa MK3 + Klipper

### Behavior
SuperSlicer crashes on click on "Printer Settings" Tab (even after fresh start)
![image](https://user-images.githubusercontent.com/304272/104134947-29b2a600-538d-11eb-8cfe-0970154302f7.png)
![image](https://user-images.githubusercontent.com/304272/104134953-3931ef00-538d-11eb-86a4-31afb0805c8e.png)

**Comment by Pavulon87** [comment]
Same here. Slicing works. "Printer settings" crash.

**Comment by Pavulon87** [comment]
Quick fix:
from **resources/ui_layout/printer_fff.ui**
remove: 
```
	line:Size for Gcode
		setting:id$0:label$Small:thumbnails
		setting:id$1:label$Big:thumbnails
	end_line
```

**Comment by uepsie** [comment]
I don't have those lines in my printer_fff.ui

**Comment by Pavulon87** [comment]
> I don't have those lines in my printer_fff.ui
Is your file different than https://github.com/supermerill/SuperSlicer/blob/master/resources/ui_layout/printer_fff.ui ?

**Comment by uepsie** [comment]
Oh - my bad. Typo in my search
indeed, removing those lines help

**Comment by khumarahn** [comment]
Same here, on arch linux.

**Comment by supermerill** [comment]
fixed yesterday
