### ISSUE TITLE
Volumetric autospeed does not respect the linear speed limit

### ISSUE THREAD

**Issue by zbrozek** [supermerill/SuperSlicer#882]
### Version
2.3.55.2

### Operating system type + version
Windows 10 Pro build 19042

### Behavior
1) Set the various linear speed limits to zero (e.g., auto).
2) Set the maximum linear speed to something finite (e.g., 120 mm/s).
3) Set the volumetric autospeed to something finite (e.g., 15 mm^3/s).
4) Slice a model.
5) Look at the linear speed in gcode visualizer and note that it exceeds (often enormously) the maximum linear speed setting.
![warp-speed](https://user-images.githubusercontent.com/4878259/104622096-aec7e480-5645-11eb-85ab-72a7c1db9f7c.JPG)

#### Project File (.3MF) where problem occurs
[demo.zip](https://github.com/supermerill/SuperSlicer/files/5815795/demo.zip)

**Comment by supermerill** [comment]
There is  two bugs here.

1) wrong speed for thinwalls & gapfill when autospeed.
2) when setting gapfill speed from somethign to 0, it doesn't recompute the perimeter, and so keep the gapfill.

I'm going to remove the "gapfill 0 speed deactivate the gapfill".
The new speed for gapfill/thinwall when autospeed will be set to the speed of a 200% width extrusion (if you have some opinions about that, tell me).

**Comment by zbrozek** [comment]
Both of those sound good to me - thank you!

**Comment by SirStigII** [comment]
I think I may have noticed a related issue in the latest stable release (2.3.56.4b), if speeds are set to auto like in the above situation, but the outer and top layers are set to a percentage (I was using 50%) they will slice at the max print speed, instead of using the correct percentage. setting the perimeter speed and solid speed to 120mm/s in this case will correctly use the 50% value (60mm/s)

**Comment by supermerill** [comment]
> I think I may have noticed a related issue in the latest stable release (2.3.56.4b), if speeds are set to auto like in the above situation, but the outer and top layers are set to a percentage (I was using 50%) they will slice at the max print speed, instead of using the correct percentage. setting the perimeter speed and solid speed to 120mm/s in this case will correctly use the 50% value (60mm/s)

Give your project file to help me reproduce the problem.

**Comment by SirStigII** [comment]
sorry, saw this one was only recently closed and figured it might be a connected issue. I'll upload the project file in a new issue.
