### ISSUE TITLE
Nightly build crashing on MacOs BigSur right after splash screen.

### ISSUE THREAD

**Issue by vvchik** [supermerill/SuperSlicer#892]
### Version
_Nightly Jan 18_

### Operating system type + version
_MacOs Big Sur, arm M1 processor._

### 3D printer brand / version + firmware version (if known)
_Ender 3, Klipper_

### Behavior
* _crash right after splash screen_
* _Just Launch_

**Comment by liftbag** [comment]
Same issue as yours? #777

**Comment by vvchik** [comment]
yeah, looks similar, closing as duplicate
