### ISSUE TITLE
"run at defaul speed" crashes everytime

### ISSUE THREAD

**Issue by Chazy12** [supermerill/SuperSlicer#903]
### Version
2.3.55.2

### Operating system type + version
Windows 10 64bit

"run at defaul speed" crashes everytime.

https://user-images.githubusercontent.com/6653347/105354291-a39a2900-5bf0-11eb-919f-57f2e504dc3e.mp4

**Comment by supermerill** [comment]
Can't redproduce in the dev build, so it should be fixed in the next version.
