### ISSUE TITLE
Incorrect slicing of model

### ISSUE THREAD

**Issue by oabdullin** [supermerill/SuperSlicer#908]
### Version
2.3.55.2 and earlier like 2.2.52

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
it's not related to printer

### Behavior
The slicer cant slice this model 

#### Project File (.3MF) where problem occurs
Please see attached project:
[Small_boat_for_Minifig.zip](https://github.com/supermerill/SuperSlicer/files/5858538/Small_boat_for_Minifig.zip)

Model:
![image](https://user-images.githubusercontent.com/50902271/105545962-65daf480-5d05-11eb-9574-b148a9bfcd78.png)

Sliced without infill:
![image](https://user-images.githubusercontent.com/50902271/105545949-5f4c7d00-5d05-11eb-8610-1fb97f2fd9dc.png)

With infill:
![image](https://user-images.githubusercontent.com/50902271/105546326-e4d02d00-5d05-11eb-826b-6c43bf156f6c.png)

**Comment by Pavulon87** [comment]
Stl with errors.
![Zrzut ekranu 2021-01-22 22 24 26](https://user-images.githubusercontent.com/23641103/105548977-a5eba880-5d00-11eb-8c6d-cebbbe70f8bd.png)
[Small_boat_for_Minifig_v2.zip](https://github.com/supermerill/SuperSlicer/files/5858656/Small_boat_for_Minifig_v2.zip)

**Comment by oabdullin** [comment]
@Pavulon87, how did you fixed STL?

**Comment by liftbag** [comment]
> @Pavulon87, how did you fixed STL?

You can try with [Netfabb online service](https://service.netfabb.com/login.php).
