### ISSUE TITLE
Infill bridge does not have fan speed of bridge setting (like 100%)

### ISSUE THREAD

**Issue by lucaslsk** [supermerill/SuperSlicer#922]
### Version
_Version of SupserSlicer used goes here, Use `About->About SuperSlicer`_
2.3.55.2

### Operating system type + version
_What OS are you using (and version)_
Octopi 0.18

### 3D printer brand / version + firmware version (if known)
_What 3D printer brand / version are you printing on, is it a stock model or did you modify the printer, what firmware is running on your printer, version of the firmware #s_
FLSUN Q5 with Marling 2.0.7 firmware

### Behavior
* _Describe the problem_
* _Steps needed to reproduce the problem_
  * _If this is a command-line slicing issue, include the options used_
* _Expected Results_
* _Actual Results_
  * _Screenshots from __*SuperSlicer*__ preview are preferred_

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_

**Comment by CroXY3D** [comment]
99%. works, but 100% yeilds 0% fan.
