### ISSUE TITLE
Convert round holes to polyholes option does not work

### ISSUE THREAD

**Issue by user32rtu** [supermerill/SuperSlicer#924]
### Version
2.3.55

### Operating system type + version
Windows 10 Pro 64 bits 20H2

### 3D printer brand / version + firmware version (if known)
Sapphire Pro Marlin 2.0
### Behavior
When I enable the "Convert round holes to polyholes" option, when I view the G code, I do not see any changes in the shape of the holes. The small hole in the screenshot consists of 32 segments when the setting is on and off.

#### Project File (.3MF) where problem occurs
![Screenshot_configuration with polyholes](https://user-images.githubusercontent.com/48878798/106228620-d51c8100-61fc-11eb-93fc-29221a555282.jpg)
![Screenshot_configuration without polyholes](https://user-images.githubusercontent.com/48878798/106228632-d9e13500-61fc-11eb-9683-3eac5c0f231b.jpg)
![Configuration with polyholes](https://user-images.githubusercontent.com/48878798/106228639-de0d5280-61fc-11eb-9d10-7ee15a6141a0.jpg)
![Configuration without polyholes](https://user-images.githubusercontent.com/48878798/106228644-dfd71600-61fc-11eb-89ab-ed406adc036c.jpg)

[ScaleHole_v2.zip](https://github.com/supermerill/SuperSlicer/files/5891473/ScaleHole_v2.zip)

**Comment by qwewer0** [comment]
There is something weird going on. (3rd smallest hole)
[PolyHoleTest_3mf.zip](https://github.com/supermerill/SuperSlicer/files/5893232/PolyHoleTest_3mf.zip)
Top of the part:
![Screenshot 2021-01-29 112857](https://user-images.githubusercontent.com/57561110/106264054-76b7c880-6225-11eb-80a7-cf6f0f6f0897.png)
Inside of the part:
![Screenshot 2021-01-29 112947](https://user-images.githubusercontent.com/57561110/106264083-7d464000-6225-11eb-854a-ac3cbf99056e.png)

**Comment by user32rtu** [comment]
The error still exists.
[PolyHoleTest_3mf.zip](https://github.com/supermerill/SuperSlicer/files/5894105/PolyHoleTest_3mf.zip)
![Screenshot](https://user-images.githubusercontent.com/48878798/106281838-d11a4e80-6250-11eb-8a4c-5dfe67572160.png)

**Comment by qwewer0** [comment]
The issue is still present on 2.3.55.4

**Comment by supermerill** [comment]
hole polygon wasn't regular. I'm now a bit more lenient in the detection.

**Comment by qwewer0** [comment]
@supermerill It is still not really working (latest nightly_win64)

[Polyhole.zip](https://github.com/supermerill/SuperSlicer/files/6182122/Polyhole.zip)
https://imgur.com/gallery/DRw1j72

**Comment by supermerill** [comment]
@qwewer0 where is the problem?

**Comment by qwewer0** [comment]
> https://imgur.com/gallery/DRw1j72

@supermerill The third smallest hole is't converted on every layer

**Comment by supermerill** [comment]
ok, i'll see

**Comment by supermerill** [comment]
I'll add a user setting to allow for not-extremely-round holes.
