### ISSUE TITLE
Bad Top-Fill Issue compared to PrusaSlicer

### ISSUE THREAD

**Issue by Photogad** [supermerill/SuperSlicer#925]
### Version
Latest

### Operating system type + version
Win64

### Behavior

The top fill on my object, when using SuperSlicer, puts weird infill on the solid layer instead of a smooth surface, below some raised text on the object. In PrusaSlicer, it does not do this problem, and has a nice smooth surface below the raised text. Both slicers are using the same profile settings that I can see. I tried matching them the best I can, but SuperSlicer have some options PrusaSlicer don't.

Please help!

See photos below.

![3](https://user-images.githubusercontent.com/18505956/106308359-97385080-622e-11eb-9f0e-744f1af83487.PNG)
![1](https://user-images.githubusercontent.com/18505956/106308360-97d0e700-622e-11eb-8171-2c58f2e0461d.PNG)
![2](https://user-images.githubusercontent.com/18505956/106308362-97d0e700-622e-11eb-8280-494aa4e25ee9.PNG)

#### Project File (.3MF) where problem occurs

[shannysugars.zip](https://github.com/supermerill/SuperSlicer/files/5895313/shannysugars.zip)

**Comment by Photogad** [comment]
@supermerill 

Actually I found the cause of the issue:
This is happening when both "Enforce 100% Fill Volume" and "Only One Perimeter On Top Surfaces" is enabled.

if I disable both, it fixes the issue.

**Comment by supermerill** [comment]
> This is happening when both "Enforce 100% Fill Volume" and "Only One Perimeter On Top Surfaces" is enabled.

You only have to disable "Only One Perimeter On Top Surfaces"

See #733 #945
