### ISSUE TITLE
Error Compiling on Fedora

### ISSUE THREAD

**Issue by karnhack** [supermerill/SuperSlicer#926]
### Version
SuperSlicer-2.3.55.2

### Operating system type + version
Fedora workstation 33

### CMAKE command
`cmake -DSLIC3R_WX_STABLE=1 -DSLIC3R_GTK=3 -DSLIC3R_BUILD_TESTS=OFF ..`

### Result
![Schermata del 2021-01-29 19-13-57](https://user-images.githubusercontent.com/3381971/106312011-52c8a700-6266-11eb-9a79-f81143b8b2a5.png)

Thanks!

**Comment by supermerill** [comment]
> -DSLIC3R_WX_STABLE=1

this is the problem i think, i use some things that aren't in the "stable" that is in the cmake.

You can take my building script [here](https://github.com/supermerill/SuperSlicer/blob/master/.github/workflows/ccpp_ubuntu.yml)

You can reopen if you have more questions
