### ISSUE TITLE
Strange Vasemode Behaviour

### ISSUE THREAD

**Issue by thelandinlook** [supermerill/SuperSlicer#931]
### Version
SuperSlicer_2.3.55.2

### Operating system type + version
Windows 10 (build 19042), 64-bit edition

### 3D printer brand / version + firmware version (if known)
Ender 3 v2 using latest klipper release

### Behavior
When slicing particular models in vasemode I'm getting a strange inconsistent width change (multiple people have helped me pin this down to just PS and SS, not apparent in Slic3r) 
The seam is always in the same corner of the model, even when changing seam behaviour or drawing seams manually. From lots of testing the only variables I've found to affect this are:
1. Changing the number of bottom layers, this moves the seam by -45 degrees around the model for each layer added.
2. The height of the model; cutting the same model horizontally in different places results in different seam behavior at the top
3. 
![20210130_230009](https://user-images.githubusercontent.com/76990913/106370464-8c7ada00-635a-11eb-8535-4227f735c68a.jpg)
<img width="645" alt="superslicer_7MJj6ng1oA" src="https://user-images.githubusercontent.com/76990913/106370370-ae279180-6359-11eb-9cb6-dfde11a33d15.png">
<img width="610" alt="superslicer_CJ9SsdQMmN" src="https://user-images.githubusercontent.com/76990913/106370372-b1228200-6359-11eb-9492-4ce2bd9690e9.png">
<img width="927" alt="superslicer_eHCfOdbuzi" src="https://user-images.githubusercontent.com/76990913/106370375-b2ec4580-6359-11eb-9b6b-b3416207e2f3.png">
<img width="594" alt="superslicer_XVfDYDP7q7" src="https://user-images.githubusercontent.com/76990913/106370378-bb448080-6359-11eb-9739-6fbb2b7f5666.png">

#### Project File (.3MF) where problem occurs

Also my extrusion multiplier is 0.4 because I'm printing foam, but this didn't seem to affect the outcome.
[Pointy1_2.zip](https://github.com/supermerill/SuperSlicer/files/5898923/Pointy1_2.zip)

Thanks x

**Comment by supermerill** [comment]
check you haven't a G92 in your layer change.
If it's the case, remove it or change to relative extrusion
