### ISSUE TITLE
Build from Source on Ubuntu - no text for calibration

### ISSUE THREAD

**Issue by dwmcqueen** [supermerill/SuperSlicer#933]
### Version
2.3.55.4

### Operating system type + version
Ubuntu 20.10

### 3D printer brand / version + firmware version (if known)
Ender 5

### Behavior
The text describing what to do on a calibration step isn't appearing. This is only happening on latest compiled from Github sources.   Using GTK-3 .

See - https://ibb.co/7N1GPqs

#### Project File (.3MF) where problem occurs
N/A - just try Calibration prints.

**Comment by Limb** [comment]
I'm seeing this as well. The content is actually there, the window is just being shrunk to its smallest possible size. If you resize the window you will see the content display.

I've tried looking for any regressions in wxWidget or recent PrusaSlicer/SuperSlicer commits that would cause this but have not found anything nor have I found a solution yet.
