### ISSUE TITLE
Speedup time issue

### ISSUE THREAD

**Issue by qwewer0** [supermerill/SuperSlicer#939]
### Versions

- 2.3.55.2
- 2.3.55.4

### Operating system type + version
Windows 10, 10.0.19042 Build 19042

### Behavior

1. _Speedup time_ (`fan_speedup_time`) always taken into account (unless zero), even if _Only for overhangs_ (`fan_speedup_overhangs`) is selected.
2. Both positive and negative values for _Speedup time_ (`fan_speedup_time`) has the same effect.

### Steps to reproduce
1. Generate a calibrating cube (or load a file)
2. Switch to _Fan speed_ view
3. See the fan speed differences

**Expected behavior**

1. By selecting _Only for overhangs_ (`fan_speedup_overhangs`) the _Speedup time_ (`fan_speedup_time`) should only be used for overhangs.
2. For _Speedup time_ (`fan_speedup_time`) a negative value should cause the fan speed change to occur sooner, and a positive value should cause the fan speed change to occur later.

**Actual behavior**
1. By selecting _Only for overhangs_ (`fan_speedup_overhangs`) the _Speedup time_ (`fan_speedup_time`) is used everywhere not just on overhangs.
2. For _Speedup time_ (`fan_speedup_time`) a negative value causes the fan speed change to occur sooner (as it should), but a positive value has the same effect.

**Screenshots**

**Speedup time = 0** (`fan_speedup_time`)
![bandicam 2021-02-02 18-32-05-327](https://user-images.githubusercontent.com/57561110/106639330-258d3900-6585-11eb-9d6d-e1a882430880.jpg)

**Speedup time = -1** (`fan_speedup_time`)
![bandicam 2021-02-02 18-31-55-261](https://user-images.githubusercontent.com/57561110/106639350-2d4cdd80-6585-11eb-86e1-4c3915a44629.jpg)

**Speedup time = 1** (`fan_speedup_time`)
![bandicam 2021-02-02 18-32-12-074](https://user-images.githubusercontent.com/57561110/106639364-2f16a100-6585-11eb-98d4-54f2b54e7a51.jpg)

#### Project File (.3MF) where problem occurs
[Shape-Box-3mf.zip](https://github.com/supermerill/SuperSlicer/files/5913087/Shape-Box-3mf.zip)

**Comment by 0x4d4e** [comment]
I can confirm that 'only for overhangs' is not taken into account. In addition, I noticed inconsistent behavior with fan_speedup_time/overhang detection which I think is related to this as well:

3s fan speedup (only overhangs true) - some overhangs are not 'detected' at all, front and backside differ in similar sections

Front
![image](https://user-images.githubusercontent.com/91870/111115246-a0724800-8564-11eb-9fb5-5edefe950c10.png)

Back
![image](https://user-images.githubusercontent.com/91870/111115316-b6800880-8564-11eb-8323-30ee28245823.png)


1s fan speedup (only overhangs true) - different 'pattern' - still differences between front and back
![image](https://user-images.githubusercontent.com/91870/111115517-0232b200-8565-11eb-813a-8a67d2ad9223.png)
![image](https://user-images.githubusercontent.com/91870/111115551-0e1e7400-8565-11eb-84df-782f67ed2be4.png)

In comparison, with fan speedup off:
![image](https://user-images.githubusercontent.com/91870/111115687-47ef7a80-8565-11eb-9b8d-8571dd0bedba.png)

**Comment by supermerill** [comment]
I'll rewrite it entirely in the new gcode writer later this year.

**Comment by gpread** [comment]
2.3.56.8

There is still a problem :-(  but its very close to working as intended/requested it seems! :-)

When "only for overhangs" is checked, currently its correctly adding the delay/advance (+/-) for only a single feature type but to the wrong one, its doing it for "Internal Bridge Infill" rather than "Overhang Perimeter"

**Comment by qwewer0** [comment]
Fixed.
