### ISSUE TITLE
macOs: Serif Font in buttons

### ISSUE THREAD

**Issue by jremen** [supermerill/SuperSlicer#940]
### Version
2.3.55.2

### Operating system type + version
macOS 11.2 (same on older)

### 3D printer brand / version + firmware version (if known)
irrelevant

### Behavior
* On macOs, some of the buttons have Serif font instead of default, sans serif one. It looks ugly. Prusaslicer doesn't have this issue
![superslicer_font_ugly](https://user-images.githubusercontent.com/7055428/106744121-a00a9700-661f-11eb-8b6a-e8e4c9d18d98.png)

**Comment by Stout001** [comment]
Strange. I use 3 different MacOS versions on 4 computers and the font is constant and not broken.

**Comment by ZhuJo** [comment]
Well it happens on two different computers. Tried to clean font cache, nope. 
New user account, nope.

**Comment by supermerill** [comment]
fixed by the merge
