### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by bakaufman** [supermerill/SuperSlicer#957]
### Version
_Version of SupserSlicer used goes here, Use `About->About SuperSlicer`_
default version - not running it, building it.

### Operating system type + version
_What OS are you using (and version)_
Mac OS X 10.15.7

### 3D printer brand / version + firmware version (if known)
_What 3D printer brand / version are you printing on, is it a stock model or did you modify the printer, what firmware is running on your printer, version of the firmware #s_
Irrelevant. 

### Behavior
Forked github, install brew requirements, compiled deps fine.
Compiled default SS with Make -j2 and failed with ```9 warnings generated.
[ 91%] Linking CXX static library liblibslic3r_gui.a
[ 91%] Built target libslic3r_gui
make: *** [all] Error 2```

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_
Irrelevant

**Comment by supermerill** [comment]
I'm using this [script](https://github.com/supermerill/SuperSlicer/blob/master/.github/workflows/ccpp_mac.yml) to compile on this [macos vm](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md)
