### ISSUE TITLE
overextrusion in vasemode

### ISSUE THREAD

**Issue by hkr955** [supermerill/SuperSlicer#960]
### Version
2.3.55

### Operating system type + version
linux ubuntu

### 3D printer brand / version + firmware version (if known)
ender 3 + Merlin

### Behavior
* when using "spiral Vase" there is an heavy over
[Shape-Cylinder.txt](https://github.com/supermerill/SuperSlicer/files/5986987/Shape-Cylinder.txt)
extrusion next to the seam.
* It seems to be a Superslicer specific issue
![image](https://user-images.githubusercontent.com/68788117/108033433-4ac58100-7034-11eb-9b51-2411fc10a949.png)
And the print looks exactly like the flow shown at the scrrenshot.
* In Prusaslicer 2.3.0 it looks like this:
* ![image](https://user-images.githubusercontent.com/68788117/108033659-a263ec80-7034-11eb-8e28-29ccafe7f4bd.png)
And prints ok.
* _Steps needed to reproduce the problem_
** open application
** Add a shape
** go to print settings  and add the tick for "spiral vase"
** slice the cylinder
** select view "volumetric flow rate"

 

#### Project File (.3MF) where problem occurs
_Upload a SuperSlicer Project File (.3MF) (`File -> Save` / `Save Project`)_

**Comment by JohanAR** [comment]
Looks like #730

**Comment by supermerill** [comment]
JohanAR is right, it's because of a little problem with G92 & absolute positioning.

I forgot to remove the G92 E0 from the custom gcode ->before layer. This shouldn't appear in the custom gcode, as it will mess up the internal extruder position.

**Comment by supermerill** [comment]
reopen it if it's still an issue
