### ISSUE TITLE
Feature request: print time estimate calibration

### ISSUE THREAD

**Issue by LaserBee** [supermerill/SuperSlicer#962]
So like a lot of people, I print using Octoprint. 

That's slower than using an SD card, so often the print times in the slicer are far less than the actual print time. 

What would be cool is if you could implement some sort of calibration AI, so I could enter the actual print time of an object after it had printed, and the slicer would "learn" how to calibrate it's estimates, based on the real-world data. 

I have absolutely no idea if this is possible!

**Comment by supermerill** [comment]
I don't have the time for that

I can show the time estimation compensation field if you're using octoprint (even on marlin), it's a simple % modifier. Is it enough?
