### ISSUE TITLE
The future of SuperSlicer

### ISSUE THREAD

**Issue by boromyr** [supermerill/SuperSlicer#968]
Hello, a quick question: has the development of SuperSlicer stopped or will there be future releases?
@supermerill

**Comment by liftbag** [comment]
supermerill has a broken computer since the beginning of the year. News should appear next week (source: discord superslicer channel)

**Comment by boromyr** [comment]
Perfect, thank you!

**Comment by supermerill** [comment]
there be future releases?

**Comment by freighttt** [comment]
> there be future releases

what on your computer has broken? i can donate an i7-7700k(lga 1151), if youre putting together a new build.

**Comment by supermerill** [comment]
@freighttt
 
Thx but I'm ok. Was more of a distraction, everything to reinstall & move, many hours & my daily routine was lost.
