### ISSUE TITLE
Feature request for expensive support - define interface extruder

### ISSUE THREAD

**Issue by bakaufman** [supermerill/SuperSlicer#971]
### Version
Doesn't matter

### Operating system type + version
Doesn't matter

### 3D printer brand / version + firmware version (if known)
Railcore dual extruder but applicable to multiextruder

### Behavior
I would like to define an extruder for my interface layer, which is $70/500g dissolvable filament. 
#### Project File (.3MF) where problem occurs
Not really needed.

**Comment by cab404** [comment]
> ### Version
> 
> Doesn't matter
> ### Operating system type + version
> 
> Doesn't matter
> ### 3D printer brand / version + firmware version (if known)
> 
> Railcore dual extruder but applicable to multiextruder
> ### Behavior
> 
> I would like to define an extruder for my interface layer, which is $70/500g dissolvable filament.
> #### Project File (.3MF) where problem occurs
> 
> Not really needed.
![image](https://user-images.githubusercontent.com/6453661/108639114-e24b2980-74a3-11eb-8c55-f72c85a877ce.png)

**Comment by cab404** [comment]
You can close this issue)
