### ISSUE TITLE
Cost & Weight is not displayed in Sliced Info Settings (and re-slice does not work) 

### ISSUE THREAD

**Issue by DaStivi** [supermerill/SuperSlicer#972]
### Version
2.3.55.5 (updated right now to latest available 3b253f3bb4be85c000f5f5f878ba2e4cb396e246)

### Operating system type + version
Win10 21H2

### Behavior
added costs and weight of filament but does not show up in Sliced Info...
![image](https://user-images.githubusercontent.com/7464802/108727725-2af8f600-7529-11eb-96f7-4174772b3b7f.png)

Also noticed that Re-Slicing doesn't work, so hitting either CTRL-R or even from the file-menu -> "(Re)Slice now" does not reslic it?! there has to be some change made, after the sliced ?!

### should look like:
![image](https://user-images.githubusercontent.com/7464802/108727304-b7ef7f80-7528-11eb-9c15-25a1e461405e.png)

**Comment by supermerill** [comment]
![image](https://user-images.githubusercontent.com/6536403/108741995-8f22b680-7537-11eb-8a0b-6ad7db3a559a.png)
could not reproduce,
 .3mf / project file?

**Comment by neophyl** [comment]
You also need the density in the filament settings for the cost and weight to work. At least you do with Prusa Slicer now so I should think it is the same.

**Comment by DaStivi** [comment]
> You also need the density in the filament settings for the cost and weight to work. At least you do with Prusa Slicer now so I should think it is the same.

that was exactly the issue... thx for pointing me too this... entering the density and costs and weight is displayed!
