### ISSUE TITLE
Flow Calibration doesn't disable Ironing Post Process

### ISSUE THREAD

**Issue by BenWhite27** [supermerill/SuperSlicer#978]
### Version
2.3.55.5

### Operating system type + version
Windows 10 20H2

### 3D printer brand / version + firmware version (if known)
Modified CR-10S running Klipper.

### Behavior
When performing a flow calibration the new Ironing Post Process isn't disabled in the printer profile.  This results in ironing the top layer twice, once with the Ironing infill option and another time with the post process.

![Slicer calibration ironing issue](https://user-images.githubusercontent.com/7678016/109141116-46484900-7755-11eb-8d32-b9057741078a.gif)

As this calibration is intended to work with the original ironing option it might be best to alter the Print Settings for the print.

#### Project File (.3MF) where problem occurs
[filament_flow_test.zip](https://github.com/supermerill/SuperSlicer/files/6042317/filament_flow_test.zip)

**Comment by ndaman** [comment]
I've been following SupeerSlicer's calibration process and I'm curious if this is causing an issue. The flow that looks the best on the top is quite low (~75%) and it leaves visible gaps in the first layer. Is there any way to manually fix this or should I use a different calibration method in the meantime?

**Comment by supermerill** [comment]
It's an issue, as the ironing post-process will hide top defects used to evaluate the flow.

**Comment by reinux** [comment]
I'm having this issue in 2.5.59. I'm not able to disable it manually either.
