### ISSUE TITLE
Directory name inside zip files is pointing to wrong version

### ISSUE THREAD

**Issue by coredump** [supermerill/SuperSlicer#980]
### Version
2.3.55.5

### Operating system type + version
Win64 / Linux

### Behavior
I use a `scoop`  [manifest](https://github.com/coredump/scoop_bucket/blob/master/superslicer.json) to install/update superslicer. Latest version [(2.3.55.5)](https://github.com/supermerill/SuperSlicer/releases/tag/2.3.55.5) has the folder name inside the zip file as `SuperSlicer_2.2.53.5_win64_20210223` instead of matching the file name `SuperSlicer_2.3.55.5_win64_20210223.zip`

That breaks the `scoop` auto installation and probably some other tools that depend on consistent naming. I checked the older pre-releases and they seem fine, so it must be a thing on the latest one.

**Comment by supermerill** [comment]
yes, it was a mistake on my part.
Sorry on that, I'll triple check next time.
