### ISSUE TITLE
One Perimeter on Top Surface Detection Failing

### ISSUE THREAD

**Issue by BlueDragonX** [supermerill/SuperSlicer#984]
### Version
2.3.55.5

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
Voron v2.4

### Behavior
The "one perimeter on top surface" detection is broken for the [80t gear](https://github.com/VoronDesign/Mobius-Extruder/blob/master/STLs/%5Ba%5D_80t_gear.stl) on the Voron M4 extruder. Enabling this causes the gear teeth to only have a single perimeter. The rest of the walls have the appropriate number of perimeters. Disabling this feature fixes the problem. Pic:

![80t_single_top_perimeter](https://user-images.githubusercontent.com/465340/109430740-b229ec00-79b7-11eb-9283-881e29d60485.png)

#### Project File (.3MF) where problem occurs
[[a]_80t_gear.zip](https://github.com/supermerill/SuperSlicer/files/6057792/a._80t_gear.zip)

**Comment by CCS86** [comment]
I notices this too, where that setting causes a single external perimeter and sparse infill, when it should be the normal amount of perimeters.

**Comment by BlueDragonX** [comment]
I've been able to reproduce this on a number of other STL files. Any idea what might be causing this?
