### ISSUE TITLE
Thumbnails are not saved (2.3.55.5)

### ISSUE THREAD

**Issue by msource** [supermerill/SuperSlicer#986]
### Version
2.3.55.5

### Operating system type + version
Windows 10 (20H2)

### 3D printer brand / version + firmware version (if known)
Sapphire Pro / SKR 1.4 Turbo + Klipper

### Behavior
When trying to save the thumbnail values if we close and open the SuperSlicer again, the values are 0. It's not saving the correct information.

#### Project File (.3MF) where problem occurs
Using standard Voron profile and changing only the necessary things.

**Comment by neophyl** [comment]
Duplicate of #979
