### ISSUE TITLE
Angel cost and Travel cost affect to rear seem position

### ISSUE THREAD

**Issue by FillPavS** [supermerill/SuperSlicer#988]
### Version
2.3.55.5

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
UlTi Steel / klipper

When choosing the position of the rear seam, the parameters Angel cost and Travel cost continue to affect, although they are inactive. If I leave there the default setting (100), the seam is not always going to be back, but if I switch to cost-Based and to set the values in these fields to 0, and then click rear seam position, he begins to work as it should.

https://www.youtube.com/watch?v=yG7l7GpFwaU

![29](https://user-images.githubusercontent.com/17209082/109483445-4cf5f980-7a90-11eb-9636-81d61ff4bd0b.png)
![30](https://user-images.githubusercontent.com/17209082/109483521-65661400-7a90-11eb-85fd-eb5e48b04b4a.png)
![32](https://user-images.githubusercontent.com/17209082/109483532-68f99b00-7a90-11eb-87c0-d60ce6c58c31.png)
![31](https://user-images.githubusercontent.com/17209082/109483540-6bf48b80-7a90-11eb-846f-d378aeb763dd.png)

**Comment by supermerill** [comment]
Can't reproduce, please give me your (zipped) project file.

**Comment by FillPavS** [comment]
> Can't reproduce, please give me your (zipped) project file.

if still relevant
[seam_position_bug.zip](https://github.com/supermerill/SuperSlicer/files/6161356/seam_position_bug.zip)

in this version the problem is solved - https://github.com/supermerill/SuperSlicer/actions/runs/661956829

Thanks for your work
