### ISSUE TITLE
[2.3.55.5] Number of perimeter is not respected

### ISSUE THREAD

**Issue by elpopo-eng** [supermerill/SuperSlicer#991]
### Version
2.3.55.5

### Operating system type + version
Win10

### 3D printer brand / version + firmware version (if known)
N/A

### Behavior
Number of perimeter is not respected in the 2.3.55.5 compared to 2.3.55.3

![image](https://user-images.githubusercontent.com/68954733/109775321-a7629780-7c01-11eb-9e2f-6990b6e713f1.png)

#### Project File (.3MF) where problem occurs
[Pb_Perimeter.zip](https://github.com/supermerill/SuperSlicer/files/6074509/Pb_Perimeter.zip)

**Comment by Pavulon87** [comment]
Disable "Only one perimeter on Top surfaces" and try again.

**Comment by elpopo-eng** [comment]
It works with one perimter on top surface disabled.

**Comment by linux-paul** [comment]
Also in my case
![2](https://user-images.githubusercontent.com/34230387/110544479-140ef200-812c-11eb-9a44-f383170900b7.png)
