### ISSUE TITLE
[2.3.55.5] Broken thin walls on 0.2 Initial Layer Height

### ISSUE THREAD

**Issue by jesterhead82** [supermerill/SuperSlicer#995]
### Version
2.3.55.5

### Operating system type + version
Win10

### 3D printer brand / version + firmware version (if known)
CR10V2 / Marlin 2.X

### Behavior
- Unconnected thin walls
- Inconsistent width on thin walls

Only on Initial Layer Height 0.2, works e.g. on 0.32 or 0.16

- Initial Layer Height 0.2 (broken)
![image](https://user-images.githubusercontent.com/11690785/109970064-eb829480-7cf4-11eb-93bf-5385c44106d4.png)

-Initial Layer height 0.32 (works)
![image](https://user-images.githubusercontent.com/11690785/109970211-12d96180-7cf5-11eb-9785-6b6c5e02356e.png)

- Initial Layer height: 0.16 (works)
![image](https://user-images.githubusercontent.com/11690785/109970729-b0349580-7cf5-11eb-8de4-f253f33bc5ae.png)

#### Project File (.3MF) where problem occurs
[Rear Door Outer Frame_0.20InitialLayer.3mf.zip](https://github.com/supermerill/SuperSlicer/files/6083922/Rear.Door.Outer.Frame_0.20InitialLayer.3mf.zip)

**Comment by supermerill** [comment]
![Uploading image.png…]()

**Comment by jesterhead82** [comment]
Hi,

it's visible on the two larger parts, right side of the bed, even in your screenshot:

![image](https://user-images.githubusercontent.com/11690785/110253916-00795500-7f8d-11eb-83c3-4443c4996608.png)

**Comment by supermerill** [comment]
Found it, very hard bug to understand as it's deep inside the boost lib.
As I can't really fix it, I've added a mitigation process: if the lines from boost voronoi are off, then offset the lines a bit and try again.

**Comment by sttts** [comment]
First I thought this is the problem I see, but it isn't, though connected to thin walls too:

<img width="732" alt="Bildschirmfoto 2021-03-30 um 00 22 57" src="https://user-images.githubusercontent.com/730123/112907422-20b0b580-90ee-11eb-85e8-d1f3467b6cbc.png">

As you see with the lower object: perimeter 4 for vertical walls. But the thin wall is hollow, only infill (13%).

The same object with the same profile with 2.2 I get solid walls, as expected:

<img width="681" alt="Bildschirmfoto 2021-03-30 um 00 23 01" src="https://user-images.githubusercontent.com/730123/112907452-2dcda480-90ee-11eb-98a9-e97fb4fc31de.png">

**Comment by sttts** [comment]
Maybe https://github.com/supermerill/SuperSlicer/issues/991.
