### ISSUE TITLE
Issue #596 is back with version 2.3.55.5

### ISSUE THREAD

**Issue by knickohr** [supermerill/SuperSlicer#996]
https://github.com/supermerill/SuperSlicer/issues/596

**Comment by supermerill** [comment]
Can't reproduce, can you send me a project file that highlight it?

**Comment by lolorc** [comment]
confirmed here "set temperature", "wait for temperature to be reached" and "set bed temperature and wait for it to be reached" are set after the custom gcodes used for priming and stuff..
