### ISSUE TITLE
request horizontal expansion for hole only

### ISSUE THREAD

**Issue by tjengbudi** [supermerill/SuperSlicer#998]
hello,
it really nice to have object printed with exactly the same dimension of my model design. i have calibrated my printer, my object square is calibrated. my filament extruder is calibrated also. but when i desain i block with a hole i cannot plug it nicely even i added 0.1 in my design. i slice it with s3d before and found nothing about horizontal expansion

so i try another slicer. i got prusaslicer, superslicer and cura. i have better printing with super slicer so i ask this. and i have very bad slicing with cura. but cura have hole horizontal expansion so i request this if any option to add this feature.

with xy horizontal expansion my outer dimension is changing also. outer dimension is priority. so i need to not changing the outer dimension. 

please let me know if this option possible to add in the future

thanks a lot

**Comment by neophyl** [comment]
This already is there.  Under Print Settings>Slicing
Vertical Hole Shrinking Compensation.  You have a few options, convert to poly holes, or the XY compensation with its associated threshold value.

**Comment by tjengbudi** [comment]
oops my bad. thanks for the clarification.

**Comment by kikomansi** [comment]
I am confused on how this work. Can someone guide me?
